{bio}[intel/2019b] Pychopper v2.3.1 w/ Python 3.7.4
easybuilders/easybuild-easyconfigs pull request #10344
Opened 2020-04-07 10:53 UTC by boegel

(created using `eb --new-pr`)

2020-04-07 11:00 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
generoso - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, Python 3.6.8
See https://gist.github.com/37392166b56f491a1ac1714d34c2be11 for a full test report.

2020-04-07 11:01 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3127.skitty.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/b2796880b37e02f45c396d8bfe8109f3 for a full test report.

2020-04-07 21:30 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 6 (1 easyconfigs in this PR)
node150.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/f0dc452c23b94251b07dad695a9bd9eb for a full test report.

2020-04-08 09:05 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
node150.hydra.os - Linux centos linux 7.7.1908, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/4b2b90374d91db55a4862abfb34c56ca for a full test report.

2020-04-08 09:19 UTC, lexming submitted a review, later dismissed
Works well, I would just make the following minor change

2020-04-08 09:19 UTC, lexming commented on easybuild/easyconfigs/p/Pychopper/Pychopper-2.3.1-intel-2019b-Python-3.7.4.eb
> +
These `sanity_check_paths` can be removed as they are default in a PythonBundle
```suggestion
```

2023-06-23 15:48 UTC, branfosj commented
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/branfosj/cc0202ba471e3ad94b3a1e146db44175 for a full test report.

2023-06-23 15:57 UTC, branfosj requested changes
Use existing `python-parasail` and `tqdm` deps.

2023-06-23 15:57 UTC, branfosj commented on easybuild/easyconfigs/p/Pychopper/Pychopper-2.3.1-intel-2019b-Python-3.7.4.eb
> +    ('Seaborn', '0.10.0', versionsuffix),
```suggestion
    ('python-parasail', '1.2', versionsuffix),
    ('Seaborn', '0.10.0', versionsuffix),
    ('tqdm', '4.41.1'),
```

2023-06-23 15:58 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/branfosj/d5f4a1d5b595647071ba33434691563f for a full test report.

2023-06-23 15:59 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/branfosj/ccc2311b1021f4caca27245146bb9483 for a full test report.

2023-06-23 16:14 UTC, branfosj approved these changes

2023-06-23 16:21 UTC, branfosj commented
Going in, thanks @boegel!

2023-06-23 16:21 UTC, merged