{bio}[system/system] PIPITS v2.7
easybuilders/easybuild-easyconfigs pull request #10558
Opened 2020-05-01 07:54 UTC by bedroge

(created using `eb --new-pr`)

2020-05-01 09:37 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
build.hpc.rug.nl - Linux centos linux 7.4.1708, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/3e189708ea5263193ab5c0807e08d469 for a full test report.

2020-05-16 07:44 UTC, boegel commented
`conda` is an easy escape here in the short term, but this is likely going to break in the not so distant future, since there's very little version restrictions on the dependencies.

I'm not sure how much of a mess this would be, but maybe trying a `PythonBundle` is worth a shot?

The documentation is rather poor, but the dependencies are listed in https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pipits/meta.yaml.

2020-05-20 15:16 UTC, bedroge commented
I went for the easy solution due to a lack of time ;-)
Maybe I'll have another look at this when I have some more time.

2020-10-20 08:56 UTC, bedroge commented
Test report by @bedroge
**FAILED**
Build succeeded for 5 out of 7 (4 easyconfigs in this PR)
build.hpc.rug.nl - Linux centos linux 7.4.1708, x86_64, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/4f405a78e765453c454bb0acdd77fc06 for a full test report.

2020-10-20 09:10 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 7 out of 7 (4 easyconfigs in this PR)
build.hpc.rug.nl - Linux centos linux 7.4.1708, x86_64, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/3db6eaec97221c5320c26b95cc422fa3 for a full test report.

2020-10-20 09:39 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 8 out of 8 (5 easyconfigs in this PR)
build.hpc.rug.nl - Linux centos linux 7.4.1708, x86_64, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/8c3020e4abff2e7ffa0b83953ba52565 for a full test report.

2020-10-20 11:27 UTC, bedroge commented
@boegel I changed this from a Conda installation to an installation from source. It also includes version bumps for some existing easyconfigs (HMMER, RDP-Classifier, VSEARCH) and a new one (ITSx).

2020-10-20 11:45 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 8 out of 8 (5 easyconfigs in this PR)
build.hpc.rug.nl - Linux centos linux 7.4.1708, x86_64, Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/73ef587eacd52f94ca353956dfb1d42f for a full test report.

2021-02-17 14:53 UTC, boegel requested changes

2021-02-17 14:53 UTC, boegel commented on easybuild/easyconfigs/i/ITSx/ITSx-1.1.2-GCCcore-9.3.0.eb
> +    'files': ['ITSx'],
We like to have sanity check commands like "`ITSx --help`" or so, would that work here?

2021-02-17 14:53 UTC, boegel commented on easybuild/easyconfigs/p/PIPITS/PIPITS-2.7-foss-2020a-Python-3.8.2.eb
> +    'files': ['bin/%s' % x for x in ['pipits_funits', 'pipits_process',
Maybe add a sanity check command for one of these?

2021-02-17 14:53 UTC, boegel commented on easybuild/easyconfigs/v/VSEARCH/VSEARCH-2.15.0-GCC-9.3.0.eb
> +    'files': ['bin/vsearch'],
Same here, add sanity check command?

2021-02-17 16:32 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (4 easyconfigs in total)
node3544.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/acdd4cccd71a6898fa5c8b5d0cbf2783 for a full test report.

2021-02-17 16:33 UTC, boegel commented
@boegelbot please test @ generoso

2021-02-17 16:33 UTC, boegel approved these changes

2021-02-17 16:35 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (4 easyconfigs in total)
node3108.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/9851bf7bedf69d77782e43008297dca2 for a full test report.

2021-02-17 16:36 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (4 easyconfigs in total)
node2614.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/998f6c4ffb646a3fa785ec571d6af4eb for a full test report.

2021-02-17 16:40 UTC, boegel commented
Going in, thanks @bedroge!

2021-02-17 16:40 UTC, merged