{bio}[GCC/9.3.0] blasr_libcpp v5.3.4
easybuilders/easybuild-easyconfigs pull request #11108
Opened 2020-08-13 14:06 UTC by mboisson

(created using `eb --new-pr`)

2020-08-13 15:12 UTC, mboisson commented
Ah, I guess this can also not be lower than the MPI level because of the HDF5 dependency ? @boegel

2020-08-20 20:18 UTC, mboisson commented
This PR requires HDF5.Serial (https://github.com/easybuilders/easybuild-easyconfigs/pull/11155) and Boost.Serial (https://github.com/easybuilders/easybuild-easyconfigs/pull/11145)

2020-08-20 20:47 UTC, mboisson commented
Mmm, I don't know what this failed check means : 
```AssertionError: ['sanity_pip_check is enabled in cram-0.7-GCCcore-9.3.0.eb'] is not false : sanity_pip_check is enabled in cram-0.7-GCCcore-9.3.0.eb```

2023-06-21 13:25 UTC, bartoldeman commented
Reopen to re-run checks

2023-06-28 06:33 UTC, akesandgren commented
This one depends on HDF5.Serial and Boost.Serial which are not in devel, they where merged to dual_serial_mpi branch.

2023-06-28 06:34 UTC, akesandgren requested changes

2023-06-28 06:34 UTC, akesandgren commented on easybuild/easyconfigs/c/cram/cram-0.7-GCCcore-9.3.0.eb
> +use_pip = True
missing
```
sanity_pip_check = True
```
here

2023-10-23 07:22 UTC, akesandgren commented
Closing this PR, since it (only) uses deprecated toolchain versions,
see https://docs.easybuild.io/policies/toolchains .

2023-10-23 07:22 UTC, closed without merging