{compiler}[GCCcore/9.3.0] almosthere v1.0.10, limix-bgen v3.0.3
easybuilders/easybuild-easyconfigs pull request #11152
Opened 2020-08-20 19:11 UTC by mboisson

(created using `eb --new-pr`)

2020-08-20 23:02 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 21 out of 21 (2 easyconfigs in this PR)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.5
See https://gist.github.com/c91ba431519d2f4b32f818d1015609fb for a full test report.

2020-08-21 08:22 UTC, verdurin commented
@mboisson could you upload a test report?

2020-08-24 08:14 UTC, verdurin commented
Thanks @zao 

@mboisson here's how you do it: `eb --from-pr=<PR number> --debug --robot --upload-test-report`, the latter being the key one.

2020-08-24 14:06 UTC, mboisson commented
Test report by @mboisson
**SUCCESS**
Build succeeded for 0 out of 0 (2 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/7c888f6010b777930d2edf9957e0c9a8 for a full test report.

2020-08-24 14:09 UTC, mboisson commented
Test report by @mboisson
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in this PR)
build-node.computecanada.ca - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.7.7
See https://gist.github.com/8c78ecb69afe953033f6361dacba1f1d for a full test report.

2020-08-24 14:10 UTC, mboisson commented
Yeah, that won't work.... `binutils` recipes don't work on our system, and we filter them out, but the test report seems to want to include them...

2020-08-24 14:12 UTC, verdurin commented
Thanks anyway @mboisson - I can go with the build from @zao

2020-08-24 14:17 UTC, verdurin requested changes

2020-08-24 14:17 UTC, verdurin commented on easybuild/easyconfigs/a/almosthere/almosthere-1.0.10-GCCcore-9.3.0.eb
> +    'files': ['lib/libathr.so', 'include/athr.h'],
@mboisson Please use `SHLIB_EXT`, see e.g. https://github.com/easybuilders/easybuild-easyconfigs/blob/9c43fb52e7a393b54b7a98255d2f17e537eab6f9/easybuild/easyconfigs/p/PostgreSQL/PostgreSQL-12.4-GCCcore-9.3.0.eb#L46

2020-08-24 14:17 UTC, verdurin commented on easybuild/easyconfigs/l/limix-bgen/limix-bgen-3.0.3-GCCcore-9.3.0.eb
> +    'files': ['lib/libbgen.so', 'include/bgen.h'],
@mboisson same as above, please use `SHLIB_EXT`.

2020-08-24 14:19 UTC, mboisson commented on easybuild/easyconfigs/l/limix-bgen/limix-bgen-3.0.3-GCCcore-9.3.0.eb
> +    'files': ['lib/libbgen.so', 'include/bgen.h'],
done

2020-08-24 14:20 UTC, mboisson commented on easybuild/easyconfigs/a/almosthere/almosthere-1.0.10-GCCcore-9.3.0.eb
> +    'files': ['lib/libathr.so', 'include/athr.h'],
done

2020-08-24 22:54 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/91a674acf4d820e1448d6f5b96ed9f27 for a full test report.

2020-08-24 22:54 UTC, verdurin approved these changes

2020-08-24 22:55 UTC, verdurin commented
Going in, thanks @mboisson!

2020-08-24 22:55 UTC, merged