{bio}[iccifort/2020.1.217] fastp v0.20.1
easybuilders/easybuild-easyconfigs pull request #11164
Opened 2020-08-26 14:15 UTC by boegel

(created using `eb --new-pr`)

2020-08-26 14:15 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3114.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/076858ed4698cefa2957e0bb347cd520 for a full test report.

2020-08-26 14:16 UTC, boegel commented
@boegelbot please test @ generoso

2020-08-26 14:16 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2400.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/fec8400939ee06b4cdefd335a98d37ed for a full test report.

2020-08-28 08:32 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node368.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/4cfe02e52a44519b8b86d010234ee69e for a full test report.

2020-08-28 08:32 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node126.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/6c3627ac91db666aa2369b6c456f137e for a full test report.

2020-08-28 12:49 UTC, lexming requested changes

2020-08-28 12:49 UTC, lexming commented on easybuild/easyconfigs/f/fastp/fastp-0.20.1-iccifort-2020.1.217.eb
> +
There is a missing dependency on `zlib`
```suggestion

dependencies = [
    ('zlib', '1.2.11'),
]

```

2020-08-28 12:49 UTC, lexming commented on easybuild/easyconfigs/f/fastp/fastp-0.20.1-iccifort-2020.1.217.eb
> +    'files': ['bin/fastp'],
Blasphemy! `files` always goes before `dirs`
```suggestion
    'files': ['bin/fastp'],
    'dirs': [],
```

2020-08-28 12:49 UTC, lexming commented on easybuild/easyconfigs/f/fastp/fastp-0.20.1-iccifort-2020.1.217.eb
> +source_urls = ['https://github.com/OpenGene/fastp/archive/']
Just for consistency with the previous easyconfig of `fastp`
```suggestion
# https://github.com/OpenGene/fastp
github_account = 'OpenGene'
source_urls = [GITHUB_SOURCE]
```

2020-09-08 08:49 UTC, verdurin commented
@boegel ping on the requested changes?

2023-06-23 18:28 UTC, branfosj commented
@boegelbot please test @ generoso

2023-06-23 18:50 UTC, branfosj approved these changes

2023-06-23 18:52 UTC, branfosj commented
Going in, thanks @boegel!

2023-06-23 18:52 UTC, merged