{mpi}[GCC/9.3.0] OpenMPI v4.0.5
easybuilders/easybuild-easyconfigs pull request #11167
Opened 2020-08-27 19:31 UTC by boegel

(created using `eb --new-pr`)

2020-08-27 19:33 UTC, boegel commented
@boegelbot please test @ generoso

2020-08-27 19:43 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/59f1ed0967daa0bd2272cae7bc83ee5d for a full test report.

2020-08-27 19:57 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2437.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/8a060178464528a32553bea0e71ea9dd for a full test report.

2020-08-28 08:08 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node368.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/505d170b53732572e96785eeaf59835b for a full test report.

2020-08-28 09:29 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node114.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/ba82612bd6f0eed6b20c48ed8850c066 for a full test report.

2020-08-28 12:27 UTC, lexming requested changes

2020-08-28 12:27 UTC, lexming commented on easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.5-GCC-9.3.0.eb
> +
Our old friend `pkg-config` is missing
```suggestion

builddependencies = [
    ('pkg-config', '0.29.2'),
]

```

2020-08-28 12:27 UTC, lexming commented on easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.5-GCC-9.3.0.eb
> +    ('UCX', '1.8.0'),
Time to fix the oversight on `libevent`
```suggestion
    ('libevent', '2.1.11'),
    ('UCX', '1.8.0'),
```

2020-09-09 19:30 UTC, boegel commented
@boegelbot please test @ generoso

2020-09-09 19:40 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/84de3d94b5745f903f43359c6e015029 for a full test report.

2020-09-09 19:43 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3152.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/95083bc21c285c1da199d7bfac092cfa for a full test report.

2020-09-10 08:48 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.5
See https://gist.github.com/2f90924791820f32f138b76b2cb725a0 for a full test report.

2020-09-10 08:51 UTC, verdurin approved these changes
Looks fine.

2020-09-10 08:51 UTC, verdurin commented
Going in, thanks @boegel!

2020-09-10 08:51 UTC, merged