add fontconfig as direct dep for Qt5
easybuilders/easybuild-easyconfigs pull request #11183
Opened 2020-08-30 07:54 UTC by boegel

(created using `eb --new-pr`)

2020-08-30 08:01 UTC, boegel commented
@boegelbot please test @ generoso
EB_ARGS=--rpath --installpath /tmp/pr11183

2020-08-30 11:25 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/d83076d539c5d0db7f94c06b82122d8f for a full test report.

2020-08-30 13:26 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2457.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/4219bdf3a4d71dc93d3bc7bfb436453c for a full test report.

2020-08-30 13:36 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3149.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/299b6812a1da46f3a0e11e6928d96a4a for a full test report.

2020-08-30 16:19 UTC, boegel commented
@boegelbot please test @ generoso
EB_ARGS=--rpath --installpath /tmp/pr11183

2020-08-30 21:52 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node2457.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/ff74d32cd73ad17a2a1818fe54a79025 for a full test report.

2020-08-30 21:52 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
node3149.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/ea3dafeba9ef7adb902929a97c434b89 for a full test report.

2020-08-31 12:32 UTC, ocaisa requested changes

2020-08-31 12:32 UTC, ocaisa commented on easybuild/easyconfigs/q/Qt5/Qt5-5.12.3-GCCcore-8.2.0.eb
> +    ('bzip2', '1.0.6'),
Missing `fontconfig/2.13.1` dep here

2020-08-31 13:13 UTC, ocaisa approved these changes

2020-08-31 13:13 UTC, merged

2020-08-31 14:05 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2700.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/77e3ab051619dfdb5d53311555677ff4 for a full test report.