{devel}[GCCcore/9.3.0] PySide2 v5.14.1, Shiboken2 v5.14.1 w/ Python 3.8.2
easybuilders/easybuild-easyconfigs pull request #11199
Opened 2020-09-02 17:30 UTC by SimonPinches

(created using `eb --new-pr`)

2020-09-08 08:45 UTC, verdurin commented
@SimonPinches could you take a look at the issues raised by the tests please?

2020-10-21 15:42 UTC, SimonPinches commented
@verdurin I've added `bintutils` build dependencies as mentioned in the test issues but I might need some clues if more is needed...

2023-06-28 14:21 UTC, akesandgren requested changes

2023-06-28 14:21 UTC, akesandgren commented on easybuild/easyconfigs/p/PySide2/PySide2-5.14.1-GCCcore-9.3.0-Python-3.8.2.eb
> +
need
sanity_pip_check = True
here

2023-06-28 14:21 UTC, akesandgren commented on easybuild/easyconfigs/s/Shiboken2/Shiboken2-5.14.1-GCCcore-9.3.0-Python-3.8.2.eb
> +
need
sanity_pip_check = True
here

2023-10-23 07:23 UTC, trz42 commented
Closing this PR, since it (only) uses deprecated toolchain versions (GCC/9.3.0),
see https://docs.easybuild.io/policies/toolchains .

Also ...
- If a new PR for this software with a supported toolchain is opened, the minor comments about sanity checks should be taken into account.

2023-10-23 07:29 UTC, closed without merging

2023-10-23 07:29 UTC, boegel commented
Also worth mentioning: a newer version of `PySide2` was merged in https://github.com/easybuilders/easybuild-easyconfigs/pull/13460