{tools,vis}[foss/2019a] Sphinx v1.8.3, Spyder v4.1.5 w/ Python 3.7.2
easybuilders/easybuild-easyconfigs pull request #11278
Opened 2020-09-15 13:07 UTC by zarybnicky

(created using `eb --new-pr`)

2020-09-15 15:37 UTC, boegel requested changes

2020-09-15 15:37 UTC, boegel commented on easybuild/easyconfigs/s/Sphinx/Sphinx-1.8.3-foss-2019a-Python-3.7.2.eb
> +sanity_pip_check = False
@zarybnicky The error message in the tests is a bit confusing, but this should be `sanity_pip_check = True`.

We want to run `pip check` in the sanity check step to ensure that all required dependencies for Sphinx are installed.

2020-09-15 15:37 UTC, boegel commented on easybuild/easyconfigs/s/Spyder/Spyder-4.1.5-foss-2019a-Python-3.7.2.eb
> +sanity_pip_check = False
Same here, should be `sanity_pip_check = True`

2020-09-15 15:38 UTC, boegel commented
@zarybnicky I don't see a relation between Sphinx and Spyder, since Spyder doesn't depend on Sphinx (but installs Sphinx 3.2.1 as an extension to Spyder)? Maybe I'm overlooking something...

2020-09-15 15:57 UTC, zarybnicky commented
@boegel As far as setup.py is concerned, sphinx is a dependency and part of the Help plugin: https://github.com/spyder-ide/spyder/blob/26227419e9c34a9a19a8316e0d4bd1ca55698013/setup.py#L246 But perhaps it should not be a standalone recipe but just a extension?

2020-09-15 19:39 UTC, zarybnicky commented
Don't close - while everything works in the resulting Spyder build, pip check found a few inconsistencies. I guess I'm not a good dependency resolver if there are more than a hundred deps to juggle...

2020-09-16 09:25 UTC, boegel commented
> @boegel As far as setup.py is concerned, sphinx is a dependency and part of the Help plugin: https://github.com/spyder-ide/spyder/blob/26227419e9c34a9a19a8316e0d4bd1ca55698013/setup.py#L246 But perhaps it should not be a standalone recipe but just a extension? I just updated the old Sphinx recipe to 2019a

If we have easyconfigs for `Sphinx` already, we indeed might as well update them and use them as a dependency for other stuff like `Spyder` (as opposed to installing `Sphinx` as an extension). But why the difference in Sphinx version, why not update the easyconfig to the latest `Sphinx` version?

2020-09-22 10:28 UTC, closed without merging

2020-09-22 10:28 UTC, zarybnicky commented
Will open a new one with just Spyder, don't want to confuse `eb --edit-pr` :man_shrugging: