{bio}[GCCcore/9.3.0] MUMmer v3.23
easybuilders/easybuild-easyconfigs pull request #11349
Opened 2020-09-23 15:29 UTC by boegel

(created using `eb --new-pr`)

2020-09-23 16:10 UTC, boegel commented
@boegelbot please test @ generoso

2020-09-23 16:57 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node371.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/17fd414c8161fb9c789b8262482782cc for a full test report.

2020-09-23 18:39 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2602.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/7bce7ee8c408303adc835b2dd329f754 for a full test report.

2020-09-23 19:43 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node124.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/a717ffd474e3cf736b79a52b09628147 for a full test report.

2020-09-24 08:05 UTC, lexming submitted a review, later dismissed
LGTM

2020-09-24 08:06 UTC, lexming commented
@boegel there are issues in CentOS 8 related to UTF-8, is that a blocker for you?

2020-09-24 12:19 UTC, boegel commented
@lexming That actually signals a bug in the MUMmer easyblock which is also relevant fro EasyBuild framework (because the MUMmer easyblock should be using `apply_regex_substitutions`, but that currently suffers from the same problem).

I'll look into fixing this, lets keep this open as a reminder...

2020-09-24 12:21 UTC, boegel commented
Just to expose the problem a bit more: fails when running EasyBuild on top of Python 3 with:

```
ERROR: Traceback (most recent call last):
  File "/lib/python2.7/site-packages/easybuild_framework-4.3.1.dev0-py2.7.egg/easybuild/main.py", line 115, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/lib/python2.7/site-packages/easybuild_framework-4.3.1.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 3301, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/lib/python2.7/site-packages/easybuild_framework-4.3.1.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 3204, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/lib/python2.7/site-packages/easybuild_framework-4.3.1.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 3059, in run_step
    step_method(self)()
  File "/lib/python2.7/site-packages/easybuild_easyblocks-4.3.1.dev0-py2.7.egg/easybuild/easyblocks/m/mummer.py", line 79, in install_step
    for line in fileinput.input(fil, inplace=1, backup='.orig.eb'):
  File "/usr/lib64/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/usr/lib64/python3.6/fileinput.py", line 364, in _readline
    return self._readline()
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 24: invalid start byte
```

2020-09-24 12:46 UTC, boegel commented
@lexming Framework issue fixed in https://github.com/easybuilders/easybuild-framework/pull/3450, MUMmer easyblock updated to leverage `apply_regex_substitutions` and fix the issue that arose here when running EasyBuild on top of Python 3.

2020-09-24 12:59 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2636.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/558586d1a6ae2d331fbb2b2aad350747 for a full test report.

2020-10-06 17:42 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.5
See https://gist.github.com/c0872f2ab0966b7b5de07006a263bbaa for a full test report.

2020-10-06 17:44 UTC, verdurin requested changes

2020-10-06 17:44 UTC, verdurin commented on easybuild/easyconfigs/m/MUMmer/MUMmer-3.23-GCCcore-9.3.0.eb
> +# easyblock = mummer.py
@boegel please re-instate the previous credits, old though they may be...

2020-10-07 07:47 UTC, zao commented
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
freja - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.2
See https://gist.github.com/0353207977306b5b72a595b957590906 for a full test report.

2020-10-14 19:23 UTC, boegel commented
@boegelbot please test @ generoso

2020-10-14 19:31 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3401.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/6307ed92581f9d0ddb4d070123fa8325 for a full test report.

2020-10-14 19:41 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.5
See https://gist.github.com/2e9a46361a5e1e22c636e51c784e64a8 for a full test report.

2020-10-14 19:44 UTC, verdurin approved these changes
Looks fine.

2020-10-14 19:46 UTC, merged