{tools}[foss/2020a] IRkernel v1.1 w/ Python 3.8.2
easybuilders/easybuild-easyconfigs pull request #11344
Opened 2020-09-23 15:10 UTC by boegel

(created using `eb --new-pr`)

2020-09-23 15:41 UTC, boegel commented
@boegelbot please test @ generoso

2020-09-23 16:13 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2602.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/17f3ec789761a630605094c1f7e965f8 for a full test report.

2020-09-23 16:57 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node308.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c4e53008c286a44bb88b3c8908eba9d7 for a full test report.

2020-09-23 23:35 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
node127.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/5a98f93fa109049a6ed82f94704d5a68 for a full test report.

2020-09-24 13:22 UTC, boegel commented
@lexming test failed because of pre-existing lock file?

2020-09-24 15:30 UTC, lexming requested changes
@boegel nope, my tests failed due to missing sources. Tarballs of v1.1 are now archived. Quick fix is to add the extra `source_url`. Alternatively the version of this easyconfig could be bumped to `1.1.1`.

2020-09-24 15:30 UTC, lexming commented on easybuild/easyconfigs/i/IRkernel/IRkernel-1.1-foss-2020a-R-3.6.3-Python-3.8.2.eb
> +        'https://cran.rstudio.com/src/contrib/',
```suggestion
        'https://cran.rstudio.com/src/contrib/',
        'https://cran.r-project.org/src/contrib/Archive/IRkernel/',
```

2020-10-06 17:46 UTC, verdurin commented on easybuild/easyconfigs/i/IRkernel/IRkernel-1.1-foss-2020a-R-3.6.3-Python-3.8.2.eb
> +        'https://cran.rstudio.com/src/contrib/',
@boegel any update here?

2020-10-13 10:18 UTC, boegel commented
@boegelbot please test @ generoso
EB_ARGS="--force-download"

2020-10-13 10:23 UTC, boegel commented
@lexming should be good to go now

2020-10-13 17:15 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8abbd0622c6e69398dc4c6041eb70784 for a full test report.

2020-10-13 17:15 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node101.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/26371a1da550619b97afc8550439b5c8 for a full test report.

2020-10-13 17:55 UTC, lexming approved these changes
LGTM

2020-10-13 17:55 UTC, lexming commented
Going in, thanks @boegel !

2020-10-13 17:55 UTC, merged