{lib}[GCCcore/9.3.0] ACTC v1.1
easybuilders/easybuild-easyconfigs pull request #11378
Opened 2020-09-25 12:14 UTC by ekieffer

(created using `eb --new-pr`)

2020-09-25 12:14 UTC, ekieffer commented
Test report by @ULHPC
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
iris-002 - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 3.6.8
See https://gist.github.com/42b8dd7f7894b579fc9d27bdac8534ff for a full test report.

2020-09-25 15:23 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node377.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ad032e8a193a12f923ec586ea0500d3b for a full test report.

2020-09-26 12:31 UTC, lexming requested changes

2020-09-26 12:31 UTC, lexming commented on easybuild/easyconfigs/a/ACTC/ACTC-1.1-GCCcore-9.3.0.eb
> +toolchain = {'name': 'GCCcore', 'version': '9.3.0'}
The `toolchainopts` from `ACTC-1.1-GCCcore-8.3.0.eb` are missing
```suggestion
toolchain = {'name': 'GCCcore', 'version': '9.3.0'}
toolchainopts = {'pic': True}
```

2020-09-28 16:03 UTC, smoors commented
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node378.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/9eb4fc767f4bf4aeed8f596b11ff9c70 for a full test report.

2020-09-28 16:03 UTC, smoors commented
@boegelbot please test @ generoso

2020-09-28 16:08 UTC, smoors approved these changes
lgtm

2020-09-28 16:09 UTC, smoors commented
Going in, thanks @ekieffer!

2020-09-28 16:09 UTC, merged