{math}[intel/2020a] Harminv v1.4.1
easybuilders/easybuild-easyconfigs pull request #11380
Opened 2020-09-25 12:31 UTC by ekieffer

(created using `eb --new-pr`)

2020-09-25 12:32 UTC, ekieffer commented
Test report by @ULHPC
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
iris-002 - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 3.6.8
See https://gist.github.com/e88abb2592f4b161f0a329c51a7ea8d3 for a full test report.

2020-09-25 15:24 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node378.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/83000ab11fef4296235643cc67be037a for a full test report.

2020-09-26 11:26 UTC, lexming requested changes
This PR works well. I would just make a few changes to the sanity checks. Please check below

2020-09-26 11:26 UTC, lexming commented on easybuild/easyconfigs/h/Harminv/Harminv-1.4.1-intel-2020a.eb
> +    'dirs': ['bin', 'lib']
The sanity checks can be improved
```suggestion
    'files': ['bin/harminv', 'lib/libharminv.a', 'lib/libharminv.%s' % SHLIB_EXT],
    'dirs': ['include']
```

2020-09-28 15:57 UTC, smoors commented
@boegelbot please test @ generoso

2020-09-28 15:59 UTC, smoors commented
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node378.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/f884f3d0a59edef9a568f33ea3a0d490 for a full test report.

2020-09-28 16:04 UTC, smoors approved these changes
lgtm

2020-09-28 16:04 UTC, smoors commented
Going in, thanks @ekieffer!

2020-09-28 16:04 UTC, merged