{tools}[intel/2018a] hypothesis v3.66.18 w/ Python 3.6.4
easybuilders/easybuild-easyconfigs pull request #11408
Opened 2020-09-30 09:24 UTC by SimonPinches

(created using `eb --new-pr`)

2020-10-01 18:35 UTC, smoors requested changes

2020-10-02 15:09 UTC, SimonPinches commented on easybuild/easyconfigs/h/hypothesis/hypothesis-3.66.18-intel-2018a-Python-3.6.4.eb
> +
Done as suggested @smoors.

2020-10-02 16:51 UTC, smoors commented
Test report by @smoors
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
node368.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/7ee9d20593c0dc7ec38c5427c54dc96d for a full test report.

2020-10-02 18:20 UTC, smoors commented
@SimonPinches `pip check` claims there is an extension missing:

> hypothesis 3.66.18 requires enum34, which is not installed.

which makes no sense since Python3.6 already has enum in the standard lib.

the culprit however is setuptools, which claims to be version 28.8.0 (at least in our site), which again makes no sense since version 38.4.0 is installed as extension in the Python-3.6.4 easyconfig. can you confirm this in your site?

the reason for that (I think) is that setuptools-38.4.0 should have been installed with pip in order to override the setuptools that comes with Python itself. however, changing the base Python installation may be a bit drastic.

a more pragmatic solution is to just add setuptools as extension to hypothesis (this worked for me):
```
    ('setuptools', '38.4.0', {
        'source_tmpl': '%(name)s-%(version)s.zip',
        'source_urls': ['https://pypi.python.org/packages/source/s/setuptools/'],
        'checksums': ['6501fc32f505ec5b3ed36ec65ba48f1b975f52cf2ea101c7b73a08583fd12f75'],
    }),
```

2020-10-02 18:20 UTC, smoors commented
@boegelbot please test @ generoso

2020-10-05 17:11 UTC, SimonPinches commented
@smoors I've added your installation fix using `setuptools` and also bumped the version of hypothesis to 4.39.0 to get around some problems here.  This is the last version that works with `pytest/3.8.0` and doesn't require `pytest/4.3.0`.

2020-10-05 20:04 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3404.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/09c19bf07917456e9d876ae305cca447 for a full test report.

2020-10-05 20:06 UTC, boegel commented
@smoors Do you mind following up on this?

2020-10-06 12:30 UTC, smoors commented
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node376.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/5ea66e87e1a369d165de8ffcebc219e3 for a full test report.

2020-10-06 12:30 UTC, smoors approved these changes
lgtm

2020-10-06 12:32 UTC, smoors commented
Going in, thanks @SimonPinches!

2020-10-06 12:32 UTC, merged