aarch64-fixing.
easybuilders/easybuild-easyconfigs pull request #11417
Opened 2020-10-01 14:44 UTC by terjekv

(created using `eb --new-pr`)

2020-10-02 04:11 UTC, terjekv commented
Test report by @terjekv
**FAILED**
Build succeeded for 6 out of 7 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux RHEL 8.2, x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/cd491e68799cbbb3cc2a97c377c8431d for a full test report.

2020-10-02 08:56 UTC, boegel commented
@boegelbot please test @ generoso

2020-10-02 11:16 UTC, terjekv commented
Test report by @terjekv
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux RHEL 8.2, x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/3b8c20372e1a17fde286f81e2645f7da for a full test report.

2020-10-03 03:03 UTC, terjekv commented
Test report by @terjekv
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux RHEL 8.2, x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/d78180e3380421bc2fad685204288bb7 for a full test report.

2020-10-03 08:53 UTC, terjekv commented
Test report by @terjekv
**FAILED**
Build succeeded for 2 out of 3 (1 easyconfigs in this PR)
arm1 - Linux ubuntu 18.04, AArch64, UNKNOWN (aarch64), Python 3.6.9
See https://gist.github.com/9f46ac2a6e606970807ee4b5fbc8e8bb for a full test report.

2020-10-03 13:01 UTC, terjekv commented
Test report by @terjekv
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux RHEL 8.2, x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/478a3bfe3f6e1f02c97350f19c3e41b9 for a full test report.

2020-10-03 13:29 UTC, terjekv commented
Test report by @terjekv
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux RHEL 8.2, x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/3a35d60ac69fa8b76d66c9b0fcef48c7 for a full test report.

2020-10-03 16:14 UTC, terjekv commented
Test report by @terjekv
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux RHEL 8.2, x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/5c9abc6009600e556df09bb6f0d8d779 for a full test report.

2020-10-04 10:42 UTC, terjekv commented
Test report by @terjekv
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
arm1 - Linux ubuntu 18.04, AArch64, UNKNOWN (aarch64), Python 3.6.9
See https://gist.github.com/d1ad930dcce6014d01990ff2069b0e17 for a full test report.

2020-10-04 12:28 UTC, terjekv commented
Test report by @terjekv
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
arm1 - Linux ubuntu 18.04, AArch64, UNKNOWN (aarch64), Python 3.6.9
See https://gist.github.com/3fab57e774c4142bd2e89eff77c30b22 for a full test report.

2020-10-04 16:43 UTC, terjekv commented
Test report by @terjekv
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
ninhursaga.uio.no - Linux RHEL 8.2, x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (cascadelake), Python 3.6.8
See https://gist.github.com/cb778007bb67dea0ba613138d2abb517 for a full test report.

2020-10-04 17:55 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
bear-pg0305u03a.bear.cluster - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/c0a1a6f49a9c06542d73ad5e5aed3a84 for a full test report.

2020-10-04 18:02 UTC, terjekv commented
Both of the aarch64 units I have access to are currently down. I'll try to have someone look at it tomorrow, but last I saw the testing had long since past LEA and other troublemakers:

```
[...]
== installing extension IlluminaHumanMethylation450kmanifest 0.4.0 (242/262)...
== installing extension IlluminaHumanMethylationEPICmanifest 0.3.0 (243/262)...
== installing extension IlluminaHumanMethylation450kanno.ilmn12.hg19 0.6.0 (244/262)...
client_loop: send disconnect: Broken pipe
```

2020-10-06 13:13 UTC, terjekv commented
No longer a WIP. This looks good. Testing on arm again today.

2020-10-07 06:48 UTC, boegel commented
@terjekv Is a test report coming up?

2020-10-07 07:16 UTC, terjekv commented
Yeah, I thought I started it last night. Sorry. Let me kick one off.

2020-10-07 10:21 UTC, terjekv commented
Test report by @terjekv
**FAILED**
Build succeeded for 77 out of 97 (1 easyconfigs in this PR)
arm2 - Linux ubuntu 18.04, AArch64, UNKNOWN, Python 3.6.9
See https://gist.github.com/7b023efdccc8dfdadc95ee6b07af6420 for a full test report.

2020-10-07 10:49 UTC, verdurin commented
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
See https://gist.github.com/e3bdb1e4dd751df521669055460eb686 for a full test report.

2020-10-07 10:56 UTC, terjekv commented
> Test report by @verdurin
> **FAILED**
> Build succeeded for 0 out of 1 (1 easyconfigs in this PR)
> easybuild.novalocal - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 2.7.5
> See https://gist.github.com/e3bdb1e4dd751df521669055460eb686 for a full test report.

@verdurin This has to be built against latest Develop. It's the same issue I ran into, as underlying EasyConfigs have changed.

2020-10-08 19:04 UTC, terjekv commented
Test report by @terjekv
**FAILED**
Build succeeded for 0 out of 20 (1 easyconfigs in this PR)
arm2 - Linux ubuntu 18.04, AArch64, UNKNOWN, Python 3.6.9
See https://gist.github.com/968cdc2438cc87d34d5eac22d1867b17 for a full test report.

2020-10-08 23:57 UTC, terjekv commented
> Test report by @terjekv
> **FAILED**
> Build succeeded for 0 out of 20 (1 easyconfigs in this PR)
> arm2 - Linux ubuntu 18.04, AArch64, UNKNOWN, Python 3.6.9
> See https://gist.github.com/968cdc2438cc87d34d5eac22d1867b17 for a full test report.

Sigh, `unzip` is a system dependency for Python:

```
== FAILED: Installation ended unsuccessfully (build directory: /home/terjekv/.local/easybuild/build/Python/3.8.2/GCCcore-9.3.0): build failed (first 300 chars): cmd "unzip -qq /h
ome/terjekv/.local/easybuild/sources/p/Python/extensions/setuptools-45.2.0.zip" exited with exit code 127 and output:
/bin/bash: unzip: command not found
```

2020-10-09 05:41 UTC, terjekv commented
Test report by @terjekv
**FAILED**
Build succeeded for 17 out of 20 (1 easyconfigs in this PR)
arm2 - Linux ubuntu 18.04, AArch64, UNKNOWN, Python 3.6.9
See https://gist.github.com/a2b1e3300c90884886f8e4064e4110a2 for a full test report.

2020-10-09 17:11 UTC, terjekv commented
Test report by @terjekv
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
arm2 - Linux ubuntu 18.04, AArch64, UNKNOWN, Python 3.6.9
See https://gist.github.com/b80ca5c715108accc49be382f3062b4e for a full test report.

2020-10-09 18:24 UTC, boegel commented
> > Test report by @terjekv
> > **FAILED**
> > Build succeeded for 0 out of 20 (1 easyconfigs in this PR)
> > arm2 - Linux ubuntu 18.04, AArch64, UNKNOWN, Python 3.6.9
> > See https://gist.github.com/968cdc2438cc87d34d5eac22d1867b17 for a full test report.
> 
> Sigh, `unzip` is a system dependency for Python:
> 
> ```
> == FAILED: Installation ended unsuccessfully (build directory: /home/terjekv/.local/easybuild/build/Python/3.8.2/GCCcore-9.3.0): build failed (first 300 chars): cmd "unzip -qq /h
> ome/terjekv/.local/easybuild/sources/p/Python/extensions/setuptools-45.2.0.zip" exited with exit code 127 and output:
> /bin/bash: unzip: command not found
> ```

We have easyconfigs for `UnZip`, so we should add it as a build dep for `Python`, see #10477.

2020-10-11 12:38 UTC, terjekv commented
Test report by @terjekv
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
arm2 - Linux ubuntu 18.04, AArch64, UNKNOWN, Python 3.6.9
See https://gist.github.com/6919d7d54c31e11e0a10c26b641b30c3 for a full test report.

2020-10-12 14:50 UTC, boegel requested changes

2020-10-12 14:50 UTC, boegel commented on easybuild/easyconfigs/r/R-bundle-Bioconductor/mzR-2.22.0_use-external-boost.patch
> +diff -ru mzR.orig/src/Makevars mzR/src/Makevars
@terjekv missing patch description + author or upstream reference

2020-10-12 14:50 UTC, boegel commented on easybuild/easyconfigs/r/R-bundle-Bioconductor/LEA-3.0.0_support_aarch64_and_ppc64le.patch
> +diff --git a/src/bituint/bituint.h b/src/bituint/bituint.h
@terjekv missing patch description + author or upstream reference

2020-10-12 15:31 UTC, terjekv commented on easybuild/easyconfigs/r/R-bundle-Bioconductor/LEA-3.0.0_support_aarch64_and_ppc64le.patch
> +diff --git a/src/bituint/bituint.h b/src/bituint/bituint.h
https://github.com/easybuilders/easybuild-easyconfigs/pull/11417/commits/23c4a7616e4b37d7c6e4e91d6f52fae06c743cb9

2020-10-12 15:31 UTC, terjekv commented on easybuild/easyconfigs/r/R-bundle-Bioconductor/mzR-2.22.0_use-external-boost.patch
> +diff -ru mzR.orig/src/Makevars mzR/src/Makevars
https://github.com/easybuilders/easybuild-easyconfigs/pull/11417/commits/23c4a7616e4b37d7c6e4e91d6f52fae06c743cb9

2020-10-12 18:05 UTC, boegel commented
@boegelbot please test @ generoso

2020-10-12 20:36 UTC, boegel approved these changes
lgtm

2020-10-12 20:52 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3407.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/2452f534a8feed0ce045ab283aec22c6 for a full test report.

2020-10-13 07:14 UTC, boegel commented
Going in, thanks @terjekv!

2020-10-13 07:14 UTC, merged