Adding SU2-7.0.6 software
easybuilders/easybuild-easyconfigs pull request #11441
Opened 2020-10-06 15:39 UTC by alirezaghavaminia

Hello, 
I have written an `Easyconfig` file for the `SU2` software. 
Please check it and PM me if it requires any changes.
Thank you very much.

2020-10-06 15:49 UTC, Micket requested changes

2020-10-06 15:49 UTC, Micket commented on easybuild/easyconfigs/f/FPM/FPM-1.4.0-Ruby-2.7.1.eb
> +# By: Alireza Ghavaminia <a.ghavami@alumni.iut.ac.ir> at Isfahan University of Technology
The PR doesn't mention this file?

2020-10-06 15:49 UTC, Micket commented on easybuild/easyconfigs/r/Ruby/Ruby-2.7.1.eb
> +# By: Alireza Ghavaminia <a.ghavami@alumni.iut.ac.ir> at Isfahan University of Technology
The PR doesn't mention this file either?

2020-10-06 15:49 UTC, Micket commented on easybuild/easyconfigs/s/SU2/SU2-7.0.2-foss-2020a.eb
> +# easyconfig file for SU2-7.0.6
This is a incorrect duplicate file.

2020-10-06 15:49 UTC, Micket commented on easybuild/easyconfigs/s/SU2-7.0.2-foss-2020a.eb
> +source_urls = ['https://github.com/su2code/SU2/archive/']
```suggestion
source_urls = [GITHUB_SOURCE]
```

2020-10-06 15:49 UTC, Micket commented on easybuild/easyconfigs/s/SU2-7.0.2-foss-2020a.eb
> +    ('SciPy-bundle', '2020.03', '-Python-3.8.2')
```suggestion
    ('SciPy-bundle', '2020.03', verionsuffix)
```

2020-10-06 15:49 UTC, Micket commented on easybuild/easyconfigs/s/SU2-7.0.2-foss-2020a.eb
> +version = '7.0.6'
This file should have a `versionsuffix = '-Python-%(pyver)s'`
(also should be included in the filename)

2020-10-06 15:53 UTC, Micket commented on easybuild/easyconfigs/s/SU2-7.0.2-foss-2020a.eb
> +    ('SciPy-bundle', '2020.03', '-Python-3.8.2')
Ack, i made this in the wrong file. I mean the correct file (7.0.6)

2020-10-06 15:53 UTC, Micket commented on easybuild/easyconfigs/s/SU2-7.0.2-foss-2020a.eb
> +version = '7.0.6'
this as well -> 7.0.6

2020-10-07 10:51 UTC, closed without merging

2020-10-13 10:16 UTC, boegel commented
replaced with #11446