{tools}[GCCcore/10.2.0] CMake v3.18.4, cURL v7.72.0, bzip2 v1.0.8
easybuilders/easybuild-easyconfigs pull request #11492
Opened 2020-10-13 20:32 UTC by boegel

(created using `eb --new-pr`)

2020-10-13 20:32 UTC, boegel commented
@boegelbot please test @ generoso

2020-10-13 20:38 UTC, Micket requested changes

2020-10-13 20:38 UTC, Micket commented on easybuild/easyconfigs/c/CMake/CMake-3.18.4-GCCcore-10.2.0.eb
> +    # ('OpenSSL', '1.1.1d'),
will probably be 1.1.1h

2020-10-13 20:38 UTC, Micket commented on easybuild/easyconfigs/c/CMake/CMake-3.18.4-GCCcore-10.2.0.eb
> +    ('openssl-devel', 'libssl-dev', 'libopenssl-devel'),
osdependencies = [OS_PKG_OPENSSL_DEV]

2020-10-13 20:38 UTC, Micket commented on easybuild/easyconfigs/c/cURL/cURL-7.72.0-GCCcore-10.2.0.eb
> +    # ('OpenSSL', '1.1.1d')
1.1.1h

2020-10-13 20:38 UTC, Micket commented on easybuild/easyconfigs/c/cURL/cURL-7.72.0-GCCcore-10.2.0.eb
> +    ('openssl-devel', 'libssl-dev', 'libopenssl-devel'),
osdependencies = [OS_PKG_OPENSSL_DEV]

2020-10-14 12:36 UTC, Micket commented
Test report by @Micket
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/eb60d8162be49a7fe0f279656b758af6 for a full test report.

2020-10-14 13:11 UTC, Micket commented
Test report by @Micket
**FAILED**
Build succeeded for 12 out of 13 (1 easyconfigs in this PR)
hebbe-c1 - Linux centos linux 7.8.2003, x86_64, Intel Core Processor (Haswell, no TSX), Python 2.7.5
See https://gist.github.com/664ad47b1075c4647581ca771b150781 for a full test report.

2020-10-14 13:21 UTC, boegel commented
@boegelbot please test @ generoso

2020-10-14 13:26 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/85018583b59bea0b912c80a2b16b6293 for a full test report.

2020-10-14 13:27 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3401.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/a1e975fd6e3890545db05184084effd0 for a full test report.

2020-10-14 13:45 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2661.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/e4f8a85e57078e4da90005a205032026 for a full test report.

2020-10-14 13:53 UTC, boegel commented
@Micket Good to go?

2020-10-14 14:01 UTC, Micket approved these changes
lgtm

2020-10-14 14:02 UTC, Micket commented
Going in, thanks @boegel!

2020-10-14 14:02 UTC, merged