{bio}[system/system] fgbio v1.3.0
easybuilders/easybuild-easyconfigs pull request #11519
Opened 2020-10-16 13:59 UTC by zarybnicky

(created using `eb --new-pr`)

2020-10-16 14:38 UTC, boegel requested changes

2020-10-16 14:38 UTC, boegel commented on easybuild/easyconfigs/f/fgbio/fgbio-1.3.0.eb
> +    (['target/scala-2.13/fgbio-%(version)s.jar'], 'lib'),
Maybe use `scala-*/fgbio-...` to avoid the hardcoded version?

2020-10-16 14:38 UTC, boegel commented on easybuild/easyconfigs/f/fgbio/fgbio-1.3.0.eb
> +sanity_check_commands = ['grep -q Version <<< $(fbgio --help 2>&1)']
simpler/clear:
```python
sanity_check_commands = ['fbgio --help 2>&1 | grep -q Version']
```

2020-10-16 14:52 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3402.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/b26df0d93184daba0a838168bff3a5d7 for a full test report.

2020-10-18 09:59 UTC, boegel commented
@boegelbot please test @ generoso

2020-10-18 11:17 UTC, zarybnicky commented
@boegel Is `Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.pom` from the logs doesn't seem like a build error I can fix - is the connectivity on `generoso-x-2` good?

2020-10-19 08:20 UTC, boegel commented
@zarybnicky We don't manage `generoso`, but it should have good connectivity to the outside world. I'll check again from a different system.

2020-10-19 08:20 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node2427.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/781b86bcee36290166567ca52923d499 for a full test report.

2020-10-19 08:26 UTC, boegel commented
@zarybnicky `$HOME/.sbt` is purposely set to read-only to ensure no installation tries to use it, please redefine `$HOME` during the installation to make it use `$TMPDIR` instead?

```
$ ls -ld /user/gent/400/vsc40023/.sbt/
dr-------- 2 vsc40023 vsc40023 4096 Nov 20  2017 /user/gent/400/vsc40023/.sbt/
```

2020-10-19 20:37 UTC, zarybnicky commented
That's what I blindly tried, setting HOME=$TMPDIR, but it seems this isn't it. I'll look into `sbt` options...

2020-10-20 15:17 UTC, zarybnicky commented
`-sbt-dir` seems to work better than just `HOME=$TMPDIR`, for future reference.

2020-10-20 17:52 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node2709.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/1bdda0b3525bdfd770e2b409bcd0be76 for a full test report.

2020-10-20 17:53 UTC, boegel commented
@zarybnicky similar issue now with `$HOME/.ivy2`...

2020-11-02 18:25 UTC, verdurin commented
@zarybnicky any thoughts on the comment from @boegel ?

2020-11-17 07:59 UTC, boegel commented
@boegelbot please test @ generoso

2020-11-17 08:01 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3166.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/98e238f854d2a6a4f24c932b89365012 for a full test report.

2020-11-17 08:31 UTC, boegel commented
@boegelbot please test @ generoso

2020-11-17 08:34 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node2632.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/8d5497e156a6faf2ab30bf732b631820 for a full test report.

2020-11-17 09:06 UTC, boegel commented
@boegelbot please test @ generoso

2020-11-17 09:09 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3407.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/2f1b5ab82a806fe76986f93ebf6b8a3b for a full test report.

2020-11-17 09:10 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3166.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/8db26c189c7b2a4e10a36a604403c5c8 for a full test report.

2020-11-17 09:12 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2632.swalot.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/8e3827dd25758169aa082aa1563e3868 for a full test report.

2020-11-17 09:27 UTC, boegel approved these changes

2020-11-17 10:32 UTC, boegel commented
Going in, thanks @zarybnicky!

2020-11-17 10:32 UTC, merged