adding easyconfigs: NCCL-2.7.8-gcccuda-2020a.eb
easybuilders/easybuild-easyconfigs pull request #11542
Opened 2020-10-19 21:43 UTC by ccoulombe

Adding latest NCCL with Cuda 11 pulling source from the redist url.

2020-10-20 13:46 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/aff3f814a41afa11530e45be7485cf6d for a full test report.

2020-10-20 14:06 UTC, smoors commented
@boegelbot please test @ generoso

2020-10-20 14:14 UTC, Micket commented
@smoors Kenneth brought up the point that, maybe this can be moved up to SYSTEM level. Does this actually compile anything?

2020-10-20 14:16 UTC, ccoulombe commented
@Micket @smoors 
It skip builds so indeed it could be at SYSTEM level.

2020-10-20 14:26 UTC, boegel commented
Maybe @bartoldeman can clarify why we have this at the `gcccuda` toolchain in the current NCCL easyconfigs.
Does it really need `CUDA(core)` as a dep?

2020-10-20 14:43 UTC, Micket commented
Recap of slack conversation:
Yes this NCCL is tied to a particular CUDA version (11.0).

One suggested option is to introduce a new toolchain and addition to HMNS and put it there. I'm not very keen on that, seems like a lot of work for a questionable benefit to me.

Another suggested option is to create a system level easyconfig, with a dependency on CUDAcore, with a `versionsuffix = '-CUDA-11.0.2'`. I prefer this.

2020-10-20 14:43 UTC, bartoldeman commented
it can indeed be at the system level but then you need to add a versionsuffix like in
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/n/NCCL/NCCL-2.2.13-CUDA-9.2.148.1.eb
(and the dep is then CUDAcore instead of CUDA now)

2020-10-28 21:02 UTC, Micket requested changes
Summarizing the changes as discussed

2020-10-28 21:02 UTC, Micket commented on easybuild/easyconfigs/n/NCCL/NCCL-2.7.8-gcccuda-2020a.eb
> +version = '2.7.8'
Please add the versionsuffix  `-CUDA-%(cudaver)s`

2020-10-28 21:02 UTC, Micket commented on easybuild/easyconfigs/n/NCCL/NCCL-2.7.8-gcccuda-2020a.eb
> +
Please add a dependency to `CUDAcore` 11.0.2

2020-10-28 21:02 UTC, Micket commented on easybuild/easyconfigs/n/NCCL/NCCL-2.7.8-gcccuda-2020a.eb
> +toolchain = {'name': 'gcccuda', 'version': '2020a'}
Please move to `toolchain = SYSTEM`

2020-11-02 12:04 UTC, verdurin commented
@ccoulombe @bartoldeman any update on this one?

2020-12-03 23:44 UTC, migueldiascosta commented
will be superseded by #11803, any objections?

2020-12-08 19:04 UTC, boegel commented
Should this be closed now that #11803 is merged?

2020-12-09 15:13 UTC, bartoldeman commented
yes this can be closed then

2020-12-09 15:13 UTC, closed without merging