{bio}[system/system] MAGeCK-VISPR v0.5.5 w/ Python 3.7.4
easybuilders/easybuild-easyconfigs pull request #11560
Opened 2020-10-22 03:55 UTC by jordiblasco

(created using `eb --new-pr`)

2020-10-27 17:18 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node101.hydra.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/69657ba7e905aac6e2783bbec7d3fba1 for a full test report.

2020-10-27 18:12 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node366.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/575b7d60f0ea53f8b425a650c90d0328 for a full test report.

2020-10-29 18:38 UTC, lexming requested changes
Thanks for this PR, the installation works well. However, there is an issue with the dependency on Python. Please check my comment below

2020-10-29 18:38 UTC, lexming commented on easybuild/easyconfigs/m/MAGeCK-VISPR/MAGeCK-VISPR-0.5.5-Python-3.7.4.eb
> +    ('Python', '3.7.4', '-GCCcore-8.3.0')
Having MAGeCK-VISPR on `SYSTEM` and this dependency on Python will cause issues. If there is any other module of Python already loaded, loading MAGeCK-VISPR will fail. The solution might be as easy as removing the dependency on Python though, as it is already installed by conda in any case
```
[...]
    python-3.7.8               |h6f2ec95_1_cpython        53.1 MB  conda-forge
    python-dateutil-2.8.1      |             py_0         220 KB  conda-forge
    python-irodsclient-0.8.2   |             py_0          69 KB  conda-forge
[...]
```

2020-11-02 18:24 UTC, verdurin commented
@jordiblasco any thoughts on the comment from @lexming ?

2022-10-17 14:13 UTC, jfgrimm reviewed
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 11560` and update the PR to use `SYSTEM` instead.

2023-06-21 13:49 UTC, closed without merging

2023-06-21 13:49 UTC, jfgrimm commented
closing since this has gone stale, and the review comments have gone unaddressed