{tools}[system/system] vsc-mympirun v5.2.2
easybuilders/easybuild-easyconfigs pull request #11578
Opened 2020-10-26 18:45 UTC by boegel

(created using `eb --new-pr`)

2020-10-26 18:47 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3623.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/22971dcfda234211e80e33b8e826cb36 for a full test report.

2020-10-26 18:47 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3120.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/f62225bc0945ddea5e7431a027494aa9 for a full test report.

2020-10-26 18:51 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3403.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/81febafa70ef38f393f6e616823507a4 for a full test report.

2020-10-26 18:52 UTC, boegel commented
@boegelbot please test @ generoso

2020-10-27 17:10 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node101.hydra.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/851d724ef9e01c5bfc8083b4e6e65ace for a full test report.

2020-10-27 17:20 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node371.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/58cdb069fe09c10900043159dc769c2e for a full test report.

2020-10-28 15:02 UTC, lexming requested changes

2020-10-28 15:02 UTC, lexming commented on easybuild/easyconfigs/v/vsc-mympirun/vsc-mympirun-5.2.2.eb
> +    ('setuptools', '41.6.0', {
Please add the previous comment about the restriction on `setuptools`, if `vsc-install` v0.17 still needs `setuptools` < 42.0.

2020-11-05 18:06 UTC, verdurin commented
@boegel any update here?

2020-11-06 15:32 UTC, lexming approved these changes
LGTM

2020-11-06 15:50 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 32, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.8.6
See https://gist.github.com/317d50a286ecd8dd87ffbd281e6b88d8 for a full test report.

2020-11-06 16:03 UTC, verdurin commented
Going in, thanks @boegel!

2020-11-06 16:03 UTC, merged

2020-11-06 17:50 UTC, lexming commented
OMG I blinked and @verdurin already merged it :smile: