{geo}[foss/2020b,intel/2020b] WRF v3.9.1.1
easybuilders/easybuild-easyconfigs pull request #11675
Opened 2020-11-11 10:47 UTC by boegel

(created using `eb --new-pr`)

2020-11-11 23:45 UTC, Micket approved these changes
lgtm

2020-11-11 23:46 UTC, Micket commented
@boegelbot please test @ generoso

2020-11-11 23:56 UTC, Micket commented
Test report by @Micket
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/17f17d68dcb73dbc1f0b8878b10a7b90 for a full test report.

2020-11-12 08:26 UTC, boegel commented
@boegelbot please test @ generoso

2020-11-12 10:58 UTC, boegel commented
@Micket No, there's something really wrong...
```
ranlib  libwrflib.a -ltirpc
ranlib: invalid option -- 'l'
ranlib: invalid option -- 'i'
ranlib: invalid option -- 'r'
ranlib: invalid option -- 'p'
ranlib: invalid option -- 'c'
```

2020-11-12 11:01 UTC, boegel commented
> Test report by @Micket
> **FAILED**
> Build succeeded for 4 out of 5 (5 easyconfigs in total)
> vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
> See https://gist.github.com/17f17d68dcb73dbc1f0b8878b10a7b90 for a full test report.
> 
> ugh, probably some test suite or something and i is problematic on my build node

@Micket In your case, it's a different problem:

```
/bin/bash: /apps/Vera/software/MPI/intel/2020.4.304/impi/2019.9.304/WRF/3.9.1.1-dmpar/WRFV3/compile: /apps/Vera/software/Compiler/GCCcore/10.2.0/tcsh/6.22.02/bin/tcsh: bad interpreter: No such file or directory
```

Did something remove the `tcsh` installation while `WRF` was being installed?

2020-11-12 11:02 UTC, Micket commented
It might have ran out of disk space, maybe. I was multitasking and didn't keep track.

2020-11-12 12:43 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3122.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/8151dc19e244c8e6061bc59496e4ea44 for a full test report.

2020-11-16 11:14 UTC, boegel commented
@boegelbot please test @ generoso

2021-04-14 07:06 UTC, akesandgren commented
Please update to tcsh 6.02.23 from #12592 before merging

2021-04-14 09:25 UTC, akesandgren requested changes

2021-04-14 09:25 UTC, akesandgren commented on easybuild/easyconfigs/w/WRF/WRF-3.9.1.1-foss-2020b-dmpar.eb
> +    ('tcsh', '6.22.02'),
please upgrade to tcsh 6.22.03 from #12592

2021-04-14 09:25 UTC, akesandgren commented on easybuild/easyconfigs/w/WRF/WRF-3.9.1.1-intel-2020b-dmpar.eb
> +    ('tcsh', '6.22.02'),
Same here, use newer tcsh from #12592

2021-04-14 11:02 UTC, akesandgren requested changes

2021-04-14 11:02 UTC, akesandgren commented on easybuild/easyconfigs/w/WRF/WRF-3.9.1.1-foss-2020b-dmpar.eb
> +    ('JasPer', '2.0.14'),
2.0.24 is the JasPer version for 10.2.0

2021-04-14 11:02 UTC, akesandgren commented on easybuild/easyconfigs/w/WRF/WRF-3.9.1.1-intel-2020b-dmpar.eb
> +    ('JasPer', '2.0.14'),
2.0.24 is the JasPer version for 10.2.0

2021-04-14 11:55 UTC, akesandgren requested changes

2021-04-14 11:55 UTC, akesandgren commented on easybuild/easyconfigs/w/WRF/WRF-3.9.1.1-foss-2020b-dmpar.eb
> +    ('libtirpc', '1.2.6'),
Current version of tirpc for 10.2.0 is 1.3.1

2021-04-14 11:55 UTC, akesandgren commented on easybuild/easyconfigs/w/WRF/WRF-3.9.1.1-intel-2020b-dmpar.eb
> +    ('libtirpc', '1.2.6'),
Current version of tirpc for 10.2.0 is 1.3.1

2021-04-15 05:58 UTC, akesandgren approved these changes
LGTM

2021-04-15 05:59 UTC, akesandgren commented
@boegelbot Please test @ generoso

2021-04-15 10:18 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (3 easyconfigs in total)
node3505.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/eff3eba063f94f94331108e712babf8d for a full test report.

2021-04-15 11:40 UTC, akesandgren commented
Going in, thanks @boegel!

2021-04-15 11:40 UTC, merged

2021-04-15 11:46 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (3 easyconfigs in total)
node3132.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/373cbaff9fe2584ebacd93afa8dba909 for a full test report.