{bio}[GCCcore/9.3.0] DIAMOND v0.9.36
easybuilders/easybuild-easyconfigs pull request #11682
Opened 2020-11-11 21:11 UTC by mboisson

(created using `eb --new-pr`)

2020-11-12 00:19 UTC, Micket reviewed
Any particular reason to drop the `sanity_check_commands = ['diamond --help']` ?

2020-12-22 16:07 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node360.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/96ef80f8bfe2548fd29784824f0694aa for a full test report.

2020-12-22 19:25 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node114.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/008c1cb0d44c5308825145869868c3ca for a full test report.

2020-12-22 20:06 UTC, boegel requested changes

2020-12-22 20:06 UTC, boegel commented on easybuild/easyconfigs/d/DIAMOND/DIAMOND-0.9.36-GCCcore-9.3.0.eb
> +toolchain = {'name': 'GCCcore', 'version': '9.3.0'}
@mboisson Same as in #11683: isn't GCC a better choice here, since this is performance sensitive?

2021-01-13 19:33 UTC, boegel requested changes

2021-01-13 19:33 UTC, boegel commented on easybuild/easyconfigs/d/DIAMOND/DIAMOND-0.9.36-GCC-9.3.0.eb
> +    ('binutils', '2.34'),
@mboisson Existing DIAMOND easyconfigs also list `zlib` as a dependency, which was dropped here, I guess that's a mistake?

Also, you can drop the `binutils` build dep, that's implied with `GCC` (but not with `GCCcore`)

2021-01-20 16:04 UTC, boegel approved these changes

2021-01-20 16:06 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3509.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/f1a15337ec1e0d8617fcb936b58f6802 for a full test report.

2021-01-20 16:07 UTC, boegel commented
@boegelbot please test @ generoso

2021-01-20 16:08 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2658.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/f552a7059128ee71390fce080a9cbc31 for a full test report.

2021-01-20 16:09 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3124.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/f4c244f6299ea7a4aa68df7c67390ef8 for a full test report.

2021-01-20 16:26 UTC, boegel commented
Going in, thanks @mboisson!

2021-01-20 16:26 UTC, merged