{phys}[foss/2019b] GetFEM v5.4.1
easybuilders/easybuild-easyconfigs pull request #11685
Opened 2020-11-12 05:20 UTC by jordiblasco

(created using `eb --new-pr`)

2021-03-02 20:05 UTC, verdurin requested changes

2021-03-02 20:05 UTC, verdurin commented on easybuild/easyconfigs/g/GetFEM/GetFEM-5.4.1-foss-2019b-Python-3.7.4.eb
> +dependencies = [
@jordiblasco I think you're missing the `Python` dependency here.

2021-03-02 20:05 UTC, verdurin commented on easybuild/easyconfigs/g/GetFEM/GetFEM-5.4.1-foss-2019b-Python-3.7.4.eb
> +homepage = 'http://getfem.org'
@jordiblasco do you know what's going on with the homepage? I tried the `https` version of that address, and it had a strange result.

2021-05-28 11:42 UTC, verdurin commented on easybuild/easyconfigs/g/GetFEM/GetFEM-5.4.1-foss-2019b-Python-3.7.4.eb
> +homepage = 'http://getfem.org'
@jordiblasco we still need to deal with the homepage error - can it be `https` or not?

2021-05-28 11:45 UTC, verdurin requested changes

2021-05-28 11:45 UTC, verdurin commented on easybuild/easyconfigs/g/GetFEM/GetFEM-5.4.1-foss-2019b-Python-3.7.4.eb
> +versionsuffix = '-Python-%(local_pyver)s'
Please remove the `local_pyver`, change `versionsuffix` back to normal, and add `Python` as a dependency.

2021-05-28 11:45 UTC, verdurin commented on easybuild/easyconfigs/g/GetFEM/GetFEM-5.4.1-foss-2019b-Python-3.7.4.eb
> +    ('SciPy-bundle', '2019.10', '', ('foss', '2019b-Python-%(local_pyver)s')),
With the changes listed above, please change this to be `versionsuffix`, in order to pick up the correct `SciPy-bundle` dependency.

2021-06-02 22:36 UTC, jordiblasco reviewed
@verdurin from my point of view if the HTTPS homepage is not working as expected, it shouldn't be our problem. Use HTTP instead.

2022-10-17 14:13 UTC, jfgrimm reviewed
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 11685` and update the PR to use `SYSTEM` instead.

2023-10-23 09:18 UTC, akesandgren commented
Closing this PR, since it (only) uses deprecated toolchain versions,
see https://docs.easybuild.io/policies/toolchains .

2023-10-23 09:18 UTC, closed without merging