{lib}[GCCcore/10.2.0] Check v0.15.2, GDRCopy v2.1, UCX v1.9.0, ...
easybuilders/easybuild-easyconfigs pull request #11701
Opened 2020-11-12 23:21 UTC by Micket

(created using `eb --new-pr`)

2020-11-12 23:25 UTC, Micket commented
Test report by @Micket
**FAILED**
Build succeeded for 2 out of 8 (8 easyconfigs in total)
alvis-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/2196617df108eefd4c719d0db6a37688 for a full test report.

2020-11-13 12:20 UTC, lexming requested changes

2020-11-13 12:20 UTC, lexming commented on easybuild/easyconfigs/u/UCX/UCX-1.9.0-GCCcore-10.2.0-CUDA-11.1.1.eb
> +osdependencies = [OS_PKG_OPENSSL_DEV]
Same fix here as in https://github.com/easybuilders/easybuild-easyconfigs/pull/11702
```suggestion
osdependencies = [OS_PKG_IBVERBS_DEV]
```

2020-11-13 12:20 UTC, lexming commented on easybuild/easyconfigs/g/GDRCopy/GDRCopy-2.1-GCCcore-10.2.0-CUDA-11.1.1.eb
> +    ('CUDAcore', local_cudaversion, '', True),
```suggestion
    ('CUDAcore', local_cudaversion, '', True),  # needed by GDRCopy binaries, which are tools for testing
```

2020-11-13 17:27 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 12 out of 18 (8 easyconfigs in total)
node155.hydra.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/71d8075c825f8d0faf99dca7d660d143 for a full test report.

2020-11-15 17:41 UTC, Micket commented
Test report by @Micket
**FAILED**
Build succeeded for 6 out of 8 (8 easyconfigs in total)
alvis-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/da4c542a11f645ab10a5cbeb97605aec for a full test report.

2020-11-15 20:30 UTC, Micket commented
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2205
**FAILED**
Build succeeded for 6 out of 8 (8 easyconfigs in total)
alvis-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/e18cc349dd4bf62a7de07b782f3a61a9 for a full test report.

2020-11-16 03:27 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
alvis-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/6e24391a26559ecd19fcc901236673f0 for a full test report.

2020-11-16 09:43 UTC, boegel commented
@Micket What was the issue with the earlier failing test reports?

2020-11-16 09:44 UTC, boegel commented
@boegelbot please test @ generoso

2020-11-16 11:17 UTC, Micket commented
> @Micket What was the issue with the earlier failing test reports?

well you have the commits along the way if you are curious, basically just a bunch of stupid mistakes as some configs copied parts from fosscuda-2020a rather than fosscuda-2020b.

2020-11-16 17:01 UTC, boegel approved these changes
lgtm, I'll get some more test reports submitted...

2020-11-16 17:46 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (8 easyconfigs in total)
node3406.kirlia.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 2.7.5
See https://gist.github.com/97c9a827a566e517106782c28b437d72 for a full test report.

2020-11-16 18:16 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node3111.skitty.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/0f2bf161cdf51765cef9f88a3c41a26d for a full test report.

2020-11-16 18:39 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 11 out of 11 (8 easyconfigs in total)
node2304.phanpy.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/eaf9b428a31bebaea8d38839b749999c for a full test report.

2020-11-16 18:42 UTC, boegel commented
Going in, thanks @Micket!

2020-11-16 18:42 UTC, merged

2020-11-19 00:09 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node155.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/9e016086c524492668c814df603bd384 for a full test report.