{devel}[system/system] Flink v1.11.2
easybuilders/easybuild-easyconfigs pull request #11747
Opened 2020-11-22 16:17 UTC by Falkor

(created using `eb --new-pr`)

2020-11-22 16:19 UTC, Falkor commented
Test report by @ULHPC
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
iris-042 - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 3.6.8
See https://gist.github.com/3d9e48d60ee2e14b84d0e5110b39b209 for a full test report.

2020-11-24 16:25 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/81ae306ed1e0cfc3c664a45eb7fcced4 for a full test report.

2020-11-26 10:53 UTC, lexming requested changes
Thanks for this PR, it works well. I would like to make a minor improvement regarding the sanity checks. Please consider my suggestions below

2020-11-26 10:53 UTC, lexming commented on easybuild/easyconfigs/f/Flink/Flink-1.11.2-bin-scala_2.11.eb
> +versionsuffix = '-bin-scala_2.11'
```suggestion
local_scala_version = '2.11'
versionsuffix = '-bin-scala_%s' % local_scala_version
```

2020-11-26 10:53 UTC, lexming commented on easybuild/easyconfigs/f/Flink/Flink-1.11.2-bin-scala_2.11.eb
> +sources = ['%(namelower)s-%(version)s-bin-scala_2.11.tgz']
```suggestion
sources = ['%%(namelower)s-%s%s.tgz' % (version, versionsuffix)]
```

2020-11-26 10:53 UTC, lexming commented on easybuild/easyconfigs/f/Flink/Flink-1.11.2-bin-scala_2.11.eb
> +}
```suggestion
sanity_check_paths = {
    'files': ['bin/flink', 'lib/flink-dist_%s-%s.jar' % (local_scala_version, version)],
    'dirs': ['conf', 'opt', 'plugins'],
}

sanity_check_commands = ['flink --version']
```

2020-11-27 15:40 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node378.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/3320f57efc3dfc8a500d6ffc4de4816f for a full test report.

2020-11-27 15:40 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node128.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/94262fc47b20c9eb67f3187fa1c3f468 for a full test report.

2020-11-27 19:18 UTC, lexming approved these changes
LGTM

2020-11-27 19:18 UTC, lexming commented
Going in, thanks @Falkor !

2020-11-27 19:18 UTC, merged