{bio}[intel/2020a] velocyto.py v0.17.17 w/ Python 3.8.2
easybuilders/easybuild-easyconfigs pull request #11744
Opened 2020-11-20 13:42 UTC by deniskristak

(created using `eb --new-pr`)

2020-11-24 19:03 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 7 out of 7 (1 easyconfigs in total)
node128.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/67585f31d866260eb7c016016165fa51 for a full test report.

2020-11-24 21:15 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 7 out of 7 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a532399e24c2fc048ef5088e51b49780 for a full test report.

2020-11-25 10:03 UTC, deniskristak commented
https://github.com/hpcugent/eb_inuits/issues/165

2020-11-26 09:35 UTC, boegel requested changes

2020-11-26 09:35 UTC, boegel commented on easybuild/easyconfigs/v/velocyto.py/velocyto.py-0.17.17-intel-2020a-Python-3.8.2.eb
> +name = 'velocyto.py'
I think using `velocyto` as name makes more sense, the Python aspect is already reflected in the `versionsuffix`; see also https://pypi.org/project/velocyto/

2020-11-26 09:35 UTC, boegel commented on easybuild/easyconfigs/v/velocyto.py/velocyto.py-0.17.17-intel-2020a-Python-3.8.2.eb
> +        'modulename': 'numpy_groupies',
This should not be required, the auto-guessed modulename should be correct?

2020-11-26 09:35 UTC, boegel commented on easybuild/easyconfigs/v/velocyto.py/velocyto.py-0.17.17-intel-2020a-Python-3.8.2.eb
> +        'source_tmpl': 'numpy_groupies-%(version)s.tar.gz',
You can remove this too if you use `numpy_groupies` as name instead two lines higher

2020-11-26 09:35 UTC, boegel commented on easybuild/easyconfigs/v/velocyto.py/velocyto.py-0.17.17-intel-2020a-Python-3.8.2.eb
> +        'modulename': 'velocyto',
No longer needed if you use `velocyto` as software name

2020-11-26 09:35 UTC, boegel commented on easybuild/easyconfigs/v/velocyto.py/velocyto.py-0.17.17-intel-2020a-Python-3.8.2.eb
> +        'source_urls': ['https://github.com/velocyto-team/velocyto.py/archive'],
Why not use `PyPI` here too, see https://pypi.org/project/velocyto/#files

2020-11-26 09:35 UTC, boegel commented on easybuild/easyconfigs/v/velocyto.py/velocyto.py-0.17.17-intel-2020a-Python-3.8.2.eb
> +    'velocyto'
style nitpicking: add trailing comma:
```python
sanity_check_commands = [
    'velocyto',
]

2020-11-27 19:29 UTC, lexming commented
@deniskristak thanks for addressing the review. I have also removed the easyconfig with the old name from this PR. In the future, if you ever need to delete easyconfigs from PRs using `eb`, you can do so by prepending `:` to the name of the easyconfig. For instance, in this case I did

```
eb --update-pr 11744 --pr-commit-msg "remove velocyto.py-0.17.17-intel-2020a-Python-3.8.2.eb" :velocyto.py-0.17.17-intel-2020a-Python-3.8.2.eb
```

2020-11-27 19:32 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node378.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/471b11847079a8bea11009e54a7d1363 for a full test report.

2020-11-27 19:32 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node128.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/77c857687ba2a785740d40feca2e8adc for a full test report.

2020-11-28 11:32 UTC, lexming approved these changes
LGTM

2020-11-28 11:33 UTC, lexming commented
Going in, thanks @deniskristak !

2020-11-28 11:33 UTC, merged