Avoid failing due to readdir_r being deprecated. https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8179887
easybuilders/easybuild-easyconfigs pull request #11755
Opened 2020-11-24 15:29 UTC by terjekv

(created using `eb --new-pr`)

2020-11-24 15:32 UTC, terjekv commented
@Flamefire Can you look at this and give it a whirl? It was required on RHEL8.3 on Power.

2020-11-27 12:05 UTC, Flamefire commented
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusml29 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/a21104bd78d74379aade734db89f51e6 for a full test report.

2020-11-27 19:02 UTC, lexming requested changes

2020-11-27 21:56 UTC, terjekv commented on easybuild/easyconfigs/j/Java/Java-1.8_191-b26-OpenJDK.eb
> +configopts = '--with-extra-cxxflags="-Wno-error" --with-extra-cflags="-Wno-error" --with-cacerts-file=/etc/pki/ca-trust/extracted/java/cacerts '
Fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/11755/commits/38b4e5b15fe352b8d230bae6dde2b3f1ae773f4d. Thanks!

2020-11-28 11:35 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node376.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c26c9481253a318f3c42da7455c39ecd for a full test report.

2020-11-28 11:36 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node128.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/aab37d62dead5ba627ce737c90833be1 for a full test report.

2020-11-28 11:37 UTC, terjekv commented
```
configure: error: Could not find all X11 headers (shape.h Xrender.h XTest.h Intrinsic.h). You might be able to fix this by running 'sudo yum install libXtst-devel libXt-devel libXrender-devel'.
configure exiting with result code 1
```
Why haven't we seen this before?

2020-11-28 11:42 UTC, lexming commented
@terjekv my test env is the best :sunglasses:

2020-11-28 11:48 UTC, terjekv commented
I thought that the OSDEP `('libXtst-devel', 'libxtst-dev'),` was supposed to fix that? Hm.

2020-11-28 11:49 UTC, lexming commented
I do not have `libXtst-devel` installed and EB failed to tell me that.

2020-11-28 11:50 UTC, terjekv commented
Okay, that's _bad_.

2020-11-28 12:32 UTC, lexming commented
@terjekv I found the issue, I always build with `--force` and that build option disables the validation of OS dependencies

2020-11-28 12:45 UTC, terjekv commented
`--rebuild`?

2020-11-28 13:04 UTC, boegel commented
@lexming This `Java` easyconfig is only relevant for POWER, no? See `Java-1.8.eb`.

2020-11-28 13:04 UTC, boegel commented
> `--rebuild`?

Indeed, `--force` is equivalent with `--rebuild --ignore-osdeps`

2020-11-28 13:10 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild1.novalocal - Linux centos linux 8.2.2004, POWER, IBM pSeries (emulated by qemu) (power8le), Python 3.6.8
See https://gist.github.com/fd81c1be3007055c412fbab863a9789f for a full test report.

2020-11-28 13:45 UTC, lexming commented
@boegel I'm so bad! how did I not think about `--rebuild` :smile:
Regarding the architecture, this is used for POWER just because the lack of support in Oracle Java, but OpenJDK still works in x86 systems as well.

2020-11-28 16:05 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login4.phoenix.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/e5b61f16fca153583661f37833dbde2a for a full test report.

2020-11-28 16:48 UTC, lexming commented
Going in, thanks @terjekv !

2020-11-28 16:48 UTC, merged