Clang: build lldb, don't disable optarch
easybuilders/easybuild-easyconfigs pull request #11814
Opened 2020-12-03 16:44 UTC by bartoldeman

(created using `eb --new-pr`)

2020-12-03 17:20 UTC, bartoldeman commented
@boegelbot please test @ generoso EB_ARGS="--include-easyblocks-from-pr 2264"

2020-12-03 17:20 UTC, bartoldeman commented
This needs https://github.com/easybuilders/easybuild-easyblocks/pull/2264

2020-12-03 18:43 UTC, Micket commented
@bartoldeman Any comment on the issue with optarch? Is the comment simply wrong?

2020-12-03 18:46 UTC, bartoldeman commented
> @bartoldeman Any comment on the issue with optarch? Is the comment simply wrong?

@Micket the comment is obsolete, it's copied from an earlier version but I had no issue building it with that line removed.

2020-12-03 18:50 UTC, bartoldeman commented
relevant commit for optarch:
fb453ae2063

2020-12-03 18:52 UTC, Micket approved these changes
lgtm

2020-12-03 19:10 UTC, Micket commented
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2264
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/18c997407aa03ea758afdf3d2cc96b25 for a full test report.

2020-12-03 19:19 UTC, Micket commented
I was wrong, it was very quick. Hmm
```
/local/EB/build/Clang/11.0.0/GCCcore-9.3.0/llvm-11.0.0.src/tools/lldb/bindings/./python/python-typemaps.swig:484: Error: Syntax error in input(3).
```

```
481 struct Py_buffer_RAII {
482   Py_buffer buffer = {};
483   Py_buffer_RAII() {};
484   Py_buffer &operator=(const Py_buffer_RAII &) = delete;
485   Py_buffer_RAII(const Py_buffer_RAII &) = delete;
486   ~Py_buffer_RAII() {
487     if (buffer.obj)
488       PyBuffer_Release(&buffer);
489   }
490 };
```
Looks fine to me, so I'm not sure what goes wrong here.

2020-12-03 19:46 UTC, bartoldeman commented
@micket perhaps it needs a build dep on swig, I my log I have:
```
-- Found SWIG: /cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/swig (found suitable version "3.0.12", minimum required is "2.0") 
```
perhaps you picked up an OS SWIG that is now too old.

2020-12-03 19:52 UTC, bartoldeman commented
I added the SWIG builddep because it's a good idea in any case.

2020-12-03 20:23 UTC, Micket requested changes

2020-12-03 20:23 UTC, Micket commented on easybuild/easyconfigs/c/Clang/Clang-11.0.0-GCCcore-9.3.0.eb
> +    ('SWIG', '4.0.1'),
perhaps also add a comment stating that it's a dep for lldb?
```suggestion
    ('SWIG', '4.0.1'),  # Optional dependency for LLDB
```

2020-12-03 21:14 UTC, Micket submitted a review, later dismissed
lgtm

2020-12-03 22:13 UTC, bartoldeman commented
@boegelbot please test @ generoso EB_ARGS="--include-easyblocks-from-pr 2264"

2020-12-03 22:13 UTC, bartoldeman commented
I asked the always friendly looking bot to do another build with the SWIG builddep

2020-12-03 22:21 UTC, Micket commented
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2264
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.8.2003, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/189e66058b6e606f9ed00c1e03d44019 for a full test report.

2020-12-03 23:42 UTC, Micket commented
@bartoldeman So.. Python turns out to be a runtime dependency;
```
$ lldb
lldb: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
```

2020-12-04 00:12 UTC, Micket commented
So, options as i see them
1. Just have python as a dependency here. Hurts a bit for a compiler though, since it means no multi-deps for anything using Clang.
2. Try to separate LLDB into a different module (probably painful) and let that module depend on Python.
3. Disable SWIG (we should probably enhance the easyblock to explicitly disable SWIG if no SWIG-dep is used regardless). 

I assume python dep comes from SWIG? If not, then, well, option 3 just disappears.

2020-12-04 00:29 UTC, bartoldeman commented
Maybe 2 (seperate lldb) is not too hard. Can give that a go.

2020-12-04 13:51 UTC, bartoldeman commented
11822 does LLDB now. Though we can still remove the optarch line I guess.

2021-01-04 18:28 UTC, verdurin commented
@bartoldeman what's the latest on this one?

2021-01-04 19:28 UTC, bartoldeman commented
still the same, I forgot about this one :(. Will adjust

2021-01-05 09:36 UTC, boegel commented
@boegelbot please test @ generoso

2021-01-05 10:13 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/c0a3e5e706d079a452c1225eb533affe for a full test report.

2021-01-05 12:01 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2641.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/24739a83ed6099ce78dc782377689c97 for a full test report.

2021-01-05 12:58 UTC, verdurin approved these changes
Looks fine.

2021-01-05 13:52 UTC, boegel commented
Going in, thanks @bartoldeman!

2021-01-05 13:52 UTC, merged