WIP: preliminary layout for OpenFOAM-v2012
easybuilders/easybuild-easyconfigs pull request #11876
Opened 2020-12-14 09:52 UTC by olesenm

Hi @boegel - a heads-up for the upcoming OpenFOAM-v2012

To help accommodate easybuild and other systems, we have an additional `FOAM_CONFIG_ETC` variable that we can hook into to quickly switch between different types of configurations (eg, intelmpi/openmpi, 64/32-bit, spdp/dp etc). It also can be used by easybuild to define its configuration, largely without patching the original sources.

The OpenFOAM internal mpi selector now recognizes "EASYBUILDMPI"  (no patching needed), and the readline discovery can be customized with the usual config.sh mechanism, which means that easybuild can generate its settings without patching into the wmake/scripts directory.  Using this approach, we are getting one step closer to being able to generate settings on-the-fly instead of patching. 

In this preliminary changeset, I did however run into issues with actually applying the patch for the build. EasyBuild complains about not being able to determine the patch level. Must be something small I guess, but figured I should provide the changeset anyhow to provide a basis and avoid duplicate effort.

2020-12-14 10:49 UTC, boegel commented
@olesenm Thanks a lot!

EasyBuild has some magic to automatically determine the patch level to use, which is derived from the first `+++` line in the patch. Shouldn't be difficult to fix, indeed. Worst case we can hard specify the correct patch level (`patches = [('example.patch', 1)]`, where `1` results in running `patch -p1`).

Any ETA for the OpenFOAM v2012 release?

2020-12-14 11:04 UTC, olesenm commented
> Any ETA for the OpenFOAM v2012 release?

Likely by Monday/Tuesday next week.

2020-12-14 11:33 UTC, olesenm commented
BTW: In case it is useful, the code-wiki is unfortunately a bit hard to find
https://develop.openfoam.com/Development/openfoam/-/wikis/home

If there is anything better that you would liked added in here:
https://develop.openfoam.com/Development/openfoam/-/wikis/building#packaging-systems

2020-12-21 23:04 UTC, olesenm commented
@boegel - on the final stretch...

2020-12-23 13:55 UTC, olesenm commented
https://sourceforge.net/projects/openfoam/files/v2012/

2020-12-27 16:57 UTC, boegel commented
@olesenm I tested this, and although the installation completes after ~1.5h, EasyBuild isn't entirely happy with it; the sanity check fails because the following files are missing in the installation:

```
OpenFOAM-v2012/platforms/linux64GccDPInt32Opt/lib/mpi/libPstream.so
OpenFOAM-v2012/platforms/linux64GccDPInt32Opt/lib/mpi/libptscotchDecomp.so
OpenFOAM-v2012/platforms/linux64GccDPInt32Opt/lib/libscotchDecomp.so
```

For `libPstream.so`, I found `lib/eb-mpi/libPstream.so` instead (`eb-mpi` rather than `mpi`).

For the other two, I couldn't find an equivalent, and I couldn't spot any obvious errors in the installation either.

Have there been changes in the v2012 that we should be aware of?

2020-12-29 16:15 UTC, olesenm commented
> ```
> OpenFOAM-v2012/platforms/linux64GccDPInt32Opt/lib/mpi/libPstream.so
> OpenFOAM-v2012/platforms/linux64GccDPInt32Opt/lib/mpi/libptscotchDecomp.so
> OpenFOAM-v2012/platforms/linux64GccDPInt32Opt/lib/libscotchDecomp.so
> ```
> 
> For `libPstream.so`, I found `lib/eb-mpi/libPstream.so` instead (`eb-mpi` rather than `mpi`).
> 
> For the other two, I couldn't find an equivalent, and I couldn't spot any obvious errors in the installation either.
> 
> Have there been changes in the v2012 that we should be aware of?

This is either a feature or an oops. The mpi handling was adjusted to avoid potential conflicts. The tag "mpi" was adjusted to "sys-mpi" (since that it is), similarly "openmpi-system" became "sys-openmpi" etc. (gives lib/sys-mpi, lib/sys-openmpi, lib/sys-openmpi4 etc). 
As part of the mpi adjustments, inserted handling of Easybuild with "eb-mpi" as its backend (yields lib/eb-mpi). Missed out on the fact that these would be trapped by a sanity check somewhere. Apologies for that. 

Here are some relevant commits
https://develop.openfoam.com/Development/openfoam/-/commit/c91fc6f41cc4d4f1ac782d4f7fd8c35ca4e5bea8

https://develop.openfoam.com/Development/openfoam/-/commit/b89f38960651701ed76a87e21c7a566fe0714f3c

.. again apologies for breaking the sanity check

2020-12-29 16:20 UTC, olesenm commented
Might need to check if the scotch detection is working as expected/desired.
After Easybuild has generated its config.sh/ files for OpenFOAM, can check using
```
sh wmake/scripts/have_scotch -test
```

2021-01-27 11:32 UTC, furstj commented
@olesenm Your proposed new layout requires patched openfaom easyblock. You can try it with easyblock from pr #2321, see https://github.com/easybuilders/easybuild-easyblocks/pull/2321. 

Moreover, the correct patch level in openfoam easyconfig file should be 1, i.e.

`
patches = [
    ('OpenFOAM-%(version)s-cleanup.patch', 1),
    'OpenFOAM-v1906-wmake-ompi.patch',
]
`

2021-02-04 11:17 UTC, boegel commented
@furstj Did you manage to install OpenFOAM v2012 with this PR and the updated easyblock from https://github.com/easybuilders/easybuild-easyblocks/pull/2321? Did you have to change anything other than the `patches` part?

2021-02-04 12:25 UTC, furstj commented
@boegel Yes, I was able to install OPenFOAMv2012 withudated easyblock when I changed patches part.

2021-02-04 13:53 UTC, Micket requested changes

2021-02-04 13:53 UTC, Micket commented on easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2012-foss-2020a.eb
> +    ('OpenFOAM-%(version)s-cleanup.patch', 0),
@furstj suggestion in one easy click;
```suggestion
    ('OpenFOAM-%(version)s-cleanup.patch', 1),
```

2021-02-04 19:47 UTC, boegel commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2321"
CORE_CNT=16

2021-02-05 12:59 UTC, boegel approved these changes
lgtm

2021-02-05 14:31 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3624.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/2310e4c6f0ae93ac268cbdc4c9692caf for a full test report.

2021-02-05 14:43 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2613.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/d99af81344eeb68429606d1f71843ce8 for a full test report.

2021-02-05 14:50 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3162.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/424d9e1e418c2450ad0e15e55586a00e for a full test report.

2021-02-14 10:58 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3142.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/8e4fe4ef37fc4b86abadd458425401ed for a full test report.

2021-02-14 19:06 UTC, boegel commented
Going in, thanks @olesenm!

2021-02-14 19:06 UTC, merged

2021-02-18 16:54 UTC, Micket commented
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2321
**SUCCESS**
Build succeeded for 8 out of 8 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/4e15f6d0f92faa36206c596d9b5eaef9 for a full test report.