libgit2 GCCcore-10.2.0
easybuilders/easybuild-easyconfigs pull request #11927
Opened 2020-12-22 20:16 UTC by fizwit

(created using `eb --new-pr`)

2020-12-22 20:27 UTC, Micket requested changes

2020-12-22 20:27 UTC, Micket commented on easybuild/easyconfigs/l/libgit2/libgit2-1.1.0-GCCcore-10.2.0.eb
> +osdependencies = [('openssl-devel', 'libssl-dev', 'libopenssl-devel')]
```suggestion
osdependencies = [OS_PKG_OPENSSL_DEV]
```

2020-12-22 20:27 UTC, Micket commented on easybuild/easyconfigs/l/libgit2/libgit2-1.1.0-GCCcore-10.2.0.eb
> +    ('PCRE', '8.44'),
Please include in the dependencies list:
```
     # ('OpenSSL', '1.1.1h')
     # OS dependency should be preferred if the os version is more recent than this version
```

2020-12-22 20:36 UTC, Micket approved these changes
lgtm

2020-12-22 20:37 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/338047781c61011d36e3d91e602d70d1 for a full test report.

2020-12-22 22:37 UTC, Micket commented
Going in, thanks @fizwit!

2020-12-22 22:37 UTC, merged

2020-12-27 09:48 UTC, boegel commented
@boegelbot please test @ generoso