{cae}[foss/2020b] OpenFOAM v8, ParaView v5.8.1, CGAL v5.2
easybuilders/easybuild-easyconfigs pull request #11970
Opened 2021-01-08 11:32 UTC by boegel

(created using `eb --new-pr`)

2021-01-08 11:35 UTC, boegel commented
@boegelbot please test @ generoso

2021-01-08 11:48 UTC, boegel commented
@boegelbot please test @ generoso
CORE_COUNT=16

2021-01-08 12:51 UTC, boegel commented on easybuild/easyconfigs/p/ParaView/ParaView-5.8.1-foss-2020b-mpi.eb
> +configopts += '-DVTK_OPENGL_HAS_OSMESA=ON '
This may need to be dropped, cfr. discussion in #10989 and #10977...

2021-01-08 13:51 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3555.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/f10241d37486a25321dcf361ab328359 for a full test report.

2021-01-08 14:30 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3136.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/dc2287ab80c02af441945b001c924713 for a full test report.

2021-01-08 22:22 UTC, boegel commented
@boegelbot please test @ generoso

2021-01-09 04:11 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2649.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/627801edc54260cc8fb8c740f6f55411 for a full test report.

2021-01-09 13:37 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3108.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/5e149d8a2965c1c270820b4264ce4282 for a full test report.

2021-01-10 11:09 UTC, furstj commented
Test report by @furstj
**SUCCESS**
Build succeeded for 7 out of 7 (3 easyconfigs in total)
pc-12101-fuji - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz, Python 3.6.12
See https://gist.github.com/9e14b0fa34e8e998ab6a81c79f95946b for a full test report.

2021-01-17 00:03 UTC, Mormacill commented
@boegel:
Don't forget about gnuplot dependency as mentioned in #11770.
Also check #11975 and #11974

2021-01-28 10:11 UTC, Mormacill commented
> 
> 
> @boegel:
> Don't forget about gnuplot dependency as mentioned in #11770.
> Also check #11975 and #11974

gnuplot 5.4.1 GCCcore/10.2.0 #12051

2021-02-19 11:47 UTC, branfosj requested changes

2021-02-19 11:47 UTC, branfosj commented on easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-8-foss-2020b.eb
> +]
```suggestion
    ('gnuplot', '5.4.1'),
]
```

Add gnuplot, as per https://github.com/easybuilders/easybuild-easyblocks/pull/2256

2021-02-19 13:34 UTC, branfosj approved these changes
lgtm

2021-02-19 15:04 UTC, branfosj commented
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2256
**SUCCESS**
Build succeeded for 11 out of 11 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/eb3c5b0570eb49758d68511265c663f2 for a full test report.

2021-02-19 15:15 UTC, branfosj commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 2256"

2021-02-20 18:02 UTC, branfosj commented
Going in, thanks @boegel!

2021-02-20 18:02 UTC, merged