{math}[GCCcore/9.3.0] Gurobi v9.0.1 w/ Python 3.8.2
easybuilders/easybuild-easyconfigs pull request #11983
Opened 2021-01-11 15:38 UTC by lexming

(created using `eb --new-pr`)

2021-01-11 20:04 UTC, boegel requested changes

2021-01-11 20:04 UTC, boegel commented on easybuild/easyconfigs/g/Gurobi/Gurobi-9.0.1-GCCcore-9.3.0-Python-3.8.2.eb
> +postinstallcmds = ['rm %(installdir)s/bin/python3.7']
@lexming Maybe this should be a bit more generic?

```python
postinstallcmds = ['rm %(installdir)s/bin/python*']
```

2021-01-11 20:10 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2635.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/dedc658d0a33f1720f7b876cf1fe5c0a for a full test report.

2021-01-17 15:24 UTC, lexming commented on easybuild/easyconfigs/g/Gurobi/Gurobi-9.0.1-GCCcore-9.3.0-Python-3.8.2.eb
> +postinstallcmds = ['rm %(installdir)s/bin/python3.7']
fixed :+1:

2021-01-17 15:33 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8fcb90729d00f6820227874e4175c2c0 for a full test report.

2021-05-11 12:39 UTC, lexming commented
@boegelbot yes :+1:

2021-05-11 12:40 UTC, lexming commented
@boegel  yes :+1:

2021-12-08 15:52 UTC, boegel approved these changes

2021-12-08 15:55 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3108.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/f282ddc3742e2cb38f465c9c2d84d7e5 for a full test report.

2021-12-08 17:44 UTC, boegel commented
Going in, thanks @lexming!

2021-12-08 17:44 UTC, merged