{bio}[gompi/2020a] fpocket v3.1.4.2
easybuilders/easybuild-easyconfigs pull request #11980
Opened 2021-01-11 08:33 UTC by bedroge

(created using `eb --new-pr`)

2021-01-11 08:35 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
pg-interactive.hpc.rug.nl - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/8e06f124992ea4bf9648b7ae1b5e4810 for a full test report.

2021-01-13 09:25 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node378.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/05215715513c18f2b6dd88796093e225 for a full test report.

2021-01-13 13:12 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node104.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/3fb6ddd668b934774bea3728247903cf for a full test report.

2021-01-13 23:40 UTC, lexming requested changes
The build of `fpocket` works well but it ignores the `CFLAGS` from EB. I suggest to fix it in the Makefile as well. Please see below

2021-01-13 23:40 UTC, lexming commented on easybuild/easyconfigs/f/fpocket/fpocket-3.1.4.2-gompi-2020a.eb
> +
```suggestion
# Use CFLAGS from EB
prebuildopts += 'sed -i "s/-O2.*c99/$CFLAGS/g" makefile && '

```

2021-01-13 23:40 UTC, lexming commented on easybuild/easyconfigs/f/fpocket/fpocket-3.1.4.2-gompi-2020a.eb
> +
```suggestion
toolchainopts = {'usempi': False, 'cstd': 'c99'}

```

2021-01-14 09:31 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/189623f6b69457d870d90ee9000f3496 for a full test report.

2021-01-14 09:32 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node109.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, Python 2.7.5
See https://gist.github.com/21023f2506d1ffe590dbacea616c905c for a full test report.

2021-01-14 09:46 UTC, lexming approved these changes
LGTM

2021-01-14 09:46 UTC, lexming commented
Going in, thanks @bedroge !

2021-01-14 09:46 UTC, merged