{bio}[GCC/10.2.0] manta v1.6.0 w/ Python 3.8.6
easybuilders/easybuild-easyconfigs pull request #12006
Opened 2021-01-15 12:40 UTC by deniskristak

(created using `eb --new-pr`)

2021-01-15 20:07 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3123.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/6e9c18f6ba42eec8052e2f12c0ccf8d3 for a full test report.

2021-01-15 20:15 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/9929e740d25ddefc81ca113aa2bb67b4 for a full test report.

2021-01-15 20:16 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3123.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/dda9473336e0bdf26af223aeff19ba98 for a full test report.

2021-01-15 20:17 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2629.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/ecdf7d9581900dd2e199545f9173d4a5 for a full test report.

2021-01-15 20:28 UTC, boegel commented
@deniskristak Test report failed on RHEL8 with:

```
*** Error compiling '/tmp/easybuild_build/manta/1.6.0/GCC-10.2.0/easybuild_obj/redist/pyflow-1.1.20/src/pyflow.py'...
  File "/tmp/easybuild_build/manta/1.6.0/GCC-10.2.0/easybuild_obj/redist/pyflow-1.1.20/src/pyflow.py", line 791
    dsfp = os.fdopen(os.open(taskDotScriptFile, os.O_WRONLY | os.O_CREAT, 0755), 'w')
                                                                             ^                                                                                                                              

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers

make[2]: *** [redist/CMakeFiles/manta_pyflow.dir/build.make:83: redist/pyflow-1.1.20/src/pyflow.pyc] Error 1
```

2021-01-19 11:40 UTC, deniskristak commented
@boegel can be tested again, fixed aforementioned error and added an extra piece for python3 compatibility

2021-01-19 15:27 UTC, boegel requested changes

2021-01-19 15:27 UTC, boegel commented on easybuild/easyconfigs/m/manta/manta-1.6.0-GCC-10.2.0.eb
> +# preinstallopts = patch -i
@deniskristak Please remove this commented out line?

2021-01-19 15:27 UTC, boegel commented on easybuild/easyconfigs/m/manta/manta-1.6.0-GCC-10.2.0.eb
> +preinstallopts += """sed -i "s/DataDirException, e/DataDirException(e)/g" ./redist/pyflow-1.1.20/src/pyflow.py && """
@deniskristak Let's avoid using `"""` by using single quotes inside each command, which is safer anyway w.r.t. handling of special characters (there are none here, but fine)?

Also, maybe avoid hardcoding the version of the `pyflow` subdir by using `*`?

```python
preinstallopts = "sed -i 's/0755/0o755/g' ./redist/pyflow-*/src/pyflow.py && "
preinstallopts += "sed -i 's/DataDirException, e/DataDirException(e)/g' ./redist/pyflow-*/src/pyflow.py && "

2021-01-19 15:27 UTC, boegel commented on easybuild/easyconfigs/m/manta/manta-1.6.0-GCC-10.2.0.eb
> +# patches = ['manta-1.6_python3_compatibility.patch']
@deniskristak Please remove this commented out line?

2021-02-05 22:23 UTC, smoors requested changes

2021-02-05 22:23 UTC, smoors commented on easybuild/easyconfigs/m/manta/manta-1.6.0-GCC-10.2.0.eb
> +
@deniskristak can you add sanity check commands for one or two of the binaries and python scripts?

2021-02-08 21:15 UTC, boegel commented
@boegelbot please test @ generoso

2021-03-05 10:24 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/5f11b330c383a934aa381108c0a4254d for a full test report.

2021-03-05 10:49 UTC, boegel commented
@deniskristak The installation still fails for me, the problem already occurs during the `build` step (so using `sed` in`preinstallopts` doesn't help) is that `pyflow` is only unpacked *during* the build step.

One possible alternative way of fixing the issue could patching the `Makefile` in which the unpacking of `pyflow` is done?

2021-03-10 09:32 UTC, deniskristak commented
@boegel closing this request, moved it to [https://github.com/easybuilders/easybuild-easyconfigs/pull/12359](url)

2021-03-10 09:32 UTC, closed without merging