{devel,lib}[fosscuda/2020a] protobuf-python v3.13.0, TensorFlow v2.3.1 w/ Python 3.8.2
easybuilders/easybuild-easyconfigs pull request #12064
Opened 2021-01-31 10:26 UTC by branfosj

(created using `eb --new-pr`)

2021-01-31 11:23 UTC, branfosj commented
@boegelbot please test @ generoso

2021-01-31 11:26 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0305u11a.bear.cluster - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/2e2b92719a9450bf77c5c3ed3437122c for a full test report.

2021-01-31 11:52 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0212u17a.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), Python 3.6.8
See https://gist.github.com/cb9a092d9b64bf14632e8225e244ece8 for a full test report.

2021-02-02 09:59 UTC, lexming requested changes
Now that https://github.com/easybuilders/easybuild-framework/pull/3541 is merged, could you please update `TensorFlow-2.3.1-fosscuda-2020a-Python-3.8.2.eb` to use the `cudaver` template? See suggestion below

2021-02-02 09:59 UTC, lexming commented on easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1-fosscuda-2020a-Python-3.8.2.eb
> +    ('NCCL', '2.8.3', '-CUDA-11.0.2', True),
```suggestion
    ('cuDNN', '8.0.4.30', '-CUDA-%(cudaver)s', True),
    ('NCCL', '2.8.3', '-CUDA-%(cudaver)s', True),
```

2021-02-02 15:59 UTC, branfosj commented
> Now that [easybuilders/easybuild-framework#3541](https://github.com/easybuilders/easybuild-framework/pull/3541) is merged, could you please update `TensorFlow-2.3.1-fosscuda-2020a-Python-3.8.2.eb` to use the `cudaver` template? See suggestion below

Done. Test reports started.

2021-02-02 16:37 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0305u03a.bear.cluster - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/e0f3d18d414c4e113a2d6f584552b9e9 for a full test report.

2021-02-02 17:02 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0212u15b.bear.cluster - Linux centos linux 8.2.2004, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), Python 3.6.8
See https://gist.github.com/fb2472024e1de76e87b3891b64f9c8ce for a full test report.

2021-02-04 04:46 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node250.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, Python 2.7.5
See https://gist.github.com/a973c8efc6157df1c69a90ce0fa9610d for a full test report.

2021-02-04 09:14 UTC, lexming approved these changes
LGTM

2021-02-04 09:16 UTC, lexming commented
Going in, thanks @branfosj !

2021-02-04 09:16 UTC, merged