{data}[GCCcore/10.2.0] PostgreSQL 13.2
easybuilders/easybuild-easyconfigs pull request #12143
Opened 2021-02-12 06:18 UTC by fizwit

(created using `eb --new-pr`)

2021-02-12 17:04 UTC, Micket requested changes

2021-02-12 17:04 UTC, Micket commented on easybuild/easyconfigs/p/PostgreSQL/PostgreSQL-13.2-GCCcore-10.2.0.eb
> +    # ('OpenSSL', '1.0.2h'),
```suggestion
    # ('OpenSSL', '1.1.1h'),
```

2021-02-12 17:04 UTC, Micket commented on easybuild/easyconfigs/p/PostgreSQL/PostgreSQL-13.2-GCCcore-10.2.0.eb
> +osdependencies = [('openssl-devel', 'libssl-dev', 'libopenssl-devel')]
```suggestion
osdependencies = [OS_PKG_OPENSSL_DEV]
```

2021-02-15 14:42 UTC, branfosj approved these changes
lgtm

2021-02-15 14:42 UTC, branfosj commented
@boegelbot please test @ generoso

2021-02-15 14:50 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/a0f77ea6bc4af96abb2ef13b23e68f95 for a full test report.

2021-02-15 15:04 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0305u15a.bear.cluster - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/1a4eabb321586b85f9b31a25d63d05bc for a full test report.

2021-02-15 15:05 UTC, branfosj commented
Going in, thanks @fizwit!

2021-02-15 15:05 UTC, merged