Set HTSLIB_DIR in HTSlib for use by EnsEMBLCoreAPI
easybuilders/easybuild-easyconfigs pull request #12253
Opened 2021-02-23 14:49 UTC by verdurin

(created using `eb --new-pr`)

2021-02-23 14:50 UTC, verdurin commented
Many thanks to @lexming who suggested the fix.

2021-02-23 15:32 UTC, lexming commented on easybuild/easyconfigs/h/HTSlib/HTSlib-1.9-GCC-8.2.0-2.31.1.eb
> +# required for EnsEMBLCoreAPI
I just saw that Bio-DB-HTS, which is also from Ensembl, needs this as well
```suggestion
# required for Bio-DB-HTS and EnsEMBLCoreAPI
```

2021-02-23 15:32 UTC, lexming commented on easybuild/easyconfigs/e/EnsEMBLCoreAPI/EnsEMBLCoreAPI-96.0-r20190601-foss-2019a-Perl-5.28.1.eb
> +# HTSLIB_DIR must be set in HTSlib
I would not say anything here, without any reference it will be very confusing
```suggestion
```

2021-02-24 13:46 UTC, lexming requested changes
I checked more carefully the code in EnsEMBLCoreAPI and Bio-DB-HTS. This variable is actually only needed at build time by those packages. So having it permanently set by `HTSlib` is not the best solution
* In EnsEMBLCoreAPI, it is already declared in its `postinstallcmd` (where it is needed). So there is nothing to do there apart from removing the `modextrapath`.
* In Bio-DB-HTS, it has to be set before the `perl Build.PL` command in the config step. I made a PR to yours with this change. Please check https://github.com/verdurin/easybuild-easyconfigs/pull/7

2021-02-24 20:59 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f2d786f697af51094001e2b0045add78 for a full test report.

2021-02-24 22:00 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/6b4e6f6a7a4595cf5c3a76b2aa957faf for a full test report.

2021-02-24 22:03 UTC, lexming approved these changes
LGTM

2021-02-24 22:03 UTC, lexming commented
Going in, thanks @verdurin !

2021-02-24 22:03 UTC, merged