{bio}[GCCcore/9.3.0] parallel-fastq-dump v0.6.6 w/ Python 3.8.2
easybuilders/easybuild-easyconfigs pull request #12286
Opened 2021-02-25 16:06 UTC by boegel

(created using `eb --new-pr`)

2021-02-25 16:13 UTC, boegel commented
@boegelbot please test @ generoso

2021-02-25 16:13 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3521.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/ee64d24bc505bf8e180b43fa85b96ad7 for a full test report.

2021-02-25 16:14 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node3152.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/b3f71eba0b577220fb1bb536bab837ba for a full test report.

2021-03-03 16:40 UTC, verdurin requested changes

2021-03-03 16:40 UTC, verdurin commented on easybuild/easyconfigs/p/parallel-fastq-dump/parallel-fastq-dump-0.6.6-GCCcore-9.3.0-Python-3.8.2.eb
> +use_pip = True
@boegel please add `sanity_pip_check`.

2022-02-26 16:50 UTC, boegel commented
@boegelbot please test @ generoso

2022-02-26 16:51 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3508.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/bba69c09638bc3faa8b758b8090bf79e for a full test report.

2022-02-26 17:04 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node2626.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/fe74cb400cfcada7487efcd6685acdff for a full test report.

2022-03-17 08:08 UTC, boegel commented
@verdurin Good to go?

2022-03-22 19:24 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
centos7.lan - Linux CentOS Linux 7.9.2009, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/27d03b4aac10589686f298560509fa9d for a full test report.

2022-03-22 19:25 UTC, verdurin commented
Going in, thanks @boegel!

2022-03-22 19:25 UTC, merged