switching back to pip-20.1.1 to fix error in building Python-2.7.18-G…
easybuilders/easybuild-easyconfigs pull request #12293
Opened 2021-02-25 23:44 UTC by algiar

…CCcore-10.2.0

2021-02-27 10:45 UTC, boegel requested changes

2021-02-27 10:45 UTC, boegel commented on easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-10.2.0.eb
> +    ('pip', '20.1.1', {
@algiar Please use `20.3.4` instead (the latest version of `pip` which still supports Python 2), see discussion in https://github.com/easybuilders/easybuild-easyconfigs/issues/12016#issuecomment-787052638.

2021-02-27 15:32 UTC, Mormacill commented
Test report by @Mormacill
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
host02.mebus - Linux oracle linux server 8.3, x86_64, Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz, Python 3.6.8
See https://gist.github.com/7b771a41503bd9f066c488041d5f549b for a full test report.

2021-02-27 15:32 UTC, Mormacill commented
Test report by @Mormacill
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node01.mebus - Linux centos linux 7.9.2009, x86_64, Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz, Python 3.6.8
See https://gist.github.com/78a6ab54e2362d9f5c277cf82d9ccd04 for a full test report.

2021-02-27 21:34 UTC, Mormacill commented
Test report by @Mormacill
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node03.mebus - Linux ubuntu 18.04, x86_64, Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz, Python 3.6.9
See https://gist.github.com/64d9b4cd256f183ccfd9fb5e9a7ccae1 for a full test report.

2021-03-02 21:57 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node313.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e096b60d6f702f87714b7eb12e11575d for a full test report.

2021-03-02 22:18 UTC, lexming approved these changes
LGTM

2021-03-02 22:19 UTC, lexming commented
Going in, thanks @algiar !

2021-03-02 22:19 UTC, merged