add sanity check commands for vorbis-tools
easybuilders/easybuild-easyconfigs pull request #12304
Opened 2021-02-27 08:27 UTC by boegel

(created using `eb --new-pr`)
`vcut` doesn't support --help, so I had to deal with that separately in sanity_check_paths

2021-02-27 08:28 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3102.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/1dcf811ac5251610fc7e2beea5f54644 for a full test report.

2021-02-27 08:29 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/a8f0f8cd76bb6073a5a7cd2cc1cba614 for a full test report.

2021-02-27 16:53 UTC, Micket requested changes

2021-02-27 16:53 UTC, Micket commented on easybuild/easyconfigs/v/vorbis-tools/vorbis-tools-1.4.2-GCCcore-10.2.0.eb
> +    'files': ['bin/%s' % x for x in local_bins] + ['bin/vcut'],
why separate out vcut?

2021-03-02 21:27 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 4 out of 4 (1 easyconfigs in total)
node356.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/0b2756dea5118f668cf138b61d77dd87 for a full test report.

2021-03-02 21:34 UTC, boegel commented on easybuild/easyconfigs/v/vorbis-tools/vorbis-tools-1.4.2-GCCcore-10.2.0.eb
> +    'files': ['bin/%s' % x for x in local_bins] + ['bin/vcut'],
Because `vcut` doesn't support `--help`

2021-03-02 21:37 UTC, lexming approved these changes
LGTM

2021-03-02 21:38 UTC, lexming commented
Going in, thanks @boegel !

2021-03-02 21:38 UTC, merged