add dl poly 4 easyconfigs
easybuilders/easybuild-easyconfigs pull request #12324
Opened 2021-03-02 19:20 UTC by alinelena

2021-03-02 21:11 UTC, zao commented
Test report by @zao
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
eb-u2004 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.5
See https://gist.github.com/5b7258cdbfa635a1e4985fb7a601c157 for a full test report.

2021-03-02 21:16 UTC, zao commented
* A build dependency on `CMake` is needed.

* Is the `tar` dance with the sources necessary, can't it be handled with `filename` and/or `download_filename`?

* Normally `sources_urls` is separate from the `sources` list unless there's a need to avoid collisions.

2021-03-02 21:25 UTC, Micket requested changes
in addition to what zao wrote

2021-03-02 21:25 UTC, Micket commented on easybuild/easyconfigs/d/DL_POLY_4/DL_POLY_4-5.0.0-foss-2020b.eb
> +description = "classical md"
```suggestion
description = "DL_POLY is a general purpose classical molecular dynamics (MD) simulation software"
```

2021-03-02 21:25 UTC, Micket commented on easybuild/easyconfigs/d/DL_POLY_4/DL_POLY_4-5.0.0-intel-2020b.eb
> +description = "classical md"
```suggestion
description = "DL_POLY is a general purpose classical molecular dynamics (MD) simulation software"
```

2021-03-02 22:16 UTC, zao commented
Test report by @zao
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
eb-u2004 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.5
See https://gist.github.com/71a1f38194c7b56ab3f8df99560a1d0c for a full test report.

2021-03-05 22:57 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node354.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/19f691531823416295fb84f59bd55347 for a full test report.

2021-03-06 00:52 UTC, lexming approved these changes
LGTM

2021-03-06 00:54 UTC, lexming commented
Going in, thanks @alinelena !

2021-03-06 00:54 UTC, merged