{bio}[system/system] BOLT-LMM v2.3.4
easybuilders/easybuild-easyconfigs pull request #12334
Opened 2021-03-04 10:49 UTC by verdurin

(created using `eb --new-pr`)

2021-03-05 08:33 UTC, Micket requested changes

2021-03-05 08:33 UTC, Micket commented on easybuild/easyconfigs/b/BOLT-LMM/BOLT-LMM-2.3.4.eb
> + This model generalizes the standard “infinitesimal” mixed model used by previous mixed model
Might be best to avoid fancy unicode “”

2021-03-05 22:49 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node320.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/63412c32d5ff29794cfd2ce6e6ab63cd for a full test report.

2021-03-06 00:32 UTC, lexming requested changes

2021-03-06 00:32 UTC, lexming commented on easybuild/easyconfigs/b/BOLT-LMM/BOLT-LMM-2.3.4.eb
> +
This `modextrapaths` is done by default by EB and can be removed
```suggestion
```

2021-03-08 20:46 UTC, verdurin commented
@boegelbot please test @ generoso

2021-03-11 09:43 UTC, Micket approved these changes

2021-03-11 11:05 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3508.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/61f7ef5157ab9dba0527938f64082a81 for a full test report.

2021-03-24 17:29 UTC, verdurin commented
@boegel is that `sanity_check` failure the result of the binary not working on your AMD node?

2023-10-23 11:12 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/6f28eacc501e05e4e407c21038438384 for a full test report.

2023-10-23 11:52 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3591.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/boegel/7fa5b3c749f8bb54449f11551aee827e for a full test report.

2023-10-23 13:22 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2023-10-23 13:45 UTC, boegel commented
> @boegel is that `sanity_check` failure the result of the binary not working on your AMD node?

Indeed, looks like these pre-built binaries simply don't work on AMD CPUs?

2023-10-23 14:55 UTC, verdurin commented
Do we have a way of handling that kind of exception, similar to what we do for ARM etc?


From: Kenneth Hoste ***@***.***>
Date: Monday, 23 October 2023 at 14:47
To: easybuilders/easybuild-easyconfigs ***@***.***>
Cc: Adam Huffman ***@***.***>, Mention ***@***.***>
Subject: Re: [easybuilders/easybuild-easyconfigs] {bio}[system/system] BOLT-LMM v2.3.4 (#12334)

@boegel<https://github.com/boegel> is that sanity_check failure the result of the binary not working on your AMD node?

Indeed, looks like these pre-built binaries simply don't work on AMD CPUs?

—
Reply to this email directly, view it on GitHub<https://github.com/easybuilders/easybuild-easyconfigs/pull/12334#issuecomment-1775236226>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAADBEZDL6PIKUNCDWZVPWDYAZYJFAVCNFSM4YTAIBDKU5DIOJSWCZC7NNSXTN2JONZXKZKDN5WW2ZLOOQ5TCNZXGUZDGNRSGI3A>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-23 20:49 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node301.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/lexming/17fc9374e6731866c66a36aa2480fc88 for a full test report.

2023-10-23 21:07 UTC, lexming requested changes
I tried v2.3.4, v2.3.6 and v2.4.1 (latest) on a AMD zen2 and none of the binaries work.

Using the bundled `libiomp5.so` or those from `intel/2021a` or `intel/2022a` makes no difference either.

IMO we should not distribute this binary as it is not compiled in a way that will work reliably on x86_64.

Solution is to compile from source. The tarball contains a `src` directory with the sources and a Makefile that we could use as starting point for the build.

2025-04-16 16:03 UTC, jfgrimm commented
@verdurin @lexming closing this since it's gone stale. 
I've made a new PR that builds BOLT-LMM from source: https://github.com/easybuilders/easybuild-easyconfigs/pull/22771

2025-04-16 16:03 UTC, closed without merging