{bio}[foss/2019b] RevBayes + deps
easybuilders/easybuild-easyconfigs pull request #12399
Opened 2021-03-15 09:12 UTC by YensyGomez

2021-03-15 17:01 UTC, Micket requested changes
Does this require Boost 1.74? If not, please use 1.71.0 that already exists for 2019b, since it would make this module more compatible with other 2019b modules.
If it does require it, then there is already a newer bzip2 version for GCCcore 8.3.0 so a foss version should be added.

2021-03-16 21:36 UTC, boegel requested changes
@YensyGomez Would it be possible to include a simple test command like `rb --help` in `sanity_check_commands`?

2021-03-16 21:36 UTC, boegel commented on easybuild/easyconfigs/r/RevBayes/RevBayes-1.1.1-foss-2019b.eb
> +    ('Boost', '1.71.0'),
@YensyGomez It doesn't make sense to include `Boost` as a dependency twice, only via `dependencies` is fine (unless `Boost` is only a build dependency, then only via `builddependencies` of course)

2021-03-16 23:12 UTC, Micket commented
We have 2 RevBayes PRs right now, and they differ slightly.
#12411 includes Java, and has slightl configure flags. I don't know which is more correct

2022-08-08 13:50 UTC, boegel commented
Closing this PR since there's no reply at all after the review...

2022-08-08 13:50 UTC, closed without merging