{vis}[GCC/10.2.0] GStreamer 1.18.3
easybuilders/easybuild-easyconfigs pull request #12392
Opened 2021-03-13 02:30 UTC by fizwit

(created using `eb --new-pr`)

2021-03-13 09:53 UTC, branfosj requested changes
Generally this looks fine. Thanks for sorting out the new build method.

2021-03-13 09:53 UTC, branfosj commented on easybuild/easyconfigs/g/GStreamer/GStreamer-1.18.3-GCC-10.2.0.eb
> +    #  ('gettext', '0.21'),  can't find any referance to gettext
```suggestion
    #  ('gettext', '0.21'),  can't find any referance to gettext
```

In the build log there is `Program xgettext found: YES`, so we should keep this as a builddep.

2021-03-13 09:53 UTC, branfosj commented on easybuild/easyconfigs/g/GStreamer/GStreamer-1.18.3-GCC-10.2.0.eb
> +
To match the `configopts = '--with-dw=no '` in the previous easyconfigs we can set `configopts = "-Dlibdw=disabled "`.

2021-03-13 09:53 UTC, branfosj commented on easybuild/easyconfigs/g/GStreamer/GStreamer-1.18.3-GCC-10.2.0.eb
> +    'files': [],
We should enhance the sanity check. My suggestion would be to check for the existence of some of the shared libraries here. So, `'files': ['lib/libgstbase-1.0.%s' % SHLIB_EXT, 'lib/libgstreamer-1.0.%s' % SHLIB_EXT],`

2021-03-13 09:53 UTC, branfosj commented on easybuild/easyconfigs/g/GStreamer/GStreamer-1.18.3-GCC-10.2.0.eb
> +    ('libffi', '3.3'),  # new, ldd found links to libffi
```suggestion
    ('libffi', '3.3'),
```

2021-03-19 20:04 UTC, fizwit commented
need this for WebKitGTK+ 2.30.6  #pr 12434

2023-06-28 13:39 UTC, closed without merging