{phys}[foss/2020b,intel/2020b] ASAP3 v3.12.3 w/ Python 3.8.6
easybuilders/easybuild-easyconfigs pull request #12449
Opened 2021-03-22 16:56 UTC by schiotz

(created using `eb --new-pr`)

2021-03-22 16:57 UTC, schiotz commented
This is a bug-fix release of Asap, fixing a memory leak introduced in version 3.12.1.

2021-03-29 12:49 UTC, smoors requested changes

2021-03-29 12:49 UTC, smoors commented on easybuild/easyconfigs/a/ASAP3/ASAP3-3.12.3-foss-2020b-ASE-3.21.1.eb
> +source_urls = [PYPI_LOWER_SOURCE]
please remove this line, it is now the default for PythonPackages and PythonBundles.

2021-03-29 12:49 UTC, smoors commented on easybuild/easyconfigs/a/ASAP3/ASAP3-3.12.3-intel-2020b-ASE-3.21.1.eb
> +source_urls = [PYPI_LOWER_SOURCE]
same here.

2021-04-19 13:04 UTC, schiotz commented
@smoors 
Thank you for your feedback.  I have stalled on this one because I found a couple of bugs in Asap, and I wanted to squash them first - one of them was a bit tricky.  I expect to release a new version tomorrow or Wednesday, and then I will use the feedback of this one to make a new PR with the newest version.

2021-04-21 14:23 UTC, schiotz commented
Withdrawn.  This PR is made obsolete by #12703.

2021-04-21 14:23 UTC, closed without merging