{bio}[foss/2020b] SIMPLE v3.0.0
easybuilders/easybuild-easyconfigs pull request #12457
Opened 2021-03-23 17:12 UTC by ThomasHoffmann77

(created using `eb --new-pr`)

2021-03-23 20:36 UTC, boegel commented
@ThomasHoffmann77 Are you up for looking into fixing the reported style issue?

You can get a detailed overview using `eb --check-style`, see below.

<details>

```
$ eb --from-pr 12457 --check-style
== Temporary log file in case of crash /tmp/eb-qh7x87hr/easybuild-4pe_785j.log

Running style check on 1 easyconfig(s)...

/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:1:1: E265 block comment should start with '# '
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:13:14: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:13:45: E261 at least two spaces before inline comment
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:13:46: E262 inline comment should start with '# '
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:15:12: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:16:15: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:21:13: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:22:1: E122 continuation line missing indentation or outdented
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:22:6: E231 missing whitespace after ','
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:23:1: E122 continuation line missing indentation or outdented
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:23:11: E231 missing whitespace after ','
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:24:1: E122 continuation line missing indentation or outdented
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:24:11: E231 missing whitespace after ','
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:26:14: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:27:14: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:27:116: E261 at least two spaces before inline comment
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:27:117: E262 inline comment should start with '# '
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:27:121: E501 line too long (156 > 120 characters)
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:29:11: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:29:38: W299 trailing whitespace
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:30:11: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:31:11: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:32:11: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:33:11: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:34:11: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:35:11: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:36:11: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:37:11: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:38:11: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:39:11: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:39:23: E226 missing whitespace around arithmetic operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:39:49: E231 missing whitespace after ','
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:39:60: E226 missing whitespace around arithmetic operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:41:10: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:47:1: E101 indentation contains mixed spaces and tabs
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:47:1: W191 indentation contains tabs
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:47:2: E131 continuation line unaligned for hanging indent
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:52:16: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:52:18: E261 at least two spaces before inline comment
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:52:19: E262 inline comment should start with '# '
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:53:1: E122 continuation line missing indentation or outdented
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:54:1: E122 continuation line missing indentation or outdented
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:55:1: E122 continuation line missing indentation or outdented
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:56:1: E122 continuation line missing indentation or outdented
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:57:1: E122 continuation line missing indentation or outdented
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:59:9: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:60:8: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:61:1: E265 block comment should start with '# '
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:62:12: E225 missing whitespace around operator
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:64:1: E101 indentation contains mixed spaces and tabs
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:65:1: E101 indentation contains mixed spaces and tabs
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:65:1: W191 indentation contains tabs
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:65:12: E128 continuation line under-indented for visual indent
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:65:29: E231 missing whitespace after ','
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:66:1: E101 indentation contains mixed spaces and tabs
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:66:44: W299 trailing whitespace
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:67:46: E231 missing whitespace after ','
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:67:58: W299 trailing whitespace
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:68:1: E101 indentation contains mixed spaces and tabs
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:68:1: W191 indentation contains tabs
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:68:6: E128 continuation line under-indented for visual indent
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:69:1: E101 indentation contains mixed spaces and tabs
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:69:23: E231 missing whitespace after ','
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:69:29: E231 missing whitespace after ','
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:69:35: E231 missing whitespace after ','
/tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:69:46: E231 missing whitespace after ','
[FAIL] /tmp/eb-qh7x87hr/files [...]

2021-03-24 07:14 UTC, ThomasHoffmann77 commented
Hi Kenneth,
I am sorry for the many style issues. This was my first upload and I was not aware of the --check-style feature. I will have a closer look.
Cheers,
Thomas
Am Di., Mrz. 23, 2021 21:36 schrieb Kenneth Hoste : 
 @ThomasHoffmann77 (https://github.com/ThomasHoffmann77) Are you up for looking into fixing the reported style issue?
 You can get a detailed overview using eb --check-style, see below.
	$ eb --from-pr 12457 --check-style == Temporary log file in case of crash /tmp/eb-qh7x87hr/easybuild-4pe_785j.log Running style check on 1 easyconfig(s)... /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:1:1: E265 block comment should start with '# ' /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:13:14: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:13:45: E261 at least two spaces before inline comment /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:13:46: E262 inline comment should start with '# ' /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:15:12: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:16:15: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:21:13: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:22:1: E122 continuation line missing indentation or outdented /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:22:6: E231 missing whitespace after ',' /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:23:1: E122 continuation line missing indentation or outdented /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:23:11: E231 missing whitespace after ',' /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:24:1: E122 continuation line missing indentation or outdented /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:24:11: E231 missing whitespace after ',' /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:26:14: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:27:14: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:27:116: E261 at least two spaces before inline comment /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:27:117: E262 inline comment should start with '# ' /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:27:121: E501 line too long (156 > 120 characters) /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:29:11: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:29:38: W299 trailing whitespace /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:30:11: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:31:11: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:32:11: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:33:11: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:34:11: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:35:11: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:36:11: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:37:11: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:38:11: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:39:11: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:39:23: E226 missing whitespace around arithmetic operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:39:49: E231 missing whitespace after ',' /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:39:60: E226 missing whitespace around arithmetic operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:41:10: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:47:1: E101 indentation contains mixed spaces and tabs /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:47:1: W191 indentation contains tabs /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:47:2: E131 continuation line unaligned for hanging indent /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:52:16: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:52:18: E261 at least two spaces before inline comment /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:52:19: E262 inline comment should start with '# ' /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:53:1: E122 continuation line missing indentation or outdented /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:54:1: E122 continuation line missing indentation or outdented /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:55:1: E122 continuation line missing indentation or outdented /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:56:1: E122 continuation line missing indentation or outdented /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:57:1: E122 continuation line missing indentation or outdented /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:59:9: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:60:8: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:61:1: E265 block comment should start with '# ' /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:62:12: E225 missing whitespace around operator /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:64:1: E101 indentation contains mixed spaces and tabs /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:65:1: E101 indentation contains mixed spaces and tabs /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:65:1: W191 indentation contains tabs /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:65:12: E128 continuation line under-indented for visual indent /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:65:29: E231 missing whitespace after ',' /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:66:1: E101 indentation contains mixed spaces and tabs /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:66:44: W299 trailing whitespace /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:67:46: E231 missing whitespace after ',' /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:67:58: W299 trailing whitespace /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:68:1: E101 indentation contains mixed spaces and tabs /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:68:1: W191 indentation contains tabs /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:68:6: E128 continuation line under-indented for visual indent /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:69:1: E101 indentation contains mixed spaces and tabs /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:69:23: E231 missing whitespace after ',' /tmp/eb-qh7x87hr/files_pr12457/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb:69:29: E231 missing whitespace after ',' /tmp/ [...]

2021-03-24 07:49 UTC, boegel commented
@ThomasHoffmann77 No need to be sorry, we're happy that you're willing to contribute!

If you have any questions, I recommend joining the EasyBuild Slack, see https://docs.easybuild.io/en/latest/#getting-help

2021-03-24 12:04 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/81dd1bc5cf253c49a5e0219a86ff174b for a full test report.

2021-03-24 12:04 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/c7b98f43e27562d867e41ae166481775 for a full test report.

2021-03-24 13:08 UTC, verdurin commented
@boegelbot please test @ generoso

2021-03-24 15:54 UTC, verdurin requested changes

2021-03-24 15:54 UTC, verdurin commented on easybuild/easyconfigs/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb
> +local_configopts += "-DJBIG_LIBRARY=$EBROOTJBIGKIT/lib/libjbig.so "
@ThomasHoffmann77 while it's a bit pedantic, could you apply `SHLIB_EXT` here too please, and in the line below?

2021-03-24 16:52 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/d0e22feb1c77b683a67f3c53ab9f1039 for a full test report.

2021-03-24 17:26 UTC, verdurin requested changes

2021-03-24 17:26 UTC, verdurin commented on easybuild/easyconfigs/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb
> +    '&& cp %(builddir)s/SIMPLE*/{doc,LICENSE,src/inc} %(installdir)s -rpP'
@ThomasHoffmann77 please add the trailing space here

2021-03-24 17:26 UTC, verdurin commented on easybuild/easyconfigs/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb
> +    '&& cd %(installdir)s/lib ' + '&& ln -s libSIMPLE%s.%s libSIMPLE.%s' % (version, SHLIB_EXT, SHLIB_EXT)
Another trailing space needs to be added here.

2021-03-24 17:26 UTC, verdurin commented on easybuild/easyconfigs/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb
> +    # "test binaries are only required for "make test".
It may be complaining about the three quotation marks here.

2021-03-24 17:26 UTC, verdurin commented on easybuild/easyconfigs/s/SIMPLE/SIMPLE-3.0.0-foss-2020b.eb
> +    '&& rm -rf %(installdir)s/bin/simple_test_*']
I also think it would be good to be consistent with `'` versus `"` on these lines, unless there's a good reason not to.

2021-03-26 12:14 UTC, verdurin approved these changes
Looks fine.

2021-03-26 14:36 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/fd4fe4bd635925bd0d1cc544991aa597 for a full test report.

2021-03-26 14:42 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/2d5a0a705c86f46cb0e461affa6d31d4 for a full test report.

2021-03-26 14:42 UTC, verdurin commented
Going in, thanks @ThomasHoffmann77!

2021-03-26 14:42 UTC, merged