{phys}[foss/2019b] georges v2019.2 w/ Python 3.7.4
easybuilders/easybuild-easyconfigs pull request #12570
Opened 2021-04-12 20:20 UTC by ekaterinaasf

(created using `eb --new-pr`)

2021-04-16 18:36 UTC, boegel requested changes
@ekaterinaasf Thank you very much for your contribution, and welcome to EasyBuild!

It looks like `LMfit-1.0.1-foss-2020a-Python-3.8.2.eb` is being removed by accident here?

If you need help with restoring it, do let us know!

2021-04-16 18:36 UTC, boegel commented on easybuild/easyconfigs/l/LMfit/LMfit-1.0.0-foss-2019b-Python-3.7.4.eb
> +    ('asteval', '0.9.17', {
@ekaterinaasf The existing `LMfit` easyconfig using `intel/2019b` as toolchain uses `asteval` 0.9.18, so I see no reason not to do that here too?

2021-04-19 08:54 UTC, verdurin commented
@boegel Are you happy with this now?

2021-04-19 10:11 UTC, boegel commented
@boegelbot please test @ generoso

2021-04-19 10:11 UTC, boegel approved these changes

2021-04-19 10:11 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2725.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/de2d083c4a939387f4f3a67c308056f9 for a full test report.

2021-04-19 10:12 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3523.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/6f51acfc7b9d2595e02f22376c8df554 for a full test report.

2021-04-19 11:03 UTC, boegel commented
Going in, thanks @ekaterinaasf!

2021-04-19 11:03 UTC, merged