{bio,chem}[foss/2020b,system/system] APBS v3.0.0, pdb2pqr v3.1.0 w/ Python 3.8.6
easybuilders/easybuild-easyconfigs pull request #12577
Opened 2021-04-13 12:22 UTC by ThomasHoffmann77

(created using `eb --new-pr`)

2021-04-14 22:38 UTC, Micket commented
Any reason why we don't compile this? We typically strive to avoid binary installs of software when we can avoid it.

2021-04-22 07:21 UTC, ThomasHoffmann77 commented
> Any reason why we don't compile this? We typically strive to avoid binary installs of software when we can avoid it.
 I assumed it would be better to at least have the binary install instead of nothing. I have been working on an installation from source. However, it is not ready, yet.

2021-04-23 11:15 UTC, boegel requested changes

2021-04-23 11:15 UTC, boegel commented on easybuild/easyconfigs/a/APBS/APBS-3.0.0_Linux.eb
> +versionsuffix = '_Linux'
Maybe tag this as `x86-64`? Linux is kind of a given...

But +1 on building this from source instead...

2024-01-13 18:44 UTC, boegel commented
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

2024-01-13 18:44 UTC, closed without merging