{chem}[foss/2020b] pdb2pqr v3.1.0 w/ Python 3.8.6
easybuilders/easybuild-easyconfigs pull request #12587
Opened 2021-04-13 14:38 UTC by ThomasHoffmann77

(created using `eb --new-pr`)

2021-04-14 22:41 UTC, Micket requested changes

2021-04-14 22:41 UTC, Micket commented on easybuild/easyconfigs/p/pdb2pqr/pdb2pqr-3.1.0-foss-2020b.eb
> +        'checksums': ['a6f5e2eefbd8bd2a072a89ee4026977de02dadd56e921095afac88d596b63820'],
No sources?

2021-04-14 22:41 UTC, Micket commented on easybuild/easyconfigs/p/pdb2pqr/pdb2pqr-3.1.0_mmcif_pdbx_2.0.0_remove_versioneer.patch
> +diff -ru mmcif_pdbx-2.0.0/MANIFEST.in mmcif_pdbx-2.0.0_patched/MANIFEST.in
A short description of what the patch does, reference to issue, and author are appreciated for patches

2021-04-28 18:31 UTC, boegel requested changes

2021-04-28 18:31 UTC, boegel commented on easybuild/easyconfigs/p/pdb2pqr/pdb2pqr-3.1.0-foss-2020b.eb
> +        'sources': 'mmcif_pdbx-%(version)s.tar.gz',
@ThomasHoffmann77 Same here

```python
'sources': ['mmcif_pdbx-%(version)s.tar.gz'],
```

2021-04-28 18:31 UTC, boegel commented on easybuild/easyconfigs/p/pdb2pqr/pdb2pqr-3.1.0-foss-2020b.eb
> +        'souces': '%(name)s-%(version)s.tar.gz',
@ThomasHoffmann77 This should be a list:

```python
'souces': ['%(name)s-%(version)s.tar.gz'],
```

2021-04-28 18:31 UTC, boegel commented on easybuild/easyconfigs/p/pdb2pqr/pdb2pqr-3.1.0-foss-2020b.eb
> +        'souces': '%(name)s-%(version)s.tar.gz',
Same here: `[...]`

2024-01-13 18:44 UTC, boegel commented
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

2024-01-13 18:44 UTC, closed without merging