Update matlab instructions
easybuilders/easybuild-easyconfigs pull request #12597
Opened 2021-04-14 13:09 UTC by Micket

2021-04-20 12:29 UTC, verdurin requested changes

2021-04-20 12:29 UTC, verdurin commented on easybuild/easyconfigs/m/MATLAB/README.md
> +Newer easyconfigs use the ISO files directly and unpacks them with the `7z` command.
`unpack`

2021-04-20 12:29 UTC, verdurin commented on easybuild/easyconfigs/m/MATLAB/README.md
> +* Your Matlab license should have a "`File Installation Key`" in under "`Advanced Options`" in the "`Install and Activate`" tab of your "`License Center`".
remove `in`

2021-07-03 18:34 UTC, boegel approved these changes
lgtm

2021-07-03 18:34 UTC, merged