{lib}[gompic/2020a] Boost.Python v1.72.0 w/ Python 2.7.18 + 3.8.2
easybuilders/easybuild-easyconfigs pull request #12630
Opened 2021-04-15 09:04 UTC by akesandgren

(created using `eb --new-pr`)

2021-04-15 09:06 UTC, akesandgren commented
@boegelbot Please test @ generoso

2021-04-29 17:40 UTC, branfosj requested changes
bintray is closing, so the `source_urls` need updating. See #12099 for more information.

2021-04-29 17:40 UTC, branfosj commented on easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.72.0-gompic-2020a.eb
> +source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
```suggestion
source_urls = ['https://boostorg.jfrog.io/artifactory/main/release/%(version)s/source/']
```

2021-04-29 17:40 UTC, branfosj commented on easybuild/easyconfigs/b/Boost/Boost-1.72.0-gompic-2020a.eb
> +source_urls = ['https://dl.bintray.com/boostorg/release/%(version)s/source/']
```suggestion
source_urls = ['https://boostorg.jfrog.io/artifactory/main/release/%(version)s/source/']
```

2021-05-03 19:37 UTC, branfosj commented
@boegelbot please test @ generoso

2021-05-03 19:48 UTC, branfosj approved these changes
lgtm

2021-05-03 19:53 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bber0501u03a.bb2.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/3a4ff6fa809c8c6ccb784f5b8f18b5c5 for a full test report.

2021-05-03 20:20 UTC, branfosj commented
Going in, thanks @akesandgren!

2021-05-03 20:20 UTC, merged