Add Python dependency to AUGUSTUS-3.4.0-foss-2020b.eb
easybuilders/easybuild-easyconfigs pull request #12662
Opened 2021-04-16 14:17 UTC by krometis

Per https://github.com/easybuilders/easybuild-easyconfigs/issues/12660

2021-04-16 14:32 UTC, Micket commented
Would you mind including the 2020a version as well?
It needs to also include a verionsuffix for Python like all the stuff did in 2020a.

2021-04-16 16:22 UTC, krometis commented
It looks like I screwed this up:
1. I correctly submitted a PR for AUGUSTUS
2. I then got full of myself and decided I'd also submit a PR for a newer OpenMM build that I had lying around
3. I screwed up (2) and somehow added it to (1)

I don't know how to untangle the two now. I'm sorry about this...

2021-04-16 17:39 UTC, Micket commented
So, alternatives in my opinion are
1. Just add Python as a build dep to satisfy the test-suite
2. Add Python and Perl as deps and also add `modextrapaths = {'PATH': 'scripts'}` (otherwise these deps don't do much at runtime anyway)

2021-04-16 17:54 UTC, Micket requested changes
Please also add Perl as a dep.

2021-04-16 18:54 UTC, Micket requested changes

2021-04-16 18:54 UTC, Micket commented on easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.4.0-foss-2020b.eb
> +    ('Perl','5.32.0'),
```suggestion
    ('Perl', '5.32.0'),
```

2021-04-19 15:01 UTC, Micket approved these changes
lgtm

2021-04-19 15:02 UTC, Micket commented
@boegelbot please test @ generoso

2021-04-20 12:10 UTC, Micket commented
Going in, thanks @krometis!

2021-04-20 12:10 UTC, merged