{chem}[fosscuda/2020b] cryoDRGN v0.3.2 w/ Python 3.8.6
easybuilders/easybuild-easyconfigs pull request #12704
Opened 2021-04-21 14:21 UTC by jfgrimm

(created using `eb --new-pr`)

2021-04-25 09:22 UTC, branfosj requested changes
I've made some minor suggestions for improvement.

2021-04-25 09:22 UTC, branfosj commented on easybuild/easyconfigs/c/cryoDRGN/cryoDRGN-0.3.2-fosscuda-2020b.eb
> +    }),
Replace this with a dependency on https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/plotly.py/plotly.py-4.14.3-GCCcore-10.2.0.eb

2021-04-25 09:22 UTC, branfosj commented on easybuild/easyconfigs/c/cryoDRGN/cryoDRGN-0.3.2-fosscuda-2020b.eb
> +    }),
Replace this with a dependency on https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/Seaborn/Seaborn-0.11.1-fosscuda-2020b.eb

2021-04-25 09:22 UTC, branfosj commented on easybuild/easyconfigs/c/cryoDRGN/cryoDRGN-0.3.2-fosscuda-2020b.eb
> +}
We can enhance the sanity check by replacing the `sanity_check_paths` with
```
sanity_check_commands = ["%(namelower)s --help"]
```

The default PythonBundle sanity check will test for the existence of the directory and the sanity check command will test the existence and function of `cryodrgn`.

2021-05-12 18:06 UTC, boegel commented
@boegelbot please test @ generoso

2021-05-12 18:07 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3304.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/3ff7b8e6889e7dbc6d7eff7a77d32f88 for a full test report.

2021-05-12 19:07 UTC, boegel approved these changes
lgtm

2021-05-12 19:07 UTC, boegel commented
Going in, thanks @jfgrimm!

2021-05-12 19:07 UTC, merged