{bio}[foss/2020b] QUAST v5.0.2 w/ Python 2.7.18
easybuilders/easybuild-easyconfigs pull request #12728
Opened 2021-04-22 15:32 UTC by boegel

(created using `eb --new-pr`)
requires #12718 (matplotlib)

2021-04-25 10:10 UTC, branfosj requested changes

2021-04-25 10:10 UTC, branfosj commented on easybuild/easyconfigs/q/QUAST/QUAST-5.0.2-foss-2020b-Python-2.7.18.eb
> +    }),
This is no longer needed, as it is provided by our Python 2.7.18 install: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-10.2.0.eb#L382

2021-05-02 10:26 UTC, boegel commented
@boegelbot please test @ generoso

2021-05-02 10:27 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3604.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/b6e692254f22931a0a5b14cd454b65c5 for a full test report.

2021-05-03 18:19 UTC, branfosj approved these changes

2021-05-03 18:22 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/a3df7757c5275420e77fb06095daae60 for a full test report.

2021-05-03 18:22 UTC, branfosj commented
Going in, thanks @boegel!

2021-05-03 18:22 UTC, merged