{bio}[gompi/2020b] MaxBin v2.2.7
easybuilders/easybuild-easyconfigs pull request #12727
Opened 2021-04-22 15:29 UTC by boegel

(created using `eb --new-pr`)

2021-04-22 17:17 UTC, boegel commented
@boegelbot please test @ generoso

2021-04-22 17:25 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/2a5d6830ffbe03640499f021d7082a04 for a full test report.

2021-04-22 17:26 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3101.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/0a15eccab402edc50badb03168f87a41 for a full test report.

2021-04-26 06:37 UTC, verdurin commented
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/98ceaa923aa7626394c964908e377fa0 for a full test report.

2021-04-26 06:38 UTC, verdurin commented
Test report by @verdurin
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.2
See https://gist.github.com/38dd598b0e5c8419add6279bf5b3a172 for a full test report.

2021-04-26 06:38 UTC, verdurin commented
@boegel checksum failure reported here.

2021-05-03 21:15 UTC, Micket commented
Test report by @Micket
**FAILED**
Build succeeded for 4 out of 5 (3 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 2.7.5
See https://gist.github.com/02c0db37d97f91ac69c5757f767cfd60 for a full test report.

2021-05-16 15:11 UTC, boegel commented
> @boegel checksum failure reported here.

Indeed, fixed in c8a9525, see also #12869.

2021-05-16 15:46 UTC, boegel commented
@boegelbot please test @ generoso

2021-05-16 17:14 UTC, branfosj requested changes

2021-05-16 17:14 UTC, branfosj commented on easybuild/easyconfigs/f/FragGeneScan/FragGeneScan-1.31-GCCcore-10.2.0.eb
> +
```suggestion

prebuildopts = "make clean && "
```

The fix in #12870 should also be applied here.

2021-05-16 17:39 UTC, branfosj approved these changes

2021-05-16 17:42 UTC, boegel commented
@boegelbot please test @ generoso
CORE_CNT=16

2021-05-16 17:43 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/b80b786f811b188bb5c6d1993409d9f4 for a full test report.

2021-05-16 17:50 UTC, branfosj commented
Going in, thanks @boegel!

2021-05-16 17:50 UTC, merged