{bio}[gompi/2020b] taxator-tk v1.3.3, SeqAn v2.4.0
easybuilders/easybuild-easyconfigs pull request #12732
Opened 2021-04-22 16:37 UTC by boegel

(created using `eb --new-pr`)

2021-04-22 17:39 UTC, boegel commented
@boegelbot please test @ generoso

2021-04-22 17:54 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3501.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/a8553902d65268e91109aed47eef1c45 for a full test report.

2021-04-22 17:55 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node3101.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/5d9114aa01be0906900ad7b760ac2c1a for a full test report.

2021-04-22 18:30 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3101.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/ecc889e195febbd1ee00e90b5cb23022 for a full test report.

2021-04-24 10:03 UTC, branfosj requested changes

2021-04-24 10:03 UTC, branfosj commented on easybuild/easyconfigs/t/taxator-tk/taxator-tk-1.3.3-gompi-2020b.eb
> +toolchain = {'name': 'gompi', 'version': '2020b'}
It does not look like taxator-tk uses MPI, so we can move it to GCC / 10.2.0.

2021-05-10 13:35 UTC, boegel commented
@boegelbot please test @ generoso
CORE_COUNT=16

2021-05-10 19:06 UTC, branfosj approved these changes

2021-05-10 19:23 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/bd5163490f775a2aeae3a75d6024cacd for a full test report.

2021-05-10 19:25 UTC, branfosj commented
Going in, thanks @boegel!

2021-05-10 19:25 UTC, merged