{bio}[foss/2020b] metaWRAP v1.3 (+ deps) w/ Python 2.7.18
easybuilders/easybuild-easyconfigs pull request #12733
Opened 2021-04-22 17:17 UTC by boegel

(created using `eb --new-pr`)
requires #12726 (bmtagger), #12720 (CheckM), #12724 (MEGAHIT), #12725 (CONCOCT), #12727 (MaxBin), #12728 (QUAST), #12729 (Trim_Galore), #12730 (Seaborn), #12732 (taxator-tk)

2021-05-16 17:54 UTC, boegel commented
@boegelbot please test @ generoso

2021-05-16 18:05 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 8 out of 8 (6 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/9288fcc6e11589ad1aed0504f036463f for a full test report.

2021-05-16 18:06 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3507.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/22a00985103cc860e3f58318d2c669b8 for a full test report.

2021-05-16 18:12 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3163.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/9728e878c16aa44a0b25427179686ebc for a full test report.

2021-05-16 18:35 UTC, branfosj requested changes

2021-05-16 18:35 UTC, branfosj commented on easybuild/easyconfigs/k/KronaTools/KronaTools-2.8-GCCcore-10.2.0.eb
> +# Contribution from the Crick HPC team
See  #12871 for suggested changes to the existing KronaTools ecs. This should be changed in the same way.

2021-05-16 18:35 UTC, branfosj commented on easybuild/easyconfigs/k/KronaTools/KronaTools-2.8-GCCcore-10.2.0.eb
> +
checksum missing

2021-05-16 18:35 UTC, branfosj commented on easybuild/easyconfigs/m/MetaBAT/MetaBAT-2.15-gompi-2020b-Python-2.7.18.eb
> +sources = ['v%(version)s.tar.gz']
checksum missing

2021-05-16 18:35 UTC, branfosj commented on easybuild/easyconfigs/m/metaWRAP/metaWRAP-1.3-foss-2020b-Python-2.7.18.eb
> +sources = ['v%(version)s.tar.gz']
checksum missing

2021-05-17 07:30 UTC, boegel commented
@boegelbot please test @ generoso

2021-05-17 07:36 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node2618.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/38af82e07736b4efebc61028134903e9 for a full test report.

2021-05-17 07:37 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3506.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/1a88ba512374a7e13bf31aa3b7cf153f for a full test report.

2021-05-17 07:53 UTC, branfosj approved these changes

2021-05-17 08:00 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/a63837d437d3f3a41b27c414311c0ade for a full test report.

2021-05-17 08:00 UTC, branfosj commented
Going in, thanks @boegel!

2021-05-17 08:00 UTC, merged