{tools}[gcccuda/2020b] gpustat v0.6.0 w/ Python 3.8.6
easybuilders/easybuild-easyconfigs pull request #12763
Opened 2021-04-27 15:40 UTC by boegel

(created using `eb --new-pr`)

2021-04-27 15:47 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3300.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/fc166cdfa5f3cc1f160b7a074a837225 for a full test report.

2021-04-27 17:24 UTC, branfosj requested changes

2021-04-27 17:24 UTC, branfosj commented on easybuild/easyconfigs/g/gpustat/gpustat-0.6.0-gcccuda-2020b.eb
> +    }),
We should be able to remove this. We have psutil 5.7.2 in the Python install and this version of gpustat was released long before psutil 5.8.0 was released.

2021-04-28 19:12 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3301.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/c6a21ae84bd64583dcbdff516339950d for a full test report.

2021-04-28 19:15 UTC, branfosj approved these changes

2021-04-28 19:15 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bber0501u03a.bb2.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/0be7ee4d8a68c4871572c11ccddf058d for a full test report.

2021-04-28 19:26 UTC, branfosj commented
Going in, thanks @boegel!

2021-04-28 19:26 UTC, merged