{math}[GCCcore/10.2.0] Clp 1.17.6 update toolchain
easybuilders/easybuild-easyconfigs pull request #12772
Opened 2021-04-27 23:49 UTC by fizwit

(created using `eb --new-pr`)

2021-05-03 20:01 UTC, Micket requested changes
All 3 files are very different from previous easyconfigs. It doesn't seem like the changes are improvements, but possible just missing that there existed versions already to base the new versions off? These seems to be missing both build and runtime dependencies, as well as not enabling features that seems like a good idea to keep (in particular in Clp)

2021-05-04 21:36 UTC, fizwit commented
Osi, and Coinutils were built by me but I never pushed them.  Replace with versions from EB.

2021-05-07 19:11 UTC, Micket requested changes

2021-05-07 19:11 UTC, Micket commented on easybuild/easyconfigs/c/Clp/Clp-1.17.6-GCCcore-10.2.0.eb
> +]
I would suspect that zlib and bzip2 are still required, they tend to sneak in everywhere. Could you check your build log, or `ldd libClp.so` and confirm if they are not present here?

2021-05-07 19:11 UTC, Micket commented on easybuild/easyconfigs/c/Clp/Clp-1.17.6-GCCcore-10.2.0.eb
> +toolchain = {'name': 'GCCcore', 'version': '10.2.0'}
Add the comment describing this variant perhaps?
```
# NOTE: this easyconfig for Clp provides a minimal build
```

2021-05-07 19:11 UTC, Micket commented on easybuild/easyconfigs/c/Clp/Clp-1.17.6-GCCcore-10.2.0.eb
> +
Isn't the CPATH environment variable still relevant here?

2023-06-28 21:54 UTC, fizwit commented
@Micket my version of Clp is out of date now.  Closing

2023-06-28 21:54 UTC, closed without merging