{bio}[intel/2020b] loompy v3.0.6 w/ Python 3.8.6
easybuilders/easybuild-easyconfigs pull request #12804
Opened 2021-05-03 17:10 UTC by boegel

(created using `eb --new-pr`)

2021-05-03 17:37 UTC, boegel commented
@boegelbot please test @ generoso

2021-05-03 18:33 UTC, Micket requested changes

2021-05-03 18:33 UTC, Micket commented on easybuild/easyconfigs/l/loompy/loompy-3.0.6-intel-2020b.eb
> +    'dirs': ['lib/python3.8/site-packages'],
```suggestion
    'dirs': ['lib/python%(pyshortver)s/site-packages'],
```

2021-05-03 19:31 UTC, Micket commented
@boegelbot please test @ generoso

2021-05-03 20:04 UTC, Micket approved these changes
lgtm

2021-05-03 20:04 UTC, merged

2021-05-04 08:32 UTC, boegel commented on easybuild/easyconfigs/l/loompy/loompy-3.0.6-intel-2020b.eb
> +    'dirs': ['lib/python3.8/site-packages'],
Ouch, thanks for fixing this @Micket !