rmats-turbo contrib v4.1.1
easybuilders/easybuild-easyconfigs pull request #12800
Opened 2021-05-03 09:52 UTC by cmeesters

(created using `eb --new-pr`)

2021-05-07 18:17 UTC, Micket requested changes

2021-05-07 18:17 UTC, Micket commented on easybuild/easyconfigs/r/rmats-turbo/rmats-turbo-4.1.1-GCCcore-10.2.0.eb
> +    ("STAR", "2.7.8a", "", ("GCC", "10.2.0")),
This needs to go into foss instead if it depends from things from foss, else things will break (for at least some module naming schemes)

2021-05-07 18:17 UTC, Micket commented on easybuild/easyconfigs/r/rmats-turbo/rmats-turbo-4.1.1-GCCcore-10.2.0.eb
> +source_urls = ["https://gitlab.com/Xinglab/archive/refs/tags/"]
Any special reason to use github for homepage, but sources from gitlab? In fact, this path doesn't really look right at all?

2021-05-07 18:17 UTC, Micket commented on easybuild/easyconfigs/r/rmats-turbo/rmats-turbo-4.1.1-GCCcore-10.2.0.eb
> +usage = "python $EBROOOTRMATSMINTURBO/rmats.py ..."
Can't we use PATH instead to make it easier to run?

2021-05-07 18:17 UTC, Micket commented on easybuild/easyconfigs/r/rmats-turbo/rmats-turbo-4.1.1.patch
> +diff -Nru rmats-turbo-4.1.1.orig/rMATS_C/Makefile rmats-turbo-4.1.1/rMATS_C/Makefile
We really like to have a small description of what the patch does (and who wrote it)

2021-05-07 18:17 UTC, Micket commented on easybuild/easyconfigs/r/rmats-turbo/rmats-turbo-4.1.1.patch
> ++LDFLAGS := -lm -lgfortran -lgsl -lgslcblas -lgomp -lopenblas -lscalapack
I wonder if we can instead use `$(LIBSCALAPACK)` environment variable here instead. This will be set to the correct link flags for any toolchain.

2021-05-07 18:17 UTC, Micket commented on easybuild/easyconfigs/r/rmats-turbo/rmats-turbo-4.1.1-GCCcore-10.2.0.eb
> +patches = ["rmats-turbo-4.1.1.patch"]
It would be good to name the patch something like `rmats-turbo-4.1.1-scalapack_linking.patch`

2021-05-07 18:17 UTC, Micket commented on easybuild/easyconfigs/r/rmats-turbo/rmats-turbo-4.1.1-GCCcore-10.2.0.eb
> +    (["tests"], ""),
Are there tests we could run here?

2021-05-07 18:17 UTC, Micket commented on easybuild/easyconfigs/r/rmats-turbo/rmats-turbo-4.1.1-GCCcore-10.2.0.eb
> +            "rMATS_pipeline/build/lib.linux-x86_64-3.*/rmats/*.so",
Hm, I think we can place these wildcards better so we're not hardcoding in an assumption on the architecture here

2024-01-14 09:26 UTC, boegel commented
closing this since `GCCcore/10.2.0` is deprecated, see https://docs.easybuild.io/policies/toolchains

2024-01-14 09:26 UTC, closed without merging