{chem}[foss/2019b] networkTools v2
easybuilders/easybuild-easyconfigs pull request #12810
Opened 2021-05-04 12:06 UTC by kerica

(created using `eb --new-pr`)

2021-05-05 17:01 UTC, Micket requested changes

2021-05-05 17:01 UTC, Micket commented on easybuild/easyconfigs/n/networkTools/networkTools-2-foss-2019b.eb
> +toolchain = {'name': 'foss', 'version': '2019b'}
I think this can (and should) move to GCC level instead of using foss.

2021-05-05 18:04 UTC, boegel commented
@kerica Thanks a lot for your contribution, and welcome to EasyBuild!

One more suggestion on top of @Micket's review: please consider adding a simple sanity check command (via the `sanity_check_commands` easyconfig parameter), something like `gncommunities --help` for example.

And don't hesitate to reach out if you have any question (either in this PR, or via Slack).

2021-05-06 13:17 UTC, kerica commented on easybuild/easyconfigs/n/networkTools/networkTools-2-foss-2019b.eb
> +    'dirs': ['']
Thank you @Micket for the suggestions, I actually changes both the dirs and the toolchain

2021-05-06 13:21 UTC, kerica commented
@boegel thanks for the suggestion and for the welcoming, it is my first PR, I am not sure how to introduce it in the slack channel so I answer here.

I have tried both a test and the sanity check you suggested, but it gives an error. The problem is that running the binaries with the help flag or without flags returns an exit error 1, that's why we decided to avoid it.

Since I changed the toolchain, should I make a new PR or I can just update this one?

2021-05-06 13:43 UTC, Micket commented
A quick glance at the source code leads me to believe that this software doesn't have any suitable commands for sanity checking. No -h or -v flags at all.

2021-05-06 13:47 UTC, kerica commented
I checked it just by running the command and it provides the USAGE, but with the exit code 1, which results in an error when testing

2021-05-06 17:46 UTC, Micket requested changes
You can just leave out the sanity check command since there are no good options.

2021-05-06 17:46 UTC, Micket commented on easybuild/easyconfigs/n/networkTools/networkTools-2-foss-2019b.eb
> +homepage = 'http://faculty.scs.illinois.edu/schulten/software/networkTools/'
```suggestion
homepage = 'https://faculty.scs.illinois.edu/schulten/software/networkTools/'
```

2021-05-06 17:46 UTC, Micket commented on easybuild/easyconfigs/n/networkTools/networkTools-2-foss-2019b.eb
> +source_urls = ['http://faculty.scs.illinois.edu/schulten/software/networkTools']
```suggestion
source_urls = ['https://faculty.scs.illinois.edu/schulten/software/networkTools']
```

2021-05-07 08:02 UTC, kerica commented on easybuild/easyconfigs/n/networkTools/networkTools-2-foss-2019b.eb
> +source_urls = ['http://faculty.scs.illinois.edu/schulten/software/networkTools']
Thanks

2021-05-07 13:10 UTC, Micket requested changes

2021-05-07 13:10 UTC, Micket commented on easybuild/easyconfigs/n/networkTools/networkTools-2-GCC-9.3.0.eb
> +source_urls = ['http://faculty.scs.illinois.edu/schulten/software/networkTools']
```suggestion
source_urls = ['https://faculty.scs.illinois.edu/schulten/software/networkTools']
```

2021-05-07 13:22 UTC, Micket approved these changes

2021-05-07 14:28 UTC, Micket approved these changes
lgtm

2021-05-07 14:28 UTC, Micket approved these changes

2021-05-07 14:29 UTC, Micket commented
@boegelbot please test @ generoso

2021-05-14 10:41 UTC, kErica commented
@Micket and @boegel any news? I don't know how it works the testing stage. There is anything else I can do to pushing forward my first recipy?

2021-05-14 12:47 UTC, Micket commented
Sorry @kErica, so many PRs it's hard to keep track on things.

You could just whitelist the URLs in the test-suite and switch back to http:// since their webserver is incorrectly configured
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/test/easyconfigs/easyconfigs.py#L865-L871
(unfortunately, you can't use the eb --update-pr commands for this, you'll need to check these changes into your PR branch manually)

2021-05-14 12:54 UTC, Micket commented
Actually, looking at this closer, perhaps we don't need to whitelist it. You can start by just switching over to http again and lets see if the test suite fails.

2021-05-14 13:00 UTC, kErica commented
I'm sending an update with just the https to http changed. Let's see if this pass @ generoso like this

2021-05-14 13:24 UTC, Micket commented
And here is the problem, the automatic test suite won't allow http urls when https exists. I'm a bit puzzled though, as `urlopen` does (correctly) fail on my machines due to the outdated SSL configuration on this host.

But, this PR needs to add a whitelist on the tests for this URL ot package name (in the code i linked above)

2021-05-15 15:18 UTC, Micket commented
@boegelbot please test @ generoso

2021-05-15 15:24 UTC, Micket approved these changes
lgtm

2021-05-15 15:26 UTC, Micket commented
Going in, thanks @kErica!

2021-05-15 15:26 UTC, merged