Latest availble EC is for v1.3.0 and foss/2018b. Don't know if something changed that makes it obsolete, but it was requested at our site - so here we are.
easybuilders/easybuild-easyconfigs pull request #12823
Opened 2021-05-05 18:37 UTC by seb45tian

(created using `eb --new-pr`)

2021-05-05 18:44 UTC, seb45tian commented
Sorry for the messy commit message, was mixing it up the comment. I changed the title accordingly. If wanted,  this PR  can be deleted (closed) and I open a new one with a proper commit msg for the logs.

2021-05-07 15:01 UTC, Micket requested changes

2021-05-07 18:43 UTC, seb45tian commented on easybuild/easyconfigs/g/gdc-client/gdc-client-1.6.0-GCCcore-10.2.0.eb
> +exts_defaultclass = 'PythonPackage'
Fixed with 38a3d1f

2021-05-15 16:39 UTC, Micket approved these changes
lgtm

2021-05-15 16:41 UTC, Micket commented
@boegelbot please test @ generoso

2021-05-15 16:52 UTC, Micket commented
Going in, thanks @seb45tian!

2021-05-15 16:52 UTC, merged