{bio}[GCC/9.3.0] vcflib v1.0.2 + deps
easybuilders/easybuild-easyconfigs pull request #12841
Opened 2021-05-10 14:30 UTC by jfgrimm

(created using `eb --new-pr`)
typo in original commit msg - require(d) ~~#12837~~ ~~#12838~~ ~~#12839~~

2021-05-11 21:58 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 7 out of 8 (5 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/8155190c979a19619e90f5ed374b1038 for a full test report.

2021-05-18 11:40 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node031.pri.viking.alces.network - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz, Python 2.7.5
See https://gist.github.com/4ed134adf714aa5f4ea973de0df4f31e for a full test report.

2021-05-21 14:16 UTC, branfosj requested changes
If there are suitable items for `sanity_check_commands` then it would be good to add some checks on the executables.

2021-05-21 14:16 UTC, branfosj commented on easybuild/easyconfigs/f/fsom/fsom-20141119_fix-abs-overload.patch
> +diff -Nru fsom-a6ef318fbd347c53189384aef7f670c0e6ce89a3/fsom.c fsom-a6ef318fbd347c53189384aef7f670c0e6ce89a3.2/fsom.c
Please add description and author to this patch.

2021-05-21 14:16 UTC, branfosj commented on easybuild/easyconfigs/s/smithwaterman/smithwaterman-20160702_build-shared-lib.patch
> +diff -Nru smithwaterman-2610e259611ae4cde8f03c72499d28f03f6d38a7.orig/Makefile smithwaterman-2610e259611ae4cde8f03c72499d28f03f6d38a7/Makefile
Please add description and author to this patch.

2021-05-21 14:16 UTC, branfosj commented on easybuild/easyconfigs/v/vcflib/vcflib-1.0.2_use-external-deps.patch
> +diff -Nru vcflib.orig/CMakeLists.txt vcflib/CMakeLists.txt
Please add description and author to this patch.

2021-05-21 14:16 UTC, branfosj commented on easybuild/easyconfigs/v/vcflib/vcflib-1.0.2-GCC-9.3.0-Python-3.8.2.eb
> +    ('CMake', '3.16.4'),
Please add `pkg-config` (0.29.2) as a build dependency.

2021-05-21 15:14 UTC, jfgrimm commented
@branfosj thanks for taking a look! I've added author/desc to the patches that were missing it, and have added some `sanity_check_commands`.

2021-05-21 17:34 UTC, branfosj commented
@boegelbot please test @ generoso

2021-05-21 17:35 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/d0f934269cef83686350ba1c5a0fa217 for a full test report.

2021-05-21 17:37 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/f2ba4047ed8e49b4929721afeb9be793 for a full test report.

2021-05-21 17:39 UTC, branfosj approved these changes

2021-05-21 17:40 UTC, branfosj commented
Going in, thanks @jfgrimm!

2021-05-21 17:40 UTC, merged