Patch UCX to add CUDA support at runtime
easybuilders/easybuild-easyconfigs pull request #12866
Opened 2021-05-15 11:44 UTC by Micket

(created using `eb --new-pr`)

2021-05-15 13:49 UTC, Micket commented
So, I think this works. ucx_info manages to find and report on CUDA stuff.

But, there are some details to sort out when it comes to building the additional UCX-plugins; I would like them link to the existing libuct.so etc. libraries. Right now, I hackishly install the plugins. Alternatively, we can just install copies of those libraries, they should hopefully be identical anyway.

2021-05-15 18:20 UTC, boegel commented
@Micket Do you think it's worth implementing a custom easyblock for this, where we can check the output produced by `ucx_info`a bit more thoroughly?

This easyconfig looks complex enough to warrant that, I think...

2021-05-15 18:53 UTC, Micket commented
Sure, though it's mostly just the same as UCX.  We could probably automatically populate EB_xxx_MODULES here.

The biggest issue is 
1. Gotta test to see if it actually works for transferring data. I need 2 nodes to test and my cluster is a bit booked up at the moment.
2. The hacky way I install just the modules right now is not good. I would really need to rework this. Maybe even requiring a patch to just build the plugins and not involve any other linking shenanigans. I'm not to familiar with how to hack this into libtool/autohell stuff going on here. I really hate autotools...

2021-05-26 16:17 UTC, akesandgren requested changes

2021-05-26 16:17 UTC, akesandgren commented on easybuild/easyconfigs/u/UCX/UCX-1.10.0-dynamic_modules.patch
> ++        sprintf(env, "EB_%s_MODULES", framework);
Use strncpy, strncat, strncat here instead, then you can drop stdio and stdlib and do string.h instead.

2021-05-28 10:10 UTC, akesandgren commented
This one no longer need the original UCX nor the patch for dynamic modules.

2021-06-26 13:38 UTC, Micket commented
Replaced with #13260

2021-06-26 13:38 UTC, closed without merging