{vis}[foss/2020b] Nilearn v0.7.1 w/ Python 3.8.6
easybuilders/easybuild-easyconfigs pull request #12890
Opened 2021-05-18 09:13 UTC by akesandgren

(created using `eb --new-pr`)

2021-05-18 09:13 UTC, akesandgren commented
@boegelbot Please test @ generoso

2021-05-20 17:20 UTC, branfosj requested changes

2021-05-20 17:20 UTC, branfosj commented on easybuild/easyconfigs/n/Nilearn/Nilearn-0.7.1-foss-2020b.eb
> +sources = [SOURCELOWER_TAR_GZ]
please add the checksum

2021-05-24 09:00 UTC, akesandgren commented on easybuild/easyconfigs/n/Nilearn/Nilearn-0.7.1-foss-2020b.eb
> +sources = [SOURCELOWER_TAR_GZ]
Done

2021-05-24 09:36 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.4
See https://gist.github.com/e87095672e3501d128740ca3c59034d3 for a full test report.

2021-05-24 09:37 UTC, verdurin approved these changes
Looks fine.

2021-05-25 17:08 UTC, verdurin commented
@branfosj could you confirm you're happy with the changes? I don't like to dismiss someone else's review...

2021-05-25 17:09 UTC, branfosj approved these changes

2021-05-25 17:10 UTC, branfosj commented
> @branfosj could you confirm you're happy with the changes? I don't like to dismiss someone else's review...

Yes, I am happy with the changes.

2021-05-25 17:11 UTC, verdurin commented
Going in, thanks @akesandgren!

2021-05-25 17:11 UTC, merged