{bio}[GCC/9.3.0] Snippy v4.6.0 w/ Python 3.8.2
easybuilders/easybuild-easyconfigs pull request #12893
Opened 2021-05-18 11:35 UTC by jfgrimm

(created using `eb --new-pr`)
Requires #12841, #12856, #12859, #12881 and #12892

2021-08-23 13:39 UTC, jfgrimm commented
@branfosj with freebayes approved recently, all deps should be covered now

2021-08-23 18:22 UTC, branfosj requested changes

2021-08-23 18:22 UTC, branfosj commented on easybuild/easyconfigs/s/Snippy/Snippy-4.6.0-GCC-9.3.0-Java-13-Python-3.8.2.eb
> +    ('freebayes', '1.3.5', local_pyversuffix),
```suggestion
    ('freebayes', '1.3.5', local_pyversuffix),
    ('gzip', '1.10'),
```

I have `Found gzip - /usr/bin/gzip` in the log so we should as `gzip` as a dependency.

2021-08-23 18:22 UTC, branfosj commented on easybuild/easyconfigs/s/Snippy/Snippy-4.6.0-GCC-9.3.0-Java-13-Python-3.8.2.eb
> +runtest = ''
```suggestion
runtest = ' '
```

An empty string for `runtest` means that no tests are run.

2021-08-24 13:07 UTC, branfosj commented
@boegelbot please test @ generoso

2021-08-24 13:08 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/69723b9c63b6b4cd2988b7a8c51dbe18 for a full test report.

2021-08-24 13:11 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/6ca3bff5f6b0da4c00c8124216fcf016 for a full test report.

2021-08-24 13:12 UTC, branfosj approved these changes
lgtm

2021-08-24 13:13 UTC, branfosj commented
Going in, thanks @jfgrimm!

2021-08-24 13:13 UTC, merged