{tools}[FCC/21.05] Perl v5.32.0, DB v18.1.40, expat v2.2.9, ...
easybuilders/easybuild-easyconfigs pull request #12965
Opened 2021-05-26 21:35 UTC by migueldiascosta

(created using `eb --new-pr`)

2021-05-26 21:50 UTC, migueldiascosta commented
Test report by @migueldiascosta
**FAILED**
Build succeeded for 0 out of 8 (8 easyconfigs in total)
d28-3009c - Linux RHEL 8.3, AArch64, UNKNOWN (a64fx), Python 3.6.8
See https://gist.github.com/097111427a79cd62f826c90def010189 for a full test report.

2021-05-27 03:09 UTC, migueldiascosta commented
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
e31-1001c - Linux RHEL 8.3, AArch64, UNKNOWN (a64fx), Python 3.6.8
See https://gist.github.com/b8481972107b8e676bd9a49b2c828af0 for a full test report.

2021-05-31 08:17 UTC, boegel requested changes
OpenSSL should also be listed as an OS dep in the `DB` easyconfig

2021-05-31 08:17 UTC, boegel commented on easybuild/easyconfigs/d/DB/DB-18.1.40-FCC-21.05.eb
> +source_urls = ['https://bintray.com/homebrew/mirror/download_file?file_path=']
This source URL needs to be fixed, see #12974

2021-05-31 08:56 UTC, boegel commented on easybuild/easyconfigs/d/DB/DB-18.1.40-FCC-21.05.eb
> +source_urls = ['https://bintray.com/homebrew/mirror/download_file?file_path=']
fixed in https://github.com/migueldiascosta/easybuild-easyconfigs/pull/34

2021-06-01 03:50 UTC, migueldiascosta commented
replaced with https://github.com/easybuilders/easybuild-easyconfigs/pull/12997

2021-06-01 03:50 UTC, closed without merging