{toolchain} nompi v2021a
easybuilders/easybuild-easyconfigs pull request #13107
Opened 2021-06-10 15:06 UTC by SebastianAchilles

(created using `eb --new-pr`)

Depends on
- [ ] https://github.com/easybuilders/easybuild-framework/pull/3735
- CUDA for 2021a (no PR yet)

2021-06-18 15:03 UTC, SebastianAchilles commented
@boegelbot please test @ generoso

2021-06-18 15:20 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/0c883508f1f2cd69a3e26171c5ad7e5a for a full test report.

2021-06-18 15:33 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/c21c48a9300d461c88bddaa92edb15ea for a full test report.

2021-06-28 11:04 UTC, akesandgren commented
@boegelbot Please test @ generoso

2021-06-28 11:12 UTC, akesandgren commented
This should eventually use UCX-CUDA when that stuff is completely in place (which should be soon)

2021-06-28 11:23 UTC, akesandgren requested changes

2021-06-28 11:23 UTC, akesandgren commented on easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.1-NVHPC-21.5.eb
> +    ('UCX', '1.10.0'),
Let's replace this with the now available UCX-CUDA of the same version.

2021-06-28 11:24 UTC, akesandgren commented
And add a HPL and OSU-Micro-Benchmarks built on top of this so we can test it.

2021-06-28 13:48 UTC, akesandgren commented on easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.7.1-nvompic-2021a.eb
> +configopts += ' --enable-cuda --with-cuda=$EBROOTCUDA'
I think that we only have CUDAcore loaded so it might need to be EBROOTCUDACORE

2021-06-29 12:27 UTC, akesandgren commented
This is now tripping up in tools/module_naming_scheme/hierarchical_mns.py:det_modpath_extensions line 231

2021-06-29 12:51 UTC, akesandgren commented
@boegel I think we might need some guidance here...
When it is trying to build CUDA-11.3.1-NVHPC-21.5.eb the hmns code sees CUDA and in det_modpath_extensions we have
non_system_cuda = true, entering that if stmt, "if ec['name'] in extend_comps:" is true since CUDA is in at least one of the COMP_NAME_VERSION_TEMPLATES keys, same for "if ec['name'] in comp_names:", etc but eventually comp_name_ver will still be None since there is no 'CUDA,NVHPC' key. But if we're trying to move away from the compiler-CUDA modulepath extension, https://github.com/easybuilders/easybuild-easyconfigs/issues/12484 option 1, we need to do this differently. Either in this PR or in framework.

What is the right way forward here?

2021-09-07 12:25 UTC, Micket commented
Considering the recent foss/fosscuda merge changes (including renaming CUDAcore -> CUDA), we need to do similar things here;

1. We use the system level CUDA package as a dependency. This allows us to use the UCX-CUDA plugin directly.
2. Presumably, NVHPC shouldn't provide it's own CUDA on top then? Because it does right now by default.
3. There won't be a second CUDA package, it's just NVHPC as the compiler level, and it already implies CUDA. There is no non-cuda variant like there used to be with GCC vs GCC-CUDA. I don't think we need to do anything special with modulepaths here. It's just NVHPC + OpenMPI to consider.

2023-10-23 14:53 UTC, SebastianAchilles commented
Closing since we added a `nvofbf/2022.07` toolchain in https://github.com/easybuilders/easybuild-easyconfigs/pull/16724

2023-10-23 14:53 UTC, closed without merging