{bio}[GCCcore/9.3.0] cutadapt v3.4 w/ Python 3.8.2
easybuilders/easybuild-easyconfigs pull request #13105
Opened 2021-06-10 14:10 UTC by kErica

(created using `eb --new-pr`)

2021-06-12 05:06 UTC, verdurin commented
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/ae525842300e74251044cfd1a2811fbe for a full test report.

2021-06-12 05:07 UTC, verdurin commented
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/1ff2da7039bed5b6f5bdc7ec13718549 for a full test report.

2021-06-12 05:08 UTC, verdurin requested changes

2021-06-12 05:08 UTC, verdurin commented on easybuild/easyconfigs/c/cutadapt/cutadapt-3.4-GCCcore-9.3.0-Python-3.8.2.eb
> +    ('xopen', '1.1.0', {
@kErica `pip check` is failing because `xopen` requires `isal` - please add that extension before `xopen`.

2024-01-13 18:08 UTC, boegel commented
closing this since `GCCcore/9.3.0` is deprecated, see https://docs.easybuild.io/policies/toolchains

2024-01-13 18:08 UTC, closed without merging