{compiler}[system/system] ispc v1.16.0
easybuilders/easybuild-easyconfigs pull request #13135
Opened 2021-06-12 12:53 UTC by boegel

(created using `eb --new-pr`)

2021-06-12 14:03 UTC, boegel commented
@boegelbot please test @ generoso

2021-06-12 14:03 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2619.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/e3345c647958ab1faca3f1d2bb42e20f for a full test report.

2021-06-12 14:04 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3545.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/91b583fb4607e94ac0fe00652b1472bf for a full test report.

2021-06-12 17:02 UTC, Micket requested changes

2021-06-12 17:02 UTC, Micket commented on easybuild/easyconfigs/i/ispc/ispc-1.16.0.eb
> +homepage = 'http://ispc.github.io/ , https://github.com/ispc/ispc/'
```suggestion
homepage = 'https://ispc.github.io/ , https://github.com/ispc/ispc/'
```

2021-06-13 12:09 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/c537a30fb85167e753d86e94cc691cd4 for a full test report.

2021-06-13 12:09 UTC, Micket approved these changes
lgtm

2021-06-13 12:10 UTC, Micket commented
Going in, thanks @boegel!

2021-06-13 12:10 UTC, merged

2021-06-14 02:41 UTC, migueldiascosta commented
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/fd67541a584bffa8ff3302d8455683b3 for a full test report.

2021-06-16 01:43 UTC, migueldiascosta commented
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
sms - Linux centos linux 7.6.1810, x86_64, AMD EPYC 7601 32-Core Processor (zen), Python 2.7.5
See https://gist.github.com/acd9e5a70b6f981a5b7aa1bb91517670 for a full test report.