{chem}[intel/2020b] AIMAll v19.10.12
easybuilders/easybuild-easyconfigs pull request #13153
Opened 2021-06-15 09:01 UTC by smoors

(created using `eb --new-pr`)

2021-06-15 10:39 UTC, smoors commented
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node354.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/c25a2d1b14f3a94472f20892a6636f1b for a full test report.

2023-06-29 07:53 UTC, branfosj requested changes

2023-06-29 07:53 UTC, branfosj commented on easybuild/easyconfigs/a/AIMAll/AIMAll-19.10.12-intel-2020b-linux_64bit.eb
> +# to run in professional mode, add required license files to the main AIMAll directory
```suggestion
download_instructions = """Download sources from http://aim.tkgristmill.com/download/download.html (requires login).
To run in professional mode, add required license files to the main AIMAll directory."""
```

2023-06-29 08:28 UTC, branfosj approved these changes

2023-06-29 09:06 UTC, merged