{bio}[foss/2020b] mapDamage v2.2.1 w/ Python 3.8.6
easybuilders/easybuild-easyconfigs pull request #13172
Opened 2021-06-16 08:19 UTC by akesandgren

(created using `eb --new-pr`)

2021-06-16 08:24 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.5
See https://gist.github.com/f32832f3c570d46fe0cdc7111690bc94 for a full test report.

2021-06-16 08:26 UTC, akesandgren commented
@boegelbot Please test @ generoso

2021-06-21 10:57 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/03ad8889ea432cab39c2f2f67e81bb0d for a full test report.

2021-06-21 10:59 UTC, verdurin requested changes

2021-06-21 10:59 UTC, verdurin commented on easybuild/easyconfigs/m/mapDamage/mapDamage-2.2.1-foss-2020b-R-4.0.4.eb
> +description = '''mapDamage2 is a computational framework written in Python and
<nitpick> - shouldn't this be `"""`?

2021-06-21 12:00 UTC, verdurin commented on easybuild/easyconfigs/m/mapDamage/mapDamage-2.2.1-foss-2020b-R-4.0.4.eb
> +description = '''mapDamage2 is a computational framework written in Python and
Thanks.

2021-06-21 12:00 UTC, verdurin approved these changes
Looks fine.

2021-06-21 12:02 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/e3e56af0a9e7db63e81d929496f1f679 for a full test report.

2021-06-21 12:02 UTC, verdurin commented
Going in, thanks @akesandgren!

2021-06-21 12:02 UTC, merged