{geo}[SYSTEM] SNAP-ESA v8.0 and python interface with Python-2.7.18/GCCcore-10.2.0
easybuilders/easybuild-easyconfigs pull request #13198
Opened 2021-06-17 13:33 UTC by lexming

2021-07-04 15:26 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/5b0ace71e6d5c75bb4496b2608e99de5 for a full test report.

2022-10-17 14:13 UTC, jfgrimm reviewed
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 13198` and update the PR to use `SYSTEM` instead.

2023-10-17 13:38 UTC, boegel requested changes
see https://github.com/lexming/easybuild-easyconfigs/pull/2

2023-10-18 08:44 UTC, lexming commented on easybuild/easyconfigs/s/SNAP-ESA-python/SNAP-ESA-python-8.0-GCCcore-10.2.0-Java-1.8.0_292-OpenJDK-Python-2.7.18.eb
> +    ('Java', '1.8.0_292', '-OpenJDK', SYSTEM),
SNAP developers recommend OpenJDK, but it is not a hard requirement so we can switch to the wrapper and let the installer choose. I updated the comment to clarify that an OpenJDK is recommended.

2023-10-18 08:45 UTC, lexming commented on easybuild/easyconfigs/s/SNAP-ESA-python/SNAP-ESA-python-8.0-GCCcore-10.2.0-Java-1.8.0_292-OpenJDK-Python-2.7.18.eb
> +modluafooter = 'setenv("JAVA_TOOL_OPTIONS", os.getenv("JAVA_TOOL_OPTIONS").."%s")' % local_javaopts
good catch, thanks for the fix :+1:

2023-10-18 09:11 UTC, lexming commented
@boegelbot: please test @ generoso

2023-10-18 16:18 UTC, boegel approved these changes

2023-10-18 16:21 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3130.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/6e3124a6fed0d259a5c3bf1a7ce2d41f for a full test report.

2023-10-18 16:25 UTC, boegel commented
Going in, thanks @lexming!

2023-10-18 16:49 UTC, boegel commented
Going in, thanks @lexming!

2023-10-18 16:49 UTC, merged