{math}[foss/2021a] retworkx v0.9.0 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #13228
Opened 2021-06-21 17:30 UTC by Micket

(created using `eb --new-pr`)

2021-06-21 17:35 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/f5af21cf3e8921d6084736b17a9ae010 for a full test report.

2021-06-21 19:21 UTC, verdurin requested changes

2021-06-21 19:21 UTC, verdurin commented on easybuild/easyconfigs/r/retworkx/retworkx-0.9.0-foss-2021a.eb
> +description= """retworkx is a general purpose graph library for python3 written in Rust to take advantage of the
Please fix the formatting here.

2021-06-21 19:21 UTC, verdurin commented on easybuild/easyconfigs/r/retworkx/retworkx-0.9.0-foss-2021a.eb
> +sources = [SOURCELOWER_TAR_GZ]
Please add the missing checksum here.

2021-06-21 19:58 UTC, Micket commented
@boegelbot please test @ generoso

2021-06-22 10:47 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/c70153f733d07c905550a9c8e9c101e3 for a full test report.

2021-06-22 14:07 UTC, verdurin approved these changes
Looks fine.

2021-06-22 14:07 UTC, verdurin commented
Going in, thanks @Micket!

2021-06-22 14:07 UTC, merged