{cae}[foss/2021a] OpenFOAM vv2106
easybuilders/easybuild-easyconfigs pull request #13266
Opened 2021-06-27 18:34 UTC by robert-mijakovic

(created using `eb --new-pr`)

2021-08-14 05:33 UTC, boegel requested changes

2021-08-14 05:33 UTC, boegel commented on easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2106-foss-2021a.eb
> +    'e765881451d8d15ce33caa28850cdcc4534b8c4590e08ee6011bcafd11216940',  # OpenFOAM-v2106.tgz
I'm getting a different SHA256 checksum for `OpenFOAM-v2106.tgz`: `11e41e5b9a253ef592a8f6b79f6aded623b28308192d02cec1327078523b5a37` 

Was there a sneaky re-release of OpenFOAM v2106 without a proper version bump? (@olesenm?!)

@robert-mijakovic Do you still have the original source tarball you were using, with checksum `e765881451d8d15ce33caa28850cdcc4534b8c4590e08ee6011bcafd11216940`?

2021-08-14 05:34 UTC, boegel commented on easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2106-foss-2021a.eb
> +    'e765881451d8d15ce33caa28850cdcc4534b8c4590e08ee6011bcafd11216940',  # OpenFOAM-v2106.tgz
The SHA256 in the Spack packages agrees with what I'm seeing, so I'll change this...

https://github.com/spack/spack/blob/e911f8ab3cfc073f77ea874871a95cb63dd928f4/var/spack/repos/builtin/packages/openfoam/package.py#L268

2021-08-14 11:28 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3111.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/403541abec92c401c21a40fa29feb692 for a full test report.

2021-08-14 14:15 UTC, boegel commented
@boegelbot please test @ generoso
CORE_CNT=16

2021-08-17 13:00 UTC, boegel commented
First compiler error from the build log of the failing build on `generoso` (CentOS 8):
```
/users/boegelbot/CentOS8/haswell/software/CGAL/5.2.2-gompi-2021a/include/CGAL/array.h:72:44: error: std::index_sequence has not been declared
   72 | make_filled_array_aux(const T& value, std::index_sequence<Is...>)
      |                                            ^~~~~~~~~~~~~~
```

This looks a lot like https://github.com/CGAL/cgal/issues/4974, but that was fixed in https://github.com/CGAL/cgal/pull/4981, which is included in CGAL 5.2.2.

I'm puzzled why this problem only pops up on `generoso`, and not on our CentOS 7 Intel Skylake cluster (see other test report)... It doesn't like like this is caused by a newer glibc?!

@olsenm Is OpenFOAM v2106 supposed to be compatible yet with CGAL 5.x? For v2012, we were still using CGAL 4.14.3...

2021-08-18 07:17 UTC, boegel commented
@boegelbot please test @ generoso
CORE_CNT=16

2021-08-18 07:20 UTC, boegel commented
I've swapped to CGAL 4.14.3 (latest 4.x) as dependency for OpenFOAM v2106, since that seems to work just fine...

I'll also use that same CGAL version for OpenFOAM 9 (even though we used CGAL 5.x there for OpenFOAM 8)

2021-08-18 08:36 UTC, branfosj commented on easybuild/easyconfigs/l/libcerf/libcerf-1.15-GCCcore-10.3.0.eb
> +
```suggestion
```

Not needed in CMakeMake as it is the default.

2021-08-18 09:01 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2621.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/b36518d30fc14ad8ef6905524b4bf6cb for a full test report.

2021-08-18 09:31 UTC, branfosj approved these changes
lgtm

2021-08-18 09:31 UTC, boegel approved these changes

2021-08-18 10:17 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/cfe7562f107db14aa070c64189034780 for a full test report.

2021-08-18 10:46 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3502.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/8f175e7f47e235daa86a15137fcdb0d0 for a full test report.

2021-08-18 13:19 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 10 out of 10 (3 easyconfigs in total)
node2621.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/362d543b3fcc6a62240e71b13ccc990f for a full test report.

2021-08-18 14:56 UTC, merged