{lib}[GCCcore/10.3.0] UCX-CUDA v1.10.0
easybuilders/easybuild-easyconfigs pull request #13260
Opened 2021-06-26 02:58 UTC by Micket

(created using `eb --new-pr`)

2021-06-26 10:07 UTC, boegel requested changes

2021-06-26 10:07 UTC, boegel commented on easybuild/easyconfigs/u/UCX-CUDA/UCX-CUDA-1.10.0-GCCcore-10.3.0-CUDA-11.3.1.eb
> +sanity_check_commands = ["ucx_info -d"]
This can be removed, it's handled by the easyblock

2021-06-27 14:15 UTC, Micket commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=2491"

2021-06-27 14:17 UTC, Micket commented
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2491
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/090681b7910b262729e0c1c78999f4a6 for a full test report.

2021-06-27 14:20 UTC, Micket commented
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2491
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/dcf41d0a091c730fd0a1167f777b6528 for a full test report.

2021-06-28 07:23 UTC, boegel commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=2491"

2021-06-28 07:33 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2491
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3517.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/01342f113f2c5e0014fbc17cf611d2a9 for a full test report.

2021-06-28 07:33 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2491
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2603.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 2.7.5
See https://gist.github.com/eba3755bac7d07fdf0b057e65550d22c for a full test report.

2021-06-28 07:37 UTC, SebastianAchilles commented
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2491
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
centos8-eb - Linux centos linux 8.3.2011, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/7384e931f7936c48122b0ea249388b9f for a full test report.

2021-06-28 07:38 UTC, SebastianAchilles commented
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2491
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/3b1b1a6199c816881c8718458aeb0079 for a full test report.

2021-06-28 08:14 UTC, boegel approved these changes

2021-06-28 08:24 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3615.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/82d82478c8e80a0b3971b2bc36cd3aad for a full test report.

2021-06-28 08:28 UTC, boegel approved these changes
lgtm

2021-06-28 09:12 UTC, boegel commented
Going in, thanks @Micket!

2021-06-28 09:12 UTC, merged