Julia for aarch64
easybuilders/easybuild-easyconfigs pull request #13303
Opened 2021-06-30 13:48 UTC by rungitta

(created using `eb --new-pr`)

2021-07-05 21:12 UTC, verdurin commented
@rungitta welcome to EasyBuild and thanks for the contribution. 
Are you able to upload a test report on `aarch64` hardware?

2021-07-06 05:11 UTC, rungitta commented
I'd be glad to upload a test report. How do I do that? Can you point me to the
relevant documentation?

-- 
Axel Rosén, Head Engineer
Research Infrastructure Services Group, USIT
University of Oslo, Norway

2021-07-13 11:16 UTC, rungitta commented
Test report by @rungitta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
freebio2.hpc.uio.no - Linux RHEL 8.4, AArch64, ARM Cortex-A72 (graviton), Python 3.6.8
See https://gist.github.com/cb66e99381e44e77e052964141fa804b for a full test report.

2024-01-14 09:19 UTC, boegel requested changes

2024-01-14 09:19 UTC, boegel commented on easybuild/easyconfigs/j/Julia/Julia-1.6.0-linux-aarch64.eb
> +}
```suggestion
sanity_check_paths = {
    'files': ['bin/julia', 'include/julia/julia.h', 'lib/libjulia.%s' % SHLIB_EXT],
    'dirs': ['bin', 'etc', 'include', 'lib', 'share']
}

sanity_check_commands = ['julia --help']

modextravars = {
    # Use default DEPOT_PATH where first entry is user's depot
    # JULIA_DEPOT_PATH must be set to be able to load other JuliaPackage modules and have
    # those installations appended to DEPOT_PATH without disabling any of the default paths
    'JULIA_DEPOT_PATH': ':',
}
```

2024-01-14 09:28 UTC, boegel approved these changes

2024-01-14 09:29 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
aarch64-neoverse-v1-node1.int.aws-rocky88-202310.eessi.io - Linux Rocky Linux 8.8, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/6bf9e3dd11546b7402d22beb7328acaf for a full test report.

2024-01-14 09:41 UTC, boegel commented
Going in, thanks @rungitta!

2024-01-14 09:41 UTC, merged