{lib}[GCCcore/10.3.0] Check v0.15.2, googletest v1.11.0, JsonCpp v1.9.4
easybuilders/easybuild-easyconfigs pull request #13319
Opened 2021-07-01 23:13 UTC by Micket

(created using `eb --new-pr`)

2021-07-01 23:16 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/6846ee7a57a265e156bac463cb3c9407 for a full test report.

2021-07-02 00:57 UTC, Micket commented
@boegelbot please test @ generoso

2021-07-02 13:15 UTC, branfosj requested changes

2021-07-02 13:15 UTC, branfosj commented on easybuild/easyconfigs/g/googletest/googletest-1.11.0-GCCcore-10.3.0.eb
> +separate_build_dir = True
```suggestion
```

This is the deafult for CMakeMake, so we should remove it.

2021-07-02 13:26 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/71276f07a09d566a106bff0c5790864d for a full test report.

2021-07-02 13:28 UTC, branfosj approved these changes

2021-07-02 13:29 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/027267ef6c561d52ddb85e4c25f14514 for a full test report.

2021-07-02 13:31 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0305u19a.bear.cluster - Linux RHEL 8.4, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/9b7b61ef40048d80024f9abfa882db3d for a full test report.

2021-07-02 13:34 UTC, branfosj commented
Going in, thanks @Micket!

2021-07-02 13:34 UTC, merged