{lang,math,vis}[GCCcore/10.3.0] gnuplot v5.4.2, libcerf v1.17, Lua v5.4.3
easybuilders/easybuild-easyconfigs pull request #13317
Opened 2021-07-01 23:00 UTC by Micket

(created using `eb --new-pr`)

2021-07-01 23:44 UTC, Micket commented
Test report by @Micket
**FAILED**
Build succeeded for 24 out of 30 (3 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/dde6f28e075ccd9b435c1be3c5280ece for a full test report.

2021-07-02 00:56 UTC, Micket commented
@boegelbot please test @ generoso

2021-07-02 01:37 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/ae847eb062fe6c8d1e2ef5849900f62a for a full test report.

2021-07-02 13:12 UTC, branfosj requested changes

2021-07-02 13:12 UTC, branfosj commented on easybuild/easyconfigs/l/libcerf/libcerf-1.17-GCCcore-10.3.0.eb
> +
```suggestion
```

This is the deafult for CMakeMake, so we should remove it.

2021-07-02 13:21 UTC, branfosj commented
Test report by @branfosj
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/95a23ec1444310e48f2b3fa67ff408f7 for a full test report.

2021-07-02 13:22 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/76fac1594ce952cbdf22c264ba6de0b6 for a full test report.

2021-07-02 13:23 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (3 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/a3b524df509b04b210c00c2f65e5b5d9 for a full test report.

2021-07-02 13:26 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/49a144fa477a2cedbe9373687c758c8b for a full test report.

2021-07-02 13:26 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0305u19a.bear.cluster - Linux RHEL 8.4, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/ac7ababa5cda0cd8d76ee7d97f739227 for a full test report.

2021-07-02 13:28 UTC, branfosj approved these changes

2021-07-02 14:04 UTC, merged