{vis}[foss/2021a] freud-analysis v2.6.2 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #13361
Opened 2021-07-07 08:57 UTC by robert-mijakovic

(created using `eb --new-pr`)

2021-07-07 09:29 UTC, robert-mijakovic commented
@boegelbot please test @ generoso EB_ARGS="--from-pr 13353"

2024-10-04 20:43 UTC, boegel requested changes

2024-10-04 20:43 UTC, boegel commented on easybuild/easyconfigs/f/freud-analysis/freud-analysis-2.6.2-foss-2021a.eb
> +    ('tbb', '2021.2.0'),
```suggestion
    ('tbb', '2020.3'),

2024-10-04 20:55 UTC, boegel commented
@boegelbot please test @ generoso

2024-10-04 20:57 UTC, boegel approved these changes
lgtm

2024-10-04 21:07 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4012.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/f679fcbf51f96fa71c821953931e84c5 for a full test report.

2024-10-05 06:57 UTC, boegel commented
Going in, thanks @robert-mijakovic!

2024-10-05 06:57 UTC, merged