{bio}[gompi/2020a] Modeltest-NG v0.1.7
easybuilders/easybuild-easyconfigs pull request #13391
Opened 2021-07-08 12:38 UTC by FokkeDijkstra

(created using `eb --new-pr`)

2021-07-09 12:43 UTC, robert-mijakovic commented
@boegelbot please test @ generoso

2021-07-09 17:52 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/077ac180b13a24cec75fc32eb4cb24ad for a full test report.

2021-07-09 17:54 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/092a7e444df38e2b6f0ec145a11b627d for a full test report.

2021-07-09 17:56 UTC, verdurin requested changes

2021-07-09 17:56 UTC, verdurin commented on easybuild/easyconfigs/m/Modeltest-NG/Modeltest-NG-0.1.7-gompi-2020a.eb
> +dependencies = [
@FokkeDijkstra I would remove `dependencies` if there aren't any.

2021-08-02 11:23 UTC, FokkeDijkstra commented on easybuild/easyconfigs/m/Modeltest-NG/Modeltest-NG-0.1.7-gompi-2020a.eb
> +dependencies = [
Done.

2024-01-13 18:12 UTC, boegel commented
closing this since `foss/2020a` is deprecated, see https://docs.easybuild.io/policies/toolchains

Sorry for not getting back to this @FokkeDijkstra 

If `Modeltest-NG` is still relevant, please consider opening a new pull request using a more toolchain

2024-01-13 18:12 UTC, closed without merging