{lib}[GCCcore/10.2.0] MATIO v1.5.21
easybuilders/easybuild-easyconfigs pull request #13439
Opened 2021-07-15 10:05 UTC by robert-mijakovic

(created using `eb --new-pr`)

2021-07-15 11:24 UTC, robert-mijakovic commented
@boegelbot: please test @ generoso

2021-07-15 11:27 UTC, robert-mijakovic commented
Test report by @robert-mijakovic
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login01.meluxina.lxp.lu - Linux RHEL 8.3, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/7367ef536306210c6555b97a15a39e1f for a full test report.

2021-07-18 18:20 UTC, smoors requested changes
@robert-mijakovic since the `autogen.sh` script runs `libtoolize` & co, you should probably add `Autotools` as build dep?

2021-07-19 09:41 UTC, robert-mijakovic commented
> @robert-mijakovic since the `autogen.sh` script runs `libtoolize` & co, you should probably add `Autotools` as build dep?

Thanks for noticing. Done.

2021-07-24 07:17 UTC, verdurin requested changes

2021-07-24 07:17 UTC, verdurin commented on easybuild/easyconfigs/m/MATIO/MATIO-1.5.21-GCCcore-10.2.0.eb
> +    ('Autotools', '20200128'),
I think this should be:
```suggestion
    ('Autotools', '20200321'),
```

2023-09-10 10:55 UTC, branfosj commented
Sorry, we missed following up on this and merged  #13710

2023-09-10 10:55 UTC, closed without merging