update GRIDSS
easybuilders/easybuild-easyconfigs pull request #13431
Opened 2021-07-13 23:42 UTC by fizwit

(created using `eb --new-pr`)

2021-07-14 13:45 UTC, smoors requested changes

2021-07-14 13:45 UTC, smoors commented on easybuild/easyconfigs/g/GRIDSS/GRIDSS-2.12.0-foss-2020b.eb
> +    ('R', '4.0.5'),
@fizwit can you use version `4.0.4` here? that's the default for the 2020b generation

2021-07-14 13:45 UTC, smoors commented on easybuild/easyconfigs/g/GRIDSS/GRIDSS-2.12.0-foss-2020b.eb
> +# sanity_check_commands = ["gridss --help"]
```suggestion
sanity_check_commands = ["gridss --help 2>&1| grep '^Usage:'"]
```

2022-08-29 22:35 UTC, closed without merging

2022-08-29 22:35 UTC, fizwit commented
duplicate