{bio}[GCC/10.2.0] OMA v2.5.0
easybuilders/easybuild-easyconfigs pull request #13447
Opened 2021-07-16 10:38 UTC by sdx23

(created using `eb --new-pr`)
New version that is not broken on Debian systems. For some reason it needs Python as a build dependency. I'm not sure I've set the toolchain correctly to achieve this, could you please comment on that?

2021-07-20 08:33 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/d792637e9a3453bd0570a7e6fce2012a for a full test report.

2021-07-20 08:35 UTC, verdurin commented
@sdx23 welcome to EasyBuild and thanks for the contribution.

That is indeed a bit strange - a binary that nevertheless requires Python. I suppose that given it's only a build dep, there's no need to include Python in the `versionsuffix`. Normally a binary would use the `SYSTEM` toolchain. `GCCcore` might make more sense than `GCC` and make it more compatible with other toolchains.

2021-07-26 12:21 UTC, verdurin requested changes

2021-07-26 12:21 UTC, verdurin commented on easybuild/easyconfigs/o/OMA/OMA-2.5.0-GCCcore-10.2.0.eb
> +    ('Python', '3.8.6'),
@sdx23 with the toolchain change, you will need to add `binutils` as a dependency.

```suggestion
    ('Python', '3.8.6'),
    ('binutils', '2.35'),
```

2024-01-14 08:59 UTC, boegel commented
closing this since `GCC/10.2.0` is deprecated, see https://docs.easybuild.io/policies/toolchains

2024-01-14 08:59 UTC, closed without merging