{lang}[system/system] Julia v1.6.2
easybuilders/easybuild-easyconfigs pull request #13466
Opened 2021-07-21 09:13 UTC by robert-mijakovic

(created using `eb --new-pr`)

2021-07-21 09:14 UTC, robert-mijakovic commented
@boegelbot: please test @ generoso

2021-07-21 09:15 UTC, robert-mijakovic commented
Test report by @robert-mijakovic
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login01.meluxina.lxp.lu - Linux RHEL 8.3, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/87f2c77f32e2d20ef65b235228c887c0 for a full test report.

2021-07-21 15:54 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.5
See https://gist.github.com/3e92426b03caa2191e59a2b14f632120 for a full test report.

2021-07-21 15:58 UTC, verdurin requested changes

2021-07-21 15:58 UTC, verdurin commented on easybuild/easyconfigs/j/Julia/Julia-1.6.2-linux-x86_64.eb
> +    'files': ['bin/julia', 'include/julia/julia.h', 'lib/libjulia.so'],
Shouldn't this use `SHLIB_EXT`?

2021-07-22 15:05 UTC, robert-mijakovic commented on easybuild/easyconfigs/j/Julia/Julia-1.6.2-linux-x86_64.eb
> +    'files': ['bin/julia', 'include/julia/julia.h', 'lib/libjulia.so'],
True. Fixed!

2021-07-22 20:53 UTC, verdurin commented
@boegelbot please test @ generoso

2021-07-23 11:45 UTC, verdurin approved these changes
Looks fine.

2021-07-23 11:46 UTC, verdurin commented
Going in, thanks @robert-mijakovic!

2021-07-23 11:46 UTC, merged