{bio}[GCCcore/10.2.0] any2fasta v0.4.2, filevercmp v20191210, freebayes v1.3.5, ...
easybuilders/easybuild-easyconfigs pull request #13474
Opened 2021-07-22 10:17 UTC by deniskristak

(created using `eb --new-pr`)

2021-07-22 21:14 UTC, verdurin submitted a review, later dismissed

2021-07-22 21:14 UTC, verdurin commented on easybuild/easyconfigs/f/filevercmp/filevercmp-20191210-GCCcore-10.2.0.eb
> +patches = ['%(name)s-20191210_build-libs.patch']
@deniskristak please add the missing checksums

2021-07-22 21:14 UTC, verdurin commented on easybuild/easyconfigs/f/freebayes/freebayes-1.3.5-GCC-10.2.0.eb
> +}]
Checksum should be added here too, if it's consistent.

2021-07-29 22:56 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 6 out of 7 (5 easyconfigs in total)
node379.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/9d5d31f0b5ee40c40d963e5143b232b6 for a full test report.

2021-07-31 22:55 UTC, lexming requested changes
I reviewed this PR and it needs some changes. The most important is to only focus on freebayes v1.3.5 and its dependencies, otherwise it will not pass our tests and it's very difficult to find the missing parts. Anything unrelated to freebayes should go in a different PR.

Therefore, I made the following changes in a PR to this one https://github.com/deniskristak/easybuild-easyconfigs/pull/1:
* remove any2fasta and samclip from the PR, they should be moved to your PR about `snippy` https://github.com/easybuilders/easybuild-easyconfigs/pull/13475
* fix the conflicts with filevercmp in current `develop`
* fix build of freebayes:
    * add missing dependencies on `vcflib`, `SeqLib`, `fastahack`, `intervaltree`, `multichoose`, `smithwaterman`
    * patch `meson.build` and set the build environment to properly detect our external dependencies
    * switch the build to a release build
* add easyconfig for SeqLib and its dependencies
* move the update of VCFtools to depend on HTSlib v1.12 from #13477  to this PR

@deniskristak please check the changes in https://github.com/deniskristak/easybuild-easyconfigs/pull/1 and if you agree merge it to update this PR.

2021-08-02 07:53 UTC, deniskristak commented
@lexming so rn, I should only add `any2fasta` and `samclip` to https://github.com/easybuilders/easybuild-easyconfigs/pull/13475 , right?

2021-08-03 00:36 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/a5d653d67de10e1b73192faea02d6dd5 for a full test report.

2021-08-06 17:56 UTC, deniskristak commented
@lexming anything left for me to do here?
think you've made most of changes you noted

2021-08-06 20:17 UTC, lexming approved these changes
LGTM

2021-08-06 20:22 UTC, lexming commented
Sorry for the delay, this PR is good. I'll check the others that are related to this one.

Going in, thanks @deniskristak !

2021-08-06 20:22 UTC, merged