{compiler}[system/system] NVHPC v21.7
easybuilders/easybuild-easyconfigs pull request #13492
Opened 2021-07-23 14:13 UTC by robert-mijakovic

(created using `eb --new-pr`)

2021-07-23 14:58 UTC, robert-mijakovic commented
@boegelbot please test @ generoso

2021-07-23 15:05 UTC, robert-mijakovic commented
Test report by @robert-mijakovic
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
login01.meluxina.lxp.lu - Linux RHEL 8.3, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/55fa88fe48855c1622bab422493bddcb for a full test report.

2021-07-23 15:22 UTC, robert-mijakovic commented
`== 2021-07-23 17:05:54,227 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:124 in __init__): A default Compute Capability is needed for installation of NVHPC.Please provide it either in the easyconfig file like 'cuda_compute_capabilities="7.0"',or use 'eb --cuda-compute-capabilities=7.0' from the command line. (at easybuild/easybuild-easyblocks/easybuild/easyblocks/n/nvhpc.py:132 in install_step)`

2021-07-23 15:22 UTC, robert-mijakovic commented
@boegelbot please test @ generoso EB_ARGS='cuda_compute_capabilities="7.0"'

2021-07-28 21:41 UTC, lexming requested changes

2021-07-28 21:41 UTC, lexming commented on easybuild/easyconfigs/n/NVHPC/NVHPC-21.7.eb
> +accept_eula = True
The EULA should not be accepted by default
```suggestion
# By downloading, you accept the HPC SDK Software License Agreement
# https://docs.nvidia.com/hpc-sdk/eula/index.html
# accept_eula = True
```

2021-07-29 15:07 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node226.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz, Python 2.7.5
See https://gist.github.com/e35fc484432ac0bc7e5d4db5e5945a40 for a full test report.

2021-07-29 15:24 UTC, lexming approved these changes
LGTM

2021-07-29 15:25 UTC, lexming commented
Going in, thanks @robert-mijakovic !

2021-07-29 15:25 UTC, merged