{bio}[GCC/10.3.0] fumi_tools v0.18.2 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #13517
Opened 2021-07-29 07:48 UTC by SethosII

(created using `eb --new-pr`)

2021-07-29 08:10 UTC, SethosII commented
Test report by @SethosII
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
ribnode012 - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz, Python 3.8.10
See https://gist.github.com/d9956aa89909dad47c8c4fcaa20535ff for a full test report.

2021-08-07 09:50 UTC, branfosj requested changes

2021-08-07 09:50 UTC, branfosj commented on easybuild/easyconfigs/f/fumi_tools/fumi_tools-0.18.2-GCC-10.3.0.eb
> +
```suggestion
```

This is default for `CMakeMake`, so this can be removed.

2021-08-10 15:21 UTC, branfosj commented
@boegelbot please test @ generoso

2021-08-10 16:49 UTC, branfosj approved these changes

2021-08-10 16:51 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/23fb8dacd94f3fcad23ebddf695d5a36 for a full test report.

2021-08-10 16:51 UTC, branfosj commented
Going in, thanks @SethosII!

2021-08-10 16:51 UTC, merged