Spyder v5.0.5 modules for foss/2020b and intel/2020b
easybuilders/easybuild-easyconfigs pull request #13519
Opened 2021-07-29 08:19 UTC by SimonPinches

(created using `eb --new-pr`)

2021-07-29 13:32 UTC, Micket requested changes
I think it's always best to keep using the existing package versions if they exist for maximum compatibility with all other stuff, which might rely on those versions

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('libspatialindex', '1.9.3'),
I really don't think spyder needs these at all. Without it, we can drop this all the way down to `GCCcore`.

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('async_generator', '1.10', {
Already included in deps

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('bleach', '3.3.1', {
Already included in deps (slightly different version, but maybe still compatible)

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('decorator', '5.0.9', {
Already included in deps (different version, but maybe still compatible?)

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('jedi', '0.17.2', {
Already included in deps

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('jeepney', '0.7.0', {
Already included in deps (different version, but maybe still compatible?)

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('jupyterlab_pygments', '0.1.2', {
Already included in deps

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('keyring', '21.8.0', {
Already included in deps (slightly different version, but maybe still compatible?)

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('keyrings.alt', '4.1.0', {
Already included in deps (slightly different version, but maybe still compatible?)

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('jupyter_client', '6.1.12', {
Already included in deps (slightly different version, but maybe still compatible)

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('nbclient', '0.5.3', {
Already included in deps (slightly different version, but maybe still compatible)

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('nest_asyncio', '1.5.1', {
Already included in deps (slightly different version, but maybe still compatible)

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('isort', '5.9.2', {
Duplicate, one with and one without use_pip?

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('ujson', '4.0.2', {
Already included in deps (slightly different version, but maybe still compatible)

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('pyrsistent', '0.18.0', {
Already included in deps (slightly different version, but maybe still compatible)

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('SecretStorage', '3.3.1', {
Already included in deps (vera different version, but maybe still compatible?)

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('parso', '0.7.0', {
Already included in deps (different version, but maybe still compatible)

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('traitlets', version, {
Already included in deps (slightly different version, but maybe still compatible). I also think the "version" here would be wrong regardless

2021-07-29 13:32 UTC, Micket commented on easybuild/easyconfigs/s/Spyder/Spyder-5.0.5-foss-2020b.eb
> +    ('flit_core', '3.2.0', {
Already included in deps (different version, but maybe still compatible)

2024-01-13 18:54 UTC, boegel commented
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

2024-01-13 18:54 UTC, closed without merging