{tools}[foss/2021a] Quandl v3.6.1 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #13534
Opened 2021-07-31 17:49 UTC by Micket

(created using `eb --new-pr`)

2021-07-31 17:53 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/9c9ff800b7b0d2d6e23fd47d97ae0fb4 for a full test report.

2021-07-31 18:31 UTC, Micket commented
@boegelbot please test @ generoso

2021-08-01 08:40 UTC, branfosj requested changes

2021-08-01 08:40 UTC, branfosj commented on easybuild/easyconfigs/q/Quandl/Quandl-3.6.1-foss-2021a.eb
> +    }),
```suggestion
```

Does this require `more-itertools` 8.8.0? Python 3.9.5 provides `more-itertools` 8.7.0.

2021-08-01 12:54 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/21572e5cd03018a934c7abe1ffd3f80e for a full test report.

2021-08-01 15:41 UTC, branfosj approved these changes

2021-08-01 15:42 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/99a25d9811abced2e6d03e8355fd4e2c for a full test report.

2021-08-01 15:42 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/0e5031cea7e898334fed7f81d0f99de7 for a full test report.

2021-08-01 15:45 UTC, branfosj commented
Going in, thanks @Micket!

2021-08-01 15:46 UTC, merged