Biopython bumped to 1.78 and foss-2020b, needed for alphafold
easybuilders/easybuild-easyconfigs pull request #13574
Opened 2021-08-03 21:33 UTC by sassy-crick

(created using `eb --new-pr`)

2021-08-03 23:59 UTC, Micket requested changes

2021-08-04 14:53 UTC, sassy-crick commented on easybuild/easyconfigs/b/Biopython/Biopython-1.79-foss-2020b-Python-3.8.6.eb
> +versionsuffix = '-Python-%(pyver)s'
Erm, yes, you are right. Teaches me to do things late at night.

2021-08-07 08:01 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/ad65379543de8d261d57fc8c510c4f1a for a full test report.

2021-08-07 08:03 UTC, SebastianAchilles commented
@boegelbot please test @ generoso

2021-08-09 09:40 UTC, sassy-crick commented
We already have that version, courtesy of Robert Mijakovic <robert.mijakovic@lxp.lu>, so we don't need mine here. Closed.

2021-08-09 09:40 UTC, closed without merging