{tools}[GCCcore/10.2.0] coverage v5.5 w/ Python 3.8.6
easybuilders/easybuild-easyconfigs pull request #13588
Opened 2021-08-04 09:35 UTC by SimonPinches

(created using `eb --new-pr`)

2021-08-04 13:28 UTC, Micket requested changes, later dismissed

2021-08-04 13:28 UTC, Micket commented on easybuild/easyconfigs/c/coverage/coverage-5.5-GCCcore-10.2.0.eb
> +source_urls = [PYPI_SOURCE]
Please remove, this is the default for pythonpackages now

2021-08-04 13:28 UTC, Micket commented on easybuild/easyconfigs/c/coverage/coverage-5.5-GCCcore-10.2.0.eb
> +use_pip = True
Please add sanity_pip_check = True

2021-08-07 17:47 UTC, SimonPinches commented
@Micket Thanks for the comments.  I've tidied up the EB file as requested.

2021-08-10 09:36 UTC, SimonPinches commented on easybuild/easyconfigs/c/coverage/coverage-5.5-GCCcore-10.2.0.eb
> +use_pip = True
Done :-)

2021-08-24 17:46 UTC, branfosj commented
@boegelbot please test @ generoso

2021-08-24 17:47 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/eb253cfda026d629a452b345b4a4db3c for a full test report.

2021-08-24 17:50 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/aa9c70160a6b2e865a713dc7db64a834 for a full test report.

2021-08-24 17:51 UTC, branfosj approved these changes
lgtm

2021-08-24 17:52 UTC, branfosj commented
Going in, thanks @SimonPinches!

2021-08-24 17:52 UTC, merged