MMseqs2: Use build_type instead of configopts
easybuilders/easybuild-easyconfigs pull request #13620
Opened 2021-08-05 08:38 UTC by Flamefire

(created using `eb --new-pr`)

2021-08-05 12:43 UTC, Flamefire commented
Test report by @Flamefire
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
taurusi6606.taurus.hrsk.tu-dresden.de - Linux RHEL 7.9, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/e95f9ecb4cc8da16dcb6092c9ede3720 for a full test report.

2021-08-05 19:59 UTC, branfosj commented
@boegelbot please test @ generoso
EB_ARGS="MMseqs2-10-6d92c-gompi-2019b.eb MMseqs2-10-6d92c-iimpi-2019b.eb MMseqs2-11-e1a1c-iimpi-2019b.eb MMseqs2-13-45111-gompi-2020b.eb MMseqs2-8-fac81-intel-2018b.eb"

2021-08-05 20:09 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/35b30a26a355009acbc91c96c49e9ad7 for a full test report.

2021-08-06 07:02 UTC, Flamefire commented
@branfosj 
> icc/2018.3.222-GCC-7.3.0-2.30/compilers_and_libraries_2018.3.222/linux/compiler/include/math.h(1230): error: identifier "_LIB_VERSION_TYPE" is undefined

Looks like the icc installation is broken. All changes here are purely stylistic, so can't cause this

2021-08-06 10:30 UTC, boegel requested changes

2021-08-06 10:30 UTC, boegel commented on easybuild/easyconfigs/m/MMseqs2/MMseqs2-13-45111-gompi-2020b.eb
> -configopts = '-DCMAKE_BUILD_TYPE=RELEASE'
@Flamefire `build_type = 'RELEASE'` is missing here?

2021-08-06 10:32 UTC, boegel commented on easybuild/easyconfigs/m/MMseqs2/MMseqs2-13-45111-gompi-2020b.eb
> -configopts = '-DCMAKE_BUILD_TYPE=RELEASE'
Or maybe it's not needed, since `CMakeMake` uses `-DCMAKE_BUILD_TYPE=Release` by default?

2021-08-06 10:35 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node2625.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/416d1f41fe4512c9a04e21f70f9ec410 for a full test report.

2021-08-06 10:43 UTC, boegel commented on easybuild/easyconfigs/m/MMseqs2/MMseqs2-13-45111-gompi-2020b.eb
> -configopts = '-DCMAKE_BUILD_TYPE=RELEASE'
Ah, you mentioned it in the description... Good to go then :+1:

2021-08-06 10:43 UTC, boegel approved these changes

2021-08-06 10:43 UTC, boegel commented
Going in, thanks @Flamefire!

2021-08-06 10:43 UTC, merged