{devel}[fosscuda/2020b] PyTorch v1.9.0 w/ Python 3.8.6
easybuilders/easybuild-easyconfigs pull request #13698
Opened 2021-08-11 09:28 UTC by terjekv

(created using `eb --new-pr`)

2021-08-11 09:29 UTC, terjekv commented
Depends on https://github.com/easybuilders/easybuild-easyconfigs/pull/13697

2021-08-11 09:32 UTC, terjekv commented
The three tests that are added to the exception list, `distributed/test_distributed_fork`,  `distributed/test_distributed_spawn`, and `test_optim` fail on A10 cards with Cuda Compute Capability 8.6. This failure does not seem to be IMKL-related as @zilverberg found similar issues with the default 1.9.0-build on A100 cards.

2021-08-11 09:57 UTC, Flamefire commented
Requires https://github.com/easybuilders/easybuild-easyconfigs/pull/13697

Please add short description why the tests fail as comments to the EC and a link to a TF issue where applicable

2021-08-11 10:25 UTC, terjekv commented
> Requires #13697
> 
> Please add short description why the tests fail as comments to the EC and a link to a TF issue where applicable

Will do. I need to get a few other things done today, but I'll go through my notes and logs and document the failures.

2021-08-11 13:28 UTC, Flamefire commented on easybuild/easyconfigs/p/PyTorch/PyTorch-1.9.0-fosscuda-2020b-imkl.eb
> +    'c94eda2289692d00873e2ae8cecaaf7a1e5e657dfa4cfcd94b56093f6f4766ad',
Will conflict with https://github.com/easybuilders/easybuild-easyconfigs/pull/13700
So whichever gets merged first requires a change to the other

2021-08-12 09:45 UTC, Flamefire requested changes

2021-08-12 14:22 UTC, Flamefire commented
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusi8029 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/07da567e3b0b01da99daebf3effa6061 for a full test report.

2021-08-15 05:32 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bask-pg0309u04a - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/b4baae5dfffebecb7f9ff987396c9a8e for a full test report.

2021-08-15 07:15 UTC, branfosj approved these changes
lgtm

2021-08-15 07:18 UTC, branfosj commented
Going in, thanks @terjekv!

2021-08-15 07:18 UTC, merged