update source url
easybuilders/easybuild-easyconfigs pull request #13732
Opened 2021-08-13 11:02 UTC by zemu-unile

(created using `eb --new-pr`)

2021-08-13 18:10 UTC, Micket submitted a review, later dismissed
lgtm

2021-08-13 18:11 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/e2970026e3de041c20ca91efdaaf82e8 for a full test report.

2021-08-13 19:17 UTC, boegel requested changes

2021-08-13 19:17 UTC, boegel commented on easybuild/easyconfigs/b/BLAST/BLAST-2.2.26-Linux_x86_64.eb
>  sources = ['%(namelower)s-%(version)s-x64-linux.tar.gz']
@zemu-unile Please add a SHA256 checksum, `eb --inject-checksums` is very handy for this.

2021-08-17 13:52 UTC, boegel approved these changes
lgtm

2021-08-17 13:53 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2640.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/1599433828f15bd163a8d8e544bf9359 for a full test report.

2021-08-17 13:54 UTC, boegel commented
@boegelbot please test @ generoso

2021-08-17 14:08 UTC, boegel commented
Going in, thanks @zemu-unile!

2021-08-17 14:08 UTC, merged