updates to easyconfigs for GCC 10.2.0 and compatability to build GRASS and QGIS
easybuilders/easybuild-easyconfigs pull request #13756
Opened 2021-08-17 09:40 UTC by jedokaplan

(created using `eb --new-pr`)

2021-08-17 22:32 UTC, Micket requested changes
In the newer toolchain versions, we decided to drop the python suffix, considering Python 3 to be the default. 

Another general comment, is that a PR like this much to large to be pratical to review. Especially with monster builds like Qt5 inside here, making them very impractical to just upload a test report.

2021-08-17 22:32 UTC, Micket commented on easybuild/easyconfigs/g/GTK+/GTK+-3.24.23-GCCcore-10.2.0.eb
>          ],
Please don't remove these.

2021-08-17 22:32 UTC, Micket commented on easybuild/easyconfigs/g/GEOS/GEOS-3.9.1-GCC-10.2.0-Python-3.8.6.eb
> +name = 'GEOS'
Already exists

2021-08-17 22:32 UTC, Micket commented on easybuild/easyconfigs/l/libcroco/libcroco-0.6.13-GCCcore-10.2.0.eb
> +name = 'libcroco'
Hm, well, this has a version at GCC level already, though, I suppose moving it to core is reasonable (not sure why it wasn't from the start)

2021-08-17 22:32 UTC, Micket commented on easybuild/easyconfigs/l/librsvg/librsvg-2.50.7-GCCcore-10.2.0.eb
> +name = 'librsvg'
You are adding both a GCC, and a GCCcore version

2021-08-17 22:32 UTC, Micket commented on easybuild/easyconfigs/l/librsvg/librsvg-2.50.7-foss-2020b.eb
> +name = 'librsvg'
and a foss version as well

2021-08-17 22:32 UTC, Micket commented on easybuild/easyconfigs/p/PostgreSQL/PostgreSQL-13.3-GCCcore-10.2.0.eb
> +version = '13.3'
version 13.2 already exists, I doubt this minor version bump is necessary

2021-08-17 22:32 UTC, Micket commented on easybuild/easyconfigs/p/PyQt5/PyQt5-5.15.4-GCCcore-10.2.0-Python-3.8.6.eb
> +version = '5.15.4'
Version 5.15.1 already exists, i doubt this minor version bump is necessary

2021-08-17 22:32 UTC, Micket commented on easybuild/easyconfigs/q/Qt5Webkit/Qt5Webkit-5.212.0-alpha4-GCCcore-10.2.0.eb
> -moduleclass = 'devel'
Please exclude this change

2024-01-14 09:01 UTC, boegel commented
closing this since `GCC/10.2.0` is deprecated, see https://docs.easybuild.io/policies/toolchains

2024-01-14 09:01 UTC, closed without merging