{bio}[foss/2021a] sinto v0.7.4  Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #13846
Opened 2021-08-27 14:10 UTC by ysagon

(created using `eb --new-pr`)

2021-08-30 06:52 UTC, migueldiascosta requested changes

2021-08-30 06:52 UTC, migueldiascosta commented on easybuild/easyconfigs/s/sinto/sinto-0.7.3.1-foss-2020b-Python-3.8.6.eb
> +versionsuffix = '-Python-%(pyver)s'
'-Python-%(pyver)s' should no longer be included in versionsuffix (when using the default Python for that toolchain)

2021-08-30 06:52 UTC, migueldiascosta commented on easybuild/easyconfigs/s/sinto/sinto-0.7.3.1-foss-2020b-Python-3.8.6.eb
> +source_urls = [PYPI_SOURCE]
'source_urls' should not be defined when using the default value

2021-08-30 06:52 UTC, migueldiascosta commented on easybuild/easyconfigs/s/sinto/sinto-0.7.3.1-foss-2020b-Python-3.8.6.eb
> +
sanity_pip_check should be enabled

2022-07-19 11:38 UTC, bedroge submitted a review, later dismissed
Just some very minor style remarks (mostly removing blank lines between parameters that are usually grouped together), other than that it looks fine.

2022-07-19 11:38 UTC, bedroge commented on easybuild/easyconfigs/s/sinto/sinto-0.7.4-foss-2021a.eb
> +
```suggestion
name = 'sinto'
version = '0.7.4'

homepage = 'https://timoast.github.io/sinto/index.html'
```

2022-07-19 11:38 UTC, bedroge commented on easybuild/easyconfigs/s/sinto/sinto-0.7.4-foss-2021a.eb
> +"""
I think I would either just go for:
```suggestion
description = """Sinto is a toolkit for processing aligned single-cell data."""
```
or I'd add the entire list of functions that they also include on their site?

2022-07-19 11:38 UTC, bedroge commented on easybuild/easyconfigs/s/sinto/sinto-0.7.4-foss-2021a.eb
> +sanity_pip_check = True
```suggestion
use_pip = True
download_dep_fail = True
sanity_pip_check = True
```

2024-01-13 19:15 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3147.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/b729a7e9f8181fc54803c301a2476c77 for a full test report.

2024-01-13 19:23 UTC, boegel commented
@boegelbot please test @ generoso

2024-01-13 19:34 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2024-01-13 19:34 UTC, boegel approved these changes
lgtm

2024-01-13 19:44 UTC, boegel commented
Going in, thanks @ysagon!

2024-01-13 19:44 UTC, merged