medaka updated to latest version and foss-2020b, required by artic (PR# 13852), WIP
easybuilders/easybuild-easyconfigs pull request #13853
Opened 2021-08-30 13:44 UTC by sassy-crick

(created using `eb --new-pr`)

2021-08-30 13:51 UTC, sassy-crick commented
Depends on fixed version of TensorFlow [13854](https://github.com/easybuilders/easybuild-easyconfigs/pull/13854)

2021-09-16 08:56 UTC, boegel requested changes

2021-09-16 08:56 UTC, boegel commented on easybuild/easyconfigs/m/medaka/medaka-1.4.3-TF-version-fix.patch
> +Removing hard-coded version for TensorFlow
It's easier to deal with this with a `sed` command in `preinstallopts` for the TensorFlow extension.

Also, we should refer to https://github.com/nanoporetech/medaka/issues/323

2021-09-16 08:56 UTC, boegel commented on easybuild/easyconfigs/m/medaka/medaka-1.4.3-foss-2020b.eb
> +    ('h5py', '2.10.0', {
I don't think we need to install `h5py` as an extension here, since it's part of the TensorFlow installation already?

2021-09-16 08:56 UTC, boegel commented on easybuild/easyconfigs/m/medaka/medaka-1.4.3-foss-2020b.eb
> +sanity_pip_check = True
This is also set below, should be removed here

2021-09-16 15:51 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2606.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/a2f2a8e984b9b96e33097e16097445b9 for a full test report.

2021-09-16 15:53 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3617.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/8a8c8b44703db018c4e369376950339e for a full test report.

2021-09-16 18:57 UTC, boegel commented
@boegelbot please test @ generoso

2021-09-16 19:06 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2606.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/1c6124a6af1a0249430641e99d3dcd15 for a full test report.

2021-09-17 07:09 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3511.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/f40ec15b0793bdf68d91f977de1e52f0 for a full test report.

2021-09-17 07:53 UTC, boegel approved these changes

2021-09-17 07:54 UTC, boegel commented
Going in, thanks @sassy-crick!

2021-09-17 07:54 UTC, merged