TF bumped to foss-2020b for the fixed requirement for medaka (PR# 13853), WIP
easybuilders/easybuild-easyconfigs pull request #13854
Opened 2021-08-30 13:46 UTC by sassy-crick

(created using `eb --new-pr`)

2021-08-30 15:22 UTC, Flamefire requested changes
See comments inline. Need updating checksums after changing versions too.

Note that you can use "Add to batch commit" (or so) from the "Files" tab to accept all changes in 1 commit

2021-08-30 15:22 UTC, Flamefire commented on easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.2-foss-2020b.eb
> +    ('cachetools', '4.2.1', {
```suggestion
    ('cachetools', '4.2.2', {
```

2021-08-30 15:22 UTC, Flamefire commented on easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.2-foss-2020b.eb
> +    ('google-auth', '1.28.0', {
```suggestion
    ('google-auth', '1.35.0', {
```

2021-08-30 15:22 UTC, Flamefire commented on easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.2-foss-2020b.eb
> +    ('oauthlib', '3.1.0', {
```suggestion
    ('oauthlib', '3.1.1', {
```

2021-08-30 15:22 UTC, Flamefire commented on easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.2-foss-2020b.eb
> +    ('google-auth-oauthlib', '0.4.4', {
```suggestion
    ('google-auth-oauthlib', '0.4.5', {
```

2021-08-30 15:22 UTC, Flamefire commented on easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.2-foss-2020b.eb
> +    ('Werkzeug', '1.0.1', {
```suggestion
    ('Werkzeug', '2.0.1', {
```

2021-08-30 15:22 UTC, Flamefire commented on easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.2-foss-2020b.eb
> +    ('absl-py', '0.12.0', {
```suggestion
    ('absl-py', '0.13.0', {
```

2021-08-30 15:22 UTC, Flamefire commented on easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.2-foss-2020b.eb
> +    ('grpcio', '1.36.1', {
```suggestion
    ('grpcio', '1.39.0', {
```

2021-08-30 15:22 UTC, Flamefire commented on easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.2-foss-2020b.eb
> +    ('tensorboard', version, {
```suggestion
    ('tensorboard', '2.2.2', {
```

2021-08-30 15:22 UTC, Flamefire commented on easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.2-foss-2020b.eb
> +    ('astor', '0.8.1', {
Not required at all as far as I can tell. Not sure why this is included...

2021-08-30 15:33 UTC, Flamefire commented
Required Bazel at https://github.com/easybuilders/easybuild-easyconfigs/pull/13855

2021-08-31 08:04 UTC, Flamefire commented on easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.2-foss-2020b.eb
> +    ('astor', '0.8.1', {
Ah no, required by TF

2021-08-31 08:39 UTC, sassy-crick commented
Dependencies:

Requires [Bazel](https://github.com/easybuilders/easybuild-easyconfigs/pull/13855)

2021-09-15 11:12 UTC, boegel commented on easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.2-foss-2020b.eb
> +    # TF 2.2 requires SciPy 1.4.1 due to potential crashes with other versions
Huh, indeed, see also https://github.com/tensorflow/tensorflow/pull/41866 .

2021-09-15 13:46 UTC, Flamefire commented
Tests started, @sassy-crick can you mark this as ready for review?

2021-09-15 14:21 UTC, Flamefire commented
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusi8012 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), Python 2.7.5
See https://gist.github.com/c6bd29458696ded2f74a480e14aaedd5 for a full test report.

2021-09-15 14:56 UTC, boegel commented
@boegelbot please test @ generoso
CORE_CNT=16

2021-09-15 15:18 UTC, Flamefire commented
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusml14 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), Python 2.7.5
See https://gist.github.com/f695ad69f41a1611d63e45b83cb86615 for a full test report.

2021-09-15 16:12 UTC, Flamefire commented
Test report by @Flamefire
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusa4 - Linux centos linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), Python 2.7.5
See https://gist.github.com/f29af09d41697a0f21657b8021e4aadd for a full test report.

2021-09-15 16:35 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3504.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/1d3c4083fe5d6728003419e183da04b9 for a full test report.

2021-09-15 16:38 UTC, boegel commented
@Flamefire We probably shouldn't let the failing test report from POWER9 block this PR?

```
Executed 15 out of 746 tests: 15 tests pass, 1 fails to build and 730 were skipped.
FAILED: Build did NOT complete successfully
```

2021-09-15 18:28 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2642.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/b38fc456478ad34900b0da01ae6480bb for a full test report.

2021-09-16 08:25 UTC, boegel approved these changes
lgtm

2021-09-16 08:30 UTC, boegel commented
Going in, thanks @sassy-crick!

2021-09-16 08:30 UTC, merged