{bio}[] PLINK2 20210826
easybuilders/easybuild-easyconfigs pull request #13850
Opened 2021-08-29 19:17 UTC by fizwit

(created using `eb --new-pr`)

2021-09-01 18:17 UTC, fizwit commented
I am requesting that PLINK 2 be called PLINK2. PLINK 2 is a fork of PLINK and binary is called plink2.

2021-09-14 08:35 UTC, verdurin commented
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.6
See https://gist.github.com/3c07b6a500285cb552aa8a2a875768c9 for a full test report.

2021-09-14 08:36 UTC, verdurin requested changes

2021-09-14 08:36 UTC, verdurin commented on easybuild/easyconfigs/p/PLINK2/PLINK2-20210826-linux_x86_64.eb
> +source_urls = ['http://s3.amazonaws.com/plink2-assets']
@fizwit seeing a `404` error when downloading the sources.

2021-09-14 08:36 UTC, verdurin commented on easybuild/easyconfigs/p/PLINK2/PLINK2-20210826-linux_x86_64.eb
> +name = 'PLINK2'
New name is fine by me.

2024-04-15 22:15 UTC, fizwit commented
Closing this PR because it is very out of date. PLINK2/20240205_linux_avx2 is available

2024-04-15 22:15 UTC, closed without merging