{bio}[fosscuda/2020b] AlphaFold v2.0.0 w/ Python 3.8.6
easybuilders/easybuild-easyconfigs pull request #13867
Opened 2021-08-31 14:59 UTC by boegel

(created using `eb --new-pr`)

2021-08-31 15:17 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3302.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), Python 3.6.8
See https://gist.github.com/7715dc604e16aeab8c9b893aaeba18c4 for a full test report.

2021-08-31 16:22 UTC, akesandgren commented
Test report by @akesandgren
**FAILED**
Build succeeded for 1 out of 3 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.5
See https://gist.github.com/43825459c05812acbf25ff445c88e577 for a full test report.

2021-08-31 16:51 UTC, akesandgren commented
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in total)
b-an04.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.5
See https://gist.github.com/234e349caf7c56f92b9b1539008953c7 for a full test report.

2021-08-31 18:33 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jwvis00.juwels - Linux centos linux 8.4.2105, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/825fdbb3d277b26a5bcf7b540acba39e for a full test report.

2021-08-31 18:55 UTC, boegel commented
@akesandgren Make sure you're using `develop`, you need https://github.com/easybuilders/easybuild-easyblocks/pull/2547 next to the custom easyblock for `jax`

2021-08-31 19:01 UTC, akesandgren commented
I know, I just had forgotten to update...

2021-08-31 20:59 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsfc060 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7742 64-Core Processor, Python 3.6.8
See https://gist.github.com/45e24280e738bb4cd08bf9122f3e6aa1 for a full test report.

2021-09-01 05:51 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an04.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.5
See https://gist.github.com/731e7b7f01c735bad0c70360d384bf28 for a full test report.

2021-09-01 05:56 UTC, akesandgren requested changes

2021-09-01 05:56 UTC, akesandgren commented on easybuild/easyconfigs/a/AlphaFold/AlphaFold-2.0.0-fosscuda-2020b.eb
> +    # CMake/oxygen/SWIG are required for building OpenMM
Doxygen, probably needs fixing in the non-GPU version too.

2021-09-01 07:00 UTC, akesandgren approved these changes

2021-09-01 07:01 UTC, akesandgren approved these changes
LGTM

2021-09-01 07:33 UTC, akesandgren commented
Going in, thanks @boegel!

2021-09-01 07:33 UTC, merged