{lib}[GCCcore/8.3.0] FSON v1.0.5
easybuilders/easybuild-easyconfigs pull request #13863
Opened 2021-08-31 11:35 UTC by DirectorSloan

(created using `eb --new-pr`)

2021-09-01 09:27 UTC, Micket requested changes

2021-09-01 09:27 UTC, Micket commented on easybuild/easyconfigs/f/FSON/FSON-1.0.5-GCCcore-8.3.0.eb
> +    'files': ['lib64/libFSON.so'],
```suggestion
    'files': ['lib64/libFSON.%s' % SHLIB_EXT]
```

2021-09-01 09:27 UTC, Micket commented on easybuild/easyconfigs/f/FSON/FSON-1.0.5-GCCcore-8.3.0.eb
> +configopts = "-DBUILD_SHARED_LIBS=ON"
```suggestion
configopts = ['-DBUILD_SHARED_LIBS=OFF', '-DBUILD_SHARED_LIBS=ON']
```
usually nice to provide both (though this is not a requirement)

2021-09-04 09:22 UTC, boegel commented
@DirectorSloan Thanks a lot for your contribution! Are you up for making the requested changes?

2022-03-02 14:36 UTC, DirectorSloan commented
will make a new one

2022-03-02 14:36 UTC, closed without merging