{lib}[foss/2020b] AMPtorch v0.1 w/ Python 3.8.6
easybuilders/easybuild-easyconfigs pull request #13920
Opened 2021-09-07 08:03 UTC by akesandgren

(created using `eb --new-pr`)

2021-09-07 08:10 UTC, akesandgren commented
@boegelbot Please test @ generoso

2021-09-07 08:10 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.5
See https://gist.github.com/d0c502a4274e99f97c4f349c30e9a2bc for a full test report.

2021-09-07 08:43 UTC, akesandgren commented
The check failures are due to a bunch of .ebs using numba-0.52.0 (which has LLVM 10.0.1) in the 2020b toolchain while most use numba-0.53.1 with LLVM 11.0.0

I.e. not this PR's fault...

2021-09-13 16:27 UTC, verdurin requested changes

2021-09-13 16:27 UTC, verdurin commented on easybuild/easyconfigs/a/AMPtorch/AMPtorch-0.1-foss-2020b.eb
> +sources = [{'filename': SOURCE_TAR_GZ, 'download_filename': 'v%(version)s.tar.gz'}]
@akesandgren please add the missing `checksum`.

2024-01-13 18:56 UTC, boegel commented
closing this since `foss/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains

2024-01-13 18:56 UTC, closed without merging