{tools}[system/system] rclone v1.56.0
easybuilders/easybuild-easyconfigs pull request #13937
Opened 2021-09-08 03:59 UTC by scicomp-moffitt

(created using `eb --new-pr`)

2021-09-08 15:48 UTC, lexming requested changes

2021-09-08 15:48 UTC, lexming commented on easybuild/easyconfigs/r/rclone/rclone-1.56.0.eb
> +#versionsuffix = '-amd64'
Please keep the version suffix for this easyconfig as the binaries are specific to `amd64`.

2021-09-08 15:48 UTC, lexming commented on easybuild/easyconfigs/r/rclone/rclone-1.56.0.eb
> +#checksums = ['c52cbf3646a2d15765b87cf05fc3b2bca3b1d2782d4922046c597bd979e42720']
Checksums are missing.

2021-09-10 08:14 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/009a94d7ea0092d2343579dab7ec5cd6 for a full test report.

2021-09-10 08:27 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node381.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ec37dc22fc247cbfff9f27dd232f00e1 for a full test report.

2021-09-10 08:27 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3103.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/09d24b4212490e99dd8cfa96a4aa9e63 for a full test report.

2021-09-10 08:29 UTC, lexming approved these changes
@scicomp-moffitt thanks for the update!

LGTM

2021-09-10 08:30 UTC, lexming commented
@boegelbot please test @ generoso

2021-09-10 08:31 UTC, lexming commented
Going in, thanks @scicomp-moffitt !

2021-09-10 08:42 UTC, lexming commented
@boegelbot please test @ generoso

2021-09-10 08:48 UTC, merged