{bio}[foss/2020b] IQ-TREE bumped to 2.1.2, required for artic
easybuilders/easybuild-easyconfigs pull request #13991
Opened 2021-09-15 12:32 UTC by sassy-crick

(created using `eb --new-pr`)

2021-09-15 15:51 UTC, verdurin commented
@sassy-crick `Eigen/3.3.9` is only currently available in `GCCcore/11.2.0` and `10.3.0`. Please add the correct dependency.

2021-09-15 16:35 UTC, sassy-crick commented
> @sassy-crick `Eigen/3.3.9` is only currently available in `GCCcore/11.2.0` and `10.3.0`. Please add the correct dependency.

I agree, However, the build fails with this version of Eigen with:
`error: eigen_assert_exception is not a member of Eigen`
Which got solved by the later version of Eigen. How shall we solve that?

2021-09-16 09:38 UTC, boegel commented
@sassy-crick Since Eigen is just a build dependency, you can resolve the issue by adding an easyconfig for Eigen 3.3.9 with `GCCcore/10.2.0` (maybe best in a separate PR).

This shouldn't cause trouble, because Eigen is a header-only library, so it's a build-only dependency (won't result in having two Eigen versions loaded at runtime).

2021-09-16 09:51 UTC, sassy-crick commented
@boegel Thanks for your advice, I have done that as requested. 
- [ ] Requires #14009

2021-09-17 15:00 UTC, boegel approved these changes
lgtm

2021-09-17 15:20 UTC, verdurin commented
@boegelbot please test @ generoso

2021-09-17 15:26 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
nuc.lan - Linux Fedora 33, x86_64, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, Python 3.9.6
See https://gist.github.com/ec4ffa88aec172db10090300fb865646 for a full test report.

2021-09-17 15:29 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/5642062eb06b241af40e3795ce83e01d for a full test report.

2021-09-17 15:36 UTC, boegel requested changes

2021-09-17 15:36 UTC, boegel commented on easybuild/easyconfigs/i/IQ-TREE/IQ-TREE-2.1.2-foss-2020b.eb
> +toolchain = {'name': 'foss', 'version': '2020b'}
@sassy-crick We can/should drop this to `gompi`, see https://github.com/sassy-crick/easybuild-easyconfigs/pull/6

2021-09-17 18:05 UTC, boegel approved these changes

2021-09-17 18:09 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node2635.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/2e469d6a8f893c2019f1aa020a2c50fb for a full test report.

2021-09-17 18:12 UTC, boegel commented
Going in, thanks @sassy-crick!

2021-09-17 18:12 UTC, merged