{compiler,mpi,toolchain}[system/system] OpenMPI v4.1.1, nvompi v2021a, NVHPC v21.7
easybuilders/easybuild-easyconfigs pull request #14006
Opened 2021-09-15 19:12 UTC by Micket

(created using `eb --new-pr`)

2021-09-15 20:22 UTC, SebastianAchilles requested changes
NVHPC 21.7 is not compatible to GCC 11. I suggest we wait for 21.9 which should be released soon.

2021-09-16 18:06 UTC, Micket commented
preliminary change to 21.9, checksums to be updated of course. I also fixed a version mistake, and switched to option 2

2021-09-22 11:20 UTC, SebastianAchilles commented on easybuild/easyconfigs/n/NVHPC/NVHPC-21.9-CUDA-11.4.1.eb
> +]
```suggestion
checksums = [
    {
        local_tarball_tmpl % 'aarch64':
            '52c2c66e30043add4afccedf0ba77daa0000bf42e0db844baa630bb635b91a7d',
        local_tarball_tmpl % 'ppc64le':
            'cff0b55fb782be1982bfeec1d9763b674ddbf84ff2c16b364495299266320289',
        local_tarball_tmpl % 'x86_64':
            '7de6a6880fd7e59afe0dee51f1fae4d3bff1ca0fb8ee234b24e1f2fdff23ffc9',
    }
]
```

2021-09-24 12:45 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/ee9c1a188d9c76a2d2f3b588d0215bcc for a full test report.

2021-09-24 12:48 UTC, SebastianAchilles commented
> Test report by @SebastianAchilles
> **SUCCESS**
> Build succeeded for 1 out of 1 (1 easyconfigs in total)
> rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
> See https://gist.github.com/ee9c1a188d9c76a2d2f3b588d0215bcc for a full test report.

This is only `NVHPC-21.9-CUDA-11.4.1.eb`.

2021-09-24 13:59 UTC, Micket commented
Test report by @Micket
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/86dd710edad7b86fbcd4576185b854e6 for a full test report.

2021-09-24 15:32 UTC, Micket commented
Test report by @Micket
**FAILED**
Build succeeded for 1 out of 4 (4 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/87202dbbd4f67c033fdee4fbb06df831 for a full test report.

2021-09-24 17:13 UTC, Micket commented
Hrm linking errors
```
ld: ./.libs/liblocal_ops_avx512.a(liblocal_ops_avx512_la-op_avx_functions.o):(.data+0x1250): multiple definition of `ompi_op_avx_3buff_functions_avx2'; ./.libs/liblocal_ops_avx2.a(liblocal_ops_avx2_la-op_avx_functions.o):(.data+0x1250): first defined here
ld: ./.libs/liblocal_ops_avx512.a(liblocal_ops_avx512_la-op_avx_functions.o):(.data+0x0): multiple definition of `ompi_op_avx_functions_avx2'; ./.libs/liblocal_ops_avx2.a(liblocal_ops_avx2_la-op_avx_functions.o):(.data+0x0): first defined here
```

2022-10-17 14:14 UTC, jfgrimm reviewed
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 14006` and update the PR to use `SYSTEM` instead.

2023-05-25 11:31 UTC, closed without merging