{bio}[GCCcore/10.2.0] vawk v0.0.1 w/ Python 2.7.18
easybuilders/easybuild-easyconfigs pull request #14040
Opened 2021-09-20 23:10 UTC by scicomp-moffitt

(created using `eb --new-pr`)

2021-09-21 08:12 UTC, SebastianAchilles requested changes
This should fix:
```
vawk-0.0.1-GCCcore-10.2.0-Python-2.7.18.eb:12:12: E222 multiple spaces after operator
```

2021-09-21 08:12 UTC, SebastianAchilles commented on easybuild/easyconfigs/v/vawk/vawk-0.0.1-GCCcore-10.2.0-Python-2.7.18.eb
> +toolchain =  {'name': 'GCCcore', 'version': '10.2.0'}
```suggestion
toolchain = {'name': 'GCCcore', 'version': '10.2.0'}
```

2021-09-23 08:29 UTC, SebastianAchilles requested changes
I think this should go in the `GCC` toolchain. `GCC` contains `GCCcore` and `binutils` which is needed for `Python`.

2021-09-23 08:29 UTC, SebastianAchilles commented on easybuild/easyconfigs/v/vawk/vawk-0.0.1-GCCcore-10.2.0-Python-2.7.18.eb
> +toolchain = {'name': 'GCCcore', 'version': '10.2.0'}
```suggestion
toolchain = {'name': 'GCC', 'version': '10.2.0'}
```

2021-09-25 17:28 UTC, scicomp-moffitt commented
Currently I always wait until someone explains the error message from the bot. Is there any way I can find that myself ? Where do these "E216 ...blala" explanations come from? I cannot find them .

2021-09-28 07:46 UTC, smoors commented
@scicomp-moffitt as discussed with @SebastianAchilles we can keep the `GCCcore` toolchain and add `binutils` as build dep.
I just made these changes for you.

2021-09-28 08:03 UTC, smoors commented
@boegelbot: please test @ generoso

2021-09-28 08:07 UTC, smoors approved these changes
lgtm

2021-09-28 08:14 UTC, smoors commented
Going in, thanks @scicomp-moffitt!

2021-09-28 08:14 UTC, merged