{bio}[system/system] MixMHC2pred v1.2
easybuilders/easybuild-easyconfigs pull request #14041
Opened 2021-09-20 23:45 UTC by scicomp-moffitt

(created using `eb --new-pr`)

2021-09-21 08:11 UTC, SebastianAchilles requested changes
This should fix
```
MixMHC2pred-1.2.eb:20:62: W299 trailing whitespace
```

2021-09-21 08:11 UTC, SebastianAchilles commented on easybuild/easyconfigs/m/MixMHC2pred/MixMHC2pred-1.2.eb
> +    "mv %(installdir)s/%(name)s %(installdir)s/%(name)s_mac",
```suggestion
    "mv %(installdir)s/%(name)s %(installdir)s/%(name)s_mac",
```

2021-09-23 08:25 UTC, SebastianAchilles commented
@boegelbot please test @ generoso

2021-09-24 05:48 UTC, SebastianAchilles requested changes

2021-09-24 05:48 UTC, SebastianAchilles commented on easybuild/easyconfigs/m/MixMHC2pred/MixMHC2pred-1.2.eb
> +easyblock = 'PackedBinary'
```suggestion
easyblock = 'PackedBinary'
```

2021-09-27 15:44 UTC, smoors approved these changes
lgtm

2021-09-27 15:47 UTC, smoors commented
Going in, thanks @scicomp-moffitt!

2021-09-27 15:47 UTC, merged