{chem}[foss/2020b,fosscuda/2020b] NAMD v2.14
easybuilders/easybuild-easyconfigs pull request #14101
Opened 2021-10-05 15:44 UTC by dithwick

(created using `eb --new-pr`)

2021-10-05 16:17 UTC, SebastianAchilles commented
@boegelbot: please test @ generoso

2021-10-05 16:53 UTC, SebastianAchilles commented
> Test report by @boegelbot **FAILED** Build succeeded for 1 out of 2 (2 easyconfigs in total) cnx1 - Linux rocky linux 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8 See https://gist.github.com/7851b440856e35d664e545d008b873a6 for a full test report.

`NAMD-2.14-fosscuda-2020b.eb` fails on generoso, because generoso has no GPUs.

2021-10-06 18:43 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3302.joltik.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 4 x NVIDIA NVIDIA Tesla V100-SXM2-32GB, 465.19.01, Python 3.6.8
See https://gist.github.com/a2375482bf9e832399a0a931e9ce3d71 for a full test report.

2021-10-06 18:48 UTC, SebastianAchilles requested changes
I think it is better to use a `builddependencies` for `tcsh` instead of `osdependencies`.

2021-10-06 18:48 UTC, SebastianAchilles commented on easybuild/easyconfigs/n/NAMD/NAMD-2.14-foss-2020b-mpi.eb
> +osdependencies = ['tcsh']
```suggestion
```

2022-01-17 16:34 UTC, smoors commented on easybuild/easyconfigs/n/NAMD/NAMD-2.14-fosscuda-2020b.eb
> +osdependencies = ['tcsh']
@dithwick I've just updated the NAMD easyblock to make this work:
https://github.com/easybuilders/easybuild-easyblocks/pull/2654

2022-01-20 08:25 UTC, dithwick commented on easybuild/easyconfigs/n/NAMD/NAMD-2.14-fosscuda-2020b.eb
> +osdependencies = ['tcsh']
Thanks, I'm just testing although I can't see why it shouldn't work.

2022-01-20 08:35 UTC, dithwick commented
depends on easyblock PR:

https://github.com/easybuilders/easybuild-easyblocks/pull/2654

2022-05-31 06:45 UTC, akesandgren commented
Test report by @akesandgren
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/ed355b0f3c987463baf824e2853dc3d1 for a full test report.

2022-05-31 06:55 UTC, akesandgren commented
Test report by @akesandgren
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
b-cn1126.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, 8 x NVIDIA Tesla K80, 470.129.06, Python 3.8.10
See https://gist.github.com/077a85b4ed29714fbcd0d17452958726 for a full test report.

2022-05-31 11:21 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-cn1126.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, 8 x NVIDIA Tesla K80, 470.129.06, Python 3.8.10
See https://gist.github.com/73444f236ef31815a0d06a377742175f for a full test report.

2022-05-31 11:47 UTC, akesandgren commented
Unfortunately the changes in https://github.com/easybuilders/easybuild-easyblocks/pull/2654 is not enough.

Our current tcsh package does not have a csh cmd, only a tcsh. And the builddep on tcsh is not enough at the moment and needs to be a runtime dep since there a re plugin scripts in NAMD that uses (t)csh

2022-05-31 12:19 UTC, akesandgren requested changes

2022-05-31 13:45 UTC, akesandgren commented
Updated tcsh easyconfigs in #15571

2022-08-18 11:50 UTC, dithwick commented on easybuild/easyconfigs/n/NAMD/NAMD-2.14-foss-2020b-mpi.eb
> +builddependencies = [
I've made the changes to the easyconfigs

2022-08-18 11:51 UTC, dithwick commented
Apologies, completely forgot about submitting this. I've made the requested changes.

2023-02-27 15:14 UTC, akesandgren commented
Test report by @akesandgren
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
b-cn1501.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, 2 x NVIDIA Tesla V100-PCIE-16GB, 470.161.03, Python 3.8.10
See https://gist.github.com/e40fb296b5ad7bdcb356e861efe5934f for a full test report.

2023-02-27 15:33 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-cn1501.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz, 2 x NVIDIA Tesla V100-PCIE-16GB, 470.161.03, Python 3.8.10
See https://gist.github.com/b3926c6bf6c077873f8336c6e28fd0ca for a full test report.

2023-02-27 15:48 UTC, akesandgren approved these changes
LGTM

2023-02-27 15:49 UTC, akesandgren commented
Going in, thanks @dithwick!

2023-02-27 15:49 UTC, merged