{bio}[foss/2020a] Mash v2.2
easybuilders/easybuild-easyconfigs pull request #14245
Opened 2021-10-29 10:43 UTC by robqiao

(created using `eb --new-pr`)

edit: requires ~#14244~ (CapnProto)

2021-10-31 12:42 UTC, boegel commented
@boegelbot please test @ generoso

2021-10-31 13:04 UTC, boegel commented
close/re-open to re-trigger test suite with latest `develop` now #14244 is merged

2021-10-31 14:53 UTC, boegel requested changes

2021-11-04 04:11 UTC, robqiao commented on easybuild/easyconfigs/m/Mash/Mash-2.2-foss-2020a.eb
> +toolchain = {'name': 'foss', 'version': '2020a'}
LGTM, updated. Thx @boegel

2021-11-04 09:30 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/55f5d19d3e27d6311cd5e2f4ecc28e72 for a full test report.

2021-11-04 09:31 UTC, verdurin commented
@boegelbot please test @ generoso

2021-11-04 16:48 UTC, verdurin approved these changes
Looks fine.

2021-11-04 16:49 UTC, verdurin commented
Going in, thanks @robqiao!

2021-11-04 16:49 UTC, merged