{phys}[intel/2021a] DFTB+ v21.1 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #14252
Opened 2021-10-29 19:50 UTC by akesandgren

(created using `eb --new-pr`)

2021-10-29 19:54 UTC, akesandgren commented
Test report by @akesandgren
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/c798767c7d5a7ea3dd62136a861f9b96 for a full test report.

2021-10-30 08:31 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/3b17fb82c96a5d97d2c9786d5eb357eb for a full test report.

2021-10-31 18:22 UTC, boegel requested changes

2021-10-31 18:22 UTC, boegel commented on easybuild/easyconfigs/d/DFTB+/DFTB+-21.1_use_dftd3_from_EB.patch
> +diff -ru dftbplus-21.1.orig/external/dftd3/CMakeLists.txt dftbplus-21.1/external/dftd3/CMakeLists.txt
missing patch description + author?

2021-10-31 18:22 UTC, boegel commented on easybuild/easyconfigs/d/DFTB+/DFTB+-21.1-intel-2021a.eb
> +sanity_check_commands = [('python', '-c "import dptools"')]
```suggestion
sanity_check_commands = ["python -c 'import dptools'"]

2021-10-31 18:22 UTC, boegel commented on easybuild/easyconfigs/d/DFTB+/DFTB+-21.1-intel-2021a.eb
> +
please drop duplicate empty line

2021-10-31 18:22 UTC, boegel commented on easybuild/easyconfigs/d/dftd3-lib/dftd3-lib-0.9-intel-compilers-2021.2.0.eb
> +    'files': ['bin/dftd3', 'bin/testapi', 'lib/libdftd3.a'],
Can we add a sanity check command here too?

2021-11-01 07:35 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/9ca391d05300be27c16142ba5ac3a525 for a full test report.

2021-12-02 22:27 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/14a8820f7fd6ad324dc934cbbaf22a2a for a full test report.

2022-03-23 06:51 UTC, akesandgren commented
@boegelbot Please test @ generoso

2022-03-23 22:21 UTC, sassy-crick commented
Test report by @sassy-crick
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
hp - Linux Debian GNU/Linux 11, x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (icelake), Python 3.9.2
See https://gist.github.com/f984e3e49bbb5260b08c51a3a4badd64 for a full test report.

2022-03-25 10:21 UTC, branfosj approved these changes
lgtm

2022-03-25 10:34 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2617.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/842e81a88a658f971210461830bacf50 for a full test report.

2022-03-25 10:54 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/b75fc8d3d597ad8de5da2955094ae62f for a full test report.

2022-03-25 10:56 UTC, branfosj commented
Going in, thanks @akesandgren!

2022-03-25 10:58 UTC, branfosj commented
Going in, thanks @akesandgren!

2022-03-25 12:16 UTC, branfosj commented
Going in, thanks @akesandgren!

2022-03-25 12:16 UTC, merged