{bio}[foss/2021a] bcbio-gff v0.6.7 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #14322
Opened 2021-11-11 10:57 UTC by robqiao

(created using `eb --new-pr`)

2021-11-11 11:02 UTC, verdurin requested changes

2021-11-11 11:02 UTC, verdurin commented on easybuild/easyconfigs/b/bcbio-gff/bcbio-gff-0.6.7-foss-2021a.eb
> +bcbiogffroot = 'lib/python%(pyshortver)s/site-packages'
@robqiao as with the other version, please use the `local_` prefix for these variables cf. https://easybuild.readthedocs.io/en/latest/Easyconfig-files-local-variables.html

2021-11-12 06:43 UTC, migueldiascosta commented on easybuild/easyconfigs/b/bcbio-gff/bcbio-gff-0.6.7-foss-2021a.eb
> +]
also missing `Biopython`?

2021-11-22 11:15 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2633.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/dfb0be839d5e1bfb963d468b6b26c027 for a full test report.

2021-11-22 11:17 UTC, boegel commented
@boegelbot please test @ generoso

2021-11-22 11:23 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsfc01.int.jusuf.sebastian.cluster - Linux rocky linux 8.4, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/ea73f16aca35762de70e7b4fb0b5bf4c for a full test report.

2021-11-22 11:23 UTC, boegel approved these changes
lgtm

2021-11-22 11:25 UTC, boegel commented
Going in, thanks @manifestoso!

2021-11-22 11:25 UTC, merged