{tools}[GCCcore/11.2.0] ROCR-Runtime v4.5.0, ROCT-Thunk-Interface v4.5.0, Clang-AOMP v4.5.0, ... w/ Python 3.9.6
easybuilders/easybuild-easyconfigs pull request #14327
Opened 2021-11-12 07:37 UTC by nordmoen

(created using `eb --new-pr`)

2021-11-12 07:49 UTC, nordmoen commented
This requires the Clang-AOMP easyblock: easybuilders/easybuild-easyblocks#2617

2021-12-08 21:05 UTC, boegel requested changes

2021-12-09 06:21 UTC, nordmoen commented on easybuild/easyconfigs/r/ROCT-Thunk-Interface/ROCT-Thunk-Interface-4.5.0-GCCcore-11.2.0.eb
> +group = 'video'
Not sure at all, just based on the requirements that AMD put in ROCT

2021-12-09 12:36 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2617
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
pg-lab02 - Linux centos linux 8.3.2011, x86_64, AMD EPYC 7542 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/01bae407ce8f14aabff05b9d440b5284 for a full test report.

2021-12-10 08:18 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2617
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
pg-lab02 - Linux centos linux 8.3.2011, x86_64, AMD EPYC 7542 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/e43ab497e94214ebb6e67a460a5a8e97 for a full test report.

2021-12-10 09:02 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2617
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3517.doduo.os - Linux RHEL 8.2, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/a9ddef80263dbfe95ada21b8acec806e for a full test report.

2021-12-10 18:29 UTC, boegel approved these changes

2021-12-10 18:29 UTC, boegel commented
Going in, thanks @nordmoen!

2021-12-10 18:29 UTC, merged