{tools}[foss/2021a] jax v0.2.24 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #14334
Opened 2021-11-12 21:38 UTC by lexming

(created using `eb --new-pr`)

2021-11-13 11:04 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3907.accelgor.os - Linux RHEL 8.4, x86_64, AMD EPYC 7413 24-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/28c52ae7287cf9377108ec967c70cabd for a full test report.

2021-11-13 12:12 UTC, branfosj commented
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2619
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0104u03a.bear.cluster - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/766a170ae7f998c33b1a9d1cba52212d for a full test report.

2021-11-13 12:26 UTC, branfosj commented
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2619
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/f7e986ace87ac42048e753a396ccd5cf for a full test report.

2021-11-13 15:03 UTC, branfosj commented
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2619
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0212u15b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), 1 x NVIDIA Tesla P100-PCIE-16GB, 460.32.03, Python 3.6.8
See https://gist.github.com/4ac103b4252426d348ea3f89c91bba97 for a full test report.

2021-11-13 15:06 UTC, branfosj commented
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2619
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0103u01a.bear.cluster - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 2 x NVIDIA NVIDIA A100-PCIE-40GB, 470.57.02, Python 3.6.8
See https://gist.github.com/4a31845ad8292602aa1a307db9c90a2e for a full test report.

2021-11-13 15:09 UTC, branfosj commented
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2619
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0103u04a.bear.cluster - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 2 x NVIDIA NVIDIA A30, 470.57.02, Python 3.6.8
See https://gist.github.com/d1ca96be87e97d3a66eb6d9f625d0384 for a full test report.

2021-11-19 19:34 UTC, branfosj commented
The patch at https://github.com/bear-rsg/easybuild-easyconfigs/blob/243f67c76370d3cb38b9f3ced3f6984236a675bc/easybuild/easyconfigs/j/jax/jax-0.2.24-foss-2021a_unimplemented.patch skips the `UNIMPLEMENTED` test that failed in https://github.com/easybuilders/easybuild-easyconfigs/pull/14334#issuecomment-968082356

2021-11-19 23:16 UTC, lexming commented
@branfosj thanks for the patch :+1:

2021-11-20 09:20 UTC, boegel requested changes

2021-11-22 08:43 UTC, lexming commented on easybuild/easyconfigs/j/jax/jax-0.2.24-foss-2021a-CUDA-11.3.1.eb
> +# Author: Denis Kristak
done :)

2021-11-22 08:44 UTC, lexming commented
As discussed in https://github.com/easybuilders/easybuild-easyconfigs/issues/14059#issuecomment-973019771, I'm adding `NVIDIA_TF32_OVERRIDE=0` to the runtest command with CUDA.

2021-11-23 12:35 UTC, lexming commented
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2618
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node308.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/064710ae2169037c70aa51deaa4e335a for a full test report.

2021-11-23 19:02 UTC, lexming commented
Test report by @lexming
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2618
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node253.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, 1 x NVIDIA Tesla P100-PCIE-16GB, 460.73.01, Python 2.7.5
See https://gist.github.com/44c908015dd0cd02a4d404111624393f for a full test report.

2021-12-04 10:41 UTC, branfosj commented
@lexming Your test reports were with https://github.com/easybuilders/easybuild-easyblocks/pull/2618 and not https://github.com/easybuilders/easybuild-easyblocks/pull/2619

2021-12-04 10:46 UTC, branfosj commented
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2619
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/113c992589652462b5a76a9afe85df15 for a full test report.

2021-12-04 12:01 UTC, branfosj commented
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2619
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux RHEL 8.3, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/8cb8186e764e3b25b69efcc2a622150d for a full test report.

2021-12-04 15:05 UTC, branfosj commented
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2619
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0103u01a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 2 x NVIDIA NVIDIA A100-PCIE-40GB, 470.57.02, Python 3.6.8
See https://gist.github.com/c6cde1397b729109612b9c4e626e1f40 for a full test report.

2021-12-04 15:07 UTC, branfosj commented
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2619
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0103u04a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 2 x NVIDIA NVIDIA A30, 470.57.02, Python 3.6.8
See https://gist.github.com/3815bb5669a86f6e1d309be12d4d7762 for a full test report.

2021-12-08 15:07 UTC, branfosj approved these changes
lgtm

2021-12-08 18:48 UTC, branfosj commented
Going in, thanks @lexming!

2021-12-08 18:48 UTC, merged

2021-12-08 21:29 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2619
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3904.accelgor.os - Linux RHEL 8.4, x86_64, AMD EPYC 7413 24-Core Processor (zen2), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 470.82.01, Python 3.6.8
See https://gist.github.com/4c1773c689a1548e71a902d3e04ad533 for a full test report.