{system}[GCCcore/11.2.0] strace v5.14
easybuilders/easybuild-easyconfigs pull request #14381
Opened 2021-11-18 21:09 UTC by SebastianAchilles

(created using `eb --new-pr`)

2021-11-18 21:14 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsfc01.int.jusuf.sebastian.cluster - Linux rocky linux 8.4, x86_64, AMD EPYC 7742 64-Core Processor (zen2), 1 x NVIDIA GRID V100-4C, 460.73.01, Python 3.6.8
See https://gist.github.com/5b1c7e3f817d2ca1b855757b71d1d453 for a full test report.

2021-11-18 21:15 UTC, SebastianAchilles commented
@boegelbot please test @ generoso

2021-11-18 21:28 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
rocky8-eb - Linux rocky linux 8.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.8
See https://gist.github.com/fca504644721d7f6a3a3d4d933d1faa9 for a full test report.

2021-11-22 16:00 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
pg-interactive.hpc.rug.nl - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/59029b056f404f6671bc802c1f1ee38e for a full test report.

2021-11-22 16:43 UTC, bedroge requested changes

2021-11-22 16:43 UTC, bedroge commented on easybuild/easyconfigs/s/strace/strace-5.14-GCCcore-11.2.0.eb
> +}
Could you add a sanity check command here, e.g. `strace --help`?
```suggestion
sanity_check_paths = {
    'files': ['bin/strace-log-merge', 'bin/strace'],
    'dirs': ['share']
}

sanity_check_commands = ['strace --help']
```

2021-11-30 08:12 UTC, bedroge commented on easybuild/easyconfigs/s/strace/strace-5.14-GCCcore-11.2.0.eb
> +}
Committing this, as it's a minor change/improvement.

2021-11-30 08:12 UTC, bedroge commented
@boegelbot please test @ generoso

2021-11-30 08:13 UTC, bedroge commented
Test report by @bedroge
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.8.10
See https://gist.github.com/a4d5d828b8198b2e8160faaf5e7ef09d for a full test report.

2021-11-30 08:14 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
pg-interactive.hpc.rug.nl - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/ffc4b1dc0140464492eb4f5c8f191fda for a full test report.

2021-11-30 08:25 UTC, bedroge commented
@SebastianAchilles I'm getting the following error on an Ubuntu system:

```
checking for m32 personality compile support (using gcc -I/data/apps/software/binutils/2.37-GCCcore-11.2.0/include -I./bundled/linux/arch/x86/include/uapi -I./bundled/linux/include/uapi -Isrc  -m32)... no
checking whether to enable m32 personality support... no
configure: error: Cannot enable m32 personality support
```

https://www.linuxquestions.org/questions/slackware-14/regression-on-current-with-binutils-2-36-a-4175689373/

Adding `--enable-mpers=check` does solve the issue, but I'm not entirely sure what that does / if we need this functionality?

2021-12-19 23:23 UTC, boegel commented
> @SebastianAchilles I'm getting the following error on an Ubuntu system:
> 
> ```
> checking for m32 personality compile support (using gcc -I/data/apps/software/binutils/2.37-GCCcore-11.2.0/include -I./bundled/linux/arch/x86/include/uapi -I./bundled/linux/include/uapi -Isrc  -m32)... no
> checking whether to enable m32 personality support... no
> configure: error: Cannot enable m32 personality support
> ```
> 
> https://www.linuxquestions.org/questions/slackware-14/regression-on-current-with-binutils-2-36-a-4175689373/
> 
> Adding `--enable-mpers=check` does solve the issue, but I'm not entirely sure what that does / if we need this functionality?

That seems like it will conditionally build support for the `mpers` feature when it's possible?

Seems like a reasonable thing to include in the easyconfig...

2023-07-04 19:15 UTC, boegel commented
@SebastianAchilles ping?

2023-07-04 19:28 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2204 - Linux Ubuntu 22.04.2 LTS (Jammy Jellyfish), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.6
See https://gist.github.com/SebastianAchilles/4f3f96b382056556ef72efba398472b9 for a full test report.

2023-07-04 19:36 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
skl-opensuse-155 - Linux openSUSE Leap 15.5, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.15
See https://gist.github.com/SebastianAchilles/d43ff4fb4574339829bd2e7c6bb8b21f for a full test report.

2023-07-04 19:36 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.16
See https://gist.github.com/SebastianAchilles/40fd037ac731352c90c1e8f57e5e855d for a full test report.

2023-07-04 19:36 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-rockylinux-88 - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/1c6924416a74d8cc821b4082083321ec for a full test report.

2023-07-04 19:37 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
skl-centos-79 - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.8
See https://gist.github.com/SebastianAchilles/5377cfd4e993d8d970ddf5af0ec481c9 for a full test report.

2023-07-04 19:37 UTC, SebastianAchilles commented
@boegelbot please test @ jsc-zen2

2023-07-04 20:55 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.6
See https://gist.github.com/bedroge/e1cc8437b5cbc9b4245aa8a4a658ff5e for a full test report.

2023-07-04 20:57 UTC, bedroge commented
@boegelbot please test @ generoso

2023-07-04 20:57 UTC, bedroge approved these changes
lgtm

2023-07-04 21:02 UTC, bedroge commented
Going in, thanks @SebastianAchilles!

2023-07-04 21:02 UTC, merged