{cae,devel,math,system}[GCCcore/10.3.0] OpenModelica v1.18.0, omniORB v4.2.4, Qt5Webkit v5.212.0-alpha4, ... w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #14448
Opened 2021-11-26 16:29 UTC by furstj

(created using `eb --new-pr`)

2021-11-29 06:07 UTC, migueldiascosta requested changes

2021-12-03 02:48 UTC, migueldiascosta commented
@boegelbot please test @ generoso

2022-10-17 14:14 UTC, jfgrimm reviewed
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 14448` and update the PR to use `SYSTEM` instead.

2025-03-31 13:43 UTC, migueldiascosta requested changes

2025-03-31 13:43 UTC, migueldiascosta commented on easybuild/easyconfigs/o/OpenModelica/OpenModelica-1.18.0-foss-2021a.eb
> +supported by a non-profit organization – the Open Source Modelica Consortium (OSMC).
```suggestion
description = """OPENMODELICA is an open-source Modelica-based modeling and simulation
environment intended for industrial and academic usage. Its long-term development is
supported by a non-profit organization – the Open Source Modelica Consortium (OSMC).
```

2025-03-31 14:23 UTC, migueldiascosta requested changes

2025-03-31 14:23 UTC, migueldiascosta commented on easybuild/easyconfigs/q/Qt5Webkit/Qt5Webkit-5.212.0-alpha4-GCCcore-10.3.0.eb
> +configopts = "-G Ninja -DPORT=Qt -DCMAKE_BUILD_TYPE=Release -DUSE_LIBHYPHEN=OFF -DUSE_GSTREAMER=OFF "
```suggestion
build_type = "Release"

configopts = "-G Ninja -DPORT=Qt -DUSE_LIBHYPHEN=OFF -DUSE_GSTREAMER=OFF "
```

2025-03-31 16:32 UTC, migueldiascosta commented on easybuild/easyconfigs/q/Qt5Webkit/Qt5Webkit-5.212.0-alpha4-GCCcore-10.3.0.eb
> +
```suggestion
```

(actually not necessary anymore, it's the default)

2025-03-31 16:52 UTC, migueldiascosta commented
@boegelbot please test @ jsc-zen3

2025-05-09 11:06 UTC, akesandgren commented
Closing this since GCC(core)/10.3.0 foss/2021a is deprecated, see https://docs.easybuild.io/policies/toolchains

Sorry for not getting back to this @furstj 

If this is still relevant, please consider opening a new pull request using a more recent toolchain

2025-05-09 11:06 UTC, closed without merging