{lib}[foss/2021b] xTB v6.4.1
easybuilders/easybuild-easyconfigs pull request #14524
Opened 2021-12-09 18:59 UTC by Micket

(created using `eb --new-pr`)

2021-12-09 19:03 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/9d75cada706356578ac5bbb5068cd899 for a full test report.

2021-12-10 10:27 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/1eeb4e9aa5f666b9c1163a3a413609af for a full test report.

2021-12-10 10:28 UTC, Micket commented
@boegelbot please test @ generoso

2021-12-10 10:31 UTC, branfosj requested changes

2021-12-10 14:50 UTC, Micket commented on easybuild/easyconfigs/x/xTB/xTB-6.4.1-foss-2021b.eb
> +name = 'xTB'
I missed that one. Lets just drop this.

2021-12-10 14:50 UTC, closed without merging