Add patch for hard-coded checksum value of downloaded source file in the source code
easybuilders/easybuild-easyconfigs pull request #14743
Opened 2022-01-17 14:32 UTC by SIB-software

(created using `eb --new-pr`)

2022-01-19 15:30 UTC, boegel requested changes

2022-01-19 15:30 UTC, boegel commented on easybuild/easyconfigs/r/RDKit/RDKit-2021.03.4_fix-comic-neue-checksum.patch
> +--- rdkit-Release_2021_03_4/Code/GraphMol/MolDraw2D/CMakeLists.txt.orig	2022-01-17 13:56:43.780726092 +0100
@SIB-software A short description should be added on top of this patch, to clarify why this is needed
Author or upstream reference for this change should also be mentioned.

Note that this implies changing the SHA256 checksum for this patch file too...

2022-01-19 16:18 UTC, robinengler commented
Thanks @boegel for reviewing this PR.

Would the following description for the patch be OK ? (or is it too long)

```
As part of its installation, RDKit downloads a font package from https://fonts.google.com
and checks its md5sum. It appears the font package was modified and therefore a new md5sum
must be used. The authors of RDKit have updated the md5sum in the source code of RDKit but
no backward fix was made for already existing releases. This patch updates the md5 checksum
to the its new value.
Author: Robin Engler, SIB Swiss Institute for Bioinformatics
--- rdkit-Release_2021_03_4/Code/GraphMol/MolDraw2D/CMakeLists.txt.orig	2022-01-17 13:56:43.780726092 +0100
+++ rdkit-Release_2021_03_4/Code/GraphMol/MolDraw2D/CMakeLists.txt	2022-01-17 13:57:02.668646178 +010
...
```

2022-01-19 17:43 UTC, boegel commented
> Thanks @boegel for reviewing this PR.
> 
> Would the following description for the patch be OK ? (or is it too long)
> 
> ```
> As part of its installation, RDKit downloads a font package from https://fonts.google.com
> and checks its md5sum. It appears the font package was modified and therefore a new md5sum
> must be used. The authors of RDKit have updated the md5sum in the source code of RDKit but
> no backward fix was made for already existing releases. This patch updates the md5 checksum
> to the its new value.
> Author: Robin Engler, SIB Swiss Institute for Bioinformatics
> --- rdkit-Release_2021_03_4/Code/GraphMol/MolDraw2D/CMakeLists.txt.orig	2022-01-17 13:56:43.780726092 +0100
> +++ rdkit-Release_2021_03_4/Code/GraphMol/MolDraw2D/CMakeLists.txt	2022-01-17 13:57:02.668646178 +010
> ...
> ```

@robinengler Looks perfect to me

2022-01-20 07:47 UTC, boegel commented
@boegelbot please test @ generoso

2022-01-21 10:56 UTC, boegel approved these changes
lgtm

2022-01-21 11:23 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2684.swalot.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/0e338d1ac92cc89b09f12c3086f49642 for a full test report.

2022-01-21 11:56 UTC, boegel commented
Going in, thanks @SIB-software!

2022-01-21 11:56 UTC, merged