{tools}[foss/2021b] Arcade-Learning-Environment v0.7.3 w/ Python 3.9.6
easybuilders/easybuild-easyconfigs pull request #14753
Opened 2022-01-18 10:15 UTC by lexming

(created using `eb --new-pr`)

2022-01-18 11:12 UTC, lexming commented
@boegelbot: please test @ generoso

2022-01-18 11:19 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node304.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/ed7eec81f33323f87b40dc50ecbee8d2 for a full test report.

2022-01-19 14:22 UTC, lexming commented
@boegelbot: please test @ generoso

2022-02-06 20:12 UTC, boegel requested changes

2022-02-06 20:12 UTC, boegel commented on easybuild/easyconfigs/a/Arcade-Learning-Environment/Arcade-Learning-Environment-0.7.3-foss-2021b.eb
> +}
@lexming Let's add a sanity check command here too?

```suggestion
}

sanity_check_commands = ["ale-import-roms --help"]
```

2022-02-06 20:13 UTC, boegel commented
@boegelbot please test @ generoso

2022-02-06 20:16 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3112.skitty.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/61eb145bd96c3692e20653a9d1310d09 for a full test report.

2022-02-06 20:18 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3508.doduo.os - Linux UNKNOWN UNKNOWN, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/6e39b73ac8113deb4adefe8396d3770a for a full test report.

2022-02-06 20:21 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2022-02-06 22:07 UTC, lexming commented on easybuild/easyconfigs/a/Arcade-Learning-Environment/Arcade-Learning-Environment-0.7.3-foss-2021b.eb
> +}
good idea, thanks :+1:

2022-02-07 20:22 UTC, boegel approved these changes

2022-02-07 20:22 UTC, boegel commented
Going in, thanks @lexming!

2022-02-07 20:22 UTC, merged