{data,math}[intel/2021b] mkl-service v2.3.0, netcdf4-python v1.5.7, Theano v1.1.2, ... w/ Python 3.9.6
easybuilders/easybuild-easyconfigs pull request #14808
Opened 2022-01-21 09:42 UTC by ItIsI-Orient

(created using `eb --new-pr`)

2022-01-21 09:46 UTC, ItIsI-Orient commented
Test report by @ItIsI-Orient
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in total)
node3202.victini.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/4638ce0737fa9a250c6967ca36eb2d20 for a full test report.

2022-01-21 10:07 UTC, ItIsI-Orient commented
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3202.victini.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/56a26bf43a95b79558e33a755fee7c6f for a full test report.

2022-02-01 12:30 UTC, boegel requested changes

2022-02-01 12:30 UTC, boegel commented on easybuild/easyconfigs/p/PyMC3/PyMC3-3.11.1-intel-2021b.eb
> +    ('typing_extensions', '3.10.0.2', {
Use a proper dependency for this instead? See #14809

2022-02-01 12:30 UTC, boegel commented on easybuild/easyconfigs/p/PyMC3/PyMC3-3.11.1-intel-2021b.eb
> +    ('arviz', '0.11.4', {
Also here, use a proper dependency, see #14810

2022-02-01 12:30 UTC, boegel commented on easybuild/easyconfigs/p/PyMC3/PyMC3-3.11.1-intel-2021b.eb
> +    ('dill', '0.3.4', {
We already have an easyconfig for `dill`, so also use proper dependency here?

2022-02-01 16:34 UTC, boegel approved these changes
lgtm

2022-02-02 07:23 UTC, boegel commented
@boegelbot please test @ generoso

2022-02-02 07:28 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2022-02-02 07:31 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3112.skitty.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/d1dc7ae3eae68d9790ecb3c4fe65b818 for a full test report.

2022-02-02 07:39 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3526.doduo.os - Linux UNKNOWN UNKNOWN, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/209f9d36b7f1f74704beb86663c7e3bf for a full test report.

2022-02-02 20:19 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2022-02-02 20:26 UTC, boegel commented
Going in, thanks @ItIsI-Orient!

2022-02-02 20:26 UTC, merged