{bio}[intel/2021b] Bambi v0.7.1 w/ Python 3.9.6
easybuilders/easybuild-easyconfigs pull request #14811
Opened 2022-01-21 10:12 UTC by ItIsI-Orient

(created using `eb --new-pr`)

2022-01-21 11:13 UTC, ItIsI-Orient commented
Dependencies:

- https://github.com/easybuilders/easybuild-easyconfigs/pull/14810
- https://github.com/easybuilders/easybuild-easyconfigs/pull/14808

2022-01-21 11:16 UTC, ItIsI-Orient commented
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3202.victini.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/7ef47787ecbcf72ed8ddf6c354e34037 for a full test report.

2022-02-01 16:45 UTC, boegel requested changes

2022-02-01 16:45 UTC, boegel commented on easybuild/easyconfigs/b/Bambi/Bambi-0.7.1-intel-2021b.eb
> +    ('formulae', '0.2.0', {
@ItIsI-Orient Hold on, Bambi itself is not actually being installed here?!

2022-02-02 20:29 UTC, boegel commented
@boegelbot please test @ generoso

2022-02-02 20:31 UTC, boegel requested changes

2022-02-02 20:31 UTC, boegel commented on easybuild/easyconfigs/b/Bambi/Bambi-0.7.1-intel-2021b.eb
> +    ('ArviZ', '0.11.4'),
@ItIsI-Orient Looks like a dependency is missing now? Test fails with:

```
bambi 0.7.1 requires pymc3, which is not installed
```

2022-02-03 20:29 UTC, boegel commented
@boegelbot please test @ generoso

2022-02-03 20:39 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2022-02-03 20:40 UTC, boegel approved these changes

2022-02-03 20:40 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3526.doduo.os - Linux UNKNOWN UNKNOWN, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/38d5e74e7f31c01facd33cc438b180bc for a full test report.

2022-02-03 20:51 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2603.swalot.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/1cac7ef94384d5d918ff84f104d357da for a full test report.

2022-02-04 10:04 UTC, boegel commented
Going in, thanks @ItIsI-Orient!

2022-02-04 10:04 UTC, merged