{data}[foss/2021b] scikit-learn v1.0.2 w/ Python 3.9.6
easybuilders/easybuild-easyconfigs pull request #14822
Opened 2022-01-21 16:41 UTC by mustafabar

(created using `eb --new-pr`)

2022-01-21 17:44 UTC, mustafabar commented
Test report by @mustafabar
**SUCCESS**
Build succeeded for 5 out of 5 (1 easyconfigs in total)
alvis-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/2e91ff361e625a4cdae83dd3c938fb8c for a full test report.

2022-02-07 06:51 UTC, migueldiascosta commented
@boegelbot please test @ generoso

2022-02-07 06:51 UTC, migueldiascosta commented
@boegelbot please test @ jsc-zen2

2022-02-07 07:09 UTC, migueldiascosta commented
@boegelbot please test @ generoso

2022-02-07 07:49 UTC, migueldiascosta commented
@mustafabar this can be added, but note that version `1.0.1` is already being used as a dependency in this toolchain version, so merging future easyconfigs that uses version `1.0.2` as a dependency in `2021b` will require an exception to the tests. Do you have a particular use case in mind?

otherwise, it may make more sense to wait for 2022a (?)

2022-02-07 08:29 UTC, mustafabar commented
@migueldiascosta I have no particular use case except that the latest version was requested by one of our users so I thought I will share it here, but I guess it can wait to 2022a

2022-06-09 12:47 UTC, boegel requested changes

2022-06-09 12:47 UTC, boegel commented on easybuild/easyconfigs/s/scikit-learn/scikit-learn-1.0.2-foss-2021b.eb
> +easyblock = 'PythonPackage'
@mustafabar Please change this to a bundle of `scikit-learn` + the `sklearn` metapackage, like we did in #15613

2022-08-10 10:50 UTC, boegel commented
@boegelbot please test @ generoso

2022-08-10 14:32 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3131.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/4e13e674d2494916af21dd1eadebe923 for a full test report.

2022-08-10 19:27 UTC, boegel approved these changes

2022-08-10 19:27 UTC, boegel commented
Going in, thanks @mustafabar!

2022-08-10 19:27 UTC, merged