{tools}[GCC/10.2.0,GCC/10.3.0,GCC/11.2.0] xxd v8.2.4220
easybuilders/easybuild-easyconfigs pull request #14846
Opened 2022-01-26 12:27 UTC by sassy-crick

(created using `eb --new-pr`)

2022-01-26 12:29 UTC, sassy-crick commented
This is related to issue [11209](https://github.com/easybuilders/easybuild-easyconfigs/issues/11209) and needed for `Plumed` installations. This does not install `vim` but only the `xxd` part of `vim`.

2022-01-26 12:51 UTC, zao commented
Test report by @zao
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
eb-u2004 - Linux UNKNOWN UNKNOWN, x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.8.10
See https://gist.github.com/73411af9cb9c47db3cef4af4f78dc355 for a full test report.

2022-01-26 13:05 UTC, zao commented
Test report by @zao
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
eb-u2004 - Linux Ubuntu 20.04, x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.8.10
See https://gist.github.com/2b7ffbbe38bfcfd47e11ea525ff5fa80 for a full test report.

2022-01-26 13:08 UTC, zao commented
You seem to be missing the `binutils` build dependency customary when using GCCcore.

2022-01-26 14:07 UTC, sassy-crick commented
Apologies, that slipped my attention. I have added that now. Thanks for pointing it out!

2022-02-02 00:58 UTC, lexming commented
@boegelbot: please test @ generoso

2022-02-02 01:02 UTC, lexming requested changes

2022-02-02 01:02 UTC, lexming commented on easybuild/easyconfigs/x/xxd/xxd-8.2.4220-GCCcore-10.2.0.eb
> +xxd converts to/from hexdumps of binary files."""
The description is used in the module file, so it should be relevant to the final user. I would remove any mentions to what will be installed
```suggestion
description = "xxd is part of the VIM package and serves to convert to/from hexdumps of binary files."
```

2022-02-02 08:12 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2022-02-02 08:13 UTC, boegel approved these changes
lgtm

2022-02-02 08:14 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3112.skitty.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/927a5e115ea197eeab1cb05b1088dc6c for a full test report.

2022-02-02 09:02 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3526.doduo.os - Linux UNKNOWN UNKNOWN, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/03dd8b8829c7067f342501375f22fddb for a full test report.

2022-02-02 10:32 UTC, boegel commented
Going in, thanks @sassy-crick!

2022-02-02 10:32 UTC, merged