{numlib,phys}[GCC/11.2.0] CLHEP v2.4.4.0, Geant4 v10.7.1
easybuilders/easybuild-easyconfigs pull request #14843
Opened 2022-01-25 16:11 UTC by ItIsI-Orient

(created using `eb --new-pr`)

2022-01-27 10:20 UTC, ItIsI-Orient commented
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3201.victini.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/d2d2df004a270a233b4fbb355f37f008 for a full test report.

2022-01-31 13:43 UTC, boegel requested changes

2022-01-31 13:43 UTC, boegel commented on easybuild/easyconfigs/g/Geant4/Geant4-10.7.1-GCC-11.2.0.eb
> +    # recommended CLHEP version, see https://geant4-data.web.cern.ch/geant4-data/ReleaseNotes/ReleaseNotes4.10.6.html
fix URL, should be https://geant4-data.web.cern.ch/geant4-data/ReleaseNotes/ReleaseNotes4.10.7.html

2022-01-31 13:43 UTC, boegel commented
This may need some more work, to avoid using C++23 standard for GATE in #14869

2022-02-07 08:14 UTC, boegel approved these changes
lgtm

2022-02-07 08:14 UTC, boegel commented
@boegelbot please test @ generoso

2022-02-07 09:02 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
node2677.swalot.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/766873e6c7dc0b4c886138609b0e65ee for a full test report.

2022-02-07 10:25 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2022-02-07 10:47 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3523.doduo.os - Linux UNKNOWN UNKNOWN, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/31018dcd805d710a60cacc6facd78b47 for a full test report.

2022-02-07 15:44 UTC, boegel commented
Going in, thanks @ItIsI-Orient!

2022-02-07 15:44 UTC, merged