{cae}[foss/2021b] GATE v9.1
easybuilders/easybuild-easyconfigs pull request #14869
Opened 2022-01-28 16:46 UTC by ItIsI-Orient

(created using `eb --new-pr`)

2022-01-28 16:56 UTC, ItIsI-Orient commented
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3202.victini.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/5d650af27fd407bec099c59bd9dfb950 for a full test report.

2022-01-31 12:01 UTC, ItIsI-Orient commented
Merge first: https://github.com/easybuilders/easybuild-easyconfigs/pull/14843

2022-01-31 13:43 UTC, boegel requested changes

2022-01-31 13:43 UTC, boegel commented on easybuild/easyconfigs/g/GATE/GATE-9.1-foss-2021b.eb
> +toolchainopts = {'cstd': 'c++23'}
We should avoid using C++23, since it's still experimental, see https://gcc.gnu.org/projects/cxx-status.html#cxx23

Can we stick to C++17?

2022-02-07 10:27 UTC, boegel commented
@boegelbot please test @ generoso
CORE_CNT=16

2022-02-07 10:35 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2677.swalot.os - Linux UNKNOWN UNKNOWN, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/df46ba2d22c690a2654f33800ca1b5da for a full test report.

2022-02-07 11:55 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3523.doduo.os - Linux UNKNOWN UNKNOWN, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/02a944e37dcc637f51802d4a6d21b2f1 for a full test report.

2022-02-08 10:23 UTC, boegel commented
@boegelbot please test @ jsc-zen2
CORE_CNT=8

2022-02-08 19:22 UTC, boegel approved these changes

2022-02-08 19:28 UTC, boegel commented
Going in, thanks @ItIsI-Orient!

2022-02-08 19:28 UTC, merged