{data}[gompi/2021b] HDF5 v1.10.8
easybuilders/easybuild-easyconfigs pull request #14894
Opened 2022-02-01 20:58 UTC by sassy-crick

(created using `eb --new-pr`)

2022-02-01 22:55 UTC, lexming commented
This version of HDF5 disabled some binaries due to CVEs. It will need an update of the `hdf5` easyblock.

2022-02-01 23:07 UTC, sassy-crick commented
@lexming I guess these are the ones I tipped over when I tried to install it. Are you going to update the `hdf5` easyblock?

2022-02-01 23:11 UTC, lexming commented
@sassy-crick yes, I already had an update for the easyblock (I was dealing with this same installation yesterday :smile: ). Waiting for a failed test to hit this PR...

2022-02-01 23:16 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node301.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/0ba7229ad61968c025ffc75bca2204f5 for a full test report.

2022-02-01 23:30 UTC, sassy-crick commented
If you want to do the EC as well as it might be easier, I am happy to close this one. :-)
Up to you.

2022-02-01 23:41 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node301.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/c17a4147a3a8319d02ae805b2449ac1a for a full test report.

2022-02-01 23:46 UTC, lexming requested changes

2022-02-01 23:46 UTC, lexming commented on easybuild/easyconfigs/h/HDF5/HDF5-1.10.8-gompi-2021b.eb
> +configopts = "--enable-hltools"  # needed to build HL-tools: gif2h5 gif2h5 and h5watch
The vulnerable tools should be left disabled by default
```suggestion
# needed to build HL-tools: gif2h5 gif2h5 and h5watch
# beware that gif tools are affected by multiple CVEs: CVE-2018-17433, CVE-2018-17436, CVE-2020-10809
# configopts = "--enable-hltools" 

```

2022-02-01 23:53 UTC, lexming commented
@sassy-crick No need to close this PR, it justs need a minor change

2022-02-02 00:06 UTC, sassy-crick commented
That looks good to me. I cannot test the file as I don't have the updated EasyBlock. Let me know how it goes.

2022-02-02 00:16 UTC, lexming commented
@sassy-crick you can test the `hdf5` easyblock from the PR with `eb --include-easyblocks-from-pr=2670`

2022-02-02 00:17 UTC, lexming commented
please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=2670"

2022-02-02 00:32 UTC, lexming commented
@boegelbot: please test @ generoso
EB_ARGS="--include-easyblocks-from-pr=2670"

2022-02-02 11:05 UTC, sassy-crick commented
> @sassy-crick you can test the `hdf5` easyblock from the PR with `eb --include-easyblocks-from-pr=2670`
I know but I did not know the number of the EasyBlock PR. :-)

2022-02-02 23:39 UTC, lexming approved these changes
LGTM

2022-02-02 23:40 UTC, lexming commented
Going in, thanks @sassy-crick !

2022-02-02 23:40 UTC, merged