{lib}[foss/2021a] TensorFlow v2.4.4 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #14970
Opened 2022-02-10 14:34 UTC by lexming

(created using `eb --new-pr`)

2022-02-11 00:06 UTC, lexming commented
@boegelbot please test @ generoso
CORE_CNT=16

2022-02-11 06:19 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/7a46fb316bdbc34cfe44c8a006901c0c for a full test report.

2022-02-12 11:45 UTC, branfosj requested changes
Based on a comparison with `TensorFlow-2.4.1-foss-2020b.eb`.

2022-02-14 15:02 UTC, lexming commented on easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.4-foss-2021a.eb
> +    }),
fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/14970/commits/ef56865131792fcac3688827424140fc78d3017e, thanks

2022-02-14 15:02 UTC, lexming commented on easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.4.4-foss-2021a.eb
> +    ('h5py', '2.10.0', {
fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/14970/commits/ef56865131792fcac3688827424140fc78d3017e, thanks

2022-02-14 15:03 UTC, lexming commented
@boegelbot please test @ generoso
CORE_CNT=16

2022-02-14 18:45 UTC, branfosj commented
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bber0501u03a.bb2.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/004415140ac8c568dfc7e0e1823af228 for a full test report.

2022-02-14 18:48 UTC, branfosj approved these changes
lgtm

2022-02-14 19:42 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 12 out of 12 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/513e4ed57c720a9a6a38638a0f9285ec for a full test report.

2022-02-14 19:46 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/6b43f38bce7594d82f5b3996ce3ccf69 for a full test report.

2022-02-14 19:47 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bber0501u03a.bb2.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/1c35cd552659c26446629b0932ca3540 for a full test report.

2022-02-14 19:48 UTC, branfosj commented
Going in, thanks @lexming!

2022-02-14 19:48 UTC, merged

2022-02-14 20:03 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node316.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/92f3a290696d82515d81f055e69e7f65 for a full test report.