devito: update description
easybuilders/easybuild-easyconfigs pull request #15009
Opened 2022-02-17 10:50 UTC by georgebisbas

Update Devito's description.

2022-02-18 14:07 UTC, boegel requested changes

2022-02-18 14:07 UTC, boegel commented on easybuild/easyconfigs/d/Devito/Devito-4.6.1-foss-2020a-Python-3.8.2.eb
> +description = "Devito is a domain-specific Language (DSL) and code generation framework for performing optimised Finite Difference (FD) computation from high-level symbolic problem definitions. Devit
@georgebisbas This should be made multi-line (using `"""`), or it's going to trip our code style check (max line length in easyconfigs is 120 characters).

```suggestion
description = """Devito is a domain-specific Language (DSL) and code generation framework for
 performing optimised Finite Difference (FD) computation from high-level symbolic problem definitions.
 Devito performs automated code generation and Just-In-time (JIT) compilation based on symbolic
 equations defined in SymPy to create and execute highly optimised Finite Difference stencil kernels on
 multiple computer platforms."""

2022-02-18 15:57 UTC, boegel commented
@boegelbot please test @ generoso

2022-02-19 08:46 UTC, branfosj approved these changes
lgtm

2022-02-19 08:48 UTC, branfosj commented
Going in, thanks @georgebisbas!

2022-02-19 08:48 UTC, merged