{tools}[foss/2021a,foss/2021b] fastparquet v0.7.2, fastparquet v0.8.0 w/ Python 3.9.5 + 3.9.6
easybuilders/easybuild-easyconfigs pull request #15020
Opened 2022-02-22 14:27 UTC by lexming

(created using `eb --new-pr`)

2022-02-22 21:08 UTC, lexming commented
@boegelbot: please test @ generoso

2022-02-22 22:10 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node315.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/b45a7becd00925a82224205f16479840 for a full test report.

2022-02-25 11:21 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
node148.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/754c093fae989a0240dfd1df77148268 for a full test report.

2022-04-24 22:53 UTC, verdurin requested changes

2022-04-24 22:53 UTC, verdurin commented on easybuild/easyconfigs/f/fastparquet/fastparquet-0.7.2-foss-2021a.eb
> +description = """fastparquet is a python implementation of the parquet format, aiming integrate
```suggestion
description = """fastparquet is a python implementation of the parquet format, aiming to integrate
```

2022-04-24 22:53 UTC, verdurin commented on easybuild/easyconfigs/f/fastparquet/fastparquet-0.8.0-foss-2021b.eb
> +description = """fastparquet is a python implementation of the parquet format, aiming integrate
```suggestion
description = """fastparquet is a python implementation of the parquet format, aiming to integrate
```

2022-04-24 22:57 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/8b358d7a2f47d2be332f4b3225b2abf8 for a full test report.

2022-07-26 10:57 UTC, lexming commented
@boegelbot: please test @ generoso

2022-07-26 11:32 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/36219c1c09738abe0efe7dfed37c6b71 for a full test report.

2022-07-26 11:33 UTC, verdurin approved these changes
Looks fine.

2022-07-26 11:33 UTC, verdurin commented
Going in, thanks @lexming!

2022-07-26 11:33 UTC, merged