{bio}[foss/2021b] SCGid v0.9b0
easybuilders/easybuild-easyconfigs pull request #15065
Opened 2022-02-28 16:42 UTC by ItIsI-Orient

(created using `eb --new-pr`)

2022-03-08 18:36 UTC, casparvl commented
Thanks for your contribution @ItIsI-Orient ! It seems that your patch file did not include any description, which is why the CI failed. Can you please include a description at the top of your patch file to indicate what the issue was that was fixed? If there is a github issue or PR on it in the SCGid repo, it's worth putting a link to those in the description too. That way, it's also easier to check for future versions of this EasyConfig if the patch is still relevant or not. As an example, you can have a look at [this patch](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/PyTorch/PyTorch-1.10.0_fix-alias-violation-in-bitwise-ops.patch)

2022-03-08 19:44 UTC, ItIsI-Orient commented
@casparvl Hi, yes, I know about this issue and that is already fixed in my current working version. I will push a fix into this PR probably tomorrow, but I will still have to wait until my framework PR gets reviewed and approved, since one of the dependencies needed (Databionics ESOM) has to be installed and provided by user and therefore cannot be found by easybuild.

2022-03-09 18:38 UTC, casparvl commented
Ah, sorry, I overlooked the part that this depends on another PR. I know the maintainer who's keeping an eye on `easybuild-framework` has not found a lot of time to work on PRs this week, so I guess we just have to be patient :)

2022-03-15 16:51 UTC, boegel requested changes

2022-03-15 16:51 UTC, boegel commented on easybuild/easyconfigs/s/SCGid/SCGid-0.9b0-foss-2021b.eb
> +    'export PATH=$PATH:$EBROOTBLAST',
These should be removed, they don't actually do anything w.r.t. the installation

2022-03-15 16:51 UTC, boegel commented on easybuild/easyconfigs/s/SCGid/SCGid-0.9b0-foss-2021b.eb
> +local_config_path = "%(installdir)s/lib/python3.9/site-packages/config.yaml"
please use `/python%(pyshortver)s/`

or just remove, `local_config_path` is not used anymore

2022-03-15 16:51 UTC, boegel commented on easybuild/easyconfigs/s/SCGid/SCGid-0.9b0-foss-2021b.eb
> +local_config_prep = "%%(installdir)s/SCGid-%s/config.yaml" % local_commit
this can be removed too

2022-03-15 16:51 UTC, boegel commented on easybuild/easyconfigs/s/SCGid/SCGid-0.9b0-foss-2021b.eb
> +builddependencies = [('Python', '3.9.6')]
`Python` should be a runtime dependency?

2022-03-15 16:51 UTC, boegel commented on easybuild/easyconfigs/s/SCGid/SCGid-0.9b0-foss-2021b.eb
> +        'source_tmpl': 'e326c34307803b9ea8ffc975ddd9bd05643af931.tar.gz',
This should be renamed on download, try this:

```python
'sources': [{
    'download_filename': 'e326c34307803b9ea8ffc975ddd9bd05643af931.tar.gz',
    'filename': 'ClaMS-CLI-%(version)s.tar.gz',
}],

2022-03-15 16:51 UTC, boegel commented on easybuild/easyconfigs/s/SCGid/SCGid-0.9b0-initEdit.patch
> ++        self.initial_config["esom_path"] = os.getenv("EBROOTSCGID")
provide a fallback value to avoid hard crash:

```python
os.getenv("EBROOTSCGID", "SCGID_INSTALL_DIR_UNKNOWN")

2022-03-31 14:09 UTC, ItIsI-Orient commented on easybuild/easyconfigs/s/SCGid/SCGid-0.9b0-foss-2021b.eb
> +        'source_tmpl': 'esom.tar.gz',
@boegel Oh, we want user to name the Tarball `esom-1.1.tar.gz`? Okay, will do

2022-04-21 10:33 UTC, boegel requested changes

2022-04-21 10:33 UTC, boegel commented on easybuild/easyconfigs/s/SCGid/SCGid-0.9b0-foss-2021b.eb
> +         You need to manually provide Databionics ESOM. Please, follow these steps:
@ItIsI-Orient Final request for change: I would tweak these instructions a bit, to make them clearer (less room for interpretation).

Done in https://github.com/ItIsI-Orient/easybuild-easyconfigs/pull/1

2022-04-21 16:20 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node2615.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/4211e1a890e25308ec28d59768c245a6 for a full test report.

2022-04-26 16:37 UTC, boegel commented
@boegelbot please test @ generoso

2022-04-26 17:25 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3519.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/faea80ddbabebeb6774cb4441180d2e7 for a full test report.

2022-04-27 06:35 UTC, boegel approved these changes

2022-04-27 06:36 UTC, boegel commented
Going in, thanks @ItIsI-Orient!

2022-04-27 06:36 UTC, merged