{compiler}[GCC/11.2.0] hipSYCL v0.9.2 w/ Python 3.9.6
easybuilders/easybuild-easyconfigs pull request #15074
Opened 2022-03-03 11:24 UTC by nordmoen

(created using `eb --new-pr`)

2022-03-03 11:30 UTC, nordmoen commented
Tested with the following Clang distribution:

```python
##
# This file is an EasyBuild reciPY as per https://github.com/easybuilders/easybuild
#
# Copyright:: Copyright 2013-2015 Dmitri Gribenko, Ward Poelmans
# Authors:: Dmitri Gribenko <gribozavr@gmail.com>
# Authors:: Ward Poelmans <wpoely86@gmail.com>
# License:: GPLv2 or later, MIT, three-clause BSD.
# $Id$
##

name = 'Clang'
version = '13.0.1'
versionsuffix = '-CUDA-%(cudaver)s'

homepage = 'https://clang.llvm.org/'
description = """C, C++, Objective-C compiler, based on LLVM.  Does not
 include C++ standard library -- use libstdc++ from GCC."""

# Clang also depends on libstdc++ during runtime, but this dependency is
# already specified as the toolchain.
toolchain = {'name': 'GCCcore', 'version': '11.2.0'}

source_urls = ["https://github.com/llvm/llvm-project/releases/download/llvmorg-%(version)s"]
sources = [
    'llvm-%(version)s.src.tar.xz',
    'clang-%(version)s.src.tar.xz',
    'compiler-rt-%(version)s.src.tar.xz',
    'polly-%(version)s.src.tar.xz',
    'openmp-%(version)s.src.tar.xz',
    # Also include the LLVM linker
    'lld-%(version)s.src.tar.xz',
    'libcxx-%(version)s.src.tar.xz',
    'libcxxabi-%(version)s.src.tar.xz',
    'clang-tools-extra-%(version)s.src.tar.xz',
    'libunwind-%(version)s.src.tar.xz',
]
checksums = [
    'ec6b80d82c384acad2dc192903a6cf2cdbaffb889b84bfb98da9d71e630fc834',  # llvm-13.0.1.src.tar.xz
    '787a9e2d99f5c8720aa1773e4be009461cd30d3bd40fdd24591e473467c917c9',  # clang-13.0.1.src.tar.xz
    '7b33955031f9a9c5d63077dedb0f99d77e4e7c996266952c1cec55626dca5dfc',  # compiler-rt-13.0.1.src.tar.xz
    'f4003e03da57b53bf206faadd0cf53f7b198c38498c605dec45743db23c10ad0',  # polly-13.0.1.src.tar.xz
    '6b79261371616c31fea18cd3ee1797c79ee38bcaf8417676d4fa366a24c96b4f',  # openmp-13.0.1.src.tar.xz
    '666af745e8bf7b680533b4d18b7a31dc7cab575b1e6e4d261922bbafd9644cfb',  # lld-13.0.1.src.tar.xz
    '2f446acc00bb7cfb4e866c2fa46d1b6dbf4e7d2ab62e3c3d84e56f7b9e28110f',  # libcxx-13.0.1.src.tar.xz
    'db5fa6093c786051e8b1c85527240924eceb6c95eeff0a2bbc57be8422b3cef1',  # libcxxabi-13.0.1.src.tar.xz
    'cc2bc8598848513fa2257a270083e986fd61048347eccf1d801926ea709392d0',  # clang-tools-extra-13.0.1.src.tar.xz
    'e206dbf1bbe058a113bffe189386ded99a160b2443ee1e2cd41ff810f78551ba',  # libunwind-13.0.1.src.tar.xz
]

dependencies = [
    # since Clang is a compiler, binutils is a runtime dependency too
    ('binutils', '2.37'),
    ('hwloc', '2.5.0'),
    ('libxml2', '2.9.10'),
    ('ncurses', '6.2'),
    ('CUDA', '11.4.1', '', True),
    ('GMP', '6.2.1'),
    ('Z3', '4.8.12'),
]

builddependencies = [
    ('CMake', '3.21.1'),
    ('Python', '3.9.6'),
    ('Perl', '5.34.0'),
    ('elfutils', '0.185'),
]

assertions = False
usepolly = True
build_lld = True
libcxx = True
enable_rtti = True
build_extra_clang_tools = True

skip_all_tests = True

moduleclass = 'compiler'
```

Note especially that we need to turn off `assertions` since hipSYCL has a tendency to touch the edges of LLVM which can erroneously signal errors.

2022-03-07 13:29 UTC, casparvl commented
@boegelbot please test @generoso

2022-03-07 18:46 UTC, casparvl commented
I had to search a bit for the actual error in the gist of boegelbot's build, but I see: 
```
== 2022-03-07 18:20:26,525 easyblock.py:4061 WARNING build failed (first 300 chars): Sanity check failed: no file found at 'lib/libomptarget-nvptx.a' in /project/boegelbot/Rocky8/haswell/software/Clang/13.0.1-GCCcore-11.2.0-CUDA-11.4.1
```
This comes from the EasyBlock sanity check ([here](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/c/clang.py#L507)). While I'm no expert, if it got put in the sanity check, I assume it's supposed to be there somewhere. @nordmoen any idea why that archive is not present at the expected location? I assume the build completed succesfully for you, do you have that archive in your installation directory?

2022-03-08 07:25 UTC, nordmoen commented
My bad @casparvl I forgot to mention that I have been using easybuilders/easybuild-easyblocks#2684 as it seems that Clang 13 no longer produces the `lib/libomptarget-nvptx.a` library.

2022-03-08 16:58 UTC, casparvl commented
Test report by @casparvl
**FAILED**
Build succeeded for 1 out of 3 (2 easyconfigs in total)
software1.lisa.surfsara.nl - Linux debian 10.11, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 2.7.16
See https://gist.github.com/7c11f6968f2bb8bc7075df496a4d3eb0 for a full test report.

2022-03-08 17:40 UTC, casparvl commented
Test report by @casparvl
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2684
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
software1.lisa.surfsara.nl - Linux debian 10.11, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 2.7.16
See https://gist.github.com/98dd0c5fa38174f5d451db1ffed78ce2 for a full test report.

2022-03-08 18:59 UTC, casparvl commented
Hm, the test failure on my system is because `sys/cdefs.h` is not in the `/usr/include` folder, but more deeply nested since it's multi-arch:

```
file /usr/include/x86_64-linux-gnu/sys/cdefs.h
/usr/include/x86_64-linux-gnu/sys/cdefs.h: C source, ASCII text
```

I'm not sure if something can/should be done about this at the EasyConfig level. I haven't run into this before with other EasyConfigs as far as I know. Then again, I also never installed CLANG before.

I'm also not sure which compilers is being used when this error is thrown: if it's CLANG itself (e.g. it's doing e.g. a bootstrap), then maybe the default include path should be changed (in which case it _could_ be something that belongs in an EasyBlock). My GCC at least _claims_ it looks in the correct include directory:
```
casparl@software1:~$ module load GCCcore/11.2.0
casparl@software1:~$ gcc -xc -E -v -
Using built-in specs.
COLLECT_GCC=gcc
OFFLOAD_TARGET_NAMES=nvptx-none
Target: x86_64-pc-linux-gnu
Configured with: ../configure --enable-languages=c,c++,fortran --without-cuda-driver --enable-offload-targets=nvptx-none --enable-lto --enable-checking=release --disable-multilib --enable-shared=yes --enable-static=yes --enable-threads=posix --enable-plugins --enable-gold=default --enable-ld --with-plugin-ld=ld.gold --prefix=/home/casparl/.local/easybuild/Debian10/2021/software/GCCcore/11.2.0 --with-local-prefix=/home/casparl/.local/easybuild/Debian10/2021/software/GCCcore/11.2.0 --enable-bootstrap --with-isl=/scratch/casparl/GCCcore/11.2.0/system-system/gcc-11.2.0/stage2_stuff --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.0 (GCC)
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
 /home/casparl/.local/easybuild/Debian10/2021/software/GCCcore/11.2.0/libexec/gcc/x86_64-pc-linux-gnu/11.2.0/cc1 -E -quiet -v -imultiarch x86_64-linux-gnu - -mtune=generic -march=x86-64 -dumpbase -
ignoring nonexistent directory "/home/casparl/.local/easybuild/Debian10/2021/software/GCCcore/11.2.0/include/x86_64-linux-gnu"
ignoring nonexistent directory "/home/casparl/.local/easybuild/Debian10/2021/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include-fixed"
ignoring nonexistent directory "/home/casparl/.local/easybuild/Debian10/2021/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/casparl/.local/easybuild/Debian10/2021/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include
 /home/casparl/.local/easybuild/Debian10/2021/software/GCCcore/11.2.0/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
```

2022-03-09 06:28 UTC, nordmoen commented
@casparvl I have never seen that error before on the systems I have tested on, so I'm afraid I can't help much there.

At least boegelbot managed to build it properly.

2022-03-16 06:45 UTC, akesandgren requested changes

2022-03-16 06:45 UTC, akesandgren commented on easybuild/easyconfigs/c/Clang/Clang-13.0.1-GCCcore-11.2.0-CUDA-11.4.1.eb
> +    ('elfutils', '0.185'),
Needs pkg-config

2022-03-16 06:53 UTC, nordmoen commented on easybuild/easyconfigs/c/Clang/Clang-13.0.1-GCCcore-11.2.0-CUDA-11.4.1.eb
> +    ('elfutils', '0.185'),
Added inn `pkg-config` now

2022-03-16 07:11 UTC, akesandgren commented
There is a patch we should add to this too. The CMAKE_VERBOSE_MAKEFILE setting isn't propagated to the sub projects it builds. Testing it now.

2022-03-17 07:42 UTC, akesandgren commented
The problem with not finding sys/cdefs.h smells like a bug in clang.
A simple
```
#include <sys/cdefs.h>
```
fails with the offending clang (1st stage) when doing
```
.../Clang/13.0.1/GCCcore-11.2.0-CUDA-11.4.1/llvm.obj.1/bin/clang -E /tmp/t.c -o /tmp/t.o -target nvptx64
```
but works if I remove the "-target nvptx64". So something goes wrong there that worked before.

I've been trying to look at the Debian patches for Clang 13 but haven't found anything yet.

2022-03-17 15:03 UTC, akesandgren commented
Actually, our Clang/11.0.1 also presents the same error in the above case and so does Clang/10.0.0
I.e. this is not something new, it just happens to hit the bootstrap step with 13.0.1 which it didn't do previously.

2022-03-29 08:20 UTC, nordmoen commented
@akesandgren Any progress on this? It seemed like the issue has always been present and maybe should not block this inclusion?

2022-03-30 17:15 UTC, akesandgren commented
The problem is described here: https://groups.google.com/g/llvm-dev/c/71cdlaU-fG8

Adding gcc-multilib (from the OS) to my build container fixes the problem.
I would argue that this is a bug in Clang, that it should not need the things gcc-multilib pulls in to correctly setup the associatedtoolchains so it will find the multiarch include paths when using -target nvptx
I know where it goes wrong, but not where the original problem is.

2022-03-30 20:03 UTC, akesandgren commented
Test report by @akesandgren
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2684
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/cc9322d4ba05895cd0e233e336195ebb for a full test report.

2022-03-31 14:45 UTC, akesandgren commented
The reason it works by adding gcc-multilib is that (for my test with sys/cdefs.h) is that libc6-dev-i386 adds a softlink for /usr/include/sys/cdefs.h -> ../x86_64-linux-gnu/sys/cdefs.h

So the "bug" in Clang remains that it doesn't properly detect that the host is multiarch.

2022-10-17 14:14 UTC, jfgrimm reviewed
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 15074` and update the PR to use `SYSTEM` instead.

2025-06-16 11:26 UTC, boegel commented
Closing this since `GCCcore/11.2.0` is no longer supported, see https://docs.easybuild.io/policies/toolchains, and no activity in this PR for quite a while.

@nordmoen If this is still relevant, please consider opening a new pull request using a more recent toolchain

2025-06-16 11:26 UTC, closed without merging