{chem}[GCC/11.2.0] dftd3-lib v0.10
easybuilders/easybuild-easyconfigs pull request #15091
Opened 2022-03-08 14:43 UTC by mustafabar

(created using `eb --new-pr`)

2022-03-08 14:44 UTC, mustafabar commented
Test report by @mustafabar
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/2e728e9bcca6fe59f776317c0ea81b17 for a full test report.

2022-03-08 14:48 UTC, mustafabar commented
Test report by @mustafabar
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/e02c889a3196462828a3333180ae8426 for a full test report.

2022-03-08 14:50 UTC, mustafabar commented
Test report by @mustafabar
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/9652ee7c9e9c5298714747de628b7ffe for a full test report.

2022-03-08 14:57 UTC, mustafabar commented
Test report by @mustafabar
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/aee717f617fa4b0c18a7df1f1696f30f for a full test report.

2022-03-08 18:00 UTC, casparvl commented
The reason the build is failing is that EasyBuild cannot determine at what level (i.e. which depth in the directory structure) the patch should be applied

```
= 2022-03-08 15:58:49,203 easyblock.py:4032 WARNING build failed (first 300 chars): Can't determine patch level for patch /local/EB/build/eb-daqlbpjv/files_pr15091/d/dftd3-lib/dftd3-lib-0.10_fix-extras-syntax.patch from directory /local/EB/build/dftd3lib/0.10/GCC-11.2.0/dftd3-lib-0.10
```
Looking at the patch, I see these lines
```
--- extras.f90.orig	2022-03-08 15:29:22.336522856 +0100
+++ extras.f90	        2022-03-08 15:30:50.750421061 +0100
```
I expect to see something more like
```
--- a/aten/src/ATen/cpu/vec/vec_base.h
+++ b/aten/src/ATen/cpu/vec/vec_base.h
```
I.e. with the full subdirectory structure (relative to the top-level of the extracted sources).

I typically create patches using `diff -Nru source.orig source/ > patch_file.patch` (an example from [here](https://github.com/eth-cscs/production/wiki/Creating-and-applying-patches-with-EasyBuild)). Maybe you used different flags?

2022-03-09 09:24 UTC, mustafabar commented
Test report by @mustafabar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux centos linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/6ee6f4112d72eabcbbccd18788a60a61 for a full test report.

2022-03-09 16:17 UTC, casparvl commented
@boegelbot please test @ generoso

2022-03-09 16:25 UTC, casparvl requested changes

2022-03-09 16:25 UTC, casparvl commented on easybuild/easyconfigs/d/dftd3-lib/dftd3-lib-0.10_fix-extras-syntax.patch
> +diff -Nru dftd3-lib-0.10.orig/prg/extras.f90 dftd3-lib-0.10/prg/extras.f90
Sorry, should have asked straight away, but: can you include some comment in the patch about which issue it solves? (e.g. without this patch, you get error XYZ). If there is an official issue or PR on the upstream github of dftd3-lib, it's also good to reference that here. That way, we can easily check when creating newer versions of this EasyConfigs if the patch is still relevant/needed, or if a solution has already been implemented upstream

2022-03-09 16:25 UTC, casparvl commented on easybuild/easyconfigs/d/dftd3-lib/dftd3-lib-0.10-GCC-11.2.0.eb
> +
Is there a sensible `sanity_check_command` that you could define? E.g. something like `<main_executable> --version` or `--help` is useful to check if the binary at least starts. That also ensures things like all shared libraries being found by the runtime linker.

2022-03-09 16:26 UTC, casparvl commented on easybuild/easyconfigs/d/dftd3-lib/dftd3-lib-0.10_fix-extras-syntax.patch
> +diff -Nru dftd3-lib-0.10.orig/prg/extras.f90 dftd3-lib-0.10/prg/extras.f90
E.g. see https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/PyTorch/PyTorch-1.10.0_fix-alias-violation-in-bitwise-ops.patch

2022-03-23 06:49 UTC, akesandgren commented
@mustafabar compare with #14252

2025-06-16 14:20 UTC, boegel commented
Closing this since `GCC/11.2.0` is deprecated or no longer supported, see https://docs.easybuild.io/policies/toolchains

Sorry for not getting back to this @mustafabar 

If this is still relevant, please consider opening a new pull request using a more recent toolchain

2025-06-16 14:20 UTC, closed without merging