{math}[GCCcore/10.2.0] MATLAB-Engine v2020b w/ Python 2.7.18 + 3.8.6
easybuilders/easybuild-easyconfigs pull request #15145
Opened 2022-03-18 17:46 UTC by SimonPinches

(created using `eb --new-pr`)

2022-04-01 18:35 UTC, Micket requested changes

2022-04-01 18:35 UTC, Micket commented on easybuild/easyconfigs/m/MATLAB-Engine/MATLAB-Engine-2020b-GCCcore-10.2.0-Java-11.eb
> +multi_deps = {'Python': ['3.8.6', '2.7.18']}
I'd say lets drop the python2 dep.

2022-10-17 14:14 UTC, jfgrimm reviewed
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 15145` and update the PR to use `SYSTEM` instead.

2022-11-16 23:14 UTC, lexming commented
Thanks  @SimonPinches. I'll close this PR since we already have a newer easyconfigs for MATLAB-Engine in this toolchain (#16118).

2022-11-16 23:14 UTC, closed without merging