{chem}[intel/2021a] Environ v2.0.3
easybuilders/easybuild-easyconfigs pull request #15188
Opened 2022-03-25 13:09 UTC by mustafabar

(created using `eb --new-pr`)

2022-03-25 13:20 UTC, mustafabar commented
Test report by @mustafabar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/461746307c7bd70a721583dcb63d2ed5 for a full test report.

2022-03-25 13:28 UTC, akesandgren commented
Does this result in building QE too? If so please note that the normal QE build uses a special easyblock for building.
QE is somewhat compllicated to build correctly.

2022-03-25 14:02 UTC, mustafabar commented
> Does this result in building QE too? If so please note that the normal QE build uses a special easyblock for building. QE is somewhat compllicated to build correctly.
@akesandgren yes it rebuilds some packages of QE (only those that use the extension). My approach is to use an independent module for Environ to avoid impacting the QE binaries as this is what Environ does to enable the extension, which is quite risky if we are to apply it in existing QE installation. 
The quantumespresso easyblock is not needed in this case, as the install script made by Environ does all that is needed for the purpose of using the extension. 
The full installation of QE with all "proper" extensions can still be obtained through the designated easyblock.

2022-03-25 14:24 UTC, mustafabar commented
Test report by @mustafabar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/6dc580dd8c71f52ad3b94cf30818106a for a full test report.

2022-03-29 09:49 UTC, smoors requested changes

2022-03-29 09:49 UTC, smoors commented on easybuild/easyconfigs/e/Environ/Environ-2.0.3-intel-2021a-qe-7.0.eb
> +# The Environ installation script requires that you select the QE package to extend
```suggestion
# The Environ installation script requires that you select the QE extension package(s)
```

2022-03-29 09:49 UTC, smoors commented on easybuild/easyconfigs/e/Environ/Environ-2.0.3-intel-2021a-qe-7.0.eb
> +
```suggestion
```

2022-04-01 08:54 UTC, mustafabar commented on easybuild/easyconfigs/e/Environ/environ_mpiifort_omp_compiler_error.patch
> +diff -Nru qe-7.0.orig/Environ/FFTs/fft_parallel.f90 qe-7.0/Environ/FFTs/fft_parallel.f90
Thanks. Done!

2022-04-01 08:54 UTC, mustafabar commented
Test report by @mustafabar
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/fee2eb5b0137b2584298eb61347a8d28 for a full test report.

2022-04-01 09:00 UTC, mustafabar commented
Test report by @mustafabar
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/229c5b7f909980869fa5993769e19db2 for a full test report.

2022-04-01 09:06 UTC, mustafabar commented
Test report by @mustafabar
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/458cb99a4de3d2893b0b3b0544dc75f8 for a full test report.

2022-04-01 09:20 UTC, mustafabar commented
Test report by @mustafabar
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/56f2ee8b51192607f4b89fa0ef16edb7 for a full test report.

2022-04-01 09:21 UTC, mustafabar commented on easybuild/easyconfigs/e/Environ/Environ-2.0.3-intel-2021a-qe-7.0.eb
> +}
@smoors The suggested file names have many errors. I took your suggestion but fixed the filenames

2025-05-09 10:54 UTC, akesandgren commented
Closing this since intel/2021a is deprecated, see https://docs.easybuild.io/policies/toolchains

Sorry for not getting back to this @mustafabar 

If this is still relevant, please consider opening a new pull request using a more recent toolchain

2025-05-09 10:54 UTC, closed without merging