{math}[intel/2020b] EigenExa v2.11
easybuilders/easybuild-easyconfigs pull request #15234
Opened 2022-04-04 01:20 UTC by Dankomaister

(created using `eb --new-pr`)

2022-04-04 11:11 UTC, jfgrimm requested changes

2022-04-04 11:11 UTC, jfgrimm commented on easybuild/easyconfigs/e/EigenExa/EigenExa-2.11-intel-2020b.eb
> +    'files': ['lib/libEigenExa.a'],
worth adding a check for the shared library as well
```suggestion
    'files': ['lib/libEigenExa.%s' % x for x in ['a', SHLIB_EXT]],
```

2022-04-05 08:51 UTC, Dankomaister commented on easybuild/easyconfigs/e/EigenExa/EigenExa-2.11-intel-2020b.eb
> +preconfigopts = './cleanup && ./bootstrap && '
great! thanks for the suggestion

2022-04-05 08:56 UTC, Dankomaister reviewed
Accept suggested changes

2022-04-06 10:09 UTC, jfgrimm commented
> Accept suggested changes

Can you update the PR with the changes? You can either use `eb --update-pr 15234 <files-to-update>` or push to the `20220404101947_new_pr_EigenExa211` branch in your fork of easybuild-easyconfigs

2022-04-06 10:09 UTC, jfgrimm commented
> Accept suggested changes

Can you update the PR with the changes? You can either use `eb --update-pr 15234 <files-to-update>` or push to the `20220404101947_new_pr_EigenExa211` branch in your fork of easybuild-easyconfigs

2022-04-06 13:52 UTC, Dankomaister commented
Okay, I will figure out how to do this.
I'm still a GitHub noob so this is somewhat confusing haha
-sorry

2022-04-16 06:11 UTC, Dankomaister commented
done!

2022-04-18 10:17 UTC, jfgrimm commented
@boegelbot: please test @ generoso

2022-04-18 10:52 UTC, jfgrimm approved these changes

2022-04-18 10:52 UTC, jfgrimm commented
Going in, thanks @Dankomaister!

2022-04-18 10:52 UTC, merged