{perf}[gompi/2021a] supermagic v20220308
easybuilders/easybuild-easyconfigs pull request #15246
Opened 2022-04-04 14:31 UTC by robert-mijakovic

(created using `eb --new-pr`)

2022-04-08 12:38 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node116.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/15b671283446dca445ebc8ed91aba5f4 for a full test report.

2022-04-08 12:59 UTC, jfgrimm requested changes

2022-04-08 12:59 UTC, jfgrimm commented on easybuild/easyconfigs/s/supermagic/supermagic-20220308-gompi-2021a.eb
> +##
please keep the previous attribution as well, e.g.:
```suggestion
# #
# This is a contribution from HPCNow! (http://hpcnow.com)
# Copyright::   HPCNow!
# Authors::     Jordi Blasco <jordi.blasco@hpcnow.com>
#                    Robert Mijakovic <robert.mijakovic@lxp.lu>
# License::     GPL-v3.0
# #
```

2022-04-08 12:59 UTC, jfgrimm commented on easybuild/easyconfigs/s/supermagic/supermagic-20220308-gompi-2021a.eb
> +
```suggestion
```

2022-04-08 12:59 UTC, jfgrimm commented on easybuild/easyconfigs/s/supermagic/supermagic-20220308-gompi-2021a.eb
> +
maybe add a simple sanity check command?
```suggestion

sanity_check_commands = ["OMPI_MCA_rmaps_base_oversubscribe=1 mpiexec -n 4 supermagic -t hello_world"]

```

2022-04-19 10:33 UTC, verdurin commented
@robert-mijakovic any update on the requested changes?

2025-05-09 10:55 UTC, akesandgren commented
Closing this since foss/2021a is deprecated, see https://docs.easybuild.io/policies/toolchains

Sorry for not getting back to this @robert-mijakovic 

If this is still relevant, please consider opening a new pull request using a more recent toolchain

2025-05-09 10:55 UTC, closed without merging