update cget
easybuilders/easybuild-easyconfigs pull request #15263
Opened 2022-04-08 19:57 UTC by fizwit

(created using `eb --new-pr`)

2022-04-12 13:19 UTC, jfgrimm requested changes
Since `exts_list` now consists of only the `cget` package, I've made some suggestions that switch to `PythonPackage` instead of `PythonBundle`.
I would also drop the toolchain to `GCCcore` (the filename should be updated to match)

2022-04-12 13:19 UTC, jfgrimm commented on easybuild/easyconfigs/c/cget/cget-0.2.0-foss-2020b.eb
> +easyblock = 'PythonBundle'
```suggestion
easyblock = 'PythonPackage'
```

2022-04-12 13:19 UTC, jfgrimm commented on easybuild/easyconfigs/c/cget/cget-0.2.0-foss-2020b.eb
> +toolchain = {'name': 'foss', 'version': '2020b'}
I don't think this really needs to be at `foss` level, we can probably drop this to `GCCcore`
```suggestion
toolchain = {'name': 'GCCcore', 'version': '10.2.0'}
```

2022-04-12 13:19 UTC, jfgrimm commented on easybuild/easyconfigs/c/cget/cget-0.2.0-foss-2020b.eb
> +
```suggestion

sources = [SOURCE_TAR_GZ]

```

2022-04-12 13:19 UTC, jfgrimm commented on easybuild/easyconfigs/c/cget/cget-0.2.0-foss-2020b.eb
> +]
```suggestion
download_dep_fail = True
]
```

2022-04-13 04:07 UTC, fizwit commented
PR 13277 is open for cget-0.1.9 for GCCcore 10.2.0 . Changed my PR to GCCcore 11.2 and version 0.2.0.  Looks like the tests were failing due to no santiy_check_paths.

2022-04-13 09:35 UTC, jfgrimm commented on easybuild/easyconfigs/c/cget/cget-0.2.0-GCCcore-11.2.0.eb
> +
this should make the test suite happier
```suggestion

builddependencies = [('binutils', '2.35')]

```

2022-09-14 18:04 UTC, closed without merging