{data}[foss/2020b] NCL v6.6.2
easybuilders/easybuild-easyconfigs pull request #15327
Opened 2022-04-23 15:16 UTC by kosl

(created using `eb --new-pr`)

2022-05-03 10:54 UTC, kosl commented
Bump

2022-05-03 12:55 UTC, migueldiascosta requested changes

2022-05-03 12:55 UTC, migueldiascosta commented on easybuild/easyconfigs/g/g2clib/g2clib-1.6.3-foss-2020b.eb
> +toolchain = {'name': 'foss', 'version': '2020b'}
```suggestion
toolchain = {'name': 'GCCcore', 'version': '10.2.0'}
```

and change the filename

2022-05-03 12:55 UTC, migueldiascosta commented on easybuild/easyconfigs/g/g2lib/g2lib-3.2.0-GCCcore-10.2.0.eb
> +    # '%(name)s-%(version)s_makefile.patch',
why is this no longer needed? (compared to `g2lib-3.2.0-GCCcore-10.3.0.eb`)

2022-05-03 12:55 UTC, migueldiascosta commented on easybuild/easyconfigs/g/g2lib/g2lib-3.2.0_compilation.patch
> +diff -Nru g2lib-3.2.0-orig/addfield.f g2lib-3.2.0/addfield.f
please add description of patch and author here

2022-05-03 12:55 UTC, migueldiascosta commented on easybuild/easyconfigs/g/g2lib/g2lib-3.2.0_compilation.patch
> ++++ g2lib-3.2.0/getfield.f~	2021-03-18 19:20:40.734837860 +0100
this was a mistake, no? it's adding an editor temporary file

2022-05-03 12:55 UTC, migueldiascosta commented on easybuild/easyconfigs/g/g2lib/g2lib-3.2.0_compilation.patch
> ++++ g2lib-3.2.0/gf_unpack7.f~	2020-12-16 18:58:40.000000000 +0100
same here

2022-05-03 12:55 UTC, migueldiascosta commented on easybuild/easyconfigs/g/g2lib/g2lib-3.2.0_compilation.patch
> ++++ g2lib-3.2.0/specunpack.f~	2020-12-16 18:58:41.000000000 +0100
same here

2022-05-03 12:55 UTC, migueldiascosta commented on easybuild/easyconfigs/n/NCL/NCL-6.6.2-foss-2020b.eb
> +    # ('GDAL', '3.9.1'),
why is `GDAL` commented?

2022-05-03 12:55 UTC, migueldiascosta commented on easybuild/easyconfigs/n/NCL/NCL-6.6.2-foss-2020b.eb
> +    # ('pixman', '0.40.0'),
`pixman` is a dependency of `cairo`, so wouldn't be needed here in any case - delete commented line?

2022-08-04 22:12 UTC, lexming commented
@kosl Thanks for your contribution. The easyconfig for NCL/6.6.2-foss-2020b has already been merged in #15820. So I'll close this PR.

2022-08-04 22:12 UTC, closed without merging