{tools}[GCCcore/11.3.0] bzip2 v1.0.8, cURL v7.83.0, libarchive v3.6.1, ...
easybuilders/easybuild-easyconfigs pull request #15386
Opened 2022-04-29 13:46 UTC by jfgrimm

(created using `eb --new-pr`)

2022-04-29 14:11 UTC, jfgrimm commented
@boegelbot: please test @ generoso

2022-04-29 14:29 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/8161e9f6f7642069d24ebdf9069fa1f5 for a full test report.

2022-04-29 14:31 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/a490047e2c54a0badef8df993d7b5f30 for a full test report.

2022-04-29 14:33 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bear-pg0306u11a.bear.cluster - Linux RHEL 8.5, POWER, 8335-GTX (power9le), 4 x NVIDIA Tesla V100-SXM2-16GB, 470.57.02, Python 3.6.8
See https://gist.github.com/1f6ff49734d419de5525df6ba1b126da for a full test report.

2022-04-29 14:43 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node127.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/c589eb0633484606b84d6386591948c0 for a full test report.

2022-04-29 15:06 UTC, bartoldeman requested changes
I noticed that pkgconf was also added recently.
Do we still need pkg-config, or should we replace with pkgconf unless we run into some compatibility issue?

2022-04-30 08:44 UTC, boegel requested changes

2022-04-30 08:44 UTC, boegel commented on easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.2-GCCcore-11.3.0.eb
> +name = 'pkg-config'
@jfgrimm Since we intend to use `pkgconf` rather than `pkg-config`, we should not add an easyconfig file for `pkg-config` with `GCCcore/11.3.0`?

2022-04-30 08:49 UTC, boegel commented on easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.2-GCCcore-11.3.0.eb
> +name = 'pkg-config'
I've removed the `pkg-config` easyconfig file with `GCCcore/11.3.0` in 3db546c so we can move this forward...

2022-04-30 09:03 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0001 - Linux Rocky Linux 8.5, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/e8296a3e6a28f1d3154bbae26dd1919f for a full test report.

2022-04-30 09:17 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node2725.swalot.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/04d688f3c6c296ee30a207017e5957b9 for a full test report.

2022-04-30 10:37 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3101.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/1af88d56e146d42acd880bf1d2ebf718 for a full test report.

2022-04-30 11:51 UTC, boegel approved these changes

2022-04-30 11:51 UTC, boegel commented
Going in, thanks @jfgrimm!

2022-04-30 11:51 UTC, merged