{tools}[system/system] gcloud v382.0.0
easybuilders/easybuild-easyconfigs pull request #15443
Opened 2022-05-05 13:09 UTC by ItIsI-Orient

(created using `eb --new-pr`)

2022-05-11 12:50 UTC, ItIsI-Orient commented
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3702.slaking.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/91996187deb291af6a83be873a7b6c58 for a full test report.

2022-05-12 14:15 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/520e9dc946237d452fb73e0730ee6757 for a full test report.

2022-05-12 14:16 UTC, verdurin requested changes

2022-05-12 14:16 UTC, verdurin commented on easybuild/easyconfigs/g/gcloud/gcloud-382.0.0.eb
> +
@ItIsI-Orient is there a `sanity_check_command` you can add here?

2022-05-12 14:17 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
centos7.lan - Linux CentOS Linux 7.9.2009, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/6074569a1d8cc0f0fe90bcea9fc58132 for a full test report.

2022-05-16 14:36 UTC, boegel commented
@boegelbot please test @ generoso

2022-05-16 21:21 UTC, boegel approved these changes
lgtm

2022-05-23 14:18 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3513.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/fde535ef685b6c20b41b2cdb2263ce8a for a full test report.

2022-05-23 15:05 UTC, boegel commented
Going in, thanks @ItIsI-Orient!

2022-05-23 15:05 UTC, merged