{tools}[foss/2021a] num2words v0.5.10 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #15473
Opened 2022-05-09 14:16 UTC by ItIsI-Orient

(created using `eb --new-pr`)

2022-05-11 12:55 UTC, ItIsI-Orient commented
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3702.slaking.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/f47bc99c65913dd3f855e598366c738d for a full test report.

2022-05-16 21:21 UTC, boegel requested changes

2022-05-16 21:21 UTC, boegel commented on easybuild/easyconfigs/n/num2words/num2words-0.5.10-foss-2021a.eb
> +    ('docopt', '0.6.2', {
`docopt` 0.6.2 is already included with `Python` 3.9.5, so there's no need to install it again?

That also implies that just using `PythonPackage` as easyblock makes more sense

2022-05-23 15:33 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2022-05-23 15:35 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3103.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/e8b31e91f0abc20803aa327f440ea90e for a full test report.

2022-05-23 17:17 UTC, boegel commented
@boegelbot please test @ generoso

2022-05-23 17:19 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3103.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/a86063a30272ff0e65e07538390543fe for a full test report.

2022-05-23 17:37 UTC, boegel approved these changes

2022-05-23 17:38 UTC, boegel commented
Going in, thanks @ItIsI-Orient!

2022-05-23 17:38 UTC, merged