{lib}[foss/2021a] PyTorch-Ignite v0.4.9 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #15491
Opened 2022-05-12 10:23 UTC by smoors

(created using `eb --new-pr`)

2022-05-12 13:42 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node134.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/29fb18c71fcbfe875c8d8b4225bff045 for a full test report.

2022-05-12 13:46 UTC, jfgrimm requested changes

2022-05-12 13:46 UTC, jfgrimm commented on easybuild/easyconfigs/p/PyTorch-Ignite/PyTorch-Ignite-0.4.9-foss-2021a-CUDA-11.3.1.eb
> +    ('pytorch-lightning', version, {
surely this should be
```suggestion
    ('pytorch-ignite', version, {
```

2022-05-13 00:34 UTC, smoors commented
Test report by @smoors
**FAILED**
Build succeeded for 0 out of 2 (1 easyconfigs in total)
node401.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7282 16-Core Processor (zen2), 1 x NVIDIA NVIDIA A100-PCIE-40GB, 470.82.01, Python 2.7.5
See https://gist.github.com/a8f08d65ef3a5b7ea69b7a7dff674865 for a full test report.

2022-05-13 07:54 UTC, smoors commented on easybuild/easyconfigs/p/PyTorch-Ignite/PyTorch-Ignite-0.4.9-foss-2021a-CUDA-11.3.1.eb
> +    ('pytorch-lightning', version, {
whoops :)

2022-05-16 11:01 UTC, jfgrimm submitted a review, later dismissed
probably worth switching to `PythonPackage` since it's currently only a single extension?

2022-05-16 11:09 UTC, smoors commented
> probably worth switching to `PythonPackage` since it's currently only a single extension?

actually, I prefer to always use `PythonBundle` as it's easier to add extensions later on (which is bound to happen at some point).
do you know if there's any advantage of using `PythonPackage` besides "consistency"?

2022-10-17 14:15 UTC, jfgrimm reviewed
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 15491` and update the PR to use `SYSTEM` instead.

2023-01-31 18:31 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0103u14a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 1 x NVIDIA NVIDIA A30, 520.61.05, Python 3.6.8
See https://gist.github.com/f5f9813fcb842a1c032865fa2c780a09 for a full test report.

2023-01-31 18:34 UTC, branfosj approved these changes

2023-01-31 18:35 UTC, merged