Google Cloud Utils
easybuilders/easybuild-easyconfigs pull request #15507
Opened 2022-05-17 00:40 UTC by fizwit

(created using `eb --new-pr`)

2022-05-18 01:43 UTC, fizwit commented
Do I need to add Binutils to a PythonBundle?

2022-05-20 15:48 UTC, casparvl commented
@fizwit If any part of the installation would invoke a linker, I'd say so... I e.g. also see it in https://github.com/easybuilders/easybuild-easyconfigs/blob/ff86c0de0a38fbd4b238cb205b07ef3608e83f20/easybuild/easyconfigs/p/plotly.py/plotly.py-5.4.0-GCCcore-11.2.0.eb and https://github.com/easybuilders/easybuild-easyconfigs/blob/7e3a302311e9f54c1c0c4811bcf38e25e777e007/easybuild/easyconfigs/o/openpyxl/openpyxl-3.0.7-GCCcore-10.3.0.eb (I searched for PythonBundle and checked for EasyConfigs based on `GCCcore`)

2022-05-22 08:21 UTC, casparvl requested changes

2022-05-22 08:21 UTC, casparvl commented on easybuild/easyconfigs/g/gsutil/gsutil-5.10-GCCcore-11.2.0.eb
> +    ('buildutils', '2.37'),
You made a typo and wrote `buildutils`  instead of `binutils`. That's where the CI failure comes from.

2022-05-22 08:31 UTC, casparvl commented on easybuild/easyconfigs/g/gsutil/gsutil-5.10-GCCcore-11.2.0.eb
> +    ('buildutils', '2.37'),
Ok, fixed it myself

2022-05-22 08:34 UTC, casparvl commented
@boegelbot please test @ generoso

2022-05-22 08:40 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/15816c91d55e1b05c17d4e81ee5c536c for a full test report.

2022-05-22 08:41 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
software1.lisa.surfsara.nl - Linux debian 10.12, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 2.7.16
See https://gist.github.com/c1a6f69b342575b7a6b361e745ff6e82 for a full test report.

2022-05-22 08:42 UTC, casparvl approved these changes
LGTM!

2022-05-22 08:43 UTC, casparvl commented
Going in, thanks @fizwit!

2022-05-22 08:43 UTC, merged