{lang}[GCCcore/10.3.0] Rust v1.60.0
easybuilders/easybuild-easyconfigs pull request #15586
Opened 2022-06-01 18:54 UTC by boegel

(created using `eb --new-pr`)

2022-06-01 18:57 UTC, boegel commented
@boegelbot please test @ generoso

2022-06-01 20:36 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
himem06.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/94253ea7df502343c75ef984ab987d31 for a full test report.

2022-06-01 20:39 UTC, jfgrimm commented
@boegel I don't think that patch is necessary anymore

2022-06-01 20:48 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3162.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/31507c61e37603c2a847ee577a76955f for a full test report.

2022-06-02 11:13 UTC, jfgrimm requested changes
I don't think the patch is required in 1.60 anymore

2022-06-02 17:58 UTC, boegel commented
> @boegel I don't think that patch is necessary anymore

@jfgrimm The patch is only relevant when EasyBuild is configured with `--sysroot`, which is used in case you're building software on top of an alternate sysroot (i.e. not `/`).

Are you sure it's not needed anymore in that case?
See https://github.com/EESSI/software-layer/issues/157 for more details.

I can give it a try without the patch when using `--sysroot` to double check, but the patch shouldn't hurt when `--sysroot` is not used.

2022-06-02 18:02 UTC, jfgrimm commented
> > @boegel I don't think that patch is necessary anymore
> 
> @jfgrimm The patch is only relevant when EasyBuild is configured with `--sysroot`, which is used in case you're building software on top of an alternate sysroot (i.e. not `/`).
> 
> Are you sure it's not needed anymore in that case?
> See https://github.com/EESSI/software-layer/issues/157 for more details.
> 
> I can give it a try without the patch when using `--sysroot` to double check, but the patch shouldn't hurt when `--sysroot` is not used.

I'm fairly sure I looked at this for the 2022a gen, but I could be wrong.

2022-06-02 19:50 UTC, boegel commented
@jfgrimm Quick test in the EESSI environment confirms my suspicion: trying to install this easyconfig without the patch file fails in ~2min with:

```
error: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/kehoste/Rust/1.60.0/GCCcore-10.3.0/rustc-1.60.0-src/build/bootstrap/debug/deps/libserde_derive-bd5ac08fcae6016e.so)
```

With the patch file, it installs without trouble. I'll upload the test report from that environment (which includes use of `--sysroot` in the EasyBuild configuration).

2022-06-02 19:51 UTC, jfgrimm commented
Gah

2022-06-02 19:56 UTC, jfgrimm approved these changes

2022-06-02 21:01 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
cnx1 - Linux Rocky Linux 8.5 (Green Obsidian), x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.9.9
See https://gist.github.com/72e50cd1c11260341f6ac59ca7f38dcf for a full test report.

2022-06-03 07:18 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/961a480bf3794a244bd4eda4321629f8 for a full test report.

2022-06-03 07:24 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/6e56edfe4d59d6e11605907c61130440 for a full test report.

2022-06-03 07:24 UTC, branfosj commented
Going in, thanks @boegel!

2022-06-03 07:24 UTC, merged

2022-06-03 07:25 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/fc5d46ca9554392740697bebf4658d14 for a full test report.