{bio}[GCC/10.3.0] Sambamba v0.8.0
easybuilders/easybuild-easyconfigs pull request #15591
Opened 2022-06-02 08:43 UTC by pberthier

(created using `eb --new-pr`)

2022-06-02 10:37 UTC, branfosj requested changes

2022-06-02 10:37 UTC, branfosj commented on easybuild/easyconfigs/s/Sambamba/Sambamba-0.8.0-GCC-10.3.0.eb
> +version = '0.8.0'
`'commit': 'f898046'` corresponds to `version = '0.8.2'`. This should be updated and the filename changed to `Sambamba-0.8.2-GCC-10.3.0.eb`

2022-06-02 10:37 UTC, branfosj commented on easybuild/easyconfigs/s/Sambamba/Sambamba-0.8.0-GCC-10.3.0.eb
> +    ('Python', '3.9.5'),
In `0.8.2`, they [no longer bundle `lz4` sources](https://github.com/biod/sambamba/releases/tag/v0.8.2), so `('lz4', '1.9.3'),` is needs to be added here.

2022-06-03 07:23 UTC, pberthier commented
Many thamks for the review.  As I've got the wrong file in the commit, I'll close this request and redo it with the correct file.

2022-06-03 07:23 UTC, closed without merging