{lib}[foss/2021a] Faiss v1.7.2 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #15608
Opened 2022-06-03 13:09 UTC by boegel

(created using `eb --new-pr`)

2022-06-03 13:10 UTC, boegel commented
@boegelbot please test @ generoso

2022-06-03 13:19 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3162.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/e0662c5e06a10a3450a35d7edc43f65b for a full test report.

2022-06-03 13:20 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3506.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/592e0c4d3bcd7a336e1f41e68dac247d for a full test report.

2022-06-03 20:23 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2022-06-05 18:02 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/e472fadc762ff5532c94587f132827fd for a full test report.

2022-06-05 20:14 UTC, Micket requested changes
Looks like this has ctest and it's enabled by default, so lets run it

2022-06-05 20:14 UTC, Micket commented on easybuild/easyconfigs/f/Faiss/Faiss-1.7.2-foss-2021a.eb
> +
```suggestion
runtests = "test"
```

2025-05-09 10:57 UTC, akesandgren commented
Closing this since foss/2021a is deprecated, see https://docs.easybuild.io/policies/toolchains

Sorry for not getting back to this @boegel 

If this is still relevant, please consider opening a new pull request using a more recent toolchain

2025-05-09 10:57 UTC, closed without merging