{system}[system/system] OpenSSL v3.0
easybuilders/easybuild-easyconfigs pull request #15659
Opened 2022-06-10 10:17 UTC by SebastianAchilles

(created using `eb --new-pr`)

Depends on
- [ ] https://github.com/easybuilders/easybuild-easyblocks/pull/2746

2022-06-10 10:21 UTC, SebastianAchilles commented
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2746
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
broadwell-alma9-eb - Linux AlmaLinux 9.0 (Emerald Puma), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 510.73.08, Python 3.9.10
See https://gist.github.com/6d6ff413baf2377faa2fa9f2f1f4f7d8 for a full test report.

2022-06-11 21:16 UTC, SebastianAchilles commented
Test report by @sebastianachilles
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2746
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-centosstream9.novalocal - Linux CentOS Stream 9, x86_64, Intel Xeon Processor (Skylake, IBRS) (skylake_avx512), Python 3.9.10
See https://gist.github.com/1df097501babf31de687bafde5791d57 for a full test report.

2022-06-13 14:23 UTC, jfgrimm commented
Test report by @jfgrimm
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2746
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
node080.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/aba24e87c922dcb6bcf26d1baa99a9a1 for a full test report.

2022-06-13 14:25 UTC, jfgrimm commented
@SebastianAchilles I'm seeing: `Can't locate IPC/Cmd.pm in @INC`

2022-06-13 14:40 UTC, SebastianAchilles commented
> @SebastianAchilles I'm seeing: `Can't locate IPC/Cmd.pm in @INC`

Yes, in the container I have installed ` perl-IPC-Cmd` and `perl-Pod-Html` to build OpenSSL v3.0:

https://github.com/easybuilders/easybuild-containers/blob/main/almalinux-9.0/Dockerfile#L22-L23

Either we could add this as `osdependencies` or we could build a `Perl-minimal` in the `system` toolchain. Which solution do you think would be better?

2022-06-16 12:57 UTC, jfgrimm commented
> > @SebastianAchilles I'm seeing: `Can't locate IPC/Cmd.pm in @INC`
> 
> Yes, in the container I have installed ` perl-IPC-Cmd` and `perl-Pod-Html` to build OpenSSL v3.0:
> 
> https://github.com/easybuilders/easybuild-containers/blob/main/almalinux-9.0/Dockerfile#L22-L23
> 
> Either we could add this as `osdependencies` or we could build a `Perl-minimal` in the `system` toolchain. Which solution do you think would be better?

I'd probably go for the latter?

2022-06-20 14:19 UTC, boegel commented
Yeah, Perl should be fairly robust to build in multiple OS configurations, I would expect.

But we should test it extensively first, so please open a separate PR for a minimal `Perl` with `system` (and mention in what context we plan to use it).

2022-06-20 14:22 UTC, boegel commented
Worth taking into account in this context: https://github.com/easybuilders/easybuild-easyconfigs/issues/8973

2023-09-30 14:31 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.16
See https://gist.github.com/SebastianAchilles/6063954e39c1ffe631d8c9ff146518c1 for a full test report.

2024-01-17 16:51 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
jsczen3g1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, AMD EPYC-Milan Processor (zen3), 1 x NVIDIA NVIDIA A100 80GB PCIe, 545.23.08, Python 3.9.18
See https://gist.github.com/SebastianAchilles/703342ec323df0806e88660145514363 for a full test report.

2024-01-17 17:05 UTC, Micket requested changes
I saw there were forward looking packages in RHEL8
openssl3.x86_64
openssl3-libs.x86_64
openssl3-devel.x86_64


I'll try it out to see that it actually finds and wraps those

2024-01-17 17:05 UTC, Micket commented on easybuild/easyconfigs/o/OpenSSL/OpenSSL-3.0.eb
> +version = '3.0'
I think we should just have `3` here as they will start following semver going foward.

2024-01-17 17:05 UTC, Micket commented on easybuild/easyconfigs/o/OpenSSL/OpenSSL-3.0.eb
> +    (name, '3.0.11', {
and maybe we want to use 3.2.x here?

2024-03-06 19:57 UTC, boegel commented
Closing this, since we're favoring `OpenSSL/3` (cfr. #19623), since OpenSSL 3.x promises a stable ABI (couldn't find a good reference for that though)

2024-03-06 19:57 UTC, closed without merging