DeepCell 0.11.1
easybuilders/easybuild-easyconfigs pull request #15704
Opened 2022-06-16 18:02 UTC by fizwit

(created using `eb --new-pr`)
requires PR #15551

2022-06-23 14:20 UTC, fizwit commented
Dependency is in dev branch
EasyBuildError: 'Missing dependencies: TensorFlow/2.7.1-foss-2021b-CUDA-11.4.1 
--from-pr #14990 

Spektral --from-pr #15551 (open PR) held up by TensorFlow

2022-07-12 22:26 UTC, fizwit commented
deps are merged

2022-08-25 21:59 UTC, fizwit commented
waiting for dev merge of  spektral-1.1.0-foss-2021b-CUDA-11.4.1.eb pr #15551

2023-04-25 09:31 UTC, verdurin requested changes

2023-04-25 09:31 UTC, verdurin commented on easybuild/easyconfigs/d/DeepCell/DeepCell-0.11.1-foss-2021b-CUDA-11.4.1.eb
> +        'patches': ['DeepCell_Toolbox-0.11.2_deps.patch'],
@fizwit please include a comment explaining the need for the patch, either here or in the patch itself

2023-05-30 14:27 UTC, verdurin commented
@boegelbot please test @ generoso

2023-05-30 15:12 UTC, verdurin commented
@fizwit I think we're ready to go, if you can add some comments to the patches, as noted above.

2023-05-30 20:23 UTC, fizwit commented
@verdurin comments added, checksums updated

2023-06-01 15:59 UTC, verdurin commented
@boegelbot please test @ generoso

2023-06-01 16:00 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/0babdcc7e423b91dbeb3ad62cb2335b8 for a full test report.

2023-06-01 16:03 UTC, verdurin commented
@boegelbot please test @ jsc-zen2

2025-06-16 15:18 UTC, boegel commented
@boegelbot please test @ jsc-zen3-a100
CORE_CNT=16

2025-06-16 15:26 UTC, boegel commented
I gave this a chance, but since it doesn't work at first attempt, I'll go ahead and close this...

Closing this since `foss/2021b` is deprecated or no longer supported, see https://docs.easybuild.io/policies/toolchains

Sorry for not getting back to this @fizwit 

If this is still relevant, please consider opening a new pull request using a more recent toolchain

2025-06-16 15:26 UTC, closed without merging