{math}[foss/2020b,intel/2020b] SUNDIALS v6.2.0
easybuilders/easybuild-easyconfigs pull request #15714
Opened 2022-06-20 17:53 UTC by boegel

(created using `eb --new-pr`)

2022-06-20 18:40 UTC, boegel commented
@boegelbot please test @ generoso

2022-06-20 18:48 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3594.doduo.os - Linux RHEL 8.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/e2ff3ca3fc876a3491d6a9aa5a2cbafa for a full test report.

2022-06-20 18:48 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3117.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/00f8bc836f2e973606a8866b78e6a419 for a full test report.

2023-06-23 19:51 UTC, branfosj requested changes

2023-06-23 19:51 UTC, branfosj commented on easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-6.2.0-intel-2020b.eb
> +
```suggestion
```

2023-06-23 19:51 UTC, branfosj commented on easybuild/easyconfigs/s/SUNDIALS/SUNDIALS-6.2.0-foss-2020b.eb
> +
```suggestion
```

2023-06-23 20:11 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (2 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/4305606e10e790c8070fe050d5a5224d for a full test report.

2023-06-23 20:11 UTC, branfosj approved these changes

2023-06-23 20:13 UTC, branfosj commented
Going in, thanks @boegel!

2023-06-23 20:13 UTC, merged