{tools}[GCC/11.2.0] Minipolish v0.1.3 w/ Python 3.9.6
easybuilders/easybuild-easyconfigs pull request #15713
Opened 2022-06-20 15:39 UTC by ItIsI-Orient

(created using `eb --new-pr`)

2022-06-20 22:01 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/03f66900415e518e72196dbbde4ce22b for a full test report.

2022-06-20 22:02 UTC, verdurin commented
@boegelbot please test @ generoso

2022-06-20 22:12 UTC, verdurin requested changes

2022-06-20 22:12 UTC, verdurin commented on easybuild/easyconfigs/m/Minipolish/Minipolish-0.1.3-GCC-11.2.0.eb
> +moduleclass = "tools"
```suggestion
moduleclass = "bio"
```

2022-06-21 15:29 UTC, verdurin commented on easybuild/easyconfigs/m/Minipolish/Minipolish-0.1.3-GCC-11.2.0.eb
> +moduleclass = "tools"
Thanks.

2022-06-21 15:31 UTC, verdurin approved these changes
Looks fine.

2022-06-21 15:31 UTC, merged

2022-06-21 16:02 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3104.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/c96a6830558a458b371bb0e7bcbef689 for a full test report.