{data}[system/system] Oracle v12.1.0.2.0
easybuilders/easybuild-easyconfigs pull request #15732
Opened 2022-06-21 12:59 UTC by DirectorSloan

(created using `eb --new-pr`)

2022-06-23 22:27 UTC, verdurin commented
@DirectorSloan please take a look at the style complaints from the bot.

2023-06-22 15:29 UTC, boegel requested changes

2023-06-22 15:29 UTC, boegel commented on easybuild/easyconfigs/o/Oracle/Oracle-12.1.0.2.0.eb
> +name = "Oracle"
This software name feels very generic...

2023-06-22 15:29 UTC, boegel commented on easybuild/easyconfigs/o/Oracle/Oracle-12.1.0.2.0.eb
> +sources = [
if sources can't be downloaded automatically, should provide `download_instructions`

2023-06-22 15:29 UTC, boegel commented on easybuild/easyconfigs/o/Oracle/Oracle-12.1.0.2.0.eb
> +install_cmd = "mv %(installdir)s/instantclient_12_1/* %(installdir)s/ && "
Can we avoid hardcoding the major/minor version by using templates?

2023-06-22 15:29 UTC, boegel commented on easybuild/easyconfigs/o/Oracle/Oracle-12.1.0.2.0.eb
> +    'dirs': ['bin', 'lib', 'include'],
should be a bit more specific?

2025-06-16 15:17 UTC, boegel commented
No activity in a long time, so closing as is.

@DirectorSloan If this is still relevant, please consider opening a new pull request using a more recent version

2025-06-16 15:17 UTC, closed without merging