{lang}[foss/2022a] R v4.2.1
easybuilders/easybuild-easyconfigs pull request #15767
Opened 2022-06-24 18:37 UTC by branfosj

(created using `eb --new-pr`)

2022-06-24 19:34 UTC, branfosj commented
@boegelbot please test @ jsc-zen2

2022-06-24 20:19 UTC, branfosj commented
Test report by @branfosj
**FAILED**
Build succeeded for 18 out of 21 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/c23177e43e931bad8f412dd413404e88 for a full test report.

2022-06-25 14:31 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/5f7455d161aecfa68584aab3db6d5aad for a full test report.

2022-06-26 01:46 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bdw-opensuse-154 - Linux openSUSE Leap 15.4 Alpha, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.15
See https://gist.github.com/96e5c52a8b476a2d1c0b205044366dc2 for a full test report.

2022-06-26 20:29 UTC, SebastianAchilles commented
@boegelbot please test @ generoso

2022-06-28 07:49 UTC, boegel submitted a review, later dismissed
lgtm (test report coming up)

2022-07-01 12:14 UTC, verdurin commented
It's maybe worth mentioning here that it appears there's a problem with `Seurat` in that it and/or some of the projects that build on it need `HDF5` `<=1.8.x`. I know it's in `Bioconductor`, but obviously that builds on what's here.

This is the upstream bug report that was mentioned to us:

https://github.com/mojaveazure/seurat-disk/issues/30

Happy to open it as an issue - just wanted to mention here too.

2022-07-05 13:17 UTC, jfgrimm commented
I'm seeing:
```
4366941 automake found. Running autogen.sh.                                             
4366942 + libtoolize --copy                                                             
4366943 autogen.sh: line 43: libtoolize: command not found                              
4366944 make --directory=libuv \                                                        
4366945         HAVE_DTRACE=0                    
4366946 make[1]: Entering directory `/dev/shm/jfg508/R/4.2.1/foss-2022a/httpuv/httpuv/src/libuv'
4366947 CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /dev/shm/jfg508/R/4.2.1/foss-2022a/httpuv/httpuv/src/libuv/missing aclocal-1.16 -I m4
4366948 /dev/shm/jfg508/R/4.2.1/foss-2022a/httpuv/httpuv/src/libuv/missing: line 81: aclocal-1.16: command not found            
4366949 WARNING: 'aclocal-1.16' is missing on your system.                              
4366950          You should only need it if you modified 'acinclude.m4' or              
4366951          'configure.ac' or m4 files included by 'configure.ac'.                 
4366952          The 'aclocal' program is part of the GNU Automake package:             
4366953          <https://www.gnu.org/software/automake>                                
4366954          It also requires GNU Autoconf, GNU m4 and Perl in order to run:        
4366955          <https://www.gnu.org/software/autoconf>                                
4366956          <https://www.gnu.org/software/m4/>                                     
4366957          <https://www.perl.org/>                                                
4366958 make[1]: *** [aclocal.m4] Error 127                                             
4366959 make[1]: Leaving directory `/dev/shm/jfg508/R/4.2.1/foss-2022a/httpuv/httpuv/src/libuv'
4366960 make: *** [libuv/.libs/libuv.a] Error 2                                         
4366961 ERROR: compilation failed for package httpuv
```
I guess we should add `('Autotools', '20220317')` as a `builddependency`

2022-07-05 14:55 UTC, jfgrimm requested changes

2022-07-05 14:55 UTC, jfgrimm commented on easybuild/easyconfigs/r/R/R-4.2.1-foss-2022a.eb
> +]
required for (at least) `httpuv`
```suggestion
    ('Autotools', '20220317'),
]
```

2022-07-06 16:04 UTC, boegel commented
> 

@verdurin Please open a separate issue for this, we've been using HDF5 1.10.x for quite some time now, so this is definitely not a reason to go back to using HDF5 1.8.x (especially since the problem is specific to Seurat).

2022-07-07 07:02 UTC, boegel commented
Going in, thanks @branfosj!

2022-07-07 07:03 UTC, merged