{vis}[foss/2022a] matplotlib v3.5.2 w/ Python 3.10.4
easybuilders/easybuild-easyconfigs pull request #15796
Opened 2022-06-30 11:13 UTC by sassy-crick

(created using `eb --new-pr`)

2022-06-30 12:31 UTC, jfgrimm commented
@sassy-crick can you add the `Pillow` easyconfig to the PR?

2022-07-01 08:55 UTC, sassy-crick commented
Apologies for that, this slipped through. I have added all the dependencies now, including the ones which are already merged.

2022-07-01 10:06 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
himem06.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/80b6e2bebd528a1c35e0209df8404f5b for a full test report.

2022-07-01 10:08 UTC, jfgrimm commented
@boegelbot please test @ generoso

2022-07-01 11:13 UTC, jfgrimm requested changes

2022-07-15 15:11 UTC, sassy-crick commented on easybuild/easyconfigs/m/matplotlib/matplotlib-3.5.2-foss-2022a.eb
> +        'sources': '%(name)s-%(version)s.tar.gz',
Done. Thanks for finding this!

2022-08-15 08:16 UTC, bedroge commented
Looks like this already got merged in #15894 in the meantime, so I'm closing this PR.

2022-08-15 08:16 UTC, closed without merging