{geo}[gompi/2021b] Fortran-YAML v20210420, flexout v20220209, FABM v1.0.3, ...
easybuilders/easybuild-easyconfigs pull request #15837
Opened 2022-07-12 10:02 UTC by lexming

(created using `eb --new-pr`)

2022-07-12 12:09 UTC, lexming commented
@boegelbot: please test @ generoso

2022-08-31 06:53 UTC, akesandgren commented on easybuild/easyconfigs/f/Fortran-YAML/Fortran-YAML-20210420-GCCcore-11.2.0.eb
> +sources = ['%s.tar.gz' % local_commit]
I prefer this for unversioned downloads
```
sources = [{'download_filename': '%s.tar.gz' % local_commit, 'filename': SOURCE_TAR_GZ}]
```
that way the downloaded filename has a more clear relation to the naming of the easyconfig.

2022-08-31 08:25 UTC, akesandgren requested changes

2025-06-16 15:19 UTC, boegel commented
Closing this since `gompi/2021b` is deprecated or no longer supported, see https://docs.easybuild.io/policies/toolchains

@lexming If this is still relevant, please consider opening a new pull request using a more recent toolchain

2025-06-16 15:19 UTC, closed without merging