{math}[GCCcore/11.3.0] libcerf v2.1
easybuilders/easybuild-easyconfigs pull request #15948
Opened 2022-08-02 08:46 UTC by sassy-crick

(created using `eb --new-pr`)

2022-08-02 12:51 UTC, jfgrimm commented
@boegelbot please test @ generoso

2022-08-02 12:54 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
himem01.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/89f102bff1a5bc5b8c9aff33cbf555d8 for a full test report.

2022-08-02 13:06 UTC, jfgrimm requested changes

2022-08-02 13:06 UTC, jfgrimm commented on easybuild/easyconfigs/l/libcerf/libcerf-2.1-GCCcore-11.3.0.eb
> +    ('Perl', '5.34.1'),  # required for pod2html
the `-minimal` version should suffice here, it provides `pod2html`
```suggestion
    ('Perl', '5.34.1', '-minimal'),  # required for pod2html
```

2022-08-08 16:36 UTC, SebastianAchilles commented
@boegelbot please test @ jsc-zen2

2022-08-08 16:37 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-eb - Linux Ubuntu 22.04, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.4
See https://gist.github.com/e661a2febc60a6e399ae7c6484eaaa22 for a full test report.

2022-08-08 16:37 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bdw-opensuse-154 - Linux openSUSE Leap 15.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 510.85.02, Python 3.6.15
See https://gist.github.com/9f31e96b8c7917a0f4e3ee636e120b5a for a full test report.

2022-08-08 16:38 UTC, SebastianAchilles commented
@boegelbot please test @ generoso

2022-08-08 16:38 UTC, SebastianAchilles approved these changes
lgtm

2022-08-08 16:42 UTC, SebastianAchilles commented
Going in, thanks @sassy-crick!

2022-08-08 16:42 UTC, merged