{vis}[GCCcore/11.3.0] gifsicle v1.93
easybuilders/easybuild-easyconfigs pull request #15954
Opened 2022-08-02 11:36 UTC by sassy-crick

(created using `eb --new-pr`)

2022-08-02 13:21 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
himem01.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/c0c74f2f04e7b06a9913431e995fed57 for a full test report.

2022-08-02 13:22 UTC, jfgrimm commented on easybuild/easyconfigs/g/gifsicle/gifsicle-1.93-GCCcore-11.3.0.eb
> +configure_cmd = "autoreconf -i && ./configure"
```suggestion
preconfigopts = "autoreconf -i &&"
```

2022-08-02 13:25 UTC, jfgrimm requested changes
you're missing some (runtime) dependencies:

```
ldd $EBROOTGIFSICLE/bin/gifview 
	linux-vdso.so.1 =>  (0x00007fffb25ed000)
	libSM.so.6 => /lib64/libSM.so.6 (0x00007febe5ef8000)
	libICE.so.6 => /lib64/libICE.so.6 (0x00007febe5cdc000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007febe599e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007febe569c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007febe5480000)
	libc.so.6 => /lib64/libc.so.6 (0x00007febe50b2000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007febe4ead000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007febe4c85000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007febe4a81000)
	/lib64/ld-linux-x86-64.so.2 (0x00007febe6100000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007febe487d000)
```

2022-08-03 09:39 UTC, sassy-crick commented on easybuild/easyconfigs/g/gifsicle/gifsicle-1.93-GCCcore-11.3.0.eb
> +configure_cmd = "autoreconf -i && ./configure"
Thanks, that is a better way.

2022-08-03 09:40 UTC, sassy-crick commented
> you're missing some (runtime) dependencies:
> 
> ```
> ldd $EBROOTGIFSICLE/bin/gifview 
> 	linux-vdso.so.1 =>  (0x00007fffb25ed000)
> 	libSM.so.6 => /lib64/libSM.so.6 (0x00007febe5ef8000)
> 	libICE.so.6 => /lib64/libICE.so.6 (0x00007febe5cdc000)
> 	libX11.so.6 => /lib64/libX11.so.6 (0x00007febe599e000)
> 	libm.so.6 => /lib64/libm.so.6 (0x00007febe569c000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007febe5480000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00007febe50b2000)
> 	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007febe4ead000)
> 	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007febe4c85000)
> 	libdl.so.2 => /lib64/libdl.so.2 (0x00007febe4a81000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007febe6100000)
> 	libXau.so.6 => /lib64/libXau.so.6 (0x00007febe487d000)
> ```

Thanks for finding that. I have added the missing X11 so hopefully that is ok now.

2022-08-09 15:44 UTC, Micket approved these changes
lgtm

2022-08-09 15:45 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.5, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/df3ccb3e2bc69e10796667a7eb1820af for a full test report.

2022-08-09 15:48 UTC, Micket commented
Going in, thanks @sassy-crick!

2022-08-09 15:48 UTC, merged