{devel}[foss/2021a] torchsampler v0.1.2 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #15965
Opened 2022-08-04 12:09 UTC by smoors

(created using `eb --new-pr`)

2022-08-23 09:07 UTC, smoors commented
@boegelbot: please test @ generoso

2022-08-23 18:41 UTC, smoors commented
Test report by @smoors
**FAILED**
Build succeeded for 2 out of 6 (2 easyconfigs in total)
node304.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/1eb7b07f0df5a1385c1eb6fe8636168a for a full test report.

2022-09-01 14:29 UTC, akesandgren requested changes

2022-09-01 14:29 UTC, akesandgren commented on easybuild/easyconfigs/t/torchsampler/torchsampler-0.1.2-foss-2021a.eb
> +A (PyTorch) imbalanced dataset sampler for oversampling low classesand
missing " " before last "and"

2022-09-01 14:29 UTC, akesandgren commented on easybuild/easyconfigs/t/torchsampler/torchsampler-0.1.2-foss-2021a-CUDA-11.3.1.eb
> +    ('CUDA', '11.3.1', '', True),
Change to use SYSTEM instead of True

2022-09-01 14:29 UTC, akesandgren commented on easybuild/easyconfigs/t/torchsampler/torchsampler-0.1.2-foss-2021a-CUDA-11.3.1.eb
> +A (PyTorch) imbalanced dataset sampler for oversampling low classesand
Missing " " before "and" here too

2022-09-01 16:21 UTC, smoors commented
@boegelbot: please test @ generoso

2022-10-24 19:33 UTC, smoors commented
closing in favor of #16464

2022-10-24 19:33 UTC, closed without merging