{numlib,phys}[intel-compilers/2022.1.0] FFTW v3.3.10, CrystFEL v0.10.1, GSL v2.7
easybuilders/easybuild-easyconfigs pull request #16039
Opened 2022-08-12 17:29 UTC by Micket

(created using `eb --new-pr`)

2022-08-12 21:22 UTC, Micket commented
I'm not sure i'm doing the right thing for FFTW here, haven't been paying attention to the recent changes done there. So please review that carefully so that it makes sense.

2023-05-24 06:57 UTC, akesandgren approved these changes
LGTM

2023-05-24 06:57 UTC, akesandgren commented
@boegelbot Please test @ jsc-zen2

2023-05-24 07:04 UTC, akesandgren commented
@boegelbot Please test @ generoso

2023-05-24 07:05 UTC, akesandgren commented
Test report by @akesandgren
**FAILED**
Build succeeded for 2 out of 7 (4 easyconfigs in total)
b-cn1603.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 525.105.17, Python 3.10.6
See https://gist.github.com/akesandgren/0926ff967837d7669dafea257f2a9a77 for a full test report.

2023-05-24 07:10 UTC, akesandgren requested changes

2024-03-26 15:44 UTC, akesandgren commented
@Micket Ping on the HDF5 version changes

2025-05-09 11:16 UTC, akesandgren commented
@Micket Ping on pending HDF5 changes

2025-05-09 12:53 UTC, Micket commented
To old to test this toolchain, don't want to build all that on my test environment. Updating it instead #22863

2025-05-09 12:53 UTC, closed without merging