{lib}[GCCcore/11.2.0] glib-networking v2.72.1
easybuilders/easybuild-easyconfigs pull request #16085
Opened 2022-08-23 09:40 UTC by sassy-crick

(created using `eb --new-pr`)

2022-08-29 09:32 UTC, akesandgren requested changes

2022-08-29 09:32 UTC, akesandgren commented on easybuild/easyconfigs/g/glib-networking/glib-networking-2.72.1-GCCcore-11.2.0.eb
> +    ('CMake', '3.22.1'),
glib-networking doesn't use CMake, please remove.

2022-08-29 10:17 UTC, Micket requested changes

2022-09-05 14:07 UTC, sassy-crick commented on easybuild/easyconfigs/g/glib-networking/glib-networking-2.72.1-GCCcore-11.2.0.eb
> +    ('CMake', '3.22.1'),
Done.

2022-09-05 14:07 UTC, sassy-crick commented on easybuild/easyconfigs/g/glib-networking/glib-networking-2.72.1-GCCcore-11.2.0.eb
> +    ('pkg-config', '0.29.2'),
Done. Thanks for both suggestions.

2022-09-05 18:16 UTC, boegel commented
@boegelbot please test @ generoso

2022-09-05 18:16 UTC, boegel approved these changes
lgtm

2022-09-05 18:22 UTC, boegel commented
Going in, thanks @sassy-crick!

2022-09-05 18:22 UTC, merged

2022-09-05 18:41 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (1 easyconfigs in total)
node3151.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/dcd3aa73b33a01d43f0017915e5d13b2 for a full test report.