{lib}[GCCcore/11.2.0] nghttp3 v0.6.0
easybuilders/easybuild-easyconfigs pull request #16097
Opened 2022-08-23 11:41 UTC by sassy-crick

(created using `eb --new-pr`)

2022-08-29 09:38 UTC, akesandgren requested changes

2022-08-29 09:38 UTC, akesandgren commented on easybuild/easyconfigs/n/nghttp3/nghttp3-0.6.0-GCCcore-11.2.0.eb
> +configopts = '-DCMAKE_BUILD_TYPE=release '
These are the default for CMakeMake and should be removed (esp since Release is spelled with capital R, not lowercase)

2022-09-05 18:22 UTC, boegel commented
@boegelbot please test @ generoso

2022-09-05 18:26 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2022-09-05 18:33 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3151.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/1e8e74abd44225065278645a48c6047d for a full test report.

2022-09-05 18:53 UTC, boegel approved these changes
lgtm

2022-09-05 18:53 UTC, boegel commented
Going in, thanks @sassy-crick!

2022-09-05 18:53 UTC, merged