{lib}[GCCcore/11.2.0] ngtcp2 v0.7.0
easybuilders/easybuild-easyconfigs pull request #16098
Opened 2022-08-23 11:44 UTC by sassy-crick

(created using `eb --new-pr`)

2022-09-05 18:42 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3151.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/b0dfcad32fbf8dd966799aa50d23e7ae for a full test report.

2022-09-05 18:54 UTC, boegel commented
@boegelbot please test @ generoso

2022-09-05 18:57 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2022-09-06 07:23 UTC, boegel requested changes

2022-09-06 07:23 UTC, boegel commented on easybuild/easyconfigs/n/ngtcp2/ngtcp2-0.7.0-GCCcore-11.2.0.eb
> +osdependencies = [('gnutls-devel', 'gnutls-dev', 'libgnutls-devel')]
@sassy-crick Why not depend on `GnuTLS` instead?

2022-09-06 07:26 UTC, boegel commented
Tests on both `generoso` and `jsc-zen2` failed with:
```
One or more OS dependencies were not found: [('gnutls-devel', 'gnutls-dev', 'libgnutls-devel')]
```

2022-09-21 09:47 UTC, zao commented
Test report by @zao
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
eb-u2204 - Linux Ubuntu 22.04, x86_64, AMD Ryzen 9 3900X 12-Core Processor, Python 3.10.4
See https://gist.github.com/6057ed08187fda851bc1392344ee9fe4 for a full test report.

2022-09-23 20:44 UTC, boegel commented
@boegelbot please test @ generoso

2022-09-23 20:46 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2022-09-23 20:47 UTC, boegel approved these changes

2022-09-23 20:49 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3144.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/4956081958d031816e24aedb23f23d5a for a full test report.

2022-09-23 21:01 UTC, boegel commented
Going in, thanks @sassy-crick!

2022-09-23 21:01 UTC, merged

2022-09-23 21:11 UTC, boegel commented
@boegelbot please test @ jsc-zen2