make check for toolchain value in dependency spec in easyconfigs test suite aware that dumped easyconfig uses SYSTEM constant
easybuilders/easybuild-easyconfigs pull request #16126
Opened 2022-08-25 15:53 UTC by boegel

requires:
* https://github.com/easybuilders/easybuild-framework/pull/4069

2022-08-25 15:54 UTC, boegel commented
The tests for this PR will fail until https://github.com/easybuilders/easybuild-framework/pull/4069 is merged, but this PR will need to get merged ASAP after the merging of https://github.com/easybuilders/easybuild-framework/pull/4069 to avoid broken tests in PRs being opened...

2022-08-26 10:35 UTC, Micket approved these changes
lgtm

2022-08-26 10:43 UTC, Micket requested changes

2022-08-26 10:43 UTC, Micket commented on test/easyconfigs/easyconfigs.py
> +                        if orig_dep[3] == True:
```suggestion
                        if orig_dep[3] is True:
```

2022-08-26 10:44 UTC, Micket commented on test/easyconfigs/easyconfigs.py
> +                        if orig_dep[3] == True:
i guess this is the nicest in this setting, don't want implicit true conversions i think

2022-08-26 11:15 UTC, jfgrimm approved these changes

2022-08-26 11:15 UTC, merged