{bio}[GCCcore/11.2.0] Porechop-0.2.4 w/Python/3.9.6
easybuilders/easybuild-easyconfigs pull request #16121
Opened 2022-08-24 17:32 UTC by fizwit

(created using `eb --new-pr`)

2022-08-25 13:10 UTC, verdurin requested changes

2022-08-26 11:16 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/3a36111e30273780e0c645b0d6751ed3 for a full test report.

2022-08-26 11:17 UTC, verdurin commented
@boegelbot please test @ generoso

2022-08-29 21:46 UTC, fizwit commented on easybuild/easyconfigs/p/Porechop/Porechop-0.2.4-GCCcore-11.2.0.eb
> +dependencies = [
done

2022-09-06 21:29 UTC, verdurin approved these changes
Looks fine.

2022-09-06 21:29 UTC, verdurin commented
Going in, thanks @fizwit!

2022-09-06 21:29 UTC, merged