{tools}[foss/2021a] Horovod v0.25.0 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #16135
Opened 2022-08-26 09:51 UTC by boegel

(created using `eb --new-pr`)

2022-08-26 09:57 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3900.accelgor.os - Linux RHEL 8.4, x86_64, AMD EPYC 7413 24-Core Processor (zen3), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 510.73.08, Python 3.6.8
See https://gist.github.com/10ce8f030bcfe1400c9b1740fa68c16b for a full test report.

2022-08-26 12:46 UTC, boegel commented
@boegelbot please test @ generoso

2022-08-29 08:40 UTC, akesandgren commented on easybuild/easyconfigs/h/Horovod/Horovod-0.25.0-foss-2021a-CUDA-11.3.1-PyTorch-1.10.0.eb
> +description = "Horovod is a distributed training framework for TensorFlow."
Perhaps the description should be updated to mention PyTorch and mxnet.
Like
```
description = """Horovod is a distributed training framework for TensorFlow, PyTorch and MXnet.
This build only have PyTorch enabled."""
```

2022-10-17 14:15 UTC, jfgrimm reviewed
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 16135` and update the PR to use `SYSTEM` instead.

2023-07-01 15:35 UTC, branfosj requested changes

2023-07-01 15:35 UTC, branfosj commented on easybuild/easyconfigs/h/Horovod/Horovod-0.25.0-foss-2021a-CUDA-11.3.1-PyTorch-1.10.0.eb
> +    ('CUDA', '11.3.1', '', True),
```suggestion
    ('CUDA', '11.3.1', '', SYSTEM),
```

2023-07-01 15:35 UTC, branfosj commented on easybuild/easyconfigs/h/Horovod/Horovod-0.25.0-foss-2021a-CUDA-11.3.1-PyTorch-1.10.0.eb
> +This build only have PyTorch enabled."""
```suggestion
This build only has PyTorch enabled."""
```

2023-07-01 15:41 UTC, branfosj approved these changes

2023-07-01 15:42 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0203u29a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 520.61.05, Python 3.6.8
See https://gist.github.com/branfosj/ad2603847a816c3b780307cc6abe7b2b for a full test report.

2023-07-01 15:55 UTC, branfosj commented
Going in, thanks @boegel!

2023-07-01 15:55 UTC, merged