{tools}[GCCcore/12.1.0] cURL v7.84.0
easybuilders/easybuild-easyconfigs pull request #16146
Opened 2022-08-29 01:37 UTC by absrocks

(created using `eb --new-pr`)

2022-08-29 08:59 UTC, akesandgren requested changes

2022-08-29 08:59 UTC, akesandgren commented on easybuild/easyconfigs/c/cURL/cURL-7.84.0-GCCcore-12.1.0.eb
> +#checksums = ['c0e64302a33d2fb79e0fc4e674260a22941e92ee2f11b894bf94d32b8f5531af']
checksum must not be commented out.

2022-08-29 15:05 UTC, absrocks commented on easybuild/easyconfigs/c/cURL/cURL-7.84.0-GCCcore-12.1.0.eb
> +#checksums = ['c0e64302a33d2fb79e0fc4e674260a22941e92ee2f11b894bf94d32b8f5531af']
I added the checksum verification

2022-08-30 07:11 UTC, akesandgren commented
@boegelbot Please test @ generoso

2022-08-30 10:44 UTC, akesandgren approved these changes

2022-08-30 10:45 UTC, akesandgren commented
Going in, thanks @absrocks!

2022-08-30 10:45 UTC, merged

2022-08-30 14:15 UTC, absrocks commented
Great! Thanks @akesandgren!