{devel}[GCCcore/11.3.0] xtrans v1.3.5
easybuilders/easybuild-easyconfigs pull request #16194
Opened 2022-09-05 20:29 UTC by sassy-crick

(created using `eb --new-pr`)

2022-09-06 09:07 UTC, jfgrimm requested changes

2022-09-06 09:07 UTC, jfgrimm commented on easybuild/easyconfigs/x/xtrans/xtrans-1.3.5-GCCcore-11.3.0.eb
> +# toolchain = {'name': 'intel', 'version': '2016a'}
```suggestion
```

2022-09-06 09:07 UTC, jfgrimm commented on easybuild/easyconfigs/x/xtrans/xtrans-1.3.5-GCCcore-11.3.0.eb
> +]
```suggestion
builddependencies = [
    ('binutils', '2.38'),
    ('xorg-macros', '1.19.3'),
    ('libxslt', '1.1.34'),
]
```

2022-09-15 08:06 UTC, migueldiascosta commented
@boegelbot please test @ generoso

2022-09-15 08:16 UTC, migueldiascosta commented
@boegelbot please test @ jsc-zen2

2022-09-15 08:56 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
node142.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/ec696548e82bda35c4601b375652fb87 for a full test report.

2022-09-15 08:58 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node142.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/5ef5ab0e6a718a5b7d5e14d7c80924b0 for a full test report.

2022-09-15 08:59 UTC, jfgrimm approved these changes
LGTM

2022-09-15 09:00 UTC, jfgrimm commented
Going in, thanks @sassy-crick!

2022-09-15 09:00 UTC, merged