{lang}[GCCcore/12.2.0] Perl v5.36.0, libreadline v8.1.2, ncurses v6.3, ...
easybuilders/easybuild-easyconfigs pull request #16204
Opened 2022-09-08 08:02 UTC by boegel

(created using `eb --new-pr`)

2022-09-08 08:30 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3114.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/ade13c4162c31e81ac865b46abf26f0e for a full test report.

2022-09-08 15:26 UTC, boegel commented on easybuild/easyconfigs/n/ncurses/ncurses-6.3-GCCcore-12.2.0.eb
> +local_common_configopts = "--with-shared --enable-overwrite --without-ada --enable-symlinks "
Let's get #16064 merged first (which only touches `ncurses` easyconfigs using the `system` toolchain).

I would definitely tackle (recent) `ncurses` easyconfigs using a non-system toolchain in a separate PR anyway...

2022-09-08 15:26 UTC, boegel commented
@boegelbot please test @ generoso
CORE_CNT=16

2022-09-09 15:58 UTC, verdurin commented on easybuild/easyconfigs/n/ncurses/ncurses-6.3-GCCcore-12.2.0.eb
> +local_common_configopts = "--with-shared --enable-overwrite --without-ada --enable-symlinks "
That's now merged.

2022-09-10 14:22 UTC, SebastianAchilles commented
@boegelbot please test @ jsc-zen2
CORE_CNT=16

2022-09-10 15:16 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**FAILED**
Build succeeded for 4 out of 6 (6 easyconfigs in total)
bdw-opensuse-154 - Linux openSUSE Leap 15.4, x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.6.15
See https://gist.github.com/58b1d1221ba71699b7516476641a8037 for a full test report.

2022-09-10 15:16 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**FAILED**
Build succeeded for 4 out of 6 (6 easyconfigs in total)
zen2-ubuntu-eb - Linux Ubuntu 22.04, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.4
See https://gist.github.com/1ed2d2d8bee8776c6498b3482907469f for a full test report.

2022-09-21 08:29 UTC, SebastianAchilles requested changes

2022-09-21 08:29 UTC, SebastianAchilles commented on easybuild/easyconfigs/n/ncurses/ncurses-6.3-GCCcore-12.2.0.eb
> +local_common_configopts = "--with-shared --enable-overwrite --without-ada --enable-symlinks "
I am seeing the issue https://github.com/easybuilders/easybuild-easyconfigs/issues/16014 here as well. As in https://github.com/easybuilders/easybuild-easyconfigs/pull/16270 we need to add `--with-versioned-syms`
```suggestion
local_common_configopts = "--with-shared --enable-overwrite --without-ada --enable-symlinks --with-versioned-syms "
```

2022-10-17 14:15 UTC, jfgrimm reviewed
As decided in issue #16330, we have deprecated the use of `True` to signify a system-toolchain dependency (#16384), in favour of the more intuitive `SYSTEM` template constant. Due to the change in the test suite, please run `eb --sync-pr-with-develop 16204` and update the PR to use `SYSTEM` instead.

2022-10-18 13:54 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bwd-rockylinux-90 - Linux Rocky Linux 9.0 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.10
See https://gist.github.com/dfbe5f232dfab544312a1f44820e52b5 for a full test report.

2022-10-18 13:54 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
zen2-ubuntu-eb - Linux Ubuntu 22.04, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.6
See https://gist.github.com/5d00a2c1947a3365ca2c3e9dcfec60bd for a full test report.

2022-10-18 14:20 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
jrc0870.jureca - Linux Rocky Linux 8.6, AArch64, ARM UNKNOWN (graviton2), 2 x NVIDIA NVIDIA A100-PCIE-40GB, 515.65.01, Python 3.6.8
See https://gist.github.com/e9dc4039474085fd333ed9e16a3c281c for a full test report.

2022-10-18 15:39 UTC, boegel commented
@boegelbot please test @ generoso

2022-10-18 16:12 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2022-10-18 17:57 UTC, jfgrimm approved these changes
LGTM

2022-10-18 17:59 UTC, jfgrimm commented
Going in, thanks @boegel!

2022-10-18 17:59 UTC, merged

2022-10-18 18:16 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/564643d4f4eda15641808dd84b7d3286 for a full test report.