add python-irodsclient
easybuilders/easybuild-easyconfigs pull request #16300
Opened 2022-09-23 12:13 UTC by jefscheepers

See #16299

2022-09-23 14:02 UTC, boegel requested changes

2022-09-23 14:02 UTC, boegel commented on easybuild/easyconfigs/p/python-irodsclient/python-irodsclient-1.1.4.eb
> +    ('python-irodsclient', '1.1.4', {'modulename':'irods'})
@jefscheepers Thanks a lot for the contribution!

You will need to add SHA256 checksums for each of the extensions here to make the CI tests pass (`eb --inject-checksums` is your friend here), and we would also appreciate from trivial style changes to make the easyconfig match the usual style in easyconfigs a bit better.

A good example to compare with is https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/g/GitPython/GitPython-3.1.24-GCCcore-11.2.0.eb

Do let us know if you need any help with this!

2022-09-23 15:18 UTC, jefscheepers commented
@boegel Is this better? 

Since I'll probably be making a GCCcore 10.3.0 & Python 3.9.5 version for our cluster, I added a Python version suffix as well (example taken from [here](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/g/GitPython/GitPython-3.1.9-GCCcore-9.3.0-Python-3.8.2.eb)). Is that okay, or should I remove it?

2022-09-23 22:28 UTC, boegel submitted a review, later dismissed

2022-09-26 09:54 UTC, jefscheepers commented on easybuild/easyconfigs/p/python-irodsclient/python-irodsclient-1.1.4-GCCcore-11.2.0-Python-3.9.6.eb
> +versionsuffix = '-Python-%(pyver)s'
Removed the versionsuffix and adapted the title

2022-09-26 11:15 UTC, smoors commented on easybuild/easyconfigs/p/python-irodsclient/python-irodsclient-1.1.4-GCCcore-11.2.0-Python-3.9.6.eb
> +
@jefscheepers please add `binutils` builddep here?
```suggestion

builddependencies = [('binutils', '2.37')]

```

2022-09-26 11:16 UTC, smoors commented on easybuild/easyconfigs/p/python-irodsclient/python-irodsclient-1.1.4-GCCcore-11.2.0.eb
> +
@jefscheepers please add `binutils` builddep here?
```suggestion

builddependencies = [('binutils', '2.37')]

```

2022-09-26 11:17 UTC, smoors commented on easybuild/easyconfigs/p/python-irodsclient/python-irodsclient-1.1.4-GCCcore-11.2.0-Python-3.9.6.eb
> +versionsuffix = '-Python-%(pyver)s'
@jefscheepers please remove the duplicate easyconfig (i.e. the one with the Python versionsuffix)?

2022-09-27 14:58 UTC, jefscheepers commented on easybuild/easyconfigs/p/python-irodsclient/python-irodsclient-1.1.4-GCCcore-11.2.0-Python-3.9.6.eb
> +versionsuffix = '-Python-%(pyver)s'
Didn't see that one in my local, should be removed now

2022-09-27 16:15 UTC, smoors commented
@boegelbot: please test @ generoso

2022-09-27 16:19 UTC, smoors commented
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node375.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/947fbe9b1db6b64257b5ed042107d4e7 for a full test report.

2022-09-27 16:41 UTC, smoors approved these changes
lgtm

2022-09-27 16:42 UTC, smoors commented
Going in, thanks @jefscheepers!

2022-09-27 16:42 UTC, merged