{lib,tools}[GCCcore/11.3.0,foss/2022a] GitPython v3.1.27, buildingspy v4.0.0 w/ Python 3.10.4
easybuilders/easybuild-easyconfigs pull request #16308
Opened 2022-09-23 19:39 UTC by ItIsI-Orient

(created using `eb --new-pr`)

2022-09-23 21:24 UTC, boegel requested changes

2022-09-23 21:24 UTC, boegel commented on easybuild/easyconfigs/b/buildingspy/buildingspy-4.0.0-foss-2022a.eb
> +    ('Jinja2', '3.1.2', {
This exact same version is already included in `Python` 3.10.4

2022-09-23 21:24 UTC, boegel commented on easybuild/easyconfigs/b/buildingspy/buildingspy-4.0.0-foss-2022a.eb
> +    ('six', '1.14.0', {
Both `simplejson` and `six` are already included with Python 3.10.4, and the versions are more recent than what you're using here.

If `buildingspy` has strict version requirements on these versions, we should just relax those (replace `==` with `>=` in `requirements.txt` for example).

2022-09-26 11:53 UTC, ItIsI-Orient commented
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3702.slaking.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/3059763fb75e80de389cd1b826a5b9f6 for a full test report.

2022-09-26 12:41 UTC, boegel approved these changes
lgtm

2022-09-26 12:41 UTC, boegel commented
@boegelbot please test @ generoso

2022-09-26 12:46 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3144.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/e67aa2540c57267edd11237a5fada295 for a full test report.

2022-09-26 13:06 UTC, boegel commented
Going in, thanks @ItIsI-Orient!

2022-09-26 13:06 UTC, merged