configs to support CP2K QM/MM in GROMACS
easybuilders/easybuild-easyconfigs pull request #16362
Opened 2022-10-05 15:13 UTC by ostueker

easyconfigs needed to evaluate changes to GROMACS easyblock changes in easybuilders/easybuild-easyblocks#2750

* GROMACS-2022.3-foss-2020a-CP2K.eb 
* CP2K-2022.1-foss-2020a.eb

2022-10-05 15:36 UTC, ostueker commented
The error in the tests (see below) is expected, because the variable `mpi_only` has been introduced in easybuilders/easybuild-easyblocks#2750 [here](https://github.com/easybuilders/easybuild-easyblocks/pull/2750/files#diff-528f8ee1c26eeeb855e4beced90381894b8bbb583cba1f8545b97e9fe13a24abR69) .


```
======================================================================
ERROR: test__parse_easyconfig_GROMACS-2022.3-foss-2020a-CP2K.eb (test.easyconfigs.easyconfigs.EasyConfigTest)
Test for easyconfig GROMACS-2022.3-foss-2020a-CP2K.eb
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/easyconfigs/easyconfigs.py", line 1481, in innertest
    template_easyconfig_test(self, spec_path)
  File "test/easyconfigs/easyconfigs.py", line 1202, in template_easyconfig_test
    ecs = process_easyconfig(spec)
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/easybuild/framework/easyconfig/easyconfig.py", line 2071, in process_easyconfig
    raise EasyBuildError("Failed to process easyconfig %s: %s", spec, err.msg)
EasyBuildError: "Failed to process easyconfig /home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/g/GROMACS/GROMACS-2022.3-foss-2020a-CP2K.eb: Use of 1 unknown easyconfig parameters detected in GROMACS-2022.3-foss-2020a-CP2K.eb: mpi_only\nIf these are just local variables please rename them to start with 'local_', or try using --fix-deprecated-easyconfigs to do this automatically.\nFor more information, see https://easybuild.readthedocs.io/en/latest/Easyconfig-files-local-variables.html ."
```

2022-10-06 12:18 UTC, ostueker commented
The error is a :chicken: and :egg:  problem:

* this PR depends on changes implemented in PR easybuilders/easybuild-easyblocks#2750
* and PR easybuilders/easybuild-easyblocks#2750 won't get merged without having been tested with these easyconfigs.

2022-12-02 06:53 UTC, akesandgren requested changes

2022-12-02 06:53 UTC, akesandgren commented on easybuild/easyconfigs/c/CP2K/CP2K-2022.1-foss-2020a.eb
> +    ('Bison', '3.7.1'),
For 2020a toolchain use Bison 3.5.3

2022-12-02 06:53 UTC, akesandgren commented on easybuild/easyconfigs/c/CP2K/CP2K-2022.1-foss-2020a.eb
> +    ('libxc', '5.1.3'),
For 2020a toolchain use libxc 4.3.4

2022-12-02 06:53 UTC, akesandgren commented on easybuild/easyconfigs/g/GROMACS/GROMACS-2022.3-foss-2020a-CP2K.eb
> +    ('CMake', '3.23.1'),
For 2020a toolchain use CMake 3.16.4

2024-01-13 18:23 UTC, boegel commented
closing this since `foss/2020a` is deprecated, see https://docs.easybuild.io/policies/toolchains

2024-01-13 18:23 UTC, closed without merging