Adding udocker version 1.3.4 with cuda support
easybuilders/easybuild-easyconfigs pull request #16399
Opened 2022-10-13 11:27 UTC by gpourtois

Test to upgrade udocker to version 1.3.4 with cuda support

2022-10-14 11:27 UTC, casparvl commented
@boegelbot please test @ generoso

2022-10-14 14:24 UTC, casparvl requested changes

2022-10-25 12:23 UTC, branfosj commented
close / open to see if that triggers the CI to run

2022-11-01 14:24 UTC, casparvl requested changes

2022-11-01 14:24 UTC, casparvl commented on easybuild/easyconfigs/u/udocker/udocker-1.3.4-fosscuda-2020b.eb
> +versionsuffix = '-Python-%(pyver)s'
Please remove this (this is one of the things the CI is complaining about). Nowadays, we assume Python-3.X to be standard, so we don't add a version suffix for it anymore. We'll only add a versionsuffix if something still depends on Python-2.X.

2022-11-01 14:24 UTC, casparvl commented on easybuild/easyconfigs/u/udocker/udocker-1.3.4-fosscuda-2020b-Python-3.8.6.eb
> +easyblock = 'PythonPackage'
This file can be removed alltogether, see the instructions at https://docs.easybuild.io/en/latest/Integration_with_GitHub.html#deleting-easyconfig-files-or-patches on how to delete easyconfig files if you use EasyBuild's github integration (if you don't use the github integration, you can simply `git rm` this file from your local fork, push that change to your local fork, and this PR should update itself automatically).

2024-01-13 19:25 UTC, closed without merging

2024-01-13 19:25 UTC, boegel commented
closing this since `fosscuda/2020b` is deprecated, see https://docs.easybuild.io/policies/toolchains