{lib}[GCCcore/10.3.0] libunistring v1.0
easybuilders/easybuild-easyconfigs pull request #16410
Opened 2022-10-14 15:43 UTC by casparvl

(created using `eb --new-pr`)

2022-10-14 15:59 UTC, casparvl commented
`libpsl` wouldn't build on one of my systems due to a missing `libunistring`. Added that as dependency now.

2022-10-14 17:06 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/ee734dbefb8e05333c2785dad069de5f for a full test report.

2022-10-14 17:06 UTC, casparvl commented
@boegelbot please test @ generoso

2022-10-14 17:07 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
software1.lisa.surfsara.nl - Linux debian 10.13, x86_64, Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz, Python 3.7.3
See https://gist.github.com/8b37ff8d01427fc6a9d36fb221c539ac for a full test report.

2022-10-17 10:19 UTC, jfgrimm commented
@boegelbot please test @ jsc-zen2

2022-10-17 10:21 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node109.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/e4ba4c5a8f1432958f4a0ebdc395f00b for a full test report.

2022-10-17 10:28 UTC, jfgrimm commented
@casparvl we should also add a dependency on `ICU`:

```
$ ldd $EBROOTLIBPSL/lib/libpsl.so | grep libicu
	libicuuc.so.50 => /lib64/libicuuc.so.50 (0x00007fa1ab6c6000)
	libicudata.so.50 => /lib64/libicudata.so.50 (0x00007fa1aa0f3000)

```

2022-10-17 10:29 UTC, jfgrimm requested changes

2022-10-17 10:29 UTC, jfgrimm commented on easybuild/easyconfigs/l/libpsl/libpsl-0.21.1-GCCcore-10.3.0.eb
> +]
```suggestion
dependencies = [
    ('ICU', '69.1'),
    ('libunistring', '0.9.10'),
]
```

2022-10-17 11:42 UTC, casparvl commented
@boegelbot please test @ generoso

2022-10-17 11:42 UTC, casparvl commented on easybuild/easyconfigs/l/libpsl/libpsl-0.21.1-GCCcore-10.3.0.eb
> +]
Done!

2022-10-17 11:43 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/cc38cab66750e7af58f553f5e7866d2c for a full test report.

2022-10-17 11:54 UTC, casparvl commented
@boegelbot please test @ jsc-zen2

2022-10-17 12:08 UTC, jfgrimm approved these changes

2022-10-17 12:09 UTC, jfgrimm commented
Going in, thanks @casparvl!

2022-10-17 12:09 UTC, merged