{vis}[foss/2021b] ruffus v2.8.4 w/ Python 3.9.6
easybuilders/easybuild-easyconfigs pull request #16428
Opened 2022-10-18 08:28 UTC by PetrKralCZ

(created using `eb --new-pr`)

2022-10-18 08:35 UTC, boegel requested changes

2022-10-18 08:35 UTC, boegel commented on easybuild/easyconfigs/r/ruffus/ruffus-2.8.4-foss-2021b.eb
> +    "python -c 'import ruffus'",
This `import` is already done by default, so drop it and only do the import check on `ruffus.graph`:

```python
sanity_check_commands = ["python -c 'import ruffus.graph'"]

2022-10-18 08:37 UTC, boegel commented
@boegelbot please test @ generoso

2022-10-18 08:44 UTC, boegel requested changes

2022-10-18 08:44 UTC, boegel commented on easybuild/easyconfigs/r/ruffus/ruffus-2.8.4-foss-2021b.eb
> +description = "Ruffus is a Computation Pipeline library for python. It is open-sourced, powerful and user-friendly, and widely used in science and bioinformatics."
You'll need to make this a multi-line string:
```python
description = """Ruffus is a Computation Pipeline library for python. It is open-sourced, powerful and
 user-friendly, and widely used in science and bioinformatics."""
```

2022-10-18 08:48 UTC, boegel requested changes

2022-10-18 08:48 UTC, boegel commented on easybuild/easyconfigs/r/ruffus/ruffus-2.8.4-foss-2021b.eb
> +moduleclass = 'vis'
Maybe `lib` is more appropriate?

2022-10-18 13:20 UTC, PetrKralCZ commented
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3701.slaking.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/d44d17eebdd4d0889c6da1ba9003871b for a full test report.

2022-10-18 13:34 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/21ecadac56fe2cde35bf854bf06339e2 for a full test report.

2022-10-19 07:32 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2022-10-19 08:11 UTC, boegel approved these changes
lgtm

2022-10-19 08:12 UTC, boegel commented
Going in, thanks @PetrKralCZ!

2022-10-19 08:12 UTC, merged