{data}[system/system] AMAPVox v1.9.4
easybuilders/easybuild-easyconfigs pull request #16438
Opened 2022-10-19 06:52 UTC by boegel

(created using `eb --new-pr`)

2022-10-19 09:32 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node109.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/3e8e1fadf6a91aec5c6d560aae14de54 for a full test report.

2022-10-19 09:41 UTC, jfgrimm requested changes

2022-10-19 09:41 UTC, jfgrimm commented on easybuild/easyconfigs/a/AMAPVox/AMAPVox-1.9.4-Java-11.eb
> +    'files': ['AMAPVox.sh', 'AMAPVox-1.9.4.jar'],
```suggestion
    'files': ['AMAPVox.sh', 'AMAPVox-%(version)s.jar'],
```

2022-10-19 09:41 UTC, jfgrimm commented on easybuild/easyconfigs/a/AMAPVox/AMAPVox-1.9.4-Java-11.eb
> +sources = ['AMAPVox-%(version)s.zip']
```suggestion
sources = [SOURCE_ZIP]
```

2022-10-19 18:23 UTC, boegel commented
@boegelbot please test @ generoso

2022-10-20 09:15 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node151.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/b558b39ab94cb672a878e5a3a18ed2e5 for a full test report.

2022-10-20 09:17 UTC, jfgrimm approved these changes
LGTM

2022-10-20 09:17 UTC, jfgrimm commented
Going in, thanks @boegel!

2022-10-20 09:17 UTC, merged