{bio}[foss/2021b] MIGRATE-N v5.0.4
easybuilders/easybuild-easyconfigs pull request #16430
Opened 2022-10-18 10:40 UTC by ItIsI-Orient

(created using `eb --new-pr`)

2022-10-18 10:46 UTC, ItIsI-Orient commented
Test report by @ItIsI-Orient
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3702.slaking.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/3e9734be7e4c624154ef7a575a406a74 for a full test report.

2022-10-18 10:54 UTC, ItIsI-Orient commented
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3702.slaking.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/637363d69936ea87505758db00412e60 for a full test report.

2022-10-18 11:27 UTC, boegel requested changes

2022-10-18 11:27 UTC, boegel commented on easybuild/easyconfigs/m/MIGRATE-N/MIGRATE-N-5.0.4-foss-2021b.eb
> +installopts = "&& make clean && make installmpi"
The `make clean` commands are actually not needed at all, the installation works fine without them

2022-10-18 11:27 UTC, boegel commented on easybuild/easyconfigs/m/MIGRATE-N/MIGRATE-N-5.0.4-foss-2021b.eb
> +start_dir = 'src'
Please move both `start_dir` and `parallel` up, above `configopts`.

The (informal) policy is to specify easyconfig parameter in the order in which they're used by EasyBuild

2022-10-18 11:27 UTC, boegel commented on easybuild/easyconfigs/m/MIGRATE-N/MIGRATE-N-5.0.4-foss-2021b.eb
> +}
We can also add a sanity check command:

```python
sanity_check_commands = ["echo Q | migrate-n"]
```

2022-10-25 14:24 UTC, ItIsI-Orient commented
Test report by @ItIsI-Orient
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3702.slaking.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 3.6.8
See https://gist.github.com/4c6b859370c8c40d94d4d3951991c026 for a full test report.

2022-10-25 20:27 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3106.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/3bd4da6fd4f6e13be8e597a50d34ee25 for a full test report.

2022-10-26 05:25 UTC, boegel approved these changes
lgtm

2022-10-26 05:26 UTC, boegel commented
Going in, thanks @ItIsI-Orient!

2022-10-26 05:26 UTC, merged