add patch for pybind11 2.6.0 to fix failing test due to extra whitespace
easybuilders/easybuild-easyconfigs pull request #16487
Opened 2022-10-25 17:50 UTC by sassy-crick

(created using `eb --new-pr`)

cfr. https://github.com/pybind/pybind11/issues/3680

2022-10-26 09:33 UTC, boegel requested changes

2022-10-26 09:33 UTC, boegel commented on easybuild/easyconfigs/p/pybind11/pybind11-2.6.0-GCCcore-10.2.0.eb
> +patches = ['1d3b04e805c8a7dd4d8b68e2a311c75a66cae1d5.patch']
@sassy-crick Please rename the patch file to something like `pybind11-2.6.0_fix-test-extra-whitespace.patch`

2022-10-26 19:57 UTC, smoors commented
@boegelbot: please test @ generoso

2022-10-27 08:48 UTC, smoors commented
@boegelbot please test @ jsc-zen2

2022-10-27 09:18 UTC, smoors approved these changes
lgtm

2022-10-27 09:19 UTC, smoors approved these changes

2022-10-27 09:20 UTC, smoors commented
Going in, thanks @sassy-crick!

2022-10-27 09:20 UTC, merged