{bio}[foss/2022a] Xmipp v3.22.07-Helios w/ Python 3.10.4
easybuilders/easybuild-easyconfigs pull request #16498
Opened 2022-10-27 09:17 UTC by akesandgren

(created using `eb --new-pr`)

2022-10-27 09:25 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/e4c1600a5427d0eda30546e08fadfa9c for a full test report.

2022-10-27 10:37 UTC, akesandgren commented
Test report by @akesandgren
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/859b94ae3c7760fe4702eced9505d23f for a full test report.

2022-10-27 10:48 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/0ca936ee7b86ae9f88c48bc409950f9b for a full test report.

2022-10-27 11:08 UTC, branfosj commented
@boegelbot please test @ jsc-zen2

2022-10-27 11:51 UTC, branfosj commented
@boegelbot please test @ jsc-zen2

2022-10-27 12:24 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 25 out of 25 (3 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/6a0a7f98ba50c7f79a5d89af1157a8ca for a full test report.

2022-10-27 12:35 UTC, branfosj requested changes
It is looking for `OpenCV` and `HDF5` in Python?

2022-10-27 12:35 UTC, branfosj commented on easybuild/easyconfigs/x/Xmipp/Xmipp-3.22.07-Helios-foss-2022a.eb
> +    ('OpenCV', '4.6.0', '-contrib'),
```
^[[92m g++ -c -w -O2 -ftree-vectorize -march=native -fno-math-errno -std=c++17 xmipp_test_opencv.cpp -o xmipp_test_opencv.o -I../ -I/rds/projects/2017/branfosj-rse/easybuild/EL8-ice/software/Python/3.10.4-GCCcore-11.3.0/include^[[0m
^[[93m xmipp_test_opencv.cpp:1:10: fatal error: opencv2/core/core.hpp: No such file or directory    1 | #include <opencv2/core/core.hpp>      |          ^~~~~~~~~~~~~~~~~~~~~~~compilation terminated.^[[0m


^[[93m OpenCV not found^[[0m
```

2022-10-27 12:54 UTC, akesandgren commented on easybuild/easyconfigs/x/Xmipp/Xmipp-3.22.07-Helios-foss-2022a.eb
> +    ('HDF5', '1.12.2'),
Are you running with the latest xmipp.py from develop?

2022-10-27 12:56 UTC, akesandgren commented on easybuild/easyconfigs/x/Xmipp/Xmipp-3.22.07-Helios-foss-2022a.eb
> +    ('HDF5', '1.12.2'),
Or was that despite the build being successful?

2022-10-27 12:59 UTC, akesandgren commented on easybuild/easyconfigs/x/Xmipp/Xmipp-3.22.07-Helios-foss-2022a.eb
> +    ('HDF5', '1.12.2'),
Oh, I have the same OpenCV error, it's looking for opencv2 not opencv4...

2022-10-27 13:06 UTC, akesandgren commented on easybuild/easyconfigs/x/Xmipp/Xmipp-3.22.07-Helios-foss-2022a.eb
> +    ('HDF5', '1.12.2'),
The problem then is that OpenCV only sets CPATH to $EBROOTOPENCV/include, and doesn't add $EBROOTOPENCV/include/opencv4

2022-10-27 14:18 UTC, akesandgren commented on easybuild/easyconfigs/x/Xmipp/Xmipp-3.22.07-Helios-foss-2022a.eb
> +    ('HDF5', '1.12.2'),
https://github.com/easybuilders/easybuild-easyblocks/pull/2818 fixes the problem in OpenCV 4.x

2022-10-27 14:19 UTC, akesandgren commented on easybuild/easyconfigs/x/Xmipp/Xmipp-3.22.07-Helios-foss-2022a.eb
> +    ('HDF5', '1.12.2'),
With that I get:
```
OPENCV-4 detected without CUDA support
```

2022-10-28 08:11 UTC, branfosj commented on easybuild/easyconfigs/x/Xmipp/Xmipp-3.22.07-Helios-foss-2022a.eb
> +    ('HDF5', '1.12.2'),
Yes, I am getting `OPENCV-4 detected without CUDA support` as well now.

However, I am still seeing
```
Headers for 'libhdf5' not found at '/rds/projects/2017/branfosj-rse/easybuild/EL8-ice/software/Python/3.10.4-GCCcore-11.3.0/include'.
No alternative found in the system.
```

2022-10-28 08:11 UTC, branfosj commented on easybuild/easyconfigs/x/Xmipp/Xmipp-3.22.07-Helios-foss-2022a.eb
> +    ('OpenCV', '4.6.0', '-contrib'),
resolved by https://github.com/easybuilders/easybuild-easyblocks/pull/2818

2022-10-28 08:49 UTC, branfosj commented on easybuild/easyconfigs/x/Xmipp/Xmipp-3.22.07-Helios-foss-2022a.eb
> +    ('HDF5', '1.12.2'),
Ah, so it complains about not finding the headers but finds the library and is fine.

2022-10-28 08:49 UTC, branfosj commented
@boegelbot please test @ jsc-zen2

2022-10-28 09:00 UTC, branfosj commented
@boegelbot please test @ generoso

2022-10-28 09:01 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/ca59b84e20ade9be754c4e076dcd868e for a full test report.

2022-10-28 09:06 UTC, branfosj approved these changes

2022-10-28 09:14 UTC, branfosj commented
Going in, thanks @akesandgren!

2022-10-28 09:14 UTC, merged