{bio}[foss/2021a] n2v v0.3.2 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #16535
Opened 2022-11-03 14:11 UTC by ThomasHoffmann77

(created using `eb --new-pr`)

2022-12-01 14:14 UTC, branfosj requested changes

2022-12-02 08:29 UTC, ThomasHoffmann77 commented on easybuild/easyconfigs/n/n2v/n2v-0.3.2-foss-2021a-CUDA-11.3.1.eb
> +homepage = 'https://github.com/juglab/cryoCARE_pip'
@branfosj indeed. fixed it.

2022-12-02 11:04 UTC, branfosj approved these changes

2022-12-02 11:06 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0103u14a.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 1 x NVIDIA NVIDIA A30, 470.57.02, Python 3.6.8
See https://gist.github.com/909c92749c230ceac542bea7254f77aa for a full test report.

2022-12-02 11:12 UTC, branfosj commented
Going in, thanks @ThomasHoffmann77!

2022-12-02 11:12 UTC, merged