{chem}[intel-compilers/2022.1.0] NCIPLOT v4.2-20221021
easybuilders/easybuild-easyconfigs pull request #16608
Opened 2022-11-09 22:54 UTC by lexming

(created using `eb --new-pr`)

2022-11-09 23:14 UTC, lexming commented
@boegelbot: please test @ generoso

2023-02-21 23:19 UTC, lexming commented
@boegelbot please test @ jsc-zen2

2024-09-27 14:25 UTC, smoors approved these changes
lgtm

2024-09-27 14:27 UTC, smoors commented on easybuild/easyconfigs/n/NCIPLOT/NCIPLOT-4.2-20221021-intel-compilers-2022.1.0.eb
> +pretestopts += "find . -name runtests.sh -exec sed -i 's/nciplot_4.0/nciplot_%s/g' {} \; && " % _formal_version
```suggestion
pretestopts += r"find . -name runtests.sh -exec sed -i 's/nciplot_4.0/nciplot_%s/g' {} \; && " % _formal_version
```

2024-09-27 14:56 UTC, smoors commented
@boegelbot please test @ jsc-zen3

2024-09-27 17:08 UTC, smoors commented
@boegelbot: please test @ generoso

2024-10-04 17:52 UTC, smoors requested changes
lgtm

2024-10-04 17:52 UTC, smoors approved these changes

2024-10-04 17:53 UTC, smoors commented
Going in, thanks @lexming!

2024-10-04 17:53 UTC, merged