{tools}[GCCcore/11.3.0] Subversion v1.14.2
easybuilders/easybuild-easyconfigs pull request #16689
Opened 2022-11-21 09:28 UTC by SebastianAchilles

(created using `eb --new-pr`)

2022-11-21 09:37 UTC, SebastianAchilles commented
@boegelbot please test @ jsc-zen2

2022-11-30 19:51 UTC, branfosj submitted a review, later dismissed

2022-11-30 19:53 UTC, branfosj requested changes

2022-11-30 19:53 UTC, branfosj commented on easybuild/easyconfigs/s/Subversion/Subversion-1.14.2-GCCcore-11.3.0.eb
> +    ('utf8proc', '2.8.0'),
```suggestion
    ('utf8proc', '2.7.0'),
```

We have https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/u/utf8proc/utf8proc-2.7.0-GCCcore-11.3.0.eb

Or is there a need to use a newer version?

2023-07-01 16:00 UTC, branfosj commented
@boegelbot please test @ generoso

2023-07-01 16:01 UTC, branfosj commented
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0104u04b - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/3fda11edd3815720c430c9e473524ebe for a full test report.

2023-07-01 16:05 UTC, branfosj commented on easybuild/easyconfigs/s/Subversion/Subversion-1.14.2-GCCcore-11.3.0.eb
> +]
```suggestion
    ('util-linux', '2.38'),
]
```

2023-07-01 16:07 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0104u04b - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/a95a8fd2c4413dcbd72cce904455c8cb for a full test report.

2023-07-01 16:07 UTC, branfosj commented
@boegelbot please test @ jsc-zen2

2023-07-01 18:01 UTC, branfosj commented
@boegelbot please test @ generoso

2023-07-01 18:01 UTC, branfosj approved these changes

2023-07-01 18:13 UTC, branfosj commented
Going in, thanks @SebastianAchilles!

2023-07-01 18:13 UTC, merged