{geo}[foss/2022a] pysteps v1.7.1 w/ Python 3.10.4
easybuilders/easybuild-easyconfigs pull request #16783
Opened 2022-12-01 21:15 UTC by smoors

(created using `eb --new-pr`)

2022-12-01 21:59 UTC, smoors commented
@boegelbot: please test @ generoso

2022-12-01 22:06 UTC, smoors commented
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node300.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (skylake_avx512), Python 2.7.5
See https://gist.github.com/0e73838fc0ecc51b54a8d36c211befa2 for a full test report.

2022-12-03 22:26 UTC, boegel requested changes

2022-12-03 22:26 UTC, boegel commented on easybuild/easyconfigs/p/pysteps/pysteps-1.7.1-foss-2022a.eb
> +        'source_tmpl': '%(version)s.tar.gz',
@smoors Please rename on download, and use a better version (datestamp)

```suggestion
    ('pysteps-nwp-importers', '20220124', {
        'sources': [{'download_filename': '6ca1582.tar.gz', 'filename': SOURCE_TAR_GZ}],

2022-12-03 22:26 UTC, boegel commented on easybuild/easyconfigs/p/pysteps/pysteps-1.7.1-foss-2022a.eb
> +        'source_tmpl': 'v%(version)s.tar.gz',
@smoors Please rename on download

```suggestion
        'sources': [{'download_filename': 'v%(version)s.tar.gz', 'filename': SOURCE_TAR_GZ}],
```

2022-12-03 22:26 UTC, boegel commented on easybuild/easyconfigs/p/pysteps/pysteps-1.7.1-foss-2022a.eb
> +            {'v1.7.1.tar.gz': '5063d7546d9995ec6ca52a5b4e50ef3f3c1ae43088a55e370af4aec18162a22f'},
```suggestion
            {'pysteps-1.7.1.tar.gz': '5063d7546d9995ec6ca52a5b4e50ef3f3c1ae43088a55e370af4aec18162a22f'},

2022-12-05 07:42 UTC, smoors commented
@boegelbot: please test @ generoso

2022-12-06 19:58 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3103.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/5a58ff707ff31423614fd49c58fa030e for a full test report.

2022-12-07 10:29 UTC, boegel commented
Going in, thanks @smoors!

2022-12-07 10:29 UTC, merged