{lib,system,vis}[GCCcore/12.2.0] LibTIFF v4.4.0, jbigkit v2.1, libdeflate v1.14
easybuilders/easybuild-easyconfigs pull request #16827
Opened 2022-12-08 09:51 UTC by boegel

(created using `eb --new-pr`)

2022-12-08 09:56 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3104.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/7c3284df3f96693c21f46bc0d417d481 for a full test report.

2022-12-08 18:37 UTC, branfosj requested changes

2022-12-08 18:37 UTC, branfosj commented on easybuild/easyconfigs/l/libdeflate/libdeflate-1.14-GCCcore-12.2.0.eb
> +version = '1.14'
1.15: https://github.com/ebiggers/libdeflate/releases/tag/v1.15 ?

2022-12-08 18:37 UTC, branfosj commented on easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.4.0-GCCcore-12.2.0.eb
> +homepage = 'https://libtiff.maptools.org/'
This is not loading for me. How about https://libtiff.gitlab.io/libtiff/ instead?

2022-12-11 10:30 UTC, branfosj commented on easybuild/easyconfigs/l/libdeflate/libdeflate-1.14-GCCcore-12.2.0.eb
> +version = '1.14'
See https://github.com/boegel/easybuild-easyconfigs/pull/90

2022-12-11 10:30 UTC, branfosj commented on easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.4.0-GCCcore-12.2.0.eb
> +homepage = 'https://libtiff.maptools.org/'
See https://github.com/boegel/easybuild-easyconfigs/pull/90

2022-12-11 11:26 UTC, branfosj commented
@boegelbot please test @ jsc-zen2

2022-12-11 11:26 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/2cb27ead4861fa1066e1f55346698d14 for a full test report.

2022-12-11 11:26 UTC, branfosj commented
Test report by @branfosj
**FAILED**
Build succeeded for 1 out of 3 (3 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/3ef3a9a69a3d770d12d7079d2584543f for a full test report.

2022-12-11 11:28 UTC, branfosj commented on easybuild/easyconfigs/l/libdeflate/libdeflate-1.15-GCCcore-12.2.0.eb
> +builddependencies = [('binutils', '2.39')]
```suggestion
builddependencies = [
    ('binutils', '2.39'),
    ('CMake', '3.24.3'),
]
```

Sorry. My test system has `CMake` in the OS.

2022-12-11 11:30 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.5, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/5f7594c06b8c91707e696646d435c168 for a full test report.

2022-12-11 11:30 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/172e8f82d5e0fbe77943fb645ed9628e for a full test report.

2022-12-11 11:30 UTC, branfosj commented
@boegelbot please test @ jsc-zen2

2022-12-11 12:27 UTC, branfosj approved these changes

2022-12-11 12:28 UTC, merged