{bio}[foss/2018b] unblur v1.0.2
easybuilders/easybuild-easyconfigs pull request #16960
Opened 2022-12-20 17:55 UTC by garadar

(created using `eb --new-pr`)

2022-12-20 19:01 UTC, boegel requested changes

2022-12-20 19:01 UTC, boegel commented on easybuild/easyconfigs/u/unblur/unblur-1.0.2-foss-2018b.eb
> +toolchain = {'name': 'foss', 'version': '2018b'}
@garadar Toolchains older than `foss/2019a` have been deprecated for a while, see https://docs.easybuild.io/en/latest/Deprecated-easyconfigs.html#deprecated-toolchains 

Would it be feasible to use a more recent toolchain for this?

2022-12-22 10:28 UTC, garadar commented
I tried with a newer toolchain but the compilation does not work anymore.

I think we can abort, unblur is an academic tool with no update since a while. :(

2024-01-13 17:59 UTC, boegel commented
closing this since `foss/2019a` is no longer supported, see https://docs.easybuild.io/policies/toolchains

2024-01-13 17:59 UTC, closed without merging