{tools}[GCCcore/11.3.0] ccache v4.6.3
easybuilders/easybuild-easyconfigs pull request #17000
Opened 2022-12-22 11:56 UTC by iotaka

(created using `eb --new-pr`)

2022-12-23 12:15 UTC, smoors commented on easybuild/easyconfigs/c/ccache/ccache-4.6.3-GCCcore-11.3.0.eb
> +    ('pkg-config', '0.29.2'),
`pkg-config` is no longer maintained, so from `2022a` onward we prefer to use `pkgconf` where possible

2022-12-23 12:21 UTC, smoors requested changes

2022-12-23 12:21 UTC, smoors commented on easybuild/easyconfigs/c/ccache/ccache-4.6.3-GCCcore-11.3.0.eb
> +sanity_check_commands = ['ccache --help']
why did you remove the second sanity check command here? see ccache-4.6.3.eb

```
sanity_check_commands = [
    'ccache --help',
    # Ensure that the binary does not depend on any shared library
    'ldd $(which ccache) | grep -q "not a dynamic executable"',
]
```

2022-12-23 12:21 UTC, smoors commented on easybuild/easyconfigs/c/ccache/ccache-4.6.3-GCCcore-11.3.0.eb
> +configopts += '-DUSE_FASTER_LINKER=OFF'
there are some other configopts in ccache-4.6.3.eb that are missing here.
please add them back (or explain why they are no longer needed).

2022-12-27 11:52 UTC, iotaka commented
I did some tests
with `'-DCMAKE_EXE_LINKER_FLAGS="-static"'`,  not compiles
so also `'ldd $(which ccache) | grep -q "not a dynamic executable"'`  is not usable

2022-12-27 13:25 UTC, smoors commented
> I did some tests with `'-DCMAKE_EXE_LINKER_FLAGS="-static"'`, not compiles so also `'ldd $(which ccache) | grep -q "not a dynamic executable"'` is not usable

I just tested it and it works for me. maybe you made a mistake somewhere?

2022-12-27 13:35 UTC, smoors requested changes

2022-12-27 13:35 UTC, smoors commented on easybuild/easyconfigs/c/ccache/ccache-4.6.3-GCCcore-11.3.0.eb
> +    ('pkgconfig', '1.5.5', '-python'),
pkgconf is not the same as pkgconfig

```suggestion
    ('pkgconf', '1.8.0'),
```

2023-06-07 12:44 UTC, smoors commented
@boegelbot: please test @ generoso

2023-06-07 14:45 UTC, smoors approved these changes
lgtm

2023-06-07 14:46 UTC, merged