{bio}[GCC/10.3.0] kneaddata v0.10.0 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #17010
Opened 2022-12-23 11:31 UTC by garadar

(created using `eb --new-pr`)

2022-12-23 23:57 UTC, garadar commented
Error from last check:
> EasyBuildError: 'Missing dependencies: TRF/4.09.1-GCC-10.3.0 (no easyconfig file or existing module found)'

Waiting missing recipe of  TRF/4.09.1-GCC-10.3.0 : https://github.com/easybuilders/easybuild-easyconfigs/pull/17015

2022-12-27 10:21 UTC, smoors requested changes

2022-12-27 10:21 UTC, smoors commented on easybuild/easyconfigs/k/kneaddata/kneaddata-0.10.0-GCC-10.3.0.eb
> +    ('Java', '1.8.0_74', '', SYSTEM),
please specify only 1.8 as Java version
```suggestion
    ('Java', '1.8', '', SYSTEM),
```

2022-12-27 10:21 UTC, smoors commented on easybuild/easyconfigs/k/kneaddata/kneaddata-0.10.0-GCC-10.3.0.eb
> +    ('Java', '1.8.0_74', '', SYSTEM),
please specify only 1.8 as Java version
```suggestion
    ('Java', '1.8', '', SYSTEM),
```

2022-12-28 10:36 UTC, garadar commented
@boegel @smoors I don't understand what is blocking?

2023-01-09 16:52 UTC, jfgrimm requested changes
Hi @garadar, and thanks for your contribution!
I've left some suggestions; in addition to those already listed, we should probably consider adding the install option `--bypass-dependencies-install` to force disable the auto-installation of dependencies

2023-01-09 16:52 UTC, jfgrimm commented on easybuild/easyconfigs/k/kneaddata/kneaddata-0.10.0-GCC-10.3.0.eb
> +    ('FastQC', '0.11.5-Java-1.8.0_74', '', SYSTEM),
default Java version used in this toolchain generation is Java 11, so we should use those versions if possible:

```suggestion
    ('Java', '11', '', SYSTEM),
    ('Trimmomatic', '0.39', '-Java-%(javaver)s', SYSTEM),
    ('FastQC', '0.11.9', '-Java-%(javaver)s', SYSTEM),
```

2023-01-09 16:52 UTC, jfgrimm commented on easybuild/easyconfigs/k/kneaddata/kneaddata-0.10.0-GCC-10.3.0.eb
> +download_dep_fail = 'true'
lets move this down to be next to `use_pip`
```suggestion
```

2023-01-09 16:52 UTC, jfgrimm commented on easybuild/easyconfigs/k/kneaddata/kneaddata-0.10.0-GCC-10.3.0.eb
> +sanity_pip_check = 'true'
in Python. `True`/`False` are booleans, `'true'` is a string
```suggestion
use_pip = True
download_dep_fail = True
sanity_pip_check = True
```

2023-01-09 16:52 UTC, jfgrimm commented on easybuild/easyconfigs/k/kneaddata/kneaddata-0.10.0-GCC-10.3.0.eb
> +#  source_urls = [PYPI_SOURCE]
not sure why this is commented out
```suggestion
source_urls = [PYPI_SOURCE]
```

2023-01-09 17:18 UTC, jfgrimm commented on easybuild/easyconfigs/k/kneaddata/kneaddata-0.10.0-GCC-10.3.0.eb
> +source_urls = [PYPI_SOURCE]
oh right, it's not actually needed since it's the default. In that case, it should simply be removed

```suggestion
```

2023-01-09 17:20 UTC, garadar commented on easybuild/easyconfigs/k/kneaddata/kneaddata-0.10.0-GCC-10.3.0.eb
> +#  source_urls = [PYPI_SOURCE]
I removed it :)

2023-01-09 17:23 UTC, jfgrimm commented
@garadar I've synced this branch with the latest `develop`, to fix some CI test failures unrelated to this PR

2023-01-18 11:14 UTC, verdurin commented
@garadar @jfgrimm is this one ready for final review now?

2023-01-18 11:17 UTC, garadar commented
> is this one ready for final review now?

I think yes

2025-05-09 11:09 UTC, akesandgren commented
Closing this since GCC(core)/10.3.0 foss/2021a is deprecated, see https://docs.easybuild.io/policies/toolchains

Sorry for not getting back to this @garadar 

If this is still relevant, please consider opening a new pull request using a more recent toolchain

2025-05-09 11:09 UTC, closed without merging