{data}[GCCcore/10.2.0,GCCcore/11.3.0] UDA v2.6.0
easybuilders/easybuild-easyconfigs pull request #17052
Opened 2023-01-05 08:27 UTC by SimonPinches

(created using `eb --new-pr`)

2023-01-12 13:21 UTC, jfgrimm requested changes
I would suggest removing the `GCCcore`-level `Boost` easyconfigs you're adding, and instead using the `GCC`-level ones we already have in the repository. This will require bumping `UDA` to `GCC` (note that the filenames should be changed to match)

2023-01-12 13:21 UTC, jfgrimm commented on easybuild/easyconfigs/u/UDA/UDA-2.6.0-GCCcore-10.2.0.eb
> +osdependencies = [('openssl-devel', 'libssl-dev', 'libopenssl-devel')]
we can use the `OpenSSL` wrapper module for this:

```suggestion
    ('OpenSSL', '1.1', '', SYSTEM),
]
```

2023-01-12 13:21 UTC, jfgrimm commented on easybuild/easyconfigs/u/UDA/UDA-2.6.0-GCCcore-11.3.0.eb
> +# osdependencies = [('openssl-devel', 'libssl-dev', 'libopenssl-devel')]
we can use the `OpenSSL` wrapper module for this:

```suggestion
    ('OpenSSL', '1.1', '', SYSTEM),
]
```

2023-01-12 13:21 UTC, jfgrimm commented on easybuild/easyconfigs/u/UDA/UDA-2.6.0-GCCcore-11.3.0.eb
> +    ('Boost', '1.79.0', '-no_mpi'),
we already build `Boost` with the tagged layout, no need to introduce a `-no_mpi` variant
```suggestion
    ('Boost', '1.79.0'),
```

2023-01-12 13:21 UTC, jfgrimm commented on easybuild/easyconfigs/u/UDA/UDA-2.6.0-GCCcore-11.3.0.eb
> +toolchain = {'name': 'GCCcore', 'version': '11.3.0'}
we already have `Boost` at `GCC` level, so we should really use that (and bump this easyconfig to `GCC`)
```suggestion
toolchain = {'name': 'GCC', 'version': '11.3.0'}
```

2023-01-12 13:21 UTC, jfgrimm commented on easybuild/easyconfigs/u/UDA/UDA-2.6.0-GCCcore-10.2.0.eb
> +toolchain = {'name': 'GCCcore', 'version': '10.2.0'}
we already have `Boost` at `GCC` level, so we should really use that (and bump this easyconfig to `GCC`)
```suggestion
toolchain = {'name': 'GCC', 'version': '10.2.0'}
```

2024-01-14 09:10 UTC, boegel commented
closing this since `GCC/10.2.0` is deprecated, see https://docs.easybuild.io/policies/toolchains

@SimonPinches If `UDA` is still relevant, please consider opening a new pull with a more recent toolchain

2024-01-14 09:10 UTC, closed without merging