Graphviz v7.0.6 and dependencies for GCCcore/12.2.0
easybuilders/easybuild-easyconfigs pull request #17124
Opened 2023-01-16 18:51 UTC by SimonPinches

(created using `eb --new-pr`)

2023-01-17 08:22 UTC, Mohammedalanizi92 requested changes
simonpinches:20230116195116_new_pr_Graphviz706

2023-01-17 08:23 UTC, Mohammedalanizi92 reviewed
simonpinches:20230116195116_new_pr_Graphviz706

2023-01-17 11:11 UTC, verdurin commented
@SimonPinches could you close #17119 if you're using this one instead?
Thanks.

2023-01-20 10:51 UTC, verdurin requested changes

2023-01-20 10:51 UTC, verdurin commented on easybuild/easyconfigs/s/SWIG/SWIG-4.1.1-GCCcore-12.2.0.eb
> +    ('PCRE', '8.45'),
@SimonPinches looks like a missing dependency on `PCRE2`.

2023-04-27 12:58 UTC, SimonPinches commented
Depends upon PR #17089

2023-06-14 23:40 UTC, fizwit commented on easybuild/easyconfigs/l/librsvg/librsvg-2.56.0-GCCcore-12.2.0.eb
missing pkgconfig
```
builddependencies = [
    ('binutils', '2.39'),
    ('pkgconfig', '1.5.5', '-python'),
    ('Rust', '1.65.0'),
]
```

2025-06-16 15:08 UTC, sassy-crick commented
@SimonPinches You might want to sync your PR with development, something like this: 
```
eb --sync-pr-with-develop NUMBER_OF_PR
```
Also, we already have `Graphviz-8.1.0-GCCcore-12.2.0.eb` merged in `EasyBuild-5.1.0`. Do we need this older version?

2025-06-16 16:25 UTC, SimonPinches commented
I think we can drop this old PR from 2.5 years ago.

2025-06-16 16:25 UTC, closed without merging