add extensions to Python 3.10.8
easybuilders/easybuild-easyconfigs pull request #17159
Opened 2023-01-19 14:42 UTC by jfgrimm

(created using `eb --new-pr`)

2023-01-19 16:23 UTC, jfgrimm commented
@boegelbot please test @ generoso
EB_ARGS="--skip"

2023-01-19 18:20 UTC, boegel requested changes

2023-01-19 18:20 UTC, boegel commented on easybuild/easyconfigs/p/Python/Python-3.10.8-GCCcore-12.2.0.eb
> +        'source_tmpl': '%(name)s-%(version)s-py3-none-any.whl',
please stick to using `SOURCE_PY3_WHL` and `SOURCE_WHL` (see above) - also a side-effect of using `--inject-checksums` which we haven't fixed yet...

2023-01-20 21:22 UTC, boegel approved these changes
lgtm

2023-01-20 21:23 UTC, boegel commented
@boegelbot please test @ jsc-zen2
EB_ARGS="--skip"

2023-01-20 21:59 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3102.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/2e3811eb47ce5fe9eda993ff7ccd6463 for a full test report.

2023-01-22 08:24 UTC, boegel commented
Going in, thanks @jfgrimm!

2023-01-22 08:24 UTC, merged