{data}[foss/2021b] NCL v6.6.2
easybuilders/easybuild-easyconfigs pull request #17173
Opened 2023-01-20 16:21 UTC by lexming

(created using `eb --new-pr`)

2023-01-27 12:36 UTC, verdurin requested changes

2023-01-27 12:36 UTC, verdurin commented on easybuild/easyconfigs/n/NCL/NCL-6.6.2-foss-2021b.eb
> +    ('makedepend', '1.0.6'),
@lexming this is actually at `GCCcore`, not `foss`

2023-01-27 12:36 UTC, verdurin commented on easybuild/easyconfigs/n/NCL/NCL-6.6.2-foss-2021b.eb
> +    ('g2lib', '3.2.0'),
Same as above.

2023-07-07 23:30 UTC, closed without merging

2023-07-08 10:56 UTC, boegel commented
@lexming Can you clarify why you closed this?