{numlib}[foss/2022b] Armadillo v11.4.3, arpack-ng v3.8.0
easybuilders/easybuild-easyconfigs pull request #17190
Opened 2023-01-24 12:27 UTC by jfgrimm

(created using `eb --new-pr`)

2023-01-24 16:25 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
himem06.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/4b2bf525db7ab3715a824d127b2166ea for a full test report.

2023-02-28 08:37 UTC, boegel commented
@boegelbot please test @ generoso

2023-02-28 08:40 UTC, boegel requested changes

2023-02-28 08:40 UTC, boegel commented on easybuild/easyconfigs/a/Armadillo/Armadillo-11.4.3-foss-2022b.eb
> +homepage = 'http://arma.sourceforge.net/'
I don't see a reason to not use `https` here?

2023-02-28 08:53 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3121.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/2672787c9f4b6d179bf39c6850ac0114 for a full test report.

2023-02-28 08:57 UTC, boegel commented on easybuild/easyconfigs/a/Armadillo/Armadillo-11.4.3-foss-2022b.eb
> +homepage = 'http://arma.sourceforge.net/'
fixed with [1242e25](https://github.com/easybuilders/easybuild-easyconfigs/pull/17190/commits/1242e25ff7f0d415a9b0aa39542f7f59c8b0566d)

2023-02-28 13:01 UTC, boegel approved these changes
lgtm

2023-02-28 13:02 UTC, merged