{perf}[GCC/11.3.0] kineto v0.4.0
easybuilders/easybuild-easyconfigs pull request #17194
Opened 2023-01-24 13:43 UTC by boegel

(created using `eb --new-pr`)

2023-01-24 14:21 UTC, boegel commented
@boegelbot please test @ generoso

2023-01-24 14:26 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2023-01-24 14:27 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3161.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/83c490b5141b20295a7710de2a6a9f0b for a full test report.

2023-01-27 08:21 UTC, terjekv commented
Test report by @terjekv
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
ninhursaga.uio.no - Linux RHEL 9.1 (Plow), x86_64, Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz, 1 x NVIDIA Tesla T4, 525.60.13, Python 3.9.14
See https://gist.github.com/5349bba7168386b95bd8b9c02c703b8a for a full test report.

2023-01-28 10:43 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0211u08b.bear.cluster - Linux Ubuntu 20.04.2 LTS (Focal Fossa), x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.8.5
See https://gist.github.com/169f212075ab26da27d65fc9e2ffe63a for a full test report.

2023-01-28 10:44 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/931dd833ac7e8efbab0ad332a09e57dd for a full test report.

2023-01-28 10:48 UTC, branfosj requested changes

2023-01-28 10:48 UTC, branfosj commented on easybuild/easyconfigs/k/kineto/kineto-0.4.0-GCC-11.3.0.eb
> +]
```suggestion
    ('Python', '3.10.4', '-bare'),
]
```

From the buildlog
```
-- Found PythonInterp: /rds/projects/2017/branfosj-rse/easybuild/venv-dev-Ubuntu20.04/bin/python (found version "3.8.5")
```

And we see that used at https://github.com/pytorch/kineto/blob/main/libkineto/CMakeLists.txt#L14

2023-01-31 20:05 UTC, boegel commented
@boegelbot please test @ generoso

2023-01-31 20:08 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/01e1cb456a55bf55028d02270509bbf2 for a full test report.

2023-01-31 20:09 UTC, branfosj approved these changes

2023-01-31 20:25 UTC, branfosj commented
Going in, thanks @boegel!

2023-01-31 20:25 UTC, merged