enhance OpenFold for standalone usage
easybuilders/easybuild-easyconfigs pull request #17206
Opened 2023-01-25 16:35 UTC by smoors

(created using `eb --new-pr`)

2023-01-25 18:21 UTC, smoors commented
Test report by @smoors
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node403.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7282 16-Core Processor, 1 x NVIDIA NVIDIA A100-PCIE-40GB, 515.48.07, Python 3.6.8
See https://gist.github.com/c58dcac88d4b98313fdef787892777cc for a full test report.

2023-01-26 09:11 UTC, smoors commented
Test report by @smoors
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
node401.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7282 16-Core Processor, 1 x NVIDIA NVIDIA A100-PCIE-40GB, 515.48.07, Python 3.6.8
See https://gist.github.com/96789d13fb37aa818490f510f3e77154 for a full test report.

2023-01-26 12:08 UTC, smoors commented
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node250.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, 1 x NVIDIA Tesla P100-PCIE-16GB, 515.48.07, Python 3.6.8
See https://gist.github.com/b2cb36120e24aa4406441e098852ad78 for a full test report.

2023-01-26 13:58 UTC, smoors commented
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node403.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7282 16-Core Processor, 1 x NVIDIA NVIDIA A100-PCIE-40GB, 515.48.07, Python 3.6.8
See https://gist.github.com/1d33f0f7113504ce2efa430d02967f1b for a full test report.

2023-01-26 14:05 UTC, smoors commented
the failing OpenCL tests for OpenMM were due to NVIDIA MPS service being run.
without MPS, all tests passed.

2023-01-26 20:08 UTC, boegel requested changes

2023-01-27 08:24 UTC, smoors commented on easybuild/easyconfigs/o/OpenFold/OpenFold-1.0.1-foss-2021a-CUDA-11.3.1.eb
> +    'PYTHONPATH': '',
indeed, `run_pretrained_openfold.py` imports modules in the scripts directory, e.g.
```
from scripts.utils import add_data_args
```

2023-01-27 08:26 UTC, smoors commented on easybuild/easyconfigs/o/OpenFold/OpenFold-1.0.1-foss-2021a-CUDA-11.3.1.eb
> +    ('flash_attn', '0.2.8', {
it's an optional dependency that should greatly speed up some parts of the calculation (see FlashAttention in the readme)

2023-01-27 08:30 UTC, smoors commented on easybuild/easyconfigs/o/OpenFold/OpenFold-1.0.1-foss-2021a-CUDA-11.3.1.eb
> +    'PYTHONPATH': '',
we could move the scripts directory into the bin directory, that may be safer?

2023-01-27 08:40 UTC, smoors commented on easybuild/easyconfigs/o/OpenFold/OpenFold-1.0.1-foss-2021a-CUDA-11.3.1.eb
> +    'PYTHONPATH': '',
I'll move the scripts directory inside bin

2023-01-27 08:56 UTC, smoors commented on easybuild/easyconfigs/o/OpenFold/OpenFold-1.0.1-foss-2021a-CUDA-11.3.1.eb
> +    ('flash_attn', '0.2.8', {
I'll add a comment

2023-01-27 11:14 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (2 easyconfigs in total)
node3300.joltik.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 525.60.13, Python 3.6.8
See https://gist.github.com/77eb148d490614e8b2d9ad9d4660d480 for a full test report.

2023-01-27 22:08 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
node3906.accelgor.os - Linux RHEL 8.6, x86_64, AMD EPYC 7413 24-Core Processor (zen3), 1 x NVIDIA [Unknown Error], 525.60.13, Python 3.6.8
See https://gist.github.com/6494cdb2f4575fbed47f157f36b8c9b8 for a full test report.

2023-01-27 23:05 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3307.joltik.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 525.60.13, Python 3.6.8
See https://gist.github.com/1efeac918a1f21c4e224f61f027db355 for a full test report.

2023-01-27 23:06 UTC, boegel approved these changes

2023-01-27 23:58 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3903.accelgor.os - Linux RHEL 8.6, x86_64, AMD EPYC 7413 24-Core Processor (zen3), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 525.60.13, Python 3.6.8
See https://gist.github.com/646bb0b17baa97e4800d20087f497941 for a full test report.

2023-01-28 08:17 UTC, boegel commented
Going in, thanks @smoors!

2023-01-28 08:17 UTC, merged