{bio}[foss/2022a] Giotto-Suite v3.0.1 w/ Python 3.10.4
easybuilders/easybuild-easyconfigs pull request #17207
Opened 2023-01-26 10:49 UTC by stevenvdb

(created using `eb --new-pr`)

2023-01-26 17:58 UTC, jfgrimm commented
Test report by @jfgrimm
**FAILED**
Build succeeded for 8 out of 16 (5 easyconfigs in total)
himem06.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/478519f30a177d807ec6a213ba8e765e for a full test report.

2023-01-27 10:04 UTC, stevenvdb commented
> Test report by @jfgrimm **FAILED** Build succeeded for 8 out of 16 (5 easyconfigs in total) himem06.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8 See https://gist.github.com/478519f30a177d807ec6a213ba8e765e for a full test report.

I don't really understand what to do about these build failures. The first one that fails is `Seaborn-0.12.1-foss-2022a.eb`, which is an easyconfig that is not part of this PR but is already in the develop branch. The failure is because the `pandas` package is not installed, but this is provided by `SciPy-bundle/2022.05-foss-2022a` which is a indirect dependency of Seaborn through `matplotlib/3.5.2-foss-2022a`. So I am not sure what I can do to make these tests to pass.

2023-01-27 11:03 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 9 out of 9 (5 easyconfigs in total)
himem06.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/fe61368b4c0e03ec7b3edff06e1e99dd for a full test report.

2023-01-27 11:16 UTC, jfgrimm commented
> > Test report by @jfgrimm **FAILED** Build succeeded for 8 out of 16 (5 easyconfigs in total) himem06.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz (skylake_avx512), Python 3.6.8 See https://gist.github.com/478519f30a177d807ec6a213ba8e765e for a full test report.
> 
> I don't really understand what to do about these build failures. The first one that fails is `Seaborn-0.12.1-foss-2022a.eb`, which is an easyconfig that is not part of this PR but is already in the develop branch. The failure is because the `pandas` package is not installed, but this is provided by `SciPy-bundle/2022.05-foss-2022a` which is a indirect dependency of Seaborn through `matplotlib/3.5.2-foss-2022a`. So I am not sure what I can do to make these tests to pass.

ah my mistake, I've been working on updating the scipy easyblock and in the process broke my 2022a SciPy-bundle module. Forgot to remove it before testing the PR

2023-01-27 11:16 UTC, jfgrimm commented
@boegelbot please test @ generoso

2023-02-28 23:04 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 13 out of 13 (5 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/bd6acbed9173ff980d45716a21b538dc for a full test report.

2023-03-18 18:00 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2023-03-18 19:40 UTC, boegel requested changes

2023-03-18 19:40 UTC, boegel commented on easybuild/easyconfigs/s/smfishHmrf/smfishHmrf-1.3.3-foss-2022a.eb
> +    ('Java', '11.0.16', '', SYSTEM),
We should use the `Java/11` wrapper here:

```suggestion
    ('Java', '11', '', SYSTEM),

2023-03-18 19:40 UTC, boegel commented on easybuild/easyconfigs/s/smfishHmrf/smfishHmrf-1.3.3-foss-2022a.eb
> +    ('Java', '11.0.16', '', SYSTEM),
I'll apply this change, so we can get this PR merged...

2023-03-18 19:57 UTC, boegel approved these changes

2023-03-18 20:40 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3118.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/a8e41f79de6749315dddf3ddf13db1cb for a full test report.

2023-03-18 20:41 UTC, boegel commented
Going in, thanks @stevenvdb!

2023-03-18 20:41 UTC, merged