{lib}[GCCcore/11.2.0,foss/2021b,system/system] PyTorch v1.12.1, NCCL v2.10.3, UCX-CUDA v1.11.2, ... w/ Python 3.9.6
easybuilders/easybuild-easyconfigs pull request #17272
Opened 2023-02-07 14:00 UTC by Flamefire

(created using `eb --new-pr`)

2023-02-07 22:44 UTC, Flamefire commented
Test report by @Flamefire
**FAILED**
Build succeeded for 5 out of 6 (6 easyconfigs in total)
taurusi8009 - Linux CentOS Linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 470.57.02, Python 2.7.5
See https://gist.github.com/fa363fc83c2f8fd9267eaddad8b20a1b for a full test report.

2023-02-08 21:44 UTC, Flamefire commented
Test report by @Flamefire
**FAILED**
Build succeeded for 2 out of 6 (6 easyconfigs in total)
taurusml24 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/52599c7ab88241e559b71f2b6bbe9663 for a full test report.

2023-02-09 23:33 UTC, Flamefire commented
Test report by @Flamefire
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
taurusa12 - Linux CentOS Linux 7.7.1908, x86_64, Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz (broadwell), 3 x NVIDIA GeForce GTX 1080 Ti, 460.32.03, Python 2.7.5
See https://gist.github.com/e3cabd5668e5c2ecf4b35a8e4a80112c for a full test report.

2023-02-10 16:16 UTC, branfosj commented
Test report by @branfosj
**FAILED**
Build succeeded for 5 out of 6 (6 easyconfigs in total)
bear-pg0103u14a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 2 x NVIDIA NVIDIA A30, 520.61.05, Python 3.6.8
See https://gist.github.com/7c637f039ff49f68749755c511119bd5 for a full test report.

2023-02-10 16:33 UTC, Flamefire commented
@branfosj I added a skip for that failing test similar to that in PyTorch 1.12 for CUDA 11.7

2023-02-10 20:42 UTC, Flamefire commented
Test report by @Flamefire
**FAILED**
Build succeeded for 5 out of 6 (6 easyconfigs in total)
taurusml5 - Linux RHEL 7.6, POWER, 8335-GTX (power9le), 6 x NVIDIA Tesla V100-SXM2-32GB, 440.64.00, Python 2.7.5
See https://gist.github.com/c81d75ad4be0502437217823c4609154 for a full test report.

2023-02-10 22:03 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (6 easyconfigs in total)
bear-pg0103u14a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 2 x NVIDIA NVIDIA A30, 520.61.05, Python 3.6.8
See https://gist.github.com/139b292b01bb3b2a4eb61cccca13003b for a full test report.

2023-02-11 08:20 UTC, branfosj commented
Test report by @branfosj
**FAILED**
Build succeeded for 81 out of 82 (6 easyconfigs in total)
bear-pg0212u17a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (broadwell), 1 x NVIDIA Tesla P100-PCIE-16GB, 520.61.05, Python 3.6.8
See https://gist.github.com/595fb693836512854f8aa6ec3b42a8a3 for a full test report.

2023-03-17 16:43 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
gcn5.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 1 x NVIDIA NVIDIA A100-SXM4-40GB, 515.86.01, Python 3.6.8
See https://gist.github.com/f337586642709534ed2c3b087594a63b for a full test report.

2023-03-18 01:05 UTC, casparvl commented
It would be nice to get this merged... @branfosj @Flamefire I see two remaining test failures in your test reports. Any chance you can investigate? Do we know if these are just flaky test results, or do they point to 'real' issues? If it's only a flaky test, maybe we can just add skips for them. Or we just merge it 'as is' - an easyconfig that works for everything except one test failure, is still better than not having any EasyConfig at all. And we're taking way too long to get this PyTorch stuff merged... :(

2023-03-18 10:31 UTC, Flamefire commented
> It would be nice to get this merged... @branfosj @Flamefire I see two remaining test failures in your test reports. Any chance you can investigate? Do we know if these are just flaky test results, or do they point to 'real' issues?

Sorry not right now or in the next ~8-10 weeks.

Feel free to merge this but create an issue to investigate this assigning me so I can look at it when I'm back.

2023-03-28 14:53 UTC, branfosj commented on easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2021b-CUDA-11.5.2.eb
> +    ]
```suggestion
        # failing on broadwell
        'test_native_mha'
    ]
```

2023-03-28 14:55 UTC, casparvl commented
Discussed on Slack with @branfosj. Proposed action:
Disable `distributed/fsdp/test_fsdp_core` and `test_native_mha`, and create at issues for each.

2023-03-28 15:03 UTC, casparvl requested changes

2023-03-28 15:03 UTC, casparvl commented on easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2021b-CUDA-11.5.2.eb
> +        'distributed/fsdp/test_fsdp_mixed_precision',
```suggestion
        'distributed/fsdp/test_fsdp_mixed_precision',
        # Produces a single failure on some systems
        # See https://github.com/easybuilders/easybuild-easyconfigs/issues/17615
        'distributed/fsdp/test_fsdp_core',
```

2023-03-28 15:03 UTC, casparvl commented on easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2021b-CUDA-11.5.2.eb
> +        # failing on broadwell
```suggestion
        # failing on broadwell
        # See https://github.com/easybuilders/easybuild-easyconfigs/issues/17615
```

2023-03-28 15:07 UTC, casparvl commented
@boegelbot please test @ jsc-zen2

2023-03-28 19:58 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
bear-pg0103u11a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 1 x NVIDIA NVIDIA A100-PCIE-40GB, 520.61.05, Python 3.6.8
See https://gist.github.com/branfosj/def32bc7b2a6d3b439c6bfd722ab066a for a full test report.

2023-03-28 21:10 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 19 out of 19 (6 easyconfigs in total)
gcn50.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 1 x NVIDIA NVIDIA A100-SXM4-40GB, 515.86.01, Python 3.6.8
See https://gist.github.com/casparvl/92ffdef5e61765630592c1b2c059cee0 for a full test report.

2023-03-29 07:45 UTC, branfosj approved these changes

2023-03-29 13:56 UTC, casparvl commented
Going in, thanks @Flamefire!

2023-03-29 13:56 UTC, casparvl commented
Going in, thanks @Flamefire!

2023-03-29 13:57 UTC, merged

2023-03-30 01:41 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 5 out of 6 (6 easyconfigs in total)
node3900.accelgor.os - Linux RHEL 8.6, x86_64, AMD EPYC 7413 24-Core Processor (zen3), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 525.85.12, Python 3.6.8
See https://gist.github.com/boegel/202f911923ab0613c6d759e9cee84acb for a full test report.