{phys}[GCC/11.3.0] HepMC3 v3.2.5 w/ Python 3.10.4
easybuilders/easybuild-easyconfigs pull request #17341
Opened 2023-02-15 15:37 UTC by APN-Pucky

(created using `eb --new-pr`)

2023-02-15 21:01 UTC, APN-Pucky commented
@boegelbot: please test @ generoso

2023-02-15 21:53 UTC, jfgrimm commented
@boegelbot: please test @ generoso

2023-02-17 15:44 UTC, jfgrimm requested changes

2023-02-17 15:44 UTC, jfgrimm commented on easybuild/easyconfigs/h/HepMC3/HepMC3-3.2.5-GCC-11.3.0.eb
> +    'files': ["lib/libHepMC3.so"],
nitpick: please use `SHLIB_EXT` to avoid hardcoding `.so`
```suggestion
    'files': ['lib/libHepMC3.%s' % SHLIB_EXT],
```

2023-02-17 15:47 UTC, jfgrimm commented
Test report by @jfgrimm
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node067.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/225ecd80871c8facd0c45e69b2483506 for a full test report.

2023-02-17 15:48 UTC, jfgrimm commented
ooh, it's trying to install to the main `Python` installdir:
```
6961 CMake Error at python/cmake_install.cmake:60 (file):                                                                    
6962   file cannot create directory:                                                                                         
6963   /opt/apps/easybuild/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/pyHepMC3.                      
6964   Maybe need administrative privileges.
```

2023-02-17 15:49 UTC, APN-Pucky commented
> ooh, it's trying to install to the main `Python` installdir:
> 
> ```
> 6961 CMake Error at python/cmake_install.cmake:60 (file):                                                                    
> 6962   file cannot create directory:                                                                                         
> 6963   /opt/apps/easybuild/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/site-packages/pyHepMC3.                      
> 6964   Maybe need administrative privileges.
> ```

Huu, I did not notice that. I'll check if there is some parameter for that. In the worst case the python bindings can be dropped.

2023-02-17 16:00 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node067.pri.viking.alces.network - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6138 CPU @ 2.00GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/659244110953b8d863d316557964f221 for a full test report.

2023-02-17 16:20 UTC, jfgrimm commented
@boegelbot: please test @ jsc-zen2

2023-02-17 16:37 UTC, jfgrimm commented
@boegelbot please test @ generoso

2023-02-17 16:45 UTC, jfgrimm approved these changes
lgtm

2023-02-17 16:45 UTC, jfgrimm commented
Going in, thanks @APN-Pucky!

2023-02-17 16:45 UTC, merged