{phys}[gompi/2022a] fastjet-contrib v1.049
easybuilders/easybuild-easyconfigs pull request #17377
Opened 2023-02-21 10:18 UTC by APN-Pucky

(created using `eb --new-pr`)

2023-02-27 17:25 UTC, verdurin commented
@boegelbot please test @ jsc-zen2

2023-02-27 17:26 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/99506f0dda630f6be95499fa0c75c4d2 for a full test report.

2023-02-27 17:28 UTC, verdurin requested changes

2023-02-27 17:28 UTC, verdurin commented on easybuild/easyconfigs/f/fastjet-contrib/fastjet-contrib-1.049-gompi-2022a.eb
> +configopts = ""
@APN-Pucky could this be removed?

2023-02-27 18:08 UTC, APN-Pucky commented on easybuild/easyconfigs/f/fastjet-contrib/fastjet-contrib-1.049-gompi-2022a.eb
> +configopts = ""
Yes just checked that.

2023-02-28 17:05 UTC, verdurin commented on easybuild/easyconfigs/f/fastjet-contrib/fastjet-contrib-1.049-gompi-2022a.eb
> +configopts = ""
Thanks.

2023-02-28 17:06 UTC, verdurin approved these changes
Looks fine.

2023-02-28 17:06 UTC, verdurin commented
@boegelbot please test @ generoso

2023-02-28 17:07 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/81b63d1178d59082587d786d49d07727 for a full test report.

2023-02-28 17:13 UTC, verdurin commented
Going in, thanks @APN-Pucky!

2023-02-28 17:13 UTC, merged