Fix for obsolete pycrypto on Python 3.10
easybuilders/easybuild-easyconfigs pull request #17412
Opened 2023-02-23 13:08 UTC by surak

(created using `eb --new-pr`)

2023-02-24 08:30 UTC, SebastianAchilles commented
@boegelbot please test @ jsc-zen2
CORE_CNT=16
EB_ARGS="--installpath /tmp/$USER/pr17412"

2023-02-24 09:36 UTC, SebastianAchilles commented
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="--installpath /tmp/$USER/pr17412"

2023-02-24 10:06 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bwd-rockylinux-91 - Linux Rocky Linux 9.1 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 525.60.13, Python 3.9.14
See https://gist.github.com/d8d1af9692654248d00668cebdac2a2b for a full test report.

2023-02-24 10:13 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
skl-rockylinux-87 - Linux Rocky Linux 8.7, x86_64, Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (skylake), 1 x NVIDIA NVIDIA RTX A4000, 525.85.12, Python 3.6.8
See https://gist.github.com/07a8626e79b04a3a70057afca9b09dad for a full test report.

2023-02-24 10:17 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
skl-opensuse-154 - Linux openSUSE Leap 15.4, x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.6.15
See https://gist.github.com/0fb446e254e40524e98a2b3477a4fc37 for a full test report.

2023-02-24 10:22 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
zen2-ubuntu-2210 - Linux Ubuntu 22.10 (Kinetic Kudu), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.10.7
See https://gist.github.com/fd1463ef72c9df3c05714ff4d17ec2b0 for a full test report.

2023-02-25 17:49 UTC, boegel requested changes

2023-02-25 17:49 UTC, boegel commented on easybuild/easyconfigs/p/Python/Python-3.10.4-GCCcore-11.3.0.eb
>          'modulename': 'Crypto',
We should also use `Crypto.PublicKey.RSA` here to catch the broken `pycrypto`?

2023-02-25 18:04 UTC, boegel commented on easybuild/easyconfigs/p/Python/Python-3.10.4-GCCcore-11.3.0.eb
>          'modulename': 'Crypto',
fixed in 545a571c1a

2023-02-25 18:06 UTC, boegel commented
@boegelbot please test @ generoso
EB_ARGS="--skip"

2023-02-25 21:11 UTC, Micket commented
@boegelbot please test @ jsc-zen2
EB_ARGS="--skip"

2023-02-25 23:20 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3121.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/5193cd10c54dd40d3470d705d691196a for a full test report.

2023-02-25 23:25 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 6 out of 6 (2 easyconfigs in total)
vera-c2 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/dbe9ed8bfe4a98c15703620c40284583 for a full test report.

2023-02-26 08:20 UTC, boegel approved these changes

2023-02-26 08:20 UTC, boegel commented
Going in, thanks @surak!

2023-02-26 08:20 UTC, merged

2023-06-26 16:46 UTC, smoors commented
@boegelbot: please test @ generoso

2023-06-26 18:57 UTC, branfosj commented
@boegelbot please test @ jsc-zen2