{numlib}[foss/2022a] Trilinos v13.4.1 w/ Python 3.10.4
easybuilders/easybuild-easyconfigs pull request #17448
Opened 2023-03-01 13:49 UTC by branfosj

(created using `eb --new-pr`)

2023-03-01 14:33 UTC, branfosj commented
Test report by @branfosj
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2900
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0104u07a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/c4ab5698058b6910c76557fa6a57928b for a full test report.

2023-03-01 20:06 UTC, boegel commented
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="--include-easyblocks-from-pr 2900"

2023-03-02 15:23 UTC, boegel commented
@boegelbot please test @ jsc-zen2
CORE_CNT=16
EB_ARGS="--include-easyblocks-from-pr 2900"

2023-03-02 16:17 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2900
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node3118.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/ead5b463613c4886516e2f6ca71aba59 for a full test report.

2023-03-02 20:33 UTC, boegel requested changes
lgtm

2023-03-02 20:33 UTC, boegel commented on easybuild/easyconfigs/t/Trilinos/Trilinos-13.4.1-foss-2022a.eb
> +sources = ['trilinos-release-13-4-1.tar.gz']
@branfosj We should probably avoid the hardcoded version here?

```suggestion
sources = ['trilinos-release-%star.gz' % '-'.join(version.split('.'))]

2023-03-02 22:41 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2900
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3518.doduo.os - Linux RHEL 8.6, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/67327e4ea7bc7116c0c3571c946a8f7f for a full test report.

2023-03-03 10:44 UTC, verdurin commented
Test report by @verdurin
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/2900
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/419e0750cd24b359f9e7bef8d07b0121 for a full test report.

2023-03-03 12:03 UTC, verdurin commented
@boegel are you happy with this one now?

2023-03-03 15:38 UTC, boegel commented
Going in, thanks @branfosj!

2023-03-03 15:38 UTC, merged