{cae}[system/system] ABAQUS v2023
easybuilders/easybuild-easyconfigs pull request #17509
Opened 2023-03-13 08:33 UTC by boegel

(created using `eb --new-pr`)

2023-03-13 08:36 UTC, branfosj requested changes

2023-03-13 08:36 UTC, branfosj commented on easybuild/easyconfigs/a/ABAQUS/ABAQUS-2023.eb
> +
Please add `download_instructions` to this.

2025-05-06 07:15 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3611.doduo.os - Linux RHEL 9.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.9.18
See https://gist.github.com/boegel/ea4a9679065f3ce665b3cb5617c03c96 for a full test report.

2025-05-06 07:26 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
node3611.doduo.os - Linux RHEL 9.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.9.18
See https://gist.github.com/boegel/dc97fee4b99199ecd0c8bf075a45e83b for a full test report.

2025-05-06 08:53 UTC, boegel commented on easybuild/easyconfigs/a/ABAQUS/ABAQUS-2023.eb
> +
done in 10d3687

2025-05-06 09:38 UTC, laraPPr approved these changes
lgtm

2025-05-06 09:58 UTC, merged