{bio}[foss/2022a] genomepy v0.15.0, qnorm v0.8.1 w/ Python 3.10.4
easybuilders/easybuild-easyconfigs pull request #17506
Opened 2023-03-10 23:03 UTC by boegel

(created using `eb --new-pr`)

2023-03-10 23:14 UTC, boegel commented
@boegelbot please test @ generoso

2023-03-10 23:19 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3135.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/e8c32542b412053a3dd290b5082e2aa7 for a full test report.

2023-03-10 23:22 UTC, boegel commented
@boegelbot please test @ generoso

2023-03-10 23:26 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2023-03-10 23:27 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3135.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/a041f6de86ecae8f31b827cd82791b32 for a full test report.

2023-03-14 00:37 UTC, casparvl requested changes

2023-03-14 00:37 UTC, casparvl commented on easybuild/easyconfigs/g/genomepy/genomepy-0.15.0-foss-2022a.eb
> +# avoid hatchling requirement to install infercnvpy
`infercnvpy`? I think this comment may have been copied from another EasyConfig, you probably forgot to change the name here :)

2023-03-14 00:46 UTC, casparvl commented on easybuild/easyconfigs/g/genomepy/genomepy-0.15.0-foss-2022a.eb
> +# avoid hatchling requirement to install infercnvpy
Ok, fixed it myself since it was such a minor change...

2023-03-14 00:48 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
tcn260.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/a7e6e127bb6ce9fa7b435f3a7b306547 for a full test report.

2023-03-14 00:49 UTC, casparvl approved these changes
Lgtm!

2023-03-14 01:06 UTC, casparvl commented
Going in, thanks @boegel!

2023-03-14 01:06 UTC, merged