{lib}[foss/2021a] GPyTorch v1.9.1 w/ Python 3.9.5
easybuilders/easybuild-easyconfigs pull request #17513
Opened 2023-03-13 13:45 UTC by VRehnberg

(created using `eb --new-pr`)

2023-03-14 00:12 UTC, casparvl requested changes
Minor changes to make CI pass, the rest looks good to me. As a note for posterity: `scikit-learn` is listed in `setup.py` of `GPyTorch`. It was omitted from `GPyTorch-1.3.0-foss-2020b.eb`, but the `setup.py` does list this as a dependency.

2023-03-14 00:12 UTC, casparvl commented on easybuild/easyconfigs/g/GPyTorch/GPyTorch-1.9.1-foss-2021a-CUDA-11.3.1.eb
> +download_dep_fail = True
This can be removed, as it is default for `PythonBundle` (and _should_ be removed in order to make the CI pass :))

2023-03-14 00:12 UTC, casparvl commented on easybuild/easyconfigs/g/GPyTorch/GPyTorch-1.9.1-foss-2021a-CUDA-11.3.1.eb
> +        'checksum': ['84bf572631a7e1576de6920d81600ca0fedcf6bda2f29dbaf440d6e72ce6abab'],
This is a typo: the correct keyword is `checksums` (multiple). That's why CI complains that there is still no checksum found.

2023-03-14 09:56 UTC, VRehnberg commented
> Minor changes to make CI pass, the rest looks good to me. As a note for posterity: `scikit-learn` is listed in `setup.py` of `GPyTorch`. It was omitted from `GPyTorch-1.3.0-foss-2020b.eb`, but the `setup.py` does list this as a dependency.

I was wondering about that. I decided to include scikit-learn as, as you said, it is listed as a dependency. But, if I could I would rather avoid installing scikit-learn on our cluster because I'm afraid our users might think it would be ok to use on our compute nodes.

2023-03-14 19:52 UTC, casparvl commented
@VRehnberg I'm afraid I don't have any expertise on `GPyTorch`. In general, if a developer lists it as a dependency, we trust that.

A quick search of the docs for `GPyTorch` is that it is mainly included as a baseline, but the preferred seems to be `faiss` - which is then an optional dependency https://docs.gpytorch.ai/en/stable/search.html?q=scikit-learn&check_keywords=yes&area=default

Why they then don't make `faiss` a real dependency is beyond me, since they claim it has better performance...

In any case, I'd not be in favour of removing `scikit-learn`, considering it is explicitely listed as dependency. What you _could_ do if you don't want the module to show up so obviously to your users, is to make it hidden (see `eb`'s `--hide-deps` and `--hidden` flags).

2023-03-14 19:52 UTC, casparvl approved these changes
Lgtm, ready for testing

2023-03-14 19:52 UTC, casparvl commented
@boegelbot please test @ generoso

2023-03-14 21:01 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gcn1.local.snellius.surf.nl - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 515.86.01, Python 3.6.8
See https://gist.github.com/f298a25f73744bf4a0b3c9aa8d7a30e9 for a full test report.

2023-03-14 21:01 UTC, casparvl commented
@boegelbot please test @ generoso

2023-03-14 21:11 UTC, casparvl commented
@boegelbot please test @ jsc-zen2

2023-03-15 00:51 UTC, casparvl commented
Going in, thanks @VRehnberg!

2023-03-15 00:52 UTC, merged