{bio}[foss/2022b] KrakenUniq-1.0.3-foss-2022a.eb
easybuilders/easybuild-easyconfigs pull request #17569
Opened 2023-03-20 12:23 UTC by deniskristak

https://github.com/vscentrum/vsc-software-stack/issues/102

2023-03-20 12:40 UTC, deniskristak commented
@boegelbot please test @ generoso

2023-03-21 01:20 UTC, casparvl requested changes

2023-03-21 01:20 UTC, casparvl commented on easybuild/easyconfigs/k/KrakenUniq/KrakenUniq-1.0.3-foss-2022a.eb
> +dependencies = [
Seeing the error on Generoso, I think it needs Perl as a dependency (it seems to be missing a particular Perl package when running the `sanity_check_commands`)

2023-03-21 01:20 UTC, casparvl commented on easybuild/easyconfigs/k/KrakenUniq/KrakenUniq-1.0.3-foss-2022a.eb
> +toolchain = {'name': 'foss', 'version': '2022a'}
Does `KrakenUniq` require `foss` as a toolchain? Isn't GCC enough here?

2023-03-21 14:54 UTC, deniskristak commented on easybuild/easyconfigs/k/KrakenUniq/KrakenUniq-1.0.3-foss-2022a.eb
> +toolchain = {'name': 'foss', 'version': '2022a'}
done

2023-03-21 14:56 UTC, deniskristak commented
@boegelbot please test @ generoso

2023-03-21 20:45 UTC, casparvl commented
@boegelbot please test @ generoso

2023-03-24 18:13 UTC, verdurin commented
Test report by @verdurin
**FAILED**
Build succeeded for 1 out of 2 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/5c2e78c45f6e18c1b4e12ddb47ab7927 for a full test report.

2023-03-24 18:15 UTC, verdurin commented
```
Compress::Raw::Zlib version 2.103 required--this is only version 2.101 at /eb/maint/software/Perl/5.34.1-GCCcore-11.3.0/lib/perl5/site_perl/5.34.1/IO/Uncompress/RawInflate.pm line 8.
```

2023-04-06 13:34 UTC, smoors commented
@deniskristak i've added the `Compress-Raw-Zlib` dep to get around the `Compress::Raw::Zlib` version error

2023-04-06 13:35 UTC, smoors commented
@boegelbot: please test @ generoso

2023-04-06 14:07 UTC, smoors approved these changes
lgtm

2023-04-06 14:09 UTC, smoors commented
Going in, thanks @deniskristak!

2023-04-06 14:09 UTC, merged

2023-04-11 13:34 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3102.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/2644f930a9b048aeccb2753f72caeb0a for a full test report.