{lib}[GCC/11.2.0] nanodbc 2.14.0
easybuilders/easybuild-easyconfigs pull request #17598
Opened 2023-03-24 10:50 UTC by ll4strw

Added easyconfig for nanondbc, a small C++ wrapper for the native C ODBC API.

2023-03-24 11:17 UTC, jfgrimm requested changes

2023-03-24 11:17 UTC, jfgrimm commented on easybuild/easyconfigs/n/nanodbc/nanodbc-2.14.0-GCCcore-11.2.0.eb
> +    ('Boost', '1.77.0', '', ('GCC', '11.2.0')),
if you're depending on a `GCC`-level easyconfig, this easyconfig should also be (at least) at `GCC` level 
```suggestion
    ('Boost', '1.77.0'),
```

2023-03-24 11:17 UTC, jfgrimm commented on easybuild/easyconfigs/n/nanodbc/nanodbc-2.14.0-GCCcore-11.2.0.eb
> +toolchain = {'name': 'GCCcore', 'version': '11.2.0'}
if you're depending on a GCC-level easyconfig, this easyconfig should also be (at least) at GCC level
note that the filename will need to be updated to match
```suggestion
toolchain = {'name': 'GCC', 'version': '11.2.0'}
```

2023-03-24 11:17 UTC, jfgrimm commented on easybuild/easyconfigs/n/nanodbc/nanodbc-2.14.0-GCCcore-11.2.0.eb
> +    'files': ['lib/libnanodbc.so'],
we should avoid hard-coding the shared library extension by using the `SHLIB_EXT` template constant
```suggestion
    'files': ['lib/libnanodbc.%s' % SHLIB_EXT],
```

2023-03-24 11:17 UTC, jfgrimm commented on easybuild/easyconfigs/n/nanodbc/nanodbc-2.14.0-GCCcore-11.2.0.eb
> +separate_build_dir = True
no need to make this explicit, this is default behaviour
```suggestion
```

2023-03-24 11:41 UTC, jfgrimm commented
@boegelbot please test @ generoso

2025-05-14 14:30 UTC, Crivella commented
Should those be OS dependencies? I see there is an EasyConfig for `unixODBC` for `GCCcore-12.3.0` ?

https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/u/unixODBC/unixODBC-2.3.12-GCCcore-12.3.0.eb

2025-08-18 17:56 UTC, boegel commented
Closing this since `GCC/11.2.0` is deprecated or no longer supported, see https://docs.easybuild.io/policies/toolchains

Sorry for not getting back to this @ll4strw 

If this is still relevant, please consider opening a new pull request using a more recent toolchain

2025-08-18 17:56 UTC, closed without merging