{bio}[foss/2022a] CASPR v20200730 w/ Python 3.10.4
easybuilders/easybuild-easyconfigs pull request #17606
Opened 2023-03-27 16:53 UTC by deniskristak

adding CASPR easyconfig + deps
https://github.com/vscentrum/vsc-software-stack/issues/116

2023-03-27 17:13 UTC, deniskristak commented
@boegelbot please test @ generoso

2023-04-10 07:15 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 9 out of 9 (4 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/efa99a27f706cf70502e335a191dd1f1 for a full test report.

2023-04-10 17:03 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2023-04-10 17:03 UTC, boegel requested changes

2023-04-10 17:03 UTC, boegel commented on easybuild/easyconfigs/f/FASTX-Toolkit/FASTX-Toolkit-0.0.14-GCC-11.3.0.eb
> -    ('Perl', '5.34.1'),
@deniskristak It looks like you're accidentally changing an existing easyconfig here?

2023-04-10 17:06 UTC, boegel requested changes

2023-04-10 17:06 UTC, boegel commented on easybuild/easyconfigs/v/vispr/vispr-0.4.14-foss-2022a.eb
> +patches = ['vispr_fix_pandas_version_change.patch']
@deniskristak Please rename the patch file to also include the `vispr` version to which it applies: `vispr-0.4.14_fix_pandas_version_change.patch`

2023-04-10 18:34 UTC, boegel approved these changes

2023-04-10 18:34 UTC, boegel commented
Going in, thanks @deniskristak!

2023-04-10 18:34 UTC, merged