{lib}[foss/2021b] simple-dftd3 v0.7.0
easybuilders/easybuild-easyconfigs pull request #17620
Opened 2023-03-29 17:28 UTC by sassy-crick

(created using `eb --new-pr`)

reopened from PR #16889 as PR #16760 is GCC version 11.**3** and required is 11.**2**

Requires:
- [x] PR #16890
- [ ] PR #17621
- [x] PR #16892

2023-04-06 09:29 UTC, lexming requested changes
Please keep the same name capitalization as in https://github.com/easybuilders/easybuild-easyconfigs/pull/16760

2023-10-23 14:28 UTC, sassy-crick commented
Closed in favour of PR #16760

2023-11-11 00:30 UTC, sassy-crick commented
My wrong. I need this for the `foss-2021b` toolchain for PR #16885 so I open that again. Apologies.

2025-01-17 14:06 UTC, sassy-crick commented
Closed as it is is the foss-2021b toolchain version

2025-01-17 14:06 UTC, closed without merging