{bio}[foss/2021b] Trinity v2.15.1, BLAT v3.7, RSEM v1.3.3 w/ Python 3.9.6
easybuilders/easybuild-easyconfigs pull request #17686
Opened 2023-04-10 16:07 UTC by boegel

(created using `eb --new-pr`)

2023-04-10 16:07 UTC, boegel commented
@boegelbot please test @ generoso

2023-04-11 08:14 UTC, verdurin commented
@boegel please take a look at the test failures

2023-06-29 08:41 UTC, akesandgren commented
HDF5 1.10.8 is used in ncbi-vdb due to ABI ioncompat from 1.12.x and that is the sole cause of the HDF5 problem.
So we probably need a whitelisting of that.
As for GATK we can just drop usage here to 4.2.3.0. Only DROP have it as a dep before this one.

2023-06-29 11:25 UTC, akesandgren requested changes

2023-06-29 11:25 UTC, akesandgren commented on easybuild/easyconfigs/t/Trinity/Trinity-2.15.1-foss-2021b.eb
> +    ('GMAP-GSNAP', '2021-21-17'),
Incorrect version once #18231 has been merged. Please update

2023-06-29 14:02 UTC, Micket commented on easybuild/easyconfigs/t/Trinity/Trinity-2.15.1-foss-2021b.eb
> +    ('GMAP-GSNAP', '2021-21-17'),
```suggestion
    ('GMAP-GSNAP', '2021-12-17'),
```

2023-06-29 16:09 UTC, boegel commented
Hmm, it's way trickier than just adding an exception in the tests...

`HISAT2` depends on `ncbi-vdb` 2.11.2 which in turns depends on HDF5 1.10.8, while `R` depends on HDF5 1.12.1.
Both `HISAT2` and `R` are dependencies for `RSEM`.

So the only way out is to change `ncbi-vdb-2.11.2-gompi-2021b.eb` so it uses HDF5 1.12.1 as well, and make it play nice with other easyconfigs from the same generation, like we did for `ncbi-vdb-3.0.0-gompi-2021b.eb` in #17140 ...

2023-06-29 18:53 UTC, branfosj commented
@boegelbot please test @ generoso

2023-06-29 19:02 UTC, branfosj commented
@boegelbot please test @ jsc-zen2

2023-06-29 19:08 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 10 out of 10 (3 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/ec9933db0d42042e6651ee0957c10efb for a full test report.

2023-06-29 19:46 UTC, branfosj commented
@boegelbot please test @ jsc-zen2

2023-06-29 19:47 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3169.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/ecd23a8b149ebc207acdf1a9a0008a11 for a full test report.

2023-06-30 06:53 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/25cb02e0b3202bce19f43b19c00c8eed for a full test report.

2023-06-30 07:04 UTC, akesandgren requested changes
LGTM

2023-06-30 07:06 UTC, akesandgren approved these changes
LGTM

2023-06-30 07:06 UTC, akesandgren commented
Going in, thanks @boegel!

2023-06-30 07:06 UTC, merged