{chem}[GCC/12.2.0,intel-compilers/2022.2.1] libxc v6.1.0
easybuilders/easybuild-easyconfigs pull request #17706
Opened 2023-04-12 17:39 UTC by Micket

(created using `eb --new-pr`)

2023-04-12 17:40 UTC, Micket commented
@boegelbot please test @ generoso

2023-04-12 18:16 UTC, Micket commented
@boegelbot please test @ generoso

2023-04-12 18:52 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/27b23fa2b4854a3e8a7bd9a5528ae888 for a full test report.

2023-04-12 19:27 UTC, boegel commented
@boegelbot please test @ jsc-zen2
CORE_CNT=16

2023-04-12 19:29 UTC, boegel requested changes

2023-04-12 19:29 UTC, boegel commented on easybuild/easyconfigs/l/libxc/libxc-6.1.0-GCC-12.2.0.eb
> +separate_build_dir = True
@Micket This is enabled by default in `CMakeMake`, so can be removed

2023-04-12 19:29 UTC, boegel commented on easybuild/easyconfigs/l/libxc/libxc-6.1.0-GCC-12.2.0.eb
> +    'files': ['bin/xc-info'] +
Is it worth adding a sanity check command for `xc-info`?

2023-04-12 20:09 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3101.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/bfe945e4c2deef87adff18f446f5edf2 for a full test report.

2023-04-13 00:57 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/1d5a4d8960b44ed65ae516deef298a39 for a full test report.

2023-04-13 10:47 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bwd-rockylinux-91 - Linux Rocky Linux 9.1 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 525.105.17, Python 3.9.14
See https://gist.github.com/SebastianAchilles/dd682c6ec8aca50ee5d10ee880050250 for a full test report.

2023-04-13 13:43 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/2648dc438eca190683c2338fb0b666d5 for a full test report.

2023-04-13 14:11 UTC, verdurin approved these changes
Looks fine.

2023-04-13 14:12 UTC, verdurin commented
Going in, thanks @Micket!

2023-04-13 14:12 UTC, merged