{cae}[foss/2022a] PICI-LIGGGHTS v3.8.1 w/ Python 3.10.4
easybuilders/easybuild-easyconfigs pull request #17710
Opened 2023-04-13 13:37 UTC by branfosj

(created using `eb --new-pr`)

2023-04-13 13:40 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/61956ca04c1694f75778d963293a0673 for a full test report.

2023-04-13 13:44 UTC, branfosj commented
@boegelbot please test @ jsc-zen2

2023-04-14 11:17 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/ca908c5abc28c0366deec8cc4ac91e93 for a full test report.

2023-04-14 11:37 UTC, verdurin requested changes

2023-04-14 11:37 UTC, verdurin commented on easybuild/easyconfigs/p/PICI-LIGGGHTS/PICI-LIGGGHTS-3.8.1-foss-2022a.eb
> +description = """UoB Postron Imaging Centre's Improved LIGGGHTS distribution with
```suggestion
description = """UoB Positron Imaging Centre's Improved LIGGGHTS distribution with
```

2023-04-14 11:58 UTC, verdurin approved these changes

2023-04-14 11:58 UTC, verdurin commented
Looks fine.

2023-04-14 12:01 UTC, merged