Add egg file to OpenCV 4.6.0 python package for pip
easybuilders/easybuild-easyconfigs pull request #17779
Opened 2023-04-21 13:27 UTC by Micket

Add egg-info file to make packages show up in pip

2023-04-24 18:20 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.6, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/cef2524c0d7d91fb58c772fb62d63f52 for a full test report.

2023-04-24 18:42 UTC, Micket commented
Erh, what am I missing here

This approach is working fine with VTK
```
$ cat /apps/Test2/software/VTK/9.2.2-foss-2022a/lib/python3.10/site-packages/vtk-9.2.2.egg-info 
Metadata-Version: 2.1
Name: vtk
Version: 9.2.2
Summary: VTK is an open-source toolkit for 3D computer graphics, image processing, and visualization
Platform: UNKNOWN

# pip list  | grep vtk
vtk                               9.2.2

# pip show vtk
Name: vtk
Version: 9.2.2
Summary: VTK is an open-source toolkit for 3D computer graphics, image processing, and visualization
Home-page: 
Author: 
Author-email: 
License: 
Location: /apps/Test2/software/VTK/9.2.2-foss-2022a/lib/python3.10/site-packages
Requires: 
Required-by: 
```

and with  this PR on OpenCV
```
 cat /apps/Test2/software/OpenCV/4.6.0-foss-2022a-contrib/lib/python3.10/site-packages/opencv-contrib-python-4.6.0.egg-info 
Metadata-Version: 2.1
Name: opencv-contrib-python
Version: 4.6.0
Summary: Wrapper package for OpenCV python bindings.
Platform: UNKNOWN

# pip list | grep opencv
opencv-contrib-python             4.6.0
```

So far so good!
```
$ pip show opencv-contrib-python
WARNING: Package(s) not found: opencv-contrib-python

$ pip show opencv
Name: opencv-contrib-python
Version: 4.6.0
Summary: Wrapper package for OpenCV python bindings.
Home-page: 
Author: 
Author-email: 
License: 
Location: /apps/Test2/software/OpenCV/4.6.0-foss-2022a-contrib/lib/python3.10/site-packages
Requires: 
Required-by: 
```

wtf, it literally doesn't say just "opencv" anywhere.

2023-05-09 17:32 UTC, Micket commented
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/9e47489b2e55a448cfb231642899c121 for a full test report.

2023-05-09 19:03 UTC, Micket commented
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/a6049a54c3e6f47053a86682045009ca for a full test report.

2023-05-10 05:31 UTC, akesandgren requested changes

2023-05-10 05:31 UTC, akesandgren commented on easybuild/easyconfigs/o/OpenCV/OpenCV-4.6.0-foss-2022a-CUDA-11.7.0-contrib.eb
> +local_egg_info_dest = '%(installdir)s/lib/python%(pyshortver)s/site-packages/opencv-contrib-python-%(version)s.egg-info'
Need to change filename here too

2023-05-10 05:31 UTC, akesandgren commented on easybuild/easyconfigs/o/OpenCV/OpenCV-4.6.0-foss-2022a-contrib.eb
> +local_egg_info_dest = '%(installdir)s/lib/python%(pyshortver)s/site-packages/opencv-contrib-python-%(version)s.egg-info'
And here

2023-05-10 10:18 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/0f39249158c87866f7a527ba0ab6cec1 for a full test report.

2023-05-10 11:26 UTC, Micket commented
I can find pc file and pip info now, so i think this is good to go

2023-05-11 06:03 UTC, akesandgren approved these changes
LGTM

2023-05-11 06:04 UTC, akesandgren commented
Going in, thanks @Micket!

2023-05-11 06:04 UTC, merged

2023-05-11 11:09 UTC, Micket commented
@boegelbot please test @ jsc-zen2

2023-05-11 11:58 UTC, Micket commented
@boegelbot please test @ jsc-zen2
EB_ARGS='--optarch=""