{geo}[foss/2022a] rgdal v1.6-6
easybuilders/easybuild-easyconfigs pull request #17798
Opened 2023-04-25 14:55 UTC by terjekv

(created using `eb --new-pr`)

2023-04-25 16:11 UTC, verdurin requested changes

2023-04-25 16:18 UTC, terjekv commented on easybuild/easyconfigs/r/rgdal/rgdal-1.6-6-foss-2022a-R-4.2.1.eb
> +versionsuffix = '-R-%(rver)s'
Ah, yeah, removing. Thanks.

2023-04-25 16:18 UTC, terjekv commented on easybuild/easyconfigs/r/rgdal/rgdal-1.6-6-foss-2022a-R-4.2.1.eb
> +
Will do. Sorry about this.

2023-04-25 16:23 UTC, terjekv commented on easybuild/easyconfigs/r/rgdal/rgdal-1.6-6-foss-2022a-R-4.2.1.eb
> +versionsuffix = '-R-%(rver)s'
Fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/17798/commits/2c8afe8b366004a39a8d286b1d33f9de6d459521

2023-04-25 16:23 UTC, terjekv commented on easybuild/easyconfigs/r/rgdal/rgdal-1.6-6-foss-2022a-R-4.2.1.eb
> +
Fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/17798/commits/2c8afe8b366004a39a8d286b1d33f9de6d459521

2023-04-25 16:24 UTC, terjekv commented
Is there a way to rename the easyconfig itself, or should I make a PR with the new correct name?

2023-04-25 16:26 UTC, verdurin commented
Looks like you've already done it, thanks.

2023-04-25 16:28 UTC, terjekv commented
> Looks like you've already done it, thanks.

I figured I could try the `:` trick with `--update-pr`. I just wasn't sure if it'd work on the only file in the commit. :)

2023-04-25 16:29 UTC, verdurin commented
@boegelbot please test @ generoso

2023-04-26 09:59 UTC, verdurin commented
@boegelbot please test @ jsc-zen2

2023-04-26 10:07 UTC, verdurin approved these changes
Looks fine.

2023-04-26 10:07 UTC, verdurin commented
Going in, thanks @terjekv!

2023-04-26 10:07 UTC, merged