{tools}[foss/2022b] MoviePy v1.0.3 w/ Python 3.10.8
easybuilders/easybuild-easyconfigs pull request #17809
Opened 2023-04-26 12:23 UTC by SimonPinches

(created using `eb --new-pr`)

2023-04-28 23:26 UTC, Micket requested changes, later dismissed
I think these can both be moved to gfbf level

2025-06-16 14:49 UTC, sassy-crick commented
@SimonPinches You might want to sync your PR with development, something like this: 
```
eb --sync-pr-with-develop NUMBER_OF_PR
```

2025-06-16 19:33 UTC, boegel commented on easybuild/easyconfigs/m/MoviePy/MoviePy-1.0.3-gfbf-2022b.eb
> +    ('imageio', '2.28.0'),
We already have `imageio-2.31.1-foss-2022b.eb`, can't that be used as a dependency here?

2025-06-17 08:06 UTC, SimonPinches commented on easybuild/easyconfigs/m/MoviePy/MoviePy-1.0.3-gfbf-2022b.eb
> +    ('imageio', '2.28.0'),
@boegel I no longer have access to a `foss/2022b` software stack but fine to change (and test with gh actions).

2025-08-18 15:43 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2025-08-18 15:52 UTC, boegel submitted a review, later dismissed
lgtm

2025-08-18 16:24 UTC, boegel submitted a review, later dismissed
lgtm

2025-08-18 16:24 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2025-08-18 16:54 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2025-08-18 17:05 UTC, boegel approved these changes
lgtm

2025-08-18 17:05 UTC, boegel commented
Going in, thanks @SimonPinches!

2025-08-18 17:05 UTC, merged