{tools}[intel/2022a] HPL v2.0.15
easybuilders/easybuild-easyconfigs pull request #17891
Opened 2023-05-10 11:37 UTC by boegel

(created using `eb --new-pr`)

2023-05-10 13:03 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3308.joltik.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 530.30.02, Python 3.6.8
See https://gist.github.com/boegel/0909c083249c22f14897802c728ac80f for a full test report.

2023-05-11 14:13 UTC, branfosj requested changes

2023-05-11 14:13 UTC, branfosj commented on easybuild/easyconfigs/h/HPL/HPL-2.0.15-intel-2022a-CUDA-11.7.0.eb
> +# download via https://developer.nvidia.com/computeworks-developer-exclusive-downloads
Please use `download_instructions` instead here.

2023-05-11 14:13 UTC, branfosj commented on easybuild/easyconfigs/h/HPL/HPL-2.0.15-intel-2022a-CUDA-11.7.0.eb
> +# fix Make dependencies, so parallel build also works
This comment is in the wrong place.

2023-09-10 13:27 UTC, branfosj commented on easybuild/easyconfigs/h/HPL/HPL-2.0.15-intel-2022a-CUDA-11.7.0.eb
> +# fix Make dependencies, so parallel build also works
```suggestion
download_instructions = """Download CUDA Accelerated Linpack from
https://developer.nvidia.com/computeworks-developer-exclusive-downloads"""
sources = ['hpl-%%(version_major_minor)s_FERMI_v%s.tgz' % local_patch_version]
# fix Make dependencies, so parallel build also works
patches = ['HPL_parallel-make.patch']
checksums = [
    {'hpl-2.0_FERMI_v15.tgz': '16dd21af22fced613923a6cb09805d63952fc9c9f278cb7582061a43fe39a408'},
    {'HPL_parallel-make.patch': '2a5bf9c4f328049828ddecec7ba3f05a9e25d236f4212747c53bd22fea80c5e6'},
]

```

2023-09-10 13:29 UTC, branfosj commented on easybuild/easyconfigs/h/HPL/HPL-2.0.15-intel-2022a-CUDA-11.7.0.eb
> +# fix Make dependencies, so parallel build also works
done in 07a000a

2023-09-10 13:29 UTC, branfosj commented on easybuild/easyconfigs/h/HPL/HPL-2.0.15-intel-2022a-CUDA-11.7.0.eb
> +# download via https://developer.nvidia.com/computeworks-developer-exclusive-downloads
done in 07a000a

2023-09-10 13:31 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0208u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), 1 x NVIDIA NVIDIA A100-SXM4-40GB, 520.61.05, Python 3.6.8
See https://gist.github.com/branfosj/51d6bd699505275c4392ee8702baa986 for a full test report.

2023-09-10 13:49 UTC, branfosj approved these changes

2023-09-10 13:50 UTC, branfosj commented
Going in, thanks @boegel!

2023-09-10 13:50 UTC, merged