{toolchain} GCC 11.4.0
easybuilders/easybuild-easyconfigs pull request #17992
Opened 2023-05-30 16:35 UTC by SebastianAchilles

(created using `eb --new-pr`)

2023-05-30 18:15 UTC, SebastianAchilles commented
@boegelbot please test @ jsc-zen2
CORE_CNT=16

2023-05-30 18:31 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
zen2-ubuntu-2304 - Linux Ubuntu 23.04 (Lunar Lobster), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.11.2
See https://gist.github.com/SebastianAchilles/0fb68a4b7372af7123601e7b244114f0 for a full test report.

2023-05-30 18:41 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
skl-fedora-39 - Linux Fedora Linux 39 (Container Image Prerelease), x86_64, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (skylake), Python 3.11.3
See https://gist.github.com/SebastianAchilles/c30f62d41db48d1b5894adb1bda6706c for a full test report.

2023-05-30 18:48 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), 2 x NVIDIA NVIDIA GeForce GTX 1060 6GB, 525.105.17, Python 3.9.16
See https://gist.github.com/SebastianAchilles/9003c21b6ba1213cda7663679b462b97 for a full test report.

2023-05-31 06:08 UTC, boegel requested changes

2023-05-31 06:08 UTC, boegel commented on easybuild/easyconfigs/g/GCCcore/GCCcore-11.4.0.eb
> +    'GCCcore-9.3.0_gmp-c99.patch',
@SebastianAchilles I have two extra patches in my PR #17993, those still seem relevant?

2023-06-03 09:18 UTC, branfosj commented
closing in favour of #17993

2023-06-03 09:18 UTC, closed without merging