{math}[foss/2020b] Demystify v0.0.17 w/ Python 3.8.6
easybuilders/easybuild-easyconfigs pull request #17990
Opened 2023-05-30 12:08 UTC by lexming

(created using `eb --new-pr`)

Depends on:
* [x] https://github.com/easybuilders/easybuild-easyconfigs/pull/18284

2023-06-13 08:47 UTC, verdurin requested changes

2023-06-19 09:50 UTC, lexming commented on easybuild/easyconfigs/d/Demystify/Demystify-0.0.17-foss-2020b.eb
> +    ('Z3', '4.8.10', '-Python-%(pyver)s'),
Thanks @verdurin, fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/17990/commits/b7f92d85ea82cdf1c76c705716699b19ad470b42

2023-06-21 17:08 UTC, verdurin submitted a review, later dismissed
Looks fine.

2023-06-21 17:09 UTC, verdurin commented
@boegelbot please test @ generoso

2023-06-21 17:09 UTC, verdurin commented
Test report by @verdurin
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/cd77f813e87b4a568d3aadf67c4088f6 for a full test report.

2023-07-04 21:53 UTC, lexming commented
@boegelbot: please test @ generoso

2023-07-07 21:41 UTC, lexming commented
Failed tests are due to missing `z3_solver`. This PR needs #18284

2023-07-11 15:12 UTC, lexming commented
@boegelbot: please test @ generoso

2023-07-11 15:19 UTC, lexming commented
@boegelbot: please test @ generoso

2023-12-14 12:12 UTC, lexming commented
@boegelbot: please test @ generoso

2023-12-14 13:36 UTC, lexming commented
@boegelbot please test @ jsc-zen2

2023-12-27 17:11 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-rockylinux-89 - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/ea80c98dbd502363d91eefd9baf1b4ea for a full test report.

2023-12-27 17:12 UTC, SebastianAchilles approved these changes
lgtm

2023-12-27 17:14 UTC, merged