{vis}[foss/2022a] PyQtGraph v0.13.3 w/ Python 3.10.4
easybuilders/easybuild-easyconfigs pull request #18004
Opened 2023-06-01 12:46 UTC by deniskristak

(created using `eb --new-pr`)

2023-06-01 12:49 UTC, deniskristak commented
Requirements:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18003 
- https://github.com/easybuilders/easybuild-easyconfigs/pull/18002

2023-06-05 16:34 UTC, boegel requested changes

2023-06-06 07:18 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3159.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/fcfd50357087bdc92df0cea51aff61a7 for a full test report.

2023-06-06 07:55 UTC, boegel commented on easybuild/easyconfigs/c/cellpose/cellpose-2.2.2-foss-2022a.eb
> +        'preinstallopts': "sed -i 's/opencv-python-headless//g' setup.py && ",
It's actually `opencv-contrib-python`, but makes sense, I'll use that instead.

```suggestion
        # OpenCV dependency provides opencv-python-headless, but it's not exposes as such to pip,
        # so strip out that requirement to make 'pip check' pass
        'preinstallopts': "sed -i 's/opencv-python-headless/opencv-contrib-python/g' setup.py && ",

2023-06-06 08:08 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3159.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/7860c7cf2e8a78b93230bcc8401118d1 for a full test report.

2023-06-19 18:58 UTC, boegel commented
@boegelbot please test @ generoso

2023-06-19 19:04 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3143.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/cc2578456e3de31e00628e9d96bd523e for a full test report.

2023-06-20 12:22 UTC, boegel approved these changes
lgtm

2023-06-20 12:22 UTC, boegel commented
Going in, thanks @deniskristak!

2023-06-20 12:22 UTC, merged