{tools}[GCCcore/12.3.0] util-linux v2.39
easybuilders/easybuild-easyconfigs pull request #18023
Opened 2023-06-04 13:28 UTC by Micket

(created using `eb --new-pr`)

2023-06-04 13:29 UTC, Micket commented
@boegelbot please test @ generoso

2023-06-04 13:33 UTC, branfosj approved these changes

2023-06-04 13:34 UTC, branfosj commented
Test report by @branfosj
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/53d7c8a95ed9f3d0fb5c7bdfbca23be9 for a full test report.

2023-06-04 13:47 UTC, branfosj requested changes

2023-06-04 13:47 UTC, branfosj commented on easybuild/easyconfigs/u/util-linux/util-linux-2.39-GCCcore-12.3.0.eb
> +checksums = ['b1f597ad172a2ee17b0a7ae4be7ab7e1b1a6f9394ddbd3d8ec90ae4ed7333579']
Please add https://github.com/util-linux/util-linux/commit/ffdd75cceedafac3ba7a80b86e1b103c383b260e to fix the [build failure](https://github.com/easybuilders/easybuild-easyconfigs/pull/18023#issuecomment-1575572091)

2023-06-04 13:55 UTC, Micket commented
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/3bc3e4c0fdf72f3a61691d9b106a1ee9 for a full test report.

2023-06-04 14:14 UTC, Micket commented
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/1697281db8017f79654d4af3ba83a23f for a full test report.

2023-06-04 14:23 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/4983df78d7d3f1924b6cdc8ea60827d3 for a full test report.

2023-06-04 14:48 UTC, Micket commented
@boegelbot please test @ generoso

2023-06-04 19:45 UTC, Micket commented
@boegelbot please test @ jsc-zen2

2023-06-05 06:55 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
fair-mastodon-c6g-2xlarge-0003 - Linux Rocky Linux 8.7, AArch64, ARM UNKNOWN (graviton2), Python 3.6.8
See https://gist.github.com/boegel/807d70fa612f6ffde6376da10464ebc7 for a full test report.

2023-06-05 07:47 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3159.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/ba34f45f0d02a091456d37c643ff4040 for a full test report.

2023-06-05 09:33 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/6547174f61dfdf4d79c272f15c61d383 for a full test report.

2023-06-05 09:35 UTC, branfosj approved these changes

2023-06-05 09:35 UTC, branfosj commented
Going in, thanks @Micket!

2023-06-05 09:35 UTC, merged