{bio}[gompi/2021a] SRA-Toolkit v3.0.5, ncbi-vdb v3.0.5
easybuilders/easybuild-easyconfigs pull request #18065
Opened 2023-06-09 08:27 UTC by SIB-software

(created using `eb --new-pr`)

2023-06-13 07:09 UTC, verdurin commented
@SIB-software would it be possible to use the older version of `ncbi-vdb`? Or do you think it explicitly requires the newer one?

2023-06-13 07:15 UTC, smoretti commented
I tried with the older version of `ncbi-vdb` but it failed (not the same lib names). Better if both ncbi-vdb and SRA-Toolkit are sync.
@boegel agreed I update the _test/easyconfigs/easyconfigs.py_ file in the PR to avoid the issue and "force" the sync.

2023-06-13 07:21 UTC, verdurin commented
Fair enough - thanks for the update.

2023-06-14 12:26 UTC, smoretti commented
In fact I am not allowed to update the `test/easyconfigs/easyconfigs.py` file:
`ERROR: Failed to process easyconfig ../../../../test/easyconfigs/easyconfigs.py: Failed to obtain class for ec.get('easyblock') easyblock (not available?): No module named 'ec'`

Could you do it @verdurin or @boegel ?
[easyconfigs.py.zip](https://github.com/easybuilders/easybuild-easyconfigs/files/11745631/easyconfigs.py.zip)

2023-06-15 10:07 UTC, smoretti commented
I have created a distinct PR for the test file #18098

2023-06-21 07:34 UTC, boegel commented
@smoretti Can you sync this with `develop` now #18098 is merged?

```
eb --sync-pr-with-devel 18098
```

2023-06-21 07:42 UTC, boegel requested changes

2023-06-21 07:42 UTC, boegel commented on easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-3.0.5-gompi-2021a.eb
> +    ('bzip2',   '1.0.8'),
```suggestion
    ('Perl', '5.32.1', '-minimal'),
    ('Python', '3.9.5', '-bare'),
    ('CMake', '3.20.1'),
]

dependencies = [
    ('HDF5', '1.10.7'),
    ('libxml2', '2.9.10'),
    ('bzip2', '1.0.8'),

2023-06-21 07:42 UTC, boegel commented on easybuild/easyconfigs/s/SRA-Toolkit/SRA-Toolkit-3.0.5-gompi-2021a.eb
> +    ('zlib',     '1.2.11'),
```suggestion
    ('CMake', '3.20.1'),
    ('flex', '2.6.4'),
    ('Bison', '3.7.6'),
    ('Perl', '5.32.1', '-minimal'),
    ('Python', '3.9.5',  '-bare'),
]

dependencies = [
    ('Java', '11',  '', SYSTEM),
    ('OpenSSL', '1.1', '', SYSTEM),
    ('ncbi-vdb', version),
    ('bzip2', '1.0.8'),
    ('file', '5.40'),
    ('HDF5', '1.10.7'),
    ('libxml2', '2.9.10'),
    ('zlib', '1.2.11'),
```

2023-06-21 07:45 UTC, boegel commented
@boegelbot please test @ generoso

2023-06-21 07:50 UTC, smoretti commented on easybuild/easyconfigs/s/SRA-Toolkit/SRA-Toolkit-3.0.5-gompi-2021a.eb
> +    ('zlib',     '1.2.11'),
done

2023-06-21 07:50 UTC, smoretti commented on easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-3.0.5-gompi-2021a.eb
> +    ('bzip2',   '1.0.8'),
done

2023-06-21 08:00 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3143.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/0887c246e29d1299c2d33ac5509d6ded for a full test report.

2023-06-21 09:15 UTC, boegel approved these changes

2023-06-21 09:15 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2023-06-21 09:33 UTC, boegel commented
Going in, thanks @SIB-software!

2023-06-21 09:33 UTC, merged