{bio}[foss/2022b] FLASH v2.2.00
easybuilders/easybuild-easyconfigs pull request #18108
Opened 2023-06-15 10:48 UTC by eylenth

(created using `eb --new-pr`)

2023-06-16 14:22 UTC, jfgrimm requested changes
I'd suggest dropping this to `GCCcore` since it doesn't rely on MPI/BLAS/LAPACK/FFTW.

please note that you should change the filename of the easyconfig as well to reflect that

2023-06-16 14:22 UTC, jfgrimm commented on easybuild/easyconfigs/f/FLASH/FLASH-2.2.00-foss-2022b.eb
> +toolchain = {'name': 'foss', 'version': '2022b'}
The Makefile looks rather straightforward, I don't see anything that suggests we need the full `foss` toolchain here. We should be able to drop this to `GCCcore`
```suggestion
toolchain = {'name': 'GCCcore', 'version': '12.2.0'}
```

2023-06-16 14:22 UTC, jfgrimm commented on easybuild/easyconfigs/f/FLASH/FLASH-2.2.00-foss-2022b.eb
> +
(explicit `zlib` and `binutils` dependencies needed when dropping to `GCCcore` )
```suggestion

builddependencies = [('binutils', '2.39')]

dependencies = [('zlib', '1.2.12')]

```

2023-06-21 06:59 UTC, smoors commented
@boegelbot please test @ jsc-zen2

2023-06-21 07:05 UTC, smoors commented
@boegelbot: please test @ generoso

2023-06-21 07:17 UTC, smoors approved these changes
lgtm

2023-06-21 07:17 UTC, smoors commented
Going in, thanks @eylenth!

2023-06-21 07:17 UTC, merged