{lib}[foss/2021b] AMGX v2.3.0
easybuilders/easybuild-easyconfigs pull request #18105
Opened 2023-06-15 10:34 UTC by lcniel

(created using `eb --new-pr`)

2023-06-15 10:42 UTC, lcniel commented
Test report by @lcniel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera41-1 - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, 1 x NVIDIA Tesla T4, 525.85.12, Python 3.6.8
See https://gist.github.com/lcniel/4bd3bd6f9d0da050643a0307659ad77d for a full test report.

2023-06-15 11:38 UTC, lcniel commented
Test report by @lcniel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-r07-01 - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 1 x NVIDIA NVIDIA A40, 525.85.12, Python 3.6.8
See https://gist.github.com/lcniel/2dd40f83f3e2ff1e2cbca67c8d104152 for a full test report.

2023-06-21 09:33 UTC, lcniel commented
Test report by @lcniel
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in total)
alvis3-28 - Linux Rocky Linux 8.7, x86_64, Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 525.85.12, Python 3.6.8
See https://gist.github.com/lcniel/56ffaa638c70cffd416e022218891398 for a full test report.

2023-06-21 18:52 UTC, boegel requested changes

2023-06-21 18:52 UTC, boegel commented on easybuild/easyconfigs/a/AMGX/AMGX-2.3.0-foss-2021b-CUDA-11.4.1.eb
> +#configopts = ' -DCUDA_NVCC_FLAGS="-fopenmp" '
This looks like it should be cleaned up?

2023-06-21 18:52 UTC, boegel commented on easybuild/easyconfigs/a/AMGX/AMGX-2.3.0-foss-2021b-CUDA-11.4.1.eb
> +#patches = ['AMGX-2.3.0_fix_tests.patch']
no patch needed, so remove commented out line?

2023-06-21 18:52 UTC, boegel commented on easybuild/easyconfigs/a/AMGX/AMGX-2.3.0-foss-2021b-CUDA-11.4.1.eb
> +# runtest = "amgx_tests_launcher && tests/amgx_tests_launcher %s " % local_tests
Why disable the tests by default?

2024-01-09 12:14 UTC, closed without merging

2024-01-09 12:15 UTC, lcniel commented
Closing since I don't think I am likely to get back to this one soon, the test stuff needs to be worked out and checked with newer versions and right now I don't have time. Might as well do it on a later version.