{lib}[foss/2022a] timm v0.9.2 w/ Python 3.10.4 + CUDA 11.7.0
easybuilders/easybuild-easyconfigs pull request #18119
Opened 2023-06-15 14:56 UTC by boegel

(created using `eb --new-pr`)

2023-06-15 14:57 UTC, boegel commented
@boegelbot please test @ generoso

2023-06-15 17:10 UTC, Micket requested changes

2023-06-15 17:10 UTC, Micket commented on easybuild/easyconfigs/t/timm/timm-0.9.2-foss-2022a-CUDA-11.7.0.eb
> +    ('torchvision', '0.13.1', versionsuffix),
So, we do have the pytorch bundle now. Should we try to transition to it?

2023-06-15 17:10 UTC, Micket commented on easybuild/easyconfigs/t/timm/timm-0.9.2-foss-2022a-CUDA-11.7.0.eb
> +    }),
CargoPythonPackage should work here. Even if just defaulting to fetching deps online it's still beneficial to use this easyblock, as it protects your home dir from CARGO_HOME and optimizes march=native

2024-03-29 22:11 UTC, Micket commented
We have timm 0.9.7 for this toolchain, using CargoPythonBundle. As this one didn't, it probably no longer even builds as packages have been updated to require newer Rust compilers. Closing this.

2024-03-29 22:11 UTC, closed without merging