{bio}[foss/2022a] duplex-tools v0.3.3 w/ Python 3.10.4
easybuilders/easybuild-easyconfigs pull request #18154
Opened 2023-06-20 14:38 UTC by PetrKralCZ

(created using `eb --new-pr`)

2023-06-20 20:41 UTC, boegel requested changes

2023-06-20 20:41 UTC, boegel commented on easybuild/easyconfigs/d/duplex-tools/duplex-tools-0.3.3-foss-2022a.eb
> +    ('Pysam', '0.20.0'),
@PetrKralCZ please stick to Pysam 0.19.1

2023-06-21 09:44 UTC, PetrKralCZ commented
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4012.donphan.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 530.30.02, Python 3.6.8
See https://gist.github.com/PetrKralCZ/3e765673eae315b74d6263628d5cd9e7 for a full test report.

2023-06-21 11:54 UTC, smoors commented
@boegelbot please test @ jsc-zen2

2023-06-21 12:23 UTC, smoors commented
@boegelbot: please test @ generoso

2023-06-21 12:23 UTC, smoors approved these changes
lgtm

2023-06-21 12:37 UTC, smoors commented
Going in, thanks @PetrKralCZ!

2023-06-21 12:37 UTC, merged