{lang}[gfbf/2022b] R v4.3.1
easybuilders/easybuild-easyconfigs pull request #18221
Opened 2023-06-28 16:16 UTC by verdurin

(created using `eb --new-pr`)

2023-06-29 09:53 UTC, verdurin commented
@boegelbot please test @ generoso
EB_ARGS="--skip"

2023-06-29 10:28 UTC, verdurin commented
@boegelbot please test @ generoso

2023-06-29 12:03 UTC, verdurin commented
@boegelbot please test @ generoso

2023-06-29 14:39 UTC, verdurin commented
@boegelbot please test @ jsc-zen2

2023-06-29 22:42 UTC, fizwit commented
Would consider adding ggplot2?  ggplot2 is a dependency 67 times in R-4.3.0.

2023-07-03 08:18 UTC, verdurin commented
> Would consider adding ggplot2? ggplot2 is a dependency 67 times in R-4.3.0.

What does it require?

2023-07-04 18:21 UTC, fizwit commented
hmmm, ggplot2 requires 14 dependencies that are not in the current R-4.3.1.  I have put ggplot2 into a new easyconfig [R-Tidyverse-4.3.1](https://github.com/FredHutch/easybuild-life-sciences/blob/main/fh_easyconfigs/r/R-Tidyverse/R-Tidyverse-4.3.1-gfbf-2022b.eb) which is larger than the base R.  Started with eight libraries with R-Tidyverse and processed with easy_update. The result is about 130 libraries.

2023-07-05 09:55 UTC, boegel requested changes

2023-07-05 11:57 UTC, verdurin commented
On Wed, Jul 05, 2023 at 02:55:44AM -0700, Kenneth Hoste wrote:
> @boegel requested changes on this pull request.
> 
> 
> 
> > @@ -0,0 +1,374 @@
> +name = 'R'
> +version = '4.3.1'
> +
> +homepage = 'https://www.r-project.org/'
> +description = """R is a free software environment for statistical computing
> + and graphics."""
> +
> +toolchain = {'name': 'gfbf', 'version': '2022b'}
> 
> Since we already have an `R` for `2022b`, shouldn't we bump this to `2023a` (once `foss/2023a` is set in stone)?
> 

Maybe. 

We need it now, which is why I went with an existing toolchain.

2023-07-10 13:42 UTC, verdurin commented
> hmmm, ggplot2 requires 14 dependencies that are not in the current R-4.3.1. I have put ggplot2 into a new easyconfig [R-Tidyverse-4.3.1](https://github.com/FredHutch/easybuild-life-sciences/blob/main/fh_easyconfigs/r/R-Tidyverse/R-Tidyverse-4.3.1-gfbf-2022b.eb) which is larger than the base R. Started with eight libraries with R-Tidyverse and processed with easy_update. The result is about 130 libraries.

Thanks. Are you happy with that approach then, rather than adding `ggplot2` here?

2023-08-11 15:58 UTC, verdurin commented
@boegelbot please test @ generoso

2023-11-05 09:25 UTC, SebastianAchilles requested changes

2023-11-05 09:25 UTC, SebastianAchilles commented on easybuild/easyconfigs/r/R/R-4.3.1-gfbf-2023a.eb
> +    ('libgit2', '1.7.0'),
A newer `libgit2` was already merged in https://github.com/easybuilders/easybuild-easyconfigs/pull/18606
```suggestion
    ('libgit2', '1.7.1'),
```

2023-11-07 16:08 UTC, SebastianAchilles requested changes
@verdurin I updated to R 4.3.2, added the dependencies and updated the extensions in https://github.com/verdurin/easybuild-easyconfigs/pull/8

2023-12-09 23:02 UTC, merged