{astro}[foss/2021b] emcee v3.1.4 w/ Python 3.9.6
easybuilders/easybuild-easyconfigs pull request #18243
Opened 2023-06-30 07:37 UTC by VRehnberg

(created using `eb --new-pr`)

2023-06-30 07:46 UTC, VRehnberg commented
There seem to no longer be a `emcee.test` attribute. So I figured `pytest` would work instead. But, I'm unsure about this so that might be something to look extra closely at.

2023-06-30 07:49 UTC, VRehnberg commented
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-c1 - Linux Rocky Linux 8.7, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/VRehnberg/2f23fc0f4f21efdefdb64900e4ba3d20 for a full test report.

2023-07-01 08:22 UTC, branfosj requested changes

2023-07-01 08:22 UTC, branfosj commented on easybuild/easyconfigs/e/emcee/emcee-3.1.4-foss-2021b.eb
> +homepage = 'https://dfm.io/emcee'
```suggestion
homepage = 'https://emcee.readthedocs.io/'
```

2023-07-01 08:23 UTC, branfosj commented
@boegelbot please test @ generoso

2023-07-01 08:26 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/cca8f0b788bb07b8baf61a5c286be75c for a full test report.

2023-07-01 08:28 UTC, branfosj commented
@boegelbot please test @ jsc-zen2

2023-07-01 08:31 UTC, branfosj commented
@boegelbot please test @ jsc-zen2

2023-07-01 08:36 UTC, branfosj approved these changes

2023-07-01 08:46 UTC, branfosj commented
Going in, thanks @VRehnberg!

2023-07-01 08:46 UTC, merged