{tools}[GCCcore/10.3.0] GangSTR v2.4.4
easybuilders/easybuild-easyconfigs pull request #18310
Opened 2023-07-14 10:38 UTC by agimenog

(created using `eb --new-pr`)

2023-07-15 07:44 UTC, branfosj requested changes

2023-07-15 07:44 UTC, branfosj commented on easybuild/easyconfigs/g/GangSTR/GangSTR-2.4.4-GCCcore-10.3.0.eb
> +toolchain = {'name': 'GCCcore', 'version': '10.3.0'}
As this depends on `GSL-2.7-GCC-10.3.0.eb` and `HTSlib-1.12-GCC-10.3.0.eb` this should also use the `GCC` toolchain (as `GCC` level items can use `GCCcore` items as dependencies but not the reverse). So:

1. `toolchain = {'name': 'GCCcore', 'version': '10.3.0'}`
2. change the filename to be `GangSTR-2.4.4-GCCcore-10.3.0.eb`

2023-07-15 07:44 UTC, branfosj commented on easybuild/easyconfigs/g/GangSTR/GangSTR-2.4.4-GCCcore-10.3.0.eb
> +
Please add `builddependencies = [('pkg-config', '0.29.2')]`, as this is used during configure.

2025-05-09 11:10 UTC, akesandgren commented
Closing this since GCC(core)/10.3.0 foss/2021a is deprecated, see https://docs.easybuild.io/policies/toolchains

Sorry for not getting back to this @agimenog 

If this is still relevant, please consider opening a new pull request using a more recent toolchain

2025-05-09 11:10 UTC, closed without merging