{data,tools}[foss/2022b] pyodbc v4.0.39, unixODBC v2.3.11
easybuilders/easybuild-easyconfigs pull request #18334
Opened 2023-07-19 12:25 UTC by PetrKralCZ

(created using `eb --new-pr`)

2023-07-21 15:18 UTC, verdurin requested changes

2023-07-21 15:18 UTC, verdurin commented on easybuild/easyconfigs/u/unixODBC/unixODBC-2.3.11-foss-2022b.eb
> +
@PetrKralCZ please note the bot's complaints about missing sanity check paths.

2023-07-26 09:30 UTC, PetrKralCZ commented
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4007.donphan.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 530.30.02, Python 3.6.8
See https://gist.github.com/PetrKralCZ/7b357435f21214c2105af2f7da4ba3c0 for a full test report.

2023-07-26 09:31 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2023-07-26 11:20 UTC, verdurin commented
@boegelbot please test @ jsc-zen2

2023-07-26 11:22 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/fe9d72c2f92a4760b7fbc1281ba50788 for a full test report.

2023-07-26 11:23 UTC, verdurin approved these changes
Looks fine.

2023-07-26 11:25 UTC, verdurin commented
Going in, thanks @PetrKralCZ!

2023-07-26 11:25 UTC, merged