{bio}[foss/2021a] purge_dups v1.2.5
easybuilders/easybuild-easyconfigs pull request #18337
Opened 2023-07-19 12:43 UTC by pberthier

(created using `eb --new-pr`)

2023-07-20 14:36 UTC, Micket requested changes

2023-07-20 15:07 UTC, pberthier commented on easybuild/easyconfigs/p/purge_dups/purge_dups-1.2.5-foss-2021a.eb
> +        'checksums': ['bfc8168e986bba3b3b41273006c99f2385f664d66c53348b952ba1b25213a14b'],
ok, did not realize that, just used "eb --inject-checksums --force".  I need to learn something here ;-)

2023-09-19 07:34 UTC, pberthier commented
Test report by @pberthier
**SUCCESS**
Build succeeded for 0 out of 0 (1 easyconfigs in total)
softdev8.ibu.internal - Linux Rocky Linux 8.8 (Green Obsidian), x86_64, AMD EPYC 7742 64-Core Processor, Python 3.11.2
See https://gist.github.com/pberthier/0da1ffdfb929982349693426490400bf for a full test report.

2023-09-19 07:38 UTC, pberthier commented
Test report by @pberthier
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
softdev8.ibu.internal - Linux Rocky Linux 8.8 (Green Obsidian), x86_64, AMD EPYC 7742 64-Core Processor, Python 3.11.2
See https://gist.github.com/pberthier/cae21d2d9815ebe54326cd9e788d1b63 for a full test report.

2025-05-09 11:01 UTC, akesandgren commented
Closing this since foss/2021a is deprecated, see https://docs.easybuild.io/policies/toolchains

Sorry for not getting back to this @pberthier 

If this is still relevant, please consider opening a new pull request using a more recent toolchain

2025-05-09 11:01 UTC, closed without merging