{bio}[GCC/11.3.0] EPA-ng v0.3.8, PLL-modules v20230628, genesis v0.29.0, ...
easybuilders/easybuild-easyconfigs pull request #18419
Opened 2023-07-31 08:36 UTC by smoors

(created using `eb --new-pr`)

2023-07-31 14:46 UTC, casparvl commented
@boegelbot please test @ generoso

2023-07-31 14:49 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
tcn445.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/485c4edab17015f8d84477d555cfda1f for a full test report.

2023-07-31 14:56 UTC, casparvl reviewed
EasyConfigs look good to me. Let's wait for the tests, if they succeed, this can be merged.

2023-07-31 14:56 UTC, casparvl commented on easybuild/easyconfigs/e/EPA-ng/EPA-ng-0.3.8-gompi-2022a.eb
> +EPA-ng - Fast, parallel, highly accurate Maximum Likelihood Phylogenetic
Doesn't this create a new line to start with? E.g. https://github.com/easybuilders/easybuild-easyconfigs/pull/18420/files starts the description right after the `"""`

2023-07-31 14:56 UTC, casparvl commented on easybuild/easyconfigs/g/genesis/genesis-0.29.0-GCC-11.3.0.eb
> +postinstallcmds = ['mkdir -p %%(installdir)s/lib/ && '
I was checking our Generic EasyBlocks. It's funny: we have something for software without `configure`, with `make`, and without `make install` (`makeCp`), as well as for software without `configure`, `make` and `make install` (`cmdCp`), but _not_ for software _with_ a `configure`, a `make`, but no `make install`.

We _should_ really have a `ConfigureMakeCp`... But don't worry, I won't force you to make one (but if you feel like it, I'd encourage it ;-))

2023-07-31 14:57 UTC, casparvl requested changes
Oh, I forgot: I do think the `description` on EPA should be changed (but let me know if you disagree)

2023-07-31 14:58 UTC, casparvl commented
@boegelbot please test @ jsc-zen2

2023-07-31 15:14 UTC, smoors commented
> Hm, the build failure on Generoso suggests that maybe `Bison` and `Flex` are (build)dependencies too?

hm, this is clearly not ready: it's building the deps, which i intended to avoid.
will mark as draft for now

2023-11-22 14:39 UTC, smoors commented
@boegelbot: please test @ generoso

2023-11-22 15:03 UTC, smoors commented
@boegelbot: please test @ generoso EB_ARGS="libpll-2-20230511-GCC-11.3.0.eb"

2024-01-15 10:53 UTC, closed without merging