bokeh 3.2.0 foss/2022b
easybuilders/easybuild-easyconfigs pull request #18461
Opened 2023-08-03 18:54 UTC by fizwit

(created using `eb --new-pr`)

2023-08-04 12:45 UTC, casparvl commented
@boegelbot please test @ generoso

2023-08-04 12:54 UTC, casparvl commented
@boegelbot please test @ jsc-zen2

2023-08-07 15:06 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/8612a4d764b42ec9ce8d65ae4b81a9fb for a full test report.

2023-08-07 16:15 UTC, casparvl requested changes

2023-08-07 16:15 UTC, casparvl commented on easybuild/easyconfigs/b/bokeh/bokeh-3.2.0-foss-2022b.eb
> +        'preinstallopts': """sed -i 's/setup(/setup(version="%(version)s",/g' setup.py && """,
This looks to be new and clearly fixes something in the sources. Can you include a comment what was wrong here that needed to be fixed?

2023-08-07 16:15 UTC, casparvl commented on easybuild/easyconfigs/b/bokeh/bokeh-3.2.0-foss-2022b.eb
> +builddependencies = [
If there are no build dependencies, this can be ommitted.

2023-08-08 10:24 UTC, casparvl commented
@fizwit [this](https://github.com/easybuilders/easybuild-easyconfigs/pull/18470) PR came in and has _a bit_ newer version. Would this also work for you? Also, I see here that `setuptools` and `meson-python` were put in the build dependencies there, which might make more sense?

2023-08-08 16:22 UTC, casparvl commented
Had a small discussion with fellow maintainers on Slack. Though we have definitely _not_ been consistent in the past, there seems to be a preference to using `setuptools` from a seperate EasyConfig as a build dependency.

Wondering how to move forward with this PR, also up to you @fizwit . If you care strongly about this particular version, and the one from [here](https://github.com/easybuilders/easybuild-easyconfigs/pull/18470) doesn't work for you, we can proceed with this PR. At the very least, I think `meson-python` can be moved to build dependencies, right? Then you can ignore my earlier comment in my review. I'd be ok in merging it like that, even if it doesn't use `setuptools` as external dependency.

2023-08-08 21:03 UTC, fizwit commented
Closing PR, the work is duplicated in PR #18470

2023-08-08 21:03 UTC, closed without merging