{lib}[GCCcore/12.3.0] tornado v6.3.2 w/ Python 3.11.3
easybuilders/easybuild-easyconfigs pull request #18511
Opened 2023-08-09 11:44 UTC by surak

(created using `eb --new-pr`)

2023-08-09 11:45 UTC, surak commented
Tornado is necessary for Bokeh and iPython, and by Jupyter. It's better to have a general version for the future than conflicting ones inside other packages. I will add the new bokeh and ipython in time.

2023-08-16 11:12 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/dd7c4c5c3f28781e70ce592302d59732 for a full test report.

2023-08-16 11:48 UTC, casparvl requested changes

2023-08-16 11:48 UTC, casparvl commented on easybuild/easyconfigs/t/tornado/tornado-timeouts.patch
> +diff -Naur tornado.orig/tornado-6.1/tornado/httpclient.py tornado/tornado-6.1/tornado/httpclient.py
Can you put a comment in the past to indicate what it fixes? What was the error, is there an upstream issue...?

2023-08-23 16:15 UTC, casparvl commented
@boegelbot please test @ jsc-zen2

2023-08-23 17:36 UTC, casparvl approved these changes
Lgtm

2023-08-23 17:37 UTC, casparvl commented
Going in, thanks @surak!

2023-08-23 17:37 UTC, merged