{lib}[GCCcore/12.2.0,foss/2022b] Mikado v2.3.4, Greenlet v2.0.2, drmaa-python v0.7.9, ...
easybuilders/easybuild-easyconfigs pull request #18614
Opened 2023-08-22 11:18 UTC by PetrKralCZ

(created using `eb --new-pr`)

2023-08-22 12:08 UTC, PetrKralCZ commented
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4001.donphan.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 530.30.02, Python 3.6.8
See https://gist.github.com/PetrKralCZ/08b55ba308e246d6d85c154144fa07c1 for a full test report.

2023-08-22 12:10 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2023-08-24 06:41 UTC, PetrKralCZ commented
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4001.donphan.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 530.30.02, Python 3.6.8
See https://gist.github.com/PetrKralCZ/c14d768db811f3878e2d4629d06e4fc9 for a full test report.

2023-08-30 16:52 UTC, boegel requested changes

2023-08-30 16:52 UTC, boegel commented on easybuild/easyconfigs/m/Mikado/Mikado-2.3.4-foss-2022b.eb
> +    ('Greenlet', '2.0.2'),
add `drmaa-python` as commented out dependency, along with a comment to explain why it can be useful, and why it's commented out

2023-08-30 16:52 UTC, boegel commented on easybuild/easyconfigs/m/Mikado/Mikado-2.3.4-foss-2022b.eb
> +local_code_patch_cmd = f"sed -i 's/{local_old_line}/{local_new_line}/g' setup.py"
F-strings only work with Python 3.6, strictly speaking EasyBuild is still compatible with Python 2, so we shouldn't use them yet:

```suggestion
local_code_patch_cmd = "sed -i 's/%s/%s/g' setup.py" % (local_old_line, local_new_line)

2023-08-30 16:52 UTC, boegel commented on easybuild/easyconfigs/m/Mikado/Mikado-2.3.4-foss-2022b.eb
> +        'preinstallopts': f"{local_code_patch_cmd} && {local_dep_patch_cmd} && ",
same here, we shouldn't use f-strings yet...

2023-08-30 16:52 UTC, boegel commented on easybuild/easyconfigs/s/slurm-drmaa/slurm-drmaa-1.1.3-GCCcore-12.2.0.eb
> +}
Order entries alphabetically, no need to extend this across multiple lines, and use `SHLIB_EXT`:

```suggestion
sanity_check_paths = {
    'files': ['bin/drmaa-run', 'include/drmaa.h', 'lib/libdrmaa.a', 'lib/libdrmaa.%s' % SHLIB_EXT],
    'dirs': ['etc'],
}

2023-08-31 11:02 UTC, PetrKralCZ commented
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node4005.donphan.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 530.30.02, Python 3.6.8
See https://gist.github.com/PetrKralCZ/74d9332faa647ed55e5ad5bf2f2b1295 for a full test report.

2023-09-05 07:56 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/b3a29926b8366c24b3308ba57d1b5826 for a full test report.

2023-09-05 07:58 UTC, boegel commented
@boegelbot please test @ generoso

2023-09-05 07:58 UTC, boegel approved these changes

2023-09-05 13:24 UTC, boegel commented
Going in, thanks @PetrKralCZ!

2023-09-05 13:24 UTC, merged