new easyconfig for leafcutterMD and an update of R-bundle-Bioconductor with depencies for leafcutterMD
easybuilders/easybuild-easyconfigs pull request #18615
Opened 2023-08-22 11:38 UTC by laraPPr

(created using `eb --new-pr`)

2023-08-22 12:49 UTC, laraPPr commented
Test report by @laraPPr
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
node3541.doduo.os - Linux RHEL 8.6 (Ootpa), x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.10.8
See https://gist.github.com/laraPPr/0dff3d81c269b35c205a57954d0820f2 for a full test report.

2023-08-22 13:14 UTC, boegel requested changes

2023-08-22 13:14 UTC, boegel commented on easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.16-foss-2022b-R-4.2.2.eb
> -    ('UCell', '2.2.0', {
You're (probably accidentally) removing extensions here (probably you were using an older copy of this easyconfig, see #18552), please restore `UCell` and `decoupleR`.

Ideally adding extensions to `R-bundle-Bioconductor` is done in a separate PR so it stands out a bit, but we'll go ahead as is here.

2023-08-22 13:40 UTC, boegel commented
@boegelbot please test @ generoso
EB_ARGS="--skip"

2023-08-22 14:03 UTC, boegel commented
@boegelbot please test @ jsc-zen2
EB_ARGS="--skip"

2023-08-22 17:12 UTC, boegel commented
@boegelbot please test @ jsc-zen2
EB_ARGS="--sanity-check-only"

2023-08-23 15:27 UTC, boegel commented
`--sanity-check-only` failed with "`/bin/bash: R: command not found`" because of a bug in `RPackage` easyblock, which makes it incompatible with `--sanity-check-only`, similar to what we had for `PythonPackage` before https://github.com/easybuilders/easybuild-easyblocks/pull/2828 was fixed...

2023-08-23 15:27 UTC, boegel commented
@boegelbot please test @ jsc-zen2
EB_ARGS="--skip"

2023-08-24 09:38 UTC, boegel commented
@boegelbot please test @ jsc-zen2
EB_ARGS="leafcutter-0.2.9-foss-2022b-R-4.2.2.eb"

2023-08-24 10:31 UTC, boegel approved these changes

2023-08-24 10:31 UTC, boegel commented
Going in, thanks @laraPPr!

2023-08-24 10:31 UTC, merged