{bio}[GCCcore/11.3.0,foss/2022a] vcflib v1.0.9, WFA2 v2.3.3 w/ R 4.2.1
easybuilders/easybuild-easyconfigs pull request #18636
Opened 2023-08-24 08:53 UTC by PetrKralCZ

(created using `eb --new-pr`)

2023-08-24 09:51 UTC, PetrKralCZ commented
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4001.donphan.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 530.30.02, Python 3.6.8
See https://gist.github.com/PetrKralCZ/d80fcdf1afbc30d6a88b50f55ba4e712 for a full test report.

2023-08-24 10:01 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2023-08-30 16:54 UTC, boegel requested changes

2023-08-30 16:54 UTC, boegel commented on easybuild/easyconfigs/v/vcflib/vcflib-1.0.9-foss-2022a-R-4.2.1.eb
> +        'lib/pyvcflib.cpython-310-x86_64-linux-gnu.so',
I wouldn't check for this file specifically due to the messy filename (which is CPU-type specific, won't work on Arm), and check whether `import pyvcflib` works instead (probably needs adding `lib` to `$PYTHONPATH` via `modextrapaths`?).

Also, no need to spread this across multiple lines then?

2023-08-31 10:50 UTC, PetrKralCZ commented
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node4005.donphan.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 530.30.02, Python 3.6.8
See https://gist.github.com/PetrKralCZ/7f0bf5a91c7e1ed864ff565888acd857 for a full test report.

2023-08-31 10:53 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2023-09-05 07:39 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/aab5d84fc07fb304add742b0fb45dfa4 for a full test report.

2023-09-05 07:47 UTC, boegel approved these changes

2023-09-05 07:48 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2023-09-05 08:03 UTC, boegel commented
Going in, thanks @PetrKralCZ!

2023-09-05 08:03 UTC, merged