{data}[GCCcore/12.3.0] HDF v4.2.16-2
easybuilders/easybuild-easyconfigs pull request #18728
Opened 2023-09-06 11:02 UTC by stefan-wolfsheimer

(created using `eb --new-pr`)

2023-09-06 11:05 UTC, stefan-wolfsheimer commented
I could not test if the software builds on ARM. 
The patch introduced in 4.2.15 does not work anymore 4.2.16-2.

2023-09-11 08:01 UTC, branfosj commented
> I could not test if the software builds on ARM. The patch introduced in 4.2.15 does not work anymore 4.2.16-2.

I searched through the commits and looked at the HDF4 code. It appears that they've made a big change to how different architectures are handled and I believe this means that ARM will not need a patch.

2023-09-11 08:01 UTC, branfosj commented
@boegelbot please test @ generoso

2023-09-11 09:23 UTC, branfosj requested changes

2023-09-11 09:23 UTC, branfosj commented on easybuild/easyconfigs/h/HDF/HDF-4.2.16-2-GCCcore-12.3.0.eb
> +
```suggestion
local_common_configopts = '--with-szlib=$EBROOTSZIP CFLAGS="$CFLAGS -I$EBROOTLIBTIRPC/include/tirpc" '
local_common_configopts += '--includedir=%(installdir)s/include/%(namelower)s '
configopts = [
    local_common_configopts,
    # Cannot build shared libraries and Fortran...
    # https://trac.osgeo.org/gdal/wiki/HDF#IncompatibilitywithNetCDFLibraries
    # netcdf must be disabled to allow HDF to be used by GDAL
    local_common_configopts + "--enable-shared --disable-fortran --disable-netcdf",
]
```

With `configopts` as a list we end up building once per item in the list.

2023-09-18 19:49 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.16
See https://gist.github.com/SebastianAchilles/d85deaa8bfbfa008806247497fccb961 for a full test report.

2023-09-18 19:49 UTC, SebastianAchilles commented
@boegelbot please test @ generoso

2023-09-18 19:53 UTC, SebastianAchilles commented
@boegelbot please test @ jsc-zen2

2023-09-19 17:14 UTC, SebastianAchilles approved these changes
lgtm

2023-09-19 17:16 UTC, SebastianAchilles commented
Going in, thanks @stefan-wolfsheimer!

2023-09-19 17:16 UTC, merged