{data}[foss/2023a] GDAL v3.7.1
easybuilders/easybuild-easyconfigs pull request #18732
Opened 2023-09-06 14:25 UTC by stefan-wolfsheimer

(created using `eb --new-pr`)

2023-09-11 09:24 UTC, branfosj requested changes

2023-09-11 09:24 UTC, branfosj commented on easybuild/easyconfigs/g/GDAL/GDAL-3.7.1-foss-2023a.eb
> +]
Similar to #18728, this is changing the `configopts` compared to the recent easyconfigs.

2023-09-19 17:37 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.16
See https://gist.github.com/SebastianAchilles/befc1e4d3ad5c7323914e5a2775d5365 for a full test report.

2023-09-24 17:27 UTC, SebastianAchilles commented
@boegelbot please test @ jsc-zen2

2023-09-25 06:31 UTC, SebastianAchilles commented on easybuild/easyconfigs/g/GDAL/GDAL-3.7.1-foss-2023a.eb
> +    ('libxml2', '2.11.4'),
I think `libarchive` is required to fix `libgdal.so.33: undefined symbol: archive_read_support_format_rar5`

```suggestion
    ('SQLite', '3.42.0'),
    ('libarchive', '3.6.2'),
    ('libxml2', '2.11.4'),
```

2023-09-27 15:16 UTC, SebastianAchilles commented
@boegelbot please test @ jsc-zen2

2023-09-27 17:40 UTC, SebastianAchilles commented
@boegelbot please test @ generoso

2023-10-14 07:23 UTC, SebastianAchilles requested changes

2023-10-14 07:23 UTC, SebastianAchilles commented on easybuild/easyconfigs/g/GDAL/GDAL-3.7.1-foss-2023a.eb
> +    'files': ['lib/libgdal.a', 'lib/libgdal.so'],
```suggestion
    'files': ['lib/libgdal.a', 'lib/libgdal.%s' % SHLIB_EXT],
```

2023-10-14 07:34 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-ubuntu-2304 - Linux Ubuntu 23.04 (Lunar Lobster), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.11.2
See https://gist.github.com/SebastianAchilles/269622ad5c2698bbe443aa9b1a9a9778 for a full test report.

2023-10-14 07:38 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bwd-rockylinux-92 - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (broadwell), Python 3.9.16
See https://gist.github.com/SebastianAchilles/35e779e1a960dd5f734223e04f5c6375 for a full test report.

2023-10-27 11:46 UTC, SebastianAchilles approved these changes
lgtm

2023-10-27 11:49 UTC, SebastianAchilles commented
Going in, thanks @stefan-wolfsheimer!

2023-10-27 11:49 UTC, merged