{lib}[GCCcore/12.3.0] tbb v2021.10.0
easybuilders/easybuild-easyconfigs pull request #18747
Opened 2023-09-08 12:01 UTC by maxim-masterov

(created using `eb --new-pr`)

2023-09-09 11:37 UTC, branfosj requested changes

2023-09-09 11:37 UTC, branfosj commented on easybuild/easyconfigs/t/tbb/tbb-2021.10.0_GCC_12_fix_compiler_error.patch
> +# What: Fix compiler error of address XXX will never be NULL.
We already have this patch: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/t/tbb/tbb-2021.10.0_null-address.patch

2023-09-09 11:37 UTC, branfosj commented on easybuild/easyconfigs/t/tbb/tbb-2021.10.0-GCCcore-12.3.0.eb
> +]
```suggestion
patches = ['%(name)s-%(version)s_null-address.patch']
checksums = [
    {'v2021.10.0.tar.gz': '487023a955e5a3cc6d3a0d5f89179f9b6c0ae7222613a7185b0227ba0c83700b'},
    {'tbb-2021.10.0_null-address.patch': '9deb243eb9d9d86f37f5e1e919cf8ff440c8b9be9c00ec14fddc437e433f0d1c'},
]
```

2025-06-16 15:24 UTC, bartoldeman commented
This PR was superseded by #19352

2025-06-16 15:24 UTC, closed without merging