{chem}[GCC/10.2.0,GCC/10.3.0,GCC/11.2.0,GCC/11.3.0,GCC/12.2.0,GCC/9.3.0] NBO v7.0.10
easybuilders/easybuild-easyconfigs pull request #18794
Opened 2023-09-15 15:19 UTC by sassy-crick

(created using `eb --new-pr`)

2023-09-18 06:24 UTC, SebastianAchilles requested changes
Using the `GCC` toolchain and adding `FlexiBLAS` or `OpenBLAS` as dependency is possible, but I would rather use toolchain that already contains a BLAS library.

Please note that adding `FlexiBLAS` and `OpenBLAS` at the same time is not possible, only `FlexiBLAS` should be used.

From 2022a onward we added the toolchain `gfbf` (GCC + FlexiBLAS + FFTW serial). This might be a good choice for a software that needs `GCC` and a `BLAS` library.

2023-09-18 06:24 UTC, SebastianAchilles commented on easybuild/easyconfigs/n/NBO/NBO-7.0.10-GCC-10.3.0.eb
> +    ('OpenBLAS', '0.3.17'),
```suggestion
```

2023-09-18 06:24 UTC, SebastianAchilles commented on easybuild/easyconfigs/n/NBO/NBO-7.0.10-GCC-11.2.0.eb
> +    ('OpenBLAS', '0.3.18'),
```suggestion
```

2023-09-18 06:24 UTC, SebastianAchilles commented on easybuild/easyconfigs/n/NBO/NBO-7.0.10-GCC-11.3.0.eb
> +    ('OpenBLAS', '0.3.20'),
```suggestion
```

2023-09-18 06:24 UTC, SebastianAchilles commented on easybuild/easyconfigs/n/NBO/NBO-7.0.10-GCC-12.2.0.eb
> +    ('OpenBLAS', '0.3.21'),
```suggestion
```

2023-09-19 16:45 UTC, sassy-crick commented
Thanks for looking into that. I done the suggested changes and done some polishing of the files as well. The patchfile sets `OpenBLAS` as the default BLAS, so I removed that where appropriated in the EC file. I hope it makes sense.

2023-09-20 12:13 UTC, SebastianAchilles requested changes
I would also add `download_instructions` the easyconfigs.

2023-09-20 12:13 UTC, SebastianAchilles commented on easybuild/easyconfigs/n/NBO/NBO-7.0.10-GCC-10.2.0.eb
> +# The dowloaded tarball does not contain the bug-fix version so rename to nbo7.0.10-src.tar.gz
```suggestion
download_instructions = """
NBO7 is proprietary software, order here: https://charge.wisc.edu/chemistry/order_nbo7.aspx
The dowloaded tarball does not contain the bug-fix version so rename to nbo7.0.10-src.tar.gz
"""
```

2023-09-20 12:13 UTC, SebastianAchilles commented on easybuild/easyconfigs/n/NBO/NBO-7.0.10-GCC-10.3.0.eb
> +# The dowloaded tarball does not contain the bug-fix version so rename to nbo7.0.10-src.tar.gz
```suggestion
download_instructions = """
NBO7 is proprietary software, order here: https://charge.wisc.edu/chemistry/order_nbo7.aspx
The dowloaded tarball does not contain the bug-fix version so rename to nbo7.0.10-src.tar.gz
"""
```

2023-09-20 12:13 UTC, SebastianAchilles commented on easybuild/easyconfigs/n/NBO/NBO-7.0.10-GCC-11.2.0.eb
> +# The dowloaded tarball does not contain the bug-fix version so rename to nbo7.0.10-src.tar.gz
```suggestion
download_instructions = """
NBO7 is proprietary software, order here: https://charge.wisc.edu/chemistry/order_nbo7.aspx
The dowloaded tarball does not contain the bug-fix version so rename to nbo7.0.10-src.tar.gz
"""
```

2023-09-20 12:13 UTC, SebastianAchilles commented on easybuild/easyconfigs/n/NBO/NBO-7.0.10-GCC-9.3.0.eb
> +# The dowloaded tarball does not contain the bug-fix version so rename to nbo7.0.10-src.tar.gz
```suggestion
download_instructions = """
NBO7 is proprietary software, order here: https://charge.wisc.edu/chemistry/order_nbo7.aspx
The dowloaded tarball does not contain the bug-fix version so rename to nbo7.0.10-src.tar.gz
"""
```

2023-09-20 12:13 UTC, SebastianAchilles commented on easybuild/easyconfigs/n/NBO/NBO-7.0.10-gfbf-2022a.eb
> +# The dowloaded tarball does not contain the bug-fix version so rename to nbo7.0.10-src.tar.gz
```suggestion
download_instructions = """
NBO7 is proprietary software, order here: https://charge.wisc.edu/chemistry/order_nbo7.aspx
The dowloaded tarball does not contain the bug-fix version so rename to nbo7.0.10-src.tar.gz
"""
```

2023-09-20 12:13 UTC, SebastianAchilles commented on easybuild/easyconfigs/n/NBO/NBO-7.0.10-gfbf-2022b.eb
> +# The dowloaded tarball does not contain the bug-fix version so rename to nbo7.0.10-src.tar.gz
```suggestion
download_instructions = """
NBO7 is proprietary software, order here: https://charge.wisc.edu/chemistry/order_nbo7.aspx
The dowloaded tarball does not contain the bug-fix version so rename to nbo7.0.10-src.tar.gz
"""
```

2023-09-20 14:18 UTC, sassy-crick commented
Test report by @sassy-crick
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
hp - Linux Debian GNU/Linux 11, x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.9.2
See https://gist.github.com/sassy-crick/c7cdbf698181f5021a4b8d7d6980e4c4 for a full test report.

2023-09-20 14:36 UTC, sassy-crick commented
Done. I have added the install instructions as suggested, and uploaded the test report. I hope that helps

2023-10-04 15:54 UTC, SebastianAchilles approved these changes
lgtm

2023-10-04 15:55 UTC, SebastianAchilles commented
Going in, thanks @sassy-crick!

2023-10-04 15:55 UTC, merged