{bio}[gompi/2022b] ProBiS v20230403
easybuilders/easybuild-easyconfigs pull request #18830
Opened 2023-09-19 08:30 UTC by ItIsI-Orient

(created using `eb --new-pr`)

2023-09-19 10:57 UTC, ItIsI-Orient commented
@boegelbot please test @ generoso

2023-09-19 19:43 UTC, ItIsI-Orient commented
@boegelbot please test @ jsc-zen2

2023-09-26 14:55 UTC, boegel requested changes

2023-09-26 14:55 UTC, boegel commented on easybuild/easyconfigs/p/ProBiS/ProBiS-20230403-gompi-2022b.eb
> +buildopts = 'probis CC="mpic++" CFLAGS="-std=c++11 -O3 -Wall -Wno-unused-function -DNDEBUG -pthread"'
avoid hardcoding `mpic++` and `-std=c++11 -O3`:

```suggestion
buildopts = 'probis CC="$MPICXX" CFLAGS="$CFLAGS -Wall -Wno-unused-function -DNDEBUG -pthread"'
```

2023-09-26 14:55 UTC, boegel commented on easybuild/easyconfigs/p/ProBiS/ProBiS-20230403-gompi-2022b.eb
> +toolchain = {'name': 'gompi', 'version': '2022b'}
```suggestion
toolchain = {'name': 'gompi', 'version': '2022b'}
toolchainopts = {'cstd': 'c++11'}

2023-09-26 14:56 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2023-09-26 14:57 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3157.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/bba9cbbbd63f1d2d6160d99a0aed095e for a full test report.

2023-09-26 18:03 UTC, boegel commented
Going in, thanks @ItIsI-Orient!

2023-09-26 18:03 UTC, merged