{phys}[foss/2021a] Yambo v5.1.1
easybuilders/easybuild-easyconfigs pull request #18905
Opened 2023-10-03 13:07 UTC by TopRichard

(created using `eb --new-pr`)

2023-10-10 12:53 UTC, smoors requested changes
why did you remove the dependencies PETSc and SLEPc, which are included in Yambo-5.1.2-intel-2021b.eb?
you also removed `--enable-par-linalg`, why?

2023-10-10 12:53 UTC, smoors commented on easybuild/easyconfigs/y/Yambo/Yambo-5.1.1-foss-2021a.eb
> +local_copy_cmd_pattern = 'cp %s yambo-%(version)s/lib/archive/'
why are you defining a local variable if you use it only once?
```suggestion
```

2023-10-10 13:01 UTC, TopRichard commented on easybuild/easyconfigs/y/Yambo/Yambo-5.1.1-foss-2021a.eb
> +}
The request i had didn't require those options, so not intentional.

2023-10-10 13:04 UTC, TopRichard commented on easybuild/easyconfigs/y/Yambo/Yambo-5.1.1-foss-2021a.eb
> +parallel = 4
Can be less, based on previous trials.

2023-10-10 13:05 UTC, TopRichard commented on easybuild/easyconfigs/y/Yambo/Yambo-5.1.1-foss-2021a.eb
> +]
During the build, it overwrites the files, since it runs twice.

2023-10-10 13:06 UTC, TopRichard commented on easybuild/easyconfigs/y/Yambo/Yambo-5.1.1-foss-2021a.eb
> +cleanupoldinstall = False
Else it overwrites the files.

2023-10-10 14:33 UTC, TopRichard commented on easybuild/easyconfigs/y/Yambo/Yambo-5.1.1-foss-2021a.eb
> +        'filename': '0.0.2.tar.gz',
Sorry didn't get exactly what you mean as the version is mentioned at top.

2023-10-10 14:49 UTC, smoors commented on easybuild/easyconfigs/y/Yambo/Yambo-5.1.1-foss-2021a.eb
> +        'filename': '0.0.2.tar.gz',
like this: https://github.com/easybuilders/easybuild-easyconfigs/blob/823ba108188ed3fa465faec2a194f1657a9d896d/easybuild/easyconfigs/y/Yambo/Yambo-5.1.2-intel-2021b.eb#L6

2023-10-10 18:47 UTC, TopRichard commented on easybuild/easyconfigs/y/Yambo/Yambo-5.1.1-foss-2021a.eb
> +        'filename': '0.0.2.tar.gz',
Done

2024-01-31 10:50 UTC, TopRichard commented on easybuild/easyconfigs/y/Yambo/Yambo-5.1.1-foss-2021a.eb
> +]
Updated the PR with the usage if another easyblock and skipping the install step.

2024-01-31 10:52 UTC, TopRichard commented on easybuild/easyconfigs/y/Yambo/Yambo-5.1.1-foss-2021a.eb
> +cleanupoldinstall = False
Used another easyblock and skipped the install step.

2025-05-09 11:03 UTC, akesandgren commented
Closing this since foss/2021a is deprecated, see https://docs.easybuild.io/policies/toolchains

Sorry for not getting back to this @TopRichard 

If this is still relevant, please consider opening a new pull request using a more recent toolchain

2025-05-09 11:03 UTC, closed without merging