{geo}[foss/2022a] rasterstats v0.19.0 w/ Python 3.10.4
easybuilders/easybuild-easyconfigs pull request #18918
Opened 2023-10-05 09:21 UTC by WilleBell

(created using `eb --new-pr`)

2023-10-05 14:12 UTC, branfosj requested changes

2023-10-05 14:12 UTC, branfosj commented on easybuild/easyconfigs/r/rasterstats/rasterstats-0.19.0-foss-2022a.eb
> +    }),
```suggestion
```

This is in [Python/3.10.4](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/Python/Python-3.10.4-GCCcore-11.3.0.eb#L339)

2023-10-05 14:12 UTC, branfosj commented on easybuild/easyconfigs/r/rasterstats/rasterstats-0.19.0-foss-2022a.eb
> +    }),
```suggestion
```

This is in [Python/3.10.4](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/Python/Python-3.10.4-GCCcore-11.3.0.eb#L428)

2023-10-05 14:52 UTC, branfosj commented
@boegelbot please test @ generoso

2023-10-05 14:58 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/24464a73f0efa0a6aff46bb670b6623d for a full test report.

2023-10-05 15:10 UTC, branfosj commented
@boegelbot please test @ jsc-zen2

2023-10-06 08:48 UTC, WilleBell commented
Test report by @WilleBell
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node300.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/WilleBell/1d07e0468c9746c024a30298a56ebad7 for a full test report.

2023-10-06 08:49 UTC, branfosj approved these changes

2023-10-06 08:50 UTC, branfosj commented
Going in, thanks @WilleBell!

2023-10-06 08:50 UTC, merged