{devel,lib,system}[GCCcore/13.2.0] ZeroMQ v4.3.5, OpenPGM v5.2.122, libsodium v1.0.19
easybuilders/easybuild-easyconfigs pull request #19055
Opened 2023-10-22 10:18 UTC by Micket

(created using `eb --new-pr`)

2023-10-22 13:58 UTC, SebastianAchilles requested changes

2023-10-22 13:58 UTC, SebastianAchilles commented on easybuild/easyconfigs/l/libsodium/libsodium-1.0.19-GCCcore-13.2.0.eb
> +checksums = ['6f504490b342a4f8a4c4a02fc9b866cbef8622d5df4e5452b46be121e46636c1']
```suggestion
checksums = ['018d79fe0a045cca07331d37bd0cb57b2e838c51bc48fd837a1472e50068bbea']
```

2023-10-22 14:05 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
alvis-c1 - Linux Rocky Linux 8.8, x86_64, Intel Xeon Processor (Skylake), Python 3.6.8
See https://gist.github.com/Micket/32befba8ca53f078b9990f610fa3b8dd for a full test report.

2023-10-22 18:37 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
zen2-ubuntu-2310 - Linux Ubuntu 23.10 (Mantic Minotaur), x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.11.6
See https://gist.github.com/SebastianAchilles/a85465746d9ee61fc1da5ab9e0ce84b4 for a full test report.

2023-10-23 05:58 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3100.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/3ea8a60e6ebb14dc2dc88456d441b74e for a full test report.

2023-10-23 06:32 UTC, boegel approved these changes
lgtm

2023-10-23 06:32 UTC, boegel commented
Going in, thanks @Micket!

2023-10-23 06:32 UTC, merged

2023-10-23 06:34 UTC, boegel commented
@boegelbot please test @ generoso

2023-10-23 06:35 UTC, boegel commented
@boegelbot please test @ jsc-zen2