{lib}[foss/2022a] scikit-lego v0.6.16 w/ Python 3.10.4
easybuilders/easybuild-easyconfigs pull request #19064
Opened 2023-10-23 15:33 UTC by WilleBell

(created using `eb --new-pr`)

2023-10-23 15:47 UTC, WilleBell commented
Test report by @WilleBell
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node301.hydra.os - Linux CentOS Linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 3.6.8
See https://gist.github.com/WilleBell/f2cbc6a87b6683c599c79b33d2422a85 for a full test report.

2023-10-23 20:29 UTC, boegel requested changes

2023-10-23 20:29 UTC, boegel commented on easybuild/easyconfigs/s/scikit-lego/scikit-lego-0.6.16-foss-2022a.eb
> +    ('wrapt', '1.14.1', {
@WilleBell We have an easyconfig for `wrapt` 1.15.0 with `foss/2022a`, any reason you're not using that as a dependency?

2023-10-23 20:29 UTC, boegel commented on easybuild/easyconfigs/s/scikit-lego/scikit-lego-0.6.16-foss-2022a.eb
> +    ('binutils', '2.38'),
`binutils` is not required when using `foss` toolchain (only when using `GCCcore` as toolchain)

2023-11-05 09:02 UTC, boegel approved these changes
lgtm

2023-11-05 09:02 UTC, boegel commented
@boegelbot please test @ generoso

2023-11-05 16:41 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2023-11-06 10:57 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3153.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/7d48ab06fcaeeb8990123fa12c3b67f1 for a full test report.

2023-11-06 11:08 UTC, boegel commented
Going in, thanks @WilleBell!

2023-11-06 11:08 UTC, merged