Scenicplus
easybuilders/easybuild-easyconfigs pull request #19060
Opened 2023-10-23 09:05 UTC by deniskristak

based on: https://github.com/vscentrum/vsc-software-stack/issues/64

- adjustText-0.7.3-foss-2022a.eb
- BioServices-1.11.2-foss-2022a.eb
- gensim-4.3.2-foss-2022a.eb
- MACS2-2.2.9.1-foss-2022a.eb
- pyfasta-0.5.2-foss-2022a.eb
- Levenshtein-0.22.0-foss-2022a.eb
- rapidfuzz-2.13.7-foss-2022a.eb
- scenicplus-1.0.0-foss-2022a.eb
- Sphinx-RTD-Theme-1.3.0-GCCcore-11.3.0.eb

2023-10-31 12:04 UTC, deniskristak commented
`Patch file cattrs-23.1.2-simplify_pyproject.patch for extension scenicplus is missing.` is obviously incorrect, as it is present at changed files

2023-11-07 18:13 UTC, boegel commented on easybuild/easyconfigs/s/scenicplus/scenicplus-1.0.0-foss-2022a.eb
> +    ('Rust', '1.65.0'),  # required (newer version) for setuptools-rust, which is needed for gseapy
`Rust` should probably only be a build dependency here, it's a pain to have this as runtime dependency...

2023-11-22 10:25 UTC, branfosj requested changes

2023-12-02 20:01 UTC, deniskristak commented on easybuild/easyconfigs/l/Levenshtein/Levenshtein-0.22.0-foss-2022a.eb
> +name = 'Levenshtein'
it is because of this change:
https://github.com/maxbachmann/python-Levenshtein#introduction

2023-12-02 20:09 UTC, deniskristak commented on easybuild/easyconfigs/l/Levenshtein/Levenshtein-0.22.0-foss-2022a.eb
> +osdependencies = [('python-devel', 'python-dev')]
youre right, removed

2023-12-06 11:02 UTC, boegel requested changes

2023-12-06 11:02 UTC, boegel commented on easybuild/easyconfigs/s/scenicplus/scenicplus-1.0.0-foss-2022a.eb
> +    # ('attr', '2.5.1'),
remove?

2023-12-06 11:02 UTC, boegel commented on easybuild/easyconfigs/s/scenicplus/scenicplus-1.0.0-foss-2022a.eb
> +        'sources': ['pyvis-0.3.2-py3-none-any.whl'],
use:

```python
        'sources': ['pyvis-%(version)s-py3-none-any.whl'],

2023-12-17 10:03 UTC, branfosj commented on easybuild/easyconfigs/l/Levenshtein/Levenshtein-0.22.0-foss-2022a.eb
> +homepage = 'https://pypi.org/project/python-Levenshtein/'
```suggestion
homepage = 'https://pypi.org/project/Levenshtein/'
```

2023-12-17 10:03 UTC, branfosj commented on easybuild/easyconfigs/l/Levenshtein/Levenshtein-0.22.0-foss-2022a.eb
> +name = 'Levenshtein'
Thanks. We should update the homepage then: https://github.com/easybuilders/easybuild-easyconfigs/pull/19060/files#r1429111440

2024-07-29 12:46 UTC, pavelToman commented
New PR that should resolved SCENIC+ issue:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21085

2025-03-19 13:54 UTC, closed without merging