{bio}[Java/11] GEMmotf-3.4
easybuilders/easybuild-easyconfigs pull request #19117
Opened 2023-10-31 02:34 UTC by wdlingit

The abbreviation of this tool (GEM) is the same with another tool so I appended "motif".

2025-06-16 15:20 UTC, sassy-crick commented
@wdlingit You might want to sync your PR with development, something like this: 
```
eb --sync-pr-with-develop NUMBER_OF_PR
```

2026-08-11 08:34 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (total: 10 secs) (1 easyconfigs in total)
node4208.shinx.os - Linux RHEL 9.6, x86_64, AMD EPYC 9654 96-Core Processor (zen4), Python 3.9.21
See https://gist.github.com/boegel/6b375be20a76cfa791cfa8cb8a117b4c for a full test report.

2026-08-11 08:36 UTC, boegel approved these changes
lgtm

2026-08-11 08:36 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2026-08-11 11:22 UTC, boegel requested changes

2026-08-11 11:22 UTC, boegel commented on easybuild/easyconfigs/g/GEMmotif/GEMmotif-3.4-Java-11.eb
> +easyblock = 'JAR'
```suggestion
easyblock = 'Binary'

2026-08-11 11:23 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2026-08-11 11:44 UTC, boegel approved these changes
lgtm

2026-08-11 11:44 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (total: 11 secs) (1 easyconfigs in total)
node4208.shinx.os - Linux RHEL 9.6, x86_64, AMD EPYC 9654 96-Core Processor (zen4), Python 3.9.21
See https://gist.github.com/boegel/92d40778fba78405094554cc805c3cdf for a full test report.

2026-08-11 11:46 UTC, boegel commented
Going in, thanks @wdlingit!

2026-08-11 11:46 UTC, merged