{bio}[foss/2022a] cryoCARE v0.3.0 /w CUDA 11.7.0
easybuilders/easybuild-easyconfigs pull request #19168
Opened 2023-11-07 12:43 UTC by ThomasHoffmann77

(created using `eb --new-pr`)

2023-11-08 09:19 UTC, verdurin requested changes

2023-11-08 09:19 UTC, verdurin commented on easybuild/easyconfigs/c/cryoCARE/cryoCARE-0.3.0-foss-2022a-CUDA-11.7.0.eb
> +
@ThomasHoffmann77 please remove the end of file blank line to appease the bot.

2023-11-08 11:12 UTC, ThomasHoffmann77 commented
@verdurin How would I fix `Conflict found for dependencies of cryoCARE-0.3.0-foss-2022a-CUDA-11.7.0: TensorFlow-2.11.0-foss-2022a vs TensorFlow-2.11.0-foss-2022a-CUDA-11.7.0`?

2023-11-08 11:25 UTC, branfosj commented
> @verdurin How would I fix `Conflict found for dependencies of cryoCARE-0.3.0-foss-2022a-CUDA-11.7.0: TensorFlow-2.11.0-foss-2022a vs TensorFlow-2.11.0-foss-2022a-CUDA-11.7.0`?

CSBDeep has a dependency on the CPU only TF (`TensorFlow-2.11.0-foss-2022a.eb`). So there should be a `CSBDeep-0.7.4-foss-2022a-CUDA-11.7.0.eb` that changes the TF dep to be the CUDA enabled version and then this PR should depend on that.

Also, does this need `tifffile`, as CSBDeep is providing a different version.

2024-02-10 13:40 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
bear-pg0208u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), 1 x NVIDIA NVIDIA A100-SXM4-40GB, 520.61.05, Python 3.6.8
See https://gist.github.com/branfosj/c245cc5d9fd2122242d07de54dbe8e48 for a full test report.

2024-02-10 13:40 UTC, branfosj approved these changes

2024-02-10 13:41 UTC, branfosj commented
Going in, thanks @ThomasHoffmann77!

2024-02-10 13:41 UTC, merged