{math}[GCCcore/11.3.0] PARI-GP v2.15.4
easybuilders/easybuild-easyconfigs pull request #19198
Opened 2023-11-11 08:10 UTC by migueldiascosta

(created using `eb --new-pr`)

2023-11-11 08:14 UTC, migueldiascosta commented
@boegelbot please test @ generoso

2023-11-11 08:33 UTC, migueldiascosta commented
@boegelbot please test @ generoso

2023-11-11 08:44 UTC, migueldiascosta commented
@boegelbot please test @ jsc-zen2

2023-11-12 20:32 UTC, boegel requested changes

2023-11-12 20:32 UTC, boegel commented on easybuild/easyconfigs/p/PARI-GP/PARI-GP-2.15.4-GCCcore-11.3.0.eb
> +}
```suggestion
}

sanity_check_commands = ["gp --help"]

2023-11-12 20:40 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3120.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/8004b024ad1d4085794b9393b4b3ce8a for a full test report.

2023-11-12 20:41 UTC, boegel approved these changes

2023-11-12 20:52 UTC, boegel commented
Going in, thanks @migueldiascosta!

2023-11-12 20:52 UTC, merged