{math}[GCCcore/11.3.0] Givaro v4.2.0
easybuilders/easybuild-easyconfigs pull request #19195
Opened 2023-11-11 07:46 UTC by migueldiascosta

(created using `eb --new-pr`)

2023-11-11 07:52 UTC, migueldiascosta commented
@boegelbot please test @ generoso

2023-11-11 07:56 UTC, migueldiascosta commented
@boegelbot please test @ jsc-zen2

2023-11-12 20:08 UTC, boegel requested changes

2023-11-12 20:08 UTC, boegel commented on easybuild/easyconfigs/g/Givaro/Givaro-4.2.0-GCCcore-11.3.0.eb
> +}
```suggestion
}

sanity_check_commands = ["givaro-config --help"]

2023-11-12 20:13 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3120.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/176d2799143bdc5b9ec8d5f33ddd7cc9 for a full test report.

2023-11-12 20:15 UTC, boegel approved these changes

2023-11-12 20:33 UTC, boegel commented
Going in, thanks @migueldiascosta!

2023-11-12 20:33 UTC, merged