{math}[GCC/11.3.0] nauty v2.8.6
easybuilders/easybuild-easyconfigs pull request #19197
Opened 2023-11-11 08:04 UTC by migueldiascosta

(created using `eb --new-pr`)

2023-11-11 08:07 UTC, migueldiascosta commented
@boegelbot please test @ generoso

2023-11-11 08:14 UTC, migueldiascosta commented
@boegelbot please test @ jsc-zen2

2023-11-12 20:31 UTC, boegel requested changes

2023-11-12 20:31 UTC, boegel commented on easybuild/easyconfigs/n/nauty/nauty-2.8.6-GCC-11.3.0.eb
> +}
```suggestion
}

sanity_check_commands = ["dreadnaut --help"]

2023-11-12 20:34 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3120.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/de8244c0612dc184605c1c41cbf9f535 for a full test report.

2023-11-12 20:41 UTC, boegel approved these changes

2023-11-12 20:53 UTC, boegel commented
Going in, thanks @migueldiascosta!

2023-11-12 20:53 UTC, merged