{math}[gompi/2022a] lrslib v7.2
easybuilders/easybuild-easyconfigs pull request #19196
Opened 2023-11-11 07:57 UTC by migueldiascosta

(created using `eb --new-pr`)

2023-11-11 07:59 UTC, migueldiascosta commented
@boegelbot please test @ generoso

2023-11-11 08:06 UTC, migueldiascosta commented
@boegelbot please test @ jsc-zen2

2023-11-12 20:10 UTC, boegel requested changes

2023-11-12 20:10 UTC, boegel commented on easybuild/easyconfigs/l/lrslib/lrslib-7.2-gompi-2022a.eb
> +}
```suggestion
}

sanity_check_commands = ["lrsnash --help 2>&1 | grep 'usage.*lrsnash'"]

2023-11-12 20:14 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3120.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/02dd3bcdfbd41d1b977736799bd88a01 for a full test report.

2023-11-12 20:16 UTC, boegel approved these changes

2023-11-12 20:33 UTC, boegel commented
Going in, thanks @migueldiascosta!

2023-11-12 20:33 UTC, merged