{chem}[foss/2022b] xtb v6.6.1
easybuilders/easybuild-easyconfigs pull request #19225
Opened 2023-11-13 13:20 UTC by sassy-crick

(created using `eb --new-pr`)

2025-05-22 07:16 UTC, akesandgren commented
Test report by @akesandgren
**FAILED**
Failed during parsing of the easyconfigs, so no ecs were built (1 easyconfigs in total)
b-cn1611.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 555.58.02, Python 3.10.12
See https://gist.github.com/akesandgren/06b788d2f7b2508e096965df68e2755b for a full test report.

2025-05-22 07:19 UTC, akesandgren requested changes

2025-05-22 07:19 UTC, akesandgren commented on easybuild/easyconfigs/x/xtb/xtb-6.6.1-foss-2022b.eb
> +    ('tblite', '0.3.0'),
Needs an upxdate to tblite 0.4.0

2025-05-22 15:58 UTC, jfgrimm commented
see also: https://github.com/grimme-lab/xtb/issues/1091

2025-05-22 16:45 UTC, sassy-crick commented on easybuild/easyconfigs/x/xtb/xtb-6.6.1-foss-2022b.eb
> +    ('tblite', '0.3.0'),
`tblite` is now broken, probably due to some of the requested changes of the modules. The problem seems to be that different subprograms are using different versions of `TOML-Fortran` and as they need to be dependencies, they will be loaded. See also issue  [1091)](https://github.com/grimme-lab/xtb/issues/1091). I am facing similar issues with version `6.7.1`

2025-05-22 19:24 UTC, sassy-crick commented
@boegelbot please test @ jsc-zen3

2025-06-09 07:29 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn1611.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 555.58.02, Python 3.10.12
See https://gist.github.com/akesandgren/0bc5d5a681e07eb90ef0a85f1b34a491 for a full test report.

2025-06-09 07:31 UTC, akesandgren approved these changes
LGTM

2025-06-09 07:32 UTC, akesandgren commented
Going in, thanks @sassy-crick!

2025-06-09 07:32 UTC, merged