{numlib}[gompi/2022a] PFFT v20181230
easybuilders/easybuild-easyconfigs pull request #19255
Opened 2023-11-17 18:35 UTC by lexming

2023-11-28 14:10 UTC, lexming commented
@boegelbot: please test @ generoso

2023-11-29 12:07 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/905f5c2df3462a25665a72a4dd863c1f for a full test report.

2023-11-29 12:09 UTC, verdurin requested changes

2023-11-29 14:25 UTC, lexming commented on easybuild/easyconfigs/p/PFFT/PFFT-20181230-gompi-2022a.eb
> +_commit = 'e4cfcf9902d0ef82cb49ec722040932b6b598c71'
`local_commit` or `_commit` both are ok

2023-12-15 09:14 UTC, smoors commented on easybuild/easyconfigs/p/PFFT/PFFT-20181230-gompi-2022a.eb
> +_commit = 'e4cfcf9902d0ef82cb49ec722040932b6b598c71'
https://docs.easybuild.io/easyconfig-files-local-variables/?h=local#easyconfig_files_local_variables_naming_scheme

2023-12-15 09:20 UTC, smoors approved these changes
lgtm

2023-12-15 09:21 UTC, smoors commented
Going in, thanks @lexming!

2023-12-15 09:21 UTC, merged