fix build of Rust 1.70.0 by disabling download of pre-built LLVM
easybuilders/easybuild-easyconfigs pull request #19264
Opened 2023-11-19 14:20 UTC by boegel

(created using `eb --new-pr`)

2023-11-19 18:46 UTC, boegel commented
@boegelbot please test @ generoso
CORE_CNT=16

2023-11-19 20:34 UTC, boegel commented
@boegelbot please test @ jsc-zen2
CORE_CNT=16

2023-11-19 21:25 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3144.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/73efb7c416f77c71df8a963c3e3e2a5a for a full test report.

2023-11-20 15:27 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/6d0eb5ac11ec462f292081a467a831b1 for a full test report.

2023-11-20 16:34 UTC, verdurin requested changes

2023-11-20 16:34 UTC, verdurin commented on easybuild/easyconfigs/r/Rust/Rust-1.70.0-GCCcore-12.3.0.eb
> +prebuildopts = r"sed -i '/\[llvm\]/d' config.toml && "
@boegel could do with a comment explaining what's going on here?

2023-11-22 23:01 UTC, sassy-crick commented
Test report by @sassy-crick 
SUCCESS
Full report is [here](https://gist.github.com/sassy-crick/858bd8815f24f3731b5820d3d4239daa)

2023-11-23 13:53 UTC, lexming commented
See https://github.com/easybuilders/easybuild-easyblocks/pull/3038 for a more elegant fix :)

2023-11-24 07:00 UTC, boegel commented
@lexming Makes sense to update the easyblock, this was more of a stop-gap solution since I wasn't sure whether older Rust versions were going to be a problem (looks like that's a no).

I'll close this, people can still use `eb --from-pr 19264` to work around this issue until the next EasyBuild release (most likely v4.9.0) that includes https://github.com/easybuilders/easybuild-easyblocks/pull/3038 is out .

2023-11-24 07:01 UTC, closed without merging