{bio}[foss/2022a] HiC-Pro v3.1.0, hic-straw v1.3.1, iced v0.5.10, ... w/ R 4.2.1
easybuilders/easybuild-easyconfigs pull request #19309
Opened 2023-11-24 06:11 UTC by migueldiascosta

(created using `eb --new-pr`)

2023-11-24 06:22 UTC, migueldiascosta commented
@boegelbot please test @ generoso

2023-11-24 07:19 UTC, migueldiascosta commented
@boegelbot please test @ jsc-zen2

2023-11-24 09:36 UTC, migueldiascosta commented
@boegelbot please test @ generoso

2023-11-24 09:57 UTC, migueldiascosta commented
@boegelbot please test @ jsc-zen2

2023-11-24 16:16 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/2c447940ea8855e5f5f9f79e5bd68b54 for a full test report.

2023-11-24 16:24 UTC, verdurin requested changes

2023-11-24 16:24 UTC, verdurin commented on easybuild/easyconfigs/h/HiC-Pro/HiC-Pro-3.1.0-foss-2022a-R-4.2.1.eb
> +homepage = 'http://nservant.github.io/HiC-Pro'
```suggestion
homepage = 'https://nservant.github.io/HiC-Pro'
```

2023-11-24 16:24 UTC, verdurin commented on easybuild/easyconfigs/h/HiC-Pro/HiC-Pro-3.1.0-foss-2022a-R-4.2.1.eb
> +prebuildopts = 'sed -i "s|PREFIX = |PREFIX = %(installdir)s|" config-install.txt && '
Could you add a quick summary of what's going on here, for the benefit of future maintainers?

2023-11-24 16:24 UTC, verdurin commented on easybuild/easyconfigs/h/HiC-Pro/HiC-Pro-3.1.0-foss-2022a-R-4.2.1.eb
> +prebuildopts = 'sed -i "s|PREFIX = |PREFIX = %(installdir)s|" config-install.txt && '
As a comment, I mean.

2023-11-25 03:57 UTC, migueldiascosta commented
@boegelbot please test @ generoso

2023-11-25 04:10 UTC, migueldiascosta commented
@boegelbot please test @ jsc-zen2

2023-11-27 09:54 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/5bcaf7b757f84584c7896f6c53fcd03e for a full test report.

2023-11-27 09:58 UTC, verdurin approved these changes
Looks fine.

2023-11-27 12:50 UTC, merged