{geo}[foss/2021b] BiasAdjustCXX v1.9.1
easybuilders/easybuild-easyconfigs pull request #19341
Opened 2023-11-30 23:48 UTC by TopRichard

(created using `eb --new-pr`)

2023-12-02 15:07 UTC, jfgrimm commented
@boegelbot please test @ generoso

2023-12-02 15:17 UTC, jfgrimm commented
```
== 2023-12-02 15:10:50,746 easyblock.py:4277 WARNING build failed (first 300 chars): Failed to determine CMake version from output of 'cmake --version': /bin/bash: cmake: command not found
```

2023-12-02 15:19 UTC, jfgrimm requested changes

2023-12-02 15:19 UTC, jfgrimm commented on easybuild/easyconfigs/b/BiasAdjustCXX/BiasAdjustCXX-1.9.1-foss-2021b.eb
> +]
you're missing a build dependency on `CMake` here
```suggestion
builddependencies = [
    ('CMake', '3.22.1'),
]

dependencies = [
    ('netCDF', '4.8.1'),
    ('CDO', '2.0.5'),
    ('NCO', '5.0.3'),
]
```

2023-12-03 13:29 UTC, jfgrimm commented
@boegelbot please test @ generoso

2023-12-05 12:34 UTC, jfgrimm commented
@TopRichard I've pushed a change that renames the easyconfig to reflect the toolchain change

2023-12-27 21:06 UTC, smoors commented
@boegelbot: please test @ generoso

2023-12-27 21:14 UTC, smoors commented
>CMakeFiles/BiasAdjustCXX.dir/Manager.cxx.o:Manager.cxx:function Manager::adjust_3d(std::vector<std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >, std::allocator<std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > > >&): error: undefined reference to 'pthread_create'

2023-12-27 21:15 UTC, smoors commented on easybuild/easyconfigs/b/BiasAdjustCXX/BiasAdjustCXX-1.9.1-gompi-2021b.eb
> +preconfigopts = 'CXXFLAGS="$CXXFLAGS -lnetcdf " '
you probably have to add -lpthread here:
```suggestion
preconfigopts = 'CXXFLAGS="$CXXFLAGS -lnetcdf -lpthread" '
```

2023-12-28 08:27 UTC, smoors commented
@boegelbot: please test @ generoso

2023-12-28 08:40 UTC, smoors commented
@boegelbot please test @ jsc-zen2

2023-12-28 09:00 UTC, smoors approved these changes
lgtm

2023-12-28 09:02 UTC, smoors commented
Going in, thanks @TopRichard!

2023-12-28 09:02 UTC, merged