{tools}[system/system] git-lfs v3.4.0
easybuilders/easybuild-easyconfigs pull request #19360
Opened 2023-12-05 15:39 UTC by pavelToman

(created using `eb --new-pr`)

2023-12-05 15:41 UTC, ItIsI-Orient commented
@boegelbot please test @ generoso

2023-12-05 15:49 UTC, ItIsI-Orient commented
@boegelbot please test @ jsc-zen2

2023-12-18 12:39 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2023-12-19 10:05 UTC, pavelToman commented
@boegelbot please test @ jsc-zen2

2023-12-19 10:18 UTC, boegel requested changes

2023-12-19 10:18 UTC, boegel commented on easybuild/easyconfigs/g/git-lfs/git-lfs-3.4.0.eb
> +sanity_check_commands = [('git-lfs', '--version')]
```suggestion
sanity_check_commands = ["git-lfs --version"]

2023-12-19 10:18 UTC, boegel approved these changes

2023-12-19 10:19 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3618.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/boegel/6bc8a8053339ad246174eab665a4a961 for a full test report.

2023-12-19 10:34 UTC, jfgrimm commented
@boegelbot please test @ jsc-zen2

2023-12-19 11:54 UTC, boegel commented
Going in, thanks @pavelToman!

2023-12-19 11:54 UTC, merged