{chem}[intel-compilers/2022.1.0] Multiwfn v3.8_dev
easybuilders/easybuild-easyconfigs pull request #19361
Opened 2023-12-06 10:58 UTC by lexming

(created using `eb --new-pr`)

2023-12-08 09:50 UTC, lexming commented
@boegelbot: please test @ generoso

2023-12-08 11:02 UTC, lexming commented
@boegelbot: please test @ generoso

2023-12-08 12:49 UTC, lexming commented
@boegelbot: please test @ generoso
EB_ARGS="--force-download=sources"

2023-12-08 12:51 UTC, lexming commented
@boegelbot: please test @ generoso
EB_ARGS="--force-download=sources"

2023-12-11 16:23 UTC, verdurin commented
@lexming any idea why it keeps failing on `generoso`?
Latest is 
```== 2023-12-08 12:55:54,149 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:126 in __init__): cmd "sed -i 's/^grep/LC_ALL=C grep/g' noGUI.sh && /bin/bash noGUI.sh && cd noGUI &&  make  -j 4 " exited with exit code 2 and output:
sed: can't read noGUI.sh: No such file or directory```

2024-01-05 15:06 UTC, jfgrimm commented
Test report by @jfgrimm
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
login2.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/6d41bdfb1ef3813cecf98d1c4607eff2 for a full test report.

2024-01-09 08:20 UTC, akesandgren requested changes

2024-01-09 08:20 UTC, akesandgren commented on easybuild/easyconfigs/m/Multiwfn/Multiwfn-3.8_dev-intel-compilers-2022.1.0.eb
> +toolchain = {'name': 'intel-compilers', 'version': '2022.1.0'}
This should be in the iimkl/2022a toolchain
Then you can drop the dependency on imkl.

2026-06-16 11:01 UTC, Thyre commented
Toolchain is deprecated by now, see [Common Toolchains](https://docs.easybuild.io/common-toolchains/#common_toolchains_overview_intel).

2026-06-16 21:29 UTC, boegel commented
> Toolchain is deprecated by now, see [Common Toolchains](https://docs.easybuild.io/common-toolchains/#common_toolchains_overview_intel).

Indeed, and no activity since quite a while, so time to close...

2026-06-16 21:29 UTC, closed without merging