{math}[GCCcore/11.3.0] primecountpy v0.1.0, primecount v7.9
easybuilders/easybuild-easyconfigs pull request #19370
Opened 2023-12-07 04:06 UTC by migueldiascosta

(created using `eb --new-pr`)

2023-12-07 04:09 UTC, migueldiascosta commented
@boegelbot please test @ generoso

2023-12-07 04:14 UTC, migueldiascosta commented
@boegelbot please test @ jsc-zen2

2023-12-14 11:55 UTC, verdurin requested changes

2023-12-14 11:55 UTC, verdurin commented on easybuild/easyconfigs/p/primecountpy/primecountpy-0.1.0-GCCcore-11.3.0.eb
> +
@migueldiascosta please add the missing build deps for `GCCcore`.

2023-12-27 11:18 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
jsczen3c1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.18
See https://gist.github.com/SebastianAchilles/1d405b47d8457883b362e20efe223417 for a full test report.

2023-12-27 11:22 UTC, SebastianAchilles approved these changes
lgtm

2023-12-27 11:23 UTC, SebastianAchilles commented
Going in, thanks @migueldiascosta!

2023-12-27 11:23 UTC, merged