{lib,vis}[foss/2022a] devbio-napari v0.10.1, PyOpenCL v2023.1.4, autopep8 v2.0.4, ...
easybuilders/easybuild-easyconfigs pull request #19392
Opened 2023-12-11 12:09 UTC by PetrKralCZ

(created using `eb --new-pr`)

2023-12-11 14:18 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2023-12-12 12:24 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2023-12-12 12:27 UTC, boegel requested changes

2023-12-12 12:27 UTC, boegel commented on easybuild/easyconfigs/d/devbio-napari/devbio-napari-0.10.1-foss-2022a.eb
> +        # `unset SESSION_MANAGER && python -c "import napari_pyclesperanto_assistant"`
We should mention here why the `unset SESSION_MANAGER` is required:

```
WARNING: Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
```

2024-01-10 12:53 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-01-10 13:13 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2024-01-10 16:14 UTC, boegel approved these changes
lgtm

2024-01-10 16:38 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3157.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/6757166fb396896283e00c4c33d37a2c for a full test report.

2024-01-10 17:43 UTC, boegel commented
Going in, thanks @PetrKralCZ!

2024-01-10 17:43 UTC, merged