{data}[foss/2023a] dask v2023.12.1
easybuilders/easybuild-easyconfigs pull request #19483
Opened 2024-01-03 13:33 UTC by pavelToman

(created using `eb --new-pr`)

2024-01-03 13:34 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-01-03 13:43 UTC, pavelToman commented
@boegelbot please test @ jsc-zen2

2024-01-03 18:54 UTC, boegel requested changes

2024-01-03 18:54 UTC, boegel commented on easybuild/easyconfigs/d/dask/dask-2023.12.1-foss-2023a.eb
> +    ('partd', '1.4.0', {
@pavelToman There's a 1.4.1 release of `partd`, let's update to that?

2024-01-03 18:54 UTC, boegel commented on easybuild/easyconfigs/d/dask/dask-2023.12.1-foss-2023a.eb
> +    ('tblib', '2.0.0', {
should be updated to `3.0.0`?

2024-01-04 10:26 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-01-04 10:38 UTC, pavelToman commented
@boegelbot please test @ jsc-zen2

2024-01-04 12:28 UTC, boegel approved these changes
lgtm

2024-01-04 12:33 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3124.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/816326e0df6ed572f51e50c77385aeb3 for a full test report.

2024-01-04 12:33 UTC, boegel commented
Going in, thanks @pavelToman!

2024-01-04 12:33 UTC, merged