{data,tools}[GCCcore/13.2.0] CppUnit v1.15.1, MDBM v4.13.0
easybuilders/easybuild-easyconfigs pull request #19536
Opened 2024-01-10 09:14 UTC by SimonPinches

(created using `eb --new-pr`)

2024-01-15 22:30 UTC, SebastianAchilles commented
@boegelbot please test @ generoso

2024-01-15 22:55 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**FAILED**
Build succeeded for 1 out of 2 (2 easyconfigs in total)
jsczen3c2.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.18
See https://gist.github.com/SebastianAchilles/571e6c46e8dd188f41cf801ce2aa62ea for a full test report.

2024-02-08 22:47 UTC, Micket requested changes, later dismissed
Based on jsczen3 build, MDBM has a OpenSSL dep, requiring 1.1 i think, so we should have that as a dep.

2024-02-19 07:39 UTC, SebastianAchilles commented
@boegelbot please test @ jsc-zen3

2026-02-16 11:19 UTC, verdurin commented
@boegelbot please test @ jsc-zen3

2026-02-16 15:11 UTC, verdurin commented
Test report by @verdurin
**FAILED**
Build succeeded for 11 out of 12 (total: 4 hours 4 mins 32 secs) (2 easyconfigs in total)
centos-stream-9 - Linux CentOS Stream 9, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.12.12
See https://gist.github.com/verdurin/ddd9b97fa1d23a67496418fc73a73697 for a full test report.

2026-02-16 15:38 UTC, verdurin commented
```
In file included from mdbm.c:47:
atomic.h:92:24: error: conflicting types for ‘gettid’; have ‘uint32_t()’ {aka ‘unsigned int()’}
   92 | static inline uint32_t gettid() {
      |                        ^~~~~~
In file included from /usr/include/unistd.h:1208,
                 from mdbm.c:29:
/usr/include/bits/unistd_ext.h:34:16: note: previous declaration of ‘gettid’ with type ‘__pid_t(void)’ {aka ‘int(void)’}
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
```

2026-02-16 15:39 UTC, verdurin commented
This is on a CentOS Stream 9 build node.

2026-04-08 08:20 UTC, akesandgren commented
Test report by @akesandgren
**FAILED**
Build succeeded for 1 out of 2 (total: 1 min 0 secs) (2 easyconfigs in total)
b-cn1611.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 580.126.09, Python 3.10.12
See https://gist.github.com/akesandgren/7dfaa516a47a64d2a656f8a42def4751 for a full test report.

2026-04-08 08:24 UTC, akesandgren commented
MDBM contains incorrect definitions of gettid and isn't fully OpenSSL3 compatible.
If you want this merged you need to find a newer version of it or make appropriate patches.

@SimonPinches I'll leave it up to you to close this or fix it.

2026-04-08 12:12 UTC, SimonPinches commented
> MDBM contains incorrect definitions of gettid and isn't fully OpenSSL3 compatible. If you want this merged you need to find a newer version of it or make appropriate patches.
> 
> @SimonPinches I'll leave it up to you to close this or fix it.

@akesandgren, I've had a go at patching to fix the gettid problem.

2026-04-08 12:28 UTC, akesandgren commented
@boegelbot Please test @ jsc-zen3

2026-04-08 12:32 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (total: 1 min 47 secs) (2 easyconfigs in total)
b-cn1611.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 580.126.09, Python 3.10.12
See https://gist.github.com/akesandgren/2da1efd4c14b3803a3ed0c13383f3305 for a full test report.

2026-04-08 12:35 UTC, akesandgren approved these changes
LGTM

2026-04-08 12:36 UTC, akesandgren commented
Going in, thanks @SimonPinches!

2026-04-08 12:36 UTC, merged