bug fix
easybuilders/easybuild-easyconfigs pull request #19532
Opened 2024-01-09 16:45 UTC by PetrKralCZ

(created using `eb --new-pr`)

2024-01-09 21:55 UTC, boegel requested changes

2024-01-09 21:55 UTC, boegel commented on easybuild/easyconfigs/a/Arrow/Arrow-11.0.0-gfbf-2022b.eb
> +patches = ['Arrow-8.0.0_bugfix.patch']
@PetrKralCZ The patch filename should be a bit more descriptive, "bugfix" is way too generic.

How about `Arrow-8.0.0_fix-BaseExtensionType-arrow-ext-methods.patch`

2024-01-09 21:55 UTC, boegel commented on easybuild/easyconfigs/a/Arrow/Arrow-8.0.0_bugfix.patch
> +the bug is fixed in Arrow version 14: https://github.com/apache/arrow/pull/33802
mention error explicitly:

```suggestion
fix for:
AttributeError: 'pyarrow.lib.BaseExtensionType' object has no attribute '__arrow_ext_class__'
see https://github.com/apache/arrow/pull/33802
```

keep in mind that changes the patch description implies updating the SHA256 checksum

2024-01-10 09:41 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-01-10 13:16 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in total)
node3157.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/5253922be81da89b7f43781946c6747d for a full test report.

2024-01-10 13:31 UTC, boegel requested changes

2024-01-10 13:31 UTC, boegel commented on easybuild/easyconfigs/a/Arrow/Arrow-11.0.0-gfbf-2022b.eb
> +    {'apache-arrow-8.0.0.tar.gz': 'ad9a05705117c989c116bae9ac70492fe015050e1b80fb0e38fde4b5d863aaa3'},
@PetrKralCZ This should be fixed, for `11.0.0`

2024-01-10 14:06 UTC, boegel commented
@boegelbot please test @ jsc-zen2

2024-01-10 14:16 UTC, boegel commented
@boegelbot please test @ generoso
EB_ARGS="Arrow-11.0.0-gfbf-2022b.eb"

2024-01-10 14:24 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3157.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/ad22a2d62ab34ceecf1e4bd90d570767 for a full test report.

2024-01-10 15:41 UTC, boegel approved these changes
lgtm

2024-01-10 15:41 UTC, merged