{tools}[foss/2023a] gcsfs v2023.12.2 w/ .post1
easybuilders/easybuild-easyconfigs pull request #19574
Opened 2024-01-12 14:39 UTC by pavelToman

(created using `eb --new-pr`)

2024-01-12 14:39 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-01-12 14:49 UTC, pavelToman commented
@boegelbot please test @ jsc-zen2

2024-01-13 15:32 UTC, boegel requested changes

2024-01-13 15:32 UTC, boegel commented on easybuild/easyconfigs/g/gcsfs/gcsfs-2023.12.2-foss-2023a.post1.eb
> +versionsuffix = '.post1'
@pavelToman the `.post1` is just part of the version, so:

```suggestion
version = '2023.12.2.post1'
```

Do note that this implies renaming the easyconfig file as well

2024-01-13 15:32 UTC, boegel commented on easybuild/easyconfigs/g/gcsfs/gcsfs-2023.12.2-foss-2023a.post1.eb
> +# builddependencies = [('protobuf', '24.0')]
can be removed?

2024-01-13 15:32 UTC, boegel commented on easybuild/easyconfigs/g/gcsfs/gcsfs-2023.12.2-foss-2023a.post1.eb
> +        # 'modulename': 'google.auth.oauthlib',
can be removed?

2024-01-13 15:32 UTC, boegel commented on easybuild/easyconfigs/g/gcsfs/gcsfs-2023.12.2-foss-2023a.post1.eb
> +        'source_tmpl': '%(name)s-%(version)s%(versionsuffix)s.tar.gz',
this can be removed if you integrate `.post1` in `version`

2024-01-15 21:48 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-01-16 07:57 UTC, pavelToman commented
@boegelbot please test @ jsc-zen2

2024-01-16 19:21 UTC, boegel approved these changes
lgtm

2024-01-16 19:27 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3171.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/5ef6ff3e7346d4021219e7fe2645ecec for a full test report.

2024-01-16 21:49 UTC, boegel commented
Going in, thanks @pavelToman!

2024-01-16 21:49 UTC, merged