{tools}[GCCcore/11.3.0] remake v4.3+dbg-1.6
easybuilders/easybuild-easyconfigs pull request #19581
Opened 2024-01-13 12:54 UTC by boegel

(created using `eb --new-pr`)

2024-01-14 09:41 UTC, branfosj submitted a review, later dismissed

2024-01-14 09:41 UTC, branfosj commented
@boegelbot please test @ generoso

2024-01-14 09:46 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/8d52af7b44e235db6706752985bc66d6 for a full test report.

2024-01-14 09:48 UTC, branfosj commented
@boegelbot please test @ jsc-zen2

2024-01-14 14:48 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3147.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/c05dcfefcfb8741899857788f8824239 for a full test report.

2024-03-29 22:26 UTC, Micket commented
Test report by @Micket
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/d5352b0e02a8b6796e72b77e7ebb504d for a full test report.

2024-03-29 22:46 UTC, Micket requested changes
build issues are readline related. should use our libreadline instead.

2024-03-29 22:46 UTC, Micket commented on easybuild/easyconfigs/r/remake/remake-4.3+dbg-1.6-GCCcore-11.3.0.eb
> +
```suggestion

dependencies = [
    ('libreadline', '8.1.2'),
]

```

2024-03-30 17:40 UTC, Micket commented on easybuild/easyconfigs/r/remake/remake-4.3+dbg-1.6-GCCcore-11.3.0.eb
> +
i'm just gonna commit it so that i can run the tests

2024-03-30 17:41 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/60df10a5017c652d7e51ff70bf79aae8 for a full test report.

2024-03-30 17:43 UTC, Micket commented
@boegelbot please test @ generoso

2024-03-30 18:32 UTC, Micket commented
@boegelbot please test @ jsc-zen3

2024-03-30 18:32 UTC, Micket approved these changes
lgtm

2024-03-30 18:32 UTC, Micket commented
Going in, thanks @boegel!

2024-03-30 18:32 UTC, merged