{bio}[GCCcore/12.3.0] BioPerl v1.7.8
easybuilders/easybuild-easyconfigs pull request #19614
Opened 2024-01-17 14:53 UTC by smoors

(created using `eb --new-pr`)

2024-01-17 16:23 UTC, smoors commented
@boegelbot: please test @ generoso

2024-01-17 16:25 UTC, smoors commented
Test report by @smoors
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node398.hydra.os - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/smoors/415ccc0855e6b99fcfbd84048a149033 for a full test report.

2024-01-17 17:22 UTC, smoors commented
@boegelbot: please test @ generoso

2024-01-17 18:52 UTC, smoors commented
@boegelbot please test @ jsc-zen2

2024-01-18 11:37 UTC, boegel requested changes

2024-01-18 11:37 UTC, boegel commented on easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0209-GCCcore-12.3.0.eb
> +    'dirs': ['lib/perl5/site_perl/%(perlver)s/x86_64-linux-thread-multi/XML/LibXML'],
@smoors Please use `%(arch)s` here (so it also works on Arm), and apply the same fix to the existing `XML-LibXML-2.0208-GCCcore-12.2.0.eb` where you probably inherited this from (in this PR is fine)

```suggestion
    'dirs': ['lib/perl5/site_perl/%(perlver)s/%(arch)s-linux-thread-multi/XML/LibXML'],
```

We already have this in all other `XML-LibXML` easyconfigs

2024-01-18 12:23 UTC, smoors commented
@boegelbot: please test @ generoso

2024-01-18 16:32 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3138.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/18504e4a50f7c582fb16387a70ae6f27 for a full test report.

2024-01-18 17:10 UTC, boegel approved these changes
lgtm

2024-01-18 17:11 UTC, boegel commented
Going in, thanks @smoors!

2024-01-18 17:11 UTC, merged