{devel}[system/system] Eclipse-SDK v4.30, Eclipse-java v2023.12 w/ Java 21
easybuilders/easybuild-easyconfigs pull request #19621
Opened 2024-01-17 18:05 UTC by SimonPinches

(created using `eb --new-pr`)

2024-01-17 18:06 UTC, SimonPinches commented
This PR relies upon #19620.

2024-04-01 21:36 UTC, Micket requested changes, later dismissed

2024-04-01 21:36 UTC, Micket commented on easybuild/easyconfigs/e/Eclipse-java/eclipse-java-2023.12_fix_path.patch
> ++/work/imas/opt/EasyBuild/software/Java/17.0.6/bin/java
this clearly won't work for anyone else

2024-04-01 21:36 UTC, Micket commented on easybuild/easyconfigs/e/Eclipse-java/eclipse-java-2023.12_fix_path.patch
> +diff -Nru eclipse-orig/eclipse.ini eclipse/eclipse.ini
Please add a description on author to patches

2024-04-01 21:36 UTC, Micket commented on easybuild/easyconfigs/e/Eclipse-SDK/Eclipse-SDK-4.30-Java-21.eb
> +description = """Integrated Development Environment"""
description doesn't seem correct here

2024-04-01 21:36 UTC, Micket commented on easybuild/easyconfigs/e/Eclipse-java/Eclipse-java-2023.12-Java-21.eb
> +description = """Integrated Development Environment"""
This seems way to short of a description to me
Maybe (taken from website)
> The essential tools for any Java developer, including a Java IDE, a Git client, XML Editor, Maven and Gradle integration

2024-04-01 21:36 UTC, Micket commented on easybuild/easyconfigs/e/Eclipse-java/Eclipse-java-2023.12-Java-21.eb
> +name = 'Eclipse-java'
I think this should say something like IDE in there

2025-08-18 14:56 UTC, boegel reviewed
lgtm

2025-08-18 14:57 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3513.doduo.os - Linux RHEL 9.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.9.18
See https://gist.github.com/boegel/36b94a08ee72342721fa9244a7a42faa for a full test report.

2025-08-18 15:07 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2025-08-18 15:07 UTC, boegel approved these changes
lgtm

2025-08-18 15:37 UTC, boegel commented
Going in, thanks @SimonPinches!

2025-08-18 15:37 UTC, merged