{phys}[gompi/2023a] Rivet v3.1.9, HepMC3 v3.2.6, fastjet v3.4.2, ... w/ HepMC3 3.2.6
easybuilders/easybuild-easyconfigs pull request #19631
Opened 2024-01-18 11:55 UTC by APN-Pucky

(created using `eb --new-pr`)

2024-01-18 12:42 UTC, boegel requested changes

2024-01-18 12:42 UTC, boegel commented on easybuild/easyconfigs/r/Rivet/Rivet-3.1.9-gompi-2023a-HepMC3-3.2.6.eb
> +toolchainopts = {'optarch': True, 'pic': True}
`optarch` is enabled by default, so this should become:

```suggestion
toolchainopts = {'pic': True}
```

2024-01-18 12:42 UTC, boegel approved these changes
lgtm

2024-01-18 17:12 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-01-19 07:26 UTC, boegel commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--sanity-check-only"

2024-01-19 09:54 UTC, boegel commented
Going in, thanks @APN-Pucky!

2024-01-19 09:54 UTC, merged

2024-01-19 19:43 UTC, APN-Pucky commented
Thanks to you @boegel . I am very excited about using it in my institute with eessi, since we can upgrade OSes w/o worrying about breaking the software.