{ai}[foss/2023a] PyTorch v2.1.2 w/ CUDA 12.1.1
easybuilders/easybuild-easyconfigs pull request #19666
Opened 2024-01-22 12:16 UTC by jfgrimm

(created using `eb --new-pr`)

2024-01-23 12:19 UTC, lexming requested changes
I'm also working on this and made two additional patches to workaround failing tests on our GPU nodes. Please check https://github.com/jfgrimm/easybuild-easyconfigs/pull/3

2024-01-24 11:34 UTC, jfgrimm commented
@lexming thanks!

2024-01-24 15:07 UTC, jfgrimm commented
Test report by @jfgrimm
**FAILED**
Build succeeded (with --ignore-test-failure) for 0 out of 1 (1 easyconfigs in total)
gpu22.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 2 x NVIDIA NVIDIA H100 PCIe, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/cfb59aaebed5ec14a7065a28c7fac285 for a full test report.

2024-01-24 23:26 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 1 out of 1 (1 easyconfigs in total)
gpu22.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 2 x NVIDIA NVIDIA H100 PCIe, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/4d87e654aa4fb984e0026ec049fa6ace for a full test report.

2024-01-27 11:52 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 1 out of 1 (1 easyconfigs in total)
gcn6.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/casparvl/5ddd19d75644b6b53980b1fcd27a6d2f for a full test report.

2024-01-29 09:15 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node406.hydra.os - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7282 16-Core Processor @ 2.80GHz, 1 x NVIDIA NVIDIA A100-PCIe-40GB, 545.23.08, Python 3.6.8
See https://gist.github.com/lexming/c89fa474ef534acc3cd170bcff5c7aca for a full test report.

2024-01-29 09:39 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node252.hydra.os - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, 1 x NVIDIA NVIDIA P100-PCIe, 545.23.08, Python 3.6.8
See https://gist.github.com/lexming/576add53a0b1c736da9137bd25c6a966 for a full test report.

```
== 2024-01-25 01:57:32,190 pytorch.py:467 WARNING 4 test failures, 0 test errors (out of 210938):
functorch/test_eager_transforms 1/1 (1 failed, 343 passed, 3 skipped, 1 xfailed, 2 rerun)
distributed/_tensor/test_dtensor_ops 1/1 (3 failed, 190 passed, 43 skipped, 409 xfailed, 6 rerun)
```

* Failed `test_eager_transforms` is  `TestCompileTransformsCPU::test_compile_vmap_hessian_cpu` with an unexpected success. Seems an implementation error failing to trigger some deprecation warnings. Very minor issue.
* Failed `test_dtensor_ops` is `TestDTensorOpsCPU::test_dtensor_op_db_nn_functional_pad_circular_cpu_float32`, same story as with our A100 on AMD zen2. See https://github.com/easybuilders/easybuild-easyconfigs/pull/19666#issuecomment-1914269571

2024-01-29 09:41 UTC, lexming submitted a review, later dismissed
On my side with just 4 test failures, this looks pretty good to me already.

2024-01-29 16:57 UTC, jfgrimm commented
haven't had a chance to look into the `742 test failures, 82 test errors` with 2x H100, zen3 yet

2024-01-29 22:18 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 1 out of 1 (1 easyconfigs in total)
gpu13.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, 3 x NVIDIA NVIDIA A40, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/29713f8c8160dff849eb5301a5f26fd3 for a full test report.

2024-01-31 09:23 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 1 out of 1 (1 easyconfigs in total)
gpu21.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 1 x NVIDIA NVIDIA H100 PCIe, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/814d5b4c5870b81f8757e7f5398bcba8 for a full test report.

2024-02-01 04:47 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 1 out of 1 (1 easyconfigs in total)
node3309.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 535.154.05, Python 3.6.8
See https://gist.github.com/boegel/3ce3ca8e311f6ced76a39f1c59785126 for a full test report.

2024-02-01 15:28 UTC, boegel commented
So, test results across a variety of systems summarized:

* on AMD Milan (EPYC 7413) with 2x NVIDIA H100 (`viking` @ York): 742 test failures, 82 test errors
* on Intel Ice Lake with 4x A100 (40GB) (`snellius` @ SURF): 15 test failures, 0 test errors
* on AMD Rome with 1x NVIDIA A100 (`hydra` @ VUB): 4 test failures, 0 test errors
* on Intel Sandy Bridge with 1x NVIDIA P100 (`hydra` @ VUB): 4 test failures, 0 test errors
* on AMD Milan (EPYC 7643) with 3x NVIDIA H100 (`viking` @ York): 740 test failures, 82 test errors
* on AMD Milan (EPYC 7413) with 1x NVIDIA H100 (`viking` @ York): 27 test failures, 78 test errors
* on Intel Cascade Lake with 1 V100 (`joltik` @ HPC-UGent): 5 test failures

So even in the worst case, 99.6% of all tests pass...

@jfgrimm I'm strongly in favor of setting `max_failed_tests = 20` in this easyconfig including a reference to this comment, and then merging it. Dealing with the failing tests can be done in subsequent PRs, if it's worth the trouble...

2024-02-01 15:42 UTC, jfgrimm commented
ohhhh damn I forgot to add `cuDNN`, `magma` and `NCCL`... :facepalm:

2024-02-01 15:47 UTC, boegel commented
> ohhhh damn I forgot to add `cuDNN`, `magma` and `NCCL`... 🤦

So, we get to do the whole dance again, I guess?

2024-02-01 15:48 UTC, jfgrimm commented
> > ohhhh damn I forgot to add `cuDNN`, `magma` and `NCCL`... 🤦
> 
> So, we get to do the whole dance again, I guess?

yup

2024-02-01 16:11 UTC, jfgrimm commented
Test report by @jfgrimm
**FAILED**
Build succeeded (with --ignore-test-failure) for 0 out of 1 (1 easyconfigs in total)
gpu22.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 1 x NVIDIA NVIDIA H100 PCIe, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/1c19d7da70e3d2d028aeb69aed40c701 for a full test report.

2024-02-01 22:40 UTC, lexming commented
My previous tests were already done with `cuDNN`, `magma` and `NCCL` in the dependency list. But I'll submit new tests again with the added patches.

2024-02-01 23:19 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 1 out of 1 (1 easyconfigs in total)
gpu05.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, 1 x NVIDIA NVIDIA A40, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/8e4632b00373e2d6b3528cfb000f1889 for a full test report.

2024-02-02 00:10 UTC, akesandgren commented
Test report by @akesandgren
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
b-cn1603.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 525.147.05, Python 3.10.12
See https://gist.github.com/akesandgren/71bfccc8f2d443428a0b2a6f87b5a22d for a full test report.

2024-02-02 01:44 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 1 out of 1 (1 easyconfigs in total)
node3906.accelgor.os - Linux RHEL 8.8, x86_64, AMD EPYC 7413 24-Core Processor (zen3), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 535.154.05, Python 3.6.8
See https://gist.github.com/boegel/2badf159c1040792b9a25bed6a79b309 for a full test report.

2024-02-02 08:55 UTC, boegel commented
@akesandgren Can you add short summary that clearly shows how many tests failed in total (like I did for my test report)?

2024-02-02 09:25 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 1 out of 1 (1 easyconfigs in total)
gpu22.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 1 x NVIDIA NVIDIA H100 PCIe, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/7c44a59e7ab82e4872719c6d2d72cb80 for a full test report.

2024-02-02 10:33 UTC, boegel commented
@jfgrimm If we want to accept the installation for all test configuration, we'll need something like `max_failed_tests = 110`?

2024-02-02 11:18 UTC, jfgrimm commented
> @jfgrimm If we want to accept the installation for all test configuration, we'll need something like `max_failed_tests = 110`?

fine by me? I can take a look at patching the tests that cause errors on omnipath at some point to bring that number back down (https://github.com/pytorch/tensorpipe/issues/413), but that isn't high on my list of priorities atm

2024-02-02 11:20 UTC, jfgrimm commented
although, I guess we could exclude those instead

2024-02-02 11:25 UTC, jfgrimm commented on easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2023a-CUDA-12.1.1.eb
> +}
```suggestion
excluded_tests = {
    '': [
        # This test seems to take too long on NVIDIA Ampere at least.
        'distributed/test_distributed_spawn',
        # Broken on CUDA 11.6/11.7: https://github.com/pytorch/pytorch/issues/75375
        'distributions/test_constraints',
        # no xdoctest
        'doctests',
        # failing on broadwell
        # See https://github.com/easybuilders/easybuild-easyconfigs/issues/17712
        'test_native_mha',
        # intermittent failures on various systems
        # See https://github.com/easybuilders/easybuild-easyconfigs/issues/17712
        'distributed/rpc/test_tensorpipe_agent',
        # failures on OmniPath systems, which don't support some optional InfiniBand features
        # See https://github.com/pytorch/tensorpipe/issues/413
        'distributed/pipeline/sync',
    ]
}
```

2024-02-02 11:25 UTC, jfgrimm commented on easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2023a-CUDA-12.1.1.eb
> +max_failed_tests = 2
```suggestion
max_failed_tests = 30
```

2024-02-02 13:31 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3300.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 535.154.05, Python 3.6.8
See https://gist.github.com/boegel/6aea2de8e1b8020a9c1586eb68a2c029 for a full test report.

2024-02-02 13:31 UTC, jfgrimm commented on easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2023a-CUDA-12.1.1.eb
> +        'distributed/pipeline/sync',
```suggestion
        # failures on OmniPath systems, which don't support some optional InfiniBand features
        # See https://github.com/pytorch/tensorpipe/issues/413
        'distributed/pipeline/sync/skip/test_gpipe',
        'distributed/pipeline/sync/skip/test_leak',
        'distributed/pipeline/sync/test_bugs',
        'distributed/pipeline/sync/test_inplace',
        'distributed/pipeline/sync/test_pipe',
        'distributed/pipeline/sync/test_transparency',
```

2024-02-02 20:56 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 1 out of 1 (1 easyconfigs in total)
gpu01.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, 1 x NVIDIA NVIDIA A40, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/0abe2699cf1c2bbb8ab17ad27c6a6316 for a full test report.

2024-02-02 21:22 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3904.accelgor.os - Linux RHEL 8.8, x86_64, AMD EPYC 7413 24-Core Processor (zen3), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 535.154.05, Python 3.6.8
See https://gist.github.com/boegel/bcc0a0ad2f0a3398cd8c474e50fff32f for a full test report.

2024-02-02 23:25 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3300.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (cascadelake), 1 x NVIDIA Tesla V100-SXM2-32GB, 535.154.05, Python 3.6.8
See https://gist.github.com/boegel/60a98c2bbaf1d00f924e289c28d15dac for a full test report.

2024-02-07 01:05 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node403.hydra.os - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7282 16-Core Processor (zen2), 1 x NVIDIA NVIDIA A100-PCIE-40GB, 545.23.06, Python 3.6.8
See https://gist.github.com/lexming/ce1241ebf1688b4afd67780313661b4c for a full test report.

2024-02-12 00:49 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node250.hydra.os - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (broadwell), 1 x NVIDIA Tesla P100-PCIE-16GB, 545.23.06, Python 3.6.8
See https://gist.github.com/lexming/372852238ee118bb8a7b22f81776793e for a full test report.

2024-02-12 10:11 UTC, boegel commented
@jfgrimm Seems like allowing 10 failing tests would already get us pretty far for now?

2024-02-12 11:36 UTC, Flamefire commented
Just seen this PR. I already was working on an EC myself but were still working through the failures before leaving for vacation. However I already made some more patches: PyTorch-2.1.0_skip-test-linalg-svd-complex.patch is PyTorch-2.1.2_fix-conj-mismatch-test-failures.patch for me but I didn't have PyTorch-2.1.0_disable-cudnn-tf32-for-too-strict-tests.patch which to me makes sense. A partial fix for the same issue I used is PyTorch-2.1.2_relax-cuda-tolerances.patch

I opened #19831 with my EC and included PyTorch-2.1.0_disable-cudnn-tf32-for-too-strict-tests.patch and the 'distributed/pipeline/sync' exclusions from here.

That might need raising the allowed number of failed tests but maybe already works with the patches I had.

I'm also open to PR my changes/patches against this PR and closing #19831 if that is preferable.

2024-02-12 13:06 UTC, boegel commented
@Flamefire A PR to this PR to add additional patches makes most sense, I think...

2024-02-12 13:35 UTC, Flamefire commented
Done: https://github.com/jfgrimm/easybuild-easyconfigs/pull/4

The idea was that we could compare if the failures were different/more/less. But I guess we can focus better on a single PR

2024-02-14 02:26 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
jsczen3g1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, AMD EPYC-Milan Processor (zen3), 1 x NVIDIA NVIDIA A100 80GB PCIe, 545.23.08, Python 3.9.18
See https://gist.github.com/SebastianAchilles/8a1be0fa287de7de600bb5b930d63d4c for a full test report.

2024-02-14 03:18 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 1 out of 1 (1 easyconfigs in total)
node3905.accelgor.os - Linux RHEL 8.8, x86_64, AMD EPYC 7413 24-Core Processor (zen3), 1 x NVIDIA NVIDIA A100-SXM4-80GB, 535.154.05, Python 3.6.8
See https://gist.github.com/boegel/a2f275a45a56b0ec2cdd947275c02c1c for a full test report.

2024-02-14 13:47 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn1603.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 525.147.05, Python 3.10.12
See https://gist.github.com/akesandgren/64fb4232d700958da9562bdd8247b0e6 for a full test report.

2024-02-15 01:03 UTC, casparvl commented
Test report by @casparvl
**FAILED**
Build succeeded (with --ignore-test-failure) for 5 out of 6 (1 easyconfigs in total)
gcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 535.104.12, Python 3.6.8
See https://gist.github.com/casparvl/b78f61fb3426148d43c5f817872b89f5 for a full test report.

2024-02-15 06:03 UTC, lexming commented
Test report by @lexming
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node408.hydra.os - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7282 16-Core Processor (zen2), 1 x NVIDIA NVIDIA A100-PCIE-40GB, 545.23.06, Python 3.6.8
See https://gist.github.com/lexming/3ab9c66ee842a8310f4395ea882d835d for a full test report.

2024-02-15 09:57 UTC, casparvl commented
My failure might just have been something on our system:
```
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```
Some signal killed the compilation. I'll try again, see what happens.

2024-02-15 14:35 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node253.hydra.os - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (broadwell), 1 x NVIDIA Tesla P100-PCIE-16GB, 545.23.06, Python 3.6.8
See https://gist.github.com/lexming/2a4296bfc81125b4333fdd342f5936a2 for a full test report.

2024-02-15 15:09 UTC, casparvl commented
Test report by @casparvl
**FAILED**
Build succeeded (with --ignore-test-failure) for 0 out of 1 (1 easyconfigs in total)
gcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 535.104.12, Python 3.6.8
See https://gist.github.com/casparvl/59dac4b527bbb8b9ea9bbc2831468c2d for a full test report.

2024-02-16 13:46 UTC, casparvl commented
Exact same error. Not sure why this only seems to be happening to me. I could imagine an OOM killer or something, but this node has 512 GB of memory... seems unlikely... No one else had issues during the build phase?

This was on the same node https://github.com/easybuilders/easybuild-easyconfigs/pull/19666#issuecomment-1913132013 and was succesful, so it might have been one of the changes after that botched it. Not sure which though...

2024-02-16 13:48 UTC, casparvl commented
Ok, this was a pretty fundamental change https://github.com/easybuilders/easybuild-easyconfigs/pull/19666/commits/969ef926a01e26defccfdc4f41b086cbde86ee6d that might explain why the failure was not there before.

2024-02-16 19:35 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 1 out of 1 (1 easyconfigs in total)
gpu05.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, 1 x NVIDIA NVIDIA A40, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/b1aac3a260fa447932dcec8ea5b8e898 for a full test report.

2024-02-16 19:57 UTC, casparvl commented
Test report by @casparvl
**FAILED**
Build succeeded (with --ignore-test-failure) for 0 out of 1 (1 easyconfigs in total)
gcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz, 4 x NVIDIA NVIDIA A100-SXM4-40GB, 535.104.12, Python 3.6.8
See https://gist.github.com/casparvl/91d05f02f9f2c31f8fc340c135b85125 for a full test report.

2024-02-17 06:02 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 7 out of 7 (1 easyconfigs in total)
bask-pg0309u36a - Linux RHEL 8.9, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), 1 x NVIDIA NVIDIA A100-SXM4-40GB, 535.154.05, Python 3.6.8
See https://gist.github.com/branfosj/4a07a0aa34a73acd92ec14f1d47a4693 for a full test report.

2024-02-19 11:31 UTC, jfgrimm commented
Test report by @jfgrimm
**FAILED**
Build succeeded (with --ignore-test-failure) for 0 out of 1 (1 easyconfigs in total)
gpu24.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 1 x NVIDIA NVIDIA H100 PCIe, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/4699b309b8ef05dac3b532678de9cf33 for a full test report.

2024-02-20 06:14 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 1 out of 1 (1 easyconfigs in total)
gpu24.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7413 24-Core Processor, 1 x NVIDIA NVIDIA H100 PCIe, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/b4c9b57340f3f2c53df2201139b03ff4 for a full test report.

2024-02-20 22:52 UTC, lexming approved these changes
I think that we have massaged the tests enough, most recent reports are passing the tests and those that don't pass the threshold have failures due to known issues. So on my side this LGTM.

The only severe fails are those of @casparvl . Did you manage to figure out the cause? I'm inclined to think that those are related to something specific to your system, since nobody else is having build issues. I'll wait for your feedback before merging.

2024-02-20 23:31 UTC, lexming commented
Test report by @lexming
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node252.hydra.os - Linux Rocky Linux 8.8, x86_64, Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (broadwell), 1 x NVIDIA Tesla P100-PCIE-16GB, 545.23.06, Python 3.6.8
See https://gist.github.com/lexming/127bf7fd9be5c9b239f7e1ba1054d20e for a full test report.

2024-02-21 07:57 UTC, VRehnberg commented
@jfgrimm what's the status of this PR now? Is @casparvl's build failure the only thing that needs to be solved before a merge or is there something else remaining as well?

2024-02-21 09:22 UTC, jfgrimm commented
@VRehnberg I'd say this is ready to merge, and if necessary further patches can be added in a follow-up PR.

The only (minor) question would be: do we want to increase the max failed tests value, and what to?

2024-02-21 09:37 UTC, Flamefire commented
> The only (minor) question would be: do we want to increase the max failed tests value, and what to?

Good point! Looks like we need at least 22 or more patches...

2024-02-21 09:55 UTC, lexming commented
Seeing the variability of the reports, I would increase the max failed threshold to 50. Anything below it is probably ok, but over 50 seems suspicious at this point.

2024-02-21 10:41 UTC, jfgrimm commented on easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2023a-CUDA-12.1.1.eb
> +max_failed_tests = 4
```suggestion
max_failed_tests = 50
```

2024-02-21 10:42 UTC, jfgrimm commented
@lexming done, I'll open an issue to revisit the failed tests

2024-02-21 21:27 UTC, lexming approved these changes
LGTM (yet again)

@casparvl I'll merge this now, if there would be any other changes needed to fix your build issues, it can be done in a follow-up PR.

2024-02-21 21:28 UTC, lexming commented
Merging, thanks @jfgrimm and @Flamefire and all the testers!

2024-02-21 21:28 UTC, merged

2024-02-23 13:01 UTC, casparvl commented
Still no idea why my builds are failing... The only thing I keep seeing consistently is

```
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```
but no clue why. If anyone has ideas, I'd love to hear :D Where there fixes to the toolchain at somepoint? Maybe I should try and recompile that...

Anyway, good to get this merged, no point in making it wait for something that is clearly specific to my machine :)

2024-02-27 13:18 UTC, lexming commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--ignore-test-failure"

2024-02-27 23:18 UTC, emdrago commented
Test report by @emdrago
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
gput052 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, 1 x NVIDIA NVIDIA GeForce RTX 2080 Ti, 535.54.03, Python 3.9.13
See https://gist.github.com/emdrago/3729452d9411286fe8d15bd627eae272 for a full test report.

2024-02-28 08:24 UTC, lexming commented
@boegelbot please test @ generoso
EB_ARGS="--ignore-test-failure"

2024-03-02 20:29 UTC, Flamefire commented
Test report by @Flamefire
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
i8013 - Linux Rocky Linux 8.7 (Green Obsidian), x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 545.23.08, Python 3.8.13
See https://gist.github.com/Flamefire/84b9710d5f445175d4b92c7d6d7f4f69 for a full test report.

2024-03-12 13:16 UTC, Flamefire commented
> We tried building this here at DTU, but it failed with 9 tests that failed. Should it not pass if there are less than 50 tests failing? That part does not seem to work, and I can see that the tests being done above are all with `--ignore-test-failure`.
> 
> It is a not-yet-implemented feature (in EB 5.0 perhaps) that up to 50 tests can fail, or is there some bug such that the `max_failed_tests = 50` line in the EasyConfig has no effect?

If it doesn't say anything about allowed failures in the output then this is a different issue. E.g. in my test report above I have:

```
ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): 7 test failures, 0 test errors (out of 211121):
Failed tests (suites/files):
distributed/checkpoint/test_fsdp_optim_state 1/1 (2 failed, 4 rerun)
distributed/fsdp/test_fsdp_tp_integration 1/1 (1 failed, 4 passed, 2 rerun)
distributed/fsdp/test_shard_utils 1/1 (2 failed, 1 passed, 4 rerun)
distributed/tensor/parallel/test_tp_random_state 1/1 (1 failed, 2 rerun)
test_nn 1/1 (1 failed, 2804 passed, 122 skipped, 3 xfailed, 2 rerun)
+ test_torch 1/1 (at easybuild/easyblocks/p/pytorch.py:507 in test_step)
```

The `+` prefix in `test_torch` is a hint that this test was not accounted in the failures. In fact this test fails entirely and crashes on my machine which is why there is no test failure count information. To be safe the run is considered a failure without comparing against allows failures. We should be more explicit in the log messages here.

2024-03-12 15:02 UTC, schiotz commented
Thank you, @Flamefire 

We are having
```
== 2024-03-11 23:32:29,846 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): 9 test failures, 0 test errors (out of 211087):
Failed tests (suites/files):
inductor/test_compiled_autograd 1/1 (1 failed, 130 passed, 114 skipped, 2 rerun)
distributed/checkpoint/test_fsdp_optim_state 1/1 (2 failed, 4 rerun)
distributed/fsdp/test_fsdp_tp_integration 1/1 (1 failed, 4 passed, 2 rerun)
distributed/fsdp/test_shard_utils 1/1 (2 failed, 1 passed, 4 rerun)
distributed/tensor/parallel/test_tp_random_state 1/1 (1 failed, 2 rerun)
test_nn 1/1 (2 failed, 2803 passed, 122 skipped, 3 xfailed, 4 rerun)
+ test_cpp_extensions_aot_ninja 1/1
+ test_cpp_extensions_aot_no_ninja 1/1 (at easybuild/easyblocks/p/pytorch.py:451 in test_step)
== 2024-03-11 23:32:29,847 build_log.py:267 INFO ... (took 9 hours 44 mins 59 secs)
```

Now we are trying to install with ``--ignore-test-failure``, I don't know if that will then fail, or if doing so is a bad idea.

2024-03-12 16:12 UTC, Flamefire commented
Yes, so `test_cpp_extensions_*` is failing/crashing. This sounds like something is wrong in your setup (e.g. broken/incompatible Ninja module) Check the log for details (search for e.g. "test_cpp_extensions_aot_ninja" from the bottom up) and then (try to) decide if `--ignore-test-failure` is a bad idea ;-) It should pass the installation however.

2024-03-13 08:29 UTC, schiotz commented
@Flamefire 

Thanks for your help.  It is really strange, it looks like nvcc fails to compile some C++ template code.  Could there be some recent update to something that we have missed, e.g. if we have installed Ninja too early?

```
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /home/modules/software/CUDA/12.1.1/bin/nvcc  -I/tmp/eb-n8ln4kf7/tmpijxfu2iq/lib/python3.11/site-packages/torch/include -I/tmp/
eb-n8ln4kf7/tmpijxfu2iq/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/tmp/eb-n8ln4kf7/tmpijxfu2iq/lib/python3
.11/site-packages/torch/include/TH -I/tmp/eb-n8ln4kf7/tmpijxfu2iq/lib/python3.11/site-packages/torch/include/THC -I/home/modules/sof
tware/CUDA/12.1.1/include -I/dev/shm/PyTorch/2.1.2/foss-2023a-CUDA-12.1.1/pytorch-v2.1.2/test/cpp_extensions/self_compiler_include_d
irs_test -I/home/modules/software/Python/3.11.3-GCCcore-12.3.0/include/python3.11 -c -c /dev/shm/PyTorch/2.1.2/foss-2023a-CUDA-12.1.
1/pytorch-v2.1.2/test/cpp_extensions/torch_library.cu -o /dev/shm/PyTorch/2.1.2/foss-2023a-CUDA-12.1.1/pytorch-v2.1.2/test/cpp_exten
sions/build/temp.linux-x86_64-cpython-311/torch_library.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BF
LOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INC
LUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1017"' -DTORCH_EXT
ENSION_NAME=torch_library -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_80,code=sm_80 -ccbin gcc -std=c++17
FAILED: /dev/shm/PyTorch/2.1.2/foss-2023a-CUDA-12.1.1/pytorch-v2.1.2/test/cpp_extensions/build/temp.linux-x86_64-cpython-311/torch_l
ibrary.o 
/home/modules/software/CUDA/12.1.1/bin/nvcc  -I/tmp/eb-n8ln4kf7/tmpijxfu2iq/lib/python3.11/site-packages/torch/include -I/tmp/eb-n8l
n4kf7/tmpijxfu2iq/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/tmp/eb-n8ln4kf7/tmpijxfu2iq/lib/python3.11/si
te-packages/torch/include/TH -I/tmp/eb-n8ln4kf7/tmpijxfu2iq/lib/python3.11/site-packages/torch/include/THC -I/home/modules/software/
CUDA/12.1.1/include -I/dev/shm/PyTorch/2.1.2/foss-2023a-CUDA-12.1.1/pytorch-v2.1.2/test/cpp_extensions/self_compiler_include_dirs_te
st -I/home/modules/software/Python/3.11.3-GCCcore-12.3.0/include/python3.11 -c -c /dev/shm/PyTorch/2.1.2/foss-2023a-CUDA-12.1.1/pyto
rch-v2.1.2/test/cpp_extensions/torch_library.cu -o /dev/shm/PyTorch/2.1.2/foss-2023a-CUDA-12.1.1/pytorch-v2.1.2/test/cpp_extensions/
build/temp.linux-x86_64-cpython-311/torch_library.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16
_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_E
XTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1017"' -DTORCH_EXTENSION
_NAME=torch_library -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_80,code=sm_80 -ccbin gcc -std=c++17
/home/modules/software/pybind11/2.11.1-GCCcore-12.3.0/include/pybind11/detail/../cast.h: In function typename pybind11::detail::type
_caster<typename pybind11::detail::intrinsic_type<T>::type>::cast_op_type<T> pybind11::detail::cast_op(make_caster<T>&):
/home/modules/software/pybind11/2.11.1-GCCcore-12.3.0/include/pybind11/detail/../cast.h:45:120: error: expected template-name before
 < token
   45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                                                        ^
/home/modules/software/pybind11/2.11.1-GCCcore-12.3.0/include/pybind11/detail/../cast.h:45:120: error: expected identifier before < 
token
/home/modules/software/pybind11/2.11.1-GCCcore-12.3.0/include/pybind11/detail/../cast.h:45:123: error: expected primary-expression b
efore > token
   45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                                                           ^
/home/modules/software/pybind11/2.11.1-GCCcore-12.3.0/include/pybind11/detail/../cast.h:45:126: error: expected primary-expression b
efore ) token
   45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                                                             
 ^
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/tmp/eb-n8ln4kf7/tmpijxfu2iq/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/home/modules/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
```

2024-03-13 08:47 UTC, Flamefire commented
Yep, that rings a bell for me. And is actually a good reason for why I'm so eager to investigate test failures instead of dismissing them just because many/most are bad code. This is an issue with the pybind11 version we use (pybind11/2.11.1-GCCcore-12.3.0)    
I added a patch to fix that.   
Try to rebuild your pybind11 from https://github.com/easybuilders/easybuild-easyconfigs/pull/19047 (included in EB 4.8.2+)

The relevant patch is https://github.com/easybuilders/easybuild-easyconfigs/blob/f9d0188424dd253a0718af1c61ba002f66072b46/easybuild/easyconfigs/p/pybind11/pybind11-2.10.3_fix-nvcc-compat.patch#L21

I suppose you could also apply that to your installed pybind11 module manually

2024-03-13 10:06 UTC, Flamefire commented
> We tried building this here at DTU, but it failed with 9 tests that failed. Should it not pass if there are less than 50 tests failing? That part does not seem to work, and I can see that the tests being done above are all with `--ignore-test-failure`.
> 
> It is a not-yet-implemented feature (in EB 5.0 perhaps) that up to 50 tests can fail, or is there some bug such that the `max_failed_tests = 50` line in the EasyConfig has no effect?

I opened https://github.com/easybuilders/easybuild-easyblocks/pull/3255 to improve the message in this case

2024-03-14 08:15 UTC, casparvl commented
Just to let you both know: I hit the same issue as @schiotz that I thought the `max_test_failures` was ignored. Also got the output:
``` 
Failed tests (suites/files):
test_quantization 1/1 (4 failed, 1043 passed, 57 skipped, 8 rerun)
test_nn 1/1 (1 failed, 2798 passed, 128 skipped, 3 xfailed, 2 rerun)
+ test_cpp_extensions_aot_ninja 1/1
+ test_cpp_extensions_aot_no_ninja 1/1
```
So I'll try to rebuild `pybind11`, see if that fixes things for me. I think improving the error message is indeed a good idea. Your explanation here 

> The + prefix in test_torch is a hint that this test was not accounted in the failures. In fact this test fails entirely and crashes on my machine which is why there is no test failure count information. To be safe the run is considered a failure without comparing against allows failures. We should be more explicit in the log messages here.

Is very clear, but without it the `+` symbol doesn't mean much, making it non-intuitive why the installation is not proceeding. Thus, https://github.com/easybuilders/easybuild-easyblocks/pull/3255/files sounds very useful to me :)

2024-04-24 22:25 UTC, emdrago commented
Test report by @emdrago
**SUCCESS**
Build succeeded (with --ignore-test-failure) for 1 out of 1 (1 easyconfigs in total)
gput052 - Linux RHEL 8.7 (Ootpa), x86_64, Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, 1 x NVIDIA NVIDIA GeForce RTX 2080 Ti, 535.54.03, Python 3.9.18
See https://gist.github.com/emdrago/e864743fc5bc6ac8f04f3453afe8a0e6 for a full test report.