{bio}[foss/2022b] medaka v1.9.1
easybuilders/easybuild-easyconfigs pull request #19689
Opened 2024-01-23 14:43 UTC by akesandgren

(created using `eb --new-pr`)

2024-01-23 14:48 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
b-cn1603.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 525.147.05, Python 3.10.12
See https://gist.github.com/akesandgren/604e4c875c0639b35ec00c4767c8622b for a full test report.

2024-01-23 14:59 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
b-cn1603.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 525.147.05, Python 3.10.12
See https://gist.github.com/akesandgren/af34acd673781af0aaf7f8e9c8888def for a full test report.

2024-01-23 15:38 UTC, verdurin requested changes

2024-01-23 15:38 UTC, verdurin commented on easybuild/easyconfigs/n/NGSpeciesID/NGSpeciesID-0.3.0-foss-2022b.eb
> +
@akesandgren - missing checksum.

2024-01-23 17:47 UTC, verdurin approved these changes
Looks fine.

2024-01-23 17:48 UTC, verdurin commented
@boegelbot please test @ generoso

2024-01-23 17:52 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 9 out of 9 (5 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/6a2a33c052e68f57ea613ef7515ab394 for a full test report.

2024-01-24 09:54 UTC, verdurin commented
@boegelbot please test @ jsc-zen3

2024-01-29 17:41 UTC, verdurin commented
Going in, thanks @akesandgren!

2024-01-29 17:41 UTC, merged