{tools}[GCCcore/12.3.0] enchant-2 v2.6.5, hunspell v1.7.2, ITSTool v2.0.7, ...
easybuilders/easybuild-easyconfigs pull request #19699
Opened 2024-01-23 16:56 UTC by jfgrimm

(created using `eb --new-pr`)

2024-01-24 12:05 UTC, jfgrimm commented
@boegelbot: please test @ generoso

2024-01-24 12:13 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
gpu07.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, 2 x NVIDIA NVIDIA A40, 535.86.10, Python 3.6.8
See https://gist.github.com/jfgrimm/4a6bbd99eabc0a17b52a0c9ab5ab4c9b for a full test report.

2024-01-24 14:28 UTC, jfgrimm commented
@boegelbot: please test @ jsc-zen3

2024-01-25 09:48 UTC, verdurin requested changes

2024-01-25 09:48 UTC, verdurin commented on easybuild/easyconfigs/h/hunspell/hunspell-1.7.2-GCCcore-12.3.0.eb
> +library and program designed for languageswith rich morphology and
```suggestion
library and program designed for languages with rich morphology and
```

2024-01-25 16:28 UTC, jfgrimm commented on easybuild/easyconfigs/h/hunspell/hunspell-1.7.2-GCCcore-12.3.0.eb
> +library and program designed for languageswith rich morphology and
fixed

2024-02-10 11:47 UTC, branfosj approved these changes

2024-02-10 12:37 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 7 out of 7 (5 easyconfigs in total)
bear-pg0105u03b - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/e4d6275fcf3cea7ab4e896275bad8e5d for a full test report.

2024-02-10 12:44 UTC, merged