{lib,tools}[GCCcore/12.3.0] evince v45.0, libgxps v0.3.2, libspectre v0.2.12, ...
easybuilders/easybuild-easyconfigs pull request #19701
Opened 2024-01-23 16:58 UTC by jfgrimm

(created using `eb --new-pr`)

2024-01-24 11:19 UTC, jfgrimm commented
Test report by @jfgrimm
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node075.viking2.yor.alces.network - Linux Rocky Linux 8.8, x86_64, AMD EPYC 7643 48-Core Processor, Python 3.6.8
See https://gist.github.com/jfgrimm/cf5f751b04773fb5d632aff7e0e25659 for a full test report.

2024-02-10 13:05 UTC, branfosj requested changes

2024-02-10 13:05 UTC, branfosj commented on easybuild/easyconfigs/e/evince/evince-45.0-GCC-12.3.0.eb
> +    ('libhandy', '1.8.2'),
This is missing from the PR.

2024-02-10 13:08 UTC, jfgrimm commented on easybuild/easyconfigs/e/evince/evince-45.0-GCC-12.3.0.eb
> +    # kpathsea
optional to provide support for some specific image formats, haven't looked into it yet

2024-02-10 13:12 UTC, jfgrimm commented on easybuild/easyconfigs/e/evince/evince-45.0-GCC-12.3.0.eb
> +    ('libhandy', '1.8.2'),
added

2024-02-10 13:18 UTC, jfgrimm commented on easybuild/easyconfigs/e/evince/evince-45.0-GCC-12.3.0.eb
> +    # kpathsea
correction:
* `kpathsea`: Path searching library for TeX-related files
* `djvulibre`: a set of compression technologies, a file format,
and a software platform for the delivery over the Web of digital documents,
scanned documents, and high resolution images.

2024-02-16 12:28 UTC, jfgrimm commented on easybuild/easyconfigs/e/evince/evince-45.0-GCC-12.3.0.eb
> +    # kpathsea
@branfosj I've added an easyconfig for `DjVuLibre`, but I think I won't enable `kpathsea` to avoid pulling in all of the `TeX` stuff

2024-02-16 12:44 UTC, branfosj commented
@boegelbot please test @ generoso

2024-02-16 13:02 UTC, branfosj commented
Test report by @branfosj
**FAILED**
Build succeeded for 7 out of 8 (7 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/4173d92a3829399a12c7c995d725e055 for a full test report.

2024-02-16 13:12 UTC, branfosj commented
@boegelbot please test @ jsc-zen3

2024-02-16 13:21 UTC, branfosj commented
```
Program update-desktop-database found: NO

../evince-45.0/meson.build:501:6: ERROR: Program 'update-desktop-database' not found or not executable
```

??

2024-02-16 13:22 UTC, jfgrimm commented
```
$ which update-desktop-database
/usr/bin/update-desktop-database
```
huh

2024-02-16 13:24 UTC, branfosj commented
I have `update-desktop-database` on my login nodes but not on the compute (or build) nodes.

2024-02-16 13:55 UTC, jfgrimm commented
@boegelbot please test @ jsc-zen3

2024-02-16 14:06 UTC, jfgrimm commented
@branfosj can you submit another test report with https://github.com/easybuilders/easybuild-easyconfigs/pull/19701/commits/01a994f1a0625e9fb2682fd03f7f07cc5be1c6b3?

2024-02-16 14:16 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/de931603119ef6e5c89598fead8380ce for a full test report.

2024-02-16 14:18 UTC, branfosj approved these changes

2024-02-16 14:21 UTC, branfosj commented
Going in, thanks @jfgrimm!

2024-02-16 14:21 UTC, merged