{data}[gfbf/2023a] DeltaLake v0.15.1
easybuilders/easybuild-easyconfigs pull request #19758
Opened 2024-01-31 10:37 UTC by lexming

(created using `eb --new-pr`)

2024-01-31 14:06 UTC, lexming commented
@boegelbot: please test @ generoso

2024-01-31 14:41 UTC, lexming commented
@boegelbot: please test @ generoso
EB_ARGS=" --include-easyblocks-from-pr=3118"

2024-02-01 09:46 UTC, lexming commented
@boegelbot: please test @ generoso
EB_ARGS=" --include-easyblocks-from-pr=3118"

2024-02-01 11:47 UTC, boegel commented
@boegelbot: please test @ jsc-zen3
EB_ARGS=" --include-easyblocks-from-pr=3118"

2024-02-01 14:34 UTC, lexming commented
@boegelbot: please test @ jsc-zen3
EB_ARGS=" --include-easyblocks-from-pr=3118"

2024-02-01 15:57 UTC, boegel requested changes

2024-02-01 15:57 UTC, boegel commented on easybuild/easyconfigs/d/DeltaLake/DeltaLake-0.15.1-gfbf-2023a.eb
> +    ('Perl', '5.36.1'),  # needed by crate openssl-sys
remove trailing whitespace that is tripping up code style check:
```suggestion
    ('Perl', '5.36.1'),  # needed by crate openssl-sys
```

2024-02-01 17:32 UTC, boegel commented
@lexming The changes you made to `Arrow` are not working for me (see upcoming test report), why are those required?

It would be better to open a dedicated PR for this if there's bug fix needed there...

2024-02-01 17:49 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3118
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
node3161.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/88003056c18e08d0a8cb86e71d6591fd for a full test report.

2024-02-01 19:31 UTC, branfosj commented
> @lexming The changes you made to `Arrow` are not working for me (see upcoming test report), why are those required?

If I've followed this correctly:
* `DeltaLake` requires `pyarrow>=8`
* The changes to `Arrow-14.0.1-gfbf-2023a.eb` mean that it correctly installs as `14.0.1` instead of `0.0.0`.
* The changes to the Arrow easyconfig require #19651 to make `setuptools_scm` available.
* 19651 targeted `5.0.x` and this PR targets `develop`

This means that merging the changes to `Arrow` will cause it to be broken in `develop` until we collapse in the `5.0.x` branch.

2024-02-01 22:30 UTC, lexming commented
@branfosj that's correct, changes to `Arrow` in this PR make it to properly install as a `PythonPackage` extension which triggers extra checks such as `pip check`. This will capture the wrong `0.0.0` version unless a Python with `setuptools_scm` is used.
I forgot that we put the changes on `setuptools_scm` into `5.0` (I have it deployed in my dev system already :yum: ). Maybe we should move it to `develop` to avoid perpetuating such issues for too long.

2024-02-02 17:23 UTC, lexming commented
@boegelbot: please test @ generoso

2024-02-02 18:08 UTC, lexming commented
@boegelbot: please test @ generoso
EB_ARGS=" --include-easyblocks-from-pr=3118"

2024-02-03 11:21 UTC, lexming commented
@boegel Python fixed in `develop`, tests from the bots are fine. Please try again.

2024-02-07 17:13 UTC, Micket commented
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3118
**SUCCESS**
Build succeeded for 3 out of 3 (2 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/b22b34c9af98456b35166f15d02361d0 for a full test report.

2024-02-09 16:17 UTC, Micket approved these changes
lgtm

2024-02-09 16:18 UTC, Micket commented
Going in, thanks @lexming!

2024-02-09 16:18 UTC, merged