{vis}[foss/2022a] yt v4.3.0
easybuilders/easybuild-easyconfigs pull request #19754
Opened 2024-01-30 17:40 UTC by sassy-crick

(created using `eb --new-pr`)

2024-01-30 17:49 UTC, sassy-crick commented
I am having problems to get that compilation working and the error messages are, well, cryptic to me. 
The full log can be found [here](https://gist.github.com/sassy-crick/59098cedb64e7e689c83e2766ebd888f)
I would appreciate some help. thanks

2024-01-31 21:39 UTC, bedroge requested changes

2024-02-02 13:56 UTC, sassy-crick commented on easybuild/easyconfigs/y/yt/yt-4.3.0-foss-2022a.eb
> +    ('sympy', '1.11.1'),
Done. Thanks for finding this. I had some problems to get the required versions correctly with that software. Also, if there are two versions in the same toolchain I usually go for the newest one.

2024-02-02 13:57 UTC, sassy-crick commented on easybuild/easyconfigs/y/yt/yt-4.3.0-foss-2022a.eb
> +
Done. Thanks for finding that.

2024-02-02 15:04 UTC, bedroge commented
@boegelbot please test @ jsc-zen3

2024-02-02 15:11 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node63 - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7763 64-Core Processor (zen3), Python 3.6.8
See https://gist.github.com/bedroge/5aeca81d16227f95bdbad2f39baf1821 for a full test report.

2024-02-02 15:38 UTC, bedroge approved these changes
Lgtm

2024-02-02 15:38 UTC, bedroge commented
Going in, thanks @sassy-crick!

2024-02-02 15:38 UTC, merged