{bio}[foss/2023a] phyluce v1.7.3
easybuilders/easybuild-easyconfigs pull request #19779
Opened 2024-02-02 10:08 UTC by pavelToman

(created using `eb --new-pr`)

2024-02-02 10:43 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-02-02 13:22 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-02-06 10:23 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-02-06 10:41 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-02-06 11:32 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-02-07 09:10 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-02-07 09:42 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-02-07 11:37 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-02-07 19:15 UTC, boegel requested changes

2024-02-07 19:15 UTC, boegel commented on easybuild/easyconfigs/p/phyluce/phyluce-1.7.3_removal-Bio-Alphabet.patch
> +author: Pavel Tomanek (INUITS)
@pavelToman I made a small change here, by adding you as author of this patch (and then changing the SHA256 checksum for this patch accordingly in the easyconfig)

2024-02-07 19:15 UTC, boegel commented on easybuild/easyconfigs/t/trimAl/trimAl-1.4.1-GCCcore-12.3.0.eb
> +    'files': ['bin/trimal', 'bin/readal', 'bin/statal'],
fixed in [c43ff54](https://github.com/easybuilders/easybuild-easyconfigs/pull/19779/commits/c43ff54c33d75d50967054da9c438293f105312d)

2024-02-07 19:16 UTC, boegel commented on easybuild/easyconfigs/p/Pilon/Pilon-1.23-Java-11-wrapped.eb
> +    "chmod a+rx %(installdir)s/bin/%(namelower)s"
fixed in [f6e5f3f](https://github.com/easybuilders/easybuild-easyconfigs/pull/19779/commits/f6e5f3f2724377900796b1626575d3299ce641d7)

2024-02-07 19:17 UTC, boegel requested changes
fix versionsuffix for Pilon

2024-02-07 19:17 UTC, boegel commented on easybuild/easyconfigs/p/Pilon/Pilon-1.23-Java-11.eb
> +versionsuffix = '-Java-%(javaver)s-wrapped'
```suggestion
versionsuffix = '-Java-%(javaver)s'
```

2024-02-07 19:30 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 9 out of 9 (9 easyconfigs in total)
node3120.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/eed8d5f60988771f57452ba85b63a34c for a full test report.

2024-02-07 19:30 UTC, boegel commented
@boegelbot please test @ generoso

2024-02-07 19:31 UTC, boegel approved these changes

2024-02-07 22:05 UTC, boegel commented
Going in, thanks @pavelToman!

2024-02-07 22:05 UTC, merged