{data}[gompi/2023b] CDO v2.2.2, UDUNITS v2.2.28 , PROJ v9.3.1, ecCods v2.31.0 , libaec v1.0.6, nlohmann_json v3.11.3, pkgconfig v1.5.5
easybuilders/easybuild-easyconfigs pull request #19792
Opened 2024-02-05 12:40 UTC by TopRichard

2024-02-26 06:23 UTC, TopRichard commented
@smoors Do these easyconfigs require any modifications?

2024-03-06 18:10 UTC, boegel requested changes

2024-03-06 18:10 UTC, boegel commented on easybuild/easyconfigs/c/CDO/CDO-2.2.2-gompi-2023b.eb
> +configopts += "--with-udunits2=$EBROOTUDUNITS --with-util-linux-uuid=$EBROOTUTILMINLINUX "
small extra bit needed here to make sure that build on CDO works fine on non-x86_64 systems, see #19735

```suggestion
configopts += "--with-udunits2=$EBROOTUDUNITS --with-util-linux-uuid=$EBROOTUTILMINLINUX "

# Make sure that right Fortran compiler is used, also on non-x86_64 architectures
configopts += 'CPPFLAGS="$CPPFLAGS -DgFortran" '

2024-03-06 18:11 UTC, boegel commented
@boegelbot please test @ generoso
CORE_CNT=16

2024-03-06 18:16 UTC, boegel commented
@boegelbot please test @ jsc-zen3
CORE_CNT=16

2024-03-06 18:46 UTC, boegel approved these changes

2024-03-06 18:50 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3110.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/f03e6791e0e3125585b2bae9dd3b01f1 for a full test report.

2024-03-06 18:52 UTC, boegel commented
Going in, thanks @TopRichard!

2024-03-06 18:52 UTC, merged