{math}[intel/2023a] AMICA v2024.1.19
easybuilders/easybuild-easyconfigs pull request #19842
Opened 2024-02-13 19:13 UTC by pavelToman

(created using `eb --new-pr`)

2024-02-13 19:19 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-02-14 12:21 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-02-14 13:20 UTC, boegel requested changes

2024-02-14 13:20 UTC, boegel commented on easybuild/easyconfigs/a/AMICA/AMICA-2024.1.19-intel-2023a.eb
> +test_cmd = "./amica17nsg ./amicadefs.param"
@pavelToman Please use `amica17` here, the binary that was built.

`amica17nsg` is a pre-built binary shipped in the repository, we don't want to use that for testing...

2024-02-14 14:26 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-02-23 07:40 UTC, boegel approved these changes
lgtm

2024-02-23 07:43 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-02-23 10:08 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3106.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/4c2286a6642adac976b83f24150a7bfa for a full test report.

2024-02-26 14:51 UTC, boegel commented
Going in, thanks @pavelToman!

2024-02-26 14:51 UTC, merged