{bio}[GCC/12.3.0,GCCcore/12.3.0,foss/2023a] Circlator v1.5.5, MUMmer v4.0.0rc1, Fastaq v3.17.0
easybuilders/easybuild-easyconfigs pull request #19847
Opened 2024-02-14 12:20 UTC by pavelToman

(created using `eb --new-pr`)

2024-02-14 12:20 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-02-14 13:23 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3117.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/b6ea54dc5037038095e1ad6fc2899264 for a full test report.

2024-02-14 13:33 UTC, boegel commented on easybuild/easyconfigs/c/Circlator/Circlator-1.5.5-foss-2023a.eb
> +            'https://files.pythonhosted.org/packages/7c/bf/f0fd534a733b7d98fc9853ca1aa735984cec1e5fc4670b632e76973f8add/'
You can avoid having to specify `source_urls` at all by using lowercase name as extension:

```python
('circulator', version, {
```

`PythonBundle` by default knows that extensions should be downloaded via PyPI, you don't need to specify that yourself

2024-02-14 13:34 UTC, boegel requested changes

2024-02-14 13:34 UTC, boegel commented on easybuild/easyconfigs/c/Circlator/Circlator-1.5.5-foss-2023a.eb
> +        'sources': ['circlator-1.5.5.tar.gz'],
Please don't hardcode the version here, use:

```python
        'sources': ['circlator-%(version)s.tar.gz'],

2024-02-14 14:31 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-02-14 17:41 UTC, boegel commented
@boegelbot please test @ generoso
EB_ARGS="--force-download --sourcepath /tmp/$USER/19847"

2024-02-14 20:45 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-02-21 05:43 UTC, boegel approved these changes
lgtm

2024-02-21 06:03 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3117.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/3fac281be7f5f137d8b7cb1d9953631b for a full test report.

2024-02-21 07:03 UTC, boegel commented
Going in, thanks @pavelToman!

2024-02-21 07:03 UTC, merged