add `download_instructions` to Amber easyconfigs
easybuilders/easybuild-easyconfigs pull request #19935
Opened 2024-02-19 19:52 UTC by branfosj

(created using `eb --new-pr`)

2024-02-19 22:55 UTC, Micket requested changes

2024-02-19 22:55 UTC, Micket commented on easybuild/easyconfigs/a/Amber/Amber-20.11-foss-2020a-AmberTools-20.15-Python-3.8.2.eb
> +homepage = 'http://ambermd.org/'
https

2024-02-20 08:54 UTC, branfosj commented on easybuild/easyconfigs/a/Amber/Amber-20.11-foss-2020a-AmberTools-20.15-Python-3.8.2.eb
> +homepage = 'http://ambermd.org/'
e088add

2024-02-23 16:34 UTC, jfgrimm approved these changes
lgtm

2024-02-23 16:34 UTC, merged