{bio,devel,vis}[GCCcore/12.3.0] QuPath v0.5.0, Gradle v8.6, OpenSlide-Java v0.12.4 w/ Java 17
easybuilders/easybuild-easyconfigs pull request #19962
Opened 2024-02-23 13:52 UTC by PetrKralCZ

(created using `eb --new-pr`)

2024-02-23 14:36 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-02-23 15:21 UTC, boegel requested changes

2024-02-23 15:21 UTC, boegel commented on easybuild/easyconfigs/g/Gradle/Gradle-8.6.eb
> +    'files': ['bin/gradle'],
Please include a sanity check command as well:

```
sanity_check_commands = ["gradle --help"]
```

Also, `Gradle` is a Java app, the `gradle` script uses the `java` command, so `Java` should be included as a runtime dependency (and the `versionsuffix` should be set accordingly)

2024-02-23 15:21 UTC, boegel commented on easybuild/easyconfigs/o/OpenSlide-Java/OpenSlide-Java-0.12.4-GCCcore-12.3.0-Java-17.eb
> +        'lib/openslide-java/libopenslide-jni.so',
```suggestion
        'lib/openslide-java/libopenslide-jni.%s' % SHLIB_EXT,

2024-02-23 15:21 UTC, boegel commented on easybuild/easyconfigs/o/OpenSlide-Java/OpenSlide-Java-0.12.4-GCCcore-12.3.0-Java-17.eb
> +    'dirs': []
```suggestion
    'dirs': [],

2024-02-23 15:21 UTC, boegel commented on easybuild/easyconfigs/q/QuPath/QuPath-0.5.0-GCCcore-12.3.0-Java-17.eb
> +    'dirs': ['lib'],
I would make this a bit more specific, by checking for `lib/app` + `lib/runtime`, and also checking for `'lib/libapplauncher.%s' % SHLIB_EXT` in `files` list

2024-02-23 20:44 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-02-27 17:07 UTC, boegel requested changes

2024-02-27 17:07 UTC, boegel commented on easybuild/easyconfigs/q/QuPath/QuPath-0.5.0-GCCcore-12.3.0-Java-17.eb
> +}
```suggestion
sanity_check_paths = {
    'files': ['bin/qupath', 'lib/libapplauncher.%s' % SHLIB_EXT],
    'dirs': ['lib/app', 'lib/runtime'],
}
```

2024-02-27 17:07 UTC, boegel commented on easybuild/easyconfigs/q/QuPath/QuPath-0.5.0-GCCcore-12.3.0-Java-17.eb
> +sanity_check_commands = ['%(name)s --help']
```suggestion
sanity_check_commands = ["qupath --help"]
```

2024-02-27 17:18 UTC, boegel requested changes

2024-02-27 17:24 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3129.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/ff1715590058c810c7e2e28bf836fd43 for a full test report.

2024-02-27 17:27 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-02-27 18:39 UTC, boegel approved these changes

2024-02-27 18:40 UTC, boegel commented
Going in, thanks @PetrKralCZ!

2024-02-27 18:40 UTC, merged