Create DIRAC-24.0-foss-2023a.eb
easybuilders/easybuild-easyconfigs pull request #19960
Opened 2024-02-23 08:35 UTC by agustinaucar

2024-02-23 14:46 UTC, jfgrimm requested changes

2024-02-23 14:46 UTC, jfgrimm commented on easybuild/easyconfigs/d/DIRAC/DIRAC-24.0-foss-2023a.eb
> +]
`DIRAC-23.0-foss-2023a.eb` also has dependencies on `SciPy-bundle` and `h5py`. Is there a reason they're not included here?

2024-02-23 14:52 UTC, jfgrimm submitted a review, later dismissed

2024-02-23 14:52 UTC, jfgrimm commented on easybuild/easyconfigs/d/DIRAC/DIRAC-24.0-foss-2023a.eb
> +sources = ['DIRAC-%(version)s-Source.tgz']
```suggestion
sources = ['DIRAC-%(version)s-Source.tar.gz']
```

2024-02-24 12:40 UTC, agustinaucar commented on easybuild/easyconfigs/d/DIRAC/DIRAC-24.0-foss-2023a.eb
> +]
Hi @jfgrimm. They are not needed anymore, at least for foss compilations.

2024-06-06 14:52 UTC, agustinaucar commented
Hi! Are there any news about this? Tks!

2025-06-14 09:10 UTC, agustinaucar commented
@smoors : Now that you're reviewing #23053, could you please also review these previous MRs :

#19958
#19959 
#19960 

?

Thanks!

2025-06-21 07:59 UTC, smoors commented
@boegelbot please test @ jsc-zen3

2025-06-21 20:16 UTC, agustinaucar commented
> @boegelbot please test @ jsc-zen3

Hi @smoors ! Could you please rerun the test set? Thanks!

2025-06-21 21:12 UTC, Thyre commented
@boegelbot please test @ jsc-zen3

2025-06-22 19:39 UTC, smoors approved these changes
lgtm

2025-09-23 20:58 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3522.doduo.os - Linux RHEL 9.6, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.9.21
See https://gist.github.com/boegel/fc94cbcf43fdd8b1a48b587321c2e8c3 for a full test report.

2025-09-24 05:52 UTC, boegel commented
Going in, thanks @agustinaucar!

2025-09-24 05:52 UTC, merged