{lib}[foss/2023a] CellTypist v1.6.2, igraph v0.10.10, python-igraph v0.11.4, ...
easybuilders/easybuild-easyconfigs pull request #19981
Opened 2024-02-27 13:10 UTC by pavelToman

(created using `eb --new-pr`)

2024-02-27 13:11 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-02-27 13:25 UTC, boegel requested changes

2024-02-27 13:25 UTC, boegel commented on easybuild/easyconfigs/c/CellTypist/CellTypist-1.6.2-foss-2023a.eb
> +    }),
@pavelToman Please include as dependency along with `Python-bundle-PyPI`, this bundle provides both `requests` and `click` so there's no need to include them here directly as extensions.

You can still stick to using `PythonBundle` even though there's only one extension (CellTypist itself)

2024-02-27 13:25 UTC, boegel commented on easybuild/easyconfigs/p/python-igraph/python-igraph-0.11.4-foss-2023a.eb
> +    ('cffi', '1.16.0', {
pycparser and `cffi` are included in `Python-bundle-PyPI`, please use that as dependency and remove these 2 extensions

2024-02-27 13:25 UTC, boegel commented on easybuild/easyconfigs/p/python-igraph/python-igraph-0.11.4-foss-2023a.eb
> +}
This can be removed (it's exactly the same as what `PythonBundle` uses as default sanity check paths)

2024-02-27 13:34 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-02-27 18:36 UTC, pavelToman commented
> Test report by @boegelbot **FAILED** Build succeeded for 3 out of 6 (5 easyconfigs in total) jsczen3c1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.3, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.18 See https://gist.github.com/boegelbot/b864f431d6a84eb84f8b3e39b553c6de for a full test report.

Seems LD_LIBRARY_PATH is set wrong? https://doc.courtbouillon.org/cairocffi/stable/overview.html#importing

2024-02-28 14:25 UTC, jfgrimm commented
@pavelToman it's missing a dependency on cairo at the very least:
```
== 2024-02-27 17:46:58,029 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:126 in __init__): Sanity check failed: sanity check command python -c 'from igraph.drawing.cairo.utils import find_cairo; cairo = find_cairo(); cairo.Context' exited with code 1 (output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/project/def-maintainers/boegelbot/rocky9/zen3/software/python-igraph/0.11.4-foss-2023a/lib/python3.11/site-packages/igraph/drawing/utils.py", line 428, in __getattr__
    raise AttributeError(self._message)
AttributeError: Plotting not available; please install pycairo or cairocffi
)
extensions sanity check failed for 1 extensions: cairocffi
failing sanity check for 'cairocffi' extension: command "python -c "import cairocffi"" failed; output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/project/def-maintainers/boegelbot/rocky9/zen3/software/python-igraph/0.11.4-foss-2023a/lib/python3.11/site-packages/cairocffi/__init__.py", line 47, in <module>
    cairo = dlopen(
            ^^^^^^^
  File "/project/def-maintainers/boegelbot/rocky9/zen3/software/python-igraph/0.11.4-foss-2023a/lib/python3.11/site-packages/cairocffi/__init__.py", line 44, in dlopen
    raise OSError(error_message)  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
```

2024-02-28 16:56 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-03-01 11:02 UTC, boegel commented
@boegelbot please test @ generoso

2024-03-01 11:05 UTC, boegel approved these changes
lgtm

2024-03-01 11:41 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (5 easyconfigs in total)
node3102.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/272dfd3c5e00ecbb7c48bd5e8a860ea6 for a full test report.

2024-03-01 12:32 UTC, boegel commented
Going in, thanks @pavelToman!

2024-03-01 12:32 UTC, merged