{bio}[foss/2023b] BWA v0.7.17
easybuilders/easybuild-easyconfigs pull request #20031
Opened 2024-03-05 00:52 UTC by grpiccoli

(created using `eb --new-pr`)

2024-03-14 14:50 UTC, verdurin requested changes

2024-03-14 14:50 UTC, verdurin commented on easybuild/easyconfigs/b/BWA/BWA-0.7.17-foss-2023b.eb
> +homepage = 'http://bio-bwa.sourceforge.net/'
```suggestion
homepage = 'https://bio-bwa.sourceforge.net/'
```
Looks like `https` works now, at last.

2024-03-14 14:50 UTC, verdurin commented on easybuild/easyconfigs/b/BWA/BWA-0.7.17-foss-2023b.eb
> +toolchain = {'name': 'foss', 'version': '2023b'}
I think some of the blank lines between sub-sections have been lost, which makes it less readable.

Please add a blank line here before `toolchain`, and another after `toolchainopts`.

2024-03-14 14:51 UTC, verdurin commented
@grpiccoli Welcome to EasyBuild, and thanks for your contribution.
I've added a couple of comments, with suggestions for small fixes.

2024-03-15 00:21 UTC, grpiccoli commented
Hi @verdurin, thank you for your welcome and feedback.
I just pushed a corrected version using --update-pr.
Cheers

2024-03-24 20:52 UTC, grpiccoli reviewed
Thank you for your feedback

2024-03-24 22:12 UTC, grpiccoli reviewed
approved

2024-03-25 03:09 UTC, grpiccoli commented
Hi @verdurin,

I deleted the original file which was using foss 2023b and switch it for foss 2023a, so you will not see your changes reflected on the file that was deleted but the new file instead. I also added you as a contributor,

Thanks

2024-04-02 19:30 UTC, grpiccoli commented
Closing this PR and opening a fresh one, Cheers

2024-04-02 19:30 UTC, closed without merging