Correct configuration of QuantumESPRESSO for 6.7/7.2
easybuilders/easybuild-easyconfigs pull request #20070
Opened 2024-03-08 10:19 UTC by ocaisa

(created using `eb --new-pr`)

2024-03-08 10:21 UTC, ocaisa commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3241"

2024-03-08 10:27 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3241"

2024-03-09 19:21 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3241"

2024-03-11 11:05 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3241"

2024-03-18 21:21 UTC, ocaisa commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3241"

2024-03-20 08:20 UTC, ocaisa commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3241 QuantumESPRESSO-7.0-foss-2021b.eb QuantumESPRESSO-7.1-intel-2022a.eb"

2024-03-20 18:27 UTC, Micket requested changes
Based on https://github.com/easybuilders/easybuild-easyblocks/pull/3258

2024-03-20 18:27 UTC, Micket commented on easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.2-foss-2022b.eb
> +# building gipaw requires FoX
```suggestion
```

2024-03-20 18:27 UTC, Micket commented on easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.2-foss-2023a.eb
> +# building gipaw requires FoX
```suggestion
```

2024-03-20 18:27 UTC, Micket commented on easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.2-intel-2022b.eb
> +# building gipaw requires FoX
```suggestion
```

2024-03-21 09:45 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3241 QuantumESPRESSO-7.2-foss-2022b.eb QuantumESPRESSO-7.2-intel-2022b.ebQuantumESPRESSO-7.2-foss-2023a.eb"

2024-04-14 11:34 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3306 QuantumESPRESSO-7.3-foss-2023a.eb QuantumESPRESSO-7.3-intel-2023a.eb"

2024-04-14 11:43 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3306 QuantumESPRESSO-7.2-foss-2023a.eb QuantumESPRESSO-7.2-intel-2022b.eb QuantumESPRESSO-7.2-foss-2022b.eb"

2024-04-14 11:50 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3306 QuantumESPRESSO-7.3-foss-2023a.eb QuantumESPRESSO-7.3-intel-2023a.eb"

2024-04-14 12:00 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3306 QuantumESPRESSO-7.1-foss-2022a.eb QuantumESPRESSO-7.1-intel-2022a.eb"

2024-04-14 12:11 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3306 QuantumESPRESSO-7.0-foss-2021b.eb QuantumESPRESSO-7.0-intel-2021b.eb"

2024-04-14 12:16 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3306 QuantumESPRESSO-7.0-foss-2021b.eb QuantumESPRESSO-7.0-intel-2021b.eb QuantumESPRESSO-6.7-foss-2021a.eb QuantumESPRESSO-6.7-intel-2021a.eb QuantumESPRESSO-6.8-foss-2021a.eb QuantumESPRESSO-6.8-intel-2021a.eb QuantumESPRESSO-6.8-foss-2021b.eb"

2024-04-14 18:30 UTC, ocaisa commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3306 QuantumESPRESSO-7.3-foss-2023a.eb QuantumESPRESSO-7.3-intel-2023a.eb"

2024-04-14 18:50 UTC, ocaisa commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3306 QuantumESPRESSO-7.2-foss-2023a.eb QuantumESPRESSO-7.2-intel-2022b.eb QuantumESPRESSO-7.2-foss-2022b.eb"

2024-04-15 07:57 UTC, boegel commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3306 QuantumESPRESSO-7.0-intel-2021b.eb"

2024-04-17 10:54 UTC, ocaisa commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3306 QuantumESPRESSO-7.0-intel-2021b.eb

2024-06-13 14:19 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3338"

2024-06-14 09:51 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3338 QuantumESPRESSO-7.3-foss-2023a.eb"

2024-06-14 10:01 UTC, ocaisa commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3338 QuantumESPRESSO-7.0-intel-2021b.eb"

2024-06-14 12:42 UTC, ocaisa commented
@boegel This is now succeeding for all easyconfigs in the PR _except_ `QuantumESPRESSO-7.0-intel-2021b.eb` which seems to be totally broken, I have no fix for that so I am just going to remove it from the PR and pretend I didn't notice

2024-06-14 12:45 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3338"

2024-06-14 12:50 UTC, ocaisa commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3338"

2024-07-16 15:18 UTC, ocaisa commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3338"

2024-07-16 15:20 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3338"

2024-07-22 12:46 UTC, ocaisa commented
There are cases where there are a significant number of test failures in old QE easyconfigs. The test suite was never run in the past so these were not caught. With the merge of https://github.com/easybuilders/easybuild-easyblocks/pull/3338 I've explicitly skipped the test step for these cases.

2024-07-22 12:47 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3338"

2024-07-22 12:57 UTC, ocaisa commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3338"

2024-07-23 16:01 UTC, jfgrimm approved these changes

2024-07-23 16:02 UTC, merged