{bio}[foss/2023a] Single-cell-python-bundle v2024.02
easybuilders/easybuild-easyconfigs pull request #20116
Opened 2024-03-14 14:03 UTC by pavelToman

(created using `eb --new-pr`)

2024-04-05 12:50 UTC, boegel requested changes

2024-04-05 12:50 UTC, boegel commented on easybuild/easyconfigs/s/Single-cell-python-bundle/Single-cell-python-bundle-2024.02-foss-2023a.eb
> +homepage = 'xxx'
use `(none)` here

2024-04-05 12:50 UTC, boegel commented on easybuild/easyconfigs/s/Single-cell-python-bundle/Single-cell-python-bundle-2024.02-foss-2023a.eb
> +description = """Bundle of softwares for single-cell research ???"""
```suggestion
description = """Bundle of tools for single-cell sequence analysis"""

2024-04-24 14:23 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-05-02 17:55 UTC, boegel commented
@boegelbot please test @ generoso

2024-05-02 19:46 UTC, boegel requested changes

2024-05-02 19:46 UTC, boegel commented on easybuild/easyconfigs/s/Single-cell-python-bundle/Single-cell-python-bundle-2024.02-foss-2023a.eb
> +# builddependencies = [('poetry', '1.5.1')]
@pavelToman `poetry` is required for installing `pypi-latest`, so you'll have to uncomment this?

See failed test report in https://gist.github.com/boegelbot/caeab59f44f6611f00bff1c7073031c9

2024-05-06 09:01 UTC, boegel commented
@boegelbot please test @ generoso

2024-05-06 16:49 UTC, pavelToman commented
Fix for the fsspec error: https://github.com/easybuilders/easybuild-easyconfigs/pull/20477

2024-05-07 15:34 UTC, boegel commented on easybuild/easyconfigs/s/Single-cell-python-bundle/Single-cell-python-bundle-2024.02-foss-2023a.eb
> +        'preinstallopts': "sed -i '28d' setup.py && ",
@pavelToman Can you explain why this is needed?

It seems like you're just removing the requirement for `tensorflow-probability` here?

2024-05-07 19:01 UTC, boegel commented on easybuild/easyconfigs/s/Single-cell-python-bundle/Single-cell-python-bundle-2024.02-foss-2023a.eb
> +        'preinstallopts': "sed -i '28d' setup.py && ",
OK, please add a comment in the easyconfig to explain that then.

And ideally we use a `sed` command that shows what gets removed exactly (so not using a random line number)

2024-05-10 09:00 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-06-26 08:18 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-06-26 11:55 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-06-26 14:06 UTC, pavelToman commented
> Test report by @boegelbot **FAILED** Build succeeded for 4 out of 5 (5 easyconfigs in total) cns1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8 See https://gist.github.com/boegelbot/377161a87e9bfdc11f25e09571b3431e for a full test report.

Seems GDAL/3.7.1-foss-2023a is missing on generoso?

2024-06-26 14:06 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-06-27 10:06 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-07-04 12:36 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3158.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/4cba265b4d6d703bae34ed679496de75 for a full test report.

2024-07-05 20:03 UTC, boegel approved these changes
lgtm

2024-07-05 20:03 UTC, boegel commented
Going in, thanks @pavelToman!

2024-07-05 20:03 UTC, merged