{bio}[foss/2023a] hdWGCNA v0.3.00 w/ R 4.3.2
easybuilders/easybuild-easyconfigs pull request #20124
Opened 2024-03-14 17:39 UTC by boegel

(created using `eb --new-pr`)

2024-03-14 18:43 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3136.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/49a5836483c01b834c7e80eef8e49875 for a full test report.

2024-03-14 18:44 UTC, boegel commented
@boegelbot please test @ generoso

2024-03-14 18:46 UTC, branfosj requested changes

2024-03-14 18:46 UTC, branfosj commented on easybuild/easyconfigs/h/hdWGCNA/hdWGCNA-0.3.00-foss-2023a-R-4.3.2.eb
> +description = "R-package for the analysis of single-cell TCR/BCR data in the Seurat ecosystem"
```suggestion
homepage = 'https://smorabit.github.io/hdWGCNA/'
description = """hdWGCNA is an R package for performing weighted gene co-expression network analysis (WGCNA) in high 
 dimensional transcriptomics data such as single-cell RNA-seq or spatial transcriptomics. hdWGCNA is highly modular 
 and can construct context-specific co-expression networks across cellular and spatial hierarchies. hdWGNCA identifies 
 modules of highly co-expressed genes and provides context for these modules via statistical testing and biological 
 knowledge sources. hdWGCNA uses datasets formatted as Seurat objects."""
```

2024-03-14 19:12 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-03-15 02:32 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/35db06016fb2e413661bc2cc30c5b6b8 for a full test report.

2024-03-15 09:27 UTC, branfosj approved these changes

2024-03-15 10:42 UTC, branfosj commented
Going in, thanks @boegel!

2024-03-15 10:42 UTC, merged