{geo}[foss/2023a] MODFLOW v6.4.4
easybuilders/easybuild-easyconfigs pull request #20142
Opened 2024-03-18 16:59 UTC by casparvl

(created using `eb --new-pr`)

2024-03-18 17:00 UTC, casparvl commented
@boegelbot please test @ jsc-zen3

2024-03-18 17:19 UTC, casparvl commented
@boegelbot please test @ generoso

2024-03-18 17:43 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/a6bd8ed795de2654f2ea94be7a2ac547 for a full test report.

2024-03-19 17:35 UTC, boegel approved these changes
lgtm

2024-03-19 17:36 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3160.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/1fd6d63c8d1f441a99f7242d0d4865c5 for a full test report.

2024-03-19 17:36 UTC, boegel requested changes

2024-03-19 17:36 UTC, boegel commented on easybuild/easyconfigs/m/MODFLOW/MODFLOW-6.4.4-foss-2023a.eb
> +    'dirs': ['bin', 'lib'],
no need to check for non-empty `bin`/`lib` dir if you're already checking for specific binaries/libraries

```suggestion
    'dirs': [],

2024-03-19 17:37 UTC, boegel approved these changes

2024-03-19 17:37 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-03-19 17:40 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/27b70bba188c3800adb108bc07cbe244 for a full test report.

2024-03-19 21:57 UTC, boegel commented
Going in, thanks @casparvl!

2024-03-19 21:57 UTC, merged