{tools}[GCCcore/12.3.0,gfbf/2023a] phonemizer v3.2.1, eSpeak-NG v1.51, festival v2.5.0, ... w/ voices 20200330
easybuilders/easybuild-easyconfigs pull request #20151
Opened 2024-03-19 12:13 UTC by appolloford

(created using `eb --new-pr`)

2024-03-19 15:03 UTC, zao commented
Test report by @zao
**FAILED**
Build succeeded for 3 out of 6 (6 easyconfigs in total)
eb-mix.zao.se - Linux Rocky Linux 9.2 (Blue Onyx), x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.9.16
See https://gist.github.com/zao/38aa681fe1d4f455d5454a3b3a2b46d2 for a full test report.

2024-03-19 15:05 UTC, zao commented
Regarding my FAILED test report - the initial install worked but a `--rebuild -u` failed as shown.

2024-03-19 18:00 UTC, casparvl commented
Test report by @casparvl
**FAILED**
Build succeeded for 6 out of 8 (6 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/42ba85790bd2f59aba19531bc6759345 for a full test report.

2024-03-19 20:44 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 7 out of 7 (6 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 8.6, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/casparvl/99813247e44fef76256d30a26954f870 for a full test report.

2024-03-19 20:45 UTC, casparvl commented
@boegelbot please test @ generoso

2024-03-19 20:51 UTC, casparvl commented
@boegelbot please test @ jsc-zen3

2024-03-19 21:27 UTC, casparvl commented on easybuild/easyconfigs/s/sonic/sonic-20180202-gfbf-2023a.eb
> +# dependencies = [('FFTW', '3.3.8')]
This can be removed I suppose?

2024-03-19 21:28 UTC, casparvl requested changes
I think there's one comment that can still be removed. Other than that, looks good to me.

2024-03-19 22:49 UTC, appolloford commented on easybuild/easyconfigs/s/sonic/sonic-20180202-gfbf-2023a.eb
> +# dependencies = [('FFTW', '3.3.8')]
Thanks! Done :)

2024-03-20 12:44 UTC, casparvl commented
@boegelbot please test @ jsc-zen3

2024-03-20 13:39 UTC, casparvl approved these changes
Lgtm!

2024-03-20 13:40 UTC, casparvl commented
Going in, thanks @appolloford!

2024-03-20 13:40 UTC, merged