{bio}[GCC/12.3.0] PLINK v2.00a3.7
easybuilders/easybuild-easyconfigs pull request #20208
Opened 2024-03-25 15:56 UTC by benczaja

(created using `eb --new-pr`)

2024-03-26 12:58 UTC, akesandgren commented
@boegelbot Please test @ jsc-zen2

2024-03-26 13:06 UTC, akesandgren requested changes
In general, please make this more like the PLINK-2.00a3.7-foss-2022a.eb, but based on gfbf/2023a instead.
It's missing PLINK1 at the moment.

2024-03-26 13:06 UTC, akesandgren commented on easybuild/easyconfigs/p/PLINK/PLINK-2.00a3.7-GCC-12.3.0.eb
> +    ('FlexiBLAS', '3.3.1'),
Drop FlexiBLAS and use gfbf/2023a as above instead

2024-03-26 13:06 UTC, akesandgren commented on easybuild/easyconfigs/p/PLINK/PLINK-2.00a3.7-GCC-12.3.0.eb
> +buildopts += ' LDFLAGS="$LIBS -ldeflate -lz -lzstd" ZLIB="" CSRC="include/SFMT.c"'
Since you have -lz here zlib should also be explicitly mentioned in the dependencies.

2024-03-27 08:33 UTC, benczaja commented
Hi @akesandgren ,

Sorry I am still cathcin up to the new naming schemes. Since I renamed the whole easyconfig (which now is gfbf), I just opened up a new PR so it can be easily found back again https://github.com/easybuilders/easybuild-easyconfigs/pull/20224

I suggest that you close this PR and review https://github.com/easybuilders/easybuild-easyconfigs/pull/20224

I have incorporated all your suggested edits

2024-03-27 11:20 UTC, akesandgren commented
Closing, better one available in #20224

2024-03-27 11:20 UTC, closed without merging