{cae}[system/system] FLUENT v2024R1
easybuilders/easybuild-easyconfigs pull request #20225
Opened 2024-03-27 10:19 UTC by boegel

(created using `eb --new-pr`)

2024-03-27 13:22 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3125.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/ee9bbd2fb24dc66c60b97b4a011a9a91 for a full test report.

2024-03-29 21:47 UTC, Micket requested changes

2024-03-29 21:47 UTC, Micket commented on easybuild/easyconfigs/f/FLUENT/FLUENT-2024R1.eb
> +
download instructions

2025-06-11 12:12 UTC, Micket commented on easybuild/easyconfigs/f/FLUENT/FLUENT-2024R1.eb
> +
```suggestion
download_instructions = f"""{name} requires manual download from {homepage}
Required download: {' '.join(sources)}"""
```

2025-06-11 12:12 UTC, Micket approved these changes
lgtm.  @boegel test report?

2025-06-16 14:19 UTC, boegel commented
Test report coming up...

2025-06-16 14:32 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3515.doduo.os - Linux RHEL 9.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.9.18
See https://gist.github.com/boegel/2181ef1ca1861b45d8f2d1976f2459fe for a full test report.

2025-06-16 14:37 UTC, verdurin approved these changes
Looks fine.

2025-06-16 14:37 UTC, verdurin commented
Going in, thanks @boegel!

2025-06-16 15:25 UTC, verdurin commented
Going in, thanks @boegel!

2025-06-16 15:25 UTC, merged