{lib}[GCC 11.2.0-13.2.0] UCX 1.16.0-rc4
easybuilders/easybuild-easyconfigs pull request #20237
Opened 2024-03-28 08:11 UTC by hajgato

Recent intel MPI might need ucx >=1.16.0 if MLNX/NVIDIA ofed >= 23.10 is installed.

2024-03-28 11:43 UTC, boegel requested changes

2024-03-28 11:43 UTC, boegel commented on easybuild/easyconfigs/u/UCX/UCX-1.16.0-rc4-GCCcore-11.2.0.eb
> +sources = ['%(namelower)s-%(version)s.tar.gz']
@hajgato The tarball is named `ucx-1.16.0.tar.gz`, so we'll need something like this:

```suggestion
sources = [{'download_filename': 'ucx-%s.tar.gz' % version.split('-'), 'filename': SOURCELOWER_TAR_GZ}]

2024-03-28 12:17 UTC, zao commented
Test report by @zao
**FAILED**
Build succeeded for 0 out of 5 (5 easyconfigs in total)
eb-mix.zao.se - Linux Ubuntu 24.04 (Noble Numbat), x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.12.2
See https://gist.github.com/zao/44968f5eef996dfb2aed690f9246f4ed for a full test report.

2024-03-28 12:19 UTC, zao commented
`/bin/bash: line 1: ./autogen.sh: No such file or  (took 1 secs)`

2024-03-28 21:19 UTC, boegel commented
@boegelbot please test @ generoso

2024-03-28 21:47 UTC, boegel approved these changes

2024-03-29 00:10 UTC, zao commented
Test report by @zao
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
eb-mix.zao.se - Linux Ubuntu 24.04 (Noble Numbat), x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.12.2
See https://gist.github.com/zao/3aceb007dfdd1a4210a1063a48ea5948 for a full test report.

2024-03-29 00:36 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (5 easyconfigs in total)
node3125.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/699081e4ae8b742a8a2055a599d29021 for a full test report.

2024-03-29 08:48 UTC, boegel commented
Going in, thanks @hajgato!

2024-03-29 08:48 UTC, merged