{tools}[foss/2023a] Optuna v3.5.0
easybuilders/easybuild-easyconfigs pull request #20264
Opened 2024-04-02 09:38 UTC by ThomasHoffmann77

(created using `eb --new-pr`)

2024-04-02 13:11 UTC, Micket requested changes

2024-04-03 09:32 UTC, ThomasHoffmann77 commented on easybuild/easyconfigs/r/Redis/Redis-7.2.3-GCC-12.3.0.eb
> +toolchain = {'name': 'GCC', 'version': '12.3.0'}
@Micket done

2024-04-03 09:32 UTC, ThomasHoffmann77 commented on easybuild/easyconfigs/r/redis-py/redis-py-5.0.1-foss-2023a.eb
> +toolchain = {'name': 'foss', 'version': '2023a'}
done

2024-04-03 15:03 UTC, Micket approved these changes
lgtm

2024-04-03 15:04 UTC, Micket commented
@boegelbot please test @ jsc-zen3

2024-04-03 15:09 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 6 out of 6 (4 easyconfigs in total)
vera40-1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz, 1 x NVIDIA Tesla T4, 550.54.14, Python 3.6.8
See https://gist.github.com/Micket/166d274983fd3499ae0104e5d145d929 for a full test report.

2024-04-03 17:38 UTC, Micket commented
Just loading Optuna and it works with CuPy directly, so i'm not sure we need to add this as a strict dep to CuPy, it can be opt-in at no loss for those who actually want to optimize the code evaluation i guess.

2024-04-03 17:38 UTC, Micket commented
@boegelbot please test @ generoso

2024-04-03 17:38 UTC, Micket commented
Going in, thanks @ThomasHoffmann77!

2024-04-03 17:38 UTC, merged