{data}[gfbf/2023a] polars v0.20.2
easybuilders/easybuild-easyconfigs pull request #20275
Opened 2024-04-03 05:39 UTC by akesandgren

(created using `eb --new-pr`)

2024-04-15 20:11 UTC, boegel commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--force-download"
EB_BRANCH=5.0.x

2024-04-30 08:05 UTC, lexming requested changes

2024-04-30 08:05 UTC, lexming commented on easybuild/easyconfigs/p/polars/polars-0.20.2-gfbf-2023a.eb
> +    {'jsonpath_lib-0.3.0.tar.gz': 'ae7f51d58613783097caa5281dc7f45b541975ab6067be49945119dae27cf5b3'},
Due to recent changes on the creation of reproducible archives in `5.0.x`, this checksum has changed:
```suggestion
    {'jsonpath_lib-0.3.0.tar.gz': 'dfb5eb7f47b5b5a7b35262f7b41787a785958001a23ff039cdae926396c6af96'},
```

2024-04-30 08:51 UTC, akesandgren commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--force-download"
EB_BRANCH=5.0.x

2024-05-01 09:16 UTC, lexming approved these changes
LGTM

2024-05-01 09:17 UTC, lexming commented
Merging, thanks @akesandgren !

2024-05-01 09:17 UTC, merged

2024-07-31 14:55 UTC, boegel commented
I've manually installed this easyconfig on `generoso` using `--ignore-checksums`, it was merged prematurely, since it depends on a new feature implemented in EasyBuild 5.0 (consistent checksums for source tarballs created by cloning a Git repository)

2024-07-31 15:44 UTC, smoors commented
> I've manually installed this easyconfig on `generoso` using `--ignore-checksums`, it was merged prematurely, since it depends on a new feature implemented in EasyBuild 5.0 (consistent checksums for source tarballs created by cloning a Git repository)

thanks! looks like generoso doesn't support the `EB_BRANCH` option

2024-07-31 16:05 UTC, boegel commented
> > I've manually installed this easyconfig on `generoso` using `--ignore-checksums`, it was merged prematurely, since it depends on a new feature implemented in EasyBuild 5.0 (consistent checksums for source tarballs created by cloning a Git repository)
> 
> thanks! looks like generoso doesn't support the `EB_BRANCH` option

Indeed, that's only on `jsc-zen3`