{lib}[GCCcore/13.2.0] libzip v1.10.1
easybuilders/easybuild-easyconfigs pull request #20283
Opened 2024-04-03 21:59 UTC by tanmoy1989

(created using `eb --new-pr`)

2024-04-03 22:38 UTC, Micket approved these changes
lgtm

2024-04-03 22:53 UTC, Micket requested changes
file has execute permissions, it must now, please change this (you may need to do it manually in the branch with git, not sure if EB's pr functionality can do this fix, maybe, maybe not)

2024-04-04 15:11 UTC, boegel submitted a review, later dismissed

2024-04-04 15:35 UTC, tanmoy1989 commented on easybuild/easyconfigs/l/libzip/libzip-1.10.1-GCCcore-13.2.0.eb
> +        'bin/zipcmp',
I am not sure how would I incorporate that? Any suggestions, please?

2024-04-04 18:42 UTC, tanmoy1989 commented on easybuild/easyconfigs/l/libzip/libzip-1.10.1-GCCcore-13.2.0.eb
> +        'bin/zipcmp',
I have tried now adding sanity check commands. Please let me know if this what you meant or if this correct.

2024-06-27 15:28 UTC, tanmoy1989 commented
Can we please have update on this?

2024-06-27 15:32 UTC, bedroge commented on easybuild/easyconfigs/l/libzip/libzip-1.10.1-GCCcore-13.2.0.eb
> +description = "libzip is a C library for reading, creating, and modifying zip archives.."
Not sure what happened in https://github.com/easybuilders/easybuild-easyconfigs/pull/20283/commits/ccb9c6942a2838782d7ef256443ec2260afb7abf, but let's revert this: 
```suggestion
description = "libzip is a C library for reading, creating, and modifying zip archives."
```

2024-06-27 16:18 UTC, bedroge commented
@boegelbot please test @ generoso

2024-06-27 18:40 UTC, bedroge commented
```
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
```
and
```
sanity check command zipmerge -h exited with code 127 (output: zipmerge: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
```
seem to suggest that we need to add bzip2 as a dependency.

2024-06-27 18:45 UTC, bedroge commented on easybuild/easyconfigs/l/libzip/libzip-1.10.1-GCCcore-13.2.0.eb
> +dependencies = [('zlib', '1.2.13')]
So, I suspect this should work:
```suggestion
dependencies = [
    ('zlib', '1.2.13'),
    ('bzip2', '1.0.8'),
    ('XZ', '5.4.4'),
    ('zstd', '1.5.5'),
]
```

2024-06-27 18:47 UTC, tanmoy1989 commented
Thank you, really appreciate your explanation and suggestion. I accepted the changes you suggested.

2024-06-27 18:49 UTC, bedroge commented
@boegelbot please test @ generoso

2024-06-27 18:52 UTC, bedroge commented
@boegelbot please test @ jsc-zen3

2024-06-27 18:53 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/0ead041f3f227d42eee1e63ff2efa086 for a full test report.

2024-06-27 18:55 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/eb44015f9825768d82db429748e2d919 for a full test report.

2024-06-27 19:07 UTC, bedroge commented
> Test report by @boegelbot **FAILED** Build succeeded for 0 out of 1 (1 easyconfigs in total) jsczen3c1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.4, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.18 See https://gist.github.com/boegelbot/0e979a2277edbe4a1ce0523207a29b2f for a full test report.

Hmm, looks like it also needs OpenSSL. In my build log I also see that it's picking this up.

2024-06-27 19:08 UTC, bedroge commented on easybuild/easyconfigs/l/libzip/libzip-1.10.1-GCCcore-13.2.0.eb
> +    ('zlib', '1.2.13'),
Let's try adding OpenSSL 3:
```suggestion
    ('OpenSSL', '3'),
    ('zlib', '1.2.13'),
```

2024-06-27 19:23 UTC, bedroge commented
@boegelbot please test @ jsc-zen3

2024-06-27 20:14 UTC, bedroge commented
@boegelbot please test @ jsc-zen3

2024-06-28 06:56 UTC, bedroge commented
@boegelbot please test @ generoso

2024-06-28 07:23 UTC, bedroge commented on easybuild/easyconfigs/l/libzip/libzip-1.10.1-GCCcore-13.2.0.eb
> +    ('OpenSSL', '3'),
Oops, forgot to specify the SYSTEM toolchain, and let's stick to 1.1 for now (other easyconfigs in this toolchain are using that version as well):
```suggestion
    ('OpenSSL', '1.1', '', SYSTEM),
```

2024-06-28 07:24 UTC, bedroge commented
@boegelbot please test @ jsc-zen3

2024-06-28 07:34 UTC, bedroge commented
@boegelbot please test @ jsc-zen3

2024-06-28 07:35 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/44605e4352760684671bea43ab30b246 for a full test report.

2024-06-28 07:39 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/a35a727faff7bd95208e0f029e0f08e2 for a full test report.

2024-06-28 08:11 UTC, bedroge approved these changes
Looks good to me.

2024-06-28 08:12 UTC, bedroge commented
Going in, thanks @tanmoy1989!

2024-06-28 08:12 UTC, merged