{lib,math}[GCCcore/12.3.0,gfbf/2023a] Transformers v4.39.3, tokenizers v0.15.2
easybuilders/easybuild-easyconfigs pull request #20322
Opened 2024-04-09 14:07 UTC by VRehnberg

(created using `eb --new-pr`)

2024-04-09 17:02 UTC, Micket requested changes

2024-04-09 17:02 UTC, Micket commented on easybuild/easyconfigs/t/tokenizers/tokenizers-0.15.2-GCCcore-12.3.0-Rust-1.75.0.eb
> +versionsuffix = '-Rust-%s' % _rust_ver
Don't need a suffix for a builddep only.

2024-04-10 06:18 UTC, VRehnberg commented
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis1-13 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 550.54.14, Python 3.6.8
See https://gist.github.com/VRehnberg/c3b2c1f6cdfad2607a901ddb46f33be1 for a full test report.

2024-04-10 06:19 UTC, VRehnberg commented
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis1-13 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 550.54.14, Python 3.6.8
See https://gist.github.com/VRehnberg/69325bb64e7e119781f902a2d413da25 for a full test report.

2024-04-10 13:29 UTC, VRehnberg commented
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
alvis-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/VRehnberg/54edf8c95f421f24c675e8818e08625d for a full test report.

2024-05-06 11:26 UTC, laraPPr commented
Test report by @laraPPr
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node4006.donphan.os - Linux RHEL 8.8 (Ootpa), x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.11.3
See https://gist.github.com/laraPPr/ca55ad2b3e7b05a7cb1b56a394210ce4 for a full test report.

2024-05-07 06:32 UTC, boegel approved these changes
lgtm

2024-05-07 06:32 UTC, boegel commented
@boegelbot please test @ generoso

2024-05-07 06:39 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3101.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/ce75681eb067783c74461ced9fe74085 for a full test report.

2024-05-07 07:37 UTC, laraPPr commented
@boegelbot please test @ jsc-zen3

2024-05-07 09:04 UTC, boegel commented
Going in, thanks @VRehnberg!

2024-05-07 09:04 UTC, merged