{lib}[foss/2023a] SimNIBS v4.0.1, charm-gems v1.3.3, FMM3D v1.0.4, ...
easybuilders/easybuild-easyconfigs pull request #20327
Opened 2024-04-10 10:35 UTC by pavelToman

(created using `eb --new-pr`)

2024-04-10 14:25 UTC, pavelToman commented
SimNIBS needs other version of tbb, CGAL, Boost then version already in EB for 2023a (12.3.0).

2024-04-10 17:02 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-04-10 18:52 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-04-11 09:42 UTC, verdurin commented
> SimNIBS needs other version of tbb, CGAL, Boost then version already in EB for 2023a (12.3.0).

If this specific versions are required, then you'll need to add exceptions to the unit tests in this PR.

2024-04-19 10:10 UTC, boegel commented
We'll have to add an exception to the easyconfigs test suite for Boost/CGAL/tbb, unless we can make them build-only dependencies (see for example https://github.com/easybuilders/easybuild-easyconfigs/pull/18843)

2024-04-19 10:10 UTC, boegel requested changes

2024-04-19 10:10 UTC, boegel commented on easybuild/easyconfigs/s/SimNIBS/SimNIBS-4.0.1-foss-2023a.eb
> +    ('Eigen', '3.3.7', '', SYSTEM),
This could be probably be:

```
('Eigen', '3.4.0'),
```

and Eigen should always be a build dependency, because it's a header-only library

2024-04-19 10:15 UTC, branfosj commented
> We'll have to add an exception to the easyconfigs test suite for Boost/CGAL/tbb, unless we can make them build-only dependencies (see for example #18843)

CGAL (>=5) is header only?

2024-04-19 15:21 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-05-03 09:26 UTC, boegel requested changes

2024-05-03 09:26 UTC, boegel commented on easybuild/easyconfigs/s/SimNIBS/SimNIBS-4.0.1-foss-2023a.eb
> +    ('tbb', '2020.1'),
```suggestion
    # SimNIBS 4.0.1 requires old versions of Boost, CGAL, tbb
    ('Boost', '1.74.0'),
    ('CGAL', '5.4'),
    ('tbb', '2020.1'),

2024-05-03 11:19 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3147.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/2fefa3109cacf7e28551d3985a9ac945 for a full test report.

2024-05-04 14:23 UTC, boegel approved these changes

2024-05-05 08:50 UTC, boegel commented
Going in, thanks @pavelToman!

2024-05-05 08:50 UTC, merged