{phys}[GCCcore/12.3.0] PyAEDT v0.8.7
easybuilders/easybuild-easyconfigs pull request #20357
Opened 2024-04-12 21:31 UTC by appolloford

(created using `eb --new-pr`)

2024-04-12 21:35 UTC, appolloford commented
Test report by @appolloford
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/appolloford/b0107145976ed54f2d50986f534c7b29 for a full test report.

2024-04-13 08:35 UTC, jfgrimm commented
> AssertionError: Should not have multiple variants of dependencies.
Found 2 variants of 'dotNET-Core' dependency in easyconfigs using 'GCCcore-12.3' toolchain generation
* version: 8.0.203; versionsuffix:  as dep for {'PyAEDT-0.8.7-GCCcore-12.3.0.eb'}
  * version: 8.0; versionsuffix:  as dep for {'PyAEDT-0.8.7-GCCcore-12.3.0.eb'}

2024-04-18 16:57 UTC, Micket commented
I asked @appolloford to also update these tests to cover the net dotNET-Core, which should be treated identically to the Java wrappers (since they are).

2024-04-18 17:03 UTC, jfgrimm commented
@boegelbot please test @ generoso

2024-04-18 17:04 UTC, jfgrimm requested changes

2024-04-18 17:04 UTC, jfgrimm commented on easybuild/easyconfigs/p/PyAEDT/PyAEDT-0.8.7-GCCcore-12.3.0.eb
> +    ('hatchling', '1.18.0'),
This should be a build dependency

2024-04-18 17:49 UTC, appolloford commented on easybuild/easyconfigs/p/PyAEDT/PyAEDT-0.8.7-GCCcore-12.3.0.eb
> +    ('hatchling', '1.18.0'),
Thanks! Fixed!

2024-04-22 08:41 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/c04b7bd46947d66e86508480b9b5ec35 for a full test report.

2024-04-24 11:36 UTC, Micket approved these changes
lgtm

2024-04-24 11:36 UTC, merged