{lib,tools,vis}[foss/2023a] imgaug v0.4.1, OpenCV v4.8.1, pdf2docx v0.5.8 w/ CUDA 12.1.1, CUDA 12.1.1 contrib
easybuilders/easybuild-easyconfigs pull request #20350
Opened 2024-04-12 11:55 UTC by WilleBell

(created using `eb --new-pr`)

2024-04-16 02:53 UTC, migueldiascosta commented
@boegelbot please test @ jsc-zen3

2024-04-16 08:14 UTC, jfgrimm requested changes

2024-04-24 16:24 UTC, lexming requested changes

2024-04-24 16:24 UTC, lexming commented on easybuild/easyconfigs/p/pdf2docx/pdf2docx-0.5.8-foss-2023a-CUDA-12.1.1.eb
> +name = 'pdf2docx'
as discussed, this easyconfig can be removed. Superseded by #20416

2024-05-07 08:17 UTC, lexming commented
@boegelbot please test @ jsc-zen3

2024-05-07 10:52 UTC, lexming approved these changes
LGTM

2024-05-07 10:52 UTC, lexming commented
Merging, thanks @WilleBell !

2024-05-07 10:53 UTC, merged