{tools}[foss/2023a] Ray-project v2.9.1
easybuilders/easybuild-easyconfigs pull request #20373
Opened 2024-04-16 14:28 UTC by WilleBell

(created using `eb --new-pr`)

2024-04-19 02:44 UTC, migueldiascosta requested changes

2024-04-19 02:44 UTC, migueldiascosta commented on easybuild/easyconfigs/r/Ray-project/Ray-project-2.9.1-foss-2023a.eb
> +    ('hatchling', '1.18.0'),
please move to builddependencies

2024-04-19 02:44 UTC, migueldiascosta commented on easybuild/easyconfigs/r/Ray-project/Ray-project-2.9.1-foss-2023a.eb
> +        'source_tmpl': '%(namelower)s-%(version)s-cp311-cp311-manylinux2014_x86_64.whl',
can you add the wheel for `aarch64`, using the `%(arch)s` template?

2024-04-19 23:35 UTC, migueldiascosta requested changes

2024-04-19 23:35 UTC, migueldiascosta commented on easybuild/easyconfigs/r/Ray-project/Ray-project-2.9.1-foss-2023a.eb
> +        'checksums': ['fabc520990c1b98dde592813d62737e5e817460e0ac359f32ba029ace292cbe2'],
```suggestion
        'checksums': [{
            '%(namelower)s-%(version)s-cp311-cp311-manylinux2014_x86_64.whl': (
                'fabc520990c1b98dde592813d62737e5e817460e0ac359f32ba029ace292cbe2'
            ),
            '%(namelower)s-%(version)s-cp311-cp311-manylinux2014_aarch64.whl': (
                '1907649d69efdc1b9ffbc03db086f6d768216cb73908ebd4038ac5030effef9e'
            ),
        }],
```

2024-04-30 05:50 UTC, migueldiascosta commented
@WilleBell I guess the reason for this to be in `foss` instead of `gfbf` is that it can use MPI, but for that doesn't `mpi4py` (https://github.com/search?q=repo%3Aray-project%2Fray%20mpi4py&type=code) need to be included as a dependency? (it's a separate easyconfig now, mpi4py-3.1.4-gompi-2023a.eb)

2024-07-05 14:06 UTC, WilleBell commented
> @WilleBell I guess the reason for this to be in `foss` instead of `gfbf` is that it can use MPI, but for that doesn't `mpi4py` (https://github.com/search?q=repo%3Aray-project%2Fray%20mpi4py&type=code) need to be included as a dependency? (it's a separate easyconfig now, mpi4py-3.1.4-gompi-2023a.eb)

Yes, indeed! I added the dependency. Thank you @migueldiascosta

2024-07-07 08:40 UTC, migueldiascosta commented
@boegelbot please test @ generoso

2024-07-07 09:12 UTC, migueldiascosta commented
@boegelbot please test @ jsc-zen3

2024-07-07 09:50 UTC, migueldiascosta commented
Test report by @migueldiascosta
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
gracehopper - Linux Rocky Linux 9.3, AArch64, ARM UNKNOWN (neoverse_v2), 1 x NVIDIA NVIDIA GH200 480GB, 550.54.15, Python 3.9.18
See https://gist.github.com/migueldiascosta/6ea7aab71e119e43a96b2b260904f3d3 for a full test report.

2024-07-07 10:02 UTC, migueldiascosta approved these changes
lgtm

2024-07-07 10:03 UTC, migueldiascosta commented
Going in, thanks @WilleBell!

2024-07-07 10:03 UTC, merged