{bio}[foss/2022b] CheckM2 v1.0.2
easybuilders/easybuild-easyconfigs pull request #20399
Opened 2024-04-19 12:13 UTC by pavelToman

(created using `eb --new-pr`)

2024-04-19 12:20 UTC, pavelToman commented
TODO: these 2 commands needs to be add to easyconfig?
- `checkm2 database --download --path $EBROOTCHECKM2`
- `export CHECKM2DB="$EBROOTCHECKM2/CheckM2_database/uniref100.KO.1.dmnd"`

2024-04-19 12:21 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-04-19 12:53 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-04-24 12:57 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-04-24 14:13 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-04-25 07:01 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-05-07 14:42 UTC, boegel requested changes

2024-05-07 14:42 UTC, boegel commented on easybuild/easyconfigs/c/CheckM2/CheckM2-1.0.2-foss-2022b.eb
> +    "%(installdir)s/lib/python%(pyshortver)s/site-packages/checkm2/defaultValues.py",
make this a raw string: `r"..."`

2024-05-07 14:47 UTC, boegel commented on easybuild/easyconfigs/c/CheckM2/CheckM2-1.0.2-foss-2022b.eb
> +    "%(installdir)s/lib/python%(pyshortver)s/site-packages/checkm2/defaultValues.py",
Maybe better (so you can avoid `unix2dos`):

```
"cd %(installdir)s/lib/python%(pyshortver)s/site-packages/checkm2 && "
r"sed -i 's/\(DB_LOCATION_DEFINITION\) = .*/\1 = os.environ.get(\"CHECKM2DB\", \"Not Set\")' defaultValues.py"

2024-05-09 10:34 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-05-09 11:10 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-05-30 20:37 UTC, boegel commented
@boegelbot please test @ generoso

2024-05-30 20:47 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3155.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/04cd83854307fb03e1be965f277cd8d2 for a full test report.

2024-06-04 17:07 UTC, boegel approved these changes
lgtm

2024-06-04 17:08 UTC, boegel commented
Going in, thanks @pavelToman!

2024-06-04 17:08 UTC, merged