{devel,chem}[foss/2023a] MetalWalls + f90wrap depedency
easybuilders/easybuild-easyconfigs pull request #20403
Opened 2024-04-19 15:30 UTC by Crivella

Depends on easyblock from https://github.com/easybuilders/easybuild-easyblocks/pull/3311

Adds the following EC files:

- MetalWalls (https://gitlab.com/ampere2/metalwalls)
- f90wrap (with a patch not yet included in the main distribution) as a dependency to build the python interface of MetalWalls

2024-05-10 13:07 UTC, ocaisa commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3311"

2024-05-10 13:10 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3311"

2024-05-10 14:35 UTC, ocaisa commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3311"

2024-05-10 14:40 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3311"

2024-05-15 12:43 UTC, ocaisa requested changes

2024-05-15 13:11 UTC, Crivella commented on easybuild/easyconfigs/f/f90wrap/f90wrap-0.2.13-foss-2023a.eb
> +version = '0.2.13'
Just tested, 0.2.14 does compile without the patch, but MetalWalls fails to compile with many errors such as reported below.

Should Iadd a dependency check for f90wraps <= 0.2.13 in the EB for MetalWalls?

```
   87 | subroutine f90wrap_mw_configuration_line__mw_configuration_line_t_initialise(this)
      |                                                                            1
Error: Name at (1) is too long
f90wrap_configuration_line.f90:98:3:

   98 | end subroutine f90wrap_mw_configuration_line__mw_configuration_line_t_initialise
      |   1
Error: Expecting END PROGRAM statement at (1)
f90wrap_configuration_line.f90:101:60:

  101 |     use mw_configuration_line, only: mw_configuration_line_t
      |                                                            1
Error: Unexpected USE statement at (1)
f90wrap_configuration_line.f90:102:17:

  102 |     implicit none
      |                 1
Error: Duplicate IMPLICIT NONE statement at (1)
f90wrap_configuration_line.f90:104:41:

  104 |     type mw_configuration_line_t_ptr_type
      |                                         1
Error: Derived type definition of mw_configuration_line_t_ptr_type at (1) has already been defined
f90wrap_configuration_line.f90:105:61:

  105 |         type(mw_configuration_line_t), pointer :: p => NULL()
      |                                                             1
Error: Unexpected data declaration statement at (1)
f90wrap_configuration_line.f90:106:7:

  106 |     end type mw_configuration_line_t_ptr_type
      |       1
Error: Expecting END PROGRAM statement at (1)
f90wrap_configuration_line.f90:107:54:
...
```

2024-05-15 13:46 UTC, ocaisa commented on easybuild/easyconfigs/f/f90wrap/f90wrap-0.2.13-foss-2023a.eb
> +version = '0.2.13'
Ok, let's kick the can down the road on this. I don't know when Metalwalls will be getting an update but they will have to deal with this

2024-05-15 13:47 UTC, ocaisa approved these changes

2024-05-15 13:48 UTC, ocaisa requested changes
CI is failing

2024-05-15 13:48 UTC, ocaisa commented on easybuild/easyconfigs/f/f90wrap/f90wrap-0.2.13_fix_old_typing.patch
> +--- f90wrap/arraydatamodule.c.orig	2024-04-19 14:22:57.488265190 +0200
Patch should have a description above this line

2024-05-15 13:52 UTC, ocaisa submitted a review, later dismissed

2024-05-15 13:55 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3311"

2024-05-15 14:01 UTC, ocaisa commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3311"

2024-05-15 15:27 UTC, merged