{lib}[GCCcore/13.2.0] UCX v1.16.0
easybuilders/easybuild-easyconfigs pull request #20431
Opened 2024-04-28 07:29 UTC by bedroge

(created using `eb --new-pr`)

2024-04-28 07:32 UTC, bedroge commented
Test report by @bedroge
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
starfive - Linux Debian GNU/Linux n/a, RISC-V-64, UNKNOWN, Python 3.10.9
See https://gist.github.com/bedroge/152820b64494730ad10a6a48d2cc75b3 for a full test report.

2024-04-28 07:47 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
starfive - Linux Debian GNU/Linux n/a, RISC-V-64, UNKNOWN, Python 3.10.9
See https://gist.github.com/bedroge/55a31a7060e0acca800f3ab016fa6920 for a full test report.

2024-04-28 08:02 UTC, bedroge commented
@boegelbot please test @ generoso

2024-04-28 08:19 UTC, bedroge commented
@boegelbot please test @ jsc-zen3

2024-04-28 18:48 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
arriesgado-2 - Linux Ubuntu 22.04, RISC-V-64, UNKNOWN (u74mc), Python 3.10.12
See https://gist.github.com/SebastianAchilles/4d70aa4fda7b410d06e62499855724a4 for a full test report.

2024-05-03 15:26 UTC, boegel requested changes

2024-05-03 15:26 UTC, boegel commented on easybuild/easyconfigs/u/UCX/UCX-1.16.0-GCCcore-13.2.0.eb
> +# sources = ['%(namelower)s-%(version)s.tar.gz']
```suggestion
```

2024-05-03 15:27 UTC, boegel approved these changes

2024-05-03 16:54 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3147.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/53d8133f4b3e50a2ae5e80acff952465 for a full test report.

2024-05-03 16:56 UTC, boegel commented
Going in, thanks @bedroge!

2024-05-03 16:56 UTC, merged