{lang,tools}[foss/2023a] RabbitMQ 3.13.1 with dependencies
easybuilders/easybuild-easyconfigs pull request #20441
Opened 2024-04-30 13:49 UTC by Crivella

This PR includes EC files for RabbitMQ and its dependencies

- RabbitMQ-3.13.1-GCC-12.3.0.eb

Deps:

- ErlangOTP-26.2.4-GCC-12.3.0.eb
- Elixir-1.16.2-GCC-12.3.0.eb
- xmlto-0.0.28-GCC-12.3.0.eb

2025-06-16 08:47 UTC, Crivella commented
Test report by @Crivella
**SUCCESS**
Build succeeded for 0 out of 0 (4 easyconfigs in total)
crivella-desktop - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 13th Gen Intel(R) Core(TM) i9-13900K (skylake), Python 3.11.13
See https://gist.github.com/Crivella/fb092a7ef7f4d6bbdbe570e22f45e707 for a full test report.

2025-06-16 08:53 UTC, Crivella commented
Test report by @Crivella
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
crivella-desktop - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 13th Gen Intel(R) Core(TM) i9-13900K (skylake), Python 3.11.13
See https://gist.github.com/Crivella/8d6a85a2359cdce5e62ebb1890ef62fc for a full test report.

2025-06-16 09:11 UTC, Crivella commented
@boegelbot please test @ jsc-zen3

2025-06-16 09:38 UTC, Crivella commented
@boegelbot please test @ jsc-zen3

2025-07-09 13:47 UTC, ocaisa requested changes

2025-07-09 13:47 UTC, ocaisa commented on easybuild/easyconfigs/r/RabbitMQ/RabbitMQ-3.13.1-GCCcore-12.3.0.eb
> +test_cmd = "make tests"
```suggestion
runtest = "tests"
```

2025-07-09 13:47 UTC, ocaisa commented on easybuild/easyconfigs/r/RabbitMQ/RabbitMQ-3.13.1-GCCcore-12.3.0.eb
> +max_parallel = 1
I'd move this all the way up above `configure_without_installdir` if it is really needed

2025-07-09 13:47 UTC, ocaisa commented on easybuild/easyconfigs/x/xmlto/xmlto-0.0.28-GCCcore-12.3.0.eb
> +test_cmd = "make check"
```suggestion
runtest = "check"
```

2025-07-09 13:55 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3

2025-07-09 14:13 UTC, ocaisa commented
Test report by @ocaisa
**FAILED**
Build succeeded for 3 out of 4 (4 easyconfigs in total)
LAPTOP-O6HF2IKC - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.11.4
See https://gist.github.com/ocaisa/6a87163ad877d57faefc01205aadb46a for a full test report.

2025-07-10 08:31 UTC, Crivella commented
Test report by @Crivella
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
crivella-desktop - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 13th Gen Intel(R) Core(TM) i9-13900K (skylake), Python 3.11.13
See https://gist.github.com/Crivella/01cce75446145e35e3cb30186b3b5fa2 for a full test report.

2025-07-10 08:44 UTC, Crivella commented
@boegelbot please test @ jsc-zen3

2025-07-10 08:46 UTC, Crivella commented
## Notes on https://github.com/easybuilders/easybuild-easyconfigs/pull/20441/commits/b72ec2d1b7f7f4d45091caee6de0cd9a64017a06

- Added dependencies for optional `Erlang` functionalities
  - Java
  - unixODBC
  - OpenSSL  **required to compile RabbitMQ** and to avoid linking to system one

2025-07-10 08:53 UTC, Crivella commented
Test report by @Crivella
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
crivella-desktop - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 13th Gen Intel(R) Core(TM) i9-13900K (skylake), Python 3.11.13
See https://gist.github.com/Crivella/2f427d34a5a2086d0db4dca3f9fdc93a for a full test report.

2025-07-10 08:58 UTC, Crivella commented on easybuild/easyconfigs/r/RabbitMQ/RabbitMQ-3.13.1-GCCcore-12.3.0.eb
> +max_parallel = 1
Done in [12fe6ff](https://github.com/easybuilders/easybuild-easyconfigs/pull/20441/commits/12fe6ff03e2d7abe4fddf83b9dd0777fefe440ea)

2025-07-10 10:23 UTC, ocaisa commented
Test report by @ocaisa
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
LAPTOP-O6HF2IKC - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.11.4
See https://gist.github.com/ocaisa/79095dd4f169c71eb0baed7a57728cff for a full test report.

2025-07-10 10:26 UTC, merged