{lib}[GCC/12.3.0] ngtcp2 v1.5.0, nghttp3 v1.3.0, nghttp2 v1.62.0, ...
easybuilders/easybuild-easyconfigs pull request #20556
Opened 2024-05-17 15:40 UTC by sassy-crick

(created using `eb --new-pr`)

2024-06-07 09:03 UTC, sassy-crick commented
As the failed checks are GitHub tag releases, right now we cannot use checksums here unless I am mistaken

2025-04-24 10:33 UTC, sassy-crick commented
Test report by @sassy-crick
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
hp - Linux Debian GNU/Linux 12, x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.11.2
See https://gist.github.com/sassy-crick/ca4d9c47f5f5c1cc8e343f464e98fa76 for a full test report.

2025-04-24 12:03 UTC, sassy-crick commented
Test report by @sassy-crick
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
hp - Linux Debian GNU/Linux 12, x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.11.2
See https://gist.github.com/sassy-crick/a48008f991b0901644b47d3b022d8fb9 for a full test report.

2025-04-24 12:19 UTC, sassy-crick commented
@boegelbot please test @ jsc-zen3

2025-06-16 09:23 UTC, akesandgren commented
@sassy-crick drop jemalloc from this one. We already have it merged

2025-06-24 14:51 UTC, sassy-crick commented
@boegelbot please test @ jsc-zen3

2025-06-24 15:37 UTC, akesandgren requested changes

2025-06-24 15:37 UTC, akesandgren commented on easybuild/easyconfigs/n/nghttp2/nghttp2-1.62.0-GCC-12.3.0.eb
> +}]
I think this should just be
```
github_account = 'nghttp2'
source_urls = [GITHUB_RELEASE]
sources = [SOURCE_TAR_XZ]
```

2025-06-24 15:37 UTC, akesandgren commented on easybuild/easyconfigs/n/ngtcp2/ngtcp2-1.5.0-GCC-12.3.0.eb
> +}]
And the same here

2025-06-24 15:52 UTC, sassy-crick commented on easybuild/easyconfigs/n/nghttp2/nghttp2-1.62.0-GCC-12.3.0.eb
> +}]
Are you sure I am then downloading the same version and to it recursive? I have removed that already existing tarball, and done:
```
eb --fetch nghttp2-1.62.0-GCC-12.3.0.eb

== fetching files and verifying checksums...
  >> download succeeded: https://github.com/nghttp2/nghttp2/releases/download/v1.62.0/nghttp2-1.62.0.tar.xz
  >> sources:
  >> /opt/sources/n/nghttp2/nghttp2-1.62.0.tar.xz [SHA256: 26798308fa0a12dabdb7ba8c77f74383019d3a0f1f36d25958b836af22474958]
== ... (took 1 secs)
== FAILED: Installation ended unsuccessfully: Checksum verification for /opt/sources/n/nghttp2/nghttp2-1.62.0.tar.xz using ac9d1fee8759a2c37c1ae2bbef6afa2f5c11fd367ed8e3f51a02142d259ee2bb 
failed. (took 1 secs)
```
Clearly differently. Could it be that the `recursive` is missing?

2025-06-24 15:55 UTC, akesandgren commented on easybuild/easyconfigs/n/nghttp2/nghttp2-1.62.0-GCC-12.3.0.eb
> +}]
Checksum will of course differ, but the content should be the correct and same one as the recursively made one.
That is the actual released source after all.

2025-06-24 16:06 UTC, sassy-crick commented on easybuild/easyconfigs/n/nghttp2/nghttp2-1.62.0-GCC-12.3.0.eb
> +}]
Some file which I found in the previous way of downloading it where actually missing. However, I have changed that for both suggestions.

2025-06-24 16:44 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/70750d737c58b169f18718ebb4461ac3 for a full test report.

2025-06-24 17:36 UTC, akesandgren commented
Going in, thanks @sassy-crick!

2025-06-24 17:36 UTC, merged