{lib}[GCCcore/13.3.0] hwloc v2.10.0, UCX v1.16.0, UCC v1.3.0
easybuilders/easybuild-easyconfigs pull request #20581
Opened 2024-05-22 07:49 UTC by SebastianAchilles

(created using `eb --new-pr`)
Depends on: https://github.com/easybuilders/easybuild-easyconfigs/pull/20580

2024-05-22 10:23 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
jscclxc1.int.jsc-clx.fz-juelich.de - Linux Rocky Linux 9.4, x86_64, Intel Xeon Processor (Cascadelake) (cascadelake), Python 3.9.18
See https://gist.github.com/SebastianAchilles/38c58ac501c076b725abc4a788b3e4f7 for a full test report.

2024-05-22 19:48 UTC, SebastianAchilles commented
@boegelbot please test @ generoso

2024-05-22 19:59 UTC, SebastianAchilles commented
@boegelbot please test @ jsc-zen3

2024-05-22 22:42 UTC, boegel commented
@boegelbot please test @ generoso

2024-05-22 22:47 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
aarch64-neoverse-n1-node1.int.aws-rocky88-202310.eessi.io - Linux Rocky Linux 8.9, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/4dcfca69aff429cf7031380b6a2cd9fe for a full test report.

2024-05-22 22:51 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-05-23 06:07 UTC, boegel requested changes

2024-05-23 06:07 UTC, boegel commented on easybuild/easyconfigs/u/UCX/UCX-1.16.0-GCCcore-13.3.0.eb
> +configure_cmd = "contrib/configure-release"
@SebastianAchilles Please change this to use the standard configure script, see #20428

2024-05-23 06:08 UTC, boegel requested changes

2024-05-23 06:08 UTC, boegel commented on easybuild/easyconfigs/u/UCX/UCX-1.16.0-GCCcore-13.3.0.eb
> +configopts += '--without-java --without-go --disable-doxygen-doc '
```suggestion
configopts = '--enable-optimizations --enable-cma --enable-mt --with-verbs '
configopts += '--without-java --without-go --disable-doxygen-doc '
# include the configure options from contrib/configure-release
configopts += '--disable-logging --disable-debug --disable-assertions --disable-params-check '
```

2024-05-23 08:09 UTC, SebastianAchilles commented
@boegelbot please test @ jsc-zen3

2024-05-23 08:21 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.9, x86_64, AMD EPYC-Milan Processor (zen2), Python 3.6.8
See https://gist.github.com/bedroge/194ed16c110da21d8dbd5b8c10084cf5 for a full test report.

2024-05-23 08:21 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 22.04, x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.10.12
See https://gist.github.com/bedroge/63c2ef35fd7783e1366628a917275387 for a full test report.

2024-05-23 09:48 UTC, boegel requested changes

2024-05-23 09:48 UTC, boegel commented on easybuild/easyconfigs/u/UCX/UCX-1.16.0-GCCcore-13.3.0.eb
> +builddependencies = [
```suggestion
```

2024-05-23 09:49 UTC, boegel requested changes

2024-05-23 09:49 UTC, boegel commented on easybuild/easyconfigs/u/UCX/UCX-1.16.0-GCCcore-13.3.0.eb
> +# sources = ['%(namelower)s-%(version)s.tar.gz']
```suggestion
```

2024-05-23 09:50 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
jrc0870.jureca - Linux Rocky Linux 8.9, AArch64, ARM UNKNOWN (neoverse_n1), 2 x NVIDIA NVIDIA A100-PCIE-40GB, 535.154.05, Python 3.6.8
See https://gist.github.com/SebastianAchilles/9cb312dae2370195e9cfba07cb94d371 for a full test report.

2024-05-23 09:54 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
aarch64-neoverse-n1-node1.int.aws-rocky88-202310.eessi.io - Linux Rocky Linux 8.9, AArch64, ARM UNKNOWN (neoverse_n1), Python 3.6.8
See https://gist.github.com/boegel/4b000b72cb071e449ed710105be81649 for a full test report.

2024-05-23 10:06 UTC, boegel approved these changes

2024-05-23 11:10 UTC, bedroge commented
Test report by @bedroge
**FAILED**
Build succeeded for 15 out of 21 (3 easyconfigs in total)
starfive - Linux Debian GNU/Linux n/a, RISC-V-64, UNKNOWN, Python 3.10.9
See https://gist.github.com/bedroge/2b4b7c0297c06d94aa7ab4819912c65a for a full test report.

2024-05-23 11:53 UTC, boegel commented
@bedroge I won't let that problem with `OpenSSL/3` on RISC-V block this PR, please open a dedicated issue to follow up on that one...

2024-05-23 11:54 UTC, boegel commented
Going in, thanks @SebastianAchilles!

2024-05-23 11:54 UTC, merged

2024-05-23 12:07 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
starfive - Linux Debian GNU/Linux n/a, RISC-V-64, UNKNOWN, Python 3.10.9
See https://gist.github.com/bedroge/3218f46c1e754c2af4eba35c73df95b9 for a full test report.

2024-05-24 11:55 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0207u28a.bear.cluster - Linux RHEL 8.6, x86_64, AMD EPYC 9554 64-Core Processor (zen4), Python 3.6.8
See https://gist.github.com/branfosj/34917332362444b37ae9025f65ed0a82 for a full test report.

2024-05-24 11:55 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/branfosj/5555da7417889096820d8633c6e8aeda for a full test report.

2024-05-24 11:56 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0105u03a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/54705d394f20da8b850077bf2e72745f for a full test report.

2024-05-24 11:56 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0207u20a - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8480CL (sapphirerapids), Python 3.6.8
See https://gist.github.com/branfosj/675fea117a41b908a2669d2f7fc76732 for a full test report.