{lib}[GCCcore/12.3.0] makefun 1.15.2
easybuilders/easybuild-easyconfigs pull request #20619
Opened 2024-05-23 16:38 UTC by ThomasHoffmann77

(created using `eb --new-pr`)

2024-06-05 15:32 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/a9f2be19dd8ae8a6f2536725770b90d9 for a full test report.

2024-06-05 15:33 UTC, verdurin commented
@boegelbot please test @ generoso

2024-06-08 07:19 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3117.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/f5be2aeb94ba129eb220bd8577bff00b for a full test report.

2024-06-08 07:19 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-06-08 07:21 UTC, boegel requested changes

2024-06-08 07:21 UTC, boegel commented on easybuild/easyconfigs/m/makefun/makefun-1.15.2-GCCcore-12.3.0.eb
> +}
```suggestion
```

2024-06-08 07:22 UTC, boegel approved these changes
lgtm

2024-06-08 07:23 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3117.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/800e8f5e6051cdee0c1aae47766a4b0f for a full test report.

2024-06-08 07:39 UTC, boegel commented
Going in, thanks @ThomasHoffmann77!

2024-06-08 07:39 UTC, merged