{vis}[foss/2023a] micro-sam v1.0.1, torch_em v0.7.1, affogato v0.3.3, ...
easybuilders/easybuild-easyconfigs pull request #20636
Opened 2024-05-24 13:26 UTC by pavelToman

(created using `eb --new-pr`)

2024-05-24 13:26 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-06-06 09:21 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-06-14 09:09 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-06-17 08:09 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-06-18 20:23 UTC, boegel requested changes

2024-06-18 20:24 UTC, boegel commented on easybuild/easyconfigs/t/torch_em/torch_em-0.7.1-foss-2023a.eb
> +name = 'torch_em'
fixed in a100374

2024-06-18 20:24 UTC, boegel commented on easybuild/easyconfigs/n/nifty/nifty-1.2.1-foss-2023a.eb
> +preinstallopts = 'export PYTHON_MODULE_INSTALL_DIR="%(builddir)s/easybuild_obj/python/" '
fixed in a100374

2024-06-18 20:24 UTC, boegel commented on easybuild/easyconfigs/z/z5py/z5py-2.0.17-foss-2023a.eb
> +preinstallopts = 'export PYTHON_MODULE_INSTALL_DIR="%(builddir)s/easybuild_obj/python/" '
fixed in d58a1fc

2024-06-18 20:24 UTC, boegel commented on easybuild/easyconfigs/t/torch_em/torch_em-0.7.1-foss-2023a.eb
> +local_preinstallopts_termcolor = ' '.join([
fixed in d58a1fc

2024-06-18 20:51 UTC, boegel commented
@boegelbot please test @ generoso

2024-06-18 21:02 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-06-19 06:27 UTC, boegel approved these changes

2024-06-19 07:06 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 12 out of 12 (12 easyconfigs in total)
node3107.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/61ff9c6881baf2f48224d152e4823166 for a full test report.

2024-06-19 09:57 UTC, boegel commented
Going in, thanks @pavelToman!

2024-06-19 09:57 UTC, merged