{ai}[foss/2023a] Safetensors v0.4.3 w/ CUDA 12.1.1
easybuilders/easybuild-easyconfigs pull request #20642
Opened 2024-05-25 09:46 UTC by smoors

(created using `eb --new-pr`)

2024-05-25 09:59 UTC, smoors commented
Test report by @smoors
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3341
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node403.hydra.os - Linux Rocky Linux 8.9, x86_64, AMD EPYC 7282 16-Core Processor (zen2), 1 x NVIDIA NVIDIA A100-PCIE-40GB, 550.54.15, Python 3.6.8
See https://gist.github.com/smoors/5dfeb563cf9ea3e255253b58f859fc3d for a full test report.

2024-05-25 10:06 UTC, smoors commented
@boegelbot: please test @ generoso EB_ARGS="--include-easyblocks-from-pr 3341"

2024-05-27 09:06 UTC, smoors commented
@boegelbot please test @ jsc-zen3

2024-06-07 10:17 UTC, Micket requested changes

2024-06-07 10:17 UTC, Micket commented on easybuild/easyconfigs/s/Safetensors/Safetensors-0.4.3-foss-2023a-CUDA-12.1.1.eb
> +    # ('TensorFlow', 'xxx', versionsuffix),  # optional, add 'tensorflow' to 'use_pip_extras'
```suggestion
```

I think these can be opt-in at runtime, which would safe us from having to make multiple versions of this (and considering the combinatorics of 3 optional things, with cuda and non-cuda, would be insane, n=2x2x2x2=ugh) 

I skimmed the source code, and it's just different plain python code wrappers for save_file and such in safetensors, and I think they are all installed unconditionally and can be combined with any (compatible) torch/numpy/tensorflow/paddle/etc.etc.

(I could be wrong, didn't test this theory yet)

2024-06-07 10:18 UTC, Micket commented on easybuild/easyconfigs/s/Safetensors/Safetensors-0.4.3-foss-2023a-CUDA-12.1.1.eb
> +toolchain = {'name': 'foss', 'version': '2023a'}
would also drop this to gfbf when keeping only SciPy-bundle dep, and drop the CUDA and suffix of course

2024-06-07 18:15 UTC, Micket commented on easybuild/easyconfigs/s/Safetensors/Safetensors-0.4.3-foss-2023a-CUDA-12.1.1.eb
> +        'use_pip_extras': 'numpy,torch',
In my testing, this also changes nothing in the installation, even just putting gibberish here, I end up with the exact same installation.

2024-06-17 19:12 UTC, smoors commented
@boegelbot: please test @ generoso

2024-06-17 19:18 UTC, smoors commented
@boegelbot please test @ jsc-zen3

2024-06-17 21:50 UTC, Micket commented
Test report by @Micket
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/e206349d9f7b8574bde208b660d29447 for a full test report.

2024-06-17 22:09 UTC, Micket approved these changes
lgtm

2024-06-17 22:10 UTC, Micket commented
Going in, thanks @smoors!

2024-06-17 22:10 UTC, merged