{bio}[foss/2022b] TF-COMB v1.1, TOBIAS v0.16.1, svist4get v1.3.1, ...
easybuilders/easybuild-easyconfigs pull request #20665
Opened 2024-05-27 18:42 UTC by pavelToman

(created using `eb --new-pr`)

2024-05-27 18:42 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-05-28 11:37 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-05-30 19:42 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node3155.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/32ea94cf283c37892415d10acfa6aa18 for a full test report.

2024-05-30 20:02 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-05-30 21:09 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node3155.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/e96a8c3f511c8f699b6e0eb756b1301f for a full test report.

2024-08-28 13:50 UTC, boegel requested changes

2024-08-28 13:50 UTC, boegel commented on easybuild/easyconfigs/t/TF-COMB/TF-COMB-1.1-foss-2022b.eb
> +]
this part doesn't make sense for this easyconfig, probably a copy-paste error?
```suggestion
```

2024-08-28 13:51 UTC, boegel approved these changes

2024-08-29 20:13 UTC, boegel commented
Going in, thanks @pavelToman!

2024-08-29 20:13 UTC, merged