{bio}[foss/2023a] lil-aretomo v0.1.0
easybuilders/easybuild-easyconfigs pull request #20696
Opened 2024-05-31 11:05 UTC by ThomasHoffmann77

(created using `eb --new-pr`)

2024-06-04 15:07 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/c99fa72e9cb09a992760d2487def9602 for a full test report.

2024-06-04 15:08 UTC, verdurin commented
@boegelbot please test @ generoso

2024-06-04 16:55 UTC, verdurin commented
@boegelbot please test @ jsc-zen3

2024-06-05 13:40 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/17df587d76480889b5c973d0da214c61 for a full test report.

2024-06-05 13:42 UTC, verdurin commented
@boegelbot please test @ generoso

2024-06-05 15:19 UTC, verdurin commented
@boegelbot please test @ jsc-zen3

2024-06-05 15:28 UTC, verdurin requested changes

2024-06-08 07:20 UTC, boegel requested changes

2024-06-08 07:20 UTC, boegel commented on easybuild/easyconfigs/l/lil-aretomo/lil-aretomo-0.1.1-foss-2023a.eb
> +
```suggestion
```

2024-06-08 07:20 UTC, boegel commented on easybuild/easyconfigs/l/lil-aretomo/lil-aretomo-0.1.1-foss-2023a.eb
> +}
This is the default when using `PythonBundle` easyblock, so can be removed
```suggestion
```

2024-06-08 07:22 UTC, boegel approved these changes
lgtm

2024-06-08 07:22 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3117.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/c309fee6005597a8a3d423401c60aaae for a full test report.

2024-06-08 07:40 UTC, boegel commented
Going in, thanks @ThomasHoffmann77!

2024-06-08 07:40 UTC, merged