{lib}[GCCcore/12.3.0] libidn2 v2.3.2
easybuilders/easybuild-easyconfigs pull request #20739
Opened 2024-06-04 20:09 UTC by sassy-crick

(created using `eb --new-pr`)

2024-06-04 20:32 UTC, sassy-crick commented
@boegelbot please test @ generoso

2024-06-07 15:22 UTC, verdurin commented
@boegelbot please test @ jsc-zen3

2024-06-07 15:24 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-c7.novalocal - Linux CentOS Linux 7.9.2009, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/437525f3c4e85e6bd8130ec61a59e2a0 for a full test report.

2024-06-07 15:27 UTC, branfosj commented
We already have 2.3.7 (https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/l/libidn2/libidn2-2.3.7-GCCcore-12.3.0.eb). Please use that instead.

2024-06-07 15:27 UTC, verdurin requested changes

2025-04-24 13:25 UTC, sassy-crick commented
Closed in favour of already existing `libidn2-2.3.7-GCCcore-12.3.0.eb`

2025-04-24 13:25 UTC, closed without merging