make sure mummerplot can use gnuplot if available for recent MUMmer
easybuilders/easybuild-easyconfigs pull request #20749
Opened 2024-06-05 15:35 UTC by smoors

(created using `eb --new-pr`)

2024-06-07 09:19 UTC, smoors commented
@boegelbot: please test @ generoso

2024-06-07 09:36 UTC, smoors commented
@boegelbot please test @ jsc-zen3

2024-06-08 07:17 UTC, boegel requested changes
@smoors We usually implement easyconfigs such that installations are done with "batteries included", so the `gnuplot` dependency should be added here (people can always install `MUMmer` without `gnuplot` via `--filter-deps`), see https://github.com/smoors/easybuild-easyconfigs/pull/7

If the `gnuplot` dependency is added, can we then come up with a sensible sanity check command, or is that a bridge too far?

2024-06-08 16:02 UTC, boegel commented
@boegelbot please test @ generoso

2024-06-08 16:03 UTC, boegel approved these changes

2024-06-08 16:08 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-06-08 16:27 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3117.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/1ba18f9582274c6760c24b27f16a85fa for a full test report.

2024-06-08 16:28 UTC, boegel commented
Going in, thanks @smoors!

2024-06-08 16:29 UTC, merged