{data}[iimkl/2023b] xarray v2024.5.0
easybuilders/easybuild-easyconfigs pull request #20762
Opened 2024-06-07 09:23 UTC by SimonPinches

(created using `eb --new-pr`)

2024-06-07 09:24 UTC, SimonPinches commented
This PR depends upon PR #20262.

2025-06-16 13:53 UTC, sassy-crick commented
@SimonPinches You might want to sync your PR with development, something like this: 
```
eb --sync-pr-with-develop NUMBER_OF_PR
```

2025-06-17 14:01 UTC, sassy-crick commented
@SimonPinches Please remove the now surplus pip-commands in the EasyConfig file, which is why the unit-test fails. Thanks.

2025-06-17 14:03 UTC, sassy-crick commented
@SimonPinches From the bot:
```
download_dep_fail, sanity_pip_check, use_pip should not be set to True (already enabled by default in PythonPackage easyblock)
```
Please remove them so the tests are passing. Thanks!

2025-12-17 13:04 UTC, Crivella commented
@boegelbot please test @ jsc-zen3

2025-12-17 13:04 UTC, Crivella commented
Test report by @Crivella
**SUCCESS**
Build succeeded for 1 out of 1 (total: 8 secs) (1 easyconfigs in total)
crivella-desktop - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 13th Gen Intel(R) Core(TM) i9-13900K (skylake), Python 3.11.14
See https://gist.github.com/Crivella/83ae0b8826f592966a6db249885fc5ac for a full test report.

2026-04-08 09:41 UTC, akesandgren requested changes

2026-04-08 09:41 UTC, akesandgren commented on easybuild/easyconfigs/x/xarray/xarray-2024.5.0-iimkl-2023b.eb
> +    ('SciPy-bundle', '2023.12'),
The existing version is 2023.11 for 2023b please fix

2026-04-08 12:18 UTC, SimonPinches commented on easybuild/easyconfigs/x/xarray/xarray-2024.5.0-iimkl-2023b.eb
> +    ('SciPy-bundle', '2023.12'),
```suggestion
    ('SciPy-bundle', '2023.11'),
```

2026-04-08 12:18 UTC, SimonPinches commented on easybuild/easyconfigs/x/xarray/xarray-2024.5.0-iimkl-2023b.eb
> +    ('SciPy-bundle', '2023.12'),
Fixed! :-)

2026-04-08 12:40 UTC, akesandgren commented
@boegelbot Please test @ jsc-zen3

2026-04-08 12:45 UTC, akesandgren approved these changes
LGTM

2026-04-08 12:52 UTC, akesandgren commented
Going in, thanks @SimonPinches!

2026-04-08 12:52 UTC, merged