{chem}[foss/2023a] CP2K v2024.1
easybuilders/easybuild-easyconfigs pull request #20798
Opened 2024-06-11 17:18 UTC by pavelToman

(created using `eb --new-pr`)

2024-06-11 17:22 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-06-11 17:25 UTC, pavelToman commented
Can be installed only with `runtest = False`
For test running the easyblock needs to be updated:
WIP of easyblock update: 
- https://github.com/easybuilders/easybuild-easyblocks/pull/2984

2024-06-12 06:54 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-06-18 11:40 UTC, boegel requested changes

2024-06-18 11:40 UTC, boegel commented on easybuild/easyconfigs/c/CP2K/CP2K-2024.1-foss-2023a.eb
> +runtest = False
We shouldn't disable the test step like this:

```suggestion
```

2024-06-18 14:06 UTC, smoors commented
Test report by @smoors
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node603.hydra.os - Linux Rocky Linux 8.9, x86_64, AMD EPYC 9384X 32-Core Processor (zen4), Python 3.6.8
See https://gist.github.com/smoors/82a9e250d2be966cd7e10fc1df9908cf for a full test report.

2024-07-01 08:15 UTC, pavelToman commented
Tests are failing - log:
https://github.com/vscentrum/vsc-software-stack/blob/wip/297_CP2K/test_error_1.txt

2025-09-05 10:09 UTC, closed without merging