{bio}[foss/2023a] scArches v0.6.1, scib-metrics v0.5.1, scvi-tools v1.1.2, ...
easybuilders/easybuild-easyconfigs pull request #20814
Opened 2024-06-13 10:08 UTC by pavelToman

(created using `eb --new-pr`)

2024-06-13 10:09 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-06-13 10:40 UTC, j551n-ncloud commented
> (created using `eb --new-pr`)
> 
> PR for #20116

Hi my name is Johannes Nguyen i have one question im new to Easybuild and i create an recipe for BamUtil and i want to merge it how are the steps for that. A replay would be helpful bc im new to this @ johannes.nguyen@dkfz-heidelberg.de :D

2024-06-13 17:41 UTC, smoors commented
> > (created using `eb --new-pr`)
> > PR for #20116
> 
> Hi my name is Johannes Nguyen i have one question im new to Easybuild and i create an recipe for BamUtil and i want to merge it how are the steps for that. A replay would be helpful bc im new to this @ [johannes.nguyen@dkfz-heidelberg.de](mailto:johannes.nguyen@dkfz-heidelberg.de) :D

see here for documentation on how to contribute an easyconfig file:
https://docs.easybuild.io/contributing/#contributing_easyconfigs

2024-06-13 17:52 UTC, smoors commented
```
    import pyproject_metadata
ModuleNotFoundError: No module named 'pyproject_metadata'
```
missing python package

2024-06-14 09:40 UTC, pavelToman commented
> > (created using `eb --new-pr`)
> > PR for #20116
> 
> Hi my name is Johannes Nguyen i have one question im new to Easybuild and i create an recipe for BamUtil and i want to merge it how are the steps for that. A replay would be helpful bc im new to this @ [johannes.nguyen@dkfz-heidelberg.de](mailto:johannes.nguyen@dkfz-heidelberg.de) :D

I do it like that:
First you need to setup your GitHub account with EB then the `eb --check-github` should work.
Then you can do `eb --new-pr your_easyconfig.eb' and it will push it as a PR to easybuild.

2024-06-14 09:56 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-06-14 11:01 UTC, pavelToman commented
jax created from: https://github.com/easybuilders/easybuild-easyconfigs/pull/20119

2024-06-18 11:49 UTC, boegel requested changes

2024-06-18 11:49 UTC, boegel commented on easybuild/easyconfigs/s/scArches/scArches-0.6.1-foss-2023a.eb
> +    ('sphinx-theme-builder', '0.2.0b2', {
You'll need to add `pyproject-metadata` as extension here too, because `sphinx-theme-builder` requires it, see failing `pip check`

2024-06-18 13:40 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-06-19 09:51 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-06-19 11:22 UTC, boegel commented
@pavelToman 
```
  hint: A `urllib.error.HTTPError` indicates that the issue is related to the
        network or the availability of NodeJS release files. It may mean the node
        version that this tool is trying to fetch is no longer available, for
        example if there is no compatible NodeJS binary for the operating system.
  link: https://sphinx-theme-builder.rtfd.io/errors/#nodeenv-creation-failed
  error: subprocess-exited-with-error
```

Can we convince this thing to use ` nodejs` we provide as dependency instead?

2024-06-19 12:49 UTC, pavelToman commented
It seems I add either the deps that are for building docs - so I remove them, hope they are not necessary.

2024-06-19 12:49 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-06-25 21:07 UTC, boegel commented
@boegelbot please test @ generoso

2024-06-25 21:07 UTC, boegel approved these changes
lgtm

2024-06-26 00:14 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 6 out of 6 (6 easyconfigs in total)
node3104.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/78561687ce1509898e6f33b0a91040a0 for a full test report.

2024-06-26 06:48 UTC, boegel commented
Going in, thanks @pavelToman!

2024-06-26 06:48 UTC, merged