{data}[intel/2023b] h5py v3.11.0
easybuilders/easybuild-easyconfigs pull request #20839
Opened 2024-06-17 16:19 UTC by SimonPinches

(created using `eb --new-pr`)

This PR depends upon
- [x] #20262

2024-06-18 11:22 UTC, SimonPinches commented
This PR depends upon PR #20262.

2025-06-16 13:44 UTC, sassy-crick commented
@SimonPinches You might want to sync your PR with development, something like this: 
```
eb --sync-pr-with-develop NUMBER_OF_PR
```

2025-12-17 13:04 UTC, Crivella commented
@boegelbot please test @ jsc-zen3

2025-12-17 13:07 UTC, Crivella commented
Test report by @Crivella
**SUCCESS**
Build succeeded for 2 out of 2 (total: 2 mins 15 secs) (1 easyconfigs in total)
crivella-desktop - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 13th Gen Intel(R) Core(TM) i9-13900K (skylake), Python 3.11.14
See https://gist.github.com/Crivella/d4074607a147ed74a2a800889c36818d for a full test report.

2026-04-08 10:30 UTC, akesandgren requested changes

2026-04-08 10:30 UTC, akesandgren commented on easybuild/easyconfigs/h/h5py/h5py-3.11.0-intel-2023b.eb
> +    ('SciPy-bundle', '2023.12'),
Needs to be 2023.11 since that's the version for 2023b, please fix

2026-04-08 12:20 UTC, SimonPinches commented on easybuild/easyconfigs/h/h5py/h5py-3.11.0-intel-2023b.eb
> +    ('SciPy-bundle', '2023.12'),
Will change to:
```suggestion
    ('SciPy-bundle', '2023.11'),
```

2026-04-08 12:43 UTC, akesandgren commented
@boegelbot Please test @ jsc-zen3

2026-04-08 12:44 UTC, akesandgren approved these changes
LGTM

2026-04-08 12:57 UTC, akesandgren commented
Going in, thanks @SimonPinches!

2026-04-08 12:57 UTC, merged