{lib,vis}[GCCcore/13.2.0] FORD v7.0.6, graphviz-python v0.20.1
easybuilders/easybuild-easyconfigs pull request #20843
Opened 2024-06-18 10:16 UTC by SimonPinches

(created using `eb --new-pr`)

2025-06-16 13:40 UTC, sassy-crick commented
@SimonPinches You might want to sync your PR with development, something like this: 
```
eb --sync-pr-with-develop NUMBER_OF_PR
```

2025-08-18 15:43 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2025-08-18 16:09 UTC, boegel requested changes

2025-08-18 16:09 UTC, boegel commented on easybuild/easyconfigs/g/Graphviz/Graphviz-9.0.0-GCCcore-13.2.0.eb
> +    ('Java', '21', '', SYSTEM),
The `Java` version we use in this generation of easyconfigs, so we should also use that here:
```suggestion
    ('Java', '11', '', SYSTEM),
```

2025-08-18 16:37 UTC, SimonPinches commented on easybuild/easyconfigs/g/Graphviz/Graphviz-9.0.0-GCCcore-13.2.0.eb
> +    ('Java', '21', '', SYSTEM),
We have several tools built with `GCCcore/13.2.0` that need `Java/21` (and `Graphviz`).  Most notably a Bayesian inference framework.

2025-08-18 16:50 UTC, boegel commented
Actual problem with failing installation is:
```
ModuleNotFoundError: No module named 'hatchling'
```

So this looks like a victim of:
* #20546

2025-08-18 16:50 UTC, boegel requested changes

2025-08-18 16:50 UTC, boegel commented on easybuild/easyconfigs/f/FORD/FORD-7.0.6-GCCcore-13.2.0.eb
> +    ('binutils', '2.40'),
```suggestion
    ('binutils', '2.40'),
    ('hatchling', '1.18.0'),

2025-08-18 16:51 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2025-08-18 17:07 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3555.doduo.os - Linux RHEL 9.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.9.18
See https://gist.github.com/boegel/cea0e767059ca0f28df1fb6f51eb0824 for a full test report.

2025-08-18 17:23 UTC, boegel approved these changes
lgtm

2025-08-18 17:23 UTC, boegel commented
Going in, thanks @SimonPinches!

2025-08-18 17:23 UTC, merged

2025-08-18 17:30 UTC, SimonPinches commented
@boegel, I guess it's too late to ask for an exception to use `Java/21` rather than `Java/11`...?

2025-08-18 17:40 UTC, boegel commented
> @boegel, I guess it's too late to ask for an exception to use `Java/21` rather than `Java/11`...?

Sorry for making that change in-place in this PR, but making exceptions doesn't solve the core problem: that we would be introducing easyconfigs that are not compatible with other easyconfigs from the same generation.

If you want to divert from upstream w.r.t. Java version used in this generation, I think it would be better for you to introduce an EasyBuild hook locally that replaces `Java/11` with `Java/21`...

2025-08-19 08:51 UTC, SimonPinches commented
> > @boegel, I guess it's too late to ask for an exception to use `Java/21` rather than `Java/11`...?
> 
> Sorry for making that change in-place in this PR, but making exceptions doesn't solve the core problem: that we would be introducing easyconfigs that are not compatible with other easyconfigs from the same generation.
> 
> If you want to divert from upstream w.r.t. Java version used in this generation, I think it would be better for you to introduce an EasyBuild hook locally that replaces `Java/11` with `Java/21`...

Okay, I'll try to work out how to do this when I get a chance.