{bio}[foss/2023a] medaka v1.12.0
easybuilders/easybuild-easyconfigs pull request #20865
Opened 2024-06-20 09:36 UTC by PetrKralCZ

(created using `eb --new-pr`)

2024-06-20 10:06 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-06-20 10:42 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3

2024-06-25 11:43 UTC, boegel requested changes
@PetrKralCZ Please add `pyabpoa` as extra dependency, to avoid warnings like:
```
Cannot import pyabpoa, some features may not be available.
```

2024-06-27 10:18 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-06-27 10:18 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3

2024-06-27 10:39 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-07-04 09:33 UTC, boegel requested changes

2024-07-04 09:33 UTC, boegel commented on easybuild/easyconfigs/m/medaka/medaka-1.12.0-foss-2023a.eb
> +    ('h5py', '3.10.0', {
```suggestion
    # medaka 1.12.0 requires h5py ~=3.10.0
    ('h5py', '3.10.0', {
```

2024-07-04 09:39 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3158.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/dde63a63db703b73e9510afd2dbb695a for a full test report.

2024-07-04 09:52 UTC, boegel approved these changes
lgtm

2024-07-04 16:23 UTC, boegel commented
Going in, thanks @PetrKralCZ!

2024-07-04 16:23 UTC, merged