{tools}[GCC/12.3.0] ega-quickview v20240620, FUSE v3.16.2, crypt4gh v1.7
easybuilders/easybuild-easyconfigs pull request #20870
Opened 2024-06-20 13:53 UTC by pavelToman

(created using `eb --new-pr`)

2024-06-20 13:55 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-06-20 14:00 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-06-20 14:56 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-06-20 19:00 UTC, branfosj requested changes

2024-06-20 19:00 UTC, branfosj commented on easybuild/easyconfigs/c/crypt4gh/crypt4gh-1.7-GCC-12.3.0.eb
> +    }),
Both of these, in the exact same versions, are provided by `Python-bundle-PyPI-2023.06-GCCcore-12.3.0.eb`.

2024-06-20 19:00 UTC, branfosj commented on easybuild/easyconfigs/e/ega-quickview/ega-quickview-20240620-GCC-12.3.0.eb
> +    ('Autoconf', '2.71'),
```suggestion
    ('Autotools', '20220317'),
```

```
Can't exec "aclocal": No such file or directory at /project/def-maintainers/boegelbot/rocky9/zen3/software/Autoconf/2.71-GCCcore-12.3.0/share/autoconf/Autom4te/FileUtils.pm line 274.
autoreconf: error: aclocal failed with exit status: 2
```
`aclocal` is provided by `Automake` - so we should provide all of the `Autotools` here.

2024-06-21 08:36 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-06-21 18:27 UTC, branfosj approved these changes

2024-06-21 18:33 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0105u03b - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/branfosj/56cf19c843b46e502056fdc8b5d58bd5 for a full test report.

2024-06-21 18:35 UTC, branfosj commented
Going in, thanks @pavelToman!

2024-06-21 18:35 UTC, merged

2024-06-24 20:35 UTC, boegel commented on easybuild/easyconfigs/e/ega-quickview/ega-quickview-20240620-GCC-12.3.0.eb
> +name = 'ega-quickview'
I would prefer using `EGA-QuickView` as software name (see also description)

fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/20888