Compleasm 0.2.6 foss 2023b
easybuilders/easybuild-easyconfigs pull request #20873
Opened 2024-06-20 14:04 UTC by jkuhl-uni

Hey, this PR adds compleasm 0.2.6 and all necessary dependencies, as well as DendroPy 4.6.4.

2024-06-20 14:11 UTC, Micket requested changes
please see equivalent changes to compleasm as the other pr

2025-06-16 13:37 UTC, sassy-crick commented
You might want to sync your PR with development, something like this: 
```
eb --sync-pr-with-develop NUMBER_OF_PR
```@jkuhl-uni

2025-09-04 12:18 UTC, Crivella commented on easybuild/easyconfigs/c/compleasm/compleasm-0.2.6-foss-2023b.eb
> +sanity_check_paths = {
```suggestion
]

sanity_check_paths = {
```

Required for new EB

2025-09-04 12:18 UTC, Crivella commented on easybuild/easyconfigs/c/compleasm/compleasm-0.2.6-foss-2023b.eb
> +moduleclass = 'bio'
```suggestion
sanity_check_commands = ['compleasm -h']

moduleclass = 'bio'
```

Required for new EB

2025-09-04 12:21 UTC, Crivella commented on easybuild/easyconfigs/d/DendroPy/DendroPy-4.5.2-GCCcore-13.2.0.eb
> +##
On the same TC we already have a `4.6.1` and `5.0.1` version, with `5.0.1` being the default for the TC

```
found 2 variants of 'DendroPy' dependency in easyconfigs using '2023b' toolchain generation
* version: 4.5.2; versionsuffix:  as dep for {'SEPP-4.5.1-foss-2023b.eb', 'compleasm-0.2.6-foss-2023b.eb'}
* version: 5.0.1; versionsuffix:  as dep for {'QIIME2-2024.10.1-foss-2023b-amplicon.eb', 'CheckM-1.2.3-foss-2023b.eb'}
```

Can SEPP work with the newer version? Otherwise we would need to add an exception in the CI

2025-09-04 12:22 UTC, Crivella commented on easybuild/easyconfigs/d/DendroPy/DendroPy-4.6.4-GCCcore-13.2.0.eb
> +##
See comment on `4.5.2`, also this does not seems to be used elsewhere in this PR.
Is it intended to add this for `DendroPy` itself (or maybe it is a leftover EC in the PR?

2025-09-04 12:24 UTC, Crivella commented on easybuild/easyconfigs/m/miniprot/miniprot-0.13-GCC-13.2.0.eb
> +easyblock = 'MakeCp'
Same requested changes as in 

- https://github.com/easybuilders/easybuild-easyconfigs/pull/20872

2025-09-04 12:24 UTC, Crivella commented on easybuild/easyconfigs/s/SEPP/SEPP-4.5.1-foss-2023b.eb
> +local_bin_files = ['run_sepp.py', 'run_upp.py', 'split_sequences.py']
```suggestion
fix_python_shebang_for = ['bin/*.py']

local_bin_files = ['run_sepp.py', 'run_upp.py', 'split_sequences.py']
```

Required for new EB and CI

2025-09-04 12:26 UTC, Crivella commented on easybuild/easyconfigs/s/SEPP/SEPP-4.5.1-foss-2023b.eb
> +# Author: Pavel Grochal (INUITS)
I see we have version `4.5.5` of this

https://github.com/easybuilders/easybuild-easyconfigs/blob/easybuild-easyconfigs-v5.1.1/easybuild/easyconfigs/s/SEPP/SEPP-4.5.5-foss-2023a.eb

on an older TC (2023a).
Is it mandatory to use an older version here for `compleasm`?

2025-09-05 08:21 UTC, Crivella commented on easybuild/easyconfigs/s/SEPP/SEPP-4.5.5-foss-2023b.eb
> +    ('Python', '3.12.3'),
```suggestion
    ('Python', '3.11.5'),
```

This is the Python version used on `foss/2023b`
https://github.com/easybuilders/easybuild-easyconfigs/blob/easybuild-easyconfigs-v5.1.1/easybuild/easyconfigs/p/Python/Python-3.11.5-GCCcore-13.2.0.eb

2025-09-05 08:40 UTC, Crivella commented on easybuild/easyconfigs/m/miniprot/miniprot-0.13-GCC-13.2.0.eb
> +toolchain = {'name': 'GCC', 'version': '13.2.0'}
```suggestion
toolchain = {'name': 'GCCcore', 'version': '13.2.0'}
```

Do not think there is a particular reason this would need `GCC`.
Using `GCCcore` make this reusable also in other TCs

Need to change also the file name to reflect this

2025-09-05 08:42 UTC, Crivella commented
Test report by @Crivella
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
crivella-desktop - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 13th Gen Intel(R) Core(TM) i9-13900K (skylake), Python 3.11.13
See https://gist.github.com/Crivella/58554872742c4e9a46db69d30b278416 for a full test report.

2025-09-05 08:53 UTC, jkuhl-uni commented on easybuild/easyconfigs/m/miniprot/miniprot-0.13-GCC-13.2.0.eb
> +toolchain = {'name': 'GCC', 'version': '13.2.0'}
Yes, I think this is fair... I'll change it.

2025-09-05 08:58 UTC, Crivella commented
Test report by @Crivella
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
crivella-desktop - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 13th Gen Intel(R) Core(TM) i9-13900K (skylake), Python 3.11.13
See https://gist.github.com/Crivella/91f040ed5bd35aefc7c9f77fe3657037 for a full test report.

2025-09-05 08:58 UTC, Crivella commented
@boegelbot please test @ jsc-zen3

2025-09-05 09:21 UTC, Crivella commented on easybuild/easyconfigs/m/miniprot/miniprot-0.13-GCCcore-12.3.0.eb
>  sources = [{'download_filename': 'v%(version)s.tar.gz', 'filename': SOURCE_TAR_GZ}]
Using GCCcore those need to be specified if they are actually needed (it seems the `13.2.0` one worked also without binutils)

```
crivella@crivella-desktop:~$ module load GCCcore/13.2.0 
crivella@crivella-desktop:~$ module list

Currently Loaded Modules:
  1) easybuild_env/custom (S)   2) GCCcore/13.2.0
```

Also i would leave fixing the file from the `12.3.0` tc to a separate PR

2025-09-05 09:25 UTC, jkuhl-uni commented on easybuild/easyconfigs/m/miniprot/miniprot-0.13-GCCcore-12.3.0.eb
>  sources = [{'download_filename': 'v%(version)s.tar.gz', 'filename': SOURCE_TAR_GZ}]
Okay... then I do not understand the tests complaining before the commit

2025-09-05 09:25 UTC, Crivella commented on easybuild/easyconfigs/m/miniprot/miniprot-0.13-GCCcore-12.3.0.eb
>  sources = [{'download_filename': 'v%(version)s.tar.gz', 'filename': SOURCE_TAR_GZ}]
On that note i would probably add `binutils` here as the build step is doing some linking is better not to rely on the system linker

```
gcc -c -std=c99 -g -Wall -O3   align.c -o align.o
gcc -c -std=c99 -g -Wall -O3   main.c -o main.o
gcc -std=c99 -g -Wall -O3 kalloc.o kthread.o nasw-sse.o nasw-tab.o sys.o misc.o options.o ntseq.o sketch.o index.o bseq.o chain.o hit.o format.o map.o align.o main.o -o miniprot -lpthread -lz -lm

== 2025-09-05 10:58:26,164 run.py:621 INFO Shell command completed successfully (see output above): make  -j 8
```

2025-09-05 09:27 UTC, Crivella requested changes

2025-09-05 09:27 UTC, Crivella commented on easybuild/easyconfigs/m/miniprot/miniprot-0.13-GCCcore-13.2.0.eb
> +]
```suggestion
builddependencies = [('binutils', '2.40')]
dependencies = [('zlib', '1.2.13')]
```

Ensure we provide a linker for the build
See https://github.com/easybuilders/easybuild-easyconfigs/pull/20873#discussion_r2324578414

2025-09-05 09:29 UTC, Crivella commented on easybuild/easyconfigs/m/miniprot/miniprot-0.13-GCCcore-12.3.0.eb
>  sources = [{'download_filename': 'v%(version)s.tar.gz', 'filename': SOURCE_TAR_GZ}]
> Okay... then I do not understand the tests complaining before the commit

That was before switching to `GCCcore`

`GCC` is a full toolchain and brings more stuff with it. We use it when the software being build is performance critical and in general when it depends on fortran modules, linear algebra, mpi, ... (the higher level stuff uses other subtoolchains like `gompi` or `foss`  see https://docs.easybuild.io/version-specific/toolchains/ for more details)

`GCCcore` is the bare minimum and is meant to be compatible/reusable also with other toolchains

2025-09-05 09:45 UTC, Crivella commented
Test report by @Crivella
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
crivella-desktop - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 13th Gen Intel(R) Core(TM) i9-13900K (skylake), Python 3.11.13
See https://gist.github.com/Crivella/d745a9508251f677f0b11b93d974742f for a full test report.

2025-09-05 09:47 UTC, Crivella requested changes
Just to re-fix 2 of the original comments by @Micket

2025-09-05 09:47 UTC, Crivella commented on easybuild/easyconfigs/m/miniprot/miniprot-0.13-GCCcore-13.2.0.eb
> +github_account = 'lh3'
```suggestion
github_account = 'lh3'
source_urls = [GITHUB_SOURCE]
sources = ['v%(version)s.tar.gz']
checksums = ['be12d98d998beb78e4e06350c03d2f188bcdf3245d6bcaf43e2cc80785a617a4']

builddependencies = [('binutils', '2.40')]
dependencies = [('zlib', '1.2.13')]
```

2025-09-05 09:47 UTC, Crivella commented on easybuild/easyconfigs/m/miniprot/miniprot-0.13-GCCcore-13.2.0.eb
> +# check whether 7z script works
```suggestion
```

2025-09-05 09:51 UTC, Crivella commented
@boegelbot please test @ jsc-zen3

2025-09-05 10:08 UTC, Crivella approved these changes
LGTM

2025-09-05 10:09 UTC, Crivella commented
Going in, thanks @jkuhl-uni!

2025-09-05 10:09 UTC, merged