{tools,vis}[GCCcore/13.2.0] pydot v3.0.4, yMMSL-dot v0.1.2
easybuilders/easybuild-easyconfigs pull request #20906
Opened 2024-06-25 15:40 UTC by SimonPinches

(created using `eb --new-pr`)

2025-05-27 18:11 UTC, laraPPr requested changes
could you look into updating the versions?

2025-05-27 18:11 UTC, laraPPr commented on easybuild/easyconfigs/y/yMMSL-dot/yMMSL-dot-0.1.2-GCCcore-13.2.0.eb
> +sanity_pip_check = False
To pass the sanity check these two should not be in the easyconfig. If the version of `yatiml` and `ymmsl` is updated it worked for me.
```suggestion
```

2025-05-27 18:11 UTC, laraPPr commented on easybuild/easyconfigs/y/yMMSL-dot/yMMSL-dot-0.1.2-GCCcore-13.2.0.eb
> +        'checksums': ['4d23bfd7bbf45ae603c08fcb70d0c86404934a0cef24fb77b532705ff195fc92'],
```suggestion
    ('yatiml', '0.11.1', {
        'checksums': ['354cefe305e45a557eda18cd3adc7680a178b4a4ebf68606404bf967fb7a72af'],
```

2025-05-27 18:11 UTC, laraPPr commented on easybuild/easyconfigs/y/yMMSL-dot/yMMSL-dot-0.1.2-GCCcore-13.2.0.eb
> +        'checksums': ['861c8b728d2808b8e8eb31592af42c5c4317b441fbd83d050ccf91fa24a9212e'],
```suggestion
    ('ymmsl', '0.14.0', {
        'checksums': ['46f0168f84af78640f458cb5fb014c4872858bebd545b4fc6543e34fac9ae60a'],
```

2025-05-27 18:11 UTC, laraPPr commented on easybuild/easyconfigs/p/pydot/pydot-2.0.0-GCCcore-13.2.0.eb
> +        'checksums': ['60246af215123fa062f21cd791be67dda23a6f280df09f68919e637a1e4f3235'],
```suggestion
        'checksums': ['3ce88b2558f3808b0376f22bfa6c263909e1c3981e2a7b629b65b451eee4a25d'],
```

2025-05-28 07:22 UTC, SimonPinches commented on easybuild/easyconfigs/p/pydot/pydot-2.0.0-GCCcore-13.2.0.eb
> +version = '2.0.0'
Version 3 was only released on 2024-07-15, this PR dates from 2025-06-25 !  But I'm very happy it's now being looked at :-)

2025-05-28 07:24 UTC, SimonPinches commented on easybuild/easyconfigs/y/yMMSL-dot/yMMSL-dot-0.1.2-GCCcore-13.2.0.eb
> +    ('ruamel.yaml', '0.18.5'),
This turns out to not be a required dependency and has been replaced by `PyYAML/6.0.1`.

2025-05-28 07:24 UTC, SimonPinches commented on easybuild/easyconfigs/y/yMMSL-dot/yMMSL-dot-0.1.2-GCCcore-13.2.0.eb
> +sanity_pip_check = False
Thanks!

2025-05-28 08:12 UTC, laraPPr commented
Test report by @laraPPr
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node4005.donphan.os - Linux RHEL 9.4 (Plow), x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), 1 x NVIDIA NVIDIA A2, 570.133.20, Python 3.11.3
See https://gist.github.com/laraPPr/e80d9404c0bc6c80e4bb3b938246c5cd for a full test report.

2025-05-28 08:16 UTC, laraPPr approved these changes
lgtm

2025-05-28 08:17 UTC, merged