{compiler}[SYSTEM,GCCcore/13.3.0] LLVM core
easybuilders/easybuild-easyconfigs pull request #20902
Opened 2024-06-25 14:23 UTC by Crivella

EC files to compile LLVMcore (clang + flang-new + optional projects)

Requires EB from PR (https://github.com/easybuilders/easybuild-easyblocks/pull/3373)

More notes on the EB PR

2024-07-18 12:54 UTC, ocaisa commented on easybuild/easyconfigs/l/LLVM/LLVM-18.1.8.eb
> +name = 'LLVMcore'
```suggestion
name = 'LLVM'
```

2024-08-13 08:48 UTC, branfosj commented
> ERROR: Missing dependencies: lit/18.1.2-GCCcore-12.2.0, git/2.42-GCCcore-13.2.0 (no easyconfig file or existing module found)

2024-08-13 09:06 UTC, Crivella commented
@branfosj Thanks! I've fixed this with [6d35631](https://github.com/easybuilders/easybuild-easyconfigs/pull/20902/commits/6d35631040f815e2787bc9acda7305bb886bbdf4)

2024-08-13 09:11 UTC, branfosj commented
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="--include-easyblocks-from-pr 3373 --installpath /tmp/$USER/pr20902"

2024-08-14 09:07 UTC, Crivella commented
I had made a mistake using the `bare` version of python for GCC 10.3.0, this should fix the first failure and most likely the 2nd and 3rd which depended on it.
Fixed with [262f0eb](https://github.com/easybuilders/easybuild-easyconfigs/pull/20902/commits/262f0eb5f96bc21348f0abf94a4a88de5123c0eb)

For the 4th and 5th related to 18.1.8 i might need the full logs to debug it. When building on my WS and on the frontend of a cluster i did not run into errors related to `*-shared.cfg.in` in the test suite.

2024-09-25 10:17 UTC, Crivella commented
@boegel @ocaisa 
Found the problem (opened an issue for LLVM https://github.com/llvm/llvm-project/issues/109949) .

Apparently the `run.py` script that is being used to run the compiled tests is not passing over the environment so `LD_LIBRARY_PATH`  is not making it to the test execution.
This was working on my WS since i also have `libatomic` in a standard location on my system, but it is not working on the build node.

As a solution i think we could patch the `run.py`  to pass over at least `LD_LIBRARY_PATH` and possibly `PATH` .

Hopefully this will be fixed/supported upstream but i think it might take a while since it is kind of a niche use?

PS: i will also investigate into building the standalone version of libatomic which right now is not being done.
I am not sure it is strictly needed also for the `full_llvm` version as a system libatomic could still be picked up instead of the GCCcore one, but it would still be useful to have.

2024-09-25 15:43 UTC, boegel commented
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="--include-easyblocks-from-pr 3373 --installpath /tmp/$USER/pr20902"

2024-09-30 16:09 UTC, Crivella commented
Added possibility to time out tests. Requires also:

- https://github.com/easybuilders/easybuild-easyconfigs/pull/21499

for psutil (needed to enable the timeout funciton of `lit`)

2024-11-07 08:12 UTC, boegel commented
@boegelbot please test @ generoso
CORE_CNT=16
EB_ARGS="--include-easyblocks-from-pr 3373 --installpath /tmp/$USER/pr20902"

2025-03-04 21:21 UTC, boegel commented
@boegelbot please test @ jsc-zen3
CORE_CNT=16

2025-03-04 22:02 UTC, boegel commented
@boegelbot please test @ jsc-zen3
CORE_CNT=16
EB_BRANCH=5.0.x
EB_ARGS="--installpath /tmp/$USER/pr20902

2025-03-05 11:31 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3373
**FAILED**
Build succeeded for 8 out of 23 (19 easyconfigs in total)
node3597.doduo.os - Linux RHEL 9.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.9.18
See https://gist.github.com/boegel/b9a7f0ee1b2ade2511c3e8dd2539342f for a full test report.

2025-03-05 17:21 UTC, boegel commented
@boegelbot please test @ jsc-zen3
CORE_CNT=16
EB_BRANCH=5.0.x
EB_ARGS="--installpath /tmp/$USER/pr20902 --include-easyblocks-from-pr 3373"

2025-03-05 20:23 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3373
**FAILED**
Build succeeded for 19 out of 20 (20 easyconfigs in total)
node3506.doduo.os - Linux Rocky Linux 8.10, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/boegel/d2dd3a2effcb1e11a4592c85a9897d89 for a full test report.

2025-03-05 20:49 UTC, boegel commented
In tests done by the bot, there's one failing test:
```
Failed Tests (1):
  LLVM :: DebugInfo/X86/vla-multi.ll
```

2025-03-05 20:55 UTC, boegel commented
@boegelbot please test @ jsc-zen3
CORE_CNT=16
EB_BRANCH=5.0.x
EB_ARGS="LLVM-11.1.0-GCCcore-10.3.0.eb LLVM-12.0.1-GCCcore-10.3.0.eb --installpath /tmp/$USER/pr20902 --include-easyblocks-from-pr 3373"

2025-03-05 21:28 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3373
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3506.doduo.os - Linux Rocky Linux 8.10, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/boegel/ace4ca4ff199d9ab44db9c4ce120c91b for a full test report.

2025-03-05 21:35 UTC, boegel commented
> In tests done by the bot, there's one failing test:
> 
> ```
> Failed Tests (1):
>   LLVM :: DebugInfo/X86/vla-multi.ll
> ```

Seems like this was a known issue, that disappeared since LLVM 14, so no clear fix for it, see https://github.com/llvm/llvm-project/issues/53980

@Crivella Can we easily ignore a particular test somehow?

2025-03-05 21:50 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3373
**FAILED**
Build succeeded for 8 out of 10 (8 easyconfigs in total)
node3597.doduo.os - Linux RHEL 9.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.9.18
See https://gist.github.com/boegel/a07e62e5708375dfd31eb9c3dfb4217d for a full test report.

2025-03-05 21:52 UTC, boegel commented
Failing tests for LLVM 16.0.6 on RHEL9:
```
Failed Tests (2):
  LLVM :: MC/ELF/compress-debug-sections-zstd-unavailable.s
  LLVM :: tools/llvm-objcopy/ELF/compress-debug-sections-zstd-err.test
```

2025-03-06 09:30 UTC, Crivella commented
Umh i think this might be a bug in the build/test-suite of LLVM 16.

It is weird as the test running means that ZSTD was properly disable through the CMAKE options
https://github.com/llvm/llvm-project/blob/7cbf1a2591520c2491aa35339f227775f4d3adf6/llvm/test/tools/llvm-objcopy/ELF/compress-debug-sections-zstd-err.test#L1

https://github.com/easybuilders/easybuild-easyblocks/blob/d726a99c52a9891ff89af95269f74f2244e150b6/easybuild/easyblocks/l/llvm.py#L581

but the test is nor erroring out with the expected message.

Similarly for the other test file
https://github.com/llvm/llvm-project/blob/0cceac6bbdf800b04c3325e1134a8b25b6d1a0bb/llvm/test/MC/ELF/compress-debug-sections-zstd-unavailable.s#L1

Either a system ZTSD is being found and linked (which could explain the difference between RHEL 8 and 9) even if it shouldn't, or I will need the logs to understand what is going on.

All in all they don't seem blocking test as they are cheking the correct behavior in case ZSTD is known not to be there.


Would probably be safe to ignore

2025-03-06 09:47 UTC, Crivella commented
> @Crivella Can we easily ignore a particular test somehow?

Would need to implement that, for now we can only specify a number of allowed failures

2025-03-06 09:51 UTC, boegel commented
@Crivella details on those failing `zstd` tests:



for failing `MC/ELF/compress-debug-sections-zstd-unavailable.s`:

<details>

```
FAIL: LLVM :: MC/ELF/compress-debug-sections-zstd-unavailable.s (30050 of 46678)
******************** TEST 'LLVM :: MC/ELF/compress-debug-sections-zstd-unavailable.s' FAILED ********************
Script:
--
: 'RUN: at line 2';   not /tmp/vsc40023/easybuild_build/LLVM/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/llvm-mc -filetype=obj -compress-debug-sections=zstd -triple x86_64 /tmp/vsc40023/easybuild_build/LLVM/16.00
.6/GCCcore-12.3.0/llvm-project-16.0.6.src/llvm/test/MC/ELF/compress-debug-sections-zstd-unavailable.s 2>&1 | /tmp/vsc40023/easybuild_build/LLVM/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/FileCheck /tmp/vsc400233
/easybuild_build/LLVM/16.0.6/GCCcore-12.3.0/llvm-project-16.0.6.src/llvm/test/MC/ELF/compress-debug-sections-zstd-unavailable.s
--
Exit Code: 1

Command Output (stderr):
--
/tmp/vsc40023/easybuild_build/LLVM/16.0.6/GCCcore-12.3.0/llvm-project-16.0.6.src/llvm/test/MC/ELF/compress-debug-sections-zstd-unavailable.s:4:10: error: CHECK: expected string not found in input
# CHECK: error: --compress-debug-sections: LLVM was not built with LLVM_ENABLE_ZSTD or did not find zstd at build time
         ^
<stdin>:1:1: note: scanning from here
^?ELF^B^A^A^@^@^@^@^@^@^@^@^@^A^@>^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@p^@^@^@^@^@^@^@^@^@^@^@@^@^@^@^@^@@^@^D^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@.text^@.strtab^@.symtab^@^@^@^@^@@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^G^@^@^@^C^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@X^@^@^@^@^@^@^@^W^@^@^@^@^@^@^@^@^^
@^@^@^@^@^@^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^A^@^@^@^F^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^D^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^O^@^@^@^B^@^@^@^@^@^@^@^@^@^@^@@
^@^@^@^@^@^@^@^@@^@^@^@^@^@^@^@^X^@^@^@^@^@^@^@^A^@^@^@^A^@^@^@^H^@^@^@^@^@^@^@^X^@^@^@^@^@^@^@
^

Input file: <stdin>
Check file: /tmp/vsc40023/easybuild_build/LLVM/16.0.6/GCCcore-12.3.0/llvm-project-16.0.6.src/llvm/test/MC/ELF/compress-debug-sections-zstd-unavailable.s

-dump-input=help explains the following input dump.

Input was:
<<<<<<
         1: ^?ELF^B^A^A^@^@^@^@^@^@^@^@^@^A^@>^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@p^@^@^@^@^@^@^@^@^@^@^@@^@^@^@^@^@@^@^D^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@.text^@.strtab^@.symtt
ab^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^G^@^@^@^C^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@X^@^@^@^@^@^@^@^W^@^@^^
@^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^A^@^@^@^F^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^D^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^O^@^@^@^B^@^@^@^@^@@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@@^@^@^@^@^@^@^@^X^@^@^@^@^@^@^@^A^@^@^@^A^@^@^@^H^@^@^@^@^@^@^@^X^@^@^@^@^@^@^@
check:4     X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
>>>>>>
```

</details>

for failing `tools/llvm-objcopy/ELF/compress-debug-sections-zstd-err.test`:

<details>

```
UNSUPPORTED: LLVM :: tools/llvm-objcopy/ELF/compress-debug-sections-zstd.test (43705 of 46678)
...
******************** TEST 'LLVM :: tools/llvm-objcopy/ELF/compress-debug-sections-zstd-err.test' FAILED ********************
Script:
--
: 'RUN: at line 2';   /tmp/vsc40023/easybuild_build/LLVM/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/yaml2obj /tmp/vsc40023/easybuild_build/LLVM/16.0.6/GCCcore-12.3.0/llvm-project-16.0.6.src/llvm/test/tools/llvmm
-objcopy/ELF/Inputs/compress-debug-sections.yaml -o /tmp/vsc40023/easybuild_build/LLVM/16.0.6/GCCcore-12.3.0/llvm.obj.1/test/tools/llvm-objcopy/ELF/Output/compress-debug-sections-zstd-err.test.tmp
: 'RUN: at line 3';   not /tmp/vsc40023/easybuild_build/LLVM/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/llvm-objcopy --compress-debug-sections=zstd /tmp/vsc40023/easybuild_build/LLVM/16.0.6/GCCcore-12.3.0/llvm..
obj.1/test/tools/llvm-objcopy/ELF/Output/compress-debug-sections-zstd-err.test.tmp /dev/null 2>&1 | /tmp/vsc40023/easybuild_build/LLVM/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/FileCheck /tmp/vsc40023/easybuill
d_build/LLVM/16.0.6/GCCcore-12.3.0/llvm-project-16.0.6.src/llvm/test/tools/llvm-objcopy/ELF/compress-debug-sections-zstd-err.test
--
Exit Code: 2

Command Output (stderr):
--
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /tmp/vsc40023/easybuild_build/LLVM/16.0.6/GCCcore-12.3.0/llvm.obj.1/bin/FileCheck /tmp/vsc40023/easybuild_build/LLVM/16.0.6/GCCcore-12.3.0/llvm-project-16.0.6.src/llvm/test/tools//
llvm-objcopy/ELF/compress-debug-sections-zstd-err.test

--
```

</details>

I agree this seems like a problem with the tests more than anything, but if possible we should figure out how to fix/dance around this, to avoid that many people fail to install LLVM 16.x because of this with EasyBuild 5+

2025-03-06 14:59 UTC, boegel commented
I've opened a dedicated issue for the `zstd` related test failures with LLVM 16.0.6:
* https://github.com/easybuilders/easybuild-easyconfigs/issues/22486

2025-03-06 15:43 UTC, boegel requested changes

2025-03-06 15:54 UTC, boegel commented
@boegelbot please test @ jsc-zen3
CORE_CNT=16
EB_ARGS="LLVM-12.0.1-GCCcore-11.2.0.eb LLVM-14.0.3-GCCcore-11.3.0.eb LLVM-14.0.6-GCCcore-12.2.0-llvmlite.eb LLVM-14.0.6-GCCcore-12.3.0-llvmlite.eb LLVM-14.0.6-GCCcore-13.2.0-llvmlite.eb LLVM-15.0.5-GCCcore-12.2.0.eb LLVM-16.0.6-GCCcore-12.3.0.eb LLVM-16.0.6-GCCcore-13.2.0.eb LLVM-18.1.8-GCCcore-13.3.0-minimal.eb --include-easyblocks-from-pr 3373"
EB_BRANCH=5.0.x

2025-03-06 18:42 UTC, boegel commented
Hmm, pretty consistent small group of tests that failed with bot:
```
Failed Tests (6):
  LLVM :: tools/llvm-mt/big_merge.test
  LLVM :: tools/llvm-mt/conflicting.test
  LLVM :: tools/llvm-mt/notify_update.test
  LLVM :: tools/llvm-mt/simple_merge.test
  LLVM :: tools/llvm-mt/single_file.test
  LLVM :: tools/llvm-mt/xml_error.test
```

Not sure what can cause these, they didn't pop up before.

@Crivella I won't let this block the merge of https://github.com/easybuilders/easybuild-easyblocks/pull/3373 + this PR, but we should maybe follow up on this?

2025-03-06 20:19 UTC, Crivella commented
I will check on them tomorrow, but i do not think they are extremely relevant (seems to be only a problem with the tool llvm-mt)

2025-03-06 20:43 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3373
**FAILED**
Build succeeded for 19 out of 20 (20 easyconfigs in total)
node3506.doduo.os - Linux Rocky Linux 8.10, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/boegel/3046b058f9552bfe638d56b83721ec52 for a full test report.

2025-03-07 00:56 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3373
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
node3623.doduo.os - Linux RHEL 9.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.9.18
See https://gist.github.com/boegel/30ecfa7426fab72e5bd2198e7d348f5e for a full test report.

2025-03-07 06:47 UTC, boegel commented
Test build for `LLVM/18.1.8-GCCcore-13.3.0-minimal` in Rocky Linux 8.10 container failed with:
```
cmake: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

That's entirely my bad, there is not OpenSSL 3 in that containers and I was reusing a bunch of modules...

I'll upload a new test report for that one easyconfigs, and then this is good to go... \o/

2025-03-07 07:43 UTC, boegel submitted a review, later dismissed
Extensively tested with https://github.com/easybuilders/easybuild-easyblocks/pull/3373, so time to finally merge this.

@Crivella Thanks *a lot* for all your efforts on this, and sorry for the holdup...

2025-03-07 07:47 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3373
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3506.doduo.os - Linux Rocky Linux 8.10, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/boegel/70a222efa6817f148396e32fc363682a for a full test report.

2025-03-07 07:56 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3623.doduo.os - Linux RHEL 9.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.9.18
See https://gist.github.com/boegel/b9cd59dc76efb68f646ec1d12d6b9328 for a full test report.

2025-03-07 10:58 UTC, Thyre commented
Is there a reason why we have both `easybuild/easyconfigs/l/lit/lit-18.1.7-GCCcore-13.3.0.eb` and `easybuild/easyconfigs/l/lit/lit-18.1.8-GCCcore-13.3.0.eb` for `GCCcore/13.3.0`? `easybuild/easyconfigs/l/LLVM/LLVM-18.1.8-GCCcore-13.3.0-minimal.eb` is only using the latter.

2025-03-07 13:18 UTC, Thyre commented
Hm, when working on #22489, I ran into checksum issues with `LLVM-14.0.6-clear-gotoffsetmap.patch`.
Looks like https://github.com/easybuilders/easybuild-easyconfigs/pull/20902/commits/1f2873ea51292e9e8d13fa99a861b07832a211fe updated the patch, but the wrong version was used.

Patch for the current checksum `c048afdddcf54c7213018d06f709f61274af5b90b8dcd97a632be4fe53750a51`:

<details>
<summary>Click to open</summary>

```
From 322c79fff224389b4df9f24ac22965867007c2fa Mon Sep 17 00:00:00 2001
From: Graham Markall <gmarkall@nvidia.com>
Date: Mon, 13 Mar 2023 21:35:11 +0000
Subject: [PATCH] RuntimeDyldELF: Clear the GOTOffsetMap when finalizing the
 load

This needs resetting so that stale entries are not left behind when the
GOT section and index are reset.

See llvm/llvm#61402: RuntimeDyldELF doesn't clear GOTOffsetMap in
finalizeLoad(), leading to invalid GOT relocations on AArch64 -
https://github.com/llvm/llvm-project/issues/61402.
---
 llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp | 1 +
 1 file changed, 1 insertion(+)

diff --git a/llvm-14.0.6.src/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp b/llvm-14.0.6.src/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp
index f92618afdff6..eb3c27a9406a 100644
--- a/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp
+++ b/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp
@@ -2345,6 +2345,7 @@ Error RuntimeDyldELF::finalizeLoad(const ObjectFile &Obj,
     }
   }
 
+  GOTOffsetMap.clear();
   GOTSectionID = 0;
   CurrentGOTIndex = 0;
 
-- 
2.34.1

```

</details>

Actual patch in the current PR `690c96dcbd0a81e11d87f02e740c4ef34a0c578be741aaa6559cc00a5349fabf`:

<details>
<summary>Click to open</summary>

```
From 322c79fff224389b4df9f24ac22965867007c2fa Mon Sep 17 00:00:00 2001
From: Graham Markall <gmarkall@nvidia.com>
Date: Mon, 13 Mar 2023 21:35:11 +0000
Subject: [PATCH] RuntimeDyldELF: Clear the GOTOffsetMap when finalizing the
 load

This needs resetting so that stale entries are not left behind when the
GOT section and index are reset.

See llvm/llvm#61402: RuntimeDyldELF doesn't clear GOTOffsetMap in
finalizeLoad(), leading to invalid GOT relocations on AArch64 -
https://github.com/llvm/llvm-project/issues/61402.
---
 llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp | 1 +
 1 file changed, 1 insertion(+)

diff --git a/llvm-14.0.6.src/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp b/llvm-14.0.6.src/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp
index f92618afdff6..eb3c27a9406a 100644
--- a/llvm-14.0.6.src/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp
+++ b/llvm-14.0.6.src/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp
@@ -2345,6 +2345,7 @@ Error RuntimeDyldELF::finalizeLoad(const ObjectFile &Obj,
     }
   }
 
+  GOTOffsetMap.clear();
   GOTSectionID = 0;
   CurrentGOTIndex = 0;
 
-- 
2.34.1

```

</details>

Diff:

```diff
19,20c19,20
< --- a/llvm-14.0.6.src/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp
< +++ b/llvm-14.0.6.src/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp
---
> --- a/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp
> +++ b/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp
```

2025-03-07 19:11 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3623.doduo.os - Linux RHEL 9.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.9.18
See https://gist.github.com/boegel/0582b42046cb9eb598a4df265fce6ba4 for a full test report.

2025-03-07 21:43 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3621.doduo.os - Linux Rocky Linux 8.10, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/boegel/e20a5f3be17311f8a26729d9a55ca585 for a full test report.

2025-03-08 08:46 UTC, boegel approved these changes

2025-03-08 08:46 UTC, boegel commented
Going in, thanks @Crivella!

2025-03-08 08:46 UTC, merged

2025-04-07 08:32 UTC, Flamefire commented
Was it an intended change to remove `build_shared_libs` from the GCCcore 10.3 toolchains or an oversight? It breaks the Mesa build for me

2025-04-07 08:42 UTC, Thyre commented
> Was it an intended change to remove `build_shared_libs` from the GCCcore 10.3 toolchains or an oversight? It breaks the Mesa build for me

Given that LLVM 14.x.x+ still have `build_shared_libs`, I'd guess that this was just an oversight.