{lib}[foss/2023a] rMATS-long v1.0.0 w/ R 4.3.2
easybuilders/easybuild-easyconfigs pull request #20916
Opened 2024-06-26 15:05 UTC by pavelToman

(created using `eb --new-pr`)

2024-06-26 15:05 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-06-26 15:14 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-06-27 09:57 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-07-06 09:55 UTC, boegel requested changes

2024-07-06 09:55 UTC, boegel commented on easybuild/easyconfigs/r/rMATS-long/rMATS-long-1.0.0-foss-2023a-R-4.3.2.eb
> +version = '1.0.0'
If we take a more recent commit that the `1.0.0` tag, we should also add a datestamp to the version:
```
version = '1.0.0-20240502'
```

2024-07-06 09:55 UTC, boegel commented on easybuild/easyconfigs/r/rMATS-long/rMATS-long-1.0.0-foss-2023a-R-4.3.2.eb
> +version = '1.0.0'
fixed in ef85e1f

2024-07-06 09:55 UTC, boegel commented
@boegelbot please test @ generoso

2024-07-06 09:55 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-07-06 09:57 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3158.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/0c67b124a12c2234df3ea62c06d8de17 for a full test report.

2024-07-06 10:02 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-07-06 10:02 UTC, boegel approved these changes

2024-07-06 15:21 UTC, boegel commented
Going in, thanks @pavelToman!

2024-07-06 15:21 UTC, merged