{numlib}[foss/2023b] Bandicoot v1.14.0
easybuilders/easybuild-easyconfigs pull request #20962
Opened 2024-07-04 11:20 UTC by tanmoy1989

(created using `eb --new-pr`)

2024-07-04 11:22 UTC, tanmoy1989 commented
Requires https://github.com/easybuilders/easybuild-easyblocks/pull/3380

2025-06-16 09:27 UTC, sassy-crick commented
@tanmoy1989 You might want to sync your PR with development, something like this: 
```
eb --sync-pr-with-develop NUMBER_OF_PR
```

2025-06-16 09:43 UTC, laraPPr submitted a review, later dismissed

2025-06-16 09:43 UTC, laraPPr commented on easybuild/easyconfigs/b/Bandicoot/Bandicoot-1.14.0-foss-2023b.eb
> +    ('CUDA', '12.0.0', '', SYSTEM),
Do you require CUDA-12.0.0 for any specific reason? Otherwise we would prefer you bump it to CUDA-12.4.0.
```suggestion
    ('CUDA', '12.4.0', '', SYSTEM),
```

2026-08-05 16:05 UTC, boegel requested changes

2026-08-05 16:05 UTC, boegel commented on easybuild/easyconfigs/b/Bandicoot/Bandicoot-1.14.0-foss-2023b-CUDA-12.4.0.eb
> +version = '1.14.0'
when `CUDA` is a dependency, this should be reflected in the `versionsuffix`:
```suggestion
version = '1.14.0'
versionsuffix = '-CUDA-%(cudaver)s'
```

note that this implies renaming the easyconfig file as well (should be `Bandicoot-1.14.0-foss-2023b-CUDA-12.4.0.eb`)

2026-08-07 08:43 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3380
**SUCCESS**
Build succeeded for 1 out of 1 (total: 1 min 3 secs) (1 easyconfigs in total)
node4401.skiddo.os - Linux RHEL 9.6, x86_64, AMD EPYC 9755 128-Core Processor (zen5), Python 3.9.21
See https://gist.github.com/boegel/89ddd7a36a8ce19d64c0dad959e67301 for a full test report.

2026-08-07 08:46 UTC, boegel commented
@boegelbot please test @ jsc-zen3-a100
EB_ARGS="--include-easyblocks-from-pr 3380"

2026-08-07 09:58 UTC, boegel approved these changes
lgtm

2026-08-07 09:59 UTC, boegel commented
Going in, thanks @tanmoy1989!

2026-08-07 09:59 UTC, merged