{bio,lib}[GCC/12.3.0] Transrate v1.0.3, crb-blast v0.6.9, colorize v0.7.7, ...
easybuilders/easybuild-easyconfigs pull request #20964
Opened 2024-07-04 12:16 UTC by PetrKralCZ

(created using `eb --new-pr`)

2024-07-04 19:12 UTC, boegel commented
@boegelbot please test @ generoso
EB_ARGS="--include-easyblocks-from-pr 3381"

2024-07-04 19:30 UTC, boegel commented
Test report by @boegel
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3381
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3158.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/3e166b117e4b021e5a13dd3525235e11 for a full test report.

2024-07-04 20:19 UTC, boegel commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--include-easyblocks-from-pr 3381"

2024-07-05 06:22 UTC, boegel commented
Hmm, sanity check on `jsc-zen3` fails with:
```
`terminal_columns': undefined method `winsize' for nil (NoMethodError)
```

2024-07-23 15:30 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3

2024-07-24 13:53 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3

2024-07-25 09:55 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3

2024-07-25 10:11 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-08-06 12:14 UTC, boegel requested changes

2024-08-06 12:14 UTC, boegel commented on easybuild/easyconfigs/c/colorize/colorize-0.7.7-GCC-12.3.0.eb
> +
`binutils` build dependency is not needed, it's already available when using `GCC` toolchain (not when using `GCCcore` as toolchain)

```suggestion
```

2024-08-06 12:14 UTC, boegel commented on easybuild/easyconfigs/c/crb-blast/crb-blast-0.6.9-GCC-12.3.0.eb
> +
```suggestion
```

2024-08-06 12:14 UTC, boegel commented on easybuild/easyconfigs/t/Transrate/Transrate-1.0.3-GCC-12.3.0.eb
> +
```suggestion
```

2024-08-06 12:14 UTC, boegel commented on easybuild/easyconfigs/y/yell/yell-2.2.2-GCC-12.3.0.eb
> +
```suggestion
```

2024-08-06 12:28 UTC, boegel approved these changes
lgtm

2024-08-06 12:28 UTC, boegel commented
@boegelbot please test @ generoso

2024-08-06 12:29 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3153.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/a67f90492a1eedce73c3ba9e14270f2f for a full test report.

2024-08-06 14:11 UTC, boegel commented
Going in, thanks @PetrKralCZ!

2024-08-06 14:11 UTC, merged