{vis}[foss/2023b] ParaView v5.12.0 w/ Qt5
easybuilders/easybuild-easyconfigs pull request #21001
Opened 2024-07-12 08:13 UTC by SimonPinches

(created using `eb --new-pr`)

2024-07-12 08:18 UTC, SimonPinches commented
Qt6 support in ParaView 5.12.0 still appears to be experimental ([see this paraview PR](https://gitlab.kitware.com/paraview/paraview/-/merge_requests/6134)).  Some users have reported significant performance benefits when using Qt5 with ParaView for some applications - hence this PR.

2024-07-12 09:44 UTC, furstj commented
Could you add VTK_PYTHON_OPTIONAL_LINK=OFF to your configuration? It seems to be necessary for OpenFOAM in-situ visualization with Catalyst. See e.g.  https://discourse.paraview.org/t/advice-on-building-paraview-superbuild-for-openfoam-runtimepostprocessing/8707.

2024-07-12 13:20 UTC, SimonPinches commented
> for OpenFOAM in-situ visualization with Catalyst.

Done :-)

2024-07-17 17:20 UTC, SimonPinches commented
PR https://github.com/easybuilders/easybuild-easyconfigs/pull/21002 fixes the issues addressed by this PR so it's no longer needed.

2024-07-18 08:05 UTC, furstj commented
Are you sure that PV wit Qt6 from #21002 solves the "Some users have reported significant performance benefits when using Qt5 with ParaView for ..." ?

2024-08-20 13:58 UTC, SimonPinches commented
Maybe not for all users so I can re-open this PR in case it's useful :-)

2024-08-21 08:01 UTC, boegel requested changes

2024-08-21 08:01 UTC, boegel commented on easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-foss-2023b-Qt5.eb
> +    '-DVTK_PYTHON_OPTIONAL_LINK=OFFVTK_PYTHON_=OFF']
```suggestion
    '-DVTK_PYTHON_OPTIONAL_LINK=OFF']
```

2024-08-21 08:12 UTC, boegel commented
@boegelbot please test @ generoso
CORE_CNT=16

2024-08-21 09:14 UTC, boegel commented
@boegelbot please test @ jsc-zen3
CORE_CNT=16

2024-08-21 09:49 UTC, SimonPinches commented on easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-foss-2023b-Qt5.eb
> +    '-DVTK_PYTHON_OPTIONAL_LINK=OFFVTK_PYTHON_=OFF']
Thanks @boegel :-)

2024-08-21 09:55 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/450dcbdd2ad4e18f2cab88666ccf28ed for a full test report.

2024-08-21 10:48 UTC, boegel approved these changes

2024-08-21 10:48 UTC, boegel commented
Going in, thanks @SimonPinches!

2024-08-21 10:48 UTC, merged