{tools}[GCC/12.3.0] GPU-comcot v20231130
easybuilders/easybuild-easyconfigs pull request #21041
Opened 2024-07-25 03:31 UTC by JinyuHan99

(created using `eb --new-pr`)

2025-06-16 13:04 UTC, sassy-crick commented
@JinyuHan99 You might want to sync your PR with development, something like this: 
```
eb --sync-pr-with-develop NUMBER_OF_PR
```

2026-01-13 13:44 UTC, sassy-crick commented
Test report by @sassy-crick
**SUCCESS**
Build succeeded for 1 out of 1 (total: 3 secs) (1 easyconfigs in total)
hp - Linux Debian GNU/Linux 12, x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.11.2
See https://gist.github.com/sassy-crick/2f9aa0b9d7e7fa3b7626335f77785073 for a full test report.

2026-01-13 14:30 UTC, Thyre commented on easybuild/easyconfigs/g/GPU-comcot/GPU-comcot-20231130-GCC-12.3.0-CUDA-12.4.0.eb
> +version = '20231130'
```suggestion
name = 'GPU-comcot'
version = '20231130'
versionsuffix = '-CUDA-%(cudaver)s'
```

2026-06-12 06:12 UTC, boegel commented on easybuild/easyconfigs/g/GPU-comcot/GPU-comcot-20231130-GCC-12.3.0-CUDA-12.4.0.eb
> +version = '20231130'
fixed in 18103299e1

2026-06-12 06:12 UTC, boegel requested changes

2026-06-12 06:12 UTC, boegel commented on easybuild/easyconfigs/g/GPU-comcot/GPU-comcot-20231130-GCC-12.3.0-CUDA-12.4.0.eb
> +sanity_check_commands = [('comcot', '--version')]
```suggestion
sanity_check_commands = [('comcot', '--version')]

```

2026-06-12 06:13 UTC, boegel approved these changes
lgtm

2026-06-12 06:14 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (total: 28 secs) (1 easyconfigs in total)
node4007.donphan.os - Linux RHEL 9.6, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), 1 x NVIDIA NVIDIA A2, 595.71.05, Python 3.9.21
See https://gist.github.com/boegel/01b54b4ebf2349051a2bc29e830a6c27 for a full test report.

2026-06-12 06:14 UTC, boegel commented
@boegelbot please test @ jsc-zen3-a100

2026-06-12 06:52 UTC, boegel commented
Going in, thanks @JinyuHan99!

2026-06-12 06:57 UTC, merged