{bio,vis}[foss/2023a] scenicplus v1.0a1-18072024, gensim v4.3.2, pyfasta v0.5.2, ...
easybuilders/easybuild-easyconfigs pull request #21085
Opened 2024-07-29 12:42 UTC by pavelToman

(created using `eb --new-pr`)

2024-07-29 12:47 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-07-30 19:04 UTC, smoors commented
> Test report by @boegelbot **FAILED** Build succeeded for 6 out of 8 (7 easyconfigs in total) cns1 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz (haswell), Python 3.6.8 See https://gist.github.com/boegelbot/de0b345903b78154ef118c9c68d9d858 for a full test report.

`polars` needs to be built from branch 5.0.x, i spawned a build for generoso in #20275

2024-07-31 14:10 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-08-02 09:21 UTC, boegel commented
@boegelbot please test @ generoso

2024-08-02 14:34 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-08-13 10:03 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-08-14 09:21 UTC, pavelToman commented
Seems `tensorflow-probability/0.20.0-foss-2023a` is not installed on generoso?

2024-08-14 09:24 UTC, smoors commented
> Seems `tensorflow-probability/0.20.0-foss-2023a` is not installed on generoso?

it was rebuilt this morning, which probably clashed with your test
see https://github.com/easybuilders/easybuild-easyconfigs/pull/21172

2024-08-14 09:38 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-08-14 12:12 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-08-20 13:51 UTC, boegel requested changes

2024-08-20 13:51 UTC, boegel commented on easybuild/easyconfigs/s/scenicplus/scenicplus-1.0a1-18072024-foss-2023a.eb
> +version = '1.0a1-18072024'
datestamp should be `<year><month><day>`, and should correspond to date of commit being used (so in this case `20240513`)

2024-08-20 13:51 UTC, boegel commented on easybuild/easyconfigs/s/scenicplus/scenicplus-1.0a1-18072024-foss-2023a.eb
> +        ],
```suggestion
        'sources': [{'download_filename': '%s.tar.gz' % local_commit, 'filename': SOURCE_TAR_GZ}],
        'checksums': ['88cddec1ab2618861e5c93e8a0b17b8e9e2aa3a76410d882c35d472f98724e29'],

2024-08-20 13:51 UTC, boegel commented on easybuild/easyconfigs/s/scenicplus/scenicplus-1.0a1-18072024-foss-2023a.eb
> +    'cp -r %(builddir)s/scenicplus/scenicplus-fa55dae55203951c0c42e359b65a28010cd544f6/src/scenicplus/snakemake '
don't hardcode commit ID here, use `local_commit` variable:
```suggestion
    "cp -r %%(builddir)s/scenicplus/scenicplus-%s*/src/scenicplus/snakemake " % local_commit
```

2024-08-20 13:51 UTC, boegel commented on easybuild/easyconfigs/s/scenicplus/scenicplus-1.0a1-18072024-foss-2023a.eb
> +    " -e '60,61d'"
Can we avoid relying on line numbers here, and use something like `/loomxpy/d` instead?

2024-08-20 13:52 UTC, boegel requested changes

2024-08-20 13:52 UTC, boegel commented on easybuild/easyconfigs/s/scenicplus/scenicplus-1.0a1-18072024-foss-2023a.eb
> +name = 'scenicplus'
@pavelToman `SCENIC+` is official software name, so we should use that.

The `+` is annoying though, so let's go with `SCENISplus` as a compromise?

2024-08-20 17:22 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-08-28 10:26 UTC, boegel requested changes

2024-08-28 10:26 UTC, boegel commented on easybuild/easyconfigs/s/SCENICplus/SCENICplus-1.0a1-20240513-foss-2023a.eb
> +    ('%(namelower)s', version, {
Avoid using `%(namelower)s` in extension name (there's an unresolved bug in EasyBuild framework that leads to not resolving this template):
```suggestion
    ('scenisplus', version, {

2024-08-28 13:15 UTC, boegel approved these changes
lgtm

2024-08-28 14:05 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
node3123.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/d8499e12f96e77a3c3d08a5291b7a3b4 for a full test report.

2024-08-29 07:32 UTC, boegel commented
Going in, thanks @pavelToman!

2024-08-29 07:32 UTC, merged