{lib}[GCCcore/13.3.0] cppzmq v4.10.0
easybuilders/easybuild-easyconfigs pull request #21125
Opened 2024-08-04 15:45 UTC by SebastianAchilles

(created using `eb --new-pr`)

2024-08-04 18:12 UTC, SebastianAchilles commented
Test report by @sebastianachilles
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
zen2-rockylinux-810 - Linux Rocky Linux 8.10, x86_64, AMD EPYC 7452 32-Core Processor (zen2), Python 3.6.8
See https://gist.github.com/SebastianAchilles/3c0928c24c9e28b930249a843059a873 for a full test report.

2024-08-04 20:11 UTC, SebastianAchilles commented
@boegelbot please test @ jsc-zen3

2024-08-04 20:22 UTC, SebastianAchilles commented
@boegelbot please test @ generoso

2025-08-18 17:44 UTC, Thyre commented on easybuild/easyconfigs/c/cppzmq/cppzmq-4.10.0-GCCcore-13.3.0.eb
> +separate_build_dir = True
```suggestion
```

This should not be needed anymore with recent EasyBuild versions

2026-06-10 12:28 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2026-06-10 12:34 UTC, boegel requested changes

2026-06-10 12:34 UTC, boegel commented on easybuild/easyconfigs/c/cppzmq/cppzmq-4.10.0-GCCcore-13.3.0.eb
> +separate_build_dir = True
```suggestion
```

2026-06-10 12:43 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (total: 6 mins 2 secs) (1 easyconfigs in total)
node4231.shinx.os - Linux RHEL 9.6, x86_64, AMD EPYC 9654 96-Core Processor (zen4), Python 3.9.21
See https://gist.github.com/boegel/a7f8ac401e2ccf9e3bd81a826c053c22 for a full test report.

2026-06-10 14:21 UTC, boegel approved these changes
lgtm

2026-06-10 14:22 UTC, boegel commented
Going in, thanks @SebastianAchilles!

2026-06-10 14:22 UTC, merged