{lib}[foss/2022b] synthcity v0.2.10, DECAF-synthetic-data v0.1.6, PyTorch-Lightning v1.8.4, ... w/ PyTorch 1.13.1
easybuilders/easybuild-easyconfigs pull request #21141
Opened 2024-08-07 10:58 UTC by pavelToman

(created using `eb --new-pr`)

2024-08-10 08:58 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-08-13 15:33 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-08-19 09:47 UTC, boegel requested changes

2024-08-19 09:47 UTC, boegel commented on easybuild/easyconfigs/s/synthcity/synthcity-0.2.10-foss-2022b.eb
> +            {'name': 'numpy-1.22.3_disable-broken-override-test.patch', 'alt_location': 'Scipy-bundle'},
@pavelToman The `alt_location` is case-sensitive, and `SciPy-bundle` has a capital `P` in it:

```suggestion
            {'name': 'numpy-1.20.3_fix-fortran-compiler-error.patch', 'alt_location': 'SciPy-bundle'},
            {'name': 'numpy-1.22.3_disable-broken-override-test.patch', 'alt_location': 'SciPy-bundle'},

2024-08-19 10:33 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-08-19 12:35 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-08-20 08:29 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-08-20 13:13 UTC, boegel commented
@pavelToman On `jsc-zen3`, it's failing for `python-igraph-0.10.6-foss-2022b.eb` with:
```
AttributeError: Plotting not available; please install pycairo or cairocffi
```

`cairo` dependency is missing in `python-igraph-0.10.6-foss-2022b.eb`, please open a separate PR to fix that.

This problem didn't happen on `generoso` because there's a system-wide installation of `cairo` there that's being picked up...

2024-08-20 13:57 UTC, pavelToman commented
PR

> @pavelToman On `jsc-zen3`, it's failing for `python-igraph-0.10.6-foss-2022b.eb` with:
> 
> ```
> AttributeError: Plotting not available; please install pycairo or cairocffi
> ```
> 
> `cairo` dependency is missing in `python-igraph-0.10.6-foss-2022b.eb`, please open a separate PR to fix that.
> 
> This problem didn't happen on `generoso` because there's a system-wide installation of `cairo` there that's being picked up...

PR created:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21211

2024-08-20 16:07 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-08-20 20:40 UTC, boegel commented
@boegelbot please test @ generoso

2024-08-28 13:33 UTC, boegel commented
Consistent test failures on both systems:
```
=========================== short test summary info ============================
FAILED plugins/privacy/test_decaf.py::test_plugin_generate[test_plugin0] - Ru...
FAILED plugins/privacy/test_decaf.py::test_plugin_generate[test_plugin1] - Ru...
FAILED plugins/privacy/test_decaf.py::test_plugin_generate[test_plugin2] - Ru...
FAILED plugins/privacy/test_decaf.py::test_get_dag[d-struct] - RuntimeError: ...
= 4 failed, 2155 passed, 13 skipped, 103 deselected, 2 xfailed, 1629 warnings in 14104.32s (3:55:04) =
```

Underlying problem isn't revealed in partial log though...

2024-08-29 09:28 UTC, boegel commented
I couldn't trigger the test failures when triggering the installation manually on `jsc-zen3`, but that was in an interactive job with 16 cores, so more memory, that may explain why the tests passed...

I'll try to confirm that.

2024-08-29 13:26 UTC, boegel commented
@boegelbot please test @ jsc-zen3
EB_ARGS="--tmp-logdir $HOME/synthcity-pr21141 --disable-cleanup-tmpdir"

2024-08-29 20:06 UTC, boegel commented
More info on first test failure shows that the tests are sensitive to running in a Slurm job environment:
```
=================================== FAILURES ===================================
______________________ test_plugin_generate[test_plugin0] ______________________

test_plugin = <synthcity.plugins.privacy.plugin_decaf.DECAFPlugin object at 0x1468bf707c70>

    @pytest.mark.parametrize(
        "test_plugin", generate_fixtures(plugin_name, plugin, plugin_args)
    )
    @pytest.mark.skipif(sys.platform != "linux", reason="Linux only for faster results")
    def test_plugin_generate(test_plugin: Plugin) -> None:
        X = pd.DataFrame(load_iris()["data"])
>       test_plugin.fit(GenericDataLoader(X))

plugins/privacy/test_decaf.py:110:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pydantic/decorator.py:40: in pydantic.decorator.validate_arguments.validate.wrapper_function
    ???
pydantic/decorator.py:134: in pydantic.decorator.ValidatedFunction.call
    ???
pydantic/decorator.py:206: in pydantic.decorator.ValidatedFunction.execute
    ???
/tmp/eb-01mfc9ba/tmpouwj1neq/lib/python3.10/site-packages/synthcity/plugins/core/plugin.py:256: in fit
    output = self._fit(X, *args, **kwargs)
/tmp/eb-01mfc9ba/tmpouwj1neq/lib/python3.10/site-packages/synthcity/plugins/privacy/plugin_decaf.py:432: in _fit
    trainer = pl.Trainer(
/project/def-maintainers/boegelbot/rocky9/zen3/software/PyTorch-Lightning/1.8.4-foss-2022b/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py:340: in insert_env_defaults
    return fn(self, **kwargs)
/project/def-maintainers/boegelbot/rocky9/zen3/software/PyTorch-Lightning/1.8.4-foss-2022b/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py:414: in __init__
    self._accelerator_connector = AcceleratorConnector(
/project/def-maintainers/boegelbot/rocky9/zen3/software/PyTorch-Lightning/1.8.4-foss-2022b/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:211: in __init__
    self.cluster_environment: ClusterEnvironment = self._choose_and_init_cluster_environment()
/project/def-maintainers/boegelbot/rocky9/zen3/software/PyTorch-Lightning/1.8.4-foss-2022b/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:566: in _choose_and_init_cluster_environment
    return env_type()
/project/def-maintainers/boegelbot/rocky9/zen3/software/PyTorch-Lightning/1.8.4-foss-2022b/lib/python3.10/site-packages/lightning_lite/plugins/environments/slurm.py:49: in __init__
    self._validate_srun_variables()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    @staticmethod
    def _validate_srun_variables() -> None:
        """Checks for conflicting or incorrectly set variables set through `srun` and raises a useful error
        message.

        Right now, we only check for the most common user errors. See `the srun docs
        <https://slurm.schedmd.com/srun.html>`_ for a complete list of supported srun variables.
        """
        ntasks = int(os.environ.get("SLURM_NTASKS", "1"))
        if ntasks > 1 and "SLURM_NTASKS_PER_NODE" not in os.environ:
>           raise RuntimeError(
                f"You set `--ntasks={ntasks}` in your SLURM bash script, but this variable is not supported."
                f" HINT: Use `--ntasks-per-node={ntasks}` instead."
            )
E           RuntimeError: You set `--ntasks=8` in your SLURM bash script, but this variable is not supported. HINT: Use `--ntasks-per-node=8` instead.
```

Other 3 failures are basically exactly the same...

It seems like this is caused by the bot using `sbatch --ntasks=...`, should be using `--ntasks-per-node` instead according to the synthcity tests?

2024-10-18 09:42 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-10-21 08:51 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-10-24 06:39 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-11-15 13:03 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 15 out of 15 (15 easyconfigs in total)
node3143.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/63b8d29ba3685f1f0165f3fbbe39589b for a full test report.

2024-11-15 15:25 UTC, boegel submitted a review, later dismissed

2024-11-16 10:42 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 14 out of 15 (15 easyconfigs in total)
node3124.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/68bbb9778f6950e2b62a111cb3e373cc for a full test report.

2024-11-16 14:06 UTC, boegel approved these changes
lgtm

2025-01-07 08:21 UTC, boegel commented
Going in, thanks @pavelToman!

2025-01-07 08:21 UTC, merged