{math}[intel/2023b] MUMPS v5.7.2 w/ metis
easybuilders/easybuild-easyconfigs pull request #21160
Opened 2024-08-09 08:30 UTC by SimonPinches

(created using `eb --new-pr`)

2025-06-16 11:27 UTC, sassy-crick commented
@SimonPinches 
You might want to sync your PR with development, something like this: 
```
eb --sync-pr-with-develop NUMBER_OF_PR
```

2025-06-17 16:50 UTC, sassy-crick commented
@boegelbot please test @ jsc-zen3

2025-06-24 09:24 UTC, boegel requested changes

2025-06-24 09:24 UTC, boegel commented on easybuild/easyconfigs/m/MUMPS/MUMPS-5.7.2-intel-2023b-metis.eb
> +homepage = 'https://graal.ens-lyon.fr/MUMPS/'
```suggestion
homepage = 'https://mumps-solver.org'

2025-06-24 09:24 UTC, boegel commented on easybuild/easyconfigs/m/MUMPS/MUMPS-5.7.2-intel-2023b-metis.eb
> +source_urls = ['http://mumps-solver.org/']
```suggestion
source_urls = [
    'https://mumps-solver.org',
    'https://ftp.mcs.anl.gov/pub/petsc/externalpackages',  # mirror
]

2025-06-24 11:06 UTC, boegel approved these changes
lgtm

2025-06-24 11:22 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3501.doduo.os - Linux RHEL 9.4, x86_64, AMD EPYC 7552 48-Core Processor (zen2), Python 3.9.18
See https://gist.github.com/boegel/80038c49c6ab5d0c2b82a28df6754a1f for a full test report.

2025-06-24 11:24 UTC, boegel commented
Going in, thanks @SimonPinches!

2025-06-25 09:14 UTC, merged