{bio}[foss/2023a] dictys v1.1.0 w/ CUDA 12.1.1
easybuilders/easybuild-easyconfigs pull request #21166
Opened 2024-08-10 12:12 UTC by pavelToman

(created using `eb --new-pr`)

2024-08-10 12:15 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-08-10 12:58 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-08-10 14:08 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-08-10 14:42 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-08-13 14:03 UTC, boegel commented on easybuild/easyconfigs/d/dictys/dictys-1.1.0-foss-2023a-CUDA-12.1.1.eb
> +    ('junos-eznc', '2.7.0', {
@pavelToman As discussed, let's add a standalone easyconfig for `junos-eznc`, and use the latest version (2.7.1) in which we install their `paramiko` fork as an extra extension, and remove the `pip install` command from their `setup.py`.

I've also opened an issue upstream on this, see https://github.com/Juniper/py-junos-eznc/issues/1318

2024-08-13 14:06 UTC, boegel commented
Just so we have a trace for this: an earlier revision of this PR, in which `junos-eznc` 2.7.1 was used, resulted in having `paramiko` being added to the `Python/3.11.3-GCCcore-12.3.0` installation, which in the end leads to failing `pip check` runs with errors like:
```
== 2024-08-13 10:11:49,714 easyblock.py:4292 WARNING build failed (first 300 chars): `/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pip check` failed:
paramiko 3.4.0 requires bcrypt, which is not installed.
```

2024-08-13 14:15 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-08-13 15:22 UTC, boegel requested changes

2024-08-13 15:22 UTC, boegel commented on easybuild/easyconfigs/j/junos-eznc/junos-eznc-2.7.1-GCCcore-12.3.0.eb
> +        'preinstallopts': "sed -i '6d' setup.py && ",
@pavelToman I would make this a bit more explicit to make it clear that we're deleting the line in which `pip install` is used (also to make sure that this line is still removed later if it moves to a different line number):
```suggestion
        'preinstallopts': "sed -i '/pip install/d' setup.py && ",
```

2024-08-13 15:28 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-08-14 08:03 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-08-14 09:16 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-08-20 13:58 UTC, boegel approved these changes
lgtm

2024-08-20 15:04 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3304.joltik.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz, 1 x NVIDIA Tesla V100-SXM2-32GB, 545.23.08, Python 3.6.8
See https://gist.github.com/boegel/3d148718e044a17fb717002dec75f6cc for a full test report.

2024-08-21 05:52 UTC, boegel commented
Going in, thanks @pavelToman!

2024-08-21 05:52 UTC, merged