{tools}[GCCcore/12.3.0] Rasqal v0.9.33, gtk-doc v1.34.0, Pygments v2.18.0, ...
easybuilders/easybuild-easyconfigs pull request #21207
Opened 2024-08-20 09:33 UTC by PetrKralCZ

(created using `eb --new-pr`)

2024-08-20 12:38 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-08-20 12:53 UTC, boegel commented
@PetrKralCZ Some missing (build) dependencies for `gtk-doc`?
```
Found pkg-config: /usr/bin/pkg-config (1.4.2)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency glib-2.0 found: NO (tried pkgconfig)

../gtk-doc-1.34.0/tests/meson.build:31:11: ERROR: Dependency "glib-2.0" not found, tried pkgconfig
```

2024-08-20 13:18 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-08-20 13:27 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3

2024-08-21 09:56 UTC, boegel requested changes

2024-08-21 09:56 UTC, boegel commented on easybuild/easyconfigs/r/Raptor/Raptor-2.0.16-GCCcore-12.3.0.eb
> +    ('binutils',   '2.40'),
Existing easyconfig for `Raptor` has a recent version of `make` as build dependency, we should keep it (it's likely that older versions of `make` won't work, and `make-4.4.1-GCCcore-12.3.0.eb` is available already anyway)

```suggestion
    ('binutils',   '2.40'),
    ('make',   '4.4.1'),

2024-08-21 09:56 UTC, boegel commented
@boegelbot please test @ generoso

2024-08-21 09:58 UTC, boegel approved these changes

2024-08-21 10:01 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-08-21 10:22 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2024-08-21 10:28 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/7d038c92b0a2f9adbc79007ad33b6e7e for a full test report.

2024-08-21 10:38 UTC, boegel commented
Going in, thanks @PetrKralCZ!

2024-08-21 10:38 UTC, merged