{data,lib,math}[GCC/12.3.0,GCCcore/12.3.0,foss/2023a] PEcAn v1.7.2.9000, Redland v1.0.17, unixODBC v2.3.12 w/ R 4.3.2
easybuilders/easybuild-easyconfigs pull request #21227
Opened 2024-08-21 10:55 UTC by PetrKralCZ

(created using `eb --new-pr`)

2024-08-21 12:51 UTC, boegel requested changes

2024-08-21 12:51 UTC, boegel commented on easybuild/easyconfigs/p/PEcAn/PEcAn-1.7.2.9000-foss-2023a-R-4.3.2.eb
> +        'preinstallopts': "sed -i '%s' src/duckdb/third_party/re2/re2/prog.cc && " % local_sed_patterns_duckdb,
@PetrKralCZ Why not use a patch file here? (see https://patch-diff.githubusercontent.com/raw/duckdb/duckdb/pull/12344.diff)

2024-08-21 16:13 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-08-21 17:13 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3

2024-08-22 06:37 UTC, boegel commented on easybuild/easyconfigs/p/PEcAn/PEcAn-1.7.2.9000-foss-2023a-R-4.3.2.eb
> +        'preinstallopts': "sed -i '%s' src/duckdb/third_party/re2/re2/prog.cc && " % local_sed_patterns_duckdb,
fixed in bed9e08

2024-08-22 15:24 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/96e69ec74e4e5cebfe5cd9d74f69f0de for a full test report.

2024-08-26 08:54 UTC, boegel approved these changes
lgtm

2024-08-26 08:54 UTC, boegel commented
Going in, thanks @PetrKralCZ!

2024-08-26 08:54 UTC, merged