{tools}[foss/2023a] nanoQC v0.9.4
easybuilders/easybuild-easyconfigs pull request #21371
Opened 2024-09-11 07:51 UTC by PetrKralCZ

(created using `eb --new-pr`)

2024-09-11 08:16 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-09-11 08:22 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3

2024-09-11 14:18 UTC, boegel approved these changes
lgtm

2024-09-11 14:19 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3116.skitty.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/boegel/dc5d1905abd3347e0e61bbf0cf72eaac for a full test report.

2024-09-12 16:36 UTC, verdurin requested changes

2024-09-12 16:36 UTC, verdurin commented on easybuild/easyconfigs/n/nanoQC/nanoQC-0.9.4-foss-2023a.eb
> +moduleclass = 'tools'
Shouldn't this be `bio`?

2024-09-13 09:30 UTC, verdurin commented on easybuild/easyconfigs/n/nanoQC/nanoQC-0.9.4-foss-2023a.eb
> +moduleclass = 'tools'
Thanks.

2024-09-13 09:31 UTC, verdurin approved these changes

2024-09-13 09:40 UTC, verdurin commented
Going in, thanks @PetrKralCZ!

2024-09-13 09:40 UTC, merged