{phys}[foss/2023b] FDS v6.9.1
easybuilders/easybuild-easyconfigs pull request #21495
Opened 2024-09-30 05:22 UTC by akesandgren

(created using `eb --new-pr`)

2024-09-30 05:31 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-an02.hpc2n.umu.se - Linux Ubuntu 20.04, x86_64, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Python 3.8.10
See https://gist.github.com/akesandgren/b7add08ee4195cc96c1198ab8189e21d for a full test report.

2025-01-21 17:34 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2025-01-21 17:38 UTC, boegel requested changes

2025-01-21 17:38 UTC, boegel commented on easybuild/easyconfigs/f/FDS/FDS-6.9.1-foss-2023b.eb
> +    "fds -v",
existing easyconfigs for FDS 6.9.1 use:
```suggestion
    "fds 2>&1 | grep 'MPI version'",
```

2025-01-21 17:41 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3107.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/faa3f31bfbe3f23cdfa8c91a655df802 for a full test report.

2025-01-22 08:29 UTC, boegel approved these changes

2025-01-22 12:19 UTC, boegel commented
Going in, thanks @akesandgren!

2025-01-22 12:19 UTC, merged