{phys,vis}[gfbf/2023b,iimkl/2023b] CHERAB v1.5.0, Raysect v0.8.1.post1
easybuilders/easybuild-easyconfigs pull request #21501
Opened 2024-09-30 12:16 UTC by SimonPinches

(created using `eb --new-pr`)

2024-10-13 14:03 UTC, SimonPinches commented
Depends upon PR #20262

2024-11-06 13:44 UTC, Louwrensth commented
@boegelbot please test @ generoso
EB_ARGS="--from-pr 20262"

2026-04-08 10:39 UTC, akesandgren requested changes

2026-04-08 10:39 UTC, akesandgren commented on easybuild/easyconfigs/c/CHERAB/CHERAB-1.5.0-iimkl-2023b.eb
> +    ('SciPy-bundle', '2023.12'),
Should be 2023.11 for the 2023b toolchain, please fix

2026-04-08 10:39 UTC, akesandgren commented on easybuild/easyconfigs/c/CHERAB/CHERAB-1.5.0-iimkl-2023b.eb
> +    ('matplotlib', '3.8.2'),
There is no matplotlib for iimkkl/2023b so you need to provide that one in this PR too

2026-04-08 10:39 UTC, akesandgren commented on easybuild/easyconfigs/r/Raysect/Raysect-0.8.1.post1-iimkl-2023b.eb
> +    ('SciPy-bundle', '2023.12'),
Use 2023.11 for 2023b toolchain

2026-04-08 10:39 UTC, akesandgren commented on easybuild/easyconfigs/r/Raysect/Raysect-0.8.1.post1-iimkl-2023b.eb
> +    ('matplotlib', '3.8.2'),
And again, there is no matplotlib for iimkl/2023b so that needs to be provided

2026-04-08 10:39 UTC, akesandgren commented on easybuild/easyconfigs/r/Raysect/Raysect-0.8.1.post1-iimkl-2023b.eb
> +sanity_pip_check = True
Drop these since they are the default

2026-04-08 10:39 UTC, akesandgren commented on easybuild/easyconfigs/r/Raysect/Raysect-0.8.1.post1-gfbf-2023b.eb
> +sanity_pip_check = True
Drop these since they are the default

2026-04-08 10:39 UTC, akesandgren commented on easybuild/easyconfigs/c/CHERAB/CHERAB-1.5.0-iimkl-2023b.eb
> +sanity_pip_check = True
Drop these since they are the default

2026-04-08 10:39 UTC, akesandgren commented on easybuild/easyconfigs/c/CHERAB/CHERAB-1.5.0-gfbf-2023b.eb
> +sanity_pip_check = True
Drop these since they are the default

2026-04-27 13:24 UTC, verdurin commented
Test report by @verdurin
**FAILED**
Build succeeded for 6 out of 9 (total: 1 hour 40 mins 6 secs) (5 easyconfigs in total)
centos-stream-9 - Linux CentOS Stream 9, x86_64, Intel Core Processor (Skylake, IBRS), Python 3.12.12
See https://gist.github.com/verdurin/194356db932b67294dd3b423ac0d19dd for a full test report.

2026-04-27 13:27 UTC, verdurin commented
This is the error in my test build, for `matplotlib`:
```
== 2026-04-27 14:24:25,117 python.py:344 INFO Found 0 missing names and 1 missing versions out of 5 packages
== 2026-04-27 14:24:25,184 build_log.py:233 ERROR EasyBuild encountered an error:
The following Python packages were likely specified with a wrong version because they have another version in the 'pip list' output:
kiwisolver 1.4.5 (version in 'pip list' output: 1.4.4) (at easybuild/easyblocks/p/python.py:360 in run_pip_list)
Callstack:
        easybuild/easyblocks/p/python.py:360 in run_pip_list
        easybuild/easyblocks/generic/pythonbundle.py:249 in _sanity_check_step_extensions
        easybuild/framework/easyblock.py:4442 in _sanity_check_step
        easybuild/framework/easyblock.py:3450 in _dispatch_sanity_check_step
        easybuild/framework/easyblock.py:3462 in sanity_check_step
        easybuild/easyblocks/generic/bundle.py:487 in sanity_check_step
        easybuild/easyblocks/generic/pythonbundle.py:208 in sanity_check_step
        easybuild/framework/easyblock.py:4830 in run_step
        easybuild/framework/easyblock.py:4989 in run_all_steps
        easybuild/framework/easyblock.py:5177 in build_and_install_one
        easybuild/main.py:184 in build_and_install_software
        easybuild/main.py:630 in process_eb_args
        easybuild/main.py:814 in main
        easybuild/main.py:872 in main_with_hooks
        easybuild/main.py:891 in <module>
```

2026-08-12 11:40 UTC, SimonPinches commented
@akesandgren and @verdurin, apologies for the delay, but I think all comments are now addressed :-)
Please can you test / review again?  Thanks!

2026-08-13 05:44 UTC, akesandgren commented
Test report by @akesandgren
**FAILED**
Build succeeded for 2 out of 6 (total: 5 mins 15 secs) (5 easyconfigs in total)
b-cn1611.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 580.159.03, Python 3.10.12
See https://gist.github.com/akesandgren/06f8ba1df4546eb0ee9dae8f982644db for a full test report.


Fails to build SciPy-bundle for intel for some reason, also fails on Intel HW

2026-08-13 11:04 UTC, SimonPinches commented
> Test report by @akesandgren **FAILED** Build succeeded for 2 out of 6 (total: 5 mins 15 secs) (5 easyconfigs in total) b-cn1611.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 580.159.03, Python 3.10.12 See https://gist.github.com/akesandgren/06f8ba1df4546eb0ee9dae8f982644db for a full test report.
> 
> Fails to build SciPy-bundle for intel for some reason, also fails on Intel HW

@akesandgren, I cannot reproduce your SciPy-bundle failure with the released version in EasyBuild version 5.3.1.  Are you using an older version of the framework/easyblocks?

2026-08-13 11:31 UTC, akesandgren commented
I tried with 5.4.0 (develop)

2026-08-16 22:33 UTC, SimonPinches commented
> I tried with 5.4.0 (develop)

I've just tested and it works for me with 5.4.0 - takes about 30mins including scipy's test suite.  Can you update your develop checkouts or use the actual 5.4.0 release?

2026-08-18 06:44 UTC, akesandgren commented
Meh, I had an old version of the SciPy-bundle-2023.11-iimkl-2023b.eb easyconfig in my own tree which was causing problems... Looks better now. Test report coming up once SciPy is built

2026-08-18 07:23 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 5 out of 5 (total: 11 mins 59 secs) (5 easyconfigs in total)
b-cn1611.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 580.173.02, Python 3.10.12
See https://gist.github.com/akesandgren/61b0ba58aa697fa8d9e925d4a5133c44 for a full test report.

2026-08-18 07:25 UTC, akesandgren approved these changes
LGTM

2026-08-18 09:39 UTC, akesandgren commented
Going in, thanks @SimonPinches!

2026-08-18 09:39 UTC, merged

2026-08-19 09:48 UTC, SimonPinches commented
Thanks @akesandgren 😃