update Levenshtein
easybuilders/easybuild-easyconfigs pull request #21515
Opened 2024-10-01 22:23 UTC by fizwit

(created using `eb --new-pr`)

2024-10-02 12:28 UTC, Micket commented
Like i have mentioned many times in the past, please don't put in non-standard names for the titles of PRs when opening simple new/updates PRs.
https://github.com/easybuilders/easybuild-easyconfigs/pull/20251#issuecomment-2027765156

I'm really not sure why you insist on ignoring this simple request. You are just making the maintainer do a bunch of extra work

2025-06-16 08:50 UTC, sassy-crick commented
@fizwit You might want to sync your PR with development, something like this: 
```
eb --sync-pr-with-develop NUMBER_OF_PR
```

2025-07-02 13:11 UTC, Crivella requested changes
These variable are now True by default and will now cause the CI to fail if present in an EC and not False

2025-07-02 13:11 UTC, Crivella commented on easybuild/easyconfigs/l/Levenshtein/Levenshtein-0.25.1-GCCcore-13.2.0.eb
> +exts_list = [
```suggestion
]

exts_list = [
```

2025-07-02 13:11 UTC, Crivella commented on easybuild/easyconfigs/l/Levenshtein/Levenshtein-0.25.1-GCCcore-13.2.0.eb
> +moduleclass = 'data'
```suggestion
]

moduleclass = 'data'
```

2025-07-02 13:42 UTC, Crivella commented
@boegelbot please test @ jsc-zen3

2025-07-02 13:45 UTC, Crivella commented
Test report by @Crivella
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
crivella-desktop - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 13th Gen Intel(R) Core(TM) i9-13900K (skylake), Python 3.11.13
See https://gist.github.com/Crivella/011d60b1df918bebc00104a2156f2d24 for a full test report.

2025-07-02 13:56 UTC, Crivella approved these changes
LGTM

2025-07-02 13:57 UTC, Crivella commented
Going in, thanks @fizwit!

2025-07-02 13:57 UTC, merged