{lib}[gompi/2024a] mpi4py v4.0.0
easybuilders/easybuild-easyconfigs pull request #21563
Opened 2024-10-05 17:46 UTC by maxim-masterov

(created using `eb --new-pr`)

2024-10-07 07:42 UTC, smoors commented on easybuild/easyconfigs/m/mpi4py/mpi4py-4.0.0-gompi-2024a.eb
> +    ('Cython', '3.0.10'),
Cython should be a build dependency

2024-10-07 07:43 UTC, smoors requested changes
please set Cython as builddep?

2024-10-07 07:47 UTC, maxim-masterov commented on easybuild/easyconfigs/m/mpi4py/mpi4py-4.0.0-gompi-2024a.eb
> +    ('Cython', '3.0.10'),
done

2024-10-08 07:26 UTC, maxim-masterov commented
> please set Cython as builddep?

done

2024-10-18 10:53 UTC, maxim-masterov commented
Test report by @maxim-masterov
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 9.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.9.18
See https://gist.github.com/maxim-masterov/0ddd41e2db2229fae9e99232f59256c3 for a full test report.

2024-10-18 13:04 UTC, maxim-masterov commented
@smoors can we go ahead with this one? mpi4py is used as a dependency in some other PRs.

2024-10-18 18:22 UTC, smoors commented
@maxim-masterov apparently `mpi4py` v4.0.1 has already been merged  a few days ago.
can you use that version instead?

2024-10-21 16:15 UTC, maxim-masterov commented
@smoors ah, I missed it. I updated the relevant PRs to v4.0.1.

2024-10-21 16:15 UTC, closed without merging