{bio}[foss/2023a] poppunk v2.6.7
easybuilders/easybuild-easyconfigs pull request #21599
Opened 2024-10-09 11:02 UTC by verdurin

(created using `eb --new-pr`)

2024-10-09 11:06 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/9f29cfe87fedbfaf0598243040e4a0d4 for a full test report.

2024-10-09 12:06 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/55e5e08b87897bd8d130acea541f07d7 for a full test report.

2024-10-09 15:29 UTC, verdurin commented
Test report by @verdurin
**SUCCESS**
Build succeeded for 5 out of 5 (4 easyconfigs in total)
easybuild-el8.cloud.in.bmrc.ox.ac.uk - Linux Rocky Linux 8.10, x86_64, Intel Xeon Processor (Skylake, IBRS), Python 3.6.8
See https://gist.github.com/verdurin/6da6ec76954cbfc98141e180e309155f for a full test report.

2025-07-02 13:08 UTC, Crivella commented
The only problem with the conflict seems to be the withespaces at the end of the lines in the description

2025-07-03 15:53 UTC, Crivella requested changes
Fixes for CI

2025-07-03 15:53 UTC, Crivella commented on easybuild/easyconfigs/p/poppunk/poppunk-2.6.7-foss-2023a.eb
> +We refer to subclusters of strains as lineages."""
```suggestion
homepage = 'https://poppunk.readthedocs.io'
description = """PopPUNK is a tool for clustering genomes.
We refer to the clusters as variable-length-k-mer clusters, or VLKCs.
Biologically, these clusters typically represent distinct strains.
We refer to subclusters of strains as lineages."""
```

2025-07-03 15:53 UTC, Crivella commented on easybuild/easyconfigs/m/mandrake/mandrake-1.2.2-foss-2023a.eb
> +exts_list = [
```suggestion
]

exts_list = [
```

2025-07-03 15:53 UTC, Crivella commented on easybuild/easyconfigs/p/poppunk/poppunk-2.6.7-foss-2023a.eb
> +exts_list = [
```suggestion
]

exts_list = [
```

2025-07-03 15:53 UTC, Crivella commented on easybuild/easyconfigs/p/pp-sketchlib/pp-sketchlib-2.1.1-foss-2023a.eb
> +exts_list = [
```suggestion
]

exts_list = [
```

2025-07-03 15:53 UTC, Crivella commented on easybuild/easyconfigs/m/mandrake/mandrake-1.2.2-foss-2023a.eb
> +description = """Fast visualisation of the population structure of pathogens
```suggestion
description = """Fast visualisation of the population structure of pathogens
```

2025-07-03 15:55 UTC, Crivella commented
@boegelbot please test @ jsc-zen3

2025-07-03 16:13 UTC, Crivella approved these changes
LGTM

2025-07-03 16:14 UTC, Crivella commented
Going in, thanks @verdurin!

2025-07-03 16:14 UTC, merged