{chem}[foss/2023a] Solids4foam v2.1
easybuilders/easybuild-easyconfigs pull request #21606
Opened 2024-10-09 15:06 UTC by pavelToman

(created using `eb --new-pr`)

2024-10-09 15:07 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-10-10 08:25 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-10-10 09:04 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-10-10 09:28 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-10-10 10:12 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-10-10 15:35 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-10-11 08:49 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-10-11 13:13 UTC, boegel requested changes

2024-10-11 13:13 UTC, boegel commented on easybuild/easyconfigs/s/Solids4foam/Solids4foam-2.1-foss-2023a.eb
> +install_cmd += ' && cp -av tutorials %(installdir)s'
@pavelToman This tells me that we could actually be using `MakeCp` here, and customize the build command via `build_cmd`:

```python
easyblock = 'MakeCp'

...
prebuildopts = "source $FOAM_BASH && "
...
build_cmd = './Allwmake'

files_to_copy = [...]
```

That way, the `-j %(parallel)s` is not required (will be added automatically I think), and the `extract_sources = True` can be dropped too.

2024-10-15 13:00 UTC, boegel commented on easybuild/easyconfigs/s/Solids4foam/Solids4foam-2.1-foss-2023a.eb
> +install_cmd += ' && cp -av tutorials %(installdir)s'
I overlooked that the `Allwmake` already installs stuff in the installation directory that is specified via `$WM_PROJECT_USER_DIR` & co, so with that in mind `MakeCp` is even worse, so don't use that :)

Add a comment abovevthe `install_cmd` though to highlight that the `Allwmake` command doesn't only build stuff, but also installs stuff, and then we can proceed like this as is

2024-10-16 14:50 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-10-17 10:02 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-10-28 09:31 UTC, laraPPr commented
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4013.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.11.3
See https://gist.github.com/laraPPr/f0da2d54bda6998e6cf9ce75ef28884e for a full test report.

2024-10-28 10:05 UTC, laraPPr commented
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3163.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.11.3
See https://gist.github.com/laraPPr/7de82e7afd3ff521ed5bc5419cf86125 for a full test report.

2024-10-28 10:07 UTC, laraPPr approved these changes
lgtm

2024-10-28 10:08 UTC, laraPPr commented
Going in, thanks @pavelToman!

2024-10-28 10:08 UTC, merged