{compiler}[SYSTEM,GCCcore/13.3.0] LLVM 19.1.1
easybuilders/easybuild-easyconfigs pull request #21611
Opened 2024-10-10 09:43 UTC by Crivella

Adds EC for LLVM:

- 19.1.1  SYSTEM
- 19.1.1  GCCcore-13.3.0

Depends on:

- https://github.com/easybuilders/easybuild-easyblocks/pull/3373

WIP:

- Pin correct number of errors that have been reduced from 18.1.8
  - Need to fix `libomptarget` false error due to missing `-fopenmp` in test-suite

2024-10-15 09:34 UTC, Crivella commented
Probelm with having system `libffi`:

- If the system compiler is too old it can lead to errors of the type

  <details>

    ```
    ld.lld: error: relocation R_X86_64_32S cannot be used against symbol 'ffi_closure_win64'; recompile with -fPIC
    >>> defined in /home/dgrassano/.local/easybuild/software/libffi/3.4.5/lib64/libffi.a(win64.o)
    >>> referenced by ffiw64.c
    >>>               ffiw64.o:(ffi_prep_closure_loc_efi64) in archive /home/dgrassano/.local/easybuild/software/libffi/3.4.5/lib64/libffi.a
    ````
  </details>

  even if the library is compiled with `-fPIC`

Anyway the library as compiled with GCC does not have any GCC deps and is statically linked so it should not be a problem.

2025-03-04 22:02 UTC, boegel commented
@boegelbot please test @ jsc-zen3
CORE_CNT=16
EB_BRANCH=5.0.x
EB_ARGS="--installpath /tmp/$USER/pr21611

2025-03-05 07:30 UTC, boegel requested changes

2025-03-05 07:30 UTC, boegel commented on easybuild/easyconfigs/l/LLVM/LLVM-19.1.1-GCCcore-13.3.0-minimal.eb
> +}
`pic` toolchain option is no longer supported in EasyBuild 5.x when using `system` toolchain, since it wasn't actually doing anything, see also https://github.com/easybuilders/easybuild-framework/pull/4585

```suggestion
```

2025-03-05 07:31 UTC, boegel commented
@boegelbot please test @ jsc-zen3
CORE_CNT=16
EB_BRANCH=5.0.x
EB_ARGS="--installpath /tmp/$USER/pr21833 --include-easyblocks-from-pr 3373"

2025-03-05 17:22 UTC, boegel commented
@boegelbot please test @ jsc-zen3
CORE_CNT=16
EB_BRANCH=5.0.x
EB_ARGS="--installpath /tmp/$USER/pr21833 --include-easyblocks-from-pr 3373"

2025-03-11 09:05 UTC, Thyre commented
Do we want to switch to LLVM 19.1.7 as the last patch release for LLVM 19? Most of our LLVM / Clang EasyConfigs use the last patch release.

2025-03-11 09:07 UTC, Crivella commented
> Do we want to switch to LLVM 19.1.7 as the last patch release for LLVM 19? Most of our LLVM / Clang EasyConfigs use the last patch release.

I can open another PR with those, had been testing them for the LLVM toolchain anyway

2025-03-30 16:24 UTC, Thyre commented
Test report by @Thyre
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3675
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
ZAM054 - Linux Zorin OS 17, x86_64, 12th Gen Intel(R) Core(TM) i7-1260P, 1 x NVIDIA NVIDIA GeForce MX550, 565.57.01, Python 3.10.12
See https://gist.github.com/Thyre/ded5bdb0baf0a3ea21e0c8c74ad3afb9 for a full test report.

2025-03-31 15:35 UTC, Thyre commented
@boegelbot please test @ jsc-zen3
CORE_CNT=16
EB_ARGS="--installpath /tmp/$USER/pr21611 --include-easyblocks-from-pr 3675"

2025-03-31 17:11 UTC, Thyre commented
Test report by @Thyre
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3675
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
ZAM054 - Linux Zorin OS 17, x86_64, 12th Gen Intel(R) Core(TM) i7-1260P, 1 x NVIDIA NVIDIA GeForce MX550, 565.57.01, Python 3.10.12
See https://gist.github.com/Thyre/ff482b63f66cf4d1320df0ebae3fa6ce for a full test report.

2025-03-31 18:18 UTC, Thyre commented
> Test report by @Thyre Using easyblocks from PR(s) [easybuilders/easybuild-easyblocks#3675](https://github.com/easybuilders/easybuild-easyblocks/pull/3675) **FAILED** Build succeeded for 0 out of 1 (1 easyconfigs in total) ZAM054 - Linux Zorin OS 17, x86_64, 12th Gen Intel(R) Core(TM) i7-1260P, 1 x NVIDIA NVIDIA GeForce MX550, 565.57.01, Python 3.10.12 See https://gist.github.com/Thyre/ff482b63f66cf4d1320df0ebae3fa6ce for a full test report.

Hm, looks like it hit the stray commands from https://github.com/llvm/llvm-project/pull/106837 (see https://github.com/llvm/llvm-project/pull/92581), though this means that the build would've failed anyways due to an error.

2025-03-31 18:45 UTC, Thyre commented
> Hm, looks like it hit the stray commands from [llvm/llvm-project#106837](https://github.com/llvm/llvm-project/pull/106837) (see [llvm/llvm-project#92581](https://github.com/llvm/llvm-project/pull/92581)), though this means that the build would've failed anyways due to an error.
> 
> It would've triggered `"Unknown GPU architecture '${gpu_arch}'"` (see https://github.com/llvm/llvm-project/blob/d401987fe349a87c53fe25829215b080b70c0c1a/offload/DeviceRTL/CMakeLists.txt#L292C6-L292C69)

Well this is annoying. It failed due to the string quotations: `Unknown architecture '"sm_75"'. We can probably skip the additional quoting now that they're already in quotation marks. I'll update https://github.com/easybuilders/easybuild-easyblocks/pull/3675.

2025-03-31 22:17 UTC, Thyre commented
Test report by @Thyre
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3675
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
ZAM054 - Linux Zorin OS 17, x86_64, 12th Gen Intel(R) Core(TM) i7-1260P, 1 x NVIDIA NVIDIA GeForce MX550, 565.57.01, Python 3.10.12
See https://gist.github.com/Thyre/244d80e116b4781cf9fedf8db0105b40 for a full test report.

2025-04-01 04:35 UTC, Thyre commented
Offload tests fail with: 
```
# ----command stderr----------
# | clang: error: cannot find libdevice for sm_75; provide path
to different CUDA installation via '--cuda-path', or pass '-no cudalib' to build without linking with libdevice 
#
# error: command failed with exit status: 1
```

I don't have CUDA on a system level, so I would need to have a CUDA module loaded. Maybe we should allow these tests to fail if CUDA is not loaded (similar thing for AMD GPUs)

2025-04-01 08:56 UTC, Thyre commented
> > Offload tests fail with:
> 
> Weird when i did try some 'all' builds i remember the NVIDIA/ROCm tests being disabled automatically if the required executables where not found. For some reason here they are not? (Either they changed their logic or there is something configuration-wise going on)

I do have NVIDIA drivers present, maybe this influences the results in some way. Nonetheless, it's probably a good idea to ignore these tests when we know that they will fail.

2025-04-01 09:02 UTC, Crivella commented
> > > Offload tests fail with:
> > 
> > 
> > Weird when i did try some 'all' builds i remember the NVIDIA/ROCm tests being disabled automatically if the required executables where not found. For some reason here they are not? (Either they changed their logic or there is something configuration-wise going on)
> 
> I do have NVIDIA drivers present, maybe this influences the results in some way. Nonetheless, it's probably a good idea to ignore these tests when we know that they will fail.

The easiest is probably to do a check for the executables and add a generic NVIDIA/ROCm ignore pattern to the test suite in case they are missing

2025-04-01 09:09 UTC, Thyre commented
> The easiest is probably to do a check for the executables and add a generic NVIDIA/ROCm ignore pattern to the test suite in case they are missing

Yeah, I added this for `ptxas` already, and I'll check on an AMD GPU system to figure out what LLVM actually checks. The source code gave a few hints, but I'm not sure what is actually used at the end.

2025-04-02 14:33 UTC, Thyre commented
@boegelbot please test @ jsc-zen3
CORE_CNT=16
EB_ARGS="--installpath /tmp/$USER/pr21611 --include-easyblocks-from-pr 3675"

2025-04-04 09:34 UTC, Crivella commented
For the GH records, regarding https://github.com/easybuilders/easybuild-easyconfigs/pull/21611#issuecomment-2773434259, and the failure https://gist.github.com/boegelbot/be2bbd1d12a38b40b646fab9c2d891d0, this might be related to https://github.com/llvm/llvm-project/issues/130783.

We might have to do the build in a way that we can continue it manually afterwards if we manage to reproduce the error

2025-04-09 13:39 UTC, Crivella commented
@boegel  Done

2025-04-25 11:51 UTC, Thyre commented
Test report by @Thyre
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3675
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
ZAM054 - Linux Zorin OS 17, x86_64, 12th Gen Intel(R) Core(TM) i7-1260P, 1 x NVIDIA NVIDIA GeForce MX550, 565.57.01, Python 3.10.12
See https://gist.github.com/Thyre/dc64576430d2576f432c266f13cfb0e5 for a full test report.

2025-05-20 14:40 UTC, Crivella commented
Close this in favor of the now merged 

- #22889

with a newer LLVM version (within the same major release) for the same toolchain.

Will open a new PR (or rename+reopen this) if we need to add the SYSTEM variant

2025-05-20 14:40 UTC, closed without merging