stop using `--buildtype=release` in easyconfigs using `MesonNinja` easyblock
easybuilders/easybuild-easyconfigs pull request #21619
Opened 2024-10-10 16:14 UTC by Micket

Depends on 

- [x] #https://github.com/easybuilders/easybuild-easyblocks/pull/3454

2024-10-10 17:35 UTC, Micket commented
Test report by @Micket
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3454
**SUCCESS**
Build succeeded for 8 out of 8 (8 easyconfigs in total)
vera-skylake-build - Linux Rocky Linux 8.9, x86_64, Intel Xeon Processor (Skylake, IBRS, no TSX), Python 3.6.8
See https://gist.github.com/Micket/18087124489f6e00fd77d58b05983c3b for a full test report.

2024-10-11 14:59 UTC, jfgrimm commented
perhaps worth adding a CI check that catches new easyconfigs that use `--buildtype release` etc?

2024-10-14 09:24 UTC, jfgrimm submitted a review, later dismissed
lgtm

2024-10-14 09:27 UTC, boegel requested changes

2024-10-14 09:27 UTC, boegel commented on test/easyconfigs/easyconfigs.py
> +        if '--buildtype ' in configopts:
@Micket Should also consider `--buildtype=`?
```suggestion
        if '--buildtype ' in configopts or '--buildtype=' in configopts:

2024-10-15 12:13 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 58 out of 58 (58 easyconfigs in total)
node3508.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/boegel/dd87c0fa03817aa050c790792b06f310 for a full test report.

2024-10-15 13:21 UTC, boegel approved these changes

2024-10-15 13:25 UTC, boegel commented
Going in, thanks @Micket!

2024-10-15 13:25 UTC, merged