{numlib}[foss/2024a] PETSc v3.22.0, ParMETIS v4.0.3, SuperLU_DIST v9.0.0
easybuilders/easybuild-easyconfigs pull request #21697
Opened 2024-10-18 08:55 UTC by maxim-masterov

(created using `eb --new-pr`)

Note that ParMETIS was moved from [glaros.dtc.umn.edu](http://glaros.dtc.umn.edu) to GitHub. The former URL is not working anymore and the new GitHub repository contains no tags or releases (see [this issue](https://github.com/KarypisLab/ParMETIS/issues/27)). After some browsing, I found the versioned tarball among the static downloads for CP2K, so I'm using it to get the package. Let me know if you have a better idea about where to fetch it from.

<s>Depends on:
- mpi4py https://github.com/easybuilders/easybuild-easyconfigs/pull/21563</s>

2024-10-25 11:17 UTC, maxim-masterov commented
removed `SuiteSparse-7.8.2-foss-2024a-METIS-5.1.0.eb` because it was recently merged with https://github.com/easybuilders/easybuild-easyconfigs/pull/21417

2024-12-12 12:54 UTC, smoors commented
> Note that ParMETIS was moved from [glaros.dtc.umn.edu](http://glaros.dtc.umn.edu) to GitHub. The former URL is not working anymore and the new GitHub repository contains no tags or releases (see [this issue](https://github.com/KarypisLab/ParMETIS/issues/27)). After some browsing, I found the versioned tarball among the static downloads for CP2K, so I'm using it to get the package. Let me know if you have a better idea about where to fetch it from.

you could take the tarball from this commit, which is the initial import of v4.0.3:
https://github.com/KarypisLab/ParMETIS/commit/d90a2a6
https://github.com/KarypisLab/ParMETIS/archive/d90a2a6.tar.gz

i compared the contents with the original 4.0.3 tarball; the only important difference is that the commit does not contain the `metis` sources. This can be fixed by adding `METIS` as a dependency for `ParMETIS`, which is a cleaner approach in any case.

but the CP2K tarball has the same checksum as the original, so i'm not against just using that.

let us know what you decide?

2025-06-16 15:11 UTC, casparvl commented
@boegelbot please test @ jsc-zen3

2025-06-16 15:58 UTC, casparvl commented
Hmmm, local build failed with:
```
ERROR: Installation of PETSc-3.22.0-foss-2024a.eb failed: "Couldn't find file petsc-3.22.0.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /scratch-shared/casparl/eb-tcmmd5lm/files_pr21697/p/PETSc/p/PETSc/petsc-3.22.0.tar.gz, /scratch-shared/casparl/eb-tcmmd5lm/files_pr21697/p/PETSc/PETSc/petsc-3.22.0.tar.gz, /scratch-shared/casparl/eb-tcmmd5lm/files_pr21697/p/PETSc/petsc-3.22.0.tar.gz, /sw/eb/easyconfigs-surf/p/PETSc/petsc-3.22.0.tar.gz, /sw/eb/easyconfigs-surf/PETSc/petsc-3.22.0.tar.gz, /sw/eb/easyconfigs-surf/petsc-3.22.0.tar.gz, /sw/noarch/RHEL8/2023/software/EasyBuild/5.1.0/easybuild/easyconfigs/p/PETSc/petsc-3.22.0.tar.gz, /sw/noarch/RHEL8/2023/software/EasyBuild/5.1.0/easybuild/easyconfigs/PETSc/petsc-3.22.0.tar.gz, /sw/noarch/RHEL8/2023/software/EasyBuild/5.1.0/easybuild/easyconfigs/petsc-3.22.0.tar.gz, /scratch-shared/casparl/eb-tcmmd5lm/files_pr21697/p/PETSc/petsc-3.22.0.tar.gz, /scratch-shared/casparl/eb-tcmmd5lm/files_pr21697/PETSc/petsc-3.22.0.tar.gz, /scratch-shared/casparl/eb-tcmmd5lm/files_pr21697/petsc-3.22.0.tar.gz, /sw/noarch/RHEL8/2023/software/EasyBuild/5.1.0/easybuild/easyconfigs/p/PETSc/petsc-3.22.0.tar.gz, /sw/noarch/RHEL8/2023/software/EasyBuild/5.1.0/easybuild/easyconfigs/PETSc/petsc-3.22.0.tar.gz, /sw/noarch/RHEL8/2023/software/EasyBuild/5.1.0/easybuild/easyconfigs/petsc-3.22.0.tar.gz, /home/casparl/.local/easybuild/sources/p/PETSc/petsc-3.22.0.tar.gz, /home/casparl/.local/easybuild/sources/PETSc/petsc-3.22.0.tar.gz, /home/casparl/.local/easybuild/sources/petsc-3.22.0.tar.gz, https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-3.22.0.tar.gz, https://sources.easybuild.io/p/PETSc/petsc-3.22.0.tar.gz "
```

2025-06-17 09:00 UTC, casparvl commented
Weird, the link https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-3.22.0.tar.gz looks ok, and if I use `wget` it downloads successfully.

2025-06-19 11:29 UTC, casparvl commented
Test report by @casparvl
**FAILED**
Build succeeded for 6 out of 7 (7 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 9.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.9.18
See https://gist.github.com/casparvl/610cb19f8a00ba1943778b407c0cd76d for a full test report.

2025-06-19 17:47 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 7 out of 7 (7 easyconfigs in total)
tcn2.local.snellius.surf.nl - Linux RHEL 9.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.9.18
See https://gist.github.com/casparvl/49a813481342fb209fcb213765e66da3 for a full test report.

2025-06-23 13:26 UTC, smoors commented
```
FAIL: test_dep_versions_per_toolchain_generation (test.easyconfigs.easyconfigs.EasyConfigTest)
Check whether there's only one dependency version per toolchain generation actively used.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 1062, in test_dep_versions_per_toolchain_generation
    self.fail("Should not have multi-variant dependencies in easyconfigs:\n%s" % multi_dep_vars_msg)
AssertionError: Should not have multi-variant dependencies in easyconfigs:

found 2 variants of 'Hypre' dependency in easyconfigs using '2024a' toolchain generation
* version: 2.31.0; versionsuffix:  as dep for {'PETSc-3.22.0-foss-2024a.eb'}
* version: 2.32.0; versionsuffix:  as dep for {'FEBio-4.6-foss-2024a.eb'}

found 2 variants of 'MUMPS' dependency in easyconfigs using '2024a' toolchain generation
* version: 5.7.2; versionsuffix: -metis as dep for {'PuLP-2.8.0-foss-2024a.eb', 'Cgl-0.60.8-foss-2024a.eb', 'Clp-1.17.10-foss-2024a.eb', 'Cbc-2.10.12-foss-2024a.eb', 'snakemake-8.27.0-foss-2024a.eb'}
* version: 5.7.3; versionsuffix: -metis as dep for {'PETSc-3.22.0-foss-2024a.eb'}

found 2 variants of 'SCOTCH' dependency in easyconfigs using '2024a' toolchain generation
* version: 7.0.5; versionsuffix:  as dep for {'PETSc-3.22.0-foss-2024a.eb', 'MUMPS-5.7.3-foss-2024a-metis.eb'}
* version: 7.0.6; versionsuffix:  as dep for {'PuLP-2.8.0-foss-2024a.eb', 'FEBio-4.6-foss-2024a.eb', 'Mmg-5.8.0-gompi-2024a.eb', 'Cgl-0.60.8-foss-2024a.eb', 'Clp-1.17.10-foss-2024a.eb', 'Cbc-2.10.12-foss-2024a.eb', 'snakemake-8.27.0-foss-2024a.eb', 'MUMPS-5.7.2-foss-2024a-metis.eb'}

found 2 variants of 'SuiteSparse' dependency in easyconfigs using '2024a' toolchain generation
* version: 7.10.1; versionsuffix:  as dep for {'AUGUSTUS-3.5.0-foss-2024a.eb'}
* version: 7.8.2; versionsuffix:  as dep for {'PETSc-3.22.0-foss-2024a.eb'}
```

2025-06-23 14:04 UTC, casparvl commented
Ah, _that_ was causing the checks to fail, I was already surprised that a deprecation warning would cause a failure. I guess time has caught up with this PR :P I'll modify the versions, see if it still builds with the versions that are (by now) part of 2024a.

2025-06-23 14:08 UTC, casparvl commented
@boegelbot please test @ jsc-zen3

2025-06-23 16:45 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 7 out of 7 (3 easyconfigs in total)
tcn2.local.snellius.surf.nl - Linux RHEL 9.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.9.18
See https://gist.github.com/casparvl/3bb29d1be0b99b3b61e5f2d2686b700b for a full test report.

2025-06-23 18:16 UTC, casparvl commented
@smoors or @branfosj Since I made some final pushes to this PR, would either of you mind doing the final check & merge?

2025-07-31 08:20 UTC, boegel requested changes

2025-07-31 08:20 UTC, boegel commented on easybuild/easyconfigs/p/PETSc/PETSc-3.22.0-foss-2024a.eb
> +version = '3.22.0'
I realize this is an old PR, but I don't think we should be using a PETSc version that's older than what we're using in the `2023b` generation, see:
- #22696

@maxim-masterov @casparvl Can we bump this version to latest (3.23.5)?

2025-07-31 08:20 UTC, boegel commented on easybuild/easyconfigs/s/SuperLU_DIST/SuperLU_DIST-9.0.0-foss-2024a.eb
> +version = '9.0.0'
There's a `9.1.0` now, let's bump to that while we're also bumping the PETSc version?

2025-07-31 16:17 UTC, boegel commented on easybuild/easyconfigs/p/PETSc/PETSc-3.22.0-foss-2024a.eb
> +version = '3.22.0'
We should probably proceed with this PR instead:
- #23252

2025-08-01 12:06 UTC, maxim-masterov commented on easybuild/easyconfigs/p/PETSc/PETSc-3.22.0-foss-2024a.eb
> +version = '3.22.0'
@boegel I think it makes sense. It might be easier than updating this one.

2025-08-04 07:26 UTC, casparvl commented
Superseded by https://github.com/easybuilders/easybuild-easyconfigs/pull/23252

2025-08-04 07:26 UTC, closed without merging