fix the vectorization bug of `scipy-1.11.1`
easybuilders/easybuild-easyconfigs pull request #21693
Opened 2024-10-17 17:07 UTC by PetrKralCZ

(created using `eb --new-pr`)

2024-10-17 17:47 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-10-17 18:43 UTC, boegel requested changes

2024-10-17 18:43 UTC, boegel commented on easybuild/easyconfigs/s/SciPy-bundle/scipy-1.11.1_vectorization_error.patch
> +Fixes the vectorization bug. see https://github.com/scipy/scipy/issues/16792
@PetrKralCZ It's useful to mention the error that this patch fixes (to make it easier to find)
```
ValueError: buffer source array is read-only
```

Keep in mind that this implies updating the checksum for the patch file accordingly

2024-10-18 04:21 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-10-18 06:53 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3

2024-11-07 11:31 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
node3103.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/ff1e756aaa20207e06c47864e2bb787f for a full test report.

2024-11-07 15:19 UTC, boegel approved these changes

2024-11-07 15:19 UTC, boegel commented
Going in, thanks @PetrKralCZ!

2024-11-07 15:19 UTC, merged