{bio}[GCCcore/13.3.0] modkit v0.4.1
easybuilders/easybuild-easyconfigs pull request #21727
Opened 2024-10-23 09:23 UTC by pavelToman

(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/415

2024-10-23 09:24 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-10-24 12:05 UTC, boegel requested changes

2024-10-24 12:05 UTC, boegel commented on easybuild/easyconfigs/m/modkit/modkit-0.4.1-GCCcore-13.3.0.eb
> +    ('Rust', '1.78.0'),
@pavelToman To fix this:
```
Can't locate IPC/Cmd.pm in @INC
```
You'll need to add `Perl-bundle-CPAN` as a build dep

2024-10-24 15:27 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-10-29 10:07 UTC, laraPPr commented
Test report by @laraPPr
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in total)
node3101.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.11.3
See https://gist.github.com/laraPPr/33faf4e2a201f0363265c2297ecd9615 for a full test report.

2024-10-29 10:43 UTC, merged