{data}[foss/2022b] h5pyd v0.18.0
easybuilders/easybuild-easyconfigs pull request #21743
Opened 2024-10-24 14:33 UTC by zdemat

Adding new easyconfig for ```h5pyd``` - Python client library for HDF5 REST interface.

2024-11-29 09:55 UTC, zdemat commented
@Micket, easybuilders:develop was merged as requested. Sorry I missed the request long time ago.

2025-07-02 13:50 UTC, Crivella commented
Test report by @Crivella
**SUCCESS**
Build succeeded for 12 out of 12 (1 easyconfigs in total)
crivella-desktop - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 13th Gen Intel(R) Core(TM) i9-13900K (skylake), Python 3.11.13
See https://gist.github.com/Crivella/6640c6f99179de075047d0652911ca25 for a full test report.

2025-07-02 14:09 UTC, Crivella requested changes
- Removed unneeded options that will fail the CI
- Added sanity checks for the produced CLI scripts

2025-07-02 14:09 UTC, Crivella commented on easybuild/easyconfigs/h/h5pyd/h5pyd-0.18.0-foss-2022b.eb
> +moduleclass = 'data'
```suggestion
]

# CLI bins that are either interactive or return 1 on `--help`
local_bins_interactive = [
    'hsconfigure',
    'hsdiff',
    'hsload',
    'hsmv',
]
local_bins_noninteractive = [
    'hsacl',
    'hscopy',
    'hsrm',
    'hsget',
    'hsinfo',
    'hsls',
    'hstouch',
]

sanity_check_paths = {
    'files': [f'bin/{binname}' for binname in local_bins_noninteractive + local_bins_interactive],
    'dirs': ['bin', 'lib'],
}

sanity_check_commands = [f'{binname} --help' for binname in local_bins_noninteractive]

moduleclass = 'data'
```

2025-07-03 09:47 UTC, Crivella commented
Test report by @Crivella
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
crivella-desktop - Linux Ubuntu 22.04.5 LTS (Jammy Jellyfish), x86_64, 13th Gen Intel(R) Core(TM) i9-13900K (skylake), Python 3.11.13
See https://gist.github.com/Crivella/7a25a281ab92eb1d5a82f0a5771f2136 for a full test report.

2025-07-03 09:47 UTC, Crivella commented
@boegelbot please test @ jsc-zen3

2025-07-03 09:53 UTC, Crivella approved these changes
LGTM

2025-07-03 09:53 UTC, Crivella commented
Going in, thanks @zdemat!

2025-07-03 09:53 UTC, merged