{astro,lib}[foss/2023b] EveryBeam v0.6.1, WSClean v3.5
easybuilders/easybuild-easyconfigs pull request #21765
Opened 2024-10-29 22:00 UTC by casparvl

(created using `eb --new-pr`)

2024-11-11 15:13 UTC, casparvl commented
We're working towards using@boegelbot please test @ generoso this software in a pipeline, but this required upgrading WSClean.

2024-11-11 15:40 UTC, casparvl commented
@boegelbot please test @ generoso

2024-11-11 16:25 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 9.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.9.18
See https://gist.github.com/casparvl/234697d2cd9bffe5306ba59df8e39210 for a full test report.

2024-11-11 16:27 UTC, casparvl commented
@boegelbot please test @ generoso@boegelbot please test @ generoso

2024-11-20 14:25 UTC, casparvl commented
@boegelbot please test @ generoso

2025-01-22 15:33 UTC, casparvl commented
@boegelbot please test @ jsc-zen3

2025-01-22 16:26 UTC, casparvl commented
Test report by @casparvl
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
tcn1.local.snellius.surf.nl - Linux RHEL 9.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.9.18
See https://gist.github.com/casparvl/304bc9d315a9bc7dc1cd0f8d68ff8b01 for a full test report.

2025-01-22 16:39 UTC, boegel approved these changes
lgtm

2025-01-22 17:04 UTC, casparvl commented
FYI, also plenty of succesful builds in https://github.com/EESSI/software-layer/pull/877

2025-01-22 17:19 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 1 out of 6 (3 easyconfigs in total)
node3107.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/7856a34c996bae9fa169e203432961f0 for a full test report.

2025-01-22 18:17 UTC, boegel commented
@casparvl `wget --retry-connrefused ftp://anonymous@ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar ` fails because FTP is blocked on our system.

Is there any way we can avoid relying on `ftp://`?

Also, it would be great if we didn't rely on on-the-fly downloading durign the installation itself, so this file could be added to `sources` instead, and then copied when needed (that would make it OK-ish to have it downloaded over FTP, since then it'll be cached)

2025-01-22 20:11 UTC, casparvl commented
Wait, where does this get downloaded?

2025-01-22 20:18 UTC, casparvl commented
Ah, found it, in one of the deps https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/c/casacore/casacore-3.5.0-foss-2023b.eb

The official instructions say to get it from the FTP server, I have no idea if it would be available in any other way https://github.com/casacore/casacore?tab=readme-ov-file#obtaining-measures-data

Can the source step download from FTP? If so, we can definitely do that (would be better, also because then things like `--fetch` work properly). But then: how do we get this tarball to be extracted in desired location (`%(installdir)s/data` if I read the casacore easyconfig right)?

2025-01-22 20:50 UTC, casparvl commented
Fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/22201

2025-02-06 12:44 UTC, bedroge requested changes

2025-02-06 12:44 UTC, bedroge commented on easybuild/easyconfigs/e/EveryBeam/EveryBeam-0.6.1-foss-2023b.eb
> +# Note: we need to create a dir %(builddir)s/EveryBeam/everybeam for the pip install to complete succesfully
```suggestion
# Note: we need to create a dir %(builddir)s/EveryBeam/everybeam for the pip install to complete successfully
```

2025-02-06 12:44 UTC, bedroge commented on easybuild/easyconfigs/e/EveryBeam/EveryBeam-0.6.1-foss-2023b.eb
> +# Check if python support was build correctly, and can be found by pip
```suggestion
# Check if Python support was built correctly, and can be found by pip
```

2025-02-06 12:44 UTC, bedroge commented on test/easyconfigs/easyconfigs.py
> +            # Requires us to also bump DP3 version (to 6.2) and it's dependency on EveryBeam
```suggestion
            # Requires us to also bump DP3 version (to 6.2) and its dependency on EveryBeam
```

2025-02-06 12:44 UTC, bedroge commented on easybuild/easyconfigs/e/EveryBeam/EveryBeam-0.6.1-foss-2023b.eb
> +    '0f66d50b1f7944ad0d64898a0e54ee8b20dc9fb3ec0d15b4e1da30bda88688ab'  # EveryBeam-0.5.4_python_metadata.patch
```suggestion
    '63c42e85d1b63cbf5887d10ec158be9b69e2c63cf3b209e9c1944f46c01810ac'  # EveryBeam-0.5.4_python_metadata.patch
```
(required for fixing a typo)

2025-02-06 12:44 UTC, bedroge commented on easybuild/easyconfigs/e/EveryBeam/EveryBeam-0.5.4_python_metadata.patch
> +# Note that this patch require a directory 'everybeam' to be created in the builddir with
```suggestion
# Note that this patch requires a directory 'everybeam' to be created in the builddir with
```

2025-02-06 15:58 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.10, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.6.8
See https://gist.github.com/bedroge/2b30318d27ee524db05318988e83ddae for a full test report.

2025-02-06 16:36 UTC, bedroge commented
Test report by @bedroge
Using easyblocks from PR(s) https://github.com/easybuilders/easybuild-easyblocks/pull/3463
**FAILED**
Build succeeded for 4 out of 5 (3 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 24.04.1 LTS (Noble Numbat), x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.12.3
See https://gist.github.com/bedroge/c2469aa66a2a2330874f371c92680f45 for a full test report.

2025-02-06 19:07 UTC, bedroge commented
@boegelbot please test @ jsc-zen3

2025-02-06 19:33 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
interactive1 - Linux Rocky Linux 8.10, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.6.8
See https://gist.github.com/bedroge/2f94d8790b9d357f76399f625f0eebd6 for a full test report.

2025-02-06 19:56 UTC, bedroge approved these changes
Looks good to me!

2025-02-06 20:05 UTC, merged