{bio}[GCC/13.2.0] DRAGMAP v1.3.0
easybuilders/easybuild-easyconfigs pull request #21838
Opened 2024-11-12 17:31 UTC by sassy-crick

(created using `eb --new-pr`)

2024-11-12 19:26 UTC, sassy-crick commented
@boegelbot please test @ generoso

2025-04-16 10:30 UTC, sassy-crick commented
Test report by @sassy-crick
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
hp - Linux Debian GNU/Linux 12, x86_64, 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Python 3.11.2
See https://gist.github.com/sassy-crick/0e2b87b23bc5e7b4bee18d2f2e6e349c for a full test report.

2025-04-16 10:48 UTC, sassy-crick commented
@boegelbot please test @ jsc-zen3

2025-06-16 11:34 UTC, akesandgren commented on easybuild/easyconfigs/d/DRAGMAP/DRAGMAP-1.3.0-GCC-13.2.0.eb
> +skipsteps = ['configure']
@sassy-crick  It would probably make sense to keep the
```
-prebuildopts = 'sed -i "s|-msse4.2 -mavx2|$CXXFLAGS|g" config.mk &&'
```
line from previous version of this since it's the same version

2025-06-23 17:20 UTC, sassy-crick commented on easybuild/easyconfigs/d/DRAGMAP/DRAGMAP-1.3.0-GCC-13.2.0.eb
> +skipsteps = ['configure']
I think you are right. I added that line again, after my local re-build worked.

2025-06-23 17:34 UTC, sassy-crick commented
@boegelbot please test @ jsc-zen3

2025-06-24 08:49 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
b-cn1611.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 555.58.02, Python 3.10.12
See https://gist.github.com/akesandgren/e9886ed839f0ff957f42340ba11aa24e for a full test report.

2025-06-24 08:54 UTC, akesandgren requested changes

2025-06-24 08:54 UTC, akesandgren commented on easybuild/easyconfigs/d/DRAGMAP/DRAGMAP-1.3.0-GCC-13.2.0.eb
> +# #include <cstdint> added to deal with 'uint64_t' problem
This comment doesn't really need to be here, it's evident from the patch file.
I think you should remove it

2025-06-24 09:14 UTC, sassy-crick commented on easybuild/easyconfigs/d/DRAGMAP/DRAGMAP-1.3.0-GCC-13.2.0.eb
> +# #include <cstdint> added to deal with 'uint64_t' problem
True. My idea was people might have a look first in the EasyConfig file, before they look into the patch file which contains that comment. That said, I have removed it as suggested.

2025-06-24 10:42 UTC, akesandgren approved these changes
LGTM

2025-06-24 10:46 UTC, akesandgren commented
Going in, thanks @sassy-crick!

2025-06-24 10:46 UTC, merged