{lib}[foss/2023b] synthcity v0.2.11, pycodestyle v2.11.1, python-igraph v0.11.8, ... w/ PyTorch 2.1.2, llvmlite, ...
easybuilders/easybuild-easyconfigs pull request #21845
Opened 2024-11-13 10:23 UTC by pavelToman

(created using `eb --new-pr`)

2024-12-11 09:53 UTC, boegel commented on easybuild/easyconfigs/m/MONAI/MONAI-1.4.0-foss-2023b-minimal.eb
> +versionsuffix = '-minimal'
@pavelToman Can you check if this is still useful, since there's also a PR for full MONAI now in #21937 ?

2025-01-02 11:21 UTC, pavelToman commented on easybuild/easyconfigs/m/MONAI/MONAI-1.4.0-foss-2023b-minimal.eb
> +versionsuffix = '-minimal'
MONAI-minimal was replaced by MONAI full version

2025-01-14 21:09 UTC, boegel commented
@pavelToman This PR needs MONAI from #21937, but MONAI needs several easyconfigs from this PR:
```
Missing dependencies: Pillow-SIMD/10.4.0-foss-2023b, Pillow-SIMD/10.4.0-GCCcore-13.2.0, tensorboard/2.18.0-foss-2023b, torchvision/0.17.0-foss-2023b (no easyconfig file or existing module found)
```

I think you'll need to open a new PR with these, so we can unblock the MONAI PR?

2025-01-15 16:25 UTC, pavelToman commented
> @pavelToman This PR needs MONAI from #21937, but MONAI needs several easyconfigs from this PR:
> 
> ```
> Missing dependencies: Pillow-SIMD/10.4.0-foss-2023b, Pillow-SIMD/10.4.0-GCCcore-13.2.0, tensorboard/2.18.0-foss-2023b, torchvision/0.17.0-foss-2023b (no easyconfig file or existing module found)
> ```
> 
> I think you'll need to open a new PR with these, so we can unblock the MONAI PR?

Created https://github.com/easybuilders/easybuild-easyconfigs/pull/22160

2025-01-23 12:44 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 22 out of 22 (17 easyconfigs in total)
node3113.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.9.18
See https://gist.github.com/pavelToman/d8d6d70983fefdc44ea1889ced4a16cf for a full test report.

2025-01-24 10:40 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2025-01-24 21:06 UTC, pavelToman commented
Test report by @pavelToman
**FAILED**
Build succeeded for 16 out of 17 (17 easyconfigs in total)
node4002.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/6a0b5ac0f7c6006825030a8164d0d0d2 for a full test report.

2025-01-27 12:24 UTC, pavelToman commented
> Test report by @boegelbot **FAILED** Build succeeded for 16 out of 17 (17 easyconfigs in total) jsczen3c1.int.jsc-zen3.fz-juelich.de - Linux Rocky Linux 9.5, x86_64, AMD EPYC-Milan Processor (zen3), Python 3.9.21 See https://gist.github.com/boegelbot/d4d5a3dfbee7f572d90b33e2646511c8 for a full test report.

```
FAILED plugins/privacy/test_decaf.py::test_plugin_generate[test_plugin0] - Ru...
FAILED plugins/privacy/test_decaf.py::test_plugin_generate[test_plugin1] - Ru...
FAILED plugins/privacy/test_decaf.py::test_plugin_generate[test_plugin2] - Ru...
FAILED plugins/privacy/test_decaf.py::test_get_dag[d-struct] - RuntimeError: ...
```
Need to investigate, but from a first look it seems it is cpu problem - on Intel it passes, but on AMD it fails. Gonna try it on shinx.

2025-01-27 13:37 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 17 out of 17 (17 easyconfigs in total)
node3129.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.9.18
See https://gist.github.com/pavelToman/1d4ca944217a3368f74062b46087d30c for a full test report.

2025-01-27 18:08 UTC, pavelToman commented
Test report by @pavelToman
**FAILED**
Build succeeded for 16 out of 17 (17 easyconfigs in total)
node4012.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/33909de7505e2622bc41f640c3e620d7 for a full test report.

2025-01-28 09:44 UTC, boegel commented
@pavelToman The failing `test_decaf.py` tests are probably because of the Slurm environment issue we also saw in #21141

We have a workaround for that in the `synhcity` easyconfig:
```python
# solve problem with PyTorch-Lightning _validate_srun_variables method
# see https://github.com/easybuilders/easybuild-easyconfigs/pull/21141#issuecomment-2318854045
local_pretestopts += "export SLURM_NTASKS_PER_NODE=$SLURM_NTASKS && "
```

2025-01-28 10:33 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2025-01-28 13:41 UTC, pavelToman commented
Test report by @pavelToman
**FAILED**
Build succeeded for 20 out of 23 (17 easyconfigs in total)
node4234.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.9.18
See https://gist.github.com/pavelToman/e4df3955e7efbf67498765f499e4b031 for a full test report.

2025-01-28 18:27 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 17 out of 17 (17 easyconfigs in total)
node4012.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/4112e805f1576b80286b15d8dd416a42 for a full test report.

2025-02-18 20:09 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 17 out of 17 (17 easyconfigs in total)
node4006.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/bb4027429df3e7a1ed113c66c71eaf32 for a full test report.

2025-02-19 04:13 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 24 out of 24 (17 easyconfigs in total)
node3100.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/ff0730b5dc91aebf5e8b20a275d4bce6 for a full test report.

2025-02-23 09:59 UTC, boegel requested changes

2025-02-23 09:59 UTC, boegel commented on easybuild/easyconfigs/t/torchtext/torchtext-0.16.2-foss-2023b-PyTorch-2.1.2.eb
> +sanity_pip_check = True,
not sure what the trailing commas are doing here, works by accident, so let's get rid of them
```suggestion
download_dep_fail = True
use_pip = True
sanity_pip_check = True

2025-02-23 10:04 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3171.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/ddc1322cb0d497ecfac75f4b2e612659 for a full test report.

2025-02-23 12:06 UTC, boegel approved these changes

2025-02-23 12:09 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3171.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/1f0157547c749ce889e9d12d31fa8ec6 for a full test report.

2025-02-23 15:47 UTC, boegel commented
Going in, thanks @pavelToman!

2025-02-23 15:47 UTC, merged