{lang}[GCCcore/12.3.0] juliaup v1.17.9
easybuilders/easybuild-easyconfigs pull request #21895
Opened 2024-11-21 16:49 UTC by pavelToman

(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/358

2024-11-21 16:50 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-11-21 16:58 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4001.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/b6b80f8f47793690b7954ee07353c64d for a full test report.

2024-11-21 17:09 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4204.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.9.18
See https://gist.github.com/pavelToman/dae52d9e187a3d3980de235a2dd6400a for a full test report.

2024-12-07 16:15 UTC, boegel requested changes

2024-12-07 16:15 UTC, boegel commented on easybuild/easyconfigs/j/juliaup/juliaup-1.17.9-GCCcore-12.3.0.eb
> +sources = []
```suggestion
sources = []
```

2024-12-07 16:24 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3105.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/d0530ec5e3fa317f7c20e71659461f16 for a full test report.

2024-12-09 09:04 UTC, pavelToman commented
Test report by @pavelToman
**FAILED**
Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3113.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.9.18
See https://gist.github.com/pavelToman/a1ec09f06ed44951dc2f628da609ea08 for a full test report.

2024-12-09 09:38 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-12-09 09:47 UTC, pavelToman commented
> Test report by @boegel **FAILED** Build succeeded for 0 out of 1 (1 easyconfigs in total) node3105.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18 See https://gist.github.com/boegel/d0530ec5e3fa317f7c20e71659461f16 for a full test report.

It seems that their test `command_initial_setup_from_launcher_test` is broken - it expects to download ` Julia 1.11.1` but it downloads `Julia 1.11.2`. 
Since their own pipelines for this test are failing: https://github.com/JuliaLang/juliaup/commits/v1.17.9/tests/command_initial_setup_from_launcher_test.rs
I will update test to count with `Julia 1.11`

2024-12-09 09:54 UTC, pavelToman commented
Problem reported: https://github.com/JuliaLang/juliaup/issues/1122

2024-12-09 10:07 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-12-09 10:07 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3113.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.9.18
See https://gist.github.com/pavelToman/4420512e20c100bac5de797279ca6a83 for a full test report.

2024-12-09 10:16 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4012.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/e03edc116334242e18dd8df1cc072070 for a full test report.

2024-12-09 10:21 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-12-20 12:39 UTC, laraPPr commented
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3127.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.11.3
See https://gist.github.com/laraPPr/53ea82317e7cc125a75875d3210cfcbf for a full test report.

2024-12-20 12:41 UTC, laraPPr commented
Test report by @laraPPr
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3536.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.11.3
See https://gist.github.com/laraPPr/31e638f984ad38b9d14e5f2623d4f377 for a full test report.

2024-12-20 13:16 UTC, laraPPr approved these changes
lgtm

2024-12-20 13:28 UTC, laraPPr commented
All requested changes made

2024-12-20 13:30 UTC, laraPPr commented
Going in, thanks @pavelToman!

2024-12-20 13:30 UTC, merged