{lib}[GCC/13.2.0,GCCcore/13.2.0,intel-compilers/2023.2.1] Fortran-stdlib v0.7.0, fypp v3.2
easybuilders/easybuild-easyconfigs pull request #21904
Opened 2024-11-23 16:40 UTC by SimonPinches

(created using `eb --new-pr`)

2024-11-23 18:27 UTC, jfgrimm commented
@boegelbot: please test @ generoso

2026-04-08 10:53 UTC, akesandgren requested changes

2026-04-08 10:53 UTC, akesandgren commented on easybuild/easyconfigs/f/Fortran-stdlib/Fortran-stdlib-0.7.0-GCC-13.2.0.eb
> +toolchainopts = {}  # toolchain options, e.g. opt, pic, usempi, optarch, ...
Drop this since it's empty

2026-04-08 10:53 UTC, akesandgren commented on easybuild/easyconfigs/f/fypp/fypp-3.2-GCCcore-13.2.0.eb
> +sanity_pip_check = True
Drop these since they are the default

2026-04-08 10:53 UTC, akesandgren commented on easybuild/easyconfigs/f/Fortran-stdlib/Fortran-stdlib-0.7.0-intel-compilers-2023.2.1.eb
> +configopts = '-DBUILD_SHARED_LIBS=on '
Use build_shared_libs=True instead of this.

2026-04-08 10:53 UTC, akesandgren commented on easybuild/easyconfigs/f/Fortran-stdlib/Fortran-stdlib-0.7.0-GCC-13.2.0.eb
> +configopts = '-DBUILD_SHARED_LIBS=on '
Use build_shared_libs=True instead of this.

2026-04-08 10:53 UTC, akesandgren commented on easybuild/easyconfigs/f/Fortran-stdlib/Fortran-stdlib-0.7.0-intel-compilers-2023.2.1.eb
> +    'files': ['include/fortran_stdlib/Intel-2021.10.0.20230609/stdlib_version.mod',
This is a weird path that would need to be manually specified to the compiler to be found.
It should be moved to just include/fortran_stdlib or more likely just include if we want other packages to find it automatically.

2026-04-08 10:53 UTC, akesandgren commented on easybuild/easyconfigs/f/Fortran-stdlib/Fortran-stdlib-0.7.0-intel-compilers-2023.2.1.eb
> +    'dirs': ['include', 'lib', 'share'],
include and lib can be dropped since they are implicit by the files directive

2026-04-08 10:53 UTC, akesandgren commented on easybuild/easyconfigs/f/Fortran-stdlib/Fortran-stdlib-0.7.0-GCC-13.2.0.eb
> +    'dirs': ['include', 'lib', 'share'],
See comment in the intel version

2026-08-20 08:24 UTC, SimonPinches commented
Thanks for your comments @akesandgren, they should now all be addressed.

2026-08-20 11:46 UTC, akesandgren commented
Test report by @akesandgren
**SUCCESS**
Build succeeded for 3 out of 3 (total: 9 mins 55 secs) (3 easyconfigs in total)
b-cn1611.hpc2n.umu.se - Linux Ubuntu 22.04, x86_64, AMD EPYC 7313 16-Core Processor, 1 x NVIDIA NVIDIA A100 80GB PCIe, 580.173.02, Python 3.10.12
See https://gist.github.com/akesandgren/6c8c8b942641316eb9af9f3218736871 for a full test report.

2026-08-20 11:50 UTC, akesandgren approved these changes
LGTM

2026-08-20 11:51 UTC, akesandgren commented
Going in, thanks @SimonPinches!

2026-08-20 11:51 UTC, merged