{data,devel,tools}[GCCcore/13.2.0] ITK v5.4.0, CastXML v0.6.10, SWIG v4.3.0
easybuilders/easybuild-easyconfigs pull request #21931
Opened 2024-11-28 17:15 UTC by pavelToman

(created using `eb --new-pr`)

2024-11-28 17:16 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-11-28 18:38 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-12-02 14:48 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node4007.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/17306dc4c40129c8741330f96a8bfb97 for a full test report.

2024-12-02 19:56 UTC, pavelToman commented
Test report by @pavelToman
**FAILED**
Build succeeded for 1 out of 4 (3 easyconfigs in total)
node4221.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.9.18
See https://gist.github.com/pavelToman/af6946d8800266a407f62bb5a5d3756c for a full test report.

2025-01-08 09:48 UTC, boegel requested changes

2025-01-08 11:57 UTC, boegel approved these changes

2025-01-08 18:20 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3170.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/7b1a1f7f2ff3e0d9c28b74413de42f8f for a full test report.

2025-01-09 07:29 UTC, boegel commented
Going in, thanks @pavelToman!

2025-01-09 07:29 UTC, merged

2025-01-27 14:23 UTC, pavelToman commented
Test report by @pavelToman
**FAILED**
Build succeeded for 2 out of 3 (3 easyconfigs in total)
node4206.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.9.18
See https://gist.github.com/pavelToman/9184d9cc0af67cde7e2367d512bfe798 for a full test report.

2025-01-27 20:47 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
node4206.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.9.18
See https://gist.github.com/pavelToman/4535f379e6ce20e69877548699b4e95a for a full test report.