{vis}[GCCcore/13.2.0,foss/2023b,gfbf/2023b] MONAI v1.4.0, PyAMG v5.2.1, zarr v2.18.3, ...
easybuilders/easybuild-easyconfigs pull request #21937
Opened 2024-11-29 11:14 UTC by pavelToman

(created using `eb --new-pr`)

2025-01-22 12:18 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2025-01-22 13:21 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2025-01-22 14:01 UTC, boegel commented
Test report by @boegel
**FAILED**
Build succeeded for 21 out of 24 (13 easyconfigs in total)
node3107.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/5aca06f870a021213dbb2e8bdc5bc542 for a full test report.

2025-01-22 16:02 UTC, boegel commented
@pavelToman Next to the problem with OpenSlide, there's also a download problem for MONAI itself:
```
Couldn't find file MONAI-1.4.0.tar.gz anywhere, and downloading it didn't work either
```

2025-01-22 17:40 UTC, pavelToman commented
`../openslide-4.0.0/src/openslide-private.h:388:40: error: error__use__openslide_fclose_instead undeclared here (not in a function)`
Seems related: https://github.com/openslide/openslide/issues/429

2025-01-22 18:34 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2025-01-22 21:05 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 46 out of 46 (13 easyconfigs in total)
node3100.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.9.18
See https://gist.github.com/pavelToman/f73ac7ca150126b62297e609d98259a5 for a full test report.

2025-01-27 13:26 UTC, pavelToman commented
Test report by @pavelToman
**FAILED**
Build succeeded for 20 out of 22 (13 easyconfigs in total)
node4206.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.9.18
See https://gist.github.com/pavelToman/9d19a8f5d2c3e4324ec0e4148f9ca0e2 for a full test report.

2025-01-28 09:21 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 13 out of 13 (13 easyconfigs in total)
node4234.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.9.18
See https://gist.github.com/pavelToman/fc188d08c404e20287710cd5d50aaee6 for a full test report.

2025-01-28 10:52 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 13 out of 13 (13 easyconfigs in total)
node4012.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/83c996d97df7c7944aff72cdf1aac629 for a full test report.

2025-01-28 11:09 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 13 out of 13 (13 easyconfigs in total)
node3139.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/88984bd319b3e6a2ccc212c0b156c5d4 for a full test report.

2025-02-18 10:26 UTC, boegel requested changes

2025-02-18 10:43 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3100.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/9a6ec233a54f1e3474029a1e89169c86 for a full test report.

2025-02-18 10:47 UTC, boegel approved these changes
lgtm

2025-02-18 10:47 UTC, boegel commented on easybuild/easyconfigs/o/OpenSlide/OpenSlide-4.0.0-GCCcore-13.2.0.eb
> +
```suggestion
}

```

2025-02-18 11:51 UTC, boegel commented
Going in, thanks @pavelToman!

2025-02-18 11:51 UTC, merged