{bio,vis}[foss/2023a] CellProfiler v4.2.8, wxPython v4.2.1
easybuilders/easybuild-easyconfigs pull request #21949
Opened 2024-12-02 10:25 UTC by WilleBell

(created using `eb --new-pr`)

2024-12-19 10:55 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 4 out of 4 (2 easyconfigs in total)
node4011.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/a09572c4757b619bb3dd288f5fae4182 for a full test report.

2025-01-15 17:23 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2025-01-17 11:28 UTC, pavelToman commented
Test report by @pavelToman
**FAILED**
Build succeeded for 2 out of 4 (2 easyconfigs in total)
node4202.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.9.18
See https://gist.github.com/pavelToman/e250e3653d3436884d45083d96ae9ed3 for a full test report.

2025-01-17 12:48 UTC, pavelToman commented
Test report by @pavelToman
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
node4237.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.9.18
See https://gist.github.com/pavelToman/305f1d966ec66746eb015df05c526a2c for a full test report.

2025-01-22 23:26 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3107.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/5cdc810139b17fc2ce409ed3d9b582c7 for a full test report.

2025-01-23 10:34 UTC, pavelToman commented
Test report by @pavelToman
**FAILED**
Build succeeded for 0 out of 2 (2 easyconfigs in total)
node4208.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.9.18
See https://gist.github.com/pavelToman/7f9ea68e19846a4cc49541cdf9ea3fd1 for a full test report.

2025-01-23 11:45 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2025-01-23 11:56 UTC, boegel commented
@pavelToman Seems like this is quite memory-hungry, indeed...

My attempt on skitty was with 18 cores and ~85GB of RAM available.

On shinx with 8 cores you only get ~15GB of RAM, which is apparently not enough to build `wxPython`...

2025-01-23 13:13 UTC, boegel requested changes

2025-01-23 13:13 UTC, boegel commented on easybuild/easyconfigs/c/CellProfiler/CellProfiler-4.2.8-foss-2023a.eb
> +    ('Java', '11', '', True),
use `SYSTEM` constant (to fix CI):
```suggestion
    ('Java', '11', '', SYSTEM),
```

2025-01-23 13:13 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2025-01-24 07:41 UTC, boegel approved these changes
lgtm

2025-01-24 07:41 UTC, boegel commented
Going in, thanks @WilleBell!

2025-01-24 07:41 UTC, merged