{bio}[foss/2023a] BindCraft v1.1.0 w/ CUDA 12.1.1
easybuilders/easybuild-easyconfigs pull request #21958
Opened 2024-12-03 11:21 UTC by PetrKralCZ

(created using `eb --new-pr`)

2024-12-03 11:49 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-12-03 11:49 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-12-03 13:34 UTC, boegel requested changes

2024-12-03 13:34 UTC, boegel commented on easybuild/easyconfigs/b/BindCraft/BindCraft-1.1.0-foss-2023a-CUDA-12.1.1.eb
> +    ('hatchling', '1.18.0'),
Make this a build-only dependency

2024-12-16 13:00 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-12-17 05:27 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3-a100

2024-12-17 21:14 UTC, boegel commented
Going in, thanks @PetrKralCZ!

2024-12-17 21:14 UTC, merged