{bio}[foss/2023a] InterOp v1.3.2
easybuilders/easybuild-easyconfigs pull request #21961
Opened 2024-12-03 12:49 UTC by PetrKralCZ

(created using `eb --new-pr`)

2024-12-03 14:20 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-12-04 05:21 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3

2025-01-07 08:55 UTC, boegel commented
@PetrKralCZ Can you clarify why this is still a draft PR?

2025-01-24 13:23 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3

2025-01-28 09:15 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2025-01-31 13:20 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3

2025-01-31 13:34 UTC, PetrKralCZ commented
Test report by @PetrKralCZ
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4010.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/PetrKralCZ/e234a03624c0a7afda6509c4b7fac98b for a full test report.

2025-02-12 09:44 UTC, boegel requested changes

2025-02-12 09:44 UTC, boegel commented on easybuild/easyconfigs/i/InterOp/InterOp-1.3.2-foss-2023a.eb
> +local_change_home = 'export HOME=%(builddir)s/home && '
@PetrKralCZ Can you add a comment to clarify why this is done (not to make a mess in home dir essentially)

2025-02-12 20:55 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3106.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/0bfe2036644c66f985d0ca57af345df9 for a full test report.

2025-02-12 21:32 UTC, boegel requested changes

2025-02-12 21:32 UTC, boegel commented on easybuild/easyconfigs/i/InterOp/InterOp-1.3.2-foss-2023a.eb
> +local_change_home = 'export HOME=%(builddir)s/home && '
```suggestion
# avoid messing around in hidden subdirectory .nuget of real home directory
local_change_home = 'export HOME=%(builddir)s/home && '
```

2025-02-12 21:33 UTC, boegel approved these changes

2025-02-13 07:01 UTC, merged