add collection of easyconfig templates organized per generation
easybuilders/easybuild-easyconfigs pull request #21984
Opened 2024-12-06 10:17 UTC by lexming

The goal of this collection of easyconfigs templates is to provide examples that more ready to be used than the default `TEMPLATE.eb`. Having templates for common types of easyconfigs per generation has the advantage that many parameters can already be set in the template, such as versions of dependencies. This avoids wasting time looking up for that information every time a new easyconfig needs to be created.

We generally have two types of templates per type of easyconfig, the _minimal_ one and the _complete_ one. The reason is that some people prefer to delete stuff from the template, while others prefer to start small and add stuff to it.

2025-01-14 10:32 UTC, smoors commented on contrib/easyconfig-templates/2023a/PythonBundle-scipy.eb.tmpl
> +# Template for a python bundle using SciPy-bundle on 2023a
can we add the toolchain name and version to the file name?

2025-01-14 10:32 UTC, smoors commented on contrib/easyconfig-templates/2023a/PythonBundle-scipy.eb.tmpl
> +        'checksums': ['0000000000000000000000000000000000000000000000000000000000000000'],
usually checksums are added with `--inject-checksums` so this is not really needed

2025-01-14 10:32 UTC, smoors commented on contrib/easyconfig-templates/2023a/PythonBundle-scipy.eb.tmpl
> +    ('name-lower', 'ext_version', {
can we add a comment here that 'name-lower' should be the name used on PyPI, i.e. the name you use when you `pip install` it?

also, 'ext_version' can be replaced with `version`

2025-01-29 10:00 UTC, boegel requested changes

2025-01-29 10:00 UTC, boegel commented on contrib/easyconfig-templates/2022a/PythonBundle-scipy.eb.tmpl
> +use_pip = True
@lexming This is enabled by default in EasyBuild 5.0.0, so this line should be removed

2025-01-30 11:22 UTC, verdurin commented on contrib/easyconfig-templates/2022a/Bundle-common-components.eb.tmpl
> +Description in 80 chars long column
I thought the informal rule was keep to around 100 characters for description?

2025-01-30 11:22 UTC, verdurin commented on contrib/easyconfig-templates/2022a/Bundle-common-components.eb.tmpl
> +    "comp2 -h",
I think it would be useful to include the pattern where you need to grab the result of stderror from the command, which is quite common.

2025-02-03 09:53 UTC, Thyre commented
Do we need to add these EasyConfigs to the filtered ones in the test suite?
https://github.com/easybuilders/easybuild-easyconfigs/blob/b5baa0528782e82ac5fe14ce690a172b4b572f95/test/easyconfigs/easyconfigs.py#L222

2025-02-10 12:09 UTC, verdurin commented
Would be useful to have templates for binary/tarball ECs too.

2025-03-08 19:19 UTC, lexming commented on contrib/easyconfig-templates/2023a/PythonBundle-scipy.eb.tmpl
> +# Template for a python bundle using SciPy-bundle on 2023a
I thought about this, but it is very messy because the names of the templates still need to have some description of what type of installation they cover. And mixing both results in very long filenames that are difficult to read.

Moreover, since the template has to be renamed in any case, there is little gain by already having the toolchain in the filename.

2025-03-08 19:19 UTC, lexming commented on contrib/easyconfig-templates/2023a/PythonBundle-scipy.eb.tmpl
> +        'checksums': ['0000000000000000000000000000000000000000000000000000000000000000'],
right, fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/21984/commits/42561bba065f26f74df737580b21abc6f09ed92f

2025-03-08 19:21 UTC, lexming commented on contrib/easyconfig-templates/2023a/PythonBundle-scipy.eb.tmpl
> +    ('name-lower', 'ext_version', {
We decided that we don't want comments in templates because they will probably stay in the final easyconfig.

So I tried to make this more clear without comments in https://github.com/easybuilders/easybuild-easyconfigs/pull/21984/commits/e43ce3d12109acce8aeaaffab5b194515bdaaa05

2025-03-08 19:21 UTC, lexming commented on contrib/easyconfig-templates/2022a/PythonBundle-scipy.eb.tmpl
> +use_pip = True
Fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/21984/commits/40cff25e1d5e98997b285b45520ee5c980b2133d

2025-03-08 19:22 UTC, lexming commented on contrib/easyconfig-templates/2022a/Bundle-common-components.eb.tmpl
> +Description in 80 chars long column
I prefer 80 because that is easier to read in the final module file. 100 characters is a rather long line.

Moreover, 80 is the default in `vi` to cut text in columns.

2025-03-08 19:22 UTC, lexming commented on contrib/easyconfig-templates/2022a/Bundle-common-components.eb.tmpl
> +    "comp2 -h",
sure, added those in https://github.com/easybuilders/easybuild-easyconfigs/pull/21984/commits/c9c090497809baa09ea2e6725dc935b7c7bba397

2025-03-08 19:24 UTC, lexming commented
@Thyre those can indeed be removed, done in https://github.com/easybuilders/easybuild-easyconfigs/pull/21984/commits/ff1e21cbf23ca1e79044811cccb786dde2c8191d

@verdurin added templates for Tarballs in https://github.com/easybuilders/easybuild-easyconfigs/pull/21984/commits/bbf9699a09684d89b81e307ba17a240760cce0d3 and (Packed)Binary in https://github.com/easybuilders/easybuild-easyconfigs/pull/21984/commits/28270ef15205b266bf9d4bd5b9d31de53142593e

2025-03-09 08:05 UTC, branfosj approved these changes

2025-03-09 08:05 UTC, merged