{perf}[gfbf/2023a] HolisticTraceAnalysis v0.2.0
easybuilders/easybuild-easyconfigs pull request #21987
Opened 2024-12-06 15:20 UTC by VRehnberg

(created using `eb --new-pr`)

2024-12-06 15:43 UTC, VRehnberg commented
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-icelake-build - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Silver 4316 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/VRehnberg/9163034617c0214797c2a09ffa39f614 for a full test report.

2024-12-06 15:47 UTC, VRehnberg commented
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis2-01 - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz, 2 x NVIDIA Tesla T4, 560.35.03, Python 3.6.8
See https://gist.github.com/VRehnberg/3140ef8dab24245bb5cb178e76c1817c for a full test report.

2024-12-06 15:57 UTC, VRehnberg commented
Test report by @VRehnberg
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
alvis-icelake-build - Linux Rocky Linux 8.9, x86_64, Intel(R) Xeon(R) Silver 4316 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/VRehnberg/56fa19ed37325573c75e7da7463d08bd for a full test report.

2024-12-17 14:22 UTC, lcniel approved these changes
Looks good to me.

2025-02-04 14:34 UTC, akesandgren requested changes

2025-02-04 16:08 UTC, akesandgren commented
@boegelbot Please test @ jsc-zen3

2025-02-05 06:22 UTC, akesandgren approved these changes
LGTM

2025-02-05 06:22 UTC, merged