{bio}[GCCcore/12.3.0,foss/2023a] scNanoGPS v1.1, LIQA v1.3.4, lifelines v0.28.0, ... w/ Perl 5.36.1
easybuilders/easybuild-easyconfigs pull request #22033
Opened 2024-12-16 11:59 UTC by pavelToman

(created using `eb --new-pr`)

2024-12-16 12:31 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 7 out of 7 (6 easyconfigs in total)
node4202.shinx.os - Linux RHEL 9.4, x86_64, AMD EPYC 9654 96-Core Processor, Python 3.9.18
See https://gist.github.com/pavelToman/08505e461b36694afcccc9d64a3a5651 for a full test report.

2024-12-16 15:00 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node4003.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/0a9bf3eca7baa1c20eec9170504a08be for a full test report.

2025-01-08 09:59 UTC, boegel requested changes

2025-01-08 09:59 UTC, boegel commented on easybuild/easyconfigs/l/LIQA/LIQA-1.3.4-foss-2023a.eb
> +options = {'modulename': '%(namelower)s_src'}
```suggestion
options = {'modulename': 'liqa_src'}

2025-01-08 09:59 UTC, boegel commented on easybuild/easyconfigs/s/scNanoGPS/scNanoGPS-1.1-foss-2023a.eb
> +    # Optional - load 'annovar/20200607-GCCcore-12.3.0-Perl-5.36.1' to make 'reporter_SNV.py' work
let's just add `annovar` as a dependency here
```suggestion
    ('annovar', '20200607'),
```

If this is a blocker for people who can't obtain the sources for `annovar`, they can always use `eb --filter-deps annovar` as an escape hatch...

2025-01-08 09:59 UTC, boegel commented on easybuild/easyconfigs/s/scNanoGPS/scNanoGPS-1.1-foss-2023a.eb
> +"""
```suggestion
```

2025-01-08 10:01 UTC, boegel requested changes

2025-01-08 10:01 UTC, boegel commented on easybuild/easyconfigs/a/annovar/annovar-20200607-GCCcore-12.3.0-Perl-5.36.1.eb
> +# rename after download to %(name)s-%(version)s.tar.gz
```suggestion
download_instructions = """
Registration required for download
via http://www.openbioinformatics.org/annovar/annovar_download_form.php
rename after download to '%(name)s-%(version)s.tar.gz'
"""

2025-01-08 10:48 UTC, boegel commented
@boegelbot please test @ generoso

2025-01-08 11:57 UTC, boegel requested changes

2025-01-08 11:57 UTC, boegel commented on easybuild/easyconfigs/a/annovar/annovar-20200607-GCCcore-12.3.0.eb
> +rename after download to '%(name)s-%(version)s.tar.gz'
Using templates in `download_instructions` results in failure in easyconfigs test suite, so let's just hardcode the version then...
```suggestion
rename after download to 'annovar-20200607.tar.gz'
```

2025-01-08 11:57 UTC, boegel commented
@boegelbot please test @ jsc-zen3

2025-01-09 07:34 UTC, boegel approved these changes

2025-01-09 07:50 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3103.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/9d37e364caf31eba26c9041039405efc for a full test report.

2025-01-14 15:42 UTC, merged