{bio}[foss/2023a] chewBBACA v3.3.10
easybuilders/easybuild-easyconfigs pull request #22038
Opened 2024-12-16 17:42 UTC by pavelToman

(created using `eb --new-pr`)
resolves https://github.com/vscentrum/vsc-software-stack/issues/473

2024-12-16 17:43 UTC, pavelToman commented
@boegelbot please test @ generoso

2024-12-16 17:51 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-12-16 17:52 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4004.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/67c897ff6a7161be17bec8b0538d1b8a for a full test report.

2024-12-17 10:03 UTC, pavelToman commented
@boegelbot please test @ jsc-zen3

2024-12-17 10:10 UTC, pavelToman commented
Test report by @pavelToman
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4004.donphan.os - Linux RHEL 8.8, x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz, 1 x NVIDIA NVIDIA A2, 545.23.08, Python 3.6.8
See https://gist.github.com/pavelToman/f99de8a66d586f5446c2e0184f9ae9bc for a full test report.

2024-12-17 10:17 UTC, pavelToman commented
@boegelbot please test @ generoso

2025-01-08 09:44 UTC, boegel requested changes

2025-01-08 09:44 UTC, boegel commented on easybuild/easyconfigs/c/chewBBACA/chewBBACA-3.3.10-foss-2023a.eb
> +)
let's make this a bit more generic:

```suggestion
local_preinstallopts = "sed -i -e 's/numpy~=/numpy>=/g' -e 's/scipy~=/scipy>=/g' pyproject.toml && "

2025-01-08 09:48 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3170.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/69404b04569a5db636b76aff93dc84db for a full test report.

2025-01-08 10:16 UTC, merged