{bio}[foss/2023a] FastK v1.1.0
easybuilders/easybuild-easyconfigs pull request #22065
Opened 2024-12-19 14:09 UTC by PetrKralCZ

(created using `eb --new-pr`)

2024-12-19 15:16 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-12-19 16:02 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2024-12-19 16:16 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3

2025-01-06 10:57 UTC, boegel requested changes

2025-01-06 10:57 UTC, boegel commented on easybuild/easyconfigs/f/FastK/FastK-1.1.0-foss-2023a.eb
> +toolchain = {'name': 'foss', 'version': '2023a'}
@PetrKralCZ It looks like `GCC` toolchain is sufficient here, so please change?

2025-01-06 11:16 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2025-01-06 11:49 UTC, PetrKralCZ commented
@boegelbot please test @ generoso

2025-01-06 11:52 UTC, PetrKralCZ commented
@boegelbot please test @ jsc-zen3

2025-01-06 13:18 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3170.skitty.os - Linux RHEL 9.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.9.18
See https://gist.github.com/boegel/b9aba59a9720f8371c22c84d9893bd48 for a full test report.

2025-01-06 13:36 UTC, boegel commented
Going in, thanks @PetrKralCZ!

2025-01-06 13:36 UTC, merged