Add easyconfig gmsh-4.12.2-foss-2023b.eb and some dependencies
easybuilders/easybuild-easyconfigs pull request #22084
Opened 2024-12-20 16:25 UTC by julianmorillo

Easyconfigs added in this PR:
```
easybuild/easyconfigs/g/gmsh/gmsh-4.12.2-foss-2023b.eb
easybuild/easyconfigs/o/occt/occt-7.8.0-GCCcore-13.2.0.eb
easybuild/easyconfigs/p/PETSc/PETSc-3.20.3-foss-2023b.eb
easybuild/easyconfigs/s/SLEPc/SLEPc-3.20.1-foss-2023b.eb
easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-7.1.0-foss-2023b.eb
```

2024-12-23 10:21 UTC, julianmorillo commented
Needs PR #22077 to pass the tests

2025-02-27 12:51 UTC, Flamefire commented
https://github.com/easybuilders/easybuild-easyconfigs/pull/20568 has a newer PETSc. Maybe use that?

2025-02-28 16:23 UTC, Flamefire requested changes

2025-02-28 16:23 UTC, Flamefire commented on easybuild/easyconfigs/g/gmsh/gmsh-4.12.2-foss-2023b.eb
> +easyblock = 'CMakeMake'
```suggestion
easyblock = 'CMakePythonPackage'
```

2025-02-28 16:23 UTC, Flamefire commented on easybuild/easyconfigs/g/gmsh/gmsh-4.12.2-foss-2023b.eb
> +
This will be done by CMakePythonPackage and take user settings for that into account

2025-02-28 21:14 UTC, gkaf89 commented on easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-7.1.0-foss-2023b.eb
> +name = 'SuiteSparse'
The version with METIS is included, `SuiteSparse-7.7.0-foss-2023b-METIS-5.1.0.eb`, which should be more performant.

2025-03-03 11:15 UTC, Flamefire requested changes
2 corrections of my previous suggestions. Can you also remove the SuiteSparse file please?

2025-03-03 11:15 UTC, Flamefire commented on easybuild/easyconfigs/p/PETSc/PETSc-3.20.3-foss-2023b.eb
> +    ('SuiteSparse', '7.7.0'),
As suggested the METIS variant is better. Sorry for the confusion.
```suggestion
    ('SuiteSparse', '7.7.0', '-METIS-5.1.0'),
```

2025-03-03 11:15 UTC, Flamefire commented on easybuild/easyconfigs/g/gmsh/gmsh-4.12.2-foss-2023b.eb
> +easyblock = 'CMakePythonPackage'
Sorry I misunderstood the added PYTHONPATH. This doesn't install a Python package but just a single file.

```suggestion
easyblock = 'CMakeMake'
```

2025-03-03 15:39 UTC, Flamefire commented
Test report by @Flamefire
**FAILED**
Build succeeded for 4 out of 5 (5 easyconfigs in total)
i8021 - Linux Rocky Linux 8.9 (Green Obsidian), x86_64, AMD EPYC 7352 24-Core Processor (zen2), 8 x NVIDIA NVIDIA A100-SXM4-40GB, 555.42.06, Python 3.8.17
See https://gist.github.com/Flamefire/615cc64a16e26e46245bf7d9be96ffc4 for a full test report.

2025-03-03 16:07 UTC, gkaf89 commented
We are encountering an issue with SLEPc. After running the `configure` command manually it reports the required build command, which is:
```
make SLEPC_DIR=/the/path/to/$EBROOTSLEPC PETSC_DIR=/the/path/to/$EBROOTPETSC
``` 

With the easyconfig, the command called is simply `make` and it fails. Maybe the easyblock should be modified?

2025-03-03 16:16 UTC, Flamefire commented
Both variables are set as environment variables, PETSC_DIR by the module and SLEPC_DIR by the easyblock. The latter points to the source directory, not the install directory (that doesn't exist at that point). Is that maybe the issue?    
I haven't seen any issue on both test installs I did

2025-03-03 16:29 UTC, gkaf89 commented
> The end of the EB configure says:
> 
> ```
>  Configure stage complete. Now build the SLEPc library with:
>    make SLEPC_DIR=/dev/shm/s3248973-EasyBuild610218/SLEPc/3.20.1/foss-2023b/slepc-3.20.1 PETSC_DIR=/data/horse/ws/s3248973-EasyBuild/easybuild-rome/software/PETSc/3.20.3-foss-2023b
> ```

You are correct, I misread the paths, `PETSC_DIR` point to the configuration directory. This is the exact error we are getting:
```
== 2025-03-03 15:46:09,323 run.py:503 INFO Running shell command 'make' in /tmp/easybuild/aion/2023b/epyc/build/SLEPc/3.20.1/foss-2023b/slepc-3.20.1
== 2025-03-03 15:46:09,511 run.py:618 INFO Output of 'make ...' shell command (stdout + stderr):
/tmp/easybuild/aion/2023b/epyc/build/SLEPc/3.20.1/foss-2023b/slepc-3.20.1/lib/slepc/conf/slepc_rules:14: /tmp/easybuild/aion/2023b/epyc/build/SLEPc/3.20.1/foss-2023b/slepc-3.20.1/installed-arch-linux2-c-opt/lib/slepc/conf/slepcrules: No such file or directory
gmake[1]: *** No rule to make target '/tmp/easybuild/aion/2023b/epyc/build/SLEPc/3.20.1/foss-2023b/slepc-3.20.1/installed-arch-linux2-c-opt/lib/slepc/conf/slepcrules'.  Stop.
/tmp/easybuild/aion/2023b/epyc/build/SLEPc/3.20.1/foss-2023b/slepc-3.20.1/lib/slepc/conf/slepc_variables:58: /tmp/easybuild/aion/2023b/epyc/build/SLEPc/3.20.1/foss-2023b/slepc-3.20.1/installed-arch-linux2-c-opt/lib/slepc/conf/slepcvariables: No such file or directory
make: *** [GNUmakefile:12: /tmp/easybuild/aion/2023b/epyc/build/SLEPc/3.20.1/foss-2023b/slepc-3.20.1/installed-arch-linux2-c-opt/lib/slepc/conf/slepcvariables] Error 2
```

We are building with v5.0.0beta1 at the moment. I will dig a little bit to find out what it going wrong.

2025-03-04 04:29 UTC, Flamefire commented
Test report by @Flamefire
**SUCCESS**
Build succeeded for 8 out of 8 (5 easyconfigs in total)
n1607 - Linux RHEL 8.9 (Ootpa), x86_64, Intel(R) Xeon(R) Platinum 8470 (icelake), Python 3.8.17
See https://gist.github.com/Flamefire/c75e5758c2f89bf9d49b7d21e850bffc for a full test report.

2025-03-04 08:24 UTC, Flamefire commented
> /tmp/easybuild/aion/2023b/epyc/build/SLEPc/3.20.1/foss-2023b/slepc-3.20.1/lib/slepc/conf/slepc_rules:14: /tmp/easybuild/aion/2023b/epyc/build/SLEPc/3.20.1/foss-2023b/slepc-3.20.1/installed-arch-linux2-c-opt/lib/slepc/conf/slepcrules: No such file or directory

It is missing an ARM folder for a build on EPYC, do I read that right? And this does work when you pass the install folder as `SLEPC_DIR` instead of the source folder?

2025-03-06 16:36 UTC, Flamefire commented
Assuming PETSc and SLEPc build processes are similar enough I opened a PR to pass SLEPC_DIR & PETSC_DIR to the `make` of SLEPc to mirror what we do for PETSc. Can you test if that resolves the issue for you: https://github.com/easybuilders/easybuild-easyblocks/pull/3656

2025-03-17 12:04 UTC, Flamefire commented
Test report by @Flamefire
**FAILED**
Build succeeded for 15 out of 16 (16 easyconfigs in total)
i7008 - Linux Rocky Linux 8.9 (Green Obsidian), x86_64, AMD EPYC 7702 64-Core Processor (zen2), Python 3.8.17
See https://gist.github.com/Flamefire/8e87174bc9222f4480ba683673e0f914 for a full test report.

2025-04-04 08:22 UTC, boegel commented on easybuild/easyconfigs/p/PETSc/PETSc-3.20.3-foss-2023b.eb
> +version = '3.20.3'
@julianmorillo Any reason you're sticking to 3.20.x here, rather than 3.22.x (which is being contributed through #22696)?

(maybe 3.22.x wasn't available yet, I didn't check that)

2025-04-04 08:40 UTC, julianmorillo commented on easybuild/easyconfigs/p/PETSc/PETSc-3.20.3-foss-2023b.eb
> +version = '3.20.3'
@boegel , No special reason at all. Probably it was that wasn't available yet, as you mention, or simply that I didn't checked. I''ve just pushed a commit upgrading to 3.22.3.

2025-04-04 12:19 UTC, Flamefire commented on easybuild/easyconfigs/p/PETSc/PETSc-3.20.3-foss-2023b.eb
> +version = '3.20.3'
IIRC that was the case. See my [comment](https://github.com/easybuilders/easybuild-easyconfigs/pull/20568#issuecomment-2688365964) There is a bug in 3.21 so 3.20 had to be used. And another reason

> However I think we should use [3.20] for 2023b. 3.20.3 is the last release of 2023 to stay with the toolchain year. 3.21.2 is already from 29th May 2024.

Just FYI, I guess no reason to change it back now.

2025-06-16 11:21 UTC, bedroge commented on easybuild/easyconfigs/g/gmsh/gmsh-4.12.2-foss-2023b.eb
> +    ('PETSc', '3.22.3'),
Ultimately this was bumped to 3.22.5 in https://github.com/easybuilders/easybuild-easyconfigs/pull/22696, so we should bump it here too
```suggestion
    ('PETSc', '3.22.5'),
```

2025-06-16 11:22 UTC, bedroge commented on easybuild/easyconfigs/p/PETSc/PETSc-3.20.3-foss-2023b.eb
> +version = '3.20.3'
#22696 got merged, so I guess we can completely remove this easyconfig from the PR now?

2025-06-16 11:26 UTC, bedroge commented on easybuild/easyconfigs/s/SLEPc/SLEPc-3.20.1-foss-2023b.eb
> +dependencies = [('PETSc', '3.20.3')]
This should also depend on the merged 3.22.5 easyconfig:
```suggestion
dependencies = [('PETSc', '3.22.5')]
```

And I don't know how PETSc / SLEPc work together (they have slightly similar version numbers), but maybe SLEPc itself should then also be bumped to 3.22?

2025-06-16 11:26 UTC, bedroge commented on easybuild/easyconfigs/s/SLEPc/SLEPc-3.20.1-foss-2023b.eb
> +dependencies = [('PETSc', '3.20.3')]
Latest 3.22 version of SLEPc is 3.22.2

2025-06-16 11:28 UTC, julianmorillo commented on easybuild/easyconfigs/p/PETSc/PETSc-3.20.3-foss-2023b.eb
> +version = '3.20.3'
Yes, sure

2025-06-16 13:14 UTC, julianmorillo commented on easybuild/easyconfigs/s/SLEPc/SLEPc-3.20.1-foss-2023b.eb
> +dependencies = [('PETSc', '3.20.3')]
Ok, let's bump SLEPc also (to 3.22.2)

2025-06-16 13:22 UTC, julianmorillo commented on easybuild/easyconfigs/s/SLEPc/SLEPc-3.20.1-foss-2023b.eb
> +dependencies = [('PETSc', '3.20.3')]
Ok, done, bumped SLEPc to version 3.22.2

2025-06-17 07:30 UTC, bedroge commented on easybuild/easyconfigs/g/gmsh/gmsh-4.12.2-foss-2023b.eb
> +    ('SLEPc', '3.20.1'),
```suggestion
    ('SLEPc', '3.22.2'),
```

2025-06-17 07:45 UTC, bedroge commented
@boegelbot please test @ jsc-zen3

2025-06-18 07:57 UTC, bedroge commented on easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-7.1.0-foss-2023b.eb
> +name = 'SuiteSparse'
@julianmorillo I think this file can be removed now?

2025-06-18 08:20 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 4 out of 4 (4 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 24.04.2 LTS (Noble Numbat), x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.12.3
See https://gist.github.com/bedroge/974f7105924a21d86c4452926ee06d55 for a full test report.

2025-06-18 09:32 UTC, julianmorillo commented on easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-7.1.0-foss-2023b.eb
> +name = 'SuiteSparse'
Yes, I already removed it.

2025-06-18 11:10 UTC, bedroge commented
@boegelbot please test @ jsc-zen3

2025-06-18 12:56 UTC, bedroge commented
Test report by @bedroge
**SUCCESS**
Build succeeded for 3 out of 3 (3 easyconfigs in total)
bob-Latitude-5300 - Linux Ubuntu 24.04.2 LTS (Noble Numbat), x86_64, Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, Python 3.12.3
See https://gist.github.com/bedroge/762109d25727a2cb84b43b6890523b3f for a full test report.

2025-06-18 17:43 UTC, bedroge commented
Going in, thanks @julianmorillo!

2025-06-18 17:43 UTC, merged