{lang} [intel/2018a] PyCUDA v2017.1.1 and Boost v1.67
easybuilders/easybuild-easyconfigs pull request #6483
Opened 2018-06-20 14:48 UTC by SimonPinches

2018-06-21 08:59 UTC, boegel requested changes

2018-06-21 08:59 UTC, boegel commented on easybuild/easyconfigs/p/PyCUDA/PyCUDA-2017.1.1-intel-2018a-Python-2.7.14.eb
> +    ('Boost', '1.67.0', versionsuffix),
@SimonPinches For easyconfigs using a `2018a` toolchain, we should stick to `Boost` 1.66.0` for now, to ensure that this module is compatible with others that depend on `Boost` (cfr. failing test)...

2019-05-08 14:42 UTC, vanzod commented
@SimonPinches I would recommend replacing the `Boost-1.66.0-Python-2.7.14` dependency with two separate dependencies as follows if the `Boost` Python bindings are needed:
```
('Boost', '1.66.0'),
('Boost.Python', '1.66.0', versionsuffix)
```

2019-05-08 16:15 UTC, boegel commented
@vanzod Actually, just `Boost.Python` is enough (since `Boost` is a dep for `Boost.Python`).

I'll fix that in a bit...

2019-05-08 16:30 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node3102.skitty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 2.7.5
See https://gist.github.com/6d6d52d1cc931da1c402a925c1cb6f71 for a full test report.

2019-05-08 16:33 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 1 out of 1 (1 easyconfigs in this PR)
node2006.delcatty.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/2400379ecc2d8b94f3378d0171dc82b0 for a full test report.

2019-05-08 16:33 UTC, boegel approved these changes

2019-05-08 16:53 UTC, vanzod commented
Test report by @vanzod
**SUCCESS**
Build succeeded for 2 out of 2 (1 easyconfigs in this PR)
cermis - Linux debian 9.9, Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz, Python 2.7.13
See https://gist.github.com/a301984c23945d79fa420e80052bb6b0 for a full test report.

2019-05-08 16:54 UTC, boegel commented
Going in, thanks @SimonPinches!

2019-05-08 16:54 UTC, merged

2019-05-08 16:55 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 3 out of 3 (1 easyconfigs in this PR)
node2434.golett.os - Linux centos linux 7.6.1810, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, Python 2.7.5
See https://gist.github.com/949c044b10156da98a20007695fa9bcb for a full test report.