{bio}[foss/2018a] Minimac4 1.0.0 and libStatGen
easybuilders/easybuild-easyconfigs pull request #7982
Opened 2019-03-31 10:18 UTC by branfosj

fixes #7981

2019-03-31 11:09 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in this PR)
bber0501u03a.bb2.cluster - Linux centos linux 7.5.1804, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz, Python 2.7.5
See https://gist.github.com/6b36f6f44401b7c459fdf868644771bd for a full test report.

2020-10-31 16:06 UTC, boegel commented
@branfosj Is it worth updating this to try and get it merged?

Needs another sync with `develop`, and perhaps a bit more love to make the tests happy...

2020-10-31 16:08 UTC, boegel requested changes

2020-10-31 16:08 UTC, boegel commented on easybuild/easyconfigs/l/libStatGen/libStatGen-457bf9e-foss-2018a.eb
> +version = '457bf9e'
@branfosj This should be changed to a datestamp `20190330`?

2020-10-31 16:08 UTC, boegel commented on easybuild/easyconfigs/l/libStatGen/libStatGen-457bf9e-foss-2018a.eb
> +sources = ['%s.tar.gz' % fullhash]
@branfosj Use `download_file` here to download via commit ID and rename after download?
See https://easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html#alternative-formats-for-sources

2020-11-01 10:23 UTC, branfosj commented
> @branfosj Is it worth updating this to try and get it merged?
> 
> Needs another sync with `develop`, and perhaps a bit more love to make the tests happy...

I've updated it.

2020-11-01 10:27 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/3c11d25a4e30b16fa00e94e1a4db9ead for a full test report.

2020-11-01 10:55 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/2f3ac24e871fc3f7063021086ad1733d for a full test report.

2020-11-01 12:26 UTC, branfosj commented
Test report by @branfosj
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
bber0501u03a.bb2.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/593543add0924575993a6755c307b9e1 for a full test report.

2020-11-01 14:28 UTC, boegel commented
Test report by @boegel
**SUCCESS**
Build succeeded for 2 out of 2 (2 easyconfigs in total)
node2424.golett.os - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (haswell), Python 2.7.5
See https://gist.github.com/f493c50ca686095a2df79159505f787d for a full test report.

2020-11-01 14:53 UTC, boegel approved these changes

2020-11-01 14:54 UTC, boegel commented
Going in, thanks @branfosj!

2020-11-01 14:54 UTC, merged